000
WTPZ32 KNHC 030530
TCPEP2
 
BULLETIN
Tropical Storm Lorena Intermediate Advisory Number 5A
NWS National Hurricane Center Miami FL       EP122025
1100 PM MST Tue Sep 02 2025
 
...LORENA STRENGTHENING AND EXPECTED TO BECOME A HURRICANE DURING 
THE NEXT SEVERAL HOURS...
 
 
SUMMARY OF 1100 PM MST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.7N 110.0W
ABOUT 155 MI...250 KM S OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* West Coast of Baja California Sur from Cabo San Lucas northward
to Cabo San Lazaro
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere on the Baja California peninsula and in
southwestern Mexico should monitor the progress of Lorena.
Additional watches or warnings may be required on Wednesday.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM MST (0600 UTC), the center of Tropical Storm Lorena was
located near latitude 20.7 North, longitude 110.0 West. Lorena is
moving toward the northwest near 14 mph (22 km/h), and this motion 
with a decrease in forward speed is expected through early Thursday. 
A generally slow northward motion is expected to begin by late 
Thursday and continue into late Friday.  On the forecast track, the 
center of Lorena is expected to move parallel to the west coast of 
the Baja California peninsula on Wednesday and Thursday and then 
could approach the coast on Friday.
 
Maximum sustained winds have increased to near 70 mph (110 km/h) 
with higher gusts.  Rapid strengthening is forecast during the next 
day or so, and Lorena is likely to become a hurricane during the 
next several hours. Fast weakening is expected to begin on 
Thursday, and Lorena could be back to tropical storm status by 
early Friday.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 994 mb (29.36 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall are expected to begin impacting
Baja California Sur by Wednesday and southwestern Sonora by
Thursday, with this rainfall potentially persisting through Friday.
Rainfall totals of 5 to 10 inches, with maximum amounts of 15
inches, are possible across portions of Baja California Sur through
Friday.  Significant flash flooding is a possibility.
 
Within the moisture surge ahead of Lorena, 1 to 2 inches of rain,
with localized totals to 4 inches, are expected from the northwest
Mexico states of Colima to Sinaloa northward into Arizona through
Friday, bringing the potential for isolated to scattered pockets of
flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Tropical Storm Lorena, please see the National
Weather Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch area
on Wednesday and Thursday.
 
SURF:  Swells generated by Lorena will affect portions of the west
coast of Baja California Sur beginning tonight and continuing
through Friday.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Beven
  