975 
WTPZ32 KNHC 030853
TCPEP2
 
BULLETIN
Hurricane Lorena Advisory Number   6
NWS National Hurricane Center Miami FL       EP122025
200 AM MST Wed Sep 03 2025
 
...LORENA BECOMES A HURRICANE...
...NEW WARNINGS AND WATCHES ISSUED FOR BAJA CALIFORNIA SUR...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...21.2N 110.4W
ABOUT 120 MI...195 KM SSW OF CABO SAN LUCAS MEXICO
ABOUT 275 MI...445 KM SSE OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Government of Mexico has issued a Tropical Storm Warning for
the west coast of Baja California Sur from Santa Fe to Cabo San
Lazaro, and a Tropical Storm Watch for the coast of Baja California
Sur north of Cabo San Lazaro to Punta Abreojos.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* West Coast of Baja California Sur from Santa Fe to Cabo San
Lazaro.
 
A Tropical Storm Watch is in effect for...
* West Coast of Baja California Sur from Cabo San Lucas northward
to Santa Fe.
* West Coast of Baja California Sur from Cabo San Lazaro northward
to Punta Abreojos.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere on the Baja California peninsula and in
northwestern Mexico should monitor the progress of Lorena.
Additional watches or warnings may be required later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Hurricane Lorena was located
near latitude 21.2 North, longitude 110.4 West. Lorena is moving
toward the northwest near 14 mph (22 km/h), and this motion with a 
decrease in forward speed is expected through early Thursday.
A generally slow northward motion is expected to begin by late
Thursday and continue into late Friday.  On the forecast track, the
center of Lorena is expected to move parallel to the west coast of
the Baja California peninsula today and Thursday and then approach
the coast Thursday night and Friday.
 
Maximum sustained winds have increased to near 75 mph (120 km/h)
with higher gusts.  Rapid strengthening is forecast through
tonight. Fast weakening is expected to begin on Thursday, and
Lorena could weaken back to a tropical storm by Friday.
 
Hurricane-force winds extend outward up to 10 miles (20 km) from the
center and tropical-storm-force winds extend outward up to 60 miles
(95 km).
 
The estimated minimum central pressure is 990 mb (29.24 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and move into southeastern Baja California and
southwestern Sonora by Thursday, with this rainfall potentially
persisting through Friday.  Rainfall totals of 5 to 10 inches, with
maximum amounts of 15 inches, are possible across portions of Baja
California Sur and far southeast Baja California through Friday.
This will bring the risk of life-threatening flash floods and
mudslides, especially in areas of higher terrain.
 
Within the moisture surge ahead of Lorena, 1 to 3 inches of rain,
with localized totals to 4 inches, is expected from the northwest
Mexico states of Sinaloa and Sonora northward into Arizona through
Friday, bringing the potential for isolated to scattered flash
flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Tropical Storm Lorena, please see the National
Weather Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected in the warning area
tonight and Thursday. Tropical storm conditions are possible within
the watch area south of Santa Fe later today through Thursday, and
in the watch area north of Cabo San Lazaro Thursday and Thursday
night.
 
SURF:  Swells generated by Lorena will affect portions of the west
coast of Baja California Sur beginning this morning and continuing
through Friday.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 500 AM MST.
Next complete advisory at 800 AM MST.
 
$$
Forecaster Beven
  