000
WTPZ32 KNHC 031454
TCPEP2
 
BULLETIN
Hurricane Lorena Advisory Number   7
NWS National Hurricane Center Miami FL       EP122025
800 AM MST Wed Sep 03 2025
 
...LORENA CONTINUES TO STRENGTHEN...
...HEAVY RAINFALL AND LIFE-THREATENING FLASH FLOODING SPREADING
NORTHWARD ACROSS BAJA CALIFORNIA SUR...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 111.6W
ABOUT 115 MI...185 KM WSW OF CABO SAN LUCAS MEXICO
ABOUT 180 MI...285 KM SSE OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has extended the Tropical Storm Warning
northward along the west coast of Baja California Sur from Cabo San
Lazaro to Punta Abreojos.
 
The government of Mexico has issued a Tropical Storm Watch along the
west coast of Baja California Sur from north of Punta Abreojos to
Punta Eugenia.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* West Coast of Baja California Sur from Santa Fe to Punta Abreojos
 
A Tropical Storm Watch is in effect for...
* West Coast of Baja California Sur from Cabo San Lucas northward
to Santa Fe.
* West Coast of Baja California Sur from north of Punta Abreojos to
Punta Eugenia
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
Interests elsewhere on the Baja California peninsula and in
northwestern Mexico should monitor the progress of Lorena.
Additional watches or warnings may be required later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Hurricane Lorena was located
near latitude 22.3 North, longitude 111.6 West. Lorena is moving
toward the northwest near 16 mph (26 km/h), and this motion with a
decrease in forward speed is expected through early Thursday. A
generally slow northward motion is expected late Thursday and early
Friday, with a gradual turn toward the northeast by late Friday. On
the forecast track, the center of Lorena is expected to move
parallel to the west coast of the Baja California peninsula through
tonight and then approach the coast late Thursday through Friday.
 
Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts.  Rapid strengthening is forecast to continue through this 
evening.  Fast weakening is expected to begin on Thursday, and 
Lorena could weaken back to a tropical storm by Friday.
 
Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).
 
The estimated minimum central pressure is 988 mb (29.18 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and move into southeastern Baja California and
southwestern Sonora by Thursday, with this rainfall potentially
persisting through Friday.  Rainfall totals of 5 to 10 inches, with
maximum amounts of 15 inches, are possible across portions of Baja
California Sur, far southeast Baja California and southwestern
Sonora through Friday. This will bring the risk of life-threatening
flash floods and mudslides, especially in areas of higher terrain.
 
Within the moisture surge ahead of Lorena, 1 to 3 inches of rain,
with localized totals up to 4 inches, are expected from the Mexico
states of Sinaloa northward into Arizona through Friday, bringing
the potential for isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Lorena, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected in the warning area
beginning tonight, and spreading northward within the warning area
in Baja California Sur through Thursday and into Friday. Tropical
storm conditions are possible within the watch area south of Santa
Fe through tonight, and in the watch area north of Punta Abreojos
Thursday night and early Friday.
 
SURF:  Swells generated by Lorena will continue affecting portions
of the south and west coasts of Baja California Sur through Friday.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1100 AM MST.
Next complete advisory at 200 PM MST.
 
$$
Forecaster Hagen
  