000
WTPZ32 KNHC 032339
TCPEP2
 
BULLETIN
Hurricane Lorena Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       EP122025
500 PM MST Wed Sep 03 2025
 
...LORENA MOVING A LITTLE SLOWER TOWARD THE NORTHWEST...
...LIFE-THREATENING FLASH FLOODING EXPECTED ACROSS BAJA CALIFORNIA 
SUR AND SOUTHWESTERN SONORA...
 
 
SUMMARY OF 500 PM MST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...23.1N 112.9W
ABOUT 125 MI...200 KM SSW OF CABO SAN LAZARO MEXICO
ABOUT 190 MI...310 KM W OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* West Coast of Baja California Sur from Santa Fe to Punta Eugenia
 
A Tropical Storm Watch is in effect for...
* West Coast of Baja California Sur from Todos Santos northward
to Santa Fe.
* East Coast of the Baja California peninsula from Santa Rosalia to
Bahia de los Angeles
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area within 48 hours.
 
Interests elsewhere on the Baja California peninsula and in
northwestern Mexico should monitor the progress of Lorena.
Additional watches or warnings may be required tonight or on
Thursday.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM MST (0000 UTC), the center of Hurricane Lorena was located
near latitude 23.1 North, longitude 112.9 West.  Lorena is moving
toward the northwest near 12 mph (19 km/h), and this motion with an 
additional decrease in forward speed is expected through early 
Thursday.  A generally slow northward motion is expected late 
Thursday and Thursday night, with a gradual turn toward the 
northeast on Friday.  On the forecast track, the center of Lorena is 
expected to move parallel to the west coast of the Baja California 
peninsula through tonight, approach the coast of Baja California Sur 
Thursday night, and move inland over the Baja California peninsula 
on Friday.
 
Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts.  Some strengthening is possible through this evening.
Fast weakening is expected to begin on Thursday, and Lorena is
expected to weaken to a tropical storm by Friday morning.
 
Hurricane-force winds extend outward up to 15 miles (30 km) from
the center and tropical-storm-force winds extend outward up to 80
miles (130 km).
 
The estimated minimum central pressure is 985 mb (29.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and move into southwestern Sonora by Thursday, with
this rainfall potentially persisting through Friday.  Rainfall
totals of 5 to 10 inches, with maximum amounts of 15 inches, are
possible across portions of Baja California Sur and southwestern
Sonora through Friday. This will bring the risk of life-threatening
flash floods and mudslides, especially in areas of higher terrain.
 
Farther northeast, 1 to 3 inches of rain, with localized totals up
to 5 inches, are expected from portions of the Mexico states of
Sinaloa north and northeast into portions of Arizona and southern
New Mexico through Saturday afternoon, bringing the potential for
isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Hurricane Lorena, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected in the warning area
beginning tonight and will spread northward within the warning
area in Baja California Sur through Thursday and into Friday.
Tropical storm conditions are possible within the watch area south
of Santa Fe through tonight, and in the watch area on the east coast
of the Baja California peninsula Friday into Friday night.
 
STORM SURGE:  Coastal flooding from storm surge is likely along the
coast of Baja California Sur near and to the right of where Lorena
makes landfall.
 
SURF:  Swells generated by Lorena will continue affecting portions
of the south and west coasts of Baja California Sur through Friday.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Berg
  