000
WTPZ32 KNHC 040544
TCPEP2
 
BULLETIN
Hurricane Lorena Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP122025
1100 PM MST Wed Sep 03 2025
 
...LORENA EXPECTED TO WEAKEN QUICKLY ON THURSDAY AND FRIDAY...
...RISK OF LIFE-THREATENING FLASH FLOODING CONTINUES FOR BAJA
CALIFORNIA SUR AND SOUTHWESTERN SONORA...
 
 
SUMMARY OF 1100 PM MST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...23.7N 113.6W
ABOUT 110 MI...180 KM SW OF CABO SAN LAZARO MEXICO
ABOUT 240 MI...390 KM WNW OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...981 MB...28.97 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Government of Mexico has discontinued the Tropical Storm Watch
for the west coast of Baja California Sur from Todos Santos
northward to Santa Fe.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* West Coast of Baja California Sur from Santa Fe to Punta Eugenia
 
A Tropical Storm Watch is in effect for...
* East Coast of the Baja California peninsula from Santa Rosalia to
Bahia de los Angeles
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area within 48 hours.
 
Interests elsewhere on the Baja California peninsula and in
northwestern Mexico should monitor the progress of Lorena.
Additional watches or warnings may be required tonight or on
Thursday.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM MST (0600 UTC), the center of Hurricane Lorena was
located near latitude 23.7 North, longitude 113.6 West. Lorena is
moving toward the northwest near 10 mph (17 km/h), and this motion 
with a decrease in forward speed is expected through early 
Thursday. A slow northward or north-northeastward motion is 
expected to begin on Thursday and continue into the weekend.  On 
the forecast track, the center of Lorena is expected to move 
parallel to the west coast of the Baja California peninsula through 
Thursday, approach the coast of Baja California Sur Thursday night, 
and move inland over the Baja California peninsula on Friday.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Lorena is expected to begin weakening quickly and become a 
tropical storm on Thursday.  Lorena is likely to degenerate into a 
remnant low near or over the Baja California peninsula by early 
Saturday.
 
Hurricane-force winds extend outward up to 15 miles (30 km) from
the center and tropical-storm-force winds extend outward up to 80
miles (130 km).
 
The estimated minimum central pressure is 981 mb (28.97 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and move into southwestern Sonora by Thursday, with
this rainfall potentially persisting through Friday.  Additional
rainfall totals of 4 to 8 inches, with maximum storm total amounts
of 15 inches, are possible across portions of Baja California Sur,
far southeast Baja California and southwestern Sonora into Friday.
This will bring the risk of life-threatening flash floods and
mudslides, especially in areas of higher terrain.
 
Farther northeast, 1 to 3 inches of rain, with localized totals up
to 5 inches, are expected from portions of the Mexican state of
Sinaloa north and northeast into portions of southeast Arizona and
southwest New Mexico through Saturday, bringing the potential for
isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Hurricane Lorena, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected in the warning area
beginning tonight and will spread northward within the warning
area in Baja California Sur through Thursday and into Friday.
Tropical storm conditions are possible within the watch area on the
east coast of the Baja California peninsula late Friday into Friday
night.
 
STORM SURGE:  Coastal flooding from storm surge is likely along the
coast of Baja California Sur near and to the right of where Lorena
makes landfall.
 
SURF:  Swells generated by Lorena will continue affecting portions
of the south and west coasts of Baja California Sur through Friday.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Beven
  