000
WTPZ32 KNHC 041742
TCPEP2
 
BULLETIN
Tropical Storm Lorena Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       EP122025
1100 AM MST Thu Sep 04 2025
 
...RISK OF LIFE-THREATENING FLASH FLOODING CONTINUES FOR BAJA
CALIFORNIA SUR AND SOUTHWESTERN SONORA...
 
 
SUMMARY OF 1100 AM MST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.4N 114.5W
ABOUT 140 MI...225 KM W OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* West Coast of Baja California Sur from Puerto Cortes to Punta
Eugenia
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
Interests elsewhere on the Baja California peninsula and in
northwestern Mexico should monitor the progress of Lorena.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM MST (1800 UTC), the center of Tropical Storm Lorena was
located near latitude 24.4 North, longitude 114.5 West. Lorena is
moving toward the northwest near 7 mph (11 km/h). A turn toward the 
north and a decrease in forward speed is expected tonight. On the 
forecast track, the center of Lorena is expected to move generally 
parallel to the west coast of the Baja California peninsula through 
tonight, and could move closer to the west-central coast of the 
Baja California peninsula while it weakens on Friday.
 
Maximum sustained winds have decreased to near 60 mph (95 km/h) 
with higher gusts. Lorena is expected to quickly weaken for the next 
couple of days, and it is forecast to degenerate into a remnant low 
near or to the west of the Baja California peninsula by Friday 
night.
 
Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.
 
The estimated minimum central pressure is 997 mb (29.44 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and Sonora Mexico through Friday. Additional rainfall
totals of 4 to 8 inches, with maximum storm total amounts of 15
inches, are possible across portions of Baja California Sur, far
southeast Baja California and southwestern Sonora into Friday. This
will bring the risk of life-threatening flash floods and mudslides,
especially in areas of higher terrain.
 
Elsewhere across Mexico, 2 to 4 inches of rain, with isolated totals
up to 6 inches, are expected across the remainder of Sonora and
northern Sinaloa. These amounts will lead to isolated to scattered
instances of flash flooding.
 
Across the southwestern United States, 1 to 3 inches of rain, with
isolated totals up to 5 inches, are expected across portions of
Arizona and New Mexico through Saturday, bringing the potential for
isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Hurricane Lorena, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
WIND:  Tropical storm conditions, mainly in gusts, are expected
somewhere within the warning area in Baja California Sur today
through Friday.
 
SURF:  Swells generated by Lorena will continue affecting portions
of the south and west coasts of Baja California Sur through Friday.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Hagen
  