750 
WTPZ32 KNHC 042033
TCPEP2
 
BULLETIN
Tropical Storm Lorena Advisory Number  12
NWS National Hurricane Center Miami FL       EP122025
200 PM MST Thu Sep 04 2025
 
...RISK OF LIFE-THREATENING FLASH FLOODING CONTINUES FOR BAJA
CALIFORNIA SUR AND SOUTHWESTERN SONORA...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...24.6N 114.8W
ABOUT 155 MI...255 KM W OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has discontinued all warnings.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect.
 
Interests on the Baja California peninsula and in northwestern
Mexico should monitor the progress of Lorena.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Tropical Storm Lorena was
located near latitude 24.6 North, longitude 114.8 West. Lorena is
moving toward the northwest near 7 mph (11 km/h). A turn toward the
north and a decrease in forward speed are expected tonight. On the
forecast track, the center of Lorena is expected to move generally
parallel to the west coast of the Baja California peninsula while 
it weakens on Friday.
 
Recent satellite-derived wind data and data from an Air Force 
Reserve reconnaissance aircraft indicate that maximum sustained 
winds have decreased to near 50 mph (85 km/h) with higher gusts. 
Lorena is expected to quickly weaken for the next couple of days, 
and it is forecast to degenerate into a remnant low on Friday over 
water, to the west of the Baja California peninsula.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The minimum central pressure, based on data from Air Force Reserve 
reconnaissance aircraft is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and Sonora Mexico through Friday. Additional rainfall
totals of 4 to 8 inches, with maximum storm total amounts of 15
inches, are possible across portions of Baja California Sur, far
southeast Baja California and southwestern Sonora into Friday. This
will bring the risk of life-threatening flash floods and mudslides,
especially in areas of higher terrain.
 
Elsewhere across Mexico, 2 to 4 inches of rain, with isolated totals
up to 6 inches, are expected across the remainder of Sonora and
northern Sinaloa. These amounts will lead to isolated to scattered
instances of flash flooding.
 
Across the southwestern United States, 1 to 2 inches of rain, with
isolated totals up to 4 inches, are expected across portions of
Arizona and New Mexico through Saturday, bringing the potential for
isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Lorena, please see the National Weather Service 
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Lorena will continue affecting portions
of the south and west coasts of Baja California Sur through Friday.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Hagen
  