504 
WTPZ32 KNHC 050237
TCPEP2
 
BULLETIN
Tropical Storm Lorena Advisory Number  13
NWS National Hurricane Center Miami FL       EP122025
800 PM PDT Thu Sep 04 2025
 
...LORENA EXPECTED TO BECOME POST-TROPICAL VERY SOON...
...MOST IMPORTANTLY, THE RISK OF LIFE-THREATENING FLASH FLOODING
CONTINUES FOR BAJA CALIFORNIA SUR AND SONORA THROUGH FRIDAY...
 
 
SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...24.6N 115.1W
ABOUT 175 MI...285 KM W OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES
 
 
WATCHES AND WARNINGS
--------------------
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect.
 
Interests in Baja California Sur and Sonora, Mexico, should
continue to monitor the risk of heavy rainfall and flash flooding
associated with Lorena.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Lorena was
located near latitude 24.6 North, longitude 115.1 West.  Lorena is
moving toward the northwest near 5 mph (7 km/h).  A slow 
north-northwestward to northwestward motion is expected through 
early Saturday, followed by a turn toward the west-northwest over 
the weekend.
 
Maximum sustained winds have decreased to near 45 mph (75 km/h) 
with higher gusts.  Additional weakening is forecast, and Lorena is 
expected to become a remnant low by Friday morning.  The remnant 
low is likely to dissipate by late Sunday.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
to the northwest of the center.
 
The estimated minimum central pressure is 998 mb (29.47 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja
California Sur and Sonora Mexico through Friday. Additional rainfall
totals of 4 to 8 inches, with maximum storm total amounts of 15
inches, are possible across portions of Baja California Sur, far
southeast Baja California and southwestern Sonora into Friday. This
will bring the risk of life-threatening flash floods and mudslides,
especially in areas of higher terrain.
 
Elsewhere across Mexico, 2 to 4 inches of rain, with isolated totals
up to 6 inches, are expected across the remainder of Sonora and
northern Sinaloa. These amounts will lead to isolated to scattered
instances of flash flooding.
 
Across the southwestern United States, 1 to 2 inches of rain, with
isolated totals up to 4 inches, are expected across portions of
Arizona and New Mexico through Saturday, bringing the potential for
isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Lorena, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Lorena will continue affecting portions
of the west coast of Baja California Sur through Friday.  These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.
 
$$
Forecaster Berg
  