000
WTPZ32 KNHC 050859
TCPEP2
 
BULLETIN
Post-Tropical Cyclone Lorena Advisory Number  14
NWS National Hurricane Center Miami FL       EP122025
200 AM PDT Fri Sep 05 2025
 
...LORENA DEGENERATES TO A REMNANT LOW PRESSURE AREA...
...MOST IMPORTANTLY, THE RISK OF LIFE-THREATENING FLASH FLOODING
CONTINUES FOR BAJA CALIFORNIA SUR AND SONORA THROUGH TODAY...
 
 
SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...24.5N 115.0W
ABOUT 170 MI...275 KM W OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...STATIONARY
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect.
 
Interests in Baja California Sur and Sonora, Mexico, should continue 
to monitor the risk of heavy rainfall and flash flooding associated 
with Lorena.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Post-Tropical Cyclone Lorena
was located near latitude 24.5 North, longitude 115.0 West. The
post-tropical cyclone is currently nearly stationary.  A slow
north-northwestward to northwestward motion is expected through
early Saturday, followed by a turn toward the west-northwest over
the weekend.
 
Maximum sustained winds have decreased to near 35 mph (55 km/h) 
with higher gusts.  Additional weakening is forecast, and the 
remnant low is expected to dissipate by late Sunday or Sunday 
night.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Lorena can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC.
 
RAINFALL: Bands of heavy rainfall will continue to impact Baja 
California Sur and Sonora Mexico through today. Additional rainfall 
totals of 4 to 8 inches, with maximum storm total amounts of 12 
inches, are possible across portions of Baja California Sur, far 
southeast Baja California, southwestern Sonora, and northern Sinaloa 
through tonight. This will bring the risk of life-threatening flash 
floods and mudslides, especially in areas of higher terrain.
 
Elsewhere across Mexico, 2 to 4 inches of rain, with isolated totals
up to 6 inches, are expected across the remainder of Sonora. These
amounts will lead to isolated to scattered instances of flash
flooding.
 
Across the southwestern United States, 1 to 2 inches of rain, with
isolated totals up to 4 inches, are expected across portions of
Arizona and New Mexico through Saturday, bringing the potential for
isolated to scattered flash flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Lorena, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Lorena will continue affecting portions
of the west coast of Baja California Sur through today.  These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
This is the last advisory on Lorena by the National Hurricane 
Center. For additional information on the remnant low please see 
High Seas Forecasts issued by the National Weather Service, under 
AWIPS header NFDHSFEPI, WMO header FZPN02 KWBC, and on the web at
ocean.weather.gov/shtml/NFDHSFEPI.php

Rainfall forecasts for the United States can be found at 
https://www.wpc.ncep.noaa.gov/qpf/qpf2.shtml and outlooks of flash 
flood risks can be found at 
https://www.wpc.ncep.noaa.gov/qpf/excessive_rainfall_outlook_ero.php

For rainfall forecasts in northwestern Mexico, please see products 
from the Meteorological Service of Mexico.
 
$$
Forecaster Beven
  