

665 
WTNT32 KNHC 291447
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  25
NWS National Hurricane Center Miami FL       AL172023
1100 AM AST Fri Sep 29 2023

...PHILIPPE BARELY MOVING...
...EXPECTED TO DRIFT AROUND EAST OF THE NORTHERN LEEWARD ISLANDS
THROUGH THE WEEKEND...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.3N 55.3W
ABOUT 510 MI...825 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WSW OR 245 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the northern Leeward Islands, the U.S. and British
Virgin Islands, and Puerto Rico should monitor the progress of this
system.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Philippe was
located near latitude 18.3 North, longitude 55.3 West. Philippe is
moving very slowly toward the west-southwest near 2 mph (4 km/h), 
and this general motion is expected to continue through Saturday 
night.  A gradual turn toward the west and northwest is forecast 
Sunday and Sunday night.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Gradual strengthening is forecast during the next few days.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through the weekend.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi


