

904 
WTNT32 KNHC 300835
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  28
NWS National Hurricane Center Miami FL       AL172023
500 AM AST Sat Sep 30 2023

...PHILIPPE FORECAST TO LINGER JUST EAST OF THE NORTHERN LEEWARD
ISLANDS FOR A FEW MORE DAYS...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...17.1N 55.9W
ABOUT 480 MI...770 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...SSW OR 200 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the northern Leeward Islands, the U.S. and British
Virgin Islands, and Puerto Rico should monitor the progress of this
system.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Philippe was
located near latitude 17.1 North, longitude 55.9 West.  Philippe is
moving toward the south-southwest near 5 mph (7 km/h).  A slow turn 
toward the southwest and west is expected through tonight, followed 
by a turn toward the northwest and north-northwest Sunday night and 
Monday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some strengthening is forecast during the next few days, and 
Philippe could become a hurricane early next week.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through early next week.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Berg


