

678 
WTNT32 KNHC 302042
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  30
NWS National Hurricane Center Miami FL       AL172023
500 PM AST Sat Sep 30 2023

...PHILIPPE STILL SHEARED AND MOVING SLOWLY SOUTHWESTWARD...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...16.3N 56.5W
ABOUT 455 MI...730 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...SW OR 215 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the northern Leeward Islands, the U.S. and British
Virgin Islands, and Puerto Rico should monitor the progress of this
system.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Philippe was 
located near latitude 16.3 North, longitude 56.5 West. Philippe is 
moving toward the southwest near 5 mph (7 km/h), and this general 
motion should continue through tonight. A turn toward the 
west-northwest and northwest with an increase in forward speed is 
expected Sunday and Monday, followed by a northward motion on 
Tuesday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some strengthening is forecast during the next few days, and
Philippe could become a hurricane early next week.

Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.

The estimated minimum central pressure based on Air Force Reserve
Hurricane Hunter dropsonde data is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through early next week. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Reinhart


