

000
WTNT32 KNHC 010846
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  32
NWS National Hurricane Center Miami FL       AL172023
500 AM AST Sun Oct 01 2023

...PHILIPPE MOVING WESTWARD WITH NO CHANGE IN STRENGTH...
...INTERESTS IN THE NORTHERN LEEWARD ISLANDS SHOULD MONITOR THE
PROGRESS OF PHILIPPE...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.4N 58.2W
ABOUT 210 MI...340 KM E OF GUADELOUPE
ABOUT 250 MI...405 KM ESE OF BARBUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the northern Leeward Islands should monitor the
progress of this system.  Tropical storm watches or warnings may
be required for a portion of that area later today.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Philippe was
located near latitude 16.4 North, longitude 58.2 West. Philippe is
moving toward the west near 7 mph (11 km/h).  A west-northwestward 
to northwestward motion is expected to begin today and continue 
into tonight.  A turn toward the northwest with an increase in 
forward speed is expected Sunday and Monday, followed by a northward 
motion on Tuesday.  On the forecast track, the center of Philippe 
is forecast to pass near or just northeast of the northern Leeward 
Islands on Monday and Monday night. 

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Little change in strength is expected during the next day or 
so.  Some strengthening is possible by late Monday as Philippe 
begins to move north of the Leeward Islands. 

Tropical-storm-force winds extend outward up to 150 miles (240 km) 
primarily to the east of the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC. 

RAINFALL:  Philippe is forecast to produce 1 to 4 inches of rain
across portions of the Leeward Islands by Monday into Tuesday. This
rainfall may result in isolated flash flooding.

WIND:  Gusty winds are possible in portions of the northern
leeward islands by Monday.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Brown

