

000
WTNT32 KNHC 011453
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  33
NWS National Hurricane Center Miami FL       AL172023
1100 AM AST Sun Oct 01 2023

...TRACK OF PHILIPPE SHIFTING WESTWARD SO TROPICAL STORM WATCHES
ISSUED FOR ANTIGUA AND BARBUDA...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.1N 58.7W
ABOUT 180 MI...290 KM E OF GUADELOUPE
ABOUT 230 MI...370 KM ESE OF BARBUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua has issued a Tropical Storm for Antigua
and Barbuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Antigua, Barbuda

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.  Additional tropical storm watches or
warnings may be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Philippe was
located near latitude 16.1 North, longitude 58.7 West. Philippe is
moving toward the west near 7 mph (11 km/h). A west-northwestward
to northwestward motion is expected to begin today and continue
into tonight.  A turn toward the northwest with an increase in
forward speed is expected on Monday, followed by a northward
motion on Tuesday.  On the forecast track, the center of Philippe
is forecast to pass near or just northeast of the northern Leeward
Islands on Monday and Monday night.

Maximum sustained winds remain near 50 mph (85 km/h) with higher 
gusts. Little change in strength is forecast during the next 48 
hours, and Philippe could begin to intensify more significantly 
around the middle of the week.

Tropical-storm-force winds extend outward up to 170 miles (275 km), 
primarily east of the center.

The estimated minimum central pressure is 1002 mb (29.59 inches) 
based on dropsonde data from an Air Force Reserve Hurricane Hunter 
aircraft.


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC 
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through Tuesday:

Barbuda and Antigua: 4 to 6 inches
Rest of Leeward Islands: 2 to 4 inches

This rainfall may result in isolated to scattered flash flooding.

WIND:  Tropical storm conditions are possible in the watch areas by
Monday morning.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Blake

