

000
WTNT32 KNHC 011743
TCPAT2

BULLETIN
Tropical Storm Philippe Intermediate Advisory Number 33A
NWS National Hurricane Center Miami FL       AL172023
200 PM AST Sun Oct 01 2023

...PHILIPPE MOVING ERRATICALLY WEST-NORTHWESTWARD...
...HEAVY RAIN AND FLASH FLOOD THREAT STARTING OVERNIGHT FOR THE 
LEEWARD ISLANDS...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...16.2N 58.8W
ABOUT 170 MI...275 KM E OF GUADELOUPE
ABOUT 220 MI...355 KM ESE OF BARBUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Antigua, Barbuda

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.  Additional tropical storm watches or
warnings may be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Tropical Storm Philippe was
located near latitude 16.2 North, longitude 58.8 West. Philippe is
moving toward the west-northwest near 7 mph (11 km/h). A 
west-northwestward to northwestward motion is expected through 
tonight.  A track toward the northwest with an increase in forward
speed is expected on Monday, followed by a northward motion on
Tuesday.  On the forecast track, the center of Philippe is forecast
to pass near or just northeast of the northern Leeward Islands on
Monday and Monday night.

Satellite wind data indicate that the maximum sustained winds 
remain near 50 mph (85 km/h) with higher gusts. Little change in 
strength is forecast during the next 48 hours, and Philippe could 
begin to intensify more significantly around the middle of the week.

Tropical-storm-force winds extend outward up to 170 miles (275 km),
primarily east of the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through Tuesday:

Barbuda and Antigua: 4 to 6 inches
Rest of the Leeward Islands: 2 to 4 inches

This rainfall may result in isolated to scattered flash flooding.

WIND:  Tropical storm conditions are possible in the watch areas by
Monday morning.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Blake

