

704 
WTNT32 KNHC 021454
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  37
NWS National Hurricane Center Miami FL       AL172023
1100 AM AST Mon Oct 02 2023

...TROPICAL STORM WARNING ISSUED FOR BARBUDA...
...PHILIPPE COULD BRING HEAVY RAINS AND FLOODING TO PORTIONS OF
THE LEEWARD ISLANDS LATER TODAY...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.1N 60.7W
ABOUT 80 MI...130 KM ESE OF BARBUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua has issued a Tropical Storm Warning for
Barbuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Barbuda

A Tropical Storm Watch is in effect for...
* Antigua

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 12
hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 12 hours.

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Philippe was
located by an Air Force Reserve Hurricane Hunter near latitude 17.1 
North, longitude 60.7 West. Philippe is moving toward the 
west-northwest near 7 mph (11 km/h), and a northwestward motion is 
expected to resume later today through early Tuesday. A turn toward 
the north-northwest is forecast to occur by late Tuesday, followed 
by a northward motion on Wednesday. On the forecast track, the 
center of Philippe is expected to pass near or just northeast of 
the northern Leeward Islands tonight. Note that the strongest 
winds and heavy rains will likely occur after the center passes.

Maximum sustained winds remain near 50 mph (85 km/h) with higher
gusts. Little change in strength is forecast during the next day or
so, but Philippe could begin to intensify more significantly around
the middle of the week.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches) 
based off dropsonde data.


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through Tuesday:

Barbuda and Antigua: 4 to 6 inches

Rest of Leeward Islands: 2 to 4 inches

This rainfall may result in isolated to scattered flash flooding.

WIND:  Tropical storm conditions are expected in the warning
area beginning this evening and are possible in the watch area
beginning this evening.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through midweek. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Blake/Stevenson


