

836 
WTNT32 KNHC 021754
TCPAT2

BULLETIN
Tropical Storm Philippe Intermediate Advisory Number 37A
NWS National Hurricane Center Miami FL       AL172023
200 PM AST Mon Oct 02 2023

...PHILIPPE FORECAST TO CAUSE HEAVY RAINS AND FLOODING TO PORTIONS 
OF THE LEEWARD ISLANDS LATER TODAY...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...17.3N 61.0W
ABOUT 55 MI...90 KM ESE OF BARBUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Barbuda

A Tropical Storm Watch is in effect for...
* Antigua

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 6-12
hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 6-12 hours.

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Tropical Storm Philippe was 
located by an Air Force Reserve Hurricane Hunter near latitude 17.3 
North, longitude 61.0 West. Philippe is moving toward the northwest 
near 7 mph (11 km/h), and this general motion is anticipated through 
early Tuesday. A turn toward the north-northwest is forecast to 
occur by late Tuesday, followed by a northward motion on Wednesday. 
On the forecast track, the center of Philippe is expected to pass 
near or just northeast of the northern Leeward Islands tonight. The 
strongest winds and heavy rains will likely occur in the islands 
after the center passes.

Maximum sustained winds remain near 50 mph (85 km/h) with higher
gusts. Little change in strength is forecast during the next day or
so, but Philippe could begin to intensify more significantly around
the middle of the week.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
primarily east of the center.

The estimated minimum central pressure is 1000 mb (29.53 inches)
based on dropsonde data.


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through Tuesday:

Barbuda and Antigua: 4 to 6 inches

Rest of Leeward Islands: 2 to 4 inches

This rainfall may result in isolated to scattered flash flooding.

WIND:  Tropical storm conditions are expected in the warning
area and possible in the watch area beginning this evening.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through midweek. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Blake/Stevenson


