

000
WTNT32 KNHC 022055
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  38
NWS National Hurricane Center Miami FL       AL172023
500 PM AST Mon Oct 02 2023

...TROPICAL STORM WARNING ISSUED FOR ANTIGUA...
...PHILIPPE LIKELY TO CAUSE HEAVY RAINS AND SOME FLOODING TO
PORTIONS OF THE LEEWARD ISLANDS OVERNIGHT...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 61.5W
ABOUT 20 MI...30 KM E OF BARBUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua has issued a Tropical Storm Warning for 
Antigua.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Barbuda
* Antigua

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 6
hours.

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Philippe was
located near latitude 17.6 North, longitude 61.5 West. Philippe is
moving toward the northwest near 7 mph (11 km/h), and this general
motion is anticipated through early Tuesday. On the forecast track, 
the center of Philippe is expected to pass near the northern 
Leeward Islands tonight and north of those islands on Tuesday. The 
strongest winds and heavy rains will likely occur in the islands 
after the center passes. A turn toward the north-northwest is 
forecast to occur by late Tuesday, followed by a northward motion 
on Wednesday. 

Maximum sustained winds remain near 50 mph (85 km/h) with higher
gusts. Little change in strength is forecast during the next day or
so, but Philippe could begin to intensify more significantly around
the middle of the week.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through Tuesday:

Barbuda and Antigua: 4 to 6 inches 
Rest of Leeward Islands: 2 to 4 inches

This rainfall may result in isolated to scattered flash flooding.

WIND:  Tropical storm conditions are expected in the warning
areas beginning this evening.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through midweek. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Blake/Stevenson

