

184 
WTNT32 KNHC 022355
TCPAT2

BULLETIN
Tropical Storm Philippe Intermediate Advisory Number 38A
NWS National Hurricane Center Miami FL       AL172023
800 PM AST Mon Oct 02 2023

...HEAVY RAINS AND FLOODING EXPECTED OVER PORTIONS OF THE 
LEEWARD ISLANDS OVERNIGHT...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 62.0W
ABOUT 80 MI...130 KM ESE OF ST. MARTIN
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Barbuda
* Antigua

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 6
hours.

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Tropical Storm Philippe was
located near latitude 17.6 North, longitude 62.0 West.  Philippe is
moving toward the west-northwest near 7 mph (11 km/h), and a 
generally northwestward motion is forecast through early Tuesday.  
On the forecast track, the center of Philippe is expected to 
continue passing near the northern Leeward Islands tonight and move 
north of those islands on Tuesday.  The strongest winds and heavy 
rains will likely occur in the islands after the center passes.  A 
turn toward the north-northwest is forecast by late Tuesday, 
followed by a northward motion on Wednesday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Little change in strength is forecast during the next day or so, 
but Philippe could begin to intensify more significantly around the 
middle of the week.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.

The minimum central pressure estimated from Air Force Hurricane 
Hunter aircraft observations is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through Tuesday:

Barbuda and Antigua: 4 to 6 inches
Rest of Leeward Islands: 2 to 4 inches

This rainfall may result in isolated to scattered flash flooding.

WIND:  Tropical storm conditions are expected in portions of the 
warning area tonight.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through midweek. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Pasch


