

949 
WTNT32 KNHC 030244
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  39
NWS National Hurricane Center Miami FL       AL172023
1100 PM AST Mon Oct 02 2023

...HEAVY RAINS AND FLOODING EXPECTED OVER PORTIONS OF THE
LEEWARD ISLANDS TONIGHT AND TUESDAY...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.8N 62.1W
ABOUT 70 MI...110 KM ESE OF ST. MARTIN
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Barbuda
* Antigua

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 6
hours.

Interests elsewhere in the northern Leeward Islands should monitor
the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Philippe was
located near latitude 17.8 North, longitude 62.1 West.  Philippe is
moving toward the west-northwest near 7 mph (11 km/h), and a
generally northwestward motion is forecast on Tuesday.  On the 
forecast track, the center of Philippe is expected to continue 
passing near the northern Leeward Islands tonight and early 
Tuesday, and move north of those islands by late Tuesday.  However, 
the strongest winds and heavy rains will likely occur in the islands 
to the south of the center.  A turn toward the north-northwest is 
forecast by late Tuesday, followed by a northward motion on 
Wednesday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Little change in strength is forecast during the next day or two,
but Philippe could begin to intensify more significantly around the
middle of the week.

Tropical-storm-force winds extend outward up to 175 miles (280 km) 
primarily to the east and southeast of the center.

The minimum central pressure estimated from Air Force Hurricane 
Hunter aircraft observations is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts into early Wednesday:

Barbuda southward to Dominica: 4 to 8 inches

Rest of Leeward Islands and northern Windward Islands: 3 to 5 inches

This rainfall would result in scattered flash flooding.

WIND:  Tropical storm conditions are expected in portions of the
warning area tonight.  Strong gusty winds are also likely elsewhere 
in the Leeward Islands tonight and Tuesday.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through midweek. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Pasch


