

000
WTNT32 KNHC 031742
TCPAT2

BULLETIN
Tropical Storm Philippe Intermediate Advisory Number 41A
NWS National Hurricane Center Miami FL       AL172023
200 PM AST Tue Oct 03 2023

...PHILIPPE PASSING BY THE BRITISH VIRGIN ISLANDS WITH A POORLY 
DEFINED CENTER...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...19.0N 64.4W
ABOUT 55 MI...90 KM NE OF ST. THOMAS
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua and Barbuda has discontinued the Tropical
Storm Warning for Anguilla.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* British Virgin Islands

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.

Interests elsewhere in the northern Leeward Islands, the U.S.
Virgin Islands, and Puerto Rico should monitor the progress of
Philippe.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the poorly defined center of Tropical 
Storm Philippe was located near latitude 19.0 North, longitude 64.4 
West.  Philippe is moving toward the northwest near 10 mph (17 
km/h).  A turn toward the north-northwest is expected later today, 
followed by a northward motion late Wednesday through Thursday.  On 
the forecast track, the center of Philippe is expected to move away 
from the Virgin Islands beginning tonight.  However, the strongest 
winds and heaviest rains will likely occur in the islands to the 
southeast of the center.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Little change in strength is forecast during the next couple of 
days.  Philippe could begin to strengthen a bit late this week.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
primarily to the east and southeast of the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts into early Wednesday:

Anguilla southward to Montserrat, including St. Kitts and Nevis,
and the British Virgin Islands:  4 to 8 inches with maximum amounts
to 12 inches.

The remainder of the Leeward Islands and northern Windward Islands:
1 to 4 inches

The U.S. Virgin Islands and northeast Puerto Rico: 2 to 4 inches

This rainfall would result in scattered flash flooding.

WIND:  Tropical storm conditions are possible in the British Virgin 
Islands through today.  Strong gusty winds are also likely elsewhere 
in the Leeward Islands today.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico through midweek. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Berg

