

000
WTNT32 KNHC 040843
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  44
NWS National Hurricane Center Miami FL       AL172023
500 AM AST Wed Oct 04 2023

...PHILIPPE REMAINS DISORGANIZED AS IT MOVES SLOWLY NORTHWESTWARD...
...HEAVY RAINS AND FLASH FLOODING CONTINUES ACROSS PORTIONS OF THE 
BRITISH AND U.S. VIRGIN ISLANDS...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...20.5N 65.5W
ABOUT 150 MI...240 KM NNW OF ST. THOMAS
ABOUT 815 MI...1315 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Bermuda should monitor the progress of Philippe, as
Tropical Storm Watches could be required later today.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Philippe was 
located near latitude 20.5 North, longitude 65.5 West. Philippe is 
moving toward the northwest near 9 mph (15 km/h). A turn toward the 
north-northwest is forecast later today, followed by a faster motion 
toward the north on Thursday and Friday.  On the forecast track, the 
center of Philippe will continue to move away from Puerto Rico and 
the Virgin Islands today.  Philippe will then approach Bermuda 
Thursday night and Friday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Little change in strength is forecast during the next day or so, 
but some gradual intensification could occur after that time.

Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Philippe is forecast to produce the following rainfall
amounts through today:

The United States & British Virgin Islands: 4 to 8 inches with
maximum amounts to 12 inches.

Puerto Rico: 2 to 4 inches.

This rainfall is likely to result in scattered flash flooding.

WIND:  Gusty winds are likely to continue across portions of the
the Virgin Islands through early today.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin Islands,
and Puerto Rico for another couple of days.  Swells are expected to
reach Bermuda by late Thursday.  These conditions are likely to
cause life-threatening surf and rip currents. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin

