

441 
WTNT32 KNHC 042346
TCPAT2

BULLETIN
Tropical Storm Philippe Intermediate Advisory Number 46A
NWS National Hurricane Center Miami FL       AL172023
800 PM AST Wed Oct 04 2023

...PHILIPPE REMAINS DISORGANIZED...
...TROPICAL STORM CONDITIONS EXPECTED IN BERMUDA ON FRIDAY...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...23.1N 66.0W
ABOUT 335 MI...535 KM N OF ST. THOMAS
ABOUT 640 MI...1030 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests in eastern New England and Atlantic Canada should monitor
the progress of Philippe.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Tropical Storm Philippe was
located near latitude 23.1 North, longitude 66.0 West.  Philippe is
moving toward the north near 12 mph (19 km/h).  This general motion
with an increase in forward speed is expected through Saturday.  On
the forecast track, the center of Philippe will pass near Bermuda 
on Friday, and approach eastern New England and Atlantic Canada on 
Saturday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Little change in strength is forecast during the next day or so.  
Some strengthening is possible on Friday and Saturday.

Tropical-storm-force winds extend outward up to 205 miles (335 km)
to the east of the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Rainfall will begin to affect Bermuda on Thursday with
rainfall totals of 3 to 6 inches expected through Friday.

These rainfall amounts may result in scattered flash flooding.

Rainfall across the U.S. and British Virgin Islands and Puerto Rico
will continue to diminish during the next few hours.

WIND:  Tropical storm conditions are possible on Bermuda beginning
Friday morning.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin Islands,
and Puerto Rico for another day or so.  Large swells are already
affecting Bermuda from another weather system but will begin to
increase further on Thursday as Philippe approaches the island.
These conditions are likely to cause life-threatening surf and rip
currents. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Cangialosi


