

999 
WTNT32 KNHC 050844
TCPAT2

BULLETIN
Tropical Storm Philippe Advisory Number  48
NWS National Hurricane Center Miami FL       AL172023
500 AM AST Thu Oct 05 2023

...PHILIPPE CONTINUES NORTHWARD...
...TROPICAL STORM CONDITIONS EXPECTED ON BERMUDA BEGINNING
TONIGHT...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...24.8N 65.9W
ABOUT 445 MI...715 KM N OF ST. THOMAS
ABOUT 520 MI...840 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests in eastern New England and Atlantic Canada should monitor
the progress of Philippe.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Philippe was
located near latitude 24.8 North, longitude 65.9 West. Philippe is
moving toward the north near 14 mph (22 km/h). This general motion
with an increase in forward speed is expected through Saturday.  On
the forecast track, the center of Philippe will pass near Bermuda on
Friday, and approach eastern New England and Atlantic Canada on
Saturday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Gradual strengthening is forecast during the next few days. Philippe 
is then forecast to become a Post-Tropical Cyclone on Saturday as it 
approaches Atlantic Canada and New England.

Tropical-storm-force winds extend outward up to 230 miles (370 km) 
from the center. In the last few hours, Saildrone SD-1041 reported a 
wind gust to 43 mph (69 km/h) to the southeast of the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Philippe can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml

RAINFALL:  Rainfall will begin to affect Bermuda today with rainfall
totals of 3 to 5 inches expected through Friday. These rainfall
amounts could result in scattered flash flooding.

Rainfall across Puerto Rico and the U.S. and British Virgin Islands
should continue to gradually diminish this morning.

WIND:  Tropical storm conditions are possible on Bermuda beginning
by tonight.

SURF:  Swells generated by Philippe will affect portions of the
Atlantic coasts of the northern Leeward Islands, the Virgin Islands,
and Puerto Rico for another day or so.  Large swells are already
affecting Bermuda from another weather system but will begin to
increase further later today as Philippe approaches the island.
These conditions are likely to cause life-threatening surf and rip
currents. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin


