

604 
WTNT33 KNHC 211436
TCPAT3

BULLETIN
Tropical Storm Gaston Advisory Number   5
NWS National Hurricane Center Miami FL       AL082022
Issued by the NWS Weather Prediction Center College Park MD
300 PM GMT Wed Sep 21 2022

...GASTON MAINTAINING ITS STRENGTH...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...38.3N 41.3W
ABOUT 775 MI...1250 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of the system.
See gale warnings and products issued by the meteorological
service in the Azores for more information.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Tropical Storm Gaston was
located near latitude 38.3 North, longitude 41.3 West. Gaston is
moving toward the northeast near 16 mph (26 km/h). A turn to the
the east is expected on Thursday, and Gaston is expected to stall 
near the western Azores late this week.

Maximum sustained winds remain near 65 mph (100 km/h) with higher
gusts.  Some additional strengthening is possible today, but 
gradual weakening should begin on Thursday.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Winds to gale force are possible in the western Azores later
this week.  See gale warnings and products issued by the
meteorological service in the Azores.

SURF:  Swells generated by Gaston are expected to affect the Azores
later this week.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Cangialosi/Kong/Gallina


