

000
WTNT33 KNHC 222047
TCPAT3

BULLETIN
Tropical Storm Gaston Advisory Number  10
NWS National Hurricane Center Miami FL       AL082022
Issued by the NWS Weather Prediction Center College Park MD
900 PM GMT Thu Sep 22 2022

...GASTON APPROACHING THE WESTERN AZORES ISLANDS..
...TROPICAL STORM CONDITIONS EXPECTED TO BEGIN LATER TONIGHT...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...41.1N 32.0W
ABOUT 245 MI...395 KM NW OF FAIAL ISLAND IN THE CENTRAL AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...ENE OR 70 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNING IN EFFECT:

A Tropical Storm Warning is in effect for...
* Flores and Corvo in the western Azores
* Faial, Pico, Sao Jorge, Graciosa and Terceira in the central
Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Tropical Storm Gaston was
located near latitude 41.1 North, longitude 32.0 West. Gaston is
moving toward the east-northeast near 17 mph (28 km/h). A turn to
the east is expected later tonight, and a slower southeastward or
southward motion is forecast by early Saturday.  On the forecast
track, the center of Gaston will move near or over portions of the
Azores tonight through Saturday.

Maximum sustained winds remain near 65 mph (100 km/h) with higher
gusts.  Gradual weakening is expected over the next few days.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.  A wind gust of 39 mph (63 km/h) was recently 
reported at an observing site in Flores in the western Azores.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Gaston can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT3 and WMO header
WTNT43 KNHC and on the web at hurricanes.gov/text/MIATCDAT3.shtml.

WIND:  Tropical-storm-force winds are expected in portions of the
western Azores beginning later tonight and will spread to the
central Azores on Friday. See products issued by the meteorological
service in the Azores.

SURF:  Swells generated by Gaston are expected to affect portions
of the Azores through Saturday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.

RAINFALL:  Gaston is expected to produce total rain accumulations
of 2 to 6 inches with isolated higher amounts across the western
and central Azores.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM GMT.
Next complete advisory at 300 AM GMT.

$$
Forecaster Cangialosi/Churchill/Hamrick

