
ZCZC MIATCPAT3 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Gaston Advisory Number  12
NWS National Hurricane Center Miami FL       AL082022
900 AM GMT Fri Sep 23 2022

...GASTON EXPECTED TO TURN SOUTHEASTWARD TODAY...
...TROPICAL STORM CONDITIONS AFFECTING THE WESTERNMOST AZORES
ISLANDS...
...HEAVY RAINFALL EXPECTED OVER THE WEST AND CENTRAL AZORES TODAY 
AND SATURDAY... 

SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...40.5N 29.6W
ABOUT 140 MI...225 KM NNW OF FAIAL ISLAND IN THE CENTRAL AZORES
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...ESE OR 115 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNING IN EFFECT:

A Tropical Storm Warning is in effect for...
* Flores and Corvo in the western Azores
* Faial, Pico, Sao Jorge, Graciosa and Terceira in the central
Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Tropical Storm Gaston was
located near latitude 40.5 North, longitude 29.6 West. Gaston is
moving toward the east-southeast near 9 mph (15 km/h).  A slower
southeastward motion is forecast today followed by a southward, and 
then southwestward, motion tonight and early Saturday.  On the 
forecast track, the center of Gaston will move near or over 
portions of the Azores today through early Saturday.

Maximum sustained winds have decreased to near 60 mph (95 km/h) 
with higher gusts.  Gradual weakening is expected over the next few 
days.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Gaston can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT3 and WMO header
WTNT43 KNHC and on the web at hurricanes.gov/text/MIATCDAT3.shtml.

WIND:  Tropical-storm-force winds are expected in portions of the
western and central Azores through today.  See products issued by
the meteorological service in the Azores.

SURF:  Swells generated by Gaston are expected to affect portions
of the Azores through Saturday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.

RAINFALL:  Gaston is expected to produced total rainfall 
accumulations of 2 to 6 inches with isolated higher amounts across 
the western and central Azores.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM GMT.
Next complete advisory at 300 PM GMT.

$$
Forecaster Roberts

NNNN
