

910 
WTNT33 KNHC 240552
TCPAT3

BULLETIN
Tropical Storm Gaston Intermediate Advisory Number 15A
NWS National Hurricane Center Miami FL       AL082022
600 AM GMT Sat Sep 24 2022

...TROPICAL STORM CONDITIONS SPREADING OVER THE WESTERN AND CENTRAL 
AZORES...


SUMMARY OF 600 AM GMT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...38.7N 29.7W
ABOUT 55 MI...90 KM WNW OF FAIAL ISLAND IN THE CENTRAL AZORES
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...SW OR 230 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNING IN EFFECT:

A Tropical Storm Warning is in effect for...
* Flores and Corvo in the western Azores
* Faial, Pico, Sao Jorge, Graciosa and Terceira in the central
Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM GMT (0600 UTC), the center of Tropical Storm Gaston was
located near latitude 38.7 North, longitude 29.7 West.  Gaston is 
moving toward the southwest near 8 mph (13 km/h).  A turn to 
the west is anticipated later today.  On the forecast track, the 
center of Gaston will move near or over portions of the Azores 
through this morning.

Maximum sustained winds have decreased to near 50 mph (85 km/h) 
with higher gusts.  Gradual weakening is expected over the next few 
days, and Gaston is expected to become a post-tropical cyclone 
later today.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Gaston can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC
and on the web at hurricanes.gov/text/MIATCDAT3.shtml.

WIND:  Tropical-storm-force winds are expected in portions of the
western and central Azores through today.  See products issued by
the meteorological service in the Azores for more information.

SURF:  Swells generated by Gaston are expected to affect portions of
the Azores through today.  These swells are likely to cause
life-threatening surf and rip current conditions.

RAINFALL:  Gaston is expected to produced total rainfall
accumulations of 2 to 6 inches with isolated higher amounts across
the western and central Azores.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Roberts


