

000
WTNT33 KNHC 241755
TCPAT3

BULLETIN
Tropical Storm Gaston Intermediate Advisory Number 17A
NWS National Hurricane Center Miami FL       AL082022
600 PM GMT Sat Sep 24 2022

...GASTON TURNS WESTWARD...


SUMMARY OF 600 PM GMT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...38.0N 31.0W
ABOUT 130 MI...210 KM WSW OF FAIAL ISLAND IN THE CENTRAL AZORES
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNING IN EFFECT:

A Tropical Storm Warning is in effect for...
* Flores and Corvo in the western Azores
* Faial, Pico, Sao Jorge, Graciosa and Terceira in the central
Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 PM GMT (1800 UTC), the center of Tropical Storm Gaston was 
located near latitude 38.0 North, longitude 31.0 West. Gaston is 
moving toward the west near 7 mph (11 km/h), and this general motion 
is expected to continue through Sunday.  A turn to the southwest is 
forecast by late Sunday.

Maximum sustained winds are near 45 mph (75 km/h) with higher
gusts. Gradual weakening is forecast over the next few days, and
Gaston is expected to become a post-tropical cyclone later this 
evening.

Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center.

The estimated minimum central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Gaston can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC
and on the web at hurricanes.gov/text/MIATCDAT3.shtml.

WIND:  Tropical-storm-force winds are expected in portions of the 
western Azores for the next several hours.  See products issued by 
the meteorological service in the Azores for more information.

SURF:  Swells generated by Gaston are expected to affect portions of
the Azores through tonight.  These swells are likely to cause
life-threatening surf and rip current conditions.

RAINFALL:  Gaston is expected to produce additional rainfall
accumulations of 1 to 2 inches with locally higher amounts of 3
inches across the western and central Azores.  This will result in
storm total rainfall of 2 to 6 inches which may result in landslides
and areas of flooding.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Bucci

