000
WTNT33 KNHC 262034
TCPAT3
 
BULLETIN
Hurricane Humberto Advisory Number   9
NWS National Hurricane Center Miami FL       AL082025
500 PM AST Fri Sep 26 2025
 
...HUMBERTO RAPIDLY STRENGTHENS TO A MAJOR HURRICANE...
...FURTHER INTENSIFICATION EXPECTED OVER THE CENTRAL ATLANTIC...
 
 
SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 58.1W
ABOUT 430 MI...690 KM NE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Humberto was 
located near latitude 22.3 North, longitude 58.1 West. Humberto is 
moving toward the west-northwest near 5 mph (7 km/h). A 
west-northwestward to northwestward motion at a slightly faster 
forward speed is forecast through the weekend, followed by a turn 
toward the north-northwest on Monday.
 
Maximum sustained winds have increased to near 115 mph (185 km/h) 
with higher gusts. Humberto is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Additional strengthening is 
forecast over the next couple of days.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the 
center and tropical-storm-force winds extend outward up to 105 miles 
(165 km). NOAA buoy 41044 located to the southwest of Humberto 
recently reported a sustained wind of 36 mph (57 km/h) and a gust of 
49 mph (80 km/h).
 
The estimated minimum central pressure is 962 mb (28.41 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Humberto will begin affecting portions of
the northern Leeward Islands, the Virgin Islands, Puerto Rico, and
Bermuda this weekend. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Reinhart
  