000
WTNT33 KNHC 270844
TCPAT3
 
BULLETIN
Hurricane Humberto Advisory Number  11
NWS National Hurricane Center Miami FL       AL082025
500 AM AST Sat Sep 27 2025
 
...HUMBERTO EXPECTED TO REMAIN A POWERFUL MAJOR HURRICANE THROUGH
EARLY NEXT WEEK...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 59.3W
ABOUT 375 MI...605 KM NE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...938 MB...27.70 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Bermuda should monitor the progress of Humberto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the eye of Hurricane Humberto was
located near latitude 22.3 North, longitude 59.3 West. Humberto is
moving toward the west near 6 mph (9 km/h). By early Monday, a
turn toward the northwest at a slightly faster forward speed is
forecast followed by a turn toward the north-northwest by Monday
night.
 
Maximum sustained winds are near 145 mph (230 km/h) with higher
gusts.  Humberto is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Additional strengthening is forecast through 
the weekend.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).
 
The estimated minimum central pressure is 938 mb (27.70 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Humberto will begin affecting portions of
the northern Leeward Islands, the Virgin Islands, Puerto Rico, and
Bermuda this weekend and early next week. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Bucci
  