000
WTNT33 KNHC 271438
TCPAT3
 
BULLETIN
Hurricane Humberto Advisory Number  12
NWS National Hurricane Center Miami FL       AL082025
1100 AM AST Sat Sep 27 2025
 
...DANGEROUS SURF FROM MAJOR HURRICANE HUMBERTO EXPECTED TO 
AFFECT CARIBBEAN AND BERMUDA SHORES LATER THIS WEEKEND...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...22.7N 60.2W
ABOUT 365 MI...585 KM NNE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 720 MI...1160 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...938 MB...27.70 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda should monitor the progress of Humberto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the eye of Hurricane Humberto was located 
near latitude 22.7 North, longitude 60.2 West. Humberto is moving 
toward the west-northwest near 8 mph (13 km/h). A turn toward the 
northwest is anticipated on Sunday. Humberto is forecast to then 
turn northward by Tuesday.
 
Maximum sustained winds are near 145 mph (230 km/h) with higher 
gusts. Humberto is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Some strengthening is possible today. Humberto 
will likely remain a powerful major hurricane for the next several 
days.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).
 
The estimated minimum central pressure is 938 mb (27.70 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Humberto will affect portions of the
northern Leeward Islands, the Virgin Islands, Puerto Rico, and
Bermuda beginning tonight and continuing next week. Swells from
Humberto will also affect the U.S. East Coast beginning Monday.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster D. Zelinsky
  