000
WTNT33 KNHC 290240
TCPAT3
 
BULLETIN
Hurricane Humberto Advisory Number  18
NWS National Hurricane Center Miami FL       AL082025
1100 PM AST Sun Sep 28 2025
 
...AIR FORCE HURRICANE HUNTERS INDICATE HUMBERTO REMAINS A
CATEGORY 4 HURRICANE...
...DANGEROUS SURF WILL AFFECT BERMUDA AND MOST OF THE U.S. EAST
COAST THIS WEEK...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...26.2N 66.2W
ABOUT 585 MI...945 KM NNW OF THE NORTHERN LEEWARD ISLANDS
ABOUT 430 MI...690 KM SSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...928 MB...27.41 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Bermuda
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the eye of Hurricane Humberto was located
near latitude 26.2 North, longitude 66.2 West. Humberto is moving
toward the northwest near 14 mph (22 km/h). A gradual turn toward
the north is expected over the next day or so. The hurricane is then
forecast to turn and accelerate east-northeastward by late Tuesday
or early Wednesday. On the forecast track, the center of Humberto
will pass well west, and then north of Bermuda on Tuesday and
Wednesday.
 
Maximum sustained winds are near 140 mph (220 km/h) with higher
gusts. Humberto is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Fluctuations in intensity are possible during
the next day or so. Gradual weakening is forecast after that, but
Humberto is expected to remain a dangerous major hurricane for
another couple of days.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 928 mb (27.41 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Humberto will continue to affect portions
of the northern Leeward Islands, the Virgin Islands, Puerto Rico,
and Bermuda through much of this week. Swells from Humberto will
also affect the U.S. East Coast beginning Monday. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
RAINFALL: Hurricane Humberto is expected to bring rainfall of 1 to
2 inches, or 25 to 50 mm, to Bermuda Monday night through Tuesday.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.
 
$$
Forecaster Cangialosi
  