738 
WTNT33 KNHC 291440
TCPAT3
 
BULLETIN
Hurricane Humberto Advisory Number  20
NWS National Hurricane Center Miami FL       AL082025
1100 AM AST Mon Sep 29 2025
 
...HUMBERTO EXPECTED TO PRODUCE DANGEROUS SURF AND RIP CURRENTS FOR
BERMUDA AND MOST OF THE U.S. EAST COAST THIS WEEK...
...TROPICAL STORM CONDITIONS POSSIBLE IN BERMUDA ON TUESDAY...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...28.0N 67.6W
ABOUT 340 MI...550 KM SSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...940 MB...27.76 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Bermuda
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours. This
Tropical Storm Watch may be replaced with a Hurricane Watch later
today due to Imelda.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Humberto was 
located by an Air Force Reserve Hurricane Hunter aircraft near 
latitude 28.0 North, longitude 67.6 West. Humberto is moving toward 
the northwest near 13 mph (20 km/h).A gradual turn towards the 
north-northwest then north is expected over the next day or so. The 
hurricane is then forecast to turn and accelerate east-northeastward 
by late Tuesday or early Wednesday. On the forecast track, the 
center of Humberto will pass west, and then north of Bermuda on 
Tuesday and Wednesday.
 
Maximum sustained winds are near 145 mph (230 km/h) with higher 
gusts. Humberto is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Fluctuations in intensity are possible today. 
Gradual weakening is forecast after that, but Humberto is expected 
to remain a dangerous major hurricane into Tuesday.
 
Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 185
miles (295 km).
 
The estimated minimum central pressure is 940 mb (27.76 inches) 
based on Air Force Reserve reconnaissance dropsonde data.
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Humberto can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT3 and WMO header
WTNT43 KNHC.
 
SURF:  Swells generated by Humberto will continue to affect portions
of the northern Leeward Islands, the Virgin Islands, Puerto Rico,
and Bermuda through much of this week. Swells from Humberto will
also affect the U.S. East Coast beginning today. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at3.shtml?ripCurrents
 
WIND: Tropical storm conditions are possible on Bermuda beginning
Tuesday.
 
RAINFALL: Hurricane Humberto is expected to bring rainfall of 1 to
2 inches – 25 to 50 mm – to Bermuda Monday night through Tuesday
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.
 
$$
Forecaster Kelly
  