000
WTNT34 KNHC 270842
TCPAT4
 
BULLETIN
Potential Tropical Cyclone Nine Advisory Number   3
NWS National Hurricane Center Miami FL       AL092025
500 AM EDT Sat Sep 27 2025
 
...DISTURBANCE HAS BECOME A LITTLE BETTER ORGANIZED...
...EXPECTED TO BECOME A TROPICAL STORM AND PRODUCE SIGNIFICANT
RAINFALL OVER PORTIONS OF EASTERN CUBA AND THE BAHAMAS...
 
 
SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...21.9N 75.8W
ABOUT 155 MI...250 KM NW OF THE EASTERN TIP OF CUBA
ABOUT 115 MI...190 KM S OF THE CENTRAL BAHAMAS
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of the Bahamas has issued a Tropical 
Storm Warning for portions of the northwestern Bahamas, including 
Eleuthera, New Providence, the Abacos, Berry Islands, Andros 
Island, and Grand Bahama Island.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Central Bahamas, including Cat Island, the Exumas, Long Island,
Rum Cay, and San Salvador
* Portions of the northwestern Bahamas, including Eleuthera, New
Providence, the Abacos, Berry Islands, Andros island, and Grand 
Bahama Island
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, within 36 hours.
 
Interests elsewhere in the Bahamas and along the southeast coast of 
the United States from Florida to North Carolina should monitor the 
progress of this system.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the disturbance was centered near latitude
21.9 North, longitude 75.8 West. The system is moving toward the
northwest near 7 mph (11 km/h). A north-northwestward motion is 
expected to begin later today and continue through Monday.  On the 
forecast track, the center of the system is expected to move across 
the central and northwestern Bahamas this weekend and approach the 
southeast U.S. coast early next week.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
The system is expected to become a tropical depression by
tonight. Gradual strengthening is forecast thereafter, with the
system becoming a tropical storm by early Sunday, and a hurricane
by late Monday.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 7 days...high...90 percent.
 
The estimated minimum central pressure is 1007 mb (29.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Nine can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and
WMO header WTNT44 KNHC.
 
WIND:  Tropical storm conditions are expected in the central Bahamas
beginning tonight or early Sunday and are possible in portions of
the northwestern Bahamas on Sunday.
 
RAINFALL: The disturbance is expected to produce 8 to 12 inches,
with isolated maximum totals of 16 inches possible to eastern Cuba
and 4 to 8 inches of rain to the Bahamas.  This rainfall will likely
produce flash and urban flooding. Mudslides are also possible in
areas of higher terrain across eastern Cuba, Hispaniola, and
Jamaica.
 
Moisture from the disturbance is leading to a threat of heavy
rainfall from this system well to the north across portions of the
Southeast and Virginia into early next week which could cause flash,
urban, and river flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Potential Tropical Cyclone Nine, please see the
National Weather Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf.
 
STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level along the immediate coast in areas of
onshore winds in the northwestern Bahamas. Near the coast, the
surge will be accompanied by large waves.
 
SURF:  Swells generated by both this system and Hurricane Humberto
will affect portions of the Bahamas this weekend, and spread to 
portions of the southeast U.S. coast early next week.  These swells 
are likely to cause life-threatening surf and rip current 
conditions.  Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Beven
  