000
WTNT34 KNHC 271150
TCPAT4
 
BULLETIN
Potential Tropical Cyclone Nine Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       AL092025
800 AM EDT Sat Sep 27 2025
 
...DISTURBANCE GRADUALLY BECOMING BETTER ORGANIZED...
...EXPECTED TO BECOME A TROPICAL STORM AND PRODUCE SIGNIFICANT
RAINFALL OVER PORTIONS OF EASTERN CUBA AND THE BAHAMAS...
 
 
SUMMARY OF 800 AM EDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...22.0N 75.9W
ABOUT 170 MI...275 KM NW OF THE EASTERN TIP OF CUBA
ABOUT 110 MI...180 KM S OF THE CENTRAL BAHAMAS
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Central Bahamas, including Cat Island, the Exumas, Long Island,
Rum Cay, and San Salvador
* Portions of the northwestern Bahamas, including Eleuthera, New
Providence, the Abacos, Berry Islands, Andros island, and Grand
Bahama Island
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, within 36 hours.
 
Interests elsewhere in the Bahamas and along the southeast coast of
the United States from Florida to North Carolina should monitor the
progress of this system.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM EDT (1200 UTC), the disturbance was centered near latitude 
22.0 North, longitude 75.9 West. The system is moving toward the 
northwest near 7 mph (11 km/h). A north-northwestward motion is 
expected to begin later today and continue through Monday. On the 
forecast track, the center of the system is expected to move across 
the central and northwestern Bahamas this weekend and approach the 
southeast U.S. coast early next week.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher gusts. 
The system is expected to become a tropical depression or storm 
later today or tonight. Gradual strengthening is expected 
thereafter, with the system forecast to become a hurricane by late 
Monday.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 7 days... high...90 percent.
 
The estimated minimum central pressure based on NOAA Hurricane 
Hunter dropsonde data is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Nine can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and
WMO header WTNT44 KNHC.
 
WIND:  Tropical storm conditions are expected in the central Bahamas
beginning tonight or early Sunday and in the northwestern Bahamas 
on Sunday.
 
RAINFALL: The disturbance is expected to produce rainfall amounts of 
8 to 12 inches with isolated maximum totals of 16 inches possible 
in eastern Cuba, and 4 to 8 inches of rain in the Bahamas. This 
rainfall will likely produce flash and urban flooding. Mudslides 
are also possible in areas of higher terrain across eastern Cuba, 
Hispaniola, and Jamaica.
 
Moisture from the disturbance will lead to a threat of heavy 
rainfall well to the north across portions of the Southeast U.S. and 
Virginia into early next week which could cause flash, urban, and 
river flooding.
 
For a complete depiction of forecast rainfall and flash flooding
associated with the system, please see the National Weather Service 
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf.
 
STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level along the immediate coast in areas of
onshore winds in the northwestern Bahamas. Near the coast, the
surge will be accompanied by large waves.
 
SURF: Swells generated by both this system and Hurricane Humberto 
will affect portions of the Bahamas this weekend, and spread to 
portions of the southeast U.S. coast early next week. These swells 
are likely to cause life-threatening surf and rip current 
conditions. Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Reinhart
  