000
WTNT34 KNHC 280854
TCPAT4
 
BULLETIN
Tropical Depression Nine Advisory Number   7
NWS National Hurricane Center Miami FL       AL092025
500 AM EDT Sun Sep 28 2025
 
...DEPRESSION FORECAST TO BRING HEAVY RAINS OVER PORTIONS OF 
EASTERN CUBA AND THE BAHAMAS TODAY, WITH WINDS INCREASING OVER THE 
BAHAMAS LATER TODAY...
 
 
SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...23.0N 77.2W
ABOUT 275 MI...440 KM NW OF THE EASTERN TIP OF CUBA
ABOUT 100 MI...160 KM WSW OF THE CENTRAL BAHAMAS
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Central Bahamas, including Cat Island, the Exumas, Long Island,
Rum Cay, and San Salvador
* Portions of the northwestern Bahamas, including Eleuthera, New
Providence, the Abacos, Berry Islands, Andros island, and Grand
Bahama Island
 
A Tropical Storm Watch is in effect for...
* East coast of Florida from the Palm Beach/Martin County Line to
the Flagler/Volusia County Line
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in the Bahamas and along the southeast coast of
the United States from Florida to North Carolina should monitor the
progress of this system. Additional watches or warnings could be
required later today.
 
For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Tropical Depression Nine was
located near latitude 23.0 North, longitude 77.2 West. The
depression is moving toward the north-northwest near 7 mph (11 km/h)
A faster motion to the north-northwest is expected to begin later
today and continue through Monday. On the forecast track, the center
of the system is expected to move across the central and
northwestern Bahamas today and tonight and approach the southeast
U.S. coast early this week.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Strengthening is expected during the next few days, and the
system is forecast to become a tropical storm later today and a
hurricane by late Monday or Tuesday.

Reports from an Air Force Reserve Hurricane Hunter aircraft 
indicate that the estimated minimum central pressure is 1003 mb 
(29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Nine can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC.
 
WIND: Tropical storm conditions are expected in the central Bahamas
beginning later today and in the northwestern Bahamas late this
afternoon. Tropical storm conditions are possible in the watch area
along the east coast of Florida on Monday.
 
RAINFALL: Tropical Depression Nine is expected to produce 
additional rainfall of 4 to 8 inches across eastern Cuba and 6 to 12 
inches across the northwest Bahamas through Tuesday. This rainfall 
will likely produce flash and urban flooding. Mudslides are also 
possible in areas of higher terrain across eastern Cuba.

Storm total rainfall amounts of 2 to 4 inches with local maxima of 7 
inches are expected into Wednesday morning across portions of the 
coastal Carolinas. This rainfall could result in flash, urban, and 
river flooding. Changes in the forecast track could result in 
further adjustments to these rainfall totals.

For a complete depiction of forecast rainfall and flash flooding 
associated with Tropical Depression Nine, please see the National 
Weather Service Storm Total Rainfall Graphic, available at 
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk 
graphic at hurricanes.gov/graphics_at4.shtml?ero
 
STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level along the immediate coast in areas of
onshore winds in the northwestern Bahamas. Near the coast, the
surge will be accompanied by large waves.
 
SURF: Swells generated by this system and Hurricane Humberto will
affect portions of the Bahamas this weekend, and spread to portions
of the southeast U.S. coast early this week. These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Blake
  