707 
WTNT34 KNHC 282048
TCPAT4
 
BULLETIN
Tropical Storm Imelda Advisory Number   9
NWS National Hurricane Center Miami FL       AL092025
500 PM EDT Sun Sep 28 2025
 
...IMELDA MOVING NORTHWARD WITH TROPICAL STORM CONDITIONS ONGOING
FOR THE CENTRAL AND NORTHWESTERN BAHAMAS...
 
 
SUMMARY OF 500 PM EDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...24.2N 77.3W
ABOUT  55 MI...90 KM SSW OF THE NORTHWEST BAHAMAS
ABOUT 355 MI...570 KM SE OF CAPE CANAVERAL FLORIDA
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Tropical Storm Watch has been discontinued for the east coast of
Florida from Palm Beach/Martin County Line to the Flagler/Volusia
County Line.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Central Bahamas, including Cat Island, the Exumas, Long Island,
Rum Cay, and San Salvador
* Portions of the northwestern Bahamas, including Eleuthera, New
Providence, the Abacos, Berry Islands, Andros island, and Grand
Bahama Island
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, within 36 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM EDT (2100 UTC), the center of Tropical Storm Imelda was
located near latitude 24.2 North, longitude 77.3 West. Imelda is
moving toward the north near 9 mph (15 km/h), and faster northward
motion is expected tonight continuing through Monday. On Tuesday,
Imelda is expected to turn sharply to the east-northeast. On the
forecast track, the center of the system is expected to move across
the central and northwestern Bahamas this afternoon and tonight and
then turn east-northeastward, moving away from the southeastern U.S.
by the middle part of this week.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Strengthening is expected during the next few days, and Imelda is
forecast to become a hurricane by late Monday or Tuesday.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km) 
from the center. Recently, a WeatherSTEM station observed sustained 
wind of 39 mph (63 km/h) with a gust to 47 mph (76 km/h) at Blue 
Lagoon Island just northeast of Nassau, Bahamas. 
 
The estimated minimum central pressure is 998 mb (29.47 inches). 
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Imelda can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC.
 
WIND: Tropical storm conditions are occuring in the central and 
northwestern Bahamas and should continue through Monday morning. 
 
RAINFALL: Tropical Storm Imelda is expected to produce additional 
rainfall of 2 to 4 inches across eastern Cuba and 4 to 8 inches 
across the northwest Bahamas through Tuesday. This rainfall will 
likely produce flash and urban flooding. Mudslides are also possible 
in areas of higher terrain across eastern Cuba.

Storm total rainfall amounts of 2 to 4 inches with local maxima of 6 
inches are expected through Tuesday across coastal South Carolina 
into southeast North Carolina. This rainfall could result in 
isolated flash, urban, and minor river flooding.

For a complete depiction of forecast rainfall and flash flooding
associated with this system, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at4.shtml?ero
 
STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level along the immediate coast in areas of
onshore winds in the northwestern Bahamas. Near the coast, the
surge will be accompanied by large waves.
 
Minor coastal flooding is possible in areas of onshore winds over
the Southeastern U.S. coastline. The water could reach the
following heights above ground somewhere in the indicated areas if
the surge occurs over the next several high tide cycles...
 
Volusia/Brevard County Line, Florida to the South Santee River,
South Carolina...1 to 2 ft
 
SURF: Swells generated by Tropical Storm Imelda and Hurricane
Humberto will affect portions of the Bahamas this weekend, and
spread to much of the east coast of the U.S. early this week. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM EDT.
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Papin
  