000
WTNT34 KNHC 291454
TCPAT4
 
BULLETIN
Tropical Storm Imelda Advisory Number  12
NWS National Hurricane Center Miami FL       AL092025
1100 AM EDT Mon Sep 29 2025
 
...IMELDA STRENGTHENING...
...TROPICAL STORM CONDITIONS CONTINUE FOR THE NORTHWEST BAHAMAS AND 
INTERESTS IN BERMUDA SHOULD CLOSELY MONITOR IMELDA...
 
 
SUMMARY OF 1100 AM EDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...26.9N 77.1W
ABOUT 35 MI...55 KM N OF GREAT ABACO ISLAND
ABOUT 240 MI...385 KM ESE OF CAPE CANAVERAL FLORIDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Portions of the Northwestern Bahamas, including Eleuthera, the
Abacos, Grand Bahama Island and the surrounding keys.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area in this case within 12
hours.
 
Interests in Bermuda should monitor the progress of Imelda.
Hurricane watches could be required for the island as soon as this
afternoon.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM EDT (1500 UTC), the center of Tropical Storm Imelda was 
located by NOAA and Air Force Reconnaissance aircraft near latitude 
26.9 North, longitude 77.1 West. Imelda is moving toward the north 
near 9 mph (15 km/h), and a general northward motion is expected to 
continue today. On Tuesday, Imelda is expected to turn sharply to 
the east-northeast. On the forecast track, the center of the system 
is expected to start moving away from the northwestern Bahamas today 
and then turn east-northeastward, moving away from the southeastern 
U.S. by the middle part of this week, but approaching the island of 
Bermuda.
 
Maximum sustained winds have increased to near 60 mph (95 km/h)
with higher gusts. Additional strengthening is forecast and Imelda
is forecast to become a hurricane on Tuesday. 

Tropical-storm-force winds extend outward up to 175 miles (280 km) 
from the center. This morning, a sustained wind of 48 mph (77 km/h) 
was reported at Little Hog Cay, in North Abacos, Bahamas. A wind 
gust of 83 mph (134 km/h) was also recently reported in Treasure 
Cay, Bahamas.
 
The minimum central pressure estimated by Air Force Reconnaissance 
dropsonde data is is 988 mb (29.18 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Imelda can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC.
 
WIND: Tropical storm conditions are occuring in portions of
the northwestern Bahamas and should continue through today.
 
RAINFALL:  Tropical Storm Imelda is expected to produce total 
rainfall of 4 to 8 inches across the northwest Bahamas through 
Tuesday. This rainfall will likely produce flash and urban 
flooding. 

Storm total rainfall amounts of 1 to 2 inches with local maxima of 4 
inches are expected through Tuesday across northeast Florida, 
coastal South Carolina, and coastal sections of southeast North 
Carolina. This rainfall could result in isolated flash and urban 
flooding.

As Imelda passes near Bermuda, 2 to 4 inches – 50 to 100 mm – of 
rainfall is expected from Wednesday into Thursday.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Tropical Storm Imelda, please see the National
Weather Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at4.shtml?ero
 
STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level along the immediate coast in areas of
onshore winds in the northwestern Bahamas.  Near the coast, the
surge will be accompanied by large waves.
 
Minor coastal flooding is possible in areas of onshore winds over
the Southeastern U.S. coastline. The water could reach the
following heights above ground somewhere in the indicated areas if
the surge occurs over the next several high tide cycles...
 
Volusia/Brevard County Line, Florida to the South Santee River,
South Carolina...1 to 2 ft
 
SURF: Swells generated by Tropical Storm Imelda and Hurricane
Humberto are affecting the Bahamas and will spread to much of the
east coast of the U.S. early this week. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM EDT.
Next complete advisory at 500 PM EDT.
 
$$
Forecaster Papin
  