000
WTNT34 KNHC 292351
TCPAT4
 
BULLETIN
Tropical Storm Imelda Intermediate Advisory Number 13A
NWS National Hurricane Center Miami FL       AL092025
800 PM EDT Mon Sep 29 2025
 
...IMELDA FORECAST TO BECOME A HURRICANE TOMORROW MORNING...
...TROPICAL STORM CONDITIONS CONTINUE OVER THE ABACOS...
 
 
SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...28.1N 77.3W
ABOUT 120 MI...190 KM N OF GREAT ABACO ISLAND
ABOUT 200 MI...325 KM E OF CAPE CANAVERAL FLORIDA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None. 
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Bermuda
 
A Tropical Storm Warning is in effect for...
* Extreme Northwestern Bahamas, including Great Abaco, Grand Bahama
Island and the surrounding keys.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area in this for the next few
hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Tropical Storm Imelda was 
located near latitude 28.1 North, longitude 77.3 West. Imelda is 
moving toward the north near 9 mph (15 km/h), and a general 
northward motion is expected to continue tonight. On Tuesday, Imelda 
is expected to turn sharply to the east-northeast and accelerate. On 
the forecast track, the center of the system should move away from 
the northwestern Bahamas later this evening and then turn 
east-northeastward, moving away from the southeastern U.S. but 
approaching the island of Bermuda on Wednesday. 
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Strengthening is forecast over the next few days, and 
Imelda is forecast to become a hurricane on Tuesday morning. 
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center. A combination of Air Force Reserve Hurricane 
Hunter aircraft data and private weather station data indicate 
that tropical-storm conditions are still occurring on Great Abaco 
and the adjacent islands.
 
The minimum central pressure estimated from Air Force Reserve 
Hurricane Hunter aircraft data is 985 mb (29.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Imelda can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area by
Wednesday night, with tropical storm conditions possible by
Wednesday afternoon.
 
Tropical storm conditions are occuring in portions of the extreme
northwestern Bahamas and should continue for the next few hours.
 
RAINFALL:  Tropical Storm Imelda is expected to produce additional
rainfall of 1 to 3 inches across the northwest Bahamas through
tonight. This rainfall may produce flash and urban flooding.
 
Storm total rainfall amounts of 1 to 2 inches with local maxima of 4
inches are expected through tonight across northeast Florida,
coastal South Carolina, and coastal sections of southeast North
Carolina. This rainfall could result in isolated flash and urban
flooding.
 
As Imelda passes near Bermuda, 2 to 4 inches – 50 to 100 mm – of
rainfall is expected from Wednesday into Thursday.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Tropical Storm Imelda, please see the National
Weather Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at4.shtml?ero
 
STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level along the immediate coast in areas of
onshore winds in the northwestern Bahamas.  Near the coast, the
surge will be accompanied by large waves.
 
Minor coastal flooding is possible in areas of onshore winds over
the Southeastern U.S. coastline. The water could reach the
following heights above ground somewhere in the indicated areas if
the surge occurs over the next several high tide cycles...
 
Volusia/Brevard County Line, Florida to the South Santee River,
South Carolina...1 to 2 ft
 
SURF: Swells generated by Tropical Storm Imelda and Hurricane
Humberto are affecting the Bahamas and are currently spreading to
much of the U.S. east coast. These swells are likely to 
cause life-threatening surf and rip current conditions. Please 
consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Beven
  