000
WTNT34 KNHC 300858
TCPAT4
 
BULLETIN
Tropical Storm Imelda Advisory Number  15
NWS National Hurricane Center Miami FL       AL092025
500 AM EDT Tue Sep 30 2025
 
...IMELDA LIKELY TO BE A HURRICANE NEAR BERMUDA LATE ON WEDNESDAY...
 
 
SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...28.8N 76.8W
ABOUT 165 MI...270 KM N OF GREAT ABACO ISLAND
ABOUT 755 MI...1210 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...981 MB...28.97 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Bermuda
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  

A Hurricane Warning could be required later today for Bermuda.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Tropical Storm Imelda was
located near latitude 28.8 North, longitude 76.8 West. Imelda is
moving toward the northeast near 7 mph (11 km/h).  This general 
motion is expected today, followed by a turn towards the east- 
northeast at a faster forward speed by tonight. On the forecast 
track, the center of the system should move away from the Bahamas 
today and quickly be approaching Bermuda late on Wednesday.
 
Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts.  Imelda should become a hurricane later today, with further 
strengthening anticipated on Wednesday.  
 
Tropical-storm-force winds extend outward up to 185 miles (295 km)
from the center.
 
The estimated minimum central pressure is 981 mb (28.97 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Imelda can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area by
Wednesday night, with tropical storm conditions possible by
Wednesday afternoon.
 
RAINFALL:  Storm total rainfall amounts of 1 to 2 inches with local
maxima of 4 inches are expected through tonight across coastal
sections of southeast North Carolina. This rainfall could result in
isolated flash and urban flooding.
 
As Imelda passes near Bermuda, 2 to 4 inches – 50 to 100 mm – of
rainfall is expected from Wednesday into Thursday.
 
STORM SURGE: Minor coastal flooding is possible in areas of onshore
winds over the Southeastern U.S. coastline. The water could reach
the following heights above ground somewhere in the indicated areas
if the surge occurs over the next several high tide cycles...
 
Volusia/Brevard County Line, Florida to the South Santee River,
South Carolina...1 to 2 ft
 
SURF: Swells generated by Tropical Storm Imelda and Hurricane
Humberto are affecting the Bahamas and are currently spreading to
much of the U.S. east coast. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Blake
  