181 
WTNT34 KNHC 302038
TCPAT4
 
BULLETIN
Hurricane Imelda Advisory Number  17
NWS National Hurricane Center Miami FL       AL092025
500 PM EDT Tue Sep 30 2025
 
...IMELDA EXPECTED TO BRING HURRICANE CONDITIONS TO BERMUDA BY
WEDNESDAY EVENING...
 
 
SUMMARY OF 500 PM EDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...29.4N 75.5W
ABOUT 665 MI...1070 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...ENE OR 60 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Bermuda
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM EDT (2100 UTC), the center of Hurricane Imelda was located
near latitude 29.4 North, longitude 75.5 West. Imelda is moving
toward the east-northeast near 12 mph (19 km/h).  A generally
east-northeastward motion at a faster forward speed is expected over
the next couple of days.  On the forecast track, the center of the
hurricane will approach Bermuda Wednesday afternoon.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Some additional strengthening is forecast during the next
day or so.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).
 
The estimated minimum central pressure is 978 mb (28.88 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Imelda can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.
 
WIND:  Hurricane conditions are expected over Bermuda by Wednesday
evening, with tropical storm conditions likely by Wednesday
afternoon.
 
RAINFALL:  Across Bermuda, 2 to 4 inches (50 to 100 mm) of rainfall
are expected from Wednesday into Thursday, which could lead to
flash flooding.
 
STORM SURGE:  In Bermuda, a dangerous storm surge is expected to
produce coastal flooding in areas of onshore winds.  The surge will
be accompanied by large and damaging waves.
 
SURF: Swells generated by Hurricane Imelda and Hurricane Humberto
are affecting the Bahamas and are currently spreading to much of the
U.S. east coast. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM EDT.
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Pasch
  