000
WTNT34 KNHC 302346
TCPAT4
 
BULLETIN
Hurricane Imelda Intermediate Advisory Number 17A
NWS National Hurricane Center Miami FL       AL092025
800 PM EDT Tue Sep 30 2025
 
...IMELDA HEADED TOWARD BERMUDA...
...EXPECTED TO BRING HURRICANE CONDITIONS TO THE ISLAND BY 
WEDNESDAY EVENING...
 
 
SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...29.4N 74.9W
ABOUT 630 MI...1015 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...ENE OR 70 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Bermuda
 
A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area.  A warning is typically issued  
36 hours before the anticipated first occurrence of 
tropical-storm-force winds, conditions that make outside 
preparations difficult or dangerous.  Preparations to protect life 
and property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Hurricane Imelda was located 
near latitude 29.4 North, longitude 74.9 West.  Imelda is moving 
toward the east-northeast near 12 mph (19 km/h).  An east-northeast 
to northeast motion at a faster forward speed is expected over the 
next couple of days.  On the forecast track, the center of the 
hurricane will be near Bermuda Wednesday afternoon or evening.
 
Maximum sustained winds remain near 85 mph (140 km/h) with higher 
gusts.  Some additional strengthening is forecast during the next 
day or so.  Imelda is then expected to become an extratropical low 
in a couple of days.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from
the center and tropical-storm-force winds extend outward up to 160
miles (260 km).
 
The estimated minimum central pressure based on data from the Air 
Force Hurricane Hunters is 978 mb (28.88 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Imelda can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.
 
WIND:  Hurricane conditions are expected over Bermuda by Wednesday
evening, with tropical storm conditions likely by Wednesday 
afternoon.
 
RAINFALL:  Across Bermuda, 2 to 4 inches (50 to 100 mm) of rainfall
are expected from Wednesday into Thursday, which could lead to
flash flooding.
 
STORM SURGE:  In Bermuda, a dangerous storm surge is expected to
produce coastal flooding in areas of onshore winds.  The surge will
be accompanied by large and damaging waves.
 
SURF: Swells generated by Hurricane Imelda and Hurricane Humberto 
are affecting the Bahamas, Bermuda, and much of the U.S. east coast. 
These swells are likely to cause life-threatening surf and rip 
current conditions.  Please consult products from your local weather 
office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Cangialosi
  