972 
WTNT34 KNHC 010545
TCPAT4
 
BULLETIN
Hurricane Imelda Intermediate Advisory Number 18A
NWS National Hurricane Center Miami FL       AL092025
200 AM EDT Wed Oct 01 2025
 
...IMELDA EXPECTED TO BRING HURRICANE-FORCE WINDS TO BERMUDA LATE 
TODAY...
 
 
SUMMARY OF 200 AM EDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...29.9N 73.1W
ABOUT 520 MI...835 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...ENE OR 75 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Bermuda
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM EDT (0600 UTC), the eye of Hurricane Imelda was located
near latitude 29.9 North, longitude 73.1 West. Imelda is moving
toward the east-northeast near 17 mph (28 km/h).  A much faster 
east-northeast to northeast motion is expected over the next
couple of days.  On the forecast track, the core of the hurricane
will be near Bermuda this afternoon or evening.
 
Data from an Air Force Reserve Hurricane Hunter mission indicate 
that the maximum sustained winds remain near 85 mph (140 km/h) with 
higher gusts.  Some strengthening is forecast during the next day 
or so.  Imelda is then expected to become an extratropical low in a 
couple of days.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from
the center and tropical-storm-force winds extend outward up to 160
miles (260 km).
 
The estimated minimum central pressure is 976 mb (28.82 inches) 
based on dropsonde data.
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Imelda can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.
 
WIND:  Hurricane conditions are expected over Bermuda by this
evening, with tropical storm conditions likely by this afternoon.
 
RAINFALL:  Across Bermuda, 2 to 4 inches (50 to 100 mm) of rainfall
are expected from later today into Thursday, which could lead to
flash flooding.
 
STORM SURGE:  In Bermuda, a dangerous storm surge is expected to
produce coastal flooding in areas of onshore winds.  The surge will
be accompanied by large and damaging waves.
 
SURF: Swells generated by Hurricane Imelda and Hurricane Humberto
are affecting the Bahamas, Bermuda, and much of the U.S. east coast.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Blake
  