819 
WTNT34 KNHC 011454
TCPAT4
 
BULLETIN
Hurricane Imelda Advisory Number  20
NWS National Hurricane Center Miami FL       AL092025
1100 AM EDT Wed Oct 01 2025
 
...AIR FORCE HURRICANE HUNTERS FIND IMELDA HAS STRENGTHENED...
...EXPECTED TO BRING HURRICANE-FORCE WINDS, DAMAGING WAVES, AND
FLASH FLOODING TO BERMUDA LATER TODAY AND TONIGHT...
 
 
SUMMARY OF 1100 AM EDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...31.0N 70.4W
ABOUT 340 MI...550 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...966 MB...28.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Bermuda
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. Preparations to protect life
and property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM EDT (1500 UTC), the center of Hurricane Imelda was 
located near latitude 31.0 North, longitude 70.4 West. Imelda is 
moving toward the east-northeast near 20 mph (31 km/h), and this 
general motion with some increase in forward speed is expected to 
continue through late Thursday. A turn toward the northeast is 
forecast on Friday and into the weekend. On the forecast track, the 
core of the hurricane will be near Bermuda this evening and tonight 
and move away from the island by Thursday afternoon.
 
Air Force Hurricane Hunter aircraft data indicate that maximum 
sustained winds have increased to near 100 mph (155 km/h) with 
higher gusts. Some additional strengthening is possible before 
Imelda passes close to Bermuda tonight. Imelda is then expected to 
become an extratropical low on Thursday, with gradual weakening 
forecast thereafter.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 230 miles
(370 km).
 
The estimated minimum central pressure based on dropsonde data from
the Air Force Hurricane Hunters is 966 mb (28.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Imelda can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.
 
WIND: Hurricane conditions are expected over Bermuda tonight,
with tropical storm conditions likely by this afternoon.
 
RAINFALL: Across Bermuda, 2 to 4 inches (50 to 100 mm) of rainfall
is expected from later today into Thursday, which could lead to
flash flooding.
 
STORM SURGE: In Bermuda, a dangerous storm surge is expected to
produce coastal flooding in areas of onshore winds. The surge will
be accompanied by large and damaging waves.
 
SURF: Swells generated by Imelda are affecting the Bahamas, Bermuda, 
and much of the U.S. East Coast. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM EDT.
Next complete advisory at 500 PM EDT.
 
$$
Forecaster Reinhart
  