000
WTNT34 KNHC 020543
TCPAT4
 
BULLETIN
Hurricane Imelda Intermediate Advisory Number 22A
NWS National Hurricane Center Miami FL       AL092025
200 AM AST Thu Oct 02 2025
 
...IMELDA'S CORE NOW EAST-NORTHEAST OF BERMUDA WITH CONDITIONS ON 
THE ISLAND EXPECTED TO IMPROVE DURING THE NEXT SEVERAL HOURS...
 
 
SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...32.6N 63.5W
ABOUT 80 MI...125 KM ENE OF BERMUDA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...ENE OR 75 DEGREES AT 30 MPH...48 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Bermuda
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. Preparations to protect life
and property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Hurricane Imelda was located
near latitude 32.6 North, longitude 63.5 West. Imelda is moving
toward the east-northeast near 30 mph (48 km/h) and this general 
motion is expected to continue through tonight. A northeastward 
motion is then forecast on Friday and Saturday. On the forecast 
track, the core of Imelda will move away from Bermuda during the 
next several hours.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher
gusts.  Imelda is expected to become an extratropical low later 
today, with gradual weakening forecast thereafter.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 255
miles (405 km). During the past few hours, an elevated observing 
site at the National Museum of Bermuda reported sustained winds of 
78 mph (125 km/h) and a wind gust of 99 mph (159 km/h).
 
The estimated minimum central pressure is 973 mb (28.74 inches). 
Several stations on Bermuda reported minimum pressures of 975-977 
mb (28.79-28.85 inches) as the center of Imelda passed just south 
of the island.
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Imelda can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.
 
WIND: Hurricane conditions are ongoing over Bermuda and expected to
continue for a few more hours. 
 
RAINFALL: Across Bermuda, 2 to 4 inches (50 to 100 mm) of rainfall
is expected through today, which could lead to flash flooding.
 
STORM SURGE: In Bermuda, a dangerous storm surge is expected to
produce coastal flooding in areas of onshore winds. The surge will
be accompanied by large and damaging waves.
 
SURF: Swells generated by Imelda are affecting the Bahamas, Bermuda,
and much of the U.S. East Coast. Swells from Imelda will spread
toward the Greater Antilles and northern Leeward Islands on Friday
and continue through the weekend. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at4.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Beven
  