

086 
WTNT34 KNHC 211753
TCPAT4

BULLETIN
Potential Tropical Cyclone Nine Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       AL092023
100 PM CDT Mon Aug 21 2023

...DISTURBANCE EXPECTED TO BECOME A TROPICAL STORM BEFORE REACHING 
TEXAS...
...FLOODING RAINS AND COASTAL FLOODING ARE POSSIBLE...


SUMMARY OF 100 PM CDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...25.0N 91.0W
ABOUT 480 MI...770 KM ESE OF PORT MANSFIELD TEXAS
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Mouth of Rio Grande to Port O'Connor, Texas

A Tropical Storm Watch is in effect for...
* Port O'Connor to Sargent, Texas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 24 hours.

Interests elsewhere in eastern Texas and northern Mexico should
monitor the progress of this system.

For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.


DISCUSSION AND OUTLOOK
----------------------
At 100 PM CDT (1800 UTC), the disturbance was centered near latitude
25.0 North, longitude 91.0 West. The system is moving toward the
west near 16 mph (26 km/h).  A fast motion to the west is expected
to continue, and the system is forecast to move inland over south
Texas early Tuesday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Strengthening is forecast, and the system is expected to
become a tropical storm before it reaches the Texas coast.

Satellite images indicate that the system continues to become 
better organized and it is expected to become a tropical depression 
later today.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 7 days...high...90 percent.  

The estimated minimum central pressure is 1008 mb (29.77 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for the disturbance can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/text/MIATCDAT4.shtml.

RAINFALL:  Potential Tropical Cyclone Nine is expected to produce
storm total rainfall amounts of 3 to 5 inches, with isolated higher
amounts of 7 inches, across Southern Texas on Tuesday and Wednesday.
This rainfall could lead to areas of flash and urban flooding.

Across Mexico, storm total rainfall of 4 to 6 inches, with local
amounts of 10 inches, are expected across portions of Coahilla and
Nuevo Leon on Tuesday and Wednesday.  Areas of flash and
urban flooding are expected.

WIND: Tropical storm conditions are expected in the warning area
and are possible in the watch area by Tuesday morning.

STORM SURGE:  The combination of a storm surge and the tide will
cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...

Mouth of Rio Grande to Sargent, including Baffin Bay, Corpus
Christi Bay and Matagorda Bay...1 to 3 ft

The deepest water will occur along the immediate coast near and to
the north of the landfall location, where the surge will be
accompanied by large waves.  Surge-related flooding
depends on the relative timing of the surge and the tidal cycle,
and can vary greatly over short distances.  For information
specific to your area, please see products issued by your local
National Weather Service forecast office.

SURF: Large swells generated by the disturbance will affect
portions of southern Texas tonight through Tuesday.  These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Cangialosi


