

000
WTNT34 KNHC 200230
TCPAT4

BULLETIN
Potential Tropical Cyclone Four Advisory Number   2
NWS National Hurricane Center Miami FL       AL042022
1000 PM CDT Fri Aug 19 2022

...TROPICAL STORM CONDITIONS AND HEAVY RAINFALL EXPECTED IN
NORTHEASTERN MEXICO AND SOUTHERN TEXAS THIS WEEKEND...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.8N 95.2W
ABOUT 310 MI...500 KM SSE OF MOUTH OF THE RIO GRANDE
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1009 MB...29.80 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* The Gulf coast of Mexico from Boca de Catan northward to the
Mouth of the Rio Grande
* The lower Texas coast from Port Mansfield southward to the Mouth
of the Rio Grande

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the disturbance was centered near 
latitude 21.8 North, longitude 95.2 West. The system is moving 
toward the northwest near 14 mph (22 km/h), and this motion is 
expected to continue for the next couple of days.  The 
disturbance is expected to reach the coast of northeastern Mexico 
on Saturday and make landfall there Saturday night.

Maximum sustained winds remain near 35 mph (55 km/h) with higher 
gusts. Slow strengthening is expected through landfall, and the
disturbance is forecast to become a tropical storm on Saturday.
* Formation chance through 48 hours...high...80 percent.
* Formation chance through 5 days...high...80 percent.

The estimated minimum central pressure is 1009 mb (29.80 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Four can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC.

WIND: Tropical storm conditions are expected to occur in the
warning area beginning Saturday afternoon or evening.

RAINFALL: The disturbance is expected to produce total rainfall 
amounts of 3 to 6 inches, with isolated totals of 8 inches, along 
the eastern coast of Mexico from the northern portions of the state 
of Veracruz across the state of Tamaulipas to Nuevo Leon through 
Saturday. Rainfall of 2 to 4 inches will be possible in South Texas 
through Saturday night with continuing uncertainty in how far north 
and west these amounts will be realized. The potential exists for 
life-threatening mudslides in the mountains of Mexico and 
life-threatening flash flooding elsewhere along the track of the 
PTC Four.

STORM SURGE: The combination of storm surge and the tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...

Mouth of Rio Grande to Port Mansfield TX...1-2 ft

Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.

Storm surge could raise water levels by as much as 1 to 2 feet above
normal tide levels along the immediate coast of northeastern Mexico 
near and to the north of where the center makes landfall.

SURF: Swells generated by this system are forecast to affect eastern
Mexico and southern Texas this weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Bucci/Cangialosi

