

189 
WTNT34 KNHC 200831
TCPAT4

BULLETIN
Potential Tropical Cyclone Four Advisory Number   3
NWS National Hurricane Center Miami FL       AL042022
400 AM CDT Sat Aug 20 2022

...DISTURBANCE HEADING TOWARD THE TAMAULIPAS MEXICO COAST...
...HEAVY RAINS COULD CAUSE FLASH FLOODS ACROSS PORTIONS OF SOUTH 
TEXAS AND NORTHEASTERN MEXICO THROUGH SUNDAY MORNING...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...22.8N 95.8W
ABOUT 230 MI...370 KM SSE OF MOUTH OF THE RIO GRANDE
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1010 MB...29.83 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* The Gulf coast of Mexico from Boca de Catan northward to the
Mouth of the Rio Grande
* The Lower Texas coast from Port Mansfield southward to the Mouth
of the Rio Grande

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
the next 12 to 24 hours.

For storm information specific to your area in the United States, 
including possible inland watches and warnings, please monitor 
products issued by your local National Weather Service forecast 
office. For storm information specific to your area outside of the 
United States, please monitor products issued by your national 
meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the disturbance was centered near latitude
22.8 North, longitude 95.8 West.  The system is moving toward the
northwest near 14 mph (22 km/h).  A northwestward to 
north-northwestward motion at a similar forward speed is expected 
through Sunday.  On the forecast track, the disturbance is 
expected to reach the coast of northeastern Mexico late this 
afternoon and then move across the Rio Grande Valley tonight and 
Sunday.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
The disturbance could still strengthen slightly and become a 
tropical storm today before reaching the coast of northeastern 
Mexico.
* Formation chance through 48 hours...high...70 percent.
* Formation chance through 5 days...high...70 percent.

The estimated minimum central pressure is 1010 mb (29.83 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Four can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC.

WIND: Tropical storm conditions are expected to occur in the warning
area beginning this afternoon or evening.

RAINFALL: The disturbance is expected to produce total rainfall 
amounts of 1 to 3 inches, with isolated totals of 5 inches, along 
the eastern coast of Mexico from the northern portions of the state 
of Veracruz across the state of Tamaulipas to Nuevo Leon through 
today.  Rainfall of 1 to 3 inches will be possible in South Texas 
through Sunday morning, with continuing uncertainty in how far north 
and west these amounts will be realized.  The potential exists for 
flash flooding elsewhere along the track of the disturbance.

STORM SURGE: The combination of storm surge and the tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...

Mouth of Rio Grande to Port Mansfield TX...1-2 ft

Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.

Storm surge could raise water levels by as much as 1 to 2 feet above
normal tide levels along the immediate coast of northeastern Mexico
near and to the north of where the center makes landfall.

SURF: Swells generated by this system are forecast to affect eastern
Mexico and southern Texas this weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Berg


