

272 
WTNT34 KNHC 201431
TCPAT4

BULLETIN
Potential Tropical Cyclone Four Advisory Number   4
NWS National Hurricane Center Miami FL       AL042022
1000 AM CDT Sat Aug 20 2022

...DISTURBANCE HEADED TOWARD NORTHEASTERN MEXICO...
...HEAVY RAINS COULD CAUSE FLASH FLOODS ACROSS PORTIONS OF SOUTH
TEXAS AND NORTHEASTERN MEXICO THROUGH SUNDAY MORNING...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...23.6N 96.4W
ABOUT 165 MI...270 KM SSE OF MOUTH OF THE RIO GRANDE
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1010 MB...29.83 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* The Gulf coast of Mexico from Boca de Catan northward to the
Mouth of the Rio Grande
* The Lower Texas coast from Port Mansfield southward to the Mouth
of the Rio Grande

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
the next 12 to 24 hours.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the disturbance was centered near
latitude 23.6 North, longitude 96.4 West. The system is moving
toward the northwest near 13 mph (20 km/h) and this motion is
expected to continue, bringing the system across northeastern 
Mexico and southern Texas this evening through early Sunday.

Maximum sustained winds remain near 35 mph (55 km/h) with higher 
gusts. The disturbance could still strengthen slightly and become a
tropical storm later today before reaching the coast of northeastern
Mexico.
* Formation chance through 48 hours...medium...60 percent.
* Formation chance through 5 days...medium...60 percent.

The estimated minimum central pressure is 1010 mb (29.83 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Four can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC.

WIND: Tropical storm conditions are expected to occur in the warning
area beginning this afternoon or evening.

RAINFALL: The disturbance is expected to produce total rainfall
amounts of 1 to 3 inches, with isolated totals of 5 inches, along
the eastern coast of Mexico from the northern portions of the state
of Veracruz across the state of Tamaulipas to Nuevo Leon through
today.  Rainfall of 1 to 3 inches will be possible in South Texas
through Sunday morning, with continuing uncertainty in how far north
and west these amounts will be realized.  The potential exists for
flash flooding elsewhere along the track of the disturbance.

STORM SURGE: The combination of storm surge and the tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...

Mouth of Rio Grande to Port Mansfield TX...1-2 ft

Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.

Storm surge could raise water levels by as much as 1 to 2 feet above
normal tide levels along the immediate coast of northeastern Mexico
near and to the north of where the center makes landfall.

SURF: Swells generated by this system are forecast to affect eastern
Mexico and southern Texas today and Sunday. These swells are likely 
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Cangialosi/Latto


