

000
WTNT32 KNHC 020854
TCPAT2

BULLETIN
Subtropical Storm Patty Advisory Number   1
NWS National Hurricane Center Miami FL       AL172024
900 AM GMT Sat Nov 02 2024

...SUBTROPICAL STORM PATTY FORMS OVER THE NORTHERN ATLANTIC...
...EXPECTED TO PASS NEAR OR OVER THE AZORES THIS WEEKEND...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...39.9N 34.4W
ABOUT 420 MI...675 KM WNW OF THE AZORES
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...ESE OR 105 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...986 MB...29.12 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Subtropical Storm Patty was
located near latitude 39.9 North, longitude 34.4 West. The storm is
moving toward the east-southeast near 7 mph (11 km/h). A faster 
east-southeastward motion is expected through tonight, followed by 
a turn toward the east and east-northeast on Sunday and Monday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Little intensity change is expected today, but gradual weakening is 
forecast through early next week. Patty could degenerate into a 
post-tropical cyclone by late Sunday.

Winds of 40 mph extend outward up to 205 miles (335 km) from the
center.

The estimated minimum central pressure is 986 mb (29.12 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are possible in portions of the
Azores this weekend. See products issued by the meteorological
service in the Azores for more information.

RAINFALL: Patty is expected to produce rainfall amounts of 1 to 2 
inches, or 25 to 50 millimeters, across the Azores through Sunday.

SURF: Swells generated by Patty will affect the Azores over the next
couple of days. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.

$$
Forecaster Reinhart

