

000
WTNT32 KNHC 021738
TCPAT2

BULLETIN
Subtropical Storm Patty Intermediate Advisory Number 2A
NWS National Hurricane Center Miami FL       AL172024
600 PM GMT Sat Nov 02 2024

...PATTY NEARING THE AZORES... .
...EXPECTED TO BRING TROPICAL STORM CONDITIONS THERE TONIGHT AND 
SUNDAY...


SUMMARY OF 600 PM GMT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...38.2N 31.1W
ABOUT 225 MI...360 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...SE OR 125 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...982 MB...29.00 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* All of the Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 12 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 PM GMT (1800 UTC), the center of Subtropical Storm Patty was
located near latitude 38.2 North, longitude 31.1 West. The storm is
moving toward the southeast near 13 mph (20 km/h). A faster eastward
motion is expected during the next couple of days. On the forecast
track, the center of Patty is expected to move near or just south of
the Azores tonight and Sunday.

Maximum sustained winds remain near 65 mph (100 km/h) with higher 
gusts. Gradual weakening is expected during the next few days. 
Patty is forecast to become a post-tropical low by Sunday
night.

Winds of 40 mph extend outward up to 205 miles (335 km) from the
center.

The estimated minimum central pressure is 982 mb (29.00 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected in the Azores tonight
and Sunday. For more information, see products issued by the
meteorological service in the Azores.

RAINFALL: Patty is expected to produce rainfall amounts of 1 to 2
inches, or 25 to 50 millimeters, across the Azores through Sunday.

SURF: Swells generated by Patty will affect the Azores over the next
day or two. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Cangialosi

