

062 
WTNT32 KNHC 030232
TCPAT2

BULLETIN
Subtropical Storm Patty Advisory Number   4
NWS National Hurricane Center Miami FL       AL172024
300 AM GMT Sun Nov 03 2024

...PATTY CONTINUING TO PASS NEAR THE AZORES...
...EXPECTED TO BRING TROPICAL STORM CONDITIONS ACROSS THE AZORES
THROUGH THE WEEKEND...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...37.9N 27.8W
ABOUT 75 MI...115 KM SSW OF LAJES IN THE AZORES
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...E OR 95 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* All of the Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case through
the weekend.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Subtropical Storm Patty was
located near latitude 37.9 North, longitude 27.8 West. The storm is
moving toward the east near 20 mph (31 km/h), and an eastward to 
east-northeastward motion is expected during the next couple of 
days. On the forecast track, the center of Patty is expected to move 
near or just south of the Azores through the overnight period.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Gradual weakening is expected during the next few days. Patty is 
forecast to become a post-tropical low late this weekend or Monday.

Winds of 40 mph extend outward up to 205 miles (335 km) mainly to 
the southwest of the center.

The estimated minimum central pressure is 985 mb (29.09 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected in the Azores through
the weekend. For more information, see products issued by
the meteorological service in the Azores.

RAINFALL: RAINFALL: Patty is expected to produce rainfall amounts of
1 to 2 inches (25 to 50 millimeters) with local amounts to 4 inches
(100 mm) across the Azores through early Monday.

SURF: Swells generated by Patty will affect the Azores over the next
day or two. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM GMT.
Next complete advisory at 900 AM GMT.

$$
Forecaster Beven


