

000
WTNT32 KNHC 030840
TCPAT2

BULLETIN
Subtropical Storm Patty Advisory Number   5
NWS National Hurricane Center Miami FL       AL172024
900 AM GMT Sun Nov 03 2024

...PATTY VERY NEAR SAO MIGUEL ISLAND...
...TROPICAL STORM WARNINGS STILL IN EFFECT FOR THE AZORES...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...37.9N 26.0W
ABOUT 85 MI...140 KM SE OF LAJES AIR BASE IN THE AZORES
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...E OR 90 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.21 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* All of the Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Subtropical Storm Patty was 
located near latitude 37.9 North, longitude 26.0 West. The storm is 
moving toward the east near 18 mph (30 km/h), and an eastward to 
east-northeastward motion is expected during the next couple of 
days. On the forecast track, the center of Patty is expected to move 
near the southeastern Azores today.

Maximum sustained winds have decreased to near 50 mph (85 km/h)
with higher gusts. Additional weakening is expected during the next
couple of days. Patty is forecast to become a post-tropical low by
early Monday and dissipate by midweek.

Winds of 40 mph extend outward up to 175 miles (280 km), mainly
to the south and southwest of the center.

The estimated minimum central pressure is 989 mb (29.21 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected in the Azores through
today.

RAINFALL: Patty is expected to produce rainfall amounts of 1 to 2
inches (25 to 50 millimeters) with local amounts to 4 inches
(100 mm) across the Azores through early Monday.

SURF: Swells generated by Patty will affect the Azores through
tonight. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM GMT.
Next complete advisory at 300 PM GMT.

$$
Forecaster Reinhart

