

000
WTNT32 KNHC 031433
TCPAT2

BULLETIN
Subtropical Storm Patty Advisory Number   6
NWS National Hurricane Center Miami FL       AL172024
300 PM GMT Sun Nov 03 2024

...PATTY BEGINNING TO PULL AWAY FROM THE AZORES...
...EXPECTED TO BECOME A POST-TROPICAL CYCLONE LATER TODAY OR
TONIGHT...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...37.5N 24.3W
ABOUT 175 MI...285 KM ESE OF LAJES AIR BASE IN THE AZORES
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...E OR 100 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* All of the Azores

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Subtropical Storm Patty was
located near latitude 37.5 North, longitude 24.3 West. The storm is
moving toward the east near 16 mph (26 km/h) and an eastward to
east-northeastward motion is expected during the next couple of
days. On the forecast track, the center of Patty is expected to 
pull away from the Azores.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Weakening is expected during the next couple of days, and Patty is
forecast to become a post-tropical low later today or tonight.

Winds of 40 mph extend outward up to 80 miles (130 km) from the
center.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected in the Azores for the
next few hours.

RAINFALL: Patty is expected to produce rainfall amounts of 1 to 2
inches (25 to 50 millimeters) with local amounts to 4 inches
(100 mm) across the Azores through early Monday.

SURF: Swells generated by Patty will affect the Azores through
tonight. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM GMT.
Next complete advisory at 900 PM GMT.

$$
Forecaster Cangialosi

