

000
WTNT32 KNHC 032031
TCPAT2

BULLETIN
Subtropical Storm Patty Advisory Number   7
NWS National Hurricane Center Miami FL       AL172024
900 PM GMT Sun Nov 03 2024

...PATTY EXPECTED TO BECOME A POST-TROPICAL CYCLONE SOON...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...37.3N 22.3W
ABOUT 280 MI...450 KM ESE OF LAJES AIR BASE IN THE AZORES
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...E OR 95 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Subtropical Storm Patty was
located near latitude 37.3 North, longitude 22.3 West. The storm is
moving toward the east near 17 mph (28 km/h) and an eastward to
east-northeastward motion is expected during the next couple of
days.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Weakening is expected during the next couple of days, and Patty is
forecast to become a post-tropical low by early Monday.

Winds of 40 mph extend outward up to 80 miles (130 km) from the
center.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL: Patty is expected to produce additional rainfall amounts
of 1 to 2 inches (25 to 50 millimeters) across the Azores through
early Monday.

SURF: Swells generated by Patty will affect the Azores through
tonight. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM GMT.

$$
Forecaster Bucci

