

022 
WTPZ33 KNHC 142047
TCPEP3

BULLETIN
Hurricane Calvin Advisory Number  13
NWS National Hurricane Center Miami FL       EP032023
1100 AM HST Fri Jul 14 2023

...CALVIN STRENGTHENS A LITTLE MORE...


SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.8N 124.6W
ABOUT 1150 MI...1850 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Hawaii should monitor the progress of Calvin.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Calvin was 
located near latitude 13.8 North, longitude 124.6 West. Calvin is 
moving toward the west-northwest near 16 mph (26 km/h). This general 
motion is expected to continue for the next several days.

Maximum sustained winds have increased to near 125 mph (205 km/h) 
with higher gusts. Calvin is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Weakening is forecast to 
commence tomorrow and continue through early next week.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 955 mb (28.20 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/miatcdep3.shtml

SURF:  Swells generated by Calvin are expected to reach the Hawaiian
Islands early next week. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.

$$
Forecaster Reinhart


