

910 
WTPZ33 KNHC 150831
TCPEP3

BULLETIN
Hurricane Calvin Advisory Number  15
NWS National Hurricane Center Miami FL       EP032023
1100 PM HST Fri Jul 14 2023

...CALVIN WEAKENS FURTHER WHILE MOVING OVER THE OPEN TROPICAL
EASTERN PACIFIC...


SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.5N 127.5W
ABOUT 1285 MI...2070 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Hawaii should monitor the progress of Calvin.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Calvin was
located near latitude 14.5 North, longitude 127.5 West. Calvin is
moving toward the west-northwest near 16 mph (26 km/h), and this 
general motion is expected to continue for the next several days.

Maximum sustained winds have decreased to near 105 mph (165 km/h) 
with higher gusts.  Further weakening is expected through the 
middle part of next week.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/miatcdep3.shtml

SURF:  Swells generated by Calvin are expected to reach the Hawaiian
Islands early next week. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.

$$
Forecaster Roberts


