

000
WTPZ33 KNHC 151447
TCPEP3

BULLETIN
Hurricane Calvin Advisory Number  16
NWS National Hurricane Center Miami FL       EP032023
500 AM HST Sat Jul 15 2023

...CALVIN CONTINUES WEST-NORTHWESTWARD OVER THE EASTERN PACIFIC...


SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...14.7N 129.0W
ABOUT 1370 MI...2205 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Hawaii should monitor the progress of Calvin.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Calvin was located 
near latitude 14.7 North, longitude 129.0 West. Calvin is moving 
toward the west-northwest near 16 mph (26 km/h). A westward to 
west-northwestward motion at a similar forward speed is expected for 
the next several days. 

Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts. Weakening is forecast through early next week.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/miatcdep3.shtml

SURF:  Swells generated by Calvin are expected to begin reaching the 
Hawaiian Islands early next week. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.

$$
Forecaster Reinhart

