

000
WTPZ33 KNHC 160236
TCPEP3

BULLETIN
Hurricane Calvin Advisory Number  18
NWS National Hurricane Center Miami FL       EP032023
500 PM HST Sat Jul 15 2023

...CALVIN MOVING WEST-NORTHWESTWARD OVER OPEN WATERS...
...EXPECTED TO MOVE INTO THE CENTRAL PACIFIC BASIN EARLY MONDAY...


SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...15.4N 132.0W
ABOUT 1530 MI...2460 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 1550 MI...2490 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Hawaii should monitor the progress of Calvin.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Hurricane Calvin was located
near latitude 15.4 North, longitude 132.0 West. Calvin is moving
toward the west-northwest near 17 mph (28 km/h), and this general
motion at a similar or slightly faster forward speed is expected
during the next few days.  On the forecast track, the center of 
Calvin is expected to move into the central Pacific hurricane basin 
on Monday morning.

Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts.  Weakening is forecast through early next week.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/miatcdep3.shtml

SURF:  Swells generated by Calvin are expected to begin reaching the
Hawaiian Islands early next week. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.

$$
Forecaster Beven

