
ZCZC HFOTCPCP1 ALL
TTAA00 PHFO DDHHMM

BULLETIN
Tropical Storm Calvin Advisory Number  24
NWS Central Pacific Hurricane Center Honolulu HI   EP032023
500 AM HST Mon Jul 17 2023

...TROPICAL STORM CALVIN ENTERS THE CENTRAL PACIFIC...
...TROPICAL STORM WATCH ISSUED FOR HAWAII COUNTY...


SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...16.8N 141.4W
ABOUT 920 MI...1480 KM E OF HILO HAWAII
ABOUT 1120 MI...1805 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY...

A Tropical Storm Watch has been issued for Hawaii County.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT...

A Tropical Storm Watch is in effect for...
* Hawaii County

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in the case with the next 36 to 48
hours.

Interests elsewhere in Hawaii should monitor the progress of
Calvin.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Tropical Storm Calvin was
located near latitude 16.8 North, longitude 141.4 West. Calvin is
moving toward the west near 18 mph (30 km/h), and this general
motion is expected to continue during the next several days. Calvin 
is expected to approach the main Hawaiian Islands on Tuesday and 
early Wednesday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some additional weakening is forecast during the next few days.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header TCPCP1 and WMO header WTPA31 PHFO.
and on the web at hurricanes.gov/text/hfotcdcp1.shtml

RAINFALL: From Tuesday night into Thursday, storm total rainfall
amounts of 4-7 inches are possible along windward areas of the Big
Island of Hawaii, with lower amounts (1-4 inches) expected elsewhere
in the state.  This rainfall could lead to localized flash flooding
and mudslides.

SURF:  Swells generated by Calvin are expected to begin reaching the
main Hawaiian Islands during the next couple of days.  These swells
are likely to cause life-threatening surf. Please consult products
from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM HST.
Next complete advisory at 1100 AM HST.

$$
Forecaster Houston

NNNN
