

000
WTPA31 PHFO 172354
TCPCP1

BULLETIN
Tropical Storm Calvin Intermediate Advisory Number 25A
NWS Central Pacific Hurricane Center Honolulu HI   EP032023
200 PM HST Mon Jul 17 2023

...TROPICAL STORM CALVIN MOVING RAPIDLY WESTWARD...
...TROPICAL STORM WATCH REMAINS IN EFFECT FOR HAWAII COUNTY...


SUMMARY OF 200 PM HST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 144.4W
ABOUT 710 MI...1140 KM E OF HILO HAWAII
ABOUT 920 MI...1480 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY...

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT...

A Tropical Storm Watch is in effect for...
* Hawaii County

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in the case with the next 36 to 48
hours.

Interests elsewhere in Hawaii should monitor the progress of
Calvin.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM HST (0000 UTC), the center of Tropical Storm Calvin was
located near latitude 17.4 North, longitude 144.4 West. Calvin is
moving toward the west near 22 mph (35 km/h) and this motion is
expected to continue over the next several days. On the forecast
track, Calvin is expected to approach the main Hawaiian Islands on
Tuesday, with tropical storm conditions possible over some areas
starting Tuesday night.

Maximum sustained winds are near 50 mph (85 km/h) with higher
gusts. Calvin is forecast to gradually weaken during the next
several days.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header TCPCP1 and WMO header WTPA31 PHFO.
and on the web at hurricanes.gov/text/HFOTCDCP1.shtml

WIND: Tropical storm conditions are possible within the watch area
starting Tuesday.

RAINFALL: From Tuesday night into Thursday, storm total rainfall
amounts of 4-8 inches, with maximum amounts of 10 inches are 
possible, mainly along the windward areas of the Big Island of 
Hawaii. Storm total rainfall amounts of 1-4 inches are expected 
elsewhere in the state.  This rainfall could lead to localized flash 
flooding and mudslides.

SURF:  Swells generated by Calvin are expected to begin reaching the
main Hawaiian Islands during the next couple of days.  A rapid
increase in surf is expected Tuesday and Wednesday. This surf will
likely cause life-threatening surf along exposed east-facing shores.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.

$$
Forecaster Kodama
