

000
WTPA31 PHFO 182357
TCPCP1

BULLETIN
Tropical Storm Calvin Intermediate Advisory Number 29A
NWS Central Pacific Hurricane Center Honolulu HI   EP032023
200 PM HST Tue Jul 18 2023

...TROPICAL STORM CALVIN STRENGTHENS FURTHER...
...IMPACTS IN HAWAII COUNTY STARTING THIS EVENING...


SUMMARY OF 200 PM HST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...17.8N 152.3W
ABOUT 220 MI...355 KM SE OF HILO HAWAII
ABOUT 430 MI...690 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 21 MPH...34 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY...

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT...

A Tropical Storm Warning is in effect for...
* Hawaii County

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in Hawaii should monitor the progress of
Calvin.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM HST (0000 UTC), the center of Tropical Storm Calvin was
located near latitude 17.8 North, longitude 152.3 West. Calvin is
moving toward the west near 21 mph (34 km/h), and this general
motion is expected to continue over the next few days. On the
forecast track, tropical storm conditions will likely begin
spreading over Hawaii County starting this evening.

Maximum sustained winds are near 60 mph (95 km/h) with higher
gusts. Calvin is expected to remain a tropical storm over the next
36 hours, and then will weaken quickly afterward.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header TCDCP1 and WMO header WTPA41 PHFO.
and on the web at hurricanes.gov/text/HFOTCDCP1.shtml

WIND: Tropical storm conditions are expected within the warning
area starting this evening. Persons in Hawaii County should
complete preparations for tropical storm force wind impacts
during daylight hours prior to the onset of tropical storm
conditions.

RAINFALL: From later today into Thursday, storm total rainfall
amounts of 4-8 inches, with maximum amounts of 10 inches are
possible, mainly along the windward and southeast flank of the Big
Island of Hawaii. Storm total rainfall amounts of 3-6 inches are
expected on the windward areas of Maui, and 2-4 inches elsewhere in
the state. This rainfall could lead to localized flash flooding and
mudslides.

SURF: Swells generated by Calvin are expected to begin spreading
across the main Hawaiian Islands later today and tonight. This
will lead to a rapid increase in surf along east facing shores,
with high surf continuing into Wednesday. This elevated surf will
likely cause life-threatening conditions along exposed shorelines.
Please consult products from your local weather office for details.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.

$$
Forecaster Kodama

