

000
WTPA31 PHFO 190847
TCPCP1

BULLETIN
Tropical Storm Calvin Advisory Number  31
NWS Central Pacific Hurricane Center Honolulu HI   EP032023
1100 PM HST Tue Jul 18 2023

...TROPICAL STORM CALVIN BEGINNING TO PASS SOUTH OF THE BIG
ISLAND...
...IMPACTS IN HAWAII COUNTY ARE IMMINENT OR OCCURRING...


SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.7N 155.2W
ABOUT 140 MI...220 KM S OF HILO HAWAII
ABOUT 305 MI...490 KM SE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY...

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT...

A Tropical Storm Warning is in effect for...
* Hawaii County

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in Hawaii should monitor the progress of
Calvin.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Tropical Storm Calvin was
located near latitude 17.7 North, longitude 155.2 West. Calvin is
moving toward the west near 20 mph (31 km/h) and this motion is
expected to continue for the next few days.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some weakening is forecast during the next 48 hours. 

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Calvin can be found in the Tropical Cyclone
Discussion under AWIPS header TCDCP1 and WMO header WTPA41 PHFO.
and on the web at hurricanes.gov/text/HFOTCDCP1.shtml

WIND: Tropical storm conditions are imminent or occurring within
the warning area this evening. Preparations for tropical storm
force wind impacts should already be completed for persons
in Hawaii County. Seek shelter.

RAINFALL: Storm total rainfall amounts through Thursday are
forecasted to be 4-8 inches, with maximum amounts of 10 inches
possible, mainly along the windward slopes and southeast flank of
the Big Island of Hawaii. Storm total rainfall amounts of 3-6 inches
are expected on the windward areas of Maui, and 2-4 inches elsewhere
in the state. This rainfall could lead to localized flash flooding
and mudslides.

SURF: Swells generated by Calvin will spread across the main
Hawaiian Islands tonight. This will lead to a rapid increase in
surf along east facing shores, with high surf continuing
into Wednesday. This elevated surf will likely cause
life-threatening conditions along exposed shorelines. Please consult
products from your local weather office for details.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM HST.
Next complete advisory at 500 AM HST.

$$
Forecaster Powell

