000
WTNT35 KNHC 072033
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number   2
NWS National Hurricane Center Miami FL       AL102025
500 PM AST Tue Oct 07 2025
 
...TROPICAL STORM WATCHES ISSUED FOR PORTIONS OF THE NORTHERN
LEEWARD ISLANDS...
 
 
SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...12.0N 46.4W
ABOUT 1190 MI...1920 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Antigua and Barbuda has issued a Tropical Storm
Watch for Barbuda and Anguilla.  The government of France has
issued a Tropical Storm Watch for St. Barthelemy and St. Martin.
The government of Sint Maarten has issued a Tropical Storm Watch
for Sint Maarten.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Barbuda and Anguilla
* St. Barthelemy and St. Martin
* Sint Maarten
 
Interests elsewhere in the northern Leeward Islands, and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Jerry was 
located near latitude 12.0 North, longitude 46.4 West. Jerry is 
moving toward the west near 23 mph (37 km/h). A decrease in forward 
speed and a turn to the west-northwest is expected during the next 
couple of days.  On the forecast track, the core of the system is 
expected to be near or to the north of the northern Leeward Islands 
late Thursday and Friday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Steady strengthening is forecast, and Jerry is expected to become a
hurricane in a day or so.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are possible in portions of the
northern Leeward Islands late Thursday and Friday, where Tropical
Storm Watches have been issued.
 
RAINFALL: On Thursday, 2 to 4 inches of rain are expected across the 
Leeward Islands due to Jerry. This rainfall brings a risk of flash 
flooding, especially in areas of higher terrain.  

For a complete depiction of forecast rainfall and flash flooding 
associated with Priscilla, please see the National Weather Service 
Storm Total Rainfall Graphic, available at 
hurricanes.gov/graphics_al5.shtml?rainqpf
 
SURF:  Swells generated by Jerry are expected to reach the Leeward
Islands on Thursday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Cangialosi
  