000
WTNT35 KNHC 080234
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number   3
NWS National Hurricane Center Miami FL       AL102025
1100 PM AST Tue Oct 07 2025
 
...JERRY NOT WELL ORGANIZED WHILE MOVING QUICKLY 
WEST-NORTHWESTWARD...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...12.8N 48.7W
ABOUT 1030 MI...1655 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of France has issued a Tropical Storm 
Watch for Guadeloupe and the adjacent islands.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Antigua, Barbuda, and Anguilla
* St. Kitts, Nevis, and Montserrat
* St. Barthelemy and St. Martin
* Sint Maarten
* Saba and St. Eustatius
* Guadeloupe and the adjacent islands
 
Interests elsewhere in the northern Leeward Islands, and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Jerry was
located near latitude 12.8 North, longitude 48.7 West. Jerry is
moving toward the west-northwest near 23 mph (37 km/h). This 
general motion is expected to continue with a decrease in forward 
speed during the next couple of days. On the forecast track, the 
core of the system is expected to be near or to the north of the 
northern Leeward Islands late Thursday and Friday.
 
Recent satellite wind data indicate that maximum sustained winds 
are near 50 mph (85 km/h) with higher gusts. Strengthening is 
forecast during the next couple of days, and Jerry is expected to
become a hurricane by Wednesday night or Thursday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are possible in portions of the
northern Leeward Islands late Thursday and Friday, where Tropical
Storm Watches are in effect.
 
RAINFALL: On Thursday, 2 to 4 inches of rain are expected across the
Leeward Islands due to Jerry. This rainfall brings a risk of flash
flooding, especially in areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF:  Swells generated by Jerry are expected to reach the Leeward 
Islands on Thursday.  These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.
 
$$
Forecaster Beven
  