335 
WTNT35 KNHC 080541
TCPAT5
 
BULLETIN
Tropical Storm Jerry Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       AL102025
200 AM AST Wed Oct 08 2025
 
...JERRY RACING WEST-NORTHWESTWARD ACROSS THE CENTRAL ATLANTIC...
 
 
SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...13.1N 49.8W
ABOUT 950 MI...1530 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Antigua, Barbuda, and Anguilla
* St. Kitts, Nevis, and Montserrat
* St. Barthelemy and St. Martin
* Sint Maarten
* Saba and St. Eustatius
* Guadeloupe and the adjacent islands
 
Interests elsewhere in the northern Leeward Islands and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Tropical Storm Jerry was 
located near latitude 13.1 North, longitude 49.8 West. Jerry is 
moving toward the west-northwest near 23 mph (37 km/h). This general 
motion is expected to continue with a decrease in forward speed 
during the next couple of days, followed by a turn toward the 
north-northwest and north on Friday. On the forecast track, the core 
of the system is expected to be near or to the north of the northern 
Leeward Islands late Thursday and Friday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Strengthening is forecast during the next few days, and Jerry is 
expected to become a hurricane by late tonight or Thursday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are possible in portions of the
northern Leeward Islands within the watch area late Thursday and 
Friday.
 
RAINFALL: On Thursday, 2 to 4 inches of rain are expected across the
Leeward Islands due to Jerry. This rainfall brings a risk of flash
flooding, especially in areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are expected to reach the Leeward 
and Windward Islands on Thursday, then spread westward toward the 
Greater Antilles on Friday. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Reinhart
  