000
WTNT35 KNHC 081741
TCPAT5
 
BULLETIN
Tropical Storm Jerry Intermediate Advisory Number 5A
NWS National Hurricane Center Miami FL       AL102025
200 PM AST Wed Oct 08 2025
 
...AIR FORCE RESERVE HURRICANE HUNTERS INVESTIGATING JERRY...
 
 
SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...14.3N 53.7W
ABOUT 680 MI...1095 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Antigua, Barbuda, Anguilla, St. Kitts, Nevis, and Montserrat
* St. Barthelemy and St. Martin
* Sint Maarten
* Saba and St. Eustatius
* Guadeloupe and the adjacent islands
 
Interests elsewhere in the northern Leeward Islands and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Tropical Storm Jerry was
located near latitude 14.3 North, longitude 53.7 West.  Jerry is
moving toward the west-northwest near 23 mph (37 km/h), and this
general motion is expected to continue through early Thursday.  A
turn toward the northwest and then north at a slower forward speed
is expected late Thursday into Saturday.  On the forecast track,
the center of Jerry is expected to pass near or to the northeast of
the northern Leeward Islands late Thursday and Thursday night.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher
gusts.  Gradual strengthening is forecast during the next few days, 
and Jerry could become a hurricane by the weekend.
 
Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.  Jerry's center passed just to the south of NOAA 
buoy 41040, which measured a sustained wind of 47 mph (76 km/h) and 
a gust to 54 mph (86 km/h).
 
The estimated minimum central pressure based on data from NOAA 
buoy 41010 is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are possible in portions of the
northern Leeward Islands within the watch area late Thursday into
Friday.
 
RAINFALL: On Thursday into early Friday, 2 to 4 inches of rain with
local storm total maxima to 6 inches are expected across the Leeward
Islands, British Virgin Islands, and U.S. Virgin Islands from
Thursday into Saturday morning due to Jerry. This rainfall brings a
risk of flash flooding, especially in areas of steep terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are expected to reach the Leeward
and Windward Islands on Thursday, then spread westward toward the
Greater Antilles on Friday. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Berg
  