000
WTNT35 KNHC 082354
TCPAT5
 
BULLETIN
Tropical Storm Jerry Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       AL102025
800 PM AST Wed Oct 08 2025

...AIR FORCE RESERVE RECONNAISSANCE AIRCRAFT FINDS JERRY A LITTLE 
STRONGER...
...TROPICAL STORM CONDITIONS POSSIBLE ON PORTIONS OF THE NORTHERN
LEEWARD ISLANDS AS JERRY PASSES NEARBY LATE THURSDAY INTO FRIDAY...
 
 
SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...14.9N 55.4W
ABOUT 560 MI...900 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...65 MPH...105 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Antigua, Barbuda, Anguilla, St. Kitts, Nevis, and Montserrat
* St. Barthelemy and St. Martin
* Sint Maarten
* Saba and St. Eustatius
* Guadeloupe and the adjacent islands
 
Interests elsewhere in the northern Leeward Islands and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Tropical Storm Jerry was 
located by Air Force Reserve reconnaissance aircraft near latitude 
14.9 North, longitude 55.4 West. Jerry is moving quickly toward the 
west-northwest near 21 mph (33 km/h) and and this general motion is 
expected to continue through Thursday. A northwestward motion at a 
slower forward speed should begin Thursday night, followed by a 
northward motion Friday night and Saturday. On the forecast track, 
the center of Jerry is expected to pass near or to the northeast of 
the northern Leeward Islands late Thursday and Thursday night.
 
Aircraft dropsonde data indicates that maximum sustained winds have 
increased to near 65 mph (105 km/h) with higher gusts. Gradual 
strengthening is forecast during the next few days, and Jerry could 
become a hurricane late this week or this weekend.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.
 
The minimum central pressure estimated by Air Force Reserve 
dropsonde data is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are possible in portions of the
northern Leeward Islands within the watch area late Thursday into
Friday.
 
RAINFALL: On Thursday into early Friday, 2 to 4 inches of rain with
local storm total maxima to 6 inches are expected across the Leeward
Islands, British Virgin Islands, and U.S. Virgin Islands from
Thursday into Saturday morning due to Jerry. This rainfall brings a
risk of flash flooding, especially in areas of steep terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are expected to reach the Leeward
and Windward Islands on Thursday, then spread westward toward the
Greater Antilles on Friday. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Papin
  