000
WTNT35 KNHC 091150
TCPAT5
 
BULLETIN
Tropical Storm Jerry Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       AL102025
800 AM AST Thu Oct 09 2025
 
...NOAA AND AIR FORCE HURRICANE HUNTERS INVESTIGATING JERRY...
 
 
SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...15.7N 58.4W
ABOUT 355 MI...570 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Antigua, Barbuda, Anguilla, St. Kitts, Nevis, and Montserrat
* St. Barthelemy and St. Martin
* Sint Maarten
* Saba and St. Eustatius
* Guadeloupe and the adjacent islands
 
Interests elsewhere in the northern Leeward Islands and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Jerry was
located near latitude 15.7 North, longitude 58.4 West. Jerry is
moving toward the west-northwest near 20 mph (31 km/h). A turn 
toward the northwest is expected later today, followed by a 
slightly slower northward motion on Friday and Saturday. On the 
forecast track, the center of Jerry is expected to pass near or to 
the northeast of the northern Leeward Islands later today and 
tonight.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Gradual strengthening is forecast during the next few days, 
and Jerry could become a hurricane by late Friday or Saturday.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are possible in portions of the
northern Leeward Islands within the watch area later today into
Friday.
 
RAINFALL: Through Friday, 2 to 4 inches of rain with local storm
total maxima to 6 inches are expected across the Leeward and Virgin
Islands. This rainfall brings a risk of flash flooding, especially
in urban areas and in steep terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are beginning to reach the Leeward
and Windward Islands. These swells will spread westward toward the
Virgin Islands and Puerto Rico tonight, then toward the rest of the
Greater Antilles over the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Cangialosi
  