000
WTNT35 KNHC 091439
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number   9
NWS National Hurricane Center Miami FL       AL102025
1100 AM AST Thu Oct 09 2025
 
...JERRY EXPECTED TO BE NEAR THE NORTHERN LEEWARD ISLANDS LATER
TODAY...
...TROPICAL STORM WARNING ISSUED FOR BARBUDA...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.9N 59.1W
ABOUT 310 MI...495 KM ESE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Antigua and Barbuda has issued a Tropical Storm 
Warning for Barbuda.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Barbuda
 
A Tropical Storm Watch is in effect for...
* Antigua, Anguilla, St. Kitts, Nevis, and Montserrat
* St. Barthelemy and St. Martin
* Sint Maarten
* Saba and St. Eustatius
* Guadeloupe and the adjacent islands
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 12
hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in the northern Leeward Islands and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Jerry was 
located near latitude 15.9 North, longitude 59.1 West. Jerry is 
moving toward the west-northwest near 18 mph (30 km/h). A turn 
toward the northwest is expected late today, followed by a slightly 
slower northward motion on Friday and Saturday. On the forecast 
track, the center of Jerry is expected to pass near or to the 
northeast of the northern Leeward Islands later today and tonight.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Gradual strengthening is forecast during the next few days,
and Jerry could become a hurricane by late Friday or Saturday.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are expected in Barbuda
later today and tonight.  Tropical storm conditions are possible
in portions of the northern Leeward Islands within the watch area
later today into Friday.
 
RAINFALL: Through Friday, 2 to 4 inches of rain with local storm
total maxima to 6 inches are expected across the Leeward and Virgin
Islands. This rainfall brings a risk of flash flooding, especially
in urban areas and in steep terrain. For portions of Puerto Rico,
moisture associated with Jerry combined with local orographic
effects may result in up to 2 to 4 inches of rain, with isolated 6
inches possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are beginning to reach the Leeward
and Windward Islands. These swells will spread westward toward the
Virgin Islands and Puerto Rico tonight, then toward the rest of the
Greater Antilles over the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.
 
$$
Forecaster Cangialosi
  