000
WTNT35 KNHC 100545
TCPAT5
 
BULLETIN
Tropical Storm Jerry Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       AL102025
200 AM AST Fri Oct 10 2025
 
...HEAVY RAINFALL FROM JERRY CONTINUES ACROSS PORTIONS OF THE 
NORTHERN LEEWARD ISLANDS...
...TROPICAL STORM WARNINGS REMAIN IN EFFECT...
 
 
SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...18.5N 62.1W
ABOUT 65 MI...100 KM ENE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Barbuda and Anguilla
* St. Barthelemy and St. Martin
* Sint Maarten
* Guadeloupe and the adjacent islands
 
A Tropical Storm Watch is in effect for...
* Antigua, St. Kitts, Nevis, and Montserrat
* Saba and St. Eustatius
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the 
next several hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 
several hours.
 
Interests elsewhere in the northern Leeward Islands and the
British and U.S. Virgin Islands should monitor the progress of
Jerry.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Tropical Storm Jerry was 
located near latitude 18.5 North, longitude 62.1 West. Jerry is 
moving toward the northwest near 16 mph (26 km/h). This motion is 
expected to continue with a gradual slowdown today, followed by a 
northward turn tonight into Saturday.  On the forecast track, the 
center of Jerry will pass to the north of the northern Leeward 
Islands through this morning.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts. 
Little change in strength is expected today, but slow strengthening 
is possible over the weekend.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km) 
mainly to the east of the center.
 
The estimated minimum central pressure based on dropsonde data from 
the Air Force Hurricane Hunters is 1007 mb (29.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions are expected in the warning area and
are possible in the watch area this morning.
 
RAINFALL: Through today, 4 to 6 inches of rain are expected across
the island of Barbuda. Elsewhere across the Leeward and Virgin
Islands, 2 to 4 inches of rain are expected. This rainfall brings a
risk of flash flooding, especially in urban areas and in steep
terrain. For portions of Puerto Rico, moisture associated with Jerry
combined with local orographic effects may result in up to 2 to 4
inches of rain, with isolated 6 inches possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service storm
total rainfall graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are affecting the Leeward Islands, 
Windward Islands, the Virgin Islands, and Puerto Rico, and are 
likely to cause life-threatening surf and rip current conditions. 
These swells are expected to spread toward the rest of the Greater 
Antilles today and tonight. Please consult products from your local 
weather office.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Reinhart
  