000
WTNT35 KNHC 100852
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number  12
NWS National Hurricane Center Miami FL       AL102025
500 AM AST Fri Oct 10 2025
 
...FLASH FLOODING THREAT FOR THE LEEWARD ISLANDS CONTINUES AS HEAVY 
RAINFALL FROM JERRY SPREADS ACROSS THE REGION...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...19.2N 62.5W
ABOUT 80 MI...130 KM NNE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Antigua and Barbuda has discontinued the Tropical
Storm Warning for Barbuda and Anguilla, as well as the Tropical
Storm Watch for Antigua, St. Kitts, Nevis, and Montserrat.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* St. Barthelemy and St. Martin
* Sint Maarten
* Guadeloupe and the adjacent islands
 
A Tropical Storm Watch is in effect for...
* Saba and St. Eustatius
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next several hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next
several hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Jerry was 
located near latitude 19.2 North, longitude 62.5 West. Jerry is 
moving toward the northwest near 17 mph (28 km/h). A turn toward the 
north is expected tonight into Saturday, followed by a northward to 
north-northeastward motion through the rest of the weekend. On the 
forecast track, the center of Jerry will continue passing to the 
north of the Leeward Islands this morning, then move away from the 
islands later today.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Little change in strength is expected today, but slow strengthening
is possible over the weekend.

Tropical-storm-force winds extend outward up to 185 miles (295 km) 
mainly to the east of the center.
 
The estimated minimum central pressure is 1007 mb (29.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
WIND: Tropical storm conditions, mainly in gusts, are expected in 
the warning area and are possible in the watch area this morning.
 
RAINFALL: Through today, 4 to 6 inches of rain are expected across
the island of Barbuda. Elsewhere across the Leeward and Virgin
Islands, 2 to 4 inches of rain are expected. This rainfall brings a
risk of flash flooding, especially in urban areas and in steep
terrain. For portions of Puerto Rico, moisture associated with Jerry
combined with local orographic effects may result in up to 2 to 4
inches of rain, with isolated amounts of 6 inches possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service storm
total rainfall graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are affecting the Leeward Islands,
Windward Islands, the Virgin Islands, and Puerto Rico, and are
likely to cause life-threatening surf and rip current conditions.
These swells are expected to spread toward the rest of the Greater
Antilles today and tonight. Please consult products from your local
weather office for more information.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Reinhart
  