000
WTNT35 KNHC 101441
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number  13
NWS National Hurricane Center Miami FL       AL102025
1100 AM AST Fri Oct 10 2025
 
...JERRY'S CENTER PULLING AWAY FROM THE NORTHERN LEEWARD ISLANDS
BUT FLOODING RAINS CONTINUE...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.2N 63.4W
ABOUT 140 MI...225 KM N OF THE NORTHERN LEEWARD ISLANDS
ABOUT 840 MI...1350 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
All Tropical Storm Warnings have been discontinued.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Jerry was
located near latitude 20.2 North, longitude 63.4 West.  Jerry is
moving toward the northwest near 16 mph (26 km/h).  A turn toward 
the north is expected by this evening, with that motion continuing 
through Sunday.  A turn toward the northeast and east-northeast is 
forecast Sunday night and Monday.
 
Air Force Reserve Hurricane Hunter and satellite-derived wind data 
indicate that maximum sustained winds remain near 50 mph (85 km/h) 
with higher gusts.  Little change in strength is expected during 
the next few days. 
 
Tropical-storm-force winds extend outward up to 185 miles (295 km)
to the east of the center.
 
The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
RAINFALL: Through today, 4 to 6 inches of rain are expected across
the island of Barbuda. Elsewhere across the Leeward and Virgin
Islands, 2 to 4 inches of rain are expected. This rainfall brings a
risk of flash flooding, especially in urban areas and in steep
terrain. For portions of Puerto Rico, moisture associated with Jerry
may result in up to 2 to 4 inches of rain, with isolated 6 inches 
possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are affecting the Leeward Islands,
Windward Islands, the Virgin Islands, and Puerto Rico, and are
likely to cause life-threatening surf and rip current conditions.
These swells are expected to spread toward the rest of the Greater
Antilles today and tonight. Please consult products from your local
weather office for more information.
 
A depiction of rip current risk for the United States, including
Puerto Rico and the U.S. Virgin Islands, can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Berg
  