708 
WTNT35 KNHC 110239
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number  15
NWS National Hurricane Center Miami FL       AL102025
1100 PM AST Fri Oct 10 2025
 
...JERRY PULLING AWAY FROM NORTHEASTERN CARIBBEAN SEA BUT HEAVY
RAINS REMAIN POSSIBLE THROUGH THE OVERNIGHT HOURS FOR NORTHERN
LEEWARD AND VIRGIN ISLANDS...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...22.7N 63.9W
ABOUT 315 MI...505 KM N OF THE NORTHERN LEEWARD ISLANDS
ABOUT 665 MI...1070 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Jerry was
located near latitude 22.7 North, longitude 63.9 West. Jerry is
moving toward the north near 15 mph (24 km/h), and this motion is
expected to continue through Saturday night. A northeastward to
eastward motion is forecast on Sunday and Monday.
 
Satellite-derived wind data indicate that maximum sustained winds 
are near 60 mph (95 km/h) with higher gusts. Little change in 
strength is forecast during the next few days.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.
 
The estimated minimum central pressure is 1004 mb (29.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Jerry can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT5 and WMO header
WTNT45 KNHC.
 
RAINFALL: Through the rest of the night, outer rain bands extending
south of Jerry may bring an additional 1 to 2 inches of rain across
parts of the northern Leeward Islands, the Virgin Islands, and
eastern Puerto Rico. This rainfall is not expected to cause any
additional flash flooding concerns.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Jerry, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
SURF: Swells generated by Jerry are affecting the Leeward Islands,
Windward Islands, the Virgin Islands, Puerto Rico, the Dominican
Republic, and the Turks and Caicos Islands, and are likely to cause
life-threatening surf and rip current conditions. These swells are
expected to spread toward the Bahamas by Saturday morning. Please
consult products from your local weather office for more
information.
 
A depiction of rip current risk for Puerto Rico and the U.S. Virgin
Islands can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Hagen
  