000
WTNT35 KNHC 111455
TCPAT5
 
BULLETIN
Tropical Storm Jerry Advisory Number  17
NWS National Hurricane Center Miami FL       AL102025
1100 AM AST Sat Oct 11 2025
 
...DISHEVELED JERRY MAY NOT LAST MUCH LONGER AS A TROPICAL
CYCLONE...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...25.8N 63.2W
ABOUT 460 MI...740 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Jerry was
located near latitude 25.8 North, longitude 63.2 West.  Jerry is
moving toward the north near 16 mph (26 km/h), and this general 
motion is expected to continue today.  A turn toward the northeast 
is forecast on Sunday, followed by an eastward motion on Monday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Weakening is forecast during the next few days, and Jerry could 
degenerate into a trough of low pressure at any time.
 
Tropical-storm-force winds extend outward up to 205 miles (335 km)
to the east of the center.
 
The estimated minimum central pressure is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Jerry are affecting the Leeward Islands,
Virgin Islands, Puerto Rico, Dominican Republic, the Turks and
Caicos Islands, and the Bahamas.  These swells will likely
causing life-threatening surf and rip current conditions.  Please
consult products from your local weather office for more
information.
 
A depiction of rip current risk for Puerto Rico and the U.S. Virgin
Islands can be found at:
hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Berg
  