

000
WTPZ31 KNHC 290832
TCPEP1

BULLETIN
Tropical Storm Orlene Advisory Number   2
NWS National Hurricane Center Miami FL       EP162022
400 AM CDT Thu Sep 29 2022

...DEPRESSION STRENGTHENS TO TROPICAL STORM ORLENE SOUTH OF
SOUTHWESTERN MEXICO...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...14.8N 104.9W
ABOUT 295 MI...470 KM S OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Orlene was
located near latitude 14.8 North, longitude 104.9 West. Orlene is
moving toward the west-northwest near 13 mph (20 km/h) and this 
motion is expected to continue over the next day or so. A turn to 
the north is forecast to occur on Friday, and this motion should 
continue over the weekend. 

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Steady strengthening is forecast, and Orlene is expected to become 
a hurricane by late Friday. 

Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Large swells generated by Orlene will affect the coast of
southwestern Mexico, and the extreme southern portion of the Baja
California peninsula by this weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Latto

