

000
WTPZ31 KNHC 300834
TCPEP1

BULLETIN
Tropical Storm Orlene Advisory Number   6
NWS National Hurricane Center Miami FL       EP162022
300 AM MDT Fri Sep 30 2022

...ORLENE STRENGTHENS AS IT TURNS NORTHWESTWARD...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.9N 106.9W
ABOUT 275 MI...440 KM SW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests along the coast of western Mexico should monitor the
progress of Orlene. Watches may be required later this morning for
a portion of the western Mexico coastline.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Tropical Storm Orlene was 
located near latitude 15.9 North, longitude 106.9 West. Orlene is 
moving toward the northwest near 5 mph (7 km/h). A turn toward the 
north is expected by tonight along with a slight increase in 
forward speed.  Orlene is then forecast to turn toward the 
north-northeast by Saturday.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts. 
Steady to rapid strengthening is expected during the next couple of 
days, and Orlene is forecast to become a hurricane tonight or 
Saturday.

Orlene is a small tropical cyclone. Tropical-storm-force winds 
extend outward up to 35 miles (55 km) from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Large swells generated by Orlene will affect the coast of
southwestern Mexico, and the extreme southern portion of the Baja
California peninsula by this weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Latto

