

000
WTPZ31 KNHC 301436
TCPEP1

BULLETIN
Tropical Storm Orlene Advisory Number   7
NWS National Hurricane Center Miami FL       EP162022
900 AM MDT Fri Sep 30 2022

...ORLENE MOVING NORTHWESTWARD AND EXPECTED TO BECOME A HURRICANE
ON SATURDAY...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...16.1N 107.1W
ABOUT 270 MI...440 KM SW OF MANZANILLO MEXICO
ABOUT 310 MI...500 KM SSW OF CABO CORRIENTES MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests along the coast of western Mexico and in the Islas
Marias should monitor the progress of Orlene. Watches will likely
be required for portions of these areas later today.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Orlene was
located near latitude 16.1 North, longitude 107.1 West. Orlene is
moving toward the northwest near 5 mph (7 km/h). A turn toward the
north is expected by tonight along with a slight increase in
forward speed.  Orlene is then forecast to turn toward the
north-northeast by Saturday or Saturday night.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Steady to rapid strengthening is expected during the next couple 
of days, and Orlene is forecast to become a hurricane tonight or
Saturday.

Orlene is a small tropical cyclone. Tropical-storm-force winds 
extend outward up to 35 miles (55 km) from the center.

The estimated minimum central pressure is 998 mb (29.47 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Large swells generated by Orlene will affect the coast of
southwestern Mexico, and the extreme southern portion of the Baja
California peninsula by this weekend. These swells are likely to
cause life-threatening surf and rip current conditions, as well as 
coastal flooding. Please consult products from your local weather 
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Beven

