

227 
WTPZ31 KNHC 010259
TCPEP1

BULLETIN
Tropical Storm Orlene Advisory Number   9
NWS National Hurricane Center Miami FL       EP162022
900 PM MDT Fri Sep 30 2022

...ORLENE MOVING NORTHWARD...
...TROPICAL STORM WARNING IN EFFECT FOR A PORTION OF MAINLAND 
MEXICO...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...17.0N 107.2W
ABOUT 255 MI...410 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 315 MI...505 KM S OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Government of Mexico has issued a Tropical Storm Warning for
the coast of mainland Mexico from Playa Perula to San Blas, and a
Hurricane Watch from San Blas to Bahia Tempehuaya.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas

A Hurricane Watch is in effect for...
* Las Islas Marias
* The coast of mainland Mexico from San Blas to Bahia Tempehuaya

A Tropical Storm Watch is in effect for...
* The coast of mainland Mexico from Manzanillo to Playa Perula

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, generally within 36
hours.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of western and northwestern
Mexico should monitor the progress of Orlene. Additional watches
or warnings will likely be required for portions of these areas
overnight or Saturday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Tropical Storm Orlene was
located near latitude 17.0 North, longitude 107.2 West. Orlene is
moving toward the north near 5 mph (7 km/h).  Orlene is forecast to 
have a slight increase in forward speed overnight and move toward 
the north-northeast on Saturday and Saturday night.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Steady to rapid strengthening is expected through Saturday 
night, and Orlene is forecast to become a hurricane overnight or 
Saturday.

Orlene remains a small tropical cyclone.  Tropical-storm-force winds 
extend outward up to 45 miles (75 km) from the center.

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are possible in Las Islas Marias on 
Sunday, with tropical storm conditions possible Saturday night and 
Sunday.  Tropical storm conditions are expected in the warning area 
by early Sunday. Tropical storm conditions are possible along the 
coast of mainland Mexico Saturday night and Sunday.

RAINFALL: Into Monday evening, Orlene is expected to produce 3 to 5
inches of rainfall, with local amounts of 10 inches, for portions of
southwestern Mexico.  These rainfall amounts should lead to flash
flooding, as well as possible landslides in areas of rugged terrain.

STORM SURGE: Coastal flooding is likely along the coast of Mexico
in the warning area in regions of onshore winds.

SURF:  Large swells generated by Orlene will affect the coast of
southwestern Mexico, and the extreme southern portion of the Baja
California peninsula by this weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM MDT.
Next complete advisory at 300 AM MDT.

$$
Forecaster Bucci


