

000
WTPZ31 KNHC 010547
TCPEP1

BULLETIN
Tropical Storm Orlene Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP162022
1200 AM MDT Sat Oct 01 2022

...ORLENE CONTINUES TO MOVE NORTHWARD...
...EXPECTED TO PASS JUST WEST OF JALISCO, MEXICO LATER THIS 
WEEKEND...


SUMMARY OF 1200 AM MDT...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.1N 107.2W
ABOUT 255 MI...410 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 305 MI...490 KM S OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas

A Hurricane Watch is in effect for...
* Las Islas Marias
* The coast of mainland Mexico from San Blas to Bahia Tempehuaya

A Tropical Storm Watch is in effect for...
* The coast of mainland Mexico from Manzanillo to Playa Perula

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, generally within 36
hours.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of western and northwestern
Mexico should monitor the progress of Orlene. Additional watches
or warnings will likely be required for portions of these areas
later this morning.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM MDT (0600 UTC), the center of Tropical Storm Orlene was 
located near latitude 17.1 North, longitude 107.2 West. Orlene is 
moving toward the north near 5 mph (7 km/h).  Orlene is forecast to 
have a slight increase in forward speed later this morning and turn 
toward the north-northeast by tonight. This north-northeastward 
motion is expected to continue into early next week. 

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Steady to rapid strengthening is expected through tonight, 
and Orlene is forecast to become a hurricane later today.

Orlene remains a small tropical cyclone.  Tropical-storm-force
winds extend outward up to 45 miles (75 km) from the center.

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are possible in Las Islas Marias on
Sunday, with tropical storm conditions possible tonight and
Sunday.  Tropical storm conditions are expected in the warning area
by early Sunday. Tropical storm conditions are possible along the
coast of mainland Mexico within the tropical storm watch area 
tonight and Sunday.

RAINFALL: Into Monday evening, Orlene is expected to produce 3 to 5
inches of rainfall, with local amounts of 10 inches, for portions of
southwestern Mexico.  These rainfall amounts should lead to flash
flooding, as well as possible landslides in areas of rugged terrain.

STORM SURGE: Coastal flooding is likely along the coast of Mexico
in the warning area in regions of onshore winds.

SURF:  Large swells generated by Orlene will affect the coast of 
southwestern Mexico, and the extreme southern portion of the Baja 
California peninsula through this weekend. These swells are likely 
to cause life-threatening surf and rip current conditions. Please 
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Latto

