

000
WTPZ31 KNHC 011747
TCPEP1

BULLETIN
Hurricane Orlene Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       EP162022
1200 PM MDT Sat Oct 01 2022

...ORLENE MOVING SLOWLY NORTHWARD TOWARD LAS ISLAS MARIAS...


SUMMARY OF 1200 PM MDT...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.8N 107.0W
ABOUT 200 MI...320 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 260 MI...420 KM S OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.21 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas

A Hurricane Watch is in effect for...
* The coast of mainland Mexico from San Blas to Bahia Tempehuaya

A Tropical Storm Watch is in effect for...
* The coast of mainland Mexico from Manzanillo to Playa Perula

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, generally within 36
hours.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of western and northwestern
Mexico should monitor the progress of Orlene. Additional watches or
warnings will likely be required for portions of these areas later
today or tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 PM MDT (1800 UTC), the center of Hurricane Orlene was
located near latitude 17.8 North, longitude 107.0 West. Orlene is
moving toward the north near 5 mph (7 km/h). A north-northeastward
motion at a slightly faster speed is expected to begin by tonight
and continue through early next week. On the forecast track, the
center of Orlene should pass near or over Las Islas Marias Sunday
night or Monday morning and reach the coast of mainland Mexico later
on Monday or Monday night.

Maximum sustained winds are near 75 mph (120 km/h) with higher 
gusts.  Strengthening is expected through Sunday. After that, 
steady weakening is expected to begin by Sunday night. An Air
Force Reserve Hurricane Hunter aircraft is currently enroute to
investigate Orlene.

Orlene remains a small tropical cyclone. Hurricane-force winds
extend outward up to 10 miles (20 km) from the center and
tropical-storm-force winds extend outward up to 45 miles (75 km).

The estimated minimum central pressure is 989 mb (29.21 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected in Las Islas Marias Sunday
night, with tropical storm conditions possible by late Sunday.
Tropical storm conditions are expected in the tropical storm warning
area by early Sunday. Hurricane conditions are possible along the
coast of mainland Mexico within the hurricane watch area by Sunday
night into Monday. Tropical storm conditions are possible along the
coast of mainland Mexico within the tropical storm watch area
tonight and Sunday.

RAINFALL: Into Monday evening, Orlene is expected to produce 3 to 5
inches of rainfall, with local amounts of 10 inches, for portions of
Southwest Mexico.  These rainfall amounts should lead to flash
flooding, as well as possible landslides in areas of rugged terrain.

STORM SURGE: Coastal flooding is likely along the coast of Mexico
in the warning area in regions of onshore winds.

SURF:  Large swells generated by Orlene will affect the coast of
southwestern Mexico, and the extreme southern portion of the Baja
California peninsula through this weekend. These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Beven

