

000
WTPZ31 KNHC 020547
TCPEP1

BULLETIN
Hurricane Orlene Intermediate Advisory Number 14A
NWS National Hurricane Center Miami FL       EP162022
1200 AM MDT Sun Oct 02 2022

...ORLENE BECOMES A MAJOR HURRICANE...


SUMMARY OF 1200 AM MDT...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.6N 106.8W
ABOUT 145 MI...230 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 205 MI...325 KM S OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* The coast of mainland Mexico from San Blas to Mazatlan

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas

A Hurricane Watch is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from Mazatlan to Bahia Tempehuaya

A Tropical Storm Watch is in effect for...
* The coast of mainland Mexico from Manzanillo to Playa Perula

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, generally within 36
hours.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of western and northwestern
Mexico should monitor the progress of Orlene. Additional watches or
warnings could be required for portions of these areas on Sunday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM MDT (0600 UTC), the center of Hurricane Orlene was
located near latitude 18.6 North, longitude 106.8 West.  Orlene is
moving toward the north near 5 mph (7 km/h).  A turn toward the
north-northeast with a slight increase in forward speed is expected
today.  On the forecast track, the center of Orlene should pass 
near or over Las Islas Marias tonight or Monday morning and reach 
the coast of mainland Mexico within the warning area later on Monday 
or Monday night.

Satellite images indicate that the maximum sustained winds have 
increased to near 115 mph (185 km/h) with higher gusts.  Orlene is 
now a category 3 hurricane on the Saffir-Simpson Hurricane Wind 
Scale.  Some additional strengthening is forecast through this 
morning, followed by weakening beginning later today and continuing 
until landfall.

Orlene is a small tropical cyclone. Hurricane-force winds extend
outward up to 10 miles (20 km) from the center and
tropical-storm-force winds extend outward up to 60 miles (95 km).

The estimated minimum central pressure is 962 mb (28.41 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected in Las Islas Marias 
tonight, with tropical storm conditions beginning later today.
Hurricane conditions are expected in the warning area along the
coast of mainland Mexico late Monday, with tropical storm conditions
beginning early Monday.

Tropical storm conditions are expected in the tropical storm warning
area by early today.  Hurricane conditions are possible along the
coast of mainland Mexico within the hurricane watch area by tonight 
or early Monday.  Tropical storm conditions are possible within the 
tropical storm watch area today.

RAINFALL: Into Tuesday, Orlene is expected to produce 3 to 5 inches
of rainfall, with local amounts of 10 inches, across portions of
southwestern Mexico.  These rainfall amounts should lead to flash
flooding, as well as possible landslides in areas of rugged terrain.

STORM SURGE: A dangerous storm surge is likely to cause coastal
flooding along the coast of mainland Mexico in the warning area in
regions of onshore winds.

SURF:  Large swells generated by Orlene are affecting the west coast
of Mexico and will spread northward to the southern portion of the
Baja California peninsula and the Gulf of California through this
weekend. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Pasch

