

000
WTPZ31 KNHC 022034
TCPEP1

BULLETIN
Hurricane Orlene Advisory Number  17
NWS National Hurricane Center Miami FL       EP162022
300 PM MDT Sun Oct 02 2022

...ORLENE EXPECTED TO BRING SIGNIFICANT WINDS, STORM SURGE, AND
HEAVY RAINFALL TO THE ISLAS MARIAS AND PORTIONS OF SOUTHWESTERN
MEXICO...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...20.4N 106.9W
ABOUT 80 MI...125 KM W OF CABO CORRIENTES MEXICO
ABOUT 85 MI...135 KM SSW OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...972 MB...28.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Tropical Storm Warning from
north of Mazatlan to Bahia Tempehuaya.

The government of Mexico has discontinued the Tropical Storm Watch
from Manzanillo to Playa Perula.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* The coast of mainland Mexico from San Blas to Mazatlan

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from north of Mazatlan to Bahia
Tempehuaya

A Hurricane Watch is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from Mazatlan to Bahia Tempehuaya

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, generally within 36
hours.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of western and northwestern
Mexico should monitor the progress of Orlene.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Hurricane Orlene was located
near latitude 20.4 North, longitude 106.9 West. Orlene is moving
toward the north near 8 mph (13 km/h).  A turn toward the
north-northeast is expected later today or tonight.  On the 
forecast track, the center of Orlene will pass near or over Las 
Islas Marias tonight, and reach the coast of mainland Mexico within 
the warning area on Monday. 

Maximum sustained winds are near 115 mph (185 km/h) with higher
gusts.  Orlene is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Weakening is expected during the next day or
so, however Orlene is forecast to be a strong hurricane when it
passes near or over the Islas Marias, and remain a hurricane when it
reaches southwestern Mexico.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure based on data from an Air 
Force Reserve reconnaissance aircraft is 972 mb (28.71 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected in Las Islas Marias this
evening and tonight, with tropical storm conditions beginning
within the next few hours.  Hurricane conditions are expected in the
warning area along the coast of mainland Mexico on Monday, with
tropical storm conditions beginning late tonight.

Tropical storm conditions are expected to spread northward in the
tropical storm warning area through early Monday.  Hurricane
conditions are possible along the coast of mainland Mexico within
the hurricane watch area by tonight or early Monday.  Tropical storm
conditions are possible within the tropical storm watch area today.

RAINFALL: Orlene is expected to produce the following rainfall
across portions of southwestern Mexico through Tuesday:

* Islas Marias: 6 to 10 inches, with local amounts of 14 inches.
* Nayarit and southern Sinaloa: 3 to 6 inches with local amounts of
10 inches.
* Jalisco, Colima, and southwest Durango: 1 to 3 inches with local
amounts of 5 inches.

These rainfall amounts are likely to lead to flash flooding, as
well as possible landslides in areas of rugged terrain.

STORM SURGE: A dangerous storm surge is likely to cause coastal
flooding in the Islas Marias and along the coast of mainland Mexico
in the warning area in regions of onshore winds.

SURF:  Large swells generated by Orlene are affecting the west coast
of Mexico and will spread northward to the southern portion of the
Baja California peninsula and the Gulf of California over the
day or so. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM MDT.
Next complete advisory at 900 PM MDT.

$$
Forecaster Brown

