

000
WTPZ31 KNHC 030846
TCPEP1

BULLETIN
Hurricane Orlene Advisory Number  19
NWS National Hurricane Center Miami FL       EP162022
300 AM MDT Mon Oct 03 2022

...ORLENE EXPECTED TO BRING STRONG WINDS AND A DANGEROUS STORM
SURGE TO PORTIONS OF WESTERN MAINLAND MEXICO LATER TODAY...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...22.1N 106.4W
ABOUT 75 MI...120 KM S OF MAZATLAN MEXICO
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...N OR 10 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* The coast of mainland Mexico from San Blas to Mazatlan

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from north of Mazatlan to Bahia
Tempehuaya

A Hurricane Watch is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from Mazatlan to Bahia Tempehuaya

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, generally within 36
hours.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.

Interests elsewhere along the coast of western and northwestern
Mexico should monitor the progress of Orlene.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Hurricane Orlene was located
near latitude 22.1 North, longitude 106.4 West. Orlene is moving
toward the north near 9 mph (15 km/h), and a general northward to
north-northeastward motion is expected to continue over the next day
or so.  On the forecast track, the center of Orlene will continue to 
move away from Las Islas Marias this morning, and reach the coast of
mainland Mexico within the warning area later today or tonight.

Maximum sustained winds have decreased to near 100 mph (155 km/h) 
with higher gusts.  Weakening is expected during the next day or 
so, but Orlene is forecast to remain as hurricane when it reaches 
southwestern Mexico.  Rapid weakening is forecast after Orlene moves 
onshore, and the system should dissipate on Tuesday.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure is 976 mb (28.82 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane conditions are expected in the warning area along
the coast of mainland Mexico today, with tropical storm conditions
beginning this morning.

Tropical storm conditions are expected to spread northward in the
tropical storm warning area through early today.  Hurricane
conditions are possible along the coast of mainland Mexico within
the hurricane watch area early today.

RAINFALL: Orlene is expected to produce the following rainfall
across portions of southwestern Mexico through Tuesday:

* Islas Marias: 6 to 10 inches, with local amounts of 14 inches.
* Nayarit and southern Sinaloa: 3 to 6 inches with local amounts of
10 inches.
* Jalisco, Colima, and southwest Durango: 1 to 3 inches with local
amounts of 5 inches.

These rainfall amounts are likely to lead to flash flooding, as
well as possible landslides in areas of rugged terrain.

STORM SURGE: A dangerous storm surge is likely to cause coastal
flooding in the Islas Marias and along the coast of mainland Mexico
in the warning area in regions of onshore winds.

SURF:  Large swells generated by Orlene are affecting the west coast
of Mexico and will spread northward to the southern portion of the
Baja California peninsula and the Gulf of California over the next
day or so. These swells are likely to cause life-threatening surf
and rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM MDT.
Next complete advisory at 900 AM MDT.

$$
Forecaster Pasch

