

000
WTPZ31 KNHC 031157
TCPEP1

BULLETIN
Hurricane Orlene Intermediate Advisory Number 19A
NWS National Hurricane Center Miami FL       EP162022
600 AM MDT Mon Oct 03 2022

...CENTER OF ORLENE NEARING THE COAST OF SOUTHWESTERN MEXICO...
...STRONG WINDS, HEAVY RAINFALL, AND A DANGEROUS STORM SURGE 
SPREADING ONSHORE... 

SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...22.6N 106.1W
ABOUT 45 MI...75 KM SSE OF MAZATLAN MEXICO
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...N OR 10 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* The coast of mainland Mexico from San Blas to Mazatlan

A Tropical Storm Warning is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from north of Mazatlan to Bahia
Tempehuaya
 The government of Mexico has discontinued the Tropical Storm 
Warning and Hurricane Watch south of Punta Mita. 
A Hurricane Watch is in effect for...
* The coast of mainland Mexico from Playa Perula to San Blas
* The coast of mainland Mexico from Mazatlan to Bahia Tempehuaya

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. 

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the center of Hurricane Orlene was located
near latitude 22.6 North, longitude 106.1 West. Orlene is moving
toward the north near 9 mph (15 km/h), and a general northward to
north-northeastward motion is expected to continue over the next day
or so.  On the forecast track, the center of Orlene will reach the 
coast of mainland Mexico within the warning area this morning. 

Maximum sustained winds are near 100 mph (155 km/h) with higher 
gusts. Little change in strength is expected before Orlene reaches
the coast.  Rapid weakening is forecast after Orlene moves
onshore, and the system should dissipate tonight or Tuesday.

Hurricane-force winds extend outward up to 15 miles (30 km) from
the center and tropical-storm-force winds extend outward up to 90
miles (150 km).

The estimated minimum central pressure is 976 mb (28.82 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane and tropical storm conditions are expected in the 
warning areas along the coast of mainland Mexico today.

Hurricane conditions are possible along the coast of mainland 
Mexico within the hurricane watch area this morning.

RAINFALL: Orlene is expected to produce the following rainfall
across portions of southwestern Mexico through Tuesday:

* Islas Marias: 6 to 10 inches, with local amounts of 14 inches.
* Nayarit and southern Sinaloa: 3 to 6 inches with local amounts of
10 inches.
* Jalisco, Colima, and southwest Durango: 1 to 3 inches with local
amounts of 5 inches.

These rainfall amounts are likely to lead to flash flooding, as
well as possible landslides in areas of rugged terrain.

STORM SURGE: A dangerous storm surge is likely to cause coastal
flooding in the Islas Marias and along the coast of mainland Mexico
in the warning area in regions of onshore winds.

SURF:  Large swells generated by Orlene will affect the 
southwestern coast of Mexico, southern portions of the Baja 
California peninsula and the Gulf of California over the next day 
or so. These swells are likely to cause life-threatening surf
and rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Brown

