

000
WTNT32 KNHC 150241
TCPAT2

BULLETIN
Tropical Storm Fiona Advisory Number   3
NWS National Hurricane Center Miami FL       AL072022
1100 PM AST Wed Sep 14 2022

...TROPICAL STORM WATCHES ISSUED FOR PORTIONS OF THE NORTHERN
LEEWARD ISLANDS...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.7N 52.0W
ABOUT 650 MI...1045 KM E OF THE LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of the Netherlands has issued a Tropical Storm Watch 
for Saba and St. Eustatius.

The government of St. Maarten has issued a Tropical Storm Watch for
St. Maarten.

The government of Antigua has issued a Tropical Storm Watch for
Montserrat, Antigua, Barbuda, St. Kitts, Nevis, and Anguilla.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Saba and St. Eustatius
* St. Maarten
* Antigua, Barbuda, St. Kitts, Nevis, Montserrat, and Anguilla

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in the northern Leeward Islands, the Virgin 
Islands, Puerto Rico, and Hispaniola should monitor the progress of 
this system, as additional tropical storm watches or warnings will 
be required for portions of those areas on Thursday.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Fiona was
located near latitude 16.7 North, longitude 52.0 West. Fiona is
moving toward the west-northwest near 16 mph (26 km/h) and
this general motion is expected to continue during the next few
days.  On the forecast track, the center of the storm is forecast 
to move through the Leeward Islands late Friday and Friday night, 
and be near the Virgin Islands and Puerto Rico this weekend.

Satellite-derived wind data indicate that maximum sustained winds 
have increased to near 50 mph (85 km/h) with higher gusts. Some slow 
strengthening is possible during the next few days.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
east of the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are possible across portions of the
northern Leeward Islands by Friday night, where a Tropical Storm
Watch has been issued.

RAINFALL:  Fiona is expected to produce total rainfall accumulations 
of 3 to 5 inches with maximum totals of 8 inches across the northern 
Leeward Islands, the British and U.S. Virgin Islands, Puerto Rico 
and eastern Hispaniola.   These rains may produce isolated flash and 
urban flooding, along with isolated mudslides in areas of higher 
terrain. 

SURF:  Swells generated by Fiona are expected to begin affecting the 
northern Leeward Islands on Friday. These swells could cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Cangialosi

