

000
WTNT32 KNHC 151450
TCPAT2

BULLETIN
Tropical Storm Fiona Advisory Number   5
NWS National Hurricane Center Miami FL       AL072022
1100 AM AST Thu Sep 15 2022

...TROPICAL STORM WARNINGS ISSUED FOR PORTIONS OF THE NORTHERN
LEEWARD ISLANDS...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.6N 54.3W
ABOUT 495 MI...800 KM E OF THE LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua and Barbuda has issued a Tropical Storm
Warning for Antigua, Barbuda, St. Kitts, Nevis, Montserrat, and
Anguilla.

The government of the Netherlands has issued a Tropical Storm
Warning for Saba and St. Eustatius.

The government of St. Maarten has issued a Tropical Storm Warning
for St. Maarten.

The government of France has issued a Tropical Storm Watch for
Guadeloupe, St. Barthelemy, and St. Martin.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Antigua, Barbuda, St. Kitts, Nevis, Montserrat, and Anguilla
* Saba and St. Eustatius
* St. Maarten

A Tropical Storm Watch is in effect for...
* Guadeloupe, St. Barthelemy, and St. Martin

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in the Virgin Islands, Puerto Rico, and
Hispaniola should monitor the progress of this system.  Additional
watches or warnings will likely be required for portions of these 
areas later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Fiona was
located near latitude 16.6 North, longitude 54.3 West.  Fiona is
moving toward the west near 14 mph (22 km/h).  A westward motion 
with some decrease in forward speed is expected to continue through 
late Saturday, with a turn toward the west-northwest possible on 
Sunday.  On the forecast track, the center of Fiona is expected to 
move across the Leeward Islands Friday night and early Saturday, 
and move near the Virgin Islands and Puerto Rico late Saturday into 
Sunday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some slow strengthening is possible during the next few days.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
mainly to the north of the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Tropical storm conditions are expected across portions of
the northern Leeward Islands within the warning area beginning
Friday evening.  Tropical storm conditions are possible across
portions of the northern Leeward Islands within the watch area by
Friday night.

RAINFALL:  Fiona is expected to produce the following rainfall
totals:

Northern Leeward Islands, the British and U.S. Virgin Islands and
Puerto Rico:  4 to 6 inches with isolated maximum totals of 10
inches across eastern Puerto Rico.

Eastern Hispaniola: 4 to 8 inches with isolated maximum totals of
12 inches.

These rains may produce flash and urban flooding, along with
isolated mudslides in areas of higher terrain.

SURF:  Swells generated by Fiona are expected to begin affecting the
Leeward Islands later today, spreading westward to the Virgin
Islands and Puerto Rico on Friday and Saturday. These swells could
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Berg

