

000
WTNT32 KNHC 152048
TCPAT2

BULLETIN
Tropical Storm Fiona Advisory Number   6
NWS National Hurricane Center Miami FL       AL072022
500 PM AST Thu Sep 15 2022

...TROPICAL STORM WATCHES ISSUED FOR PUERTO RICO AND THE VIRGIN
ISLANDS...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...16.3N 55.4W
ABOUT 425 MI...685 KM E OF THE LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of France has upgraded the Tropical Storm Watches
for Guadeloupe, St. Barthelemy, and St. Martin to Tropical Storm
Warnings.

A Tropical Storm Watch has been issued for the U.S. Virgin Islands
and Puerto Rico, including Vieques and Culebra.

The government of Antigua and Barbuda has issued a Tropical Storm
Watch for the British Virgin Islands.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Antigua, Barbuda, St. Kitts, Nevis, Montserrat, and Anguilla
* Saba and St. Eustatius
* St. Maarten
* Guadeloupe, St. Barthelemy, and St. Martin

A Tropical Storm Watch is in effect for...
* Puerto Rico, including Vieques and Culebra
* U.S. Virgin Islands
* British Virgin Islands

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in Hispaniola should monitor the progress of this system.
Additional watches or warnings will likely be required tonight or
on Friday.

For storm information specific to your area in the United States, 
including possible inland watches and warnings, please monitor 
products issued by your local National Weather Service forecast 
office. For storm information specific to your area outside of the 
United States, please monitor products issued by your national 
meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Fiona was
located near latitude 16.3 North, longitude 55.4 West.  Fiona is
moving toward the west near 14 mph (22 km/h).  A westward motion 
with some decrease in forward speed is expected through Saturday 
night, with a turn toward the west-northwest possible on Sunday.  On 
the forecast track, the center of Fiona is expected to move across 
the Leeward Islands Friday night and early Saturday, and move near 
the Virgin Islands and Puerto Rico late Saturday into Sunday.

Data from an Air Force Reserve Hurricane Hunter aircraft indicate 
that maximum sustained winds are near 60 mph (95 km/h) with higher 
gusts.  Little change in strength is forecast during the next few 
days.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
mainly to the north of the center.

The minimum central pressure based on data from the reconnaissance 
aircraft is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Tropical storm conditions are expected across portions of
the northern Leeward Islands within the warning area beginning
Friday evening.  Tropical storm conditions are possible within the 
watch area across the Virgin Islands on Saturday, and reaching
Puerto Rico late Saturday or Saturday night.

RAINFALL:  Fiona is expected to produce the following rainfall
totals:

Northern Leeward Islands, the British and U.S. Virgin Islands and
Puerto Rico:  4 to 6 inches with isolated maximum totals of 10
inches across eastern Puerto Rico.

Eastern Hispaniola: 4 to 8 inches with isolated maximum  totals of
12 inches.

These rains may produce flash and urban flooding, along with
isolated mudslides in areas of higher terrain. Considerable flood
impacts are possible across eastern portions of Puerto Rico.

STORM SURGE:  Localized coastal flooding will be possible along the
coasts of the U.S. Virgin Islands and Puerto Rico in areas of
onshore winds Saturday into Sunday.

SURF:  Swells generated by Fiona are beginning to affect the Leeward
Islands and will spread westward to the Virgin Islands and Puerto
Rico on Friday and Saturday.  These swells could cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Berg

