

062 
WTNT32 KNHC 201754
TCPAT2

BULLETIN
Hurricane Fiona Intermediate Advisory Number 25A
NWS National Hurricane Center Miami FL       AL072022
200 PM EDT Tue Sep 20 2022

...FIONA CONTINUES TO BRING HURRICANE CONDITIONS TO PORTIONS OF 
THE TURKS AND CAICOS...


SUMMARY OF 200 PM EDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 71.7W
ABOUT 30 MI...50 KM NNE OF NORTH CAICOS ISLAND
ABOUT 810 MI...1305 KM SSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...959 MB...28.32 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Turks and Caicos

A Tropical Storm Warning is in effect for...
* Southeastern Bahamas, including the Acklins, Crooked Island, Long
Cay, the Inaguas, Mayaguana, and the Ragged Islands

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. Preparations to protect life
and property should be nearing completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in Bermuda should monitor the progress of Fiona.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM EDT (1800 UTC), the center of Hurricane Fiona was located
near latitude 22.3 North, longitude 71.7 West.  Fiona is moving
toward the north-northwest near 9 mph (15 km/h).  This general
motion is expected to continue through today, followed by a turn
toward the north tonight or on Wednesday.  A turn toward the 
north-northeast with an increase in forward speed is expected on 
Thursday.  On the forecast track, the center of Fiona will continue 
to move near the eastern Turks and Caicos during the next few hours, 
away from those islands by tomorrow, and approach Bermuda late on 
Thursday.

Maximum sustained winds remain near 115 mph (185 km/h) with higher
gusts.  Fiona is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Strengthening is forecast during the next
couple of days.

Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).

The minimum central pressure estimated from Air Force Hurricane 
Hunter aircraft observations is 959 mb (28.32 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Fiona can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND: Hurricane conditions are occurring over portions of the Turks
and Caicos, and these conditions should continue for the next few
hours.

Tropical storm conditions are expected over portions of the
southeastern Bahamas for the next several hours.

RAINFALL:  Fiona is forecast to produce the following rainfall:

British and U.S. Virgin Islands: Additional local 1 to 2 inches over
the next 24 hours.

Southern Puerto Rico: Additional local 1 to 4 inches over the next
24 hours. Storm Total 12 to 20 inches with local maximum of 35
inches.

Northern Puerto Rico: Additional local 1 to 2 inches over the next
24 hours. Storm Total 4 to 12 inches with local maximum of 20
inches.

Dominican Republic: Additional 1 to 4 inches with local maximum of 6
inches over the next 24 hours. Storm Total up to 20 inches in the
eastern section.

Turks and Caicos: Additional 4 to 8 inches.

Southeast Bahamas: 1 to 4 inches.

Bermuda: 1 to 3 inches.

Heavy rainfall and localized life-threatening flash flooding
continues over portions of the Dominican Republic today.  Heavy
rains around the center of Fiona impacts the Turks and Caicos
through this afternoon with continued life-threatening flooding.
Localized additional flash and urban flooding is possible in Puerto
Rico.

STORM SURGE:  The combination of storm surge and the tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.

Storm surge could raise water levels by as much as 5 to 8 feet above
normal tide levels along the immediate coast in areas of onshore
winds in the Turks and Caicos through today.

Localized coastal flooding is possible for the Southeastern Bahamas
in areas of onshore winds through today.

SURF:  Swells generated by Fiona are affecting the Virgin Islands,
Puerto Rico, the northern coast of Hispaniola, the Turks and Caicos
Islands, and the southeastern Bahamas.  These swells will continue
to spread westward across the southwestern Atlantic toward the
central and northwestern Bahamas and the east coast of the United
States through midweek.  Swells from Fiona are expected to spread
across Bermuda later this week.  The swells could cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM EDT.

$$
Forecaster Pasch


