

000
WTNT32 KNHC 210247
TCPAT2

BULLETIN
Hurricane Fiona Advisory Number  27
NWS National Hurricane Center Miami FL       AL072022
1100 PM EDT Tue Sep 20 2022

...FIONA MOVING AWAY FROM THE TURKS AND CAICOS ISLANDS...


SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...23.2N 71.8W
ABOUT 95 MI...155 KM N OF NORTH CAICOS ISLAND
ABOUT 760 MI...1220 KM SW OF BERMUDA
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...947 MB...27.97 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of the Bahamas has discontinued all warnings for the
Turks and Caicos and the southeastern Bahamas.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in Atlantic Canada should monitor the progress of this
system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Hurricane Fiona was located
near latitude 23.2 North, longitude 71.8 West. Fiona is moving
toward the north near 8 mph (13 km/h).  This general motion is 
expected to continue through Wednesday.  A turn toward the 
north-northeast with an increase in forward speed is expected by 
Thursday.  On the forecast track, the center of Fiona will continue 
to move away from the Turks and Caicos tonight and Wednesday, and 
approach Bermuda late on Thursday.

Data from a NOAA Hurricane Hunter aircraft indicate that the 
maximum sustained winds are near 125 mph (205 km/h) with higher
gusts.  Fiona is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Strengthening is forecast during the 
next day or so. Some fluctuations in intensity are possible 
Wednesday night and Thursday. 

Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).

The latest minimum central pressure reported by the NOAA 
reconnaissance aircraft is 947 mb (27.97 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Fiona can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND: Gusty winds are likely to continue over portions of the
southeastern Bahamas and Turks and Caicos islands overnight.

Tropical storm conditions could reach Bermuda by late Thursday or
early Friday.

RAINFALL:  Fiona is forecast to produce the following rainfall:

Dominican Republic: Up to an additional local 1 to 2 inches. Storm
Total up to 20 inches in the eastern section.

Turks and Caicos: Additional 1 to 3 inches with storm totals of 5-10
inches. Areas of flooding remain possible.

Southeast Bahamas: 1 to 4 inches.

Bermuda: 1 to 3 inches.

SURF:  Swells generated by Fiona are affecting the northern coast
of Hispaniola, the Turks and Caicos Islands, and the southeastern
and central Bahamas.  These swells will continue to spread westward
across the southwestern Atlantic toward the northwestern Bahamas
and the east coast of the United States during the next day or two.
Swells from Fiona are expected to reach Bermuda by early Thursday.
The swells could cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.

$$
Forecaster Brown

