

803 
WTNT32 KNHC 211145
TCPAT2

BULLETIN
Hurricane Fiona Intermediate Advisory Number 28A
NWS National Hurricane Center Miami FL       AL072022
800 AM EDT Wed Sep 21 2022

...TROPICAL STORM WARNING AND HURRICANE WATCH ISSUED FOR BERMUDA...


SUMMARY OF 800 AM EDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...24.2N 71.7W
ABOUT 700 MI...1125 KM SW OF BERMUDA
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...937 MB...27.67 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Bermuda Weather Service has issued a Tropical Storm Warning and 
a Hurricane Watch for Bermuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bermuda

A Tropical Storm Warning is in effect for...
* Bermuda

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests in Atlantic Canada should monitor the progress of this
system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM EDT (1200 UTC), the eye of Hurricane Fiona was located by 
an Air Force Hurricane Hunter aircraft near latitude 24.2 North, 
longitude 71.7 West.  Fiona is moving toward the north near 8 mph 
(13 km/h).  This general motion is expected to continue through 
this evening.  A turn toward the north-northeast with an increase 
in forward speed is expected by Thursday.  On the forecast track, 
the center of Fiona will continue to move away from the Turks and 
Caicos today, and approach Bermuda late on Thursday.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Fiona is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Some additional strengthening is forecast 
through tonight, with some fluctuations in intensity possible on 
Thursday.

Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 160
miles (260 km).

The latest minimum central pressure estimated from Air Force 
Hurricane Hunter aircraft observations is 937 mb (27.67 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Fiona can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND: Gusty winds are likely to continue over portions of the
southeastern Bahamas and Turks and Caicos islands this morning.

Tropical storm conditions are expected, and hurricane conditions 
are possible, on Bermuda by late Thursday or early Friday.

RAINFALL:  Fiona is forecast to produce the following rainfall:

Dominican Republic: Up to an additional local 1 to 2 inches. Storm
Total up to 20 inches in the eastern section.

Turks and Caicos: Additional 1 to 3 inches with storm totals of 5-10
inches. Areas of flooding remain possible.

Southeast Bahamas: 1 to 4 inches.

Bermuda: 2 to 4 inches.

SURF:  Swells generated by Fiona are affecting the northern coast
of Hispaniola, the Turks and Caicos Islands, and the southeastern
and central Bahamas.  These swells will continue to spread westward
across the southwestern Atlantic toward the northwestern Bahamas
and the east coast of the United States during the next day or two.
Swells from Fiona are expected to reach Bermuda by early Thursday.
The swells could cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM EDT.

$$
Forecaster Pasch


