

828 
WTNT32 KNHC 220850
TCPAT2

BULLETIN
Hurricane Fiona Advisory Number  32
NWS National Hurricane Center Miami FL       AL072022
500 AM EDT Thu Sep 22 2022

...FIONA NOW MOVING NORTH-NORTHEASTWARD...
...HURRICANE WARNING ISSUED FOR BERMUDA...


SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...27.4N 70.6W
ABOUT 485 MI...780 KM SW OF BERMUDA
ABOUT 1250 MI...2010 KM SSW OF HALIFAX NOVA SCOTIA
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...NNE OR 25 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...934 MB...27.58 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Meteorological Service of Bermuda has issued a Hurricane
Warning for Bermuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Bermuda

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

Interests in Atlantic Canada should monitor the progress of this
system.  Watches will likely be required for portions of Atlantic
Canada later this morning.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Hurricane Fiona was located
near latitude 27.4 North, longitude 70.6 West. Fiona is moving
toward the north-northeast near 13 mph (20 km/h).  A north- 
northeastward or northeastward motion with an increase in forward 
speed is expected today through Friday, followed by a somewhat 
slower northward motion beginning Friday night or Saturday.  On the 
forecast track, the center of Fiona will pass just to the west of 
Bermuda tonight, approach Nova Scotia on Friday, and move across 
Nova Scotia and into the Gulf of St. Lawrence on Saturday.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Fiona is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Little change in strength is expected through
tonight.  Some weakening is expected to begin on Friday, but Fiona 
is forecast to still be producing hurricane-force winds Friday 
night and Saturday after it has become post-tropical.

Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 205
miles (335 km). NOAA buoy 41047, about 50 miles west-northwest of
the center of Fiona, recently reported a sustained wind of 62 mph
(100 km/h) and a gust to 80 mph (129 km/h).

The estimated minimum central pressure is 934 mb (27.58 inches). 
NOAA buoy 41047 recently reported a pressure of 975.0 mb
(28.79 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Fiona can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND: Hurricane conditions are expected on Bermuda beginning
tonight and continuing through Friday morning.

RAINFALL:  Fiona is forecast to produce the following rainfall:

Bermuda: 2 to 4 inches.

Nova Scotia, Prince Edward Island, and western Newfoundland: 3 to 6
inches, with local maximum up to 10 inches. This rainfall could
result in areas of flooding, some of which may be significant in
nature.

Eastern Quebec: 2 to 5 inches.

Eastern New Brunswick: 1 to 3 inches.

STORM SURGE:  A storm surge will cause elevated water levels along
the coast of Bermuda in areas of onshore winds beginning tonight.
Near the coast, the surge will be accompanied by large and
destructive waves.

SURF:  Swells generated by Fiona are affecting the northern coast
of Hispaniola, the Turks and Caicos Islands, and the Bahamas.
These swells will continue to spread westward across the
southwestern Atlantic toward the east coast of the United States
and Atlantic Canada during the next day or two.  Swells from Fiona
are expected to reach Bermuda this morning.  The swells could
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.

$$
Forecaster Beven


