

000
WTNT32 KNHC 240000
TCPAT2

BULLETIN
Hurricane Fiona Intermediate Advisory Number 38A
NWS National Hurricane Center Miami FL       AL072022
800 PM AST Fri Sep 23 2022

...HURRICANE CONDITIONS EXPECTED TO BEGIN IN ATLANTIC CANADA 
TONIGHT...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...42.3N 60.70W
ABOUT 215 MI...345 KM SE OF HALIFAX NOVA SCOTIA
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...N OR 0 DEGREES AT 46 MPH...74 KM/H
MINIMUM CENTRAL PRESSURE...935 MB...27.61 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Nova Scotia from Hubbards to Brule
* Prince Edward Island
* Isle-de-la-Madeleine
* Newfoundland from Parson's Pond to Francois

A Tropical Storm Warning is in effect for...
* St. Andrews New Brunswick to west of Hubbards Nova Scotia
* West of Brule Nova Scotia to Cap Madeleine Quebec
* Anticosti Island
* Sheldrake Quebec to north of Parson's Pond Newfoundland
* Boat Harbor to Hare Bay Newfoundland
* Francois to St Lawrence Newfoundland

A Tropical Storm Watch is in effect for...
* North of Boat Harbor Newfoundland to West Bay Labrador

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Hurricane Fiona was located
near latitude 42.3 North, longitude 60.7 West.  Fiona is moving
toward the north near 46 mph (74 km/h).  A slower
north-northeast or northward motion is expected through Sunday.  On
the forecast track, the center of Fiona will approach Nova Scotia
tonight, move across Nova Scotia and into the Gulf of St.
Lawrence on Saturday, and then move across Labrador and over the 
Labrador Sea by late Sunday.

Maximum sustained winds are near 125 mph (205 km/h) with higher
gusts.  Fiona is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Although gradual weakening is forecast during
the next couple of days, Fiona is expected to be a powerful
hurricane-force cyclone when it moves across Atlantic Canada.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 345
miles (555 km).  Sable Island, Nova Scotia, reported a wind gust of 
43 mph (69 km/h).

The estimated minimum central pressure is 935 mb (27.61 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Fiona can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND:  Hurricane conditions are expected in portions of the
hurricane warning area in Canada late tonight or early Saturday.
Tropical storm conditions are expected to begin in portions of the
tropical storm warning area in Canada tonight.  Tropical storm
conditions are possible in the watch area in Labrador on Sunday.

RAINFALL:  Fiona is forecast to produce the following rainfall:

Nova Scotia, Prince Edward Island, and western Newfoundland: 3 to 6
inches (75 to 150 mm), with local maxima of up to 10 inches (250
mm).  This rainfall could result in areas of flooding, some of
which may be significant in nature.

Labrador and eastern Quebec:  2 to 5 inches (50 to 125 mm).

Eastern New Brunswick: 1 to 3 inches (25 to 75 mm).

STORM SURGE: A dangerous storm surge is expected to produce coastal
flooding within the warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.

SURF:  Swells generated by Fiona are affecting the northwestern
Bahamas, the eastern United States coast, and Bermuda.  These
swells are now reaching Atlantic Canada this evening.  The swells 
are likely to cause life-threatening surf and rip current 
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Pasch

