
ZCZC MIATCPAT2 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Post-Tropical Cyclone Fiona Intermediate Advisory Number 40A
NWS National Hurricane Center Miami FL       AL072022
800 AM AST Sat Sep 24 2022

...CENTER OF FIONA NOW OVER THE GULF OF ST. LAWRENCE...
...HURRICANE-FORCE WINDS, SURGE, AND HEAVY RAINS CONTINUE ACROSS 
PORTIONS OF ATLANTIC CANADA...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...47.3N 61.5W
ABOUT 200 MI...340 KM NE OF HALIFAX NOVA SCOTIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...N OR 0 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...937 MB...27.67 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Nova Scotia from Hubbards to Brule
* Prince Edward Island
* Isle-de-la-Madeleine
* Newfoundland from Parson's Pond to Francois

A Tropical Storm Warning is in effect for...
* St. Andrews New Brunswick to west of Hubbards Nova Scotia
* West of Brule Nova Scotia to Cap Madeleine Quebec
* Anticosti Island
* Sheldrake Quebec to north of Parson's Pond Newfoundland
* Boat Harbor to Hare Bay Newfoundland
* Francois to St Lawrence Newfoundland

A Tropical Storm Watch is in effect for...
* North of Boat Harbor Newfoundland to West Bay Labrador

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Post-Tropical Cyclone Fiona
was located near latitude 47.3 North, longitude 61.5 West. The
post-tropical cyclone is moving toward the north near 23 mph (37
km/h).  A slower north-northeast or northward motion is expected
through Sunday.  On the forecast track, the center of Fiona will
move across the Gulf of St. Lawrence this morning, and then move 
across Labrador and over the Labrador Sea on Sunday.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Although gradual weakening is forecast during the next
couple of days, Fiona is expected to maintain hurricane-force winds
until this afternoon.

Hurricane-force winds extend outward up to 175 miles (280 km) from
the center and tropical-storm-force winds extend outward up to 405
miles (650 km).  An observation on St. Paul Island recently 
reported a sustained wind of 76 mph (122 km/h) and a gust to 90 
(145 km/h).

The estimated minimum central pressure based on surface 
observations is 937 mb (27.67 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Fiona can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND:  Hurricane conditions are occurring in portions of the
hurricane warning area in Canada. Tropical storm conditions are
occurring in portions of the tropical storm warning area in Canada.
These conditions should persist through this evening. Tropical storm
conditions are possible in the watch area in Labrador on Sunday.

RAINFALL:  Fiona is forecast to produce the following rainfall:

Nova Scotia, Prince Edward Island, and western Newfoundland: 3 to 6
inches (75 to 150 mm), with local maxima of up to 10 inches (250
mm). Flooding is expected, some of which could be significant.

Labrador and eastern Quebec:  2 to 5 inches (50 to 125 mm).

Eastern New Brunswick: 1 to 3 inches (25 to 75 mm).

STORM SURGE: A dangerous storm surge is expected to produce coastal
flooding within the warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.

SURF:  Swells generated by Fiona are affecting Atlantic Canada, the
northeastern United States coast, and Bermuda. The swells are 
likely to cause life-threatening surf and rip current conditions.  
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Cangialosi

NNNN
