

000
WTNT32 KNHC 241744
TCPAT2

BULLETIN
Post-Tropical Cyclone Fiona Intermediate Advisory Number 41A
NWS National Hurricane Center Miami FL       AL072022
200 PM AST Sat Sep 24 2022

...HURRICANE-FORCE WINDS, STORM SURGE, AND HEAVY RAINS CONTINUE
ACROSS PORTIONS OF ATLANTIC CANADA...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...47.7N 61.4W
ABOUT 105 MI...170 KM W OF PORT AUX BASQUES NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...N OR 355 DEGREES AT 25 MPH...41 KM/H
MINIMUM CENTRAL PRESSURE...948 MB...28.00 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Canadian Hurricane Centre has discontinued the Tropical Storm 
Watch for Labrador and discontinued the Tropical Storm Warning for 
all of Nova Scotia. 

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Prince Edward Island
* Isle-de-la-Madeleine
* Newfoundland from Parson's Pond to Francois

A Tropical Storm Warning is in effect for...
* Sheldrake Quebec to north of Parson's Pond Newfoundland
* Boat Harbor to Hare Bay Newfoundland
* Francois to St Lawrence Newfoundland

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Post-Tropical Cyclone Fiona
was located near latitude 47.7 North, longitude 61.4 West. The
post-tropical cyclone is moving toward the north near 25 mph (41
km/h), and a slower northward motion is expected during the next 
few days.  On the forecast track, the center of Fiona will move
across the Gulf of St. Lawrence through this evening, and then move 
across Labrador and over the Labrador Sea on Sunday.

Maximum sustained winds are near 75 mph (120 km/h) with higher
gusts.  Gradual weakening is expected during the next couple of
days.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 405
miles (650 km).

The estimated minimum central pressure based on surface
observations is 948 mb (28.00 inches).  Several observing sites in 
Atlantic Canada are recording gale- and storm-force winds.


HAZARDS AFFECTING LAND
----------------------
Key messages for Fiona can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC
and on the web at hurricanes.gov/text/MIATCDAT2.shtml.

WIND:  Hurricane conditions are occurring in portions of the
hurricane warning area in Canada. Tropical storm conditions are
occurring in portions of the tropical storm warning area in Canada.

RAINFALL:  Fiona is forecast to produce the following additional
rainfall:

Nova Scotia, Prince Edward Island, and western Newfoundland: 1 to 3
inches (25 to 75 mm), resulting in storm total rainfall maxima of up
to 10 inches (200 mm). Flooding is expected, some of which could be
significant.

Labrador and eastern Quebec:  2 to 5 inches (50 to 125 mm).

Eastern New Brunswick: 1 inch (25 mm) with locally higher amounts.

STORM SURGE: A dangerous storm surge is expected to produce coastal
flooding within the warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.

SURF:  Swells generated by Fiona are affecting Atlantic Canada, the
northeastern United States coast, and Bermuda. The swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi

