000
WTNT32 KNHC 200245
TCPAT2
 
BULLETIN
Tropical Storm Gabrielle Advisory Number  12
NWS National Hurricane Center Miami FL       AL072025
1100 PM AST Fri Sep 19 2025
 
...GABRIELLE FORECAST TO BECOME A HURRICANE BY SUNDAY...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...23.6N 57.2W
ABOUT 535 MI...855 KM NE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 760 MI...1220 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Gabrielle
was located near latitude 23.6 North, longitude 57.2 West. Gabrielle 
is moving toward the northwest near 12 mph (19 km/h), and this 
motion is expected to continue through Saturday. A gradual turn 
towards the north-northwest is expected by Sunday, followed by a 
northward motion by Sunday night. On the forecast track, the center 
of Gabrielle is expected to pass east of Bermuda Sunday night and 
Monday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Gradual strengthening is forecast, and Gabrielle is expected to
become a hurricane by Sunday.
 
Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.
 
The estimated minimum central pressure is 1004 mb (29.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle are expected to reach Bermuda
soon and build through the weekend.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Bucci
  