275 
WTNT32 KNHC 200836
TCPAT2
 
BULLETIN
Tropical Storm Gabrielle Advisory Number  13
NWS National Hurricane Center Miami FL       AL072025
500 AM AST Sat Sep 20 2025
 
...GABRIELLE MOVING NORTHWESTWARD...
...EXPECTED TO BECOME A HURRICANE AND PASS EAST OF BERMUDA SUNDAY
NIGHT AND MONDAY...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...24.3N 58.1W
ABOUT 530 MI...855 KM NE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 685 MI...1105 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Gabrielle was
located near latitude 24.3 North, longitude 58.1 West. Gabrielle is
moving toward the northwest near 13 mph (20 km/h), and this general
motion is expected to continue through tonight.  A turn toward the
north-northwest is forecast on Sunday, followed by a turn toward
the north and northeast Monday and Monday night.  On the forecast
track, the center of Gabrielle is expected to pass east of Bermuda
Sunday night and Monday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Gradual strengthening is forecast, and Gabrielle is expected to
become a hurricane by Sunday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
to the east of the center.
 
The estimated minimum central pressure is 1004 mb (29.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle are beginning to reach Bermuda
and will build through the weekend.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Berg
  