000
WTNT32 KNHC 201445
TCPAT2
 
BULLETIN
Tropical Storm Gabrielle Advisory Number  14
NWS National Hurricane Center Miami FL       AL072025
1100 AM AST Sat Sep 20 2025
 
...RECON AIRCRAFT TO INVESTIGATE GABRIELLE TODAY...
...EXPECTED TO BECOME A HURRICANE AND PASS EAST OF BERMUDA SUNDAY
NIGHT AND MONDAY...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...25.0N 59.0W
ABOUT 540 MI...865 KM NNE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 615 MI...990 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Gabrielle
was located near latitude 25.0 North, longitude 59.0 West. Gabrielle
is moving toward the northwest near 13 mph (20 km/h), and this 
general motion is expected to continue through tonight.  A turn 
toward the north-northwest is forecast on Sunday, followed by a 
turn toward the north and northeast Monday and Monday night.  On 
the forecast track, the center of Gabrielle is expected to pass 
east of Bermuda Sunday night and Monday.
 
Maximum sustained winds are now near 60 mph (95 km/h) with higher 
gusts. Continued gradual strengthening is forecast, and Gabrielle 
is expected to become a hurricane by Sunday. Air Force Reserve and 
NOAA Hurricane Hunter aircraft are scheduled to investigate 
Gabrielle later today.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle are beginning to reach Bermuda
and will build through the weekend.  Swells generated by Gabrielle 
should reach the east coast of the United States from North 
Carolina northward, along with Atlantic Canada, later this weekend 
into early next week. These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Beven
  