501 
WTNT32 KNHC 210236
TCPAT2
 
BULLETIN
Tropical Storm Gabrielle Advisory Number  16
NWS National Hurricane Center Miami FL       AL072025
1100 PM AST Sat Sep 20 2025
 
...GABRIELLE EXPECTED TO BECOME A HURRICANE ON SUNDAY...
...FORECAST TO PASS EAST OF BERMUDA ON MONDAY...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...26.3N 59.2W
ABOUT 535 MI...860 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Gabrielle 
was located near latitude 26.3 North, longitude 59.2 West. Gabrielle 
is moving toward the north-northwest near 9 mph (15 km/h), and this 
general motion should continue through Sunday. A turn toward the 
north is forecast on Monday, followed by a faster northeastward or 
east-northeastward motion on Tuesday. On the forecast track, the 
center of Gabrielle is expected to pass east of Bermuda on Monday.

Maximum sustained winds are near 65 mph (100 km/h) with higher 
gusts. Strengthening is forecast during the next couple of days, and 
Gabrielle is expected to become a hurricane on Sunday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km) 
mainly to the east of the center.
 
The estimated minimum central pressure is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle will continue to affect Bermuda 
through early next week. Distant swells from Gabrielle should reach 
the east coast of the United States from North Carolina northward, 
along with Atlantic Canada, on Sunday and continue through early 
next week. These swells are likely to cause life-threatening surf 
and rip current conditions. Please consult products from your local 
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Reinhart
  