000
WTNT32 KNHC 210842
TCPAT2
 
BULLETIN
Tropical Storm Gabrielle Advisory Number  17
NWS National Hurricane Center Miami FL       AL072025
500 AM AST Sun Sep 21 2025
 
...GABRIELLE EXPECTED TO BECOME A HURRICANE TODAY...
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...27.2N 60.0W
ABOUT 455 MI...730 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Gabrielle was
located near latitude 27.2 North, longitude 60.0 West. Gabrielle is
moving toward the north-northwest near 9 mph (15 km/h) and this
general motion should continue through tonight. A turn toward the
north is forecast on Monday, followed by a faster northeastward or
east-northeastward motion on Tuesday. On the forecast track, the
center of Gabrielle is expected to pass east of Bermuda on Monday.
 
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts. Strengthening is forecast during the next couple of days, and
Gabrielle is expected to become a hurricane later today.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 995 mb (29.39 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle will continue to affect Bermuda 
during the next few days. These swells are expected to reach the  
east coast of the United States from North Carolina northward, as 
well as Atlantic Canada, beginning later today and continuing 
through early this week. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Kelly
  