728 
WTNT32 KNHC 221454
TCPAT2
 
BULLETIN
Hurricane Gabrielle Advisory Number  23
NWS National Hurricane Center Miami FL       AL072025
1100 AM AST Mon Sep 22 2025
 
...GABRIELLE COULD FURTHER STRENGTHEN AS IT PASSES EAST OF BERMUDA
TODAY...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...30.8N 62.3W
ABOUT 180 MI...290 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...N OR 10 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in Bermuda and the Azores should monitor the progress of
Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Gabrielle was
located near latitude 30.8 North, longitude 62.3 West. Gabrielle is
moving toward the north near 10 mph (17 km/h).  This general motion
is expected today, followed by a faster northeastward or east-
northeastward motion on Tuesday and Wednesday. On the forecast
track, the center of Gabrielle is expected to pass east of Bermuda
tonight.
 
Maximum sustained winds remain near 120 mph (195 km/h) with higher
gusts.  Gabrielle is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Gabrielle could intensify even more today,
though some weakening should begin by Wednesday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The estimated minimum central pressure is 955 mb (28.20 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle will continue to affect Bermuda
during the next few days. These swells are now reaching the east
coast of the United States from North Carolina northward, as well as
Atlantic Canada, and are expected to continue through the early
part this week. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Blake
  