902 
WTNT32 KNHC 230233
TCPAT2
 
BULLETIN
Hurricane Gabrielle Advisory Number  25
NWS National Hurricane Center Miami FL       AL072025
1100 PM AST Mon Sep 22 2025
 
...GABRIELLE PASSING EAST OF BERMUDA...
...INTERESTS IN THE AZORES SHOULD MONITOR ITS PROGRESS...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...32.4N 61.0W
ABOUT 220 MI...355 KM E OF BERMUDA
ABOUT 1945 MI...3130 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...NE OR 50 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...948 MB...28.00 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Azores should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the eye of Hurricane Gabrielle was
located near latitude 32.4 North, longitude 61.0 West.  Gabrielle is
moving toward the northeast near 13 mph (20 km/h).  A faster 
northeastward to east- northeastward motion is expected on Tuesday 
and Wednesday.  On the forecast track, the center of Gabrielle 
will continue to move away from Bermuda tonight and Tuesday.

Maximum sustained winds are near 140 mph (220 km/h) with higher
gusts.  Gabrielle is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Little change in strength is expected 
through early Tuesday, followed by  gradual weakening later on 
Tuesday and on Wednesday.
 
Hurricane-force winds extend outward up to 40 miles (65 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The estimated minimum central pressure is 948 mb (28.00 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle will continue to affect Bermuda
and the east coast of the United States from North Carolina
northward, as well as Atlantic Canada, and are expected to continue
for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Pasch
  