091 
WTNT32 KNHC 230848
TCPAT2
 
BULLETIN
Hurricane Gabrielle Advisory Number  26
NWS National Hurricane Center Miami FL       AL072025
500 AM AST Tue Sep 23 2025
 
...GABRIELLE MOVING NORTHEASTWARD INTO THE OPEN CENTRAL ATLANTIC...
...INTERESTS IN THE AZORES SHOULD MONITOR ITS PROGRESS...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...33.2N 59.7W
ABOUT 305 MI...485 KM ENE OF BERMUDA
ABOUT 1855 MI...2985 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...949 MB...28.03 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Azores should monitor the progress of Gabrielle.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Gabrielle was 
located near latitude 33.2 North, longitude 59.7 West. Gabrielle is 
moving toward the northeast near 13 mph (20 km/h).  A faster 
northeastward to east- northeastward motion is expected through 
Thursday.  On the forecast track, the center of Gabrielle will 
continue to move away from Bermuda today.
 
Maximum sustained winds are near 140 mph (220 km/h) with higher
gusts.  Gabrielle is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Gradual weakening is expected during the 
next couple of days.
 
Hurricane-force winds extend outward up to 40 miles (65 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The estimated minimum central pressure is 949 mb (28.03 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
SURF:  Swells generated by Gabrielle will continue to affect 
Bermuda, the U.S. East Coast from North Carolina northward, and 
Atlantic Canada over the next few days.  These swells are expected 
to produce life-threatening surf and rip current conditions.  Please 
consult products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Beven
  