000
WTNT32 KNHC 232335
TCPAT2
 
BULLETIN
Hurricane Gabrielle Intermediate Advisory Number 28A
NWS National Hurricane Center Miami FL       AL072025
800 PM AST Tue Sep 23 2025
 
...GABRIELLE EXPECTED TO MOVE NEAR THE AZORES AS A HURRICANE IN A 
COUPLE OF DAYS...
 
 
SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...34.8N 55.2W
ABOUT 580 MI...930 KM ENE OF BERMUDA
ABOUT 1575 MI...2535 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...953 MB...28.15 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* All of the Azores
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the eye of Hurricane Gabrielle was
located near latitude 34.8 North, longitude 55.2 West.  Gabrielle is
moving toward the east-northeast near 21 mph (33 km/h), and this 
motion with some additional acceleration is expected to continue 
for the next several days.  On the forecast track, the center of 
Gabrielle will approach the Azores during the day on Thursday, and 
move across the island chain Thursday night into Friday.

maximum sustained winds are near 125 mph (205 km/h) with higher
gusts.  Gabrielle is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.   Steady weakening is expected during the 
next couple of days, but Gabrielle is still expected to be a 
hurricane when it passes through the Azores. 
 
Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 140
miles (220 km).
 
The estimated minimum central pressure is 953 mb (28.15 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Hurricane conditions are possible within the watch area
by Thursday night.
 
STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near the areas of onshore winds. The
surge will be accompanied by large and destructive waves.
 
RAINFALL: From Thursday into Friday morning, Gabrielle may bring 3
to 5 inches, or 75 to 125 mm, of rainfall across the central and
western Azores. During the same time outer bands from Gabrielle may
also result in 1 to 2 inches, or 25 to 50 mm, of rain across the
eastern Azores.
 
SURF: Swells generated by Gabrielle will continue to affect Bermuda,
the U.S. East Coast from North Carolina northward, and Atlantic
Canada over the next few days. These swells are expected to produce
life-threatening surf and rip current conditions. Please consult
products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Pasch
  