576 
WTNT32 KNHC 240532
TCPAT2
 
BULLETIN
Hurricane Gabrielle Intermediate Advisory Number 29A
NWS National Hurricane Center Miami FL       AL072025
200 AM AST Wed Sep 24 2025
 
...GABRIELLE MOVING QUICKLY EAST-NORTHEASTWARD AND EXPECTED TO BE 
NEAR OR OVER THE AZORES AS A HURRICANE BY LATE THURSDAY OR EARLY 
FRIDAY...
 
 
SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...35.3N 52.7W
ABOUT 1430 MI...2305 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...954 MB...28.17 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* All of the Azores
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.

A Hurricane Warning will likely be issued for all of or portions of 
the Azores later this morning.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Hurricane Gabrielle was
located near latitude 35.3 North, longitude 52.7 West. Gabrielle is
moving toward the east-northeast near 22 mph (35 km/h), and this
motion with some additional acceleration is expected to continue
for the next several days.  On the forecast track, the center of
Gabrielle will approach the Azores during the day on Thursday, and
move across the island chain Thursday night into Friday.
 
Maximum sustained winds are near 120 mph (195 km/h) with higher
gusts.  Gabrielle is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Steady weakening is expected during the
next couple of days, but Gabrielle is still expected to be a
hurricane when it passes through the Azores.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 140
miles (220 km).
 
The estimated minimum central pressure is 954 mb (28.17 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Hurricane conditions are possible within the watch area
by Thursday night.
 
STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near the areas of onshore winds. The
surge will be accompanied by large and destructive waves.
 
RAINFALL: From Thursday into Friday morning, Gabrielle may bring 3
to 5 inches, or 75 to 125 mm, of rainfall across the central and
western Azores. During the same time outer bands from Gabrielle may
also result in 1 to 2 inches, or 25 to 50 mm, of rain across the
eastern Azores.
 
SURF: Swells generated by Gabrielle will continue to affect Bermuda,
the U.S. East Coast from North Carolina northward, and Atlantic
Canada over the next few days. These swells are expected to produce
life-threatening surf and rip current conditions. Please consult
products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Beven
  