000
WTNT32 KNHC 241146
TCPAT2
 
BULLETIN
Hurricane Gabrielle Intermediate Advisory Number 30A
NWS National Hurricane Center Miami FL       AL072025
800 AM AST Wed Sep 24 2025
 
...GABRIELLE RACING EAST-NORTHEASTWARD ACROSS THE NORTH ATLANTIC...
...HURRICANE WARNING IN EFFECT FOR THE AZORES...
 
 
SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...35.8N 50.2W
ABOUT 1285 MI...2070 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...ENE OR 75 DEGREES AT 25 MPH...41 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* All of the Azores
 
A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area. A warning is typically issued 36 
hours before the anticipated first occurrence of 
tropical-storm-force winds, conditions that make outside 
preparations difficult or dangerous. Preparations to protect life 
and property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Hurricane Gabrielle was
located near latitude 35.8 North, longitude 50.2 West. Gabrielle is
moving toward the east-northeast near 25 mph (41 km/h), and this
motion with some additional acceleration is expected to continue
for the next several days. On the forecast track, the center of
Gabrielle will approach the Azores during the day on Thursday, and
move across the island chain Thursday night into Friday.
 
Maximum sustained winds are near 115 mph (185 km/h) with higher 
gusts. Gabrielle is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Weakening is expected during the next couple 
of days, but Gabrielle is still expected to be a hurricane when it 
passes through the Azores.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 140
miles (220 km).
 
The estimated minimum central pressure is 960 mb (28.35 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Hurricane conditions are expected in the warning area
Thursday night and Friday, with tropical storm conditions likely by 
Thursday evening. 
 
STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near the areas of onshore winds. The
surge will be accompanied by large and destructive waves.
 
RAINFALL: From Thursday into Friday morning, Gabrielle may bring 3
to 5 inches, or 75 to 125 mm, of rainfall across the central and
western Azores. During the same time outer bands from Gabrielle may
also result in 1 to 2 inches, or 25 to 50 mm, of rain across the
eastern Azores.
 
SURF: Swells generated by Gabrielle will continue to affect Bermuda, 
the U.S. East Coast from North Carolina northward, and Atlantic 
Canada over the next couple of days. These swells are expected to 
produce life-threatening surf and rip current conditions. Please 
consult products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Reinhart
  