000
WTNT32 KNHC 241740
TCPAT2
 
BULLETIN
Hurricane Gabrielle Intermediate Advisory Number 31A
NWS National Hurricane Center Miami FL       AL072025
200 PM AST Wed Sep 24 2025
 
...GABRIELLE ACCELERATES EASTWARD ACROSS THE SUBTROPICAL ATLANTIC...
...EXPECTED TO BRING HURRICANE CONDITIONS WHEN IT PASSES NEAR OR 
OVER THE AZORES LATE THURSDAY OR EARLY FRIDAY...
 
 
SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...36.1N 46.8W
ABOUT 1100 MI...1775 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...E OR 80 DEGREES AT 26 MPH...43 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* All of the Azores
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. A warning is typically issued 36
hours before the anticipated first occurrence of tropical-storm-
force winds, conditions that make outside preparations difficult or
dangerous. Preparations to protect life and property should be
rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Hurricane Gabrielle was
located near latitude 36.1 North, longitude 46.8 West. Gabrielle is
moving toward the east near 26 mph (43 km/h). An eastward to 
east-northeastward motion is expected during the next couple of 
days, followed by a slower eastward to east-southeastward motion 
this weekend. On the forecast track, the center of Gabrielle will 
approach the Azores during the day on Thursday, and move across the 
island chain Thursday night into Friday.
 
Maximum sustained winds are near 110 mph (175 km/h) with higher
gusts. Some weakening is expected during the next couple of days, 
but Gabrielle is still forecast to be a hurricane when it passes 
through the Azores.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).
 
The estimated minimum central pressure is 962 mb (28.41 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Hurricane conditions are expected in the Azores Thursday night
and Friday, with tropical storm conditions likely by Thursday
evening.
 
STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds in the
Azores. The surge will be accompanied by large and destructive
waves.
 
RAINFALL: From Thursday into Friday morning, Gabrielle may bring 3
to 5 inches, or 75 to 125 mm, of rainfall across the central and
western Azores. During the same time outer bands from Gabrielle may
also result in 1 to 2 inches, or 25 to 50 mm, of rain across the
eastern Azores.
 
SURF: Swells generated by Gabrielle will continue to affect Bermuda
over the next couple of days, and the U.S. East Coast from North
Carolina northward and Atlantic Canada over the next day or so.
These swells are expected to produce life-threatening surf and rip
current conditions. Please consult products issued by your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Reinhart
  