741 
WTNT32 KNHC 250839
TCPAT2
 
BULLETIN
Hurricane Gabrielle Advisory Number  34
NWS National Hurricane Center Miami FL       AL072025
900 AM GMT Thu Sep 25 2025
 
...GABRIELLE MOVING RAPIDLY EASTWARD TOWARD THE AZORES...
...ON TRACK TO BRING HURRICANE CONDITIONS TO THE AZORES TONIGHT OR
EARLY FRIDAY...
 
 
SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...36.5N 38.8W
ABOUT 655 MI...1055 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...E OR 80 DEGREES AT 32 MPH...52 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* All of the Azores
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. Preparations to protect life and
property should be rushed to completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Hurricane Gabrielle was
located near latitude 36.5 North, longitude 38.8 West. Gabrielle is
moving toward the east near 32 mph (52 km/h). A fast eastward to
east-northeastward motion is expected during the next couple of
days, followed by a slower eastward to east-southeastward motion
this weekend.  On the forecast track, the center of Gabrielle will
approach the Azores today and move across the island chain tonight
into early Friday.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Gabrielle is forecast to be at hurricane strength when it
passes through the Azores. After that, it is expected to weaken as 
it becomes an extratropical low.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).
 
The estimated minimum central pressure is 979 mb (28.91 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Hurricane conditions are expected in the Azores tonight into
early Friday, with tropical storm conditions likely by this
evening. Significant hurricane-force wind gusts are likely across
portions of the Azores even after the center passes.
 
STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds in the
Azores. The surge will be accompanied by large and destructive
waves.
 
RAINFALL: From tonight through Friday morning, Gabrielle could
produce up to 3 to 5 inches, 75 to 125 mm, of storm total rainfall
across the central Azores.  This rainfall could produce flash
flooding within their mountains.  Elsewhere, Gabrielle is expected
to yield 1 to 3 inches or 25 to 75 mm of rain across the western and
eastern Azores.
 
SURF: Swells generated by Gabrielle will continue to affect Bermuda
over the next couple of days, and the U.S. East Coast from North
Carolina northward and Atlantic Canada over the next day or so.
Swells from Gabrielle will begin reaching the Azores later today.
These swells are expected to produce life-threatening surf and rip
current conditions. Please consult products issued by your local
weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM GMT.
Next complete advisory at 300 PM GMT.
 
$$
Forecaster Beven
  