434 
WTNT32 KNHC 251141
TCPAT2
 
BULLETIN
Hurricane Gabrielle Intermediate Advisory Number 34A
NWS National Hurricane Center Miami FL       AL072025
1200 PM GMT Thu Sep 25 2025
 
...GABRIELLE RACING EASTWARD TOWARD THE AZORES...
...EXPECTED TO BRING HURRICANE CONDITIONS TO THE AZORES TONIGHT OR
EARLY FRIDAY...
 
 
SUMMARY OF 1200 PM GMT...1200 UTC...INFORMATION
-----------------------------------------------
LOCATION...36.4N 36.5W
ABOUT 535 MI...860 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...E OR 80 DEGREES AT 32 MPH...52 KM/H
MINIMUM CENTRAL PRESSURE...980 MB...28.94 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* All of the Azores
 
A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area, in case tonight or early Friday. 
Preparations to protect life and property should be rushed to 
completion.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1200 PM GMT (1200 UTC), the center of Hurricane Gabrielle was 
located near latitude 36.4 North, longitude 36.5 West. Gabrielle is 
moving quickly toward the east near 32 mph (52 km/h). A fast 
eastward to east-northeastward motion is expected during the next 
day or two, followed by a slower eastward to east-southeastward 
motion this weekend. On the forecast track, the center of Gabrielle 
will approach the Azores today and move across the island chain 
tonight into early Friday.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts. Gabrielle is forecast to be at hurricane strength when it
passes through the Azores. After that, it is expected to weaken as 
an extratropical low through the weekend.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from
the center and tropical-storm-force winds extend outward up to 195
miles (315 km).
 
The estimated minimum central pressure is 980 mb (28.94 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Hurricane conditions are expected in the Azores tonight into
early Friday, with tropical storm conditions likely by this
evening. Significant hurricane-force wind gusts are likely across
portions of the Azores even after the center passes.
 
STORM SURGE: A dangerous storm surge is expected to produce 
significant coastal flooding in areas of onshore winds in the 
Azores. The surge will be accompanied by large and destructive 
waves.
 
RAINFALL: From tonight through Friday morning, Gabrielle could
produce up to 3 to 5 inches, 75 to 125 mm, of storm total rainfall
across the central Azores. This rainfall could produce flash
flooding within the mountains. Elsewhere, Gabrielle is expected
to yield 1 to 3 inches, or 25 to 75 mm, of rain across the western 
and eastern Azores.
 
SURF: Swells generated by Gabrielle will continue to affect Bermuda, 
the northeastern coast of the U.S., and Atlantic Canada today. 
Swells from Gabrielle will begin reaching the Azores later today. 
These swells are expected to produce life-threatening surf and rip 
current conditions. Please consult products issued by your local 
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.
 
$$
Forecaster Reinhart
  