000
WTNT32 KNHC 260244
TCPAT2
 
BULLETIN
Post-Tropical Cyclone Gabrielle Advisory Number  37
NWS National Hurricane Center Miami FL       AL072025
300 AM GMT Fri Sep 26 2025
 
...STRONG WINDS OCCURRING OVER THE CENTRAL AZORES AS GABRIELLE'S
CENTER APPROACHES...
...WINDS SHOULD ALSO PICK UP IN THE SOUTHEASTERN AZORES VERY SOON...
 
 
SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...37.8N 29.3W
ABOUT 65 MI...105 KM SSW OF FAIAL ISLAND IN THE CENTRAL AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...ENE OR 75 DEGREES AT 29 MPH...46 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* All of the Azores
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case through this
morning.  Preparations to protect life and property should be
complete.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Post-Tropical Cyclone
Gabrielle was located near latitude 37.8 North, longitude 29.3 West.
The post-tropical cyclone is moving toward the east-northeast near
29 mph (46 km/h).  An eastward to east-northeastward motion with a
gradual decrease in forward speed is expected through Saturday,
followed by a turn toward the southeast and south through early 
next week.  On the forecast track, the center of post-tropical 
Gabrielle will move across the Azores this morning, then approach 
the coast of Portugal by early Sunday.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Some slight re-strengthening is possible later today, but 
gradual weakening should begin on Saturday.
 
Gale-force winds extend outward up to 160 miles (260 km) from the 
center.  A sustained wind of 71 mph (114 km/h) with a gust to 86 
mph (138 km/h) was recently reported by a station on Terceira Island 
in the central Azores at an elevation of 884 feet (269 m).  Closer 
to sea level, a wind gust to 58 mph (93 km/h) was measured at Ponta 
Furada on Faial Island.
 
The estimated minimum central pressure is 985 mb (29.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Tropical storm conditions, with gusts to hurricane force, are
occurring in the central Azores and will spread to the southeastern
Azores over the next couple of hours.  Strong, gusty winds will
continue across these islands through the morning.
 
Gusty winds are possible along portions of the coast of Portugal
late Saturday through Sunday.
 
STORM SURGE: A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds in the
Azores. The surge will be accompanied by large and destructive
waves.
 
RAINFALL: Through this morning, Gabrielle could produce 3 to 5 
inches, or 75 to 125 mm, of storm total rainfall across the central 
Azores.  This rainfall could cause flash flooding across the 
terrain.  Elsewhere, Gabrielle is expected to produce 1 to 3 inches, 
or 25 to 75 mm, of rain across the eastern Azores.  
 
SURF: Swells generated by Gabrielle will affect the Azores through
the weekend and will reach the coasts of Portugal, northwestern
Spain, and northern Morocco on Saturday. These swells are expected
to produce life-threatening surf and rip current conditions. Please
consult products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM GMT.
Next complete advisory at 900 AM GMT.
 
$$
Forecaster Berg
  