554 
WTNT32 KNHC 260547
TCPAT2
 
BULLETIN
Post-Tropical Cyclone Gabrielle Intermediate Advisory Number 37A
NWS National Hurricane Center Miami FL       AL072025
600 AM GMT Fri Sep 26 2025
 
...CENTER OF GABRIELLE MOVING THROUGH THE AZORES...
...STRONG WINDS OCCURRING OVER THE CENTRAL AZORES AND SHOULD 
SOON INCREASE IN THE SOUTHEASTERN AZORES...
 
 
SUMMARY OF 600 AM GMT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...38.6N 27.7W
ABOUT 55 MI...85 KM E OF FAIAL ISLAND IN THE CENTRAL AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...ENE OR 75 DEGREES AT 30 MPH...48 KM/H
MINIMUM CENTRAL PRESSURE...987 MB...29.15 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* All of the Azores
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case through this
morning.  Preparations to protect life and property should be
complete.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 AM GMT (0600 UTC), the center of Post-Tropical Cyclone
Gabrielle was located near latitude 38.6 North, longitude 27.7 West.
The post-tropical cyclone is moving toward the east-northeast near
30 mph (48 km/h).  An eastward to east-northeastward motion with a
gradual decrease in forward speed is expected through Saturday,
followed by a turn toward the southeast and south through early 
next week.  On the forecast track, the center of post-tropical 
Gabrielle will move across the Azores during the next few hours, 
then approach the coast of Portugal by early Sunday.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Some slight re-strengthening is possible during the next 
several hours, but gradual weakening should begin on Saturday.
 
Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center. Horta Airport on Faial Island recently reported 
sustained winds of 48 mph (78 km/h) and a wind gust of 76 mph   
(122 km/h). A few hours ago, Serra St. Barbera, located in the 
mountains on Terceira Island, reported a wind gust of 115 mph   
(185 km/h).
 
The estimated minimum central pressure is 987 mb (29.15 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Tropical storm conditions, with gusts to hurricane force, are
occurring in the central Azores and will spread to the southeastern
Azores over the next couple of hours.  Strong, gusty winds will
continue across these islands through the morning.
 
Gusty winds are possible along portions of the coast of Portugal
late Saturday through Sunday.
 
STORM SURGE: A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds in the
Azores. The surge will be accompanied by large and destructive
waves.
 
RAINFALL: Through this morning, Gabrielle could produce 3 to 5
inches, or 75 to 125 mm, of storm total rainfall across the central
Azores.  This rainfall could cause flash flooding across the
terrain.  Elsewhere, Gabrielle is expected to produce 1 to 3 inches,
or 25 to 75 mm, of rain across the eastern Azores.
 
SURF: Swells generated by Gabrielle will affect the Azores through
the weekend and will reach the coasts of Portugal, northwestern
Spain, and northern Morocco on Saturday. These swells are expected
to produce life-threatening surf and rip current conditions. Please
consult products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.
 
$$
Forecaster Beven
  