772 
WTNT32 KNHC 261439
TCPAT2
 
BULLETIN
Post-Tropical Cyclone Gabrielle Advisory Number  39
NWS National Hurricane Center Miami FL       AL072025
300 PM GMT Fri Sep 26 2025
 
...CENTER OF GABRIELLE CONTINUES MOVING AWAY FROM THE AZORES...
...THIS IS THE FINAL NHC ADVISORY...
 
 
SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...40.0N 22.8W
ABOUT 245 MI...395 KM ENE OF LAJES AIR BASE IN THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 31 MPH...50 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Post-Tropical Cyclone
Gabrielle was located near latitude 40.0 North, longitude 22.8 West.
The post-tropical cyclone is moving toward the east-northeast near
31 mph (50 km/h). A turn toward the east with a decrease in forward 
speed is expected through Saturday, followed by a turn toward the 
southeast and south through early next week. On the forecast track, 
the center of post-tropical Gabrielle will continue moving away from 
the Azores today, then approach the coast of Portugal by early 
Sunday.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Some strengthening is forecast through tonight, with 
weakening expected over the weekend.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.
 
The estimated minimum central pressure is 992 mb (29.30 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Gabrielle can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT2 and WMO header WTNT42 KNHC.
 
WIND: Gusty winds across the central and southeastern Azores will
continue to diminish this afternoon.
 
RAINFALL: Gabrielle is expected to produce less than an inch, or 25
mm, of additional rainfall across the Azores today. Any flooding
caused by Gabrielle across the terrain of the central Azores should
subside today.
 
SURF: Swells generated by Gabrielle will affect the Azores through
the weekend and will reach the coasts of Portugal, northwestern
Spain, and northern Morocco on Saturday. These swells are expected
to produce life-threatening surf and rip current conditions. Please
consult products issued by your local weather office.
 
 
NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on this system. Future information on marine impacts can be 
found in High Seas Forecasts issued by Meteo France under WMO header 
FQNT50 LFPW and available on the web at 
https://tgftp.nws.noaa.gov/data/raw/fq/fqnt50.lfpw..txt. Future 
information on potential land-based impacts in Portugal can be found 
in products issued by the Portugal Meteorological Institute at 
https://www.ipma.pt/en/index.html
 
$$
Forecaster Hagen
  