
ZCZC MIATCPEP4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Madeline Advisory Number   1
NWS National Hurricane Center Miami FL       EP142022
300 PM MDT Sat Sep 17 2022

...TROPICAL STORM MADELINE FORMS OVER THE EASTERN PACIFIC...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...15.9N 106.9W
ABOUT 520 MI...840 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 1 MPH...2 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Tropical Storm Madeline was
located near latitude 15.9 North, longitude 106.9 West. Madeline is
drifting toward the north near 1 mph (2 km/h). A faster northward 
motion is expected by tonight, followed by a slow counter-clockwise 
turn toward the west through Tuesday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Slight strengthening is forecast for the next day or so, with 
fluctuations in intensity possible after that.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Madeline will affect portions of the 
southwest coast of Mexico for the next few days. High surf 
associated with Madeline will spread northward and begin to affect 
the coast of Baja California late this weekend or early next week. 
These swells are likely to cause life-threatening surf and rip 
current conditions.  Please consult products from your local weather 
office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster D. Zelinsky

NNNN
