

875 
WTPZ34 KNHC 180237
TCPEP4

BULLETIN
Tropical Storm Madeline Advisory Number   2
NWS National Hurricane Center Miami FL       EP142022
900 PM MDT Sat Sep 17 2022

...MADELINE HEADING NORTHWARD...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...16.9N 106.8W
ABOUT 460 MI...740 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Tropical Storm Madeline was
located near latitude 16.9 North, longitude 106.8 West. Madeline is
moving toward the north near 9 mph (15 km/h). A gradual turn toward 
the northwest then west is expected through early next week. 

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Some slight strengthening is forecast over the next day or so, 
with fluctuations in intensity possible after that. 

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Madeline will affect portions of the
southwest coast of Mexico for the next few days. High surf
associated with Madeline will spread northward and begin to affect
the coast of Baja California late this weekend or early next week.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Latto


