

000
WTPZ34 KNHC 181736
TCPEP4

BULLETIN
Tropical Storm Madeline Intermediate Advisory Number 4A
NWS National Hurricane Center Miami FL       EP142022
1200 PM MDT Sun Sep 18 2022

...MADELINE TURNS TOWARD THE NORTH-NORTHWEST...


SUMMARY OF 1200 PM MDT...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.6N 107.1W
ABOUT 155 MI...250 KM SW OF CABO CORRIENTES MEXICO
ABOUT 350 MI...560 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Manzanillo northward to Cabo Corrientes

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case during the next 24
hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 PM MDT (1800 UTC), the center of Tropical Storm Madeline was
located near latitude 18.6 North, longitude 107.1 West.  Madeline is
moving toward the north-northwest near 9 mph (15 km/h).  A turn 
toward the northwest is expected by this evening, followed by a
turn toward the west-northwest and west on Monday and Tuesday. On
the forecast track, the center of Madeline is expected to turn away
from the coast of Mexico during the next couple of days.

Maximum sustained winds are near 45 mph (75 km/h) with higher
gusts. Little change in strength is forecast during the next day or
so. Weakening is expected to begin on Monday, and Madeline is likely
to degenerate into a post-tropical remnant low on Tuesday.

Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.

The estimated minimum central pressure is 998 mb (29.47 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Madeline can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP4 and WMO
header WTPZ44 KNHC and on the web at
hurricanes.gov/text/MIATCDEP4.shtml.

RAINFALL:  Outer bands from Madeline are forecast to produce
rainfall totals of 2 to 4 inches with local maximum totals of 6
inches today into Monday across mainly coastal portions of the
following Mexican States: Colima, Jalisco, and Nayarit.

These heavy rains may produce localized flash and urban flooding,
along with possible mudslides in areas of higher coastal terrain.

WIND:  Tropical storm conditions are possible within the watch
area today and tonight.

SURF:  Swells generated by Madeline will affect portions of the
southwest coast of Mexico for the next few days. High surf
associated with Madeline will spread northward and begin to affect
the coast of the Baja California peninsula today into Monday. These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Berg

