

730 
WTPZ34 KNHC 190237
TCPEP4

BULLETIN
Tropical Storm Madeline Advisory Number   6
NWS National Hurricane Center Miami FL       EP142022
900 PM MDT Sun Sep 18 2022

...MADELINE TURNING NORTHWESTWARD AND IS A LITTLE STRONGER...
...LOCALIZED FLASH FLOODING POSSIBLE ALONG THE SOUTHWESTERN COAST
OF MEXICO THROUGH MONDAY...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...19.3N 107.9W
ABOUT 160 MI...260 KM WSW OF CABO CORRIENTES MEXICO
ABOUT 280 MI...450 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm Watch
along the coast of southwest Mexico.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches and warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Tropical Storm Madeline was 
located near latitude 19.3 North, longitude 107.9 West.  Madeline is 
moving toward the northwest near 9 mph (15 km/h).  A turn toward the 
west-northwest at a similar forward speed is expected on Monday, 
followed by a turn toward the west by Tuesday night.  On the 
forecast track, the center of Madeline will gradually move away from 
the coast of Mexico through Tuesday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some slight strengthening is possible through Monday morning.
Weakening is expected to begin by Monday night, and Madeline is
forecast to become a remnant low on Tuesday.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure is 996 mb (29.42 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Madeline can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP4 and WMO
header WTPZ44 KNHC and on the web at
hurricanes.gov/text/MIATCDEP4.shtml.

RAINFALL:  Outer bands from Madeline are forecast to produce 
rainfall totals of 2 to 4 inches with local maximum totals of 6 
inches into Monday across mainly coastal portions of the following 
Mexican States: Colima, Jalisco, and Nayarit.

These heavy rains may produce localized flash and urban flooding, 
along with possible mudslides in areas of higher coastal terrain. 

SURF:  Swells generated by Madeline will affect the southwestern
coast of Mexico for the next couple of days, and will spread
northward to the southern Baja California peninsula coast and the
coast of west-central Mexico tonight and Monday.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Latto

