

826 
WTPZ34 KNHC 190856
TCPEP4

BULLETIN
Tropical Storm Madeline Advisory Number   7
NWS National Hurricane Center Miami FL       EP142022
300 AM MDT Mon Sep 19 2022

...MADELINE INTENSIFIES A BIT MORE...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...20.3N 108.2W
ABOUT 160 MI...260 KM W OF CABO CORRIENTES MEXICO
ABOUT 210 MI...340 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Tropical Storm Madeline was 
located near latitude 20.3 North, longitude 108.2 West. Madeline is 
moving toward the northwest near 9 mph (15 km/h). A gradual turn 
toward the west-northwest and then west is expected over the next 
24-36 hours. On the forecast track, the center of Madeline will 
gradually move away from the coast of Mexico and pass to the south 
of the Baja California peninsula by tonight.

Maximum sustained winds have increased to near 60 mph (95 km/h) with
higher gusts. Little change in strength is expected today, followed
by weakening expected to begin tonight. Madeline is forecast to
become a remnant low on Tuesday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Outer bands from Madeline are forecast to produce 
additional rainfall of 1 to 3 inches along the Jalisco coast into 
this afternoon and 1 to 2 inches this evening over the southern tip 
of Baja California.

SURF:  Swells generated by Madeline will affect the southwestern
coast of Mexico for the next couple of days, and will spread
northward to the southern Baja California peninsula coast and the
coast of west-central Mexico later today.  These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Papin


