

000
WTPZ34 KNHC 191500
TCPEP4

BULLETIN
Tropical Storm Madeline Advisory Number   8
NWS National Hurricane Center Miami FL       EP142022
900 AM MDT Mon Sep 19 2022

...MADELINE EXPECTED TO TURN WEST-NORTHWARD BY TONIGHT...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...20.6N 108.8W
ABOUT 200 MI...325 KM W OF CABO CORRIENTES MEXICO
ABOUT 175 MI...280 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Madeline was
located near latitude 20.6 North, longitude 108.8 West. Madeline is
moving toward the northwest near 8 mph (13 km/h).  A gradual turn
toward the west-northwest is expected by tonight followed by a 
westward motion on Wednesday. On the forecast track, the center of 
Madeline will gradually move away from the coast of Mexico and pass 
to the south of the Baja California peninsula by tonight.

Maximum sustained winds have increased to near 65 mph (100 km/h) 
with higher gusts.  Little change in strength is expected today, 
followed by weakening beginning tonight.  Madeline is forecast to 
become a remnant low by early Wednesday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Outer bands from Madeline are forecast to produce
additional rainfall of 1 to 3 inches along the Jalisco coast into
this afternoon and 1 to 2 inches this evening over the southern tip
of Baja California.

SURF:  Swells generated by Madeline will affect the southwestern
coast of Mexico for the next couple of days, and will spread
northward to the southern Baja California peninsula coast and the
coast of west-central Mexico later today.  These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Roberts

