

000
WTPZ34 KNHC 192031
TCPEP4

BULLETIN
Tropical Storm Madeline Advisory Number   9
NWS National Hurricane Center Miami FL       EP142022
Issued by the NWS Weather Prediction Center College Park MD
300 PM MDT Mon Sep 19 2022

...MADELINE HAS TURNED TO THE WEST-NORTHWEST...
...GUSTY WINDS REPORTED IN EXTREME SOUTHERN BAJA CALIFORNIA...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...20.9N 109.8W
ABOUT 140 MI...220 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Tropical Storm Madeline was
located near latitude 20.9 North, longitude 109.8 West. Madeline is
moving toward the west-northwest near 10 mph (17 km/h) and this
motion is expected to continue during the next day or so, followed 
by a turn to the west by Wednesday. 

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Gradual weakening is forecast, and Madeline is expected to become a 
post-tropical cyclone by early Wednesday.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Outer bands from Madeline are forecast to produce
additional rainfall of 1 to 2 inches this evening over the southern
tip of Baja California.

SURF:  Swells generated by Madeline will affect the southern Baja
California peninsula during the next couple of days.  These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster Cangialosi/Bann

