798 
WTPZ31 KNHC 290833
TCPEP1
 
BULLETIN
Tropical Depression Six-E Advisory Number   1
NWS National Hurricane Center Miami FL       EP062025
300 AM CST Sun Jun 29 2025
 
...TROPICAL DEPRESSION SIX-E FORMS OFFSHORE SOUTHERN MEXICO...
...TROPICAL STORM WATCHES ISSUED ALONG THE COAST OF SOUTHWESTERN
MEXICO...
 
 
SUMMARY OF 300 AM CST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...13.0N 99.5W
ABOUT 270 MI...435 KM S OF ACAPULCO MEXICO
ABOUT 520 MI...840 KM SE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...30 MPH...45 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has issued a Tropical Storm Watch
along the southwest coast of Mexico from Zihuatanejo to Manzanillo.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Southwest coast of Mexico from Zihuatanejo to Manzanillo
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in southwestern Mexico should monitor the
progress of Tropical Depression Six-E.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM CST (0900 UTC), the center of Tropical Depression Six-E
was located near latitude 13.0 North, longitude 99.5 West. The
depression is moving toward the west near 12 mph (19 km/h). A 
west-northwestward to northwestward motion should begin later today 
and continue through the next few days.
 
Maximum sustained winds are near 30 mph (45 km/h) with higher 
gusts. Gradual strengthening is forecast during the next day, 
followed by steady to rapid strengthening thereafter, and the 
depression is expected to become a hurricane on Tuesday.
 
The estimated minimum central pressure is 1008 mb (29.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Tropical Depression Six-E is expected to produce rainfall
totals of 3 to 6 inches, with isolated maximum totals of 10 inches,
across portions of the Mexican states of Oaxaca, Guerrero,
Michoacán, Colima, and Jalisco through early next week. This
rainfall may lead to areas of life-threatening flooding and
mudslides, especially in areas of steep terrain.
 
For a complete depiction of forecast rainfall associated with
Tropical Depression Six-E, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep6.shtml?rainqpf
 
WIND: Tropical storm conditions are possible along the coast within
the watch area Monday and Tuesday.
 
SURF: Swells generated by Tropical Depression Six-E will begin 
increasing along the coast of southwestern Mexico Monday and 
continue into mid-week. These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM CST.
Next complete advisory at 900 AM CST.
 
$$
Forecaster Hagen
  