089 
WTPZ31 KNHC 291139
TCPEP1
 
BULLETIN
Tropical Depression Six-E Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       EP062025
600 AM CST Sun Jun 29 2025
 
...DEPRESSION BECOMING BETTER ORGANIZED...
 
 
SUMMARY OF 600 AM CST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...13.2N 99.7W
ABOUT 255 MI...410 KM S OF ACAPULCO MEXICO
ABOUT 500 MI...810 KM SE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Southwest coast of Mexico from Zihuatanejo to Manzanillo
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in southwestern Mexico should monitor the
progress of Tropical Depression Six-E.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 AM CST (1200 UTC), the center of Tropical Depression Six-E
was located near latitude 13.2 North, longitude 99.7 West. The
depression is moving toward the west near 12 mph (19 km/h). A
west-northwestward to northwestward motion should begin later today
and continue through the next few days.
 
Maximum sustained winds have increased to near 35 mph (55 km/h) with 
higher gusts. Gradual strengthening is forecast today, followed by 
steady to rapid strengthening thereafter, and the system is expected 
to become a hurricane on Tuesday.
 
The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Tropical Depression Six-E is expected to produce rainfall
totals of 3 to 6 inches, with isolated maximum totals of 10 inches,
across portions of the Mexican states of Oaxaca, Guerrero,
Michoacán, Colima, and Jalisco through early next week. This
rainfall may lead to areas of life-threatening flooding and
mudslides, especially in areas of steep terrain.
 
For a complete depiction of forecast rainfall associated with
Tropical Depression Six-E, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep6.shtml?rainqpf
 
WIND: Tropical storm conditions are possible along the coast within
the watch area Monday and Tuesday.
 
SURF: Swells generated by Tropical Depression Six-E will begin
increasing along the coast of southwestern Mexico Monday and
continue into mid-week. These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.
 
$$
Forecaster Kelly
  