653 
WTPZ31 KNHC 291739
TCPEP1
 
BULLETIN
Tropical Storm Flossie Intermediate Advisory Number 2A
NWS National Hurricane Center Miami FL       EP062025
1200 PM CST Sun Jun 29 2025
 
...FLOSSIE MOVING WEST-NORTHWESTWARD...

 
SUMMARY OF 1200 PM CST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.6N 100.1W
ABOUT 225 MI...370 KM S OF ACAPULCO MEXICO
ABOUT 465 MI...750 KM SE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Southwest coast of Mexico from Zihuatanejo to Cabo Corrientes
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in southwestern Mexico should monitor the
progress of Tropical Storm Flossie.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1200 PM CST (1800 UTC), the center of Tropical Storm Flossie was 
located near latitude 13.6 North, longitude 100.1 West. Flossie is 
moving toward the west-northwest near 9 mph (15 km/h). A 
west-northwest to northwestward motion should continue over the next 
few days.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Steady strengthening is forecast during the next few days, and the 
system is expected to become a hurricane late Monday or Tuesday.
 
Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.
 
The estimated minimum central pressure is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Flossie can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP1 and WMO header
WTPZ41 KNHC.
 
RAINFALL: Tropical Storm Flossie is expected to produce rainfall
totals of 3 to 6 inches, with isolated maximum totals of 10 inches,
across portions of the Mexican states of Oaxaca, Guerrero,
Michoacán, Colima, and Jalisco through early next week. This
rainfall may lead to areas of life-threatening flooding and
mudslides, especially in areas of steep terrain.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Flossie, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
WIND: Tropical storm conditions are possible along the coast within
the watch area late Monday and Tuesday.
 
SURF: Swells generated by Flossie will affect portions of the coast
of southwestern Mexico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 PM CST.
 
$$
Forecaster Kelly
  