132 
WTPZ31 KNHC 011438
TCPEP1
 
BULLETIN
Hurricane Flossie Advisory Number  10
NWS National Hurricane Center Miami FL       EP062025
900 AM CST Tue Jul 01 2025
 
...FLOSSIE STRENGTHENS FURTHER AS RAINBANDS AFFECT PORTIONS OF THE
COAST OF MEXICO...
 
 
SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 105.9W
ABOUT 150 MI...245 KM SW OF MANZANILLO MEXICO
ABOUT 460 MI...740 KM SE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...974 MB...28.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Punta San Telmo to Playa Perula
 
A Tropical Storm Watch is in effect for...
* East of Punta San Telmo to Zihuatanejo
* North of Playa Perula to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in southwestern Mexico should monitor the
progress of Flossie.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Hurricane Flossie was
located near latitude 17.4 North, longitude 105.9 West. Flossie is
moving toward the northwest near 10 mph (17 km/h). A general
northwestward to west-northwestward motion with a slight decrease
in forward speed is expected for the next few days. On the forecast
track, Flossie should move away from southwestern Mexico today and
tonight.
 
Maximum sustained winds have increased to near 100 mph (155 km/h)
with higher gusts.  Additional strengthening is expected through
Wednesday morning, and Flossie could become a major hurricane
tonight or Wednesday morning. Steady to rapid weakening is expected
starting late Wednesday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).
 
The estimated minimum central pressure is 974 mb (28.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Flossie can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP1 and WMO header
WTPZ41 KNHC.
 
RAINFALL: Hurricane Flossie should produce additional rainfall
totals of 2 to 4 inches, with isolated maximum totals of 6 inches,
across coastal portions of the Mexican states of Michoacán, Colima,
and Jalisco into Wednesday. This rainfall could lead to localized
flash flooding.
 
For a complete depiction of forecast rainfall associated with
Hurricane Flossie, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within portions of the
warning area, and are possible within the watch areas, for the next
several hours.
 
SURF: Swells generated by Flossie will affect portions of the coast
of southwestern Mexico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM CST.
Next complete advisory at 300 PM CST.
 
$$
Forecaster Beven
  