526 
WTPZ31 KNHC 012032
TCPEP1
 
BULLETIN
Hurricane Flossie Advisory Number  11
NWS National Hurricane Center Miami FL       EP062025
200 PM MST Tue Jul 01 2025
 
...FLOSSIE MOVING WEST-NORTHWESTWARD...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...17.7N 106.7W
ABOUT 180 MI...290 KM WSW OF MANZANILLO MEXICO
ABOUT 415 MI...665 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...966 MB...28.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has discontinued all Tropical Storm
Watches for the southwestern coast of Mexico.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Punta San Telmo to Playa Perula
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
Interests elsewhere in southwestern Mexico should monitor the
progress of Flossie.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Hurricane Flossie was 
located near latitude 17.7 North, longitude 106.7 West. Flossie is 
moving toward the northwest near 7 mph (11 km/h). A west-northwest 
to northwest motion is anticipated during the next few days.
 
Maximum sustained winds are near 110 mph (175 km/h) with higher 
gusts. Some additional strengthening is possible today and tonight. 
By Wednesday, steady to rapid weakening is expected.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).
 
The estimated minimum central pressure is 966 mb (28.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Flossie can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP1 and WMO header
WTPZ41 KNHC.
 
RAINFALL: Hurricane Flossie should produce additional rainfall
totals of 1 to 2 inches, with isolated maximum totals of 4 inches,
across coastal portions of the Mexican states of Michoacán, Colima,
and Jalisco into Wednesday. This rainfall could lead to localized
flash flooding.
 
For a complete depiction of forecast rainfall associated with
Hurricane Flossie, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within portions of the
warning area for the next few hours.
 
SURF: Swells generated by Flossie will affect portions of the coast
of southwestern Mexico, and the Baja California peninsula during the
next few days. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 500 PM MST.
Next complete advisory at 800 PM MST.
 
$$
Forecaster Kelly/E.Adams
  