000
WTPZ31 KNHC 032029
TCPEP1
 
BULLETIN
Post-Tropical Cyclone Flossie Advisory Number  19
NWS National Hurricane Center Miami FL       EP062025
200 PM MST Thu Jul 03 2025
 
...FLOSSIE NOW A POST-TROPICAL CYCLONE...
...THIS IS THE LAST NHC ADVISORY...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...21.2N 112.4W
ABOUT 200 MI...320 KM SW OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Post-Tropical Cyclone 
Flossie was located near latitude 21.2 North, longitude 112.4 West. 
The post-tropical cyclone is moving toward the northwest near 10 
mph (17 km/h). A general west-northwestward to northwestward 
motion is expected during the next couple of days.
 
Maximum sustained winds have decreased to near 40 mph (65 km/h)
with higher gusts. Continued steady weakening is expected, and the 
post-tropical low is forecast to dissipate this weekend.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Flossie will continue to affect portions
of the coast of southwestern Mexico and the Baja California
peninsula for another day or so. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on this system.  For additional information on the 
post-tropical low please see High Seas Forecasts issued by the 
National Weather Service, under AWIPS header NFDHSFEPI, WMO header 
FZPN02 KWBC, and on the web at ocean.weather.gov/shtml/NFDHSFEPI.php

$$
Forecaster Cangialosi
  