

000
WTPZ31 KNHC 060840
TCPEP1

BULLETIN
Tropical Storm Eugene Advisory Number   4
NWS National Hurricane Center Miami FL       EP062023
300 AM MDT Sun Aug 06 2023

...EUGENE CONTINUES TO STRENGTHEN AND COULD BECOME A HURRICANE
LATER TODAY...
...GUSTY WINDS LIKELY ACROSS SOUTHERN BAJA CALIFORNIA PENINSULA
TODAY...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...20.9N 109.9W
ABOUT 140 MI...220 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the southern portion of the Baja California peninsula
should monitor the progress of this system.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Tropical Storm Eugene was
located near latitude 20.9 North, longitude 109.9 West. Eugene is
moving toward the northwest near 14 mph (22 km/h).  A turn to the 
west-northwest is expected later today, and that motion should 
continue through Monday.  On the forecast track, Eugene should pass 
to the south of the southern portion of the Baja California Sur 
today.

Maximum sustained winds have increased to near 65 mph (100 km/h) 
with higher gusts.  Continued strengthening is expected and 
Eugene could become a hurricane later today.  Weakening should 
begin by tonight.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL: The outer edges of the rainfall pattern from Eugene may
produce storm total amounts of 1 to 2 inches along sections of the
southwestern Mexican states of Sinaloa, Jalisco, Nayarit, and
the southern portion of Baja California Sur.

SURF: Swells generated by Eugene will affect portions of the coasts
of west-central Mexico and Baja California Sur during the next day
or so. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.

WIND: Gusty winds are likely across the southern portion of Baja
California Sur today.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Cangialosi

