

000
WTPZ31 KNHC 062031
TCPEP1

BULLETIN
Tropical Storm Eugene Advisory Number   6
NWS National Hurricane Center Miami FL       EP062023
300 PM MDT Sun Aug 06 2023

...EUGENE MOVING QUICKLY AWAY FROM BAJA CALIFORNIA SUR...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...22.7N 113.2W
ABOUT 210 MI...340 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Tropical Storm Eugene was
located near latitude 22.7 North, longitude 113.2 West. Eugene is
moving toward the west-northwest near 20 mph (31 km/h), and this 
motion should continue for the next day or so, followed by a turn 
to the north and a sharp reduction in forward speed.  Eugene should 
continue moving farther away from Baja California Sur.

Maximum sustained winds remain near 70 mph (110 km/h) with higher
gusts.  Little change in strength is forecast tonight, followed by 
steady weakening likely starting on Monday.  Eugene could become a 
post-tropical cyclone late on Monday.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Eugene will affect portions of the coasts
of west-central Mexico and Baja California Sur during the next day
or so. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster Blake

