

000
WTPZ31 KNHC 070233
TCPEP1

BULLETIN
Tropical Storm Eugene Advisory Number   7
NWS National Hurricane Center Miami FL       EP062023
800 PM PDT Sun Aug 06 2023

...EUGENE CONTINUES TO MOVE AWAY FROM BAJA CALIFORNIA SUR...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...23.3N 115.0W
ABOUT 325 MI...525 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Eugene was
located near latitude 23.3 North, longitude 115.0 West.  Eugene is
moving toward the west-northwest near 20 mph (31 km/h), and this
motion should continue for the next day or so, followed by a turn
to the north and a sharp reduction in forward speed.  Eugene should
continue moving farther away from Baja California Sur.

Maximum sustained winds have decreased to near 60 mph (95 km/h) 
with higher gusts.  Eugene is forecast to weaken to a tropical 
depression on Monday.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 997 mb (29.44 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Eugene will affect portions of the coasts
of west-central Mexico and Baja California Sur during the next day
or so. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.

$$
Forecaster Pasch

