

903 
WTPZ31 KNHC 091756
TCPEP1

BULLETIN
Tropical Storm Max Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP162023
100 PM CDT Mon Oct 09 2023

...MAX MAKING LANDFALL IN MEXICO...
...TROPICAL STORM CONDITIONS AND HEAVY RAINFALL EXPECTED THIS 
AFTERNOON...


SUMMARY OF 100 PM CDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 101.2W
ABOUT 30 MI...50 KM SE OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Acapulco to Punta San Telmo

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case over the
next 12 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 PM CDT (1800 UTC), the center of Tropical Storm Max was 
making landfall located near latitude 17.4 North, longitude 101.2 
West. Max is moving toward the north-northeast near 5 mph (7 km/h) 
and this motion is expected to continue through tomorrow.  On the 
forecast track, Max should move inland over southern Mexico.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts. 
Rapid weakening is expected as Max moves inland, with the storm 
expected to dissipate over Mexico on Tuesday.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center. In the past few hours, a surface observing station
at Puerto Vicente Guerrero reported a wind gust of 51 mph (83 km/h).

The estimated minimum central pressure is 996 mb (29.42 inches). A 
surface observing station at Puerto Vicente Guerrero recently 
reported a minimum surface pressure of 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Max can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC
and on the web at hurricanes.gov/text/MIATCDEP1.shtml

RAINFALL:  Max is expected to produce rainfall totals of 4 to 8
inches with local maxima of 12 inches through Tuesday across the
states of Guerrero and Michoacan. These rains will likely produce
flash and urban flooding, along with possible mudslides in areas of
higher terrain near the coast.

WIND:  Tropical storm conditions are occurring in the warning area
and expected to overspread the warning area throughout the day.

SURF:  Swells generated by Max will affect the southern coast of
Mexico for the next day or two.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Papin


