

000
WTPZ31 KNHC 092036
TCPEP1

BULLETIN
Tropical Storm Max Advisory Number   8
NWS National Hurricane Center Miami FL       EP162023
400 PM CDT Mon Oct 09 2023

...MAX MOVING INLAND INTO SOUTHERN MEXICO...
...TROPICAL STORM CONDITIONS EXPECTED ALONG THE MEXICAN COAST
THROUGH THIS EVENING...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 101.0W
ABOUT 40 MI...65 KM E OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the tropical storm warning 
from Punta San Telmo to Lazaro Cardenas.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Acapulco to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case over the
next 12 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Max was 
located near latitude 17.6 North, longitude 101.0 West. Max is 
moving toward the north-northeast near 7 mph (11 km/h) and this 
motion is expected to continue until dissipation as the cyclone 
moves further inland over southern Mexico.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Rapid weakening is expected as Max moves inland, with the storm
expected to dissipate over Mexico on Tuesday.

Tropical-storm-force winds extend outward up to 60 miles (95 km) 
from the center. In the past few hours, a surface observing station 
at Puerto Vicente Guerrero reported a sustained wind of 41 mph (66 
km/h) with a wind gust up to 72 mph (116 km/h).

The estimated minimum central pressure is 995 mb (29.39 inches). 


HAZARDS AFFECTING LAND
----------------------
Key messages for Max can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC
and on the web at hurricanes.gov/text/MIATCDEP1.shtml

RAINFALL:  Max is expected to produce rainfall totals of 4 to 8
inches with local maxima of 12 inches through Tuesday across the
states of Guerrero and Michoacan. These rains will likely produce
flash and urban flooding, along with possible mudslides in areas of
higher terrain near the coast.

WIND:  Tropical storm conditions are occurring in the warning area
and expected to continue through this evening.

SURF:  Swells generated by Max will affect the southern coast of
Mexico for the next day or two.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Papin

