

003 
WTPZ31 KNHC 100840
TCPEP1

BULLETIN
Remnants Of Max Advisory Number  10
NWS National Hurricane Center Miami FL       EP162023
400 AM CDT Tue Oct 10 2023

...MAX DISSIPATES OVER MEXICO...
...THIS IS THE LAST ADVISORY...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...19.5N 100.5W
ABOUT 145 MI...230 KM NNE OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...25 MPH...40 KM/H
PRESENT MOVEMENT...NNE OR 25 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
-------------------- 
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the remnants of Max were located near
latitude 19.5 North, longitude 100.5 West. The remnants are moving
toward the north-northeast near 12 mph (19 km/h).

Maximum sustained winds are near 25 mph (40 km/h) with higher gusts.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Max will affect the southern coast of
Mexico today.  These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane
Center on this system.

$$
Forecaster Blake


