000
WTPZ31 KNHC 042055
TCPEP1
 
BULLETIN
Hurricane Kiko Advisory Number  19
NWS National Hurricane Center Miami FL       EP112025
Issued by the NWS Weather Prediction Center College Park MD
1100 AM HST Thu Sep 04 2025
 
...KIKO STILL A CATEGORY FOUR HURRICANE AND COULD BECOME A LITTLE
STRONGER...
...INTEREST IN THE HAWAIIAN ISLANDS SHOULD MONITOR KIKO'S
PROGRESS...
 
 
SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.9N 134.6W
ABOUT 1410 MI...2270 KM ESE OF HILO HAWAII
ABOUT 1615 MI...2600 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...951 MB...28.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Kiko was located
near latitude 13.9 North, longitude 134.6 West. Kiko is moving
toward the west near 9 mph (15 km/h) and this motion is expected to
continue through tonight, followed by a turn to the west-northwest 
on Friday through the weekend.
 
Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Kiko is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Fluctuations in intensity are expected in the
next two to three days, but Kiko is expected to remain a major 
hurricane through the weekend.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).
 
The estimated minimum central pressure is 951 mb (28.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko could begin reaching the
Hawaiian Islands towards the end of this weekend. These swells
could cause life-threatening surf and rip currents. Please consult
products by the National Weather Service in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.
 
$$
Forecaster Kleebauer/Papin
  