000
WTPZ31 KNHC 050858
TCPEP1
 
BULLETIN
Hurricane Kiko Advisory Number  21
NWS National Hurricane Center Miami FL       EP112025
1100 PM HST Thu Sep 04 2025
 
...KIKO REMAINS A STRONG CATEGORY 3 HURRICANE WELL TO THE
EAST-SOUTHEAST OF HAWAII...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.9N 136.2W
ABOUT 1310 MI...2110 KM ESE OF HILO HAWAII
ABOUT 1515 MI...2440 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Kiko was located 
near latitude 13.9 North, longitude 136.2 West.  Kiko is moving 
toward the west near 9 mph (15 km/h).  A gradual turn toward the 
west-northwest is expected later tonight or Friday, with this motion 
forecast to continue through the weekend with a slight increase in 
forward speed.
 
Maximum sustained winds are near 125 mph (205 km/h) with higher 
gusts.  Kiko is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Some strengthening is possible tonight and 
Friday, followed by slow weakening Friday night through the weekend.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).
 
The estimated minimum central pressure is 955 mb (28.20 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko could begin reaching the
Hawaiian Islands towards the end of this weekend. These swells
could cause life-threatening surf and rip currents. Please consult
products by the National Weather Service in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.
 
$$
Forecaster Jelsema (CPHC)
  