000
WTPZ31 KNHC 051435
TCPEP1
 
BULLETIN
Hurricane Kiko Advisory Number  22
NWS National Hurricane Center Miami FL       EP112025
Issued by the NWS Weather Prediction Center College Park MD
500 AM HST Fri Sep 05 2025
 
...KIKO NOW MOVING TO THE WEST-NORTHWEST WELL TO THE EAST-SOUTHEAST
OF HAWAII...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 137.1W
ABOUT 1245 MI...2005 KM ESE OF HILO HAWAII
ABOUT 1450 MI...2335 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Kiko was located
near latitude 14.2 North, longitude 137.1 West. Kiko is now moving
toward the west-northwest near 9 mph (15 km/h) and this motion is
expected to continue for the next few days.
 
Maximum sustained winds have decreased to near 115 mph (185 km/h) 
with higher gusts.  Kiko is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Fluctuations in intensity are 
expected during the next 48 hours followed by weakening by early 
next week.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).
 
The estimated minimum central pressure is 962 mb (28.41 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko could begin reaching the
Hawaiian Islands towards the end of this weekend. These swells
could cause life-threatening surf and rip currents. Please consult
products by the National Weather Service in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.
 
$$
Forecaster Roth/Papin
  