000
WTPZ31 KNHC 052041
TCPEP1
 
BULLETIN
Hurricane Kiko Advisory Number  23
NWS National Hurricane Center Miami FL       EP112025
Issued by the NWS Weather Prediction Center College Park MD
1100 AM HST Fri Sep 05 2025
 
...KIKO QUICKLY RE-INTENSIFIES INTO A CATEGORY FOUR HURRICANE AS IT
APPROACHES THE CENTRAL PACIFIC BASIN...
 
 
SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.5N 137.8W
ABOUT 1195 MI...1925 KM ESE OF HILO HAWAII
ABOUT 1400 MI...2255 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...951 MB...28.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Kiko was located
near latitude 14.5 North, longitude 137.8 West. Kiko is moving
toward the west-northwest near 10 mph (17 km/h) and this motion is
expected to continue over the next few days. On the forecast track, 
Kiko is expected to move into the central Pacific basin by tomorrow 
morning. 
 
Maximum sustained winds have increased to near 130 mph (215 km/h) 
with higher gusts.  Kiko is a category 4 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Additional strengthening is 
expected this afternoon and tonight before slow weakening begins on 
Saturday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).
 
The estimated minimum central pressure is 951 mb (28.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko could begin reaching the
Hawaiian Islands towards the end of this weekend. These swells
could cause life-threatening surf and rip currents. Please consult
products by the National Weather Service in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.
 
$$
Forecaster Roth/Papin
  