918 
WTPZ31 KNHC 060235
TCPEP1
 
BULLETIN
Hurricane Kiko Advisory Number  24
NWS National Hurricane Center Miami FL       EP112025
500 PM HST Fri Sep 05 2025
 
...KIKO STRENGTHENS AS A CATEGORY FOUR HURRICANE AS IT APPROACHES
THE CENTRAL PACIFIC BASIN...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...14.9N 138.7W
ABOUT 1130 MI...1820 KM ESE OF HILO HAWAII
ABOUT 1335 MI...2145 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...946 MB...27.94 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Hurricane Kiko was located
near latitude 14.9 North, longitude 138.7 West. Kiko is moving
toward the west-northwest near 12 mph (19 km/h) and this motion is
expected to continue over the next few days.
 
Maximum sustained winds are near 140 mph (220 km/h) with higher
gusts.  Kiko is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Additional strengthening is possible 
overnight and into Saturday before gradual weakening begins by 
Sunday. 
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).
 
The estimated minimum central pressure is 946 mb (27.94 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko are expected to begin
reaching the Big Island and Maui by Sunday. These swells will
gradually build and are forecast to peak along east facing exposures
of the Hawaiian Islands late Monday through midweek, potentially
producing life-threatening surf and rip currents. Listen for later
advisories and possible warnings from the National Weather Service
in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Gibbs (CPHC)
  