052 
WTPZ31 KNHC 060832
TCPEP1
 
BULLETIN
Hurricane Kiko Advisory Number  25
NWS National Hurricane Center Miami FL       EP112025
1100 PM HST Fri Sep 05 2025
 
...KIKO HOLDS STEADY AS A CATEGORY FOUR HURRICANE NEARING
THE CENTRAL PACIFIC BASIN...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.1N 139.7W
ABOUT 1065 MI...1710 KM ESE OF HILO HAWAII
ABOUT 1265 MI...2040 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...946 MB...27.94 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Kiko was located
near latitude 15.1 North, longitude 139.7 West. Kiko is moving
toward the west-northwest near 10 mph (17 km/h) and this motion is
expected to continue over the next few days.
 
Maximum sustained winds are near 140 mph (220 km/h) with higher
gusts. Kiko is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Only minor fluctuations in strength are 
anticipated through Saturday, with gradual weakening expected to 
begin by Sunday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).
 
The estimated minimum central pressure is 946 mb (27.94 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko are expected to begin
reaching the Big Island and Maui by Sunday. These swells will
gradually build and are forecast to peak along east facing exposures
of the Hawaiian Islands late Monday through midweek, potentially
producing life-threatening surf and rip currents. Listen for later
advisories and possible warnings from the National Weather Service
in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Future information on Kiko can be found under Central Pacific 
basin headers beginning at 500 AM HST, under AWIPS header HFOTCPCP4 
and WMO header WTPA34 PHFO.  Products will continue to be available 
on the web at hurricanes.gov
 
$$
Forecaster Gibbs (CPHC)
  