000
WTPA34 PHFO 061442
TCPCP4
 
BULLETIN
Hurricane Kiko Advisory Number  26
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
500 AM HST Sat Sep 06 2025
 
...KIKO ENTERS THE CENTRAL PACIFIC BASIN AS A CATEGORY 4
HURRICANE...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...15.5N 140.5W
ABOUT 1005 MI...1615 KM ESE OF HILO HAWAII
ABOUT 1205 MI...1945 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...948 MB...28.00 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Kiko was located
near latitude 15.5 North, longitude 140.5 West.  Kiko is moving
toward the west-northwest near 12 mph (19 km/h) and this general 
motion is expected to continue for the next few days.
 
Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Kiko is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Gradual weakening is expected over the next 
several days.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).
 
The estimated minimum central pressure is 948 mb (28.00 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko are expected to begin
reaching the Big Island and Maui by Sunday.  These swells will
gradually build and are forecast to peak along east-facing exposures
of the Hawaiian Islands late Monday through midweek, potentially
producing life-threatening surf and rip currents.  Listen for later
advisories and possible warnings from the National Weather Service
in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.
 
$$
Forecaster Pasch
  