000
WTPA34 PHFO 062035
TCPCP4
 
BULLETIN
Hurricane Kiko Advisory Number  27
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
1100 AM HST Sat Sep 06 2025
 
...KIKO WEAKENS SOME AS IT MOVES WEST-NORTHWESTWARD THROUGH THE
CENTRAL PACIFIC...
 
 
SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.1N 141.4W
ABOUT 935 MI...1500 KM ESE OF HILO HAWAII
ABOUT 1135 MI...1830 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...954 MB...28.17 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Kiko was located
near latitude 16.1 North, longitude 141.4 West. Kiko is moving
toward the west-northwest near 12 mph (19 km/h) and this general
motion is expected to continue for the next few days.
 
Maximum sustained winds are now near 120 mph (195 km/h) with higher
gusts.  Kiko is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Gradual weakening is expected over the next
several days.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).
 
The estimated minimum central pressure is 954 mb (28.17 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Hurricane Kiko are expected to reach the 
Big Island and Maui by Sunday.  These swells will gradually build 
and are forecast to peak along east-facing exposures of the Hawaiian 
Islands late Monday through midweek, potentially producing 
life-threatening surf and rip currents.  Listen for later advisories 
and possible warnings from the National Weather Service in Honolulu, 
Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.
 
$$
Forecaster Beven
  