000
WTPA34 PHFO 071438
TCPCP4
 
BULLETIN
Hurricane Kiko Advisory Number  30
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
500 AM HST Sun Sep 07 2025
 
...KIKO GRADUALLY WEAKENING OVER COOL WATERS...
...EXPECTED TO PASS NORTH OF THE HAWAIIAN ISLANDS ON TUESDAY AND
WEDNESDAY...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 144.4W
ABOUT 715 MI...1150 KM E OF HILO HAWAII
ABOUT 915 MI...1470 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...965 MB...28.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Kiko was located
near latitude 17.6 North, longitude 144.4 West.  Kiko is moving
toward the west-northwest near 13 mph (20 km/h), and this general 
motion is expected to continue through early Wednesday.  On the 
forecast track, the center of Kiko is expected to pass north of the 
Hawaiian Islands on Tuesday and Wednesday.
 
Maximum sustained winds have decreased to near 115 mph (185 km/h) 
with higher gusts.  Kiko is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Additional weakening is 
forecast during the next few days, and Kiko is expected to become a 
tropical storm on Tuesday.
 
Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).
 
The estimated minimum central pressure is 965 mb (28.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone 
Discussion under AWIPS header HFOTCDCP4 and WMO header WTPA44 PHFO.
 
SURF: Swells generated by Kiko are expected to begin reaching the 
Big Island and Maui later today. These swells will gradually build 
and are forecast to peak along east-facing exposures of the Hawaiian
Islands late Monday through midweek, potentially producing
life-threatening surf and rip currents.  Listen for later advisories
and possible warnings from the National Weather Service.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.
 
$$
Forecaster Berg
  