489 
WTPA34 PHFO 080250
TCPCP4
 
BULLETIN
Hurricane Kiko Advisory Number  32
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
500 PM HST Sun Sep 07 2025
 
...KIKO REMAINS A CATEGORY 2 HURRICANE...
...EXPECTED TO PASS NORTH OF THE HAWAIIAN ISLANDS ON TUESDAY AND
WEDNESDAY...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...18.9N 146.6W
ABOUT 555 MI...895 KM E OF HILO HAWAII
ABOUT 750 MI...1210 KM E OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...974 MB...28.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Hurricane Kiko was located
near latitude 18.9 North, longitude 146.6 West. Kiko is moving
toward the northwest near 14 mph (22 km/h) and this motion is
expected to continue for the next few days, with Kiko expected to 
pass north of the main Hawaiian Islands Tuesday and Wednesday.
 
Maximum sustained winds are near 105 mph (165 km/h) with higher 
gusts. Additional weakening is forecast during the next few days, 
and Kiko is expected to become a tropical storm late Monday or 
Monday night.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the 
center and tropical-storm-force winds extend outward up to 90 miles 
(150 km).

The minimum central pressure based on dropsonde data is 974 mb 
(28.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP4 and WMO header WTPA44 PHFO.
 
SURF: Swells generated by Kiko are expected to gradually build and 
are forecast to peak along east-facing exposures of the Hawaiian 
Islands late Monday through midweek, potentially producing 
life-threatening surf and rip currents. Listen for later advisories 
and possible warnings from the National Weather Service in Honolulu, 
Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Gibbs (CPHC)
  