ZCZC HFOTCPCP4 ALL
TTAA00 PHFO DDHHMM
 
BULLETIN
Tropical Storm Kiko Advisory Number  38
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
500 AM HST Tue Sep 09 2025
 
...KIKO FORECAST TO PASS NORTH OF THE HAWAII TUESDAY AND
WEDNESDAY...
...LIFE-THREATENING RIP CURRENTS AND HIGH SURF POSSIBLE ACROSS
PORTIONS OF HAWAIIAN ISLANDS...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...22.4N 153.4W
ABOUT 215 MI...350 KM NNE OF HILO HAWAII
ABOUT 300 MI...480 KM ENE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Tropical Storm Kiko was
located near latitude 22.4 North, longitude 153.4 West. Kiko is
moving toward the west-northwest near 14 mph (22 km/h) and this
motion is expected to continue for the next few days, while passing
north of the main Hawaiian Islands.
 
Maximum sustained winds have decreased to near 45 mph (75 km/h) with 
higher gusts. Additional weakening is expected, and the system may 
become post-tropical in a few days.
 
Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.
 
The estimated minimum central pressure is 1007 mb (29.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP4 and WMO header WTPA44 PHFO.
 
SURF: Swells generated by Kiko are building from east to west across
the exposed Hawaiian waters and are forecast to peak today
through Wednesday, potentially producing life-threatening surf and
rip currents. Refer to the latest updates and forecasts issued from
the National Weather Service in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.
 
$$
Forecaster Kelly
 
NNNN
  