ZCZC HFOTCPCP4 ALL
TTAA00 PHFO DDHHMM
 
BULLETIN
Tropical Storm Kiko Advisory Number  40
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
500 PM HST Tue Sep 09 2025
 
... KIKO STILL A TROPICAL STORM AND IS PRODUCING LIFE-THREATENING
RIP CURRENTS AND HIGH SURF ACROSS PORTIONS OF HAWAIIAN ISLANDS...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...22.9N 156.3W
ABOUT 150 MI...240 KM NE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Tropical Storm Kiko was
located near latitude 22.9 North, longitude 156.3 West. Kiko is
moving toward the west-northwest near 14 mph (22 km/h)  and this
motion is expected to continue for the next few days, while passing
north of the main Hawaiian Islands.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Weakening is expected, and the system is forecast to become 
post-tropical in a couple days.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
to the north of the center.
 
The estimated minimum central pressure is 1008 mb (29.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP4 and WMO header WTPA44 PHFO.
 
SURF: Swells generated by Kiko are building from east to west across
the exposed Hawaiian waters and are forecast to peak tonight
through Wednesday, potentially producing life-threatening surf and
rip currents. Refer to the latest updates and forecasts issued from
the National Weather Service in Honolulu, Hawaii.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Beven
 
NNNN
  