000
WTPA34 PHFO 100856
TCPCP4
 
BULLETIN
Tropical Storm Kiko Advisory Number  41
NWS Central Pacific Hurricane Center Honolulu HI   EP112025
Issued by NWS National Hurricane Center Miami FL
1100 PM HST Tue Sep 09 2025
 
... KIKO STILL A TROPICAL STORM AND HEADING WESTWARD JUST TO THE
NORTH OF HAWAIIAN ISLANDS...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...22.4N 157.1W
ABOUT 90 MI...145 KM NE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the western Hawaiian Islands should continue to
monitor the progress of Kiko.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Tropical Storm Kiko was
located near latitude 22.4 North, longitude 157.1 West. Kiko is
moving toward the west near 13 mph (20 km/h). A turn toward the
west-northwest is expected soon, with this general motion then
continuing during the next few days.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Slow weakening is expected during the next couple of days, with 
Kiko forecast to become a tropical depression on Wednesday and a
post-tropical remnant low by late Thursday or Thursday night.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.
 
The estimated minimum central pressure is 1008 mb (29.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Kiko can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP4 and WMO header WTPA44 PHFO.
 
SURF: Swells generated by Kiko will peak across exposed waters of
the western Hawaiian Islands tonight and Wednesday, producing
life-threatening surf and rip currents. Refer to the latest updates
and forecasts issued by the National Weather Service in Honolulu,
Hawaii for further information.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.
 
$$
Forecaster Jelsema (CPHC)
  