

000
WTNT34 KNHC 051458
TCPAT4

BULLETIN
Tropical Depression Fourteen Advisory Number   1
NWS National Hurricane Center Miami FL       AL142024
1000 AM CDT Sat Oct 05 2024

...TROPICAL DEPRESSION FORMS IN THE SOUTHWESTERN GULF OF MEXICO...
...FORECAST TO STRENGTHEN AND BRING THE RISK OF LIFE-THREATENING 
IMPACTS TO PORTIONS OF THE WEST COAST OF FLORIDA NEXT WEEK...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...22.1N 95.1W
ABOUT 210 MI...340 KM NNE OF VERACRUZ MEXICO
ABOUT 350 MI...565 KM W OF PROGRESO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNE OR 25 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Yucatan peninsula of Mexico, the Florida Peninsula, 
the Florida Keys, and the northwestern Bahamas should monitor the 
progress of this system. 

Hurricane and Storm Surge watches will likely be required for 
portions of Florida on Sunday.

DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Depression 
Fourteen was located near latitude 22.1 North, longitude 95.1 West. 
The depression is moving toward the north-northeast near 3 mph (6 
km/h).  A slow northeastward or east-northeastward motion is 
expected during the next day or so.  A faster east-northeastward to 
northeastward motion is forecast by Monday and Tuesday.  On the 
forecast track, the depression is forecast to remain over the 
southwestern Gulf of Mexico through Sunday night, then move across 
the south-central Gulf of Mexico on Monday and Tuesday, and approach 
the west coast of the Florida Peninsula by midweek. 

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts. 
Rapid strengthening is forecast during the next few days.  The 
depression is forecast to become a tropical storm later today and a 
hurricane by early Monday. The system could become a major 
hurricane while it moves across the central and eastern Gulf of 
Mexico. 

The estimated minimum central pressure is 1007 mb (29.74 inches).


HAZARDS AFFECTING LAND
----------------------
Key Messages for Tropical Depression Fourteen can be found in the 
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO 
header WTNT44 KNHC and on the web at 
hurricanes.gov/text/MIATCDAT4.shtml

Rainfall: The system may produce rainfall of 2 to 4 inches across 
portions of the northern Yucatan Peninsula and western Cuba.

Areas of heavy rainfall will also impact portions of Florida Sunday 
and Monday well ahead of the tropical system, with heavy rainfall 
more directly related to the system expected by later Tuesday 
through Wednesday. This rainfall brings the risk of flash, urban, 
and areal flooding, along with minor to isolated moderate river 
flooding.

For a complete depiction of forecast rainfall associated with 
Tropical Depression Fourteen, please see the National Weather 
Service Storm Total Rainfall Graphic, available at 
hurricanes.gov/graphics_at4.shtml?rainqpf.

SURF:  Swells generated by the system will begin to affect the coast 
of the southwestern Gulf of Mexico today.  These swells are expected 
to spread northward and eastward along much of the Gulf Coast by 
early next week. These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Brown

