

000
WTNT34 KNHC 060845
TCPAT4

BULLETIN
Tropical Storm Milton Advisory Number   4
NWS National Hurricane Center Miami FL       AL142024
400 AM CDT Sun Oct 06 2024

...NOAA HURRICANE HUNTER AIRCRAFT ENROUTE TO INVESTIGATE MILTON...
...RISK OF LIFE-THREATENING IMPACTS INCREASING FOR PORTIONS OF THE
FLORIDA WEST COAST...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...23.0N 94.9W
ABOUT 355 MI...565 KM WNW OF PROGRESO MEXICO
ABOUT 845 MI...1360 KM WSW OF TAMPA FLORIDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...E OR 90 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Celestun to Cancun

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in the remainder of the Yucatan peninsula of Mexico, the
Florida Peninsula, the Florida Keys, and the northwestern Bahamas
should monitor the progress of this system.

Hurricane and Storm Surge Watches will likely be required for
portions of Florida late today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Milton was
located near latitude 23.0 North, longitude 94.9 West. Milton is
moving toward the east near 5 mph (7 km/h).  An eastward to
east-northeastward motion is forecast during the next couple of
days, followed by a faster northeastward motion.  On the forecast
track, Milton is forecast to move across the Gulf of Mexico and
approach the west coast of the Florida Peninsula by midweek.

Maximum sustained winds have increased to near 50 mph (85 km/h) 
with higher gusts. Steady to rapid strengthening is forecast during 
the next few days. Milton is forecast to become a hurricane 
tonight, and it could become a major hurricane while it moves across 
the central and eastern Gulf of Mexico.

Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key Messages for Tropical Storm Milton can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/text/MIATCDAT4.shtml

RAINFALL: Rainfall amounts of 5 to 8 inches, with localized totals
up to 12 inches, are expected across portions of the Florida
Peninsula and the Keys through Wednesday night. This rainfall brings
the risk of flash, urban, and areal flooding, along with minor to
moderate river flooding.

Milton will also produce rainfall totals of 2 to 4 inches across
portions of the northern Yucatan Peninsula and western Cuba.

For a complete depiction of forecast rainfall associated with 
Milton, please see the National Weather Service Storm Total Rainfall 
Graphic, available at hurricanes.gov/graphics_at4.shtml?rainqpf and 
the Flash Flood Risk graphic at 
hurricanes.gov/graphics_at4.shtml?ero.

WIND: Tropical storm conditions are possible in the Tropical Storm
Watch area in the Yucatan Peninsula Monday night and Tuesday.

SURF:  Swells generated by the system will begin to affect the coast
of the southwestern Gulf of Mexico today.  These swells are expected
to spread northward and eastward along much of the Gulf Coast by
early next week, and could cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Beven

