

000
WTNT34 KNHC 062052
TCPAT4

BULLETIN
Hurricane Milton Advisory Number   6
NWS National Hurricane Center Miami FL       AL142024
400 PM CDT Sun Oct 06 2024

...MILTON CONTINUING TO RAPIDLY INTENSIFY...
...HURRICANE WATCH ISSUED FOR THE NORTHERN COAST OF YUCATAN 
PENINSULA...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...22.4N 93.8W
ABOUT 275 MI...440 KM WNW OF PROGRESO MEXICO
ABOUT 805 MI...1295 KM WSW OF TAMPA FLORIDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...E OR 100 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...983 MB...29.03 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Hurricane Watch for the north 
coast of the Yucatan Peninsula from Celestun to Cabo Catoche and a 
Tropical Storm Warning from east of Cabo Catoche to Cancun.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Celestun to Cabo Catoche

A Tropical Storm Warning is in effect for...
* Celestun to Cancun

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests in the remainder of the Yucatan peninsula of Mexico, the
Florida Peninsula, the Florida Keys, and the northwestern Bahamas
should monitor the progress of this system.

Storm Surge and Hurricane Watches will likely be issued for portions 
of Florida tonight or early Monday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Hurricane Milton was located
near latitude 22.4 North, longitude 93.8 West. Milton is moving
toward the east near 7 mph (11 km/h), and this general motion is 
expected today. An eastward to east-northeastward motion is 
forecast on Monday, followed by a faster northeastward motion on 
Tuesday and Wednesday.  On the forecast track, Milton is forecast 
to move just north of the Yucatan Peninsula and across the southern 
Gulf of Mexico Monday and Tuesday and approach the west coast of 
the Florida Peninsula by Wednesday.

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts.   Milton is forecast to rapidly intensify during
the next couple of days and become a major hurricane on Monday.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 983 mb (29.03 inches).


HAZARDS AFFECTING LAND
----------------------
Key Messages for Hurricane Milton can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/text/MIATCDAT4.shtml

STORM SURGE:  A storm surge will raise water levels by as much as 2 
to 4 feet above ground level along the northern coast of the 
Yucatan Peninsula in areas of onshore flow.  Near the coast, the 
surge will be accompanied by large and destructive waves.

RAINFALL: Rainfall amounts of 5 to 10 inches, with localized totals 
up to 15 inches, are expected across portions of the Florida 
Peninsula and the Keys through Wednesday night. This rainfall brings 
the risk of considerable flash, urban, and areal flooding, along 
with the potential for moderate to major river flooding.

Milton will also produce rainfall totals of 2 to 4 inches across 
portions of the northern Yucatan Peninsula.

For a complete depiction of forecast rainfall associated with 
Hurricane Milton, please see the National Weather Service Storm 
Total Rainfall Graphic, available at 
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk 
graphic at hurricanes.gov/graphics_at4.shtml?ero. 

WIND:  Tropical storm conditions are expected to begin as early as 
Monday morning in the warning area, and hurricane conditions are 
possible beginning Monday afternoon.

SURF:  Swells generated by the system are affecting the coast of the 
southwestern Gulf of Mexico today.  These swells are expected to 
spread northward and eastward along much of the Gulf Coast within 
the next day or two, and are likely to cause life-threatening surf 
and rip current conditions.  Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Blake

