

000
WTNT34 KNHC 101730
TCPAT4

BULLETIN
Post-Tropical Cyclone Milton Intermediate Advisory Number 22A
NWS National Hurricane Center Miami FL       AL142024
200 PM EDT Thu Oct 10 2024

...MILTON BECOMES A HURRICANE-FORCE EXTRATROPICAL LOW...
...TROPICAL STORM CONDITIONS AND STORM SURGE STILL OCCURRING OVER 
PORTIONS OF THE SOUTHEASTERN U.S. COAST...


SUMMARY OF 200 PM EDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...29.3N 77.5W
ABOUT 200 MI...320 KM ENE OF CAPE CANAVERAL FLORIDA
ABOUT 200 MI...325 KM N OF GREAT ABACO ISLAND
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...ENE OR 70 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...983 MB...29.03 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

Storm Surge and Tropical Storm Warnings have been discontinued south 
of the Flagler/Volusia County Line.

The government of the Bahamas has discontinued the Tropical Storm 
Warning for the extreme northwestern Bahamas.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Storm Surge Warning is in effect for...
* Flagler/Volusia County Line northward to Altamaha Sound Georgia, 
including the St. Johns River

A Tropical Storm Warning is in effect for...
* Flagler/Volusia County Line northward to Edisto Beach South 
Carolina

A Storm Surge Warning means there is a danger of life-threatening
inundation, from rising water moving inland from the coastline in
the indicated locations. For a depiction of areas at risk, please
see the National Weather Service Storm Surge Watch/Warning Graphic,
available at hurricanes.gov.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM EDT (1800 UTC), the center of Post-Tropical Cyclone 
Milton was located near latitude 29.3 North, longitude 77.5 West.  
Milton is moving toward the east-northeast near 21 mph (33 km/h).  
A turn toward the east is expected later today, with that motion 
forecast to continue over the western Atlantic for the next few 
days.  On the forecast track, the center of Milton will continue to 
move away from the east coast of Florida and pass north of the 
northwestern Bahamas this afternoon.

Satellite-derived wind data indicate Milton has become a powerful 
post-tropical cyclone with maximum sustained winds near 75 mph (120 
km/h) with higher gusts.  Gradual weakening is expected during the 
next several days.

Hurricane-force winds extend outward up to 70 miles (110 km) 
northwest of the center and tropical-storm-force winds extend 
outward up to 310 miles (500 km).

The estimated minimum central pressure is 983 mb (29.03 inches).


HAZARDS AFFECTING LAND
----------------------
Key Messages for Milton can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC
and on the web at hurricanes.gov/text/MIATCDAT4.shtml

STORM SURGE: The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...

Flagler/Volusia County Line, FL to Altamaha Sound, GA...3-5 ft
St. Johns River...2-4 ft

The deepest water will occur along the immediate coast in areas of
onshore winds, where the surge will be accompanied by large and
dangerous waves.  Surge-related flooding depends on the relative
timing of the surge and the tidal cycle, and can vary greatly over
short distances.  For information specific to your area, please see
products issued by your local National Weather Service forecast
office.

For a complete depiction of areas at risk of storm surge
inundation, please see the National Weather Service Peak Storm
Surge Graphic, available at
hurricanes.gov/graphics_at4.shtml?peakSurge.

RAINFALL: Additional rainfall amounts around an inch are possible
along the northeastern coast of Florida through today.  In the wake
of heavy rainfall from Milton, the risk of considerable urban
flooding will linger through this morning across east central
Florida.  Moderate to major river flooding is ongoing and forecast
throughout central Florida.

For a complete depiction of forecast rainfall associated with
Post-Tropical Cyclone Milton, please see the National Weather 
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at4.shtml?ero.

WIND: Tropical storm conditions will continue within the tropical 
storm warning areas in Florida, Georgia, and South Carolina for the 
next few hours.

SURF:  Swells generated by Milton are expected to continue to
affect portions of the southeast U.S. and the Bahamas during the
next couple of days.  These swells could cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM EDT.

$$
Forecaster Berg

