000
WTNT35 KNHC 130842
TCPAT5
 
BULLETIN
Tropical Storm Erin Advisory Number   8
NWS National Hurricane Center Miami FL       AL052025
500 AM AST Wed Aug 13 2025
 
...ERIN CONTINUES WESTWARD...
...EXPECTED TO BECOME A HURRICANE IN A COUPLE OF DAYS...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.5N 41.9W
ABOUT 1400 MI...2255 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 260 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the northern Leeward Islands, Virgin Islands, and
Puerto Rico should monitor the progress of Erin.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Erin was
located near latitude 16.5 North, longitude 41.9 West. Erin is
moving toward the west near 20 mph (31 km/h). This general motion
is expected into Thursday, with a west-northwestward motion 
beginning Thursday night and continuing into the weekend.
On the forecast track, the center of Erin is likely to move near or
just north of the northern Leeward Islands over the weekend.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Gradual strengthening is forecast to begin today, and Erin will 
likely become a hurricane by late Thursday or early Friday.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 1004 mb (29.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Erin will begin affecting portions of the 
northern Leeward Islands, the Virgin Islands and Puerto Rico by this 
weekend.  These swells are likely to cause life-threatening surf and 
rip current conditions. Please consult products from your local 
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Pasch
  