000
WTNT35 KNHC 131434
TCPAT5
 
BULLETIN
Tropical Storm Erin Advisory Number   9
NWS National Hurricane Center Miami FL       AL052025
1100 AM AST Wed Aug 13 2025
 
...ERIN CONTINUES GENERALLY WESTWARD...
...EXPECTED TO BECOME A HURRICANE IN A COUPLE OF DAYS...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.3N 43.4W
ABOUT 1305 MI...2100 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 265 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the northern Leeward Islands, Virgin Islands, and
Puerto Rico should monitor the progress of Erin.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Erin was
located near latitude 16.3 North, longitude 43.4 West. Erin is
moving toward the west near 17 mph (28 km/h). This general motion
is expected to continue into Thursday, with a west-northwestward 
motion beginning Thursday night and continuing into the weekend.
On the forecast track, the center of Erin is likely to move near or
just north of the northern Leeward Islands over the weekend.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Gradual strengthening is forecast to begin later today or tonight, 
and Erin is expected to become a hurricane by Friday.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 1004 mb (29.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Beven
  