499 
WTNT35 KNHC 132034
TCPAT5
 
BULLETIN
Tropical Storm Erin Advisory Number  10
NWS National Hurricane Center Miami FL       AL052025
500 PM AST Wed Aug 13 2025
 
...ERIN STRENGTHENS AS IT MOVES WESTWARD...
...EXPECTED TO BECOME A HURRICANE IN A DAY OR TWO...
 
 
SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...16.3N 45.0W
ABOUT 1200 MI...1930 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the northern Leeward Islands, Virgin Islands, and
Puerto Rico should monitor the progress of Erin.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Erin was
located near latitude 16.3 North, longitude 45.0 West. Erin is
moving toward the west near 17 mph (28 km/h). This general motion
is expected to continue into Thursday, with a west-northwestward
motion beginning Thursday night and continuing into the weekend.
On the forecast track, the center of Erin is likely to move near or
just north of the northern Leeward Islands over the weekend.
 
Maximum sustained winds have increased to near 50 mph (85 km/h) 
with higher gusts. Gradual strengthening is forecast during the 
next couple of days, and Erin is expected to become a hurricane by 
Friday.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC. 

SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Beven
  