341 
WTNT35 KNHC 141435
TCPAT5
 
BULLETIN
Tropical Storm Erin Advisory Number  13
NWS National Hurricane Center Miami FL       AL052025
1100 AM AST Thu Aug 14 2025
 
...ERIN STRENGTHENING WHILE MOVING WESTWARD...
...FORECAST TO BECOME A HURRICANE BY TOMORROW...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.4N 49.7W
ABOUT 890 MI...1435 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the northern Leeward Islands, Virgin Islands, and
Puerto Rico should monitor the progress of Erin.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Erin was
located near latitude 16.4 North, longitude 49.7 West. Erin is
moving toward the west near 17 mph (28 km/h). A turn toward the
west-northwest is expected tonight, with this motion expected to
continue into the weekend. On the forecast track, the center of
Erin is likely to move near or just north of the northern Leeward
Islands over the weekend.
 
Maximum sustained winds have increased to near 60 mph (95 km/h)
with higher gusts. Additional strengthening is forecast during the
next day or so, and Erin is expected to become a hurricane on
Friday.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Beven
  