000
WTNT35 KNHC 150843
TCPAT5
 
BULLETIN
Tropical Storm Erin Advisory Number  16
NWS National Hurricane Center Miami FL       AL052025
500 AM AST Fri Aug 15 2025
 
...ERIN FORECAST TO STRENGTHEN INTO A HURRICANE TODAY...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...17.8N 54.4W
ABOUT 570 MI...920 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Anguilla and Barbuda
* St. Martin and St. Barthelemy
* Saba and St. Eustatius
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Erin was
located near latitude 17.8 North, longitude 54.4 West. Erin is
moving toward the west-northwest near 17 mph (28 km/h). This motion
is expected to continue into the weekend. On the forecast track, the
center of Erin is likely to move near or just north of the northern
Leeward Islands over the weekend.
 
Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts. Steady strengthening is expected during the next few days and
Erin is forecast to become a hurricane later today and could become
a major hurricane by this weekend.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.
 
The minimum central pressure based on dropsonde data is 997 mb 
(29.44 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: Tropical Storm Erin is expected to produce areas of heavy
rainfall beginning late Friday and continuing through the weekend
across the northernmost Leeward Islands, the U.S. and British Virgin
Islands, as well as southern and eastern Puerto Rico.  Rainfall
totals of 2 to 4 inches, with isolated totals of 6 inches, are
expected. This rainfall may lead to isolated flash and urban
flooding, along with landslides or mudslides.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Tropical Storm Erin, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area by early Saturday.
 
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend, and will likely spread to the western Atlantic next
week.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Kelly
  