000
WTNT35 KNHC 151156
TCPAT5
 
BULLETIN
Tropical Storm Erin Intermediate Advisory Number 16A
NWS National Hurricane Center Miami FL       AL052025
800 AM AST Fri Aug 15 2025
 
...ERIN BECOMING BETTER ORGANIZED AND IS EXPECTED TO BECOME A 
HURRICANE LATER TODAY...
 
 
SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...18.1N 55.2W
ABOUT 520 MI...835 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Anguilla and Barbuda
* St. Martin and St. Barthelemy
* Saba and St. Eustatius
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Erin was
located near latitude 18.1 North, longitude 55.2 West. Erin is
moving toward the west-northwest near 17 mph (28 km/h). This motion
is expected to continue into the weekend. On the forecast track, the
center of Erin is likely to move near or just north of the northern
Leeward Islands over the weekend.
 
Maximum sustained winds are near 70 mph (110 km/h) with higher 
gusts.  Steady strengthening is expected during the next few days 
and Erin is forecast to become a hurricane later today, and it could 
become a major hurricane by this weekend.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
mainly to the northeast of the center.
 
The latest minimum central pressure estimated from NOAA Hurricane 
Hunter aircraft data is 998 mb (29.47 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: Tropical Storm Erin is expected to produce areas of heavy
rainfall beginning late Friday and continuing through the weekend
across the northernmost Leeward Islands, the U.S. and British Virgin 
Islands, as well as southern and eastern Puerto Rico.  Rainfall 
totals of 2 to 4 inches, with isolated totals of 6 inches, are 
expected. This rainfall may lead to isolated flash and urban 
flooding, along with landslides or mudslides.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Tropical Storm Erin, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area by early Saturday.
 
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend, and will likely spread to the western Atlantic next
week.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Beven
  