000
WTNT35 KNHC 151736
TCPAT5
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 17A
NWS National Hurricane Center Miami FL       AL052025
200 PM AST Fri Aug 15 2025
 
...ERIN MOVING QUICKLY WEST-NORTHWESTWARD...
...EXPECTED TO PASS NEAR OR NORTH OF THE LEEWARD ISLANDS ON
SATURDAY...
 
 
SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...18.6N 56.8W
ABOUT 415 MI...665 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Anguilla and Barbuda
* St. Martin and St. Barthelemy
* Saba and St. Eustatius
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Hurricane Erin was located
near latitude 18.6 North, longitude 56.8 West. Erin is moving toward
the west-northwest near 17 mph (28 km/h). This motion is expected
to continue into the weekend. On the forecast track, the center of
Erin is likely to move near or just north of the northern Leeward 
Islands over the weekend.
 
Reports from an Air Force Reserve Hurricane Hunter aircraft indicate 
that maximum sustained winds are near 75 mph (120 km/h) with higher 
gusts.  Steady to rapid strengthening is expected during the next 
two to three days, and Erin is forecast to become a major hurricane 
during the weekend.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from
the center and tropical-storm-force winds extend outward up to 115
miles (185 km) mainly to the north of the center.
 
The minimum central pressure extrapolated by the Hurricane Hunter 
aircraft is 993 mb (29.33 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone 
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin are expected to produce areas of
heavy rainfall tonight into Sunday across the northern Leeward
Islands, the Virgin Islands, and Puerto Rico. Rainfall totals of 2
to 4 inches, with isolated totals of 6 inches, are expected.  This
rainfall may lead to isolated and locally considerable flash and
urban flooding, along with landslides or mudslides.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area by early Saturday.
 
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend, and will likely spread to the western Atlantic next week.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Beven
  