226 
WTNT35 KNHC 152350
TCPAT5
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 18A
NWS National Hurricane Center Miami FL       AL052025
800 PM AST Fri Aug 15 2025
 
...ERIN INTENSIFYING AS IT NEARS ITS CLOSEST APPROACH TO THE NORTH 
OF THE LEEWARD ISLANDS...
 
 
SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...19.4N 58.5W
ABOUT 310 MI...500 KM ENE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...982 MB...29.00 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of Antigua/Barbuda has discontinued 
the Tropical Storm Watch for the island of Barbuda.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Anguilla
* St. Martin and St. Barthelemy
* Saba and St. Eustatius
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case over the next 24 
hours. 
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico, as well as in the Turks and Caicos and the
southeastern Bahamas should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Hurricane Erin was located
near latitude 19.4 North, longitude 58.5 West. Erin is moving toward
the west-northwest near 17 mph (28 km/h). This motion is expected
to continue through the weekend with a gradual decrease in forward 
speed. On the forecast track, the center of Erin is likely to move 
just north of the northern Leeward Islands, the Virgin Islands, and 
Puerto Rico over the weekend.
 
NOAA Hurricane Hunter aircraft data indicates that maximum 
sustained winds have increased to near 85 mph (140 km/h) with higher 
gusts.  Steady to rapid strengthening is expected over the next few 
days, and Erin is forecast to become a major hurricane during the 
weekend. Both NOAA and Air Force Reserve Hurricane Hunter aircraft 
are investigating Erin this evening.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the 
center and tropical-storm-force winds extend outward up to 115 miles 
(185 km).
 
The minimum central pressure estimated from NOAA Hurricane Hunter 
dropsonde data is 982 mb (29.00 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin are expected to produce areas of
heavy rainfall tonight into Sunday across the northern Leeward
Islands, the Virgin Islands, and Puerto Rico. Rainfall totals of 2
to 4 inches, with isolated totals of 6 inches, are expected. This
rainfall may lead to isolated and locally considerable flash and
urban flooding, along with landslides or mudslides.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area by early Saturday.
 
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands and Puerto Rico by this
weekend, and will likely spread to the western Atlantic early next 
week. These swells are likely to cause life-threatening surf and 
rip current conditions. Please consult products from your local 
weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Papin
  