392 
WTNT35 KNHC 160256
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  19
NWS National Hurricane Center Miami FL       AL052025
1100 PM AST Fri Aug 15 2025
 
...ERIN NOW A CATEGORY 2 HURRICANE AND EXPECTED TO RAPIDLY
INTENSIFY INTO A MAJOR HURRICANE THIS WEEKEND...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...19.5N 59.5W
ABOUT 250 MI...405 KM ENE OF ANGUILLA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Anguilla
* St. Martin and St. Barthelemy
* Saba and St. Eustatius
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 24
hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico, as well as in the Turks and Caicos and the
southeastern Bahamas should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Erin was located 
near latitude 19.5 North, longitude 59.5 West. Erin is moving toward 
the west-northwest near 17 mph (28 km/h). This motion is expected to 
continue through the weekend with a gradual decrease in forward 
speed. On the forecast track, the center of Erin is likely to move 
just north of the northern Leeward Islands, the Virgin Islands, and 
Puerto Rico over the weekend.
 
Air Force reconnaissance aircraft indicate that maximum sustained
winds have increased to near 100 mph (155 km/h) with higher gusts.
Rapid strengthening is forecast over the next 24-36 hours, and Erin
is forecast to become a major hurricane during the weekend.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).
 
The minimum central pressure estimated by NOAA and Air Force
dropsonde data is 979 mb (28.91 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin are expected to produce areas of
heavy rainfall tonight into Sunday across the northern Leeward
Islands, the Virgin Islands, and Puerto Rico. Rainfall totals of 2
to 4 inches, with isolated totals of 6 inches, are expected. This
rainfall may lead to isolated and locally considerable flash and
urban flooding, along with landslides or mudslides.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area by early Saturday.
 
SURF:  Swells generated by Erin will begin affecting portions of the
northern Leeward Islands, the Virgin Islands, Puerto Rico,
Hispaniola, and the Turks and Caicos Islands this weekend, and will
likely spread to the Bahamas, Bermuda, and the east coast of the
United States early next week. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather forecast office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.
 
$$
Forecaster Papin
  