973 
WTNT35 KNHC 160530
TCPAT5
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 19A
NWS National Hurricane Center Miami FL       AL052025
200 AM AST Sat Aug 16 2025
 
...ERIN FORECAST TO BECOME A MAJOR HURRICANE LATER IN THE WEEKEND...
...OUTER RAINBANDS BEGINNING TO AFFECT THE NORTHERN LEEWARD 
ISLANDS...
 
 
SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...19.7N 60.6W
ABOUT 195 MI...310 KM ENE OF ANGUILLA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...971 MB...28.67 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of the Netherlands has discontinued the 
Tropical Storm Watch for Saba and St. Eustatius
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Anguilla
* St. Martin and St. Barthelemy
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 12 to 
24 hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico, as well as in the Turks and Caicos and the
southeastern Bahamas should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the eye of Hurricane Erin was located
near latitude 19.7 North, longitude 60.6 West. Erin is moving toward
the west-northwest near 17 mph (28 km/h). This motion is expected 
to continue through the weekend with a gradual decrease in forward 
speed.  On the forecast track, the center of Erin is expected to 
move just north of the northern Leeward Islands, the Virgin 
Islands, and Puerto Rico over the weekend.
 
Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts. Rapid strengthening is expected over the next 24 to 36 
hours, and Erin is forecast to become a major hurricane later in 
the weekend.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 125
miles (205 km).
 
The minimum central pressure based on data from the Air Force 
Hurricane Hunter is 971 mb (28.67 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin are expected to produce areas of
heavy rainfall through Sunday across the northern Leeward Islands, 
the Virgin Islands, and Puerto Rico. Rainfall totals of 2 to 4 
inches, with isolated totals of 6 inches, are expected. This
rainfall may lead to isolated and locally considerable flash and
urban flooding, along with landslides or mudslides.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area later today.
 
SURF:  Swells generated by Erin will affect portions of the northern 
Leeward Islands, the Virgin Islands, Puerto Rico, Hispaniola, and 
the Turks and Caicos Islands through the weekend.  These swells will 
spread to the Bahamas, Bermuda, and the east coast of the United 
States early next week.  These rough ocean conditions will likely 
cause life-threatening surf and rip currents.  Please consult 
products from your local weather forecast office for more 
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Cangialosi
  