643 
WTNT35 KNHC 160834
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  20
NWS National Hurricane Center Miami FL       AL052025
500 AM AST Sat Aug 16 2025
 
...ERIN RAPIDLY STRENGTHENING...
...OUTER RAINBANDS BEGINNING TO AFFECT THE NORTHERN LEEWARD
ISLANDS...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...19.8N 61.1W
ABOUT 170 MI...275 KM NE OF ANGUILLA
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of Antigua/Barbuda has discontinued the
Tropical Storm Watch for Anguilla.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* St. Martin and St. Barthelemy
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next
12 hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico, as well as in the Turks and Caicos and the
southeastern Bahamas should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Erin was located
near latitude 19.8 North, longitude 61.1 West. Erin is moving toward
the west-northwest near 20 mph (31 km/h). This motion is expected
to continue through the weekend with a gradual decrease in forward
speed. A turn toward the north is expected to occur early next
week. On the forecast track, the center of Erin is expected to
move just north of the northern Leeward Islands, the Virgin
Islands, and Puerto Rico over the weekend.
 
Maximum sustained winds are near 120 mph (195 km/h) with higher
gusts.  Erin is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Continued rapid strengthening is expected, 
and Erin is forecast to become a Category 4 hurricane later today.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).
 
The estimated minimum central pressure is 955 mb (28.20 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin are expected to produce areas of
heavy rainfall through Sunday across the northern Leeward Islands,
the Virgin Islands, and Puerto Rico. Rainfall totals of 2 to 4
inches, with isolated totals of 6 inches, are expected. Locally
considerable flash and urban flooding, along with landslides or
mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area later today.
 
SURF:  Swells generated by Erin will affect portions of the northern
Leeward Islands, the Virgin Islands, Puerto Rico, Hispaniola, and
the Turks and Caicos Islands through the weekend.  These swells will
spread to the Bahamas, Bermuda, and the east coast of the United
States early next week.  These rough ocean conditions will likely
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Cangialosi
  