619 
WTNT35 KNHC 161731
TCPAT5
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 21A
NWS National Hurricane Center Miami FL       AL052025
200 PM AST Sat Aug 16 2025
 
...CATEGORY 5 ERIN PASSING NORTH OF THE NORTHERN LEEWARD ISLANDS...
...OUTER RAINBANDS AFFECTING THE NORTHERN LEEWARD ISLANDS...
 
 
SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...19.8N 63.3W
ABOUT 110 MI...180 KM N OF ANGUILLA
ABOUT 205 MI...335 KM ENE OF SAN JUAN PUERTO RICO
MAXIMUM SUSTAINED WINDS...160 MPH...260 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...915 MB...27.02 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* St. Martin and St. Barthelemy
* Sint Maarten
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next
12 hours.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico, as well as in the Turks and Caicos and the
southeastern Bahamas should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Hurricane Erin was located
near latitude 19.8 North, longitude 63.3 West. Erin is moving toward
the west near 16 mph (26 km/h), and this motion is expected to
continue this afternoon. A turn toward the west-northwest is
expected tonight with a decrease in forward speed, and a turn
toward the north is expected to occur early next week. On the
forecast track, the center of Erin is expected to move just north
of the northern Leeward Islands, the Virgin Islands, and Puerto
Rico through Sunday.
 
Reports from an Air Force Reserve Hurricane Hunter aircraft 
indicate that maximum sustained winds are near 160 mph (260 km/h) 
with higher gusts.  Erin is a category 5 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Some strengthening is possible 
this afternoon.  Fluctuations in intensity are expected for the 
rest of the weekend.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 140
miles (220 km) mainly to the north of the center.
 
The minimum central pressure estimated from the Hurricane Hunter 
aircraft data is 915 mb (27.02 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin are expected to continue producing
areas of heavy rainfall through Sunday across the northern Leeward
Islands, the Virgin Islands, and Puerto Rico. Rainfall totals of 2
to 4 inches, with isolated totals of 6 inches, are expected. Locally
considerable flash and urban flooding, along with landslides or
mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area today. Squalls with wind gusts to tropical-storm force may 
occur elsewhere over portions of the northern Leeward and Virgin 
Islands.
 
SURF:  Swells generated by Erin will affect portions of the northern
Leeward Islands, the Virgin Islands, Puerto Rico, Hispaniola, and
the Turks and Caicos Islands through the weekend.  These swells will
spread to the Bahamas, Bermuda, and the east coast of the United
States early next week.  These rough ocean conditions will likely
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Beven
  