ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Hurricane Erin Advisory Number  22
NWS National Hurricane Center Miami FL       AL052025
500 PM AST Sat Aug 16 2025
 
...CATEGORY 5 ERIN CONTINUING TO PASS NORTH OF THE NORTHERN LEEWARD
ISLANDS...
...NEW TROPICAL STORM WATCH FOR THE TURKS AND CAICOS ISLANDS...
 
 
SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...20.0N 64.0W
ABOUT 135 MI...220 KM NNW OF ANGUILLA
ABOUT 175 MI...285 KM NE OF SAN JUAN PUERTO RICO
MAXIMUM SUSTAINED WINDS...160 MPH...260 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...915 MB...27.02 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Government of the Bahamas has issued a Tropical Storm Watch for
the Turks and Caicos Islands.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* St. Martin and St. Barthelemy
* Sint Maarten
* Turks and Caicos Islands
 
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next
12 hours in the Leeward Islands and in the next 48 hours in the
Turks and Caicos Islands.
 
Interests elsewhere in the northern Leeward Islands, Virgin Islands,
and Puerto Rico, as well as in the southeastern Bahamas should
monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Erin was located
near latitude 20.0 North, longitude 64.0 West. Erin is moving toward
the west near 15 mph (24 km/h), and this motion is expected to
continue this evening. A turn toward the west-northwest is expected
tonight with a decrease in forward speed, and a turn toward the
north is expected to occur early next week. On the forecast track,
the center of Erin is expected to move just north of the northern
Leeward Islands, the Virgin Islands, and Puerto Rico through Sunday 
and pass to the east of the Turks and Caicos Islands and the 
southeastern Bahamas Sunday night and Monday.
 
Maximum sustained winds are near 160 mph (260 km/h) with higher 
gusts.  Erin is a category 5 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Fluctuations in intensity are expected 
tonight through Sunday night. A slow weakening is expected to begin 
on Monday. A NOAA Hurricane Hunter aircraft is en route to 
investigate Erin this evening.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km) mainly to the north of the center.
 
The estimated minimum central pressure is 915 mb (27.02 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin will continue to produce areas of
heavy rainfall through Sunday across the northern Leeward Islands,
the Virgin Islands, and Puerto Rico. Rainfall totals of 2 to 4
inches, with isolated totals of 6 inches, are expected. Locally
considerable flash and urban flooding, along with landslides or
mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch
area in the Leeward Islands tonight, and in the watch area in the 
Turks and Caicos Islands beginning on Sunday. Squalls with wind 
gusts to tropical-storm force may occur elsewhere over portions of 
the northern Leeward Islands, Virgin Islands, and Puerto Rico 
through Sunday. Squalls with wind gusts to tropical-storm force may 
also occur over the southeastern Bahamas beginning on Sunday.
 
SURF:  Swells generated by Erin will affect portions of the northern
Leeward Islands, the Virgin Islands, Puerto Rico, Hispaniola, and
the Turks and Caicos Islands through the weekend.  These swells will
spread to the Bahamas, Bermuda, and the east coast of the United
States by early next week.  These rough ocean conditions will likely
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Beven
 
NNNN
  