289 
WTNT35 KNHC 170258
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  23
NWS National Hurricane Center Miami FL       AL052025
1100 PM AST Sat Aug 16 2025
 
...ERIN STILL A FORMIDABLE CATEGORY 4 HURRICANE UNDERGOING
STRUCTURAL CHANGES...
...HEAVY RAINS AND GUSTY WINDS OCCURING OVER PUERTO RICO AND
THE VIRGIN ISLANDS...
 
 
SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.3N 65.1W
ABOUT 145 MI...235 KM NNE OF SAN JUAN PUERTO RICO
ABOUT 395 MI...635 KM E OF GRAND TURK ISLAND
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...937 MB...27.67 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of France has discontinued the Tropical
Storm Watch for St. Martin and St. Barthelemy.
 
The Meteorological Service of the Netherlands has discontinued the
Tropical Storm Watch for Sint Maarten.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Turks and Caicos Islands
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case in the next 36-48 hours
in the Turks and Caicos Islands.
 
Interests elsewhere in the Virgin Islands, Puerto Rico, and the
southeastern Bahamas should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the eye of Hurricane Erin was located 
near latitude 20.3 North, longitude 65.1 West. Erin is moving toward 
the west-northwest near 14 mph (22 km/h). This motion is expected to 
continue through Sunday with a decrease in forward speed. A turn 
more northward is expected to occur on Monday into Tuesday. On the 
forecast track, the center of Erin is expected to begin moving away 
from the Virgin Islands and Puerto Rico on Sunday, and pass to the 
east of the Turks and Caicos Islands and the southeastern Bahamas 
Sunday night and Monday.
 
NOAA Hurricane Hunter and Air Force Reserve reconnaissance data 
indicates that maximum sustained winds have decreased to near 140 
mph (220 km/h) with higher gusts. Erin is a category 4 hurricane on 
the Saffir-Simpson Hurricane Wind Scale. Fluctuations in intensity 
are expected over the next day or two due to inner-core structural 
changes with Erin.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 205 miles
(335 km).
 
The estimated minimum central pressure measured by Air Force reserve
dropsonde data is 937 mb (27.67 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin will continue to produce areas of
heavy rainfall through Sunday across the northern Leeward Islands,
the Virgin Islands, and Puerto Rico. Rainfall totals of 2 to 4
inches, with isolated totals of 8 inches, are expected. Locally
considerable flash and urban flooding, along with landslides or
mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch area
in the Turks and Caicos Islands beginning late Sunday. Squalls with
wind gusts to tropical-storm force may occur elsewhere over portions
of the northern Leeward Islands, Virgin Islands, and Puerto Rico
through Sunday. Squalls with wind gusts to tropical-storm force may
also occur over the southeastern Bahamas beginning late Sunday.
 
SURF:  Swells generated by Erin will affect portions of the northern
Leeward Islands, the Virgin Islands, Puerto Rico, Hispaniola, and
the Turks and Caicos Islands through the weekend.  These swells will
spread to the Bahamas, Bermuda, and the east coast of the United
States by early next week.  These rough ocean conditions will likely
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.
 
$$
Forecaster Papin
  