000
WTNT35 KNHC 170531
TCPAT5
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 23A
NWS National Hurricane Center Miami FL       AL052025
200 AM AST Sun Aug 17 2025
 
...ERIN'S OUTER RAINBANDS PRODUCING GUSTY WINDS AND HEAVY RAINS 
ACROSS THE VIRGIN ISLANDS AND PUERTO RICO... 
 
 
SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...20.4N 66.1W
ABOUT 140 MI...220 KM N OF SAN JUAN PUERTO RICO
ABOUT 330 MI...535 KM ESE OF GRAND TURK ISLAND
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...940 MB...27.76 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Turks and Caicos Islands
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case in the next 24 hours.
 
Interests elsewhere in the Virgin Islands, Puerto Rico, and the
southeast and central Bahamas should monitor the progress of 
Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Hurricane Erin was located 
near latitude 20.4 North, longitude 66.1 West. Erin is moving toward 
the west-northwest near 14 mph (22 km/h). This motion with a 
decrease in forward speed is expected today, followed by a turn 
to the north on Monday and Tuesday. On the forecast track, the 
core of Erin is expected to pass to the east of the Turks and 
Caicos Islands and the southeastern Bahamas tonight and Monday.
 
Maximum sustained winds are near 125 mph (205 km/h) with higher 
gusts. Erin is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Fluctuations in intensity are expected over 
the next day or two due to inner-core structural changes.
 
Erin is becoming a larger system. Hurricane-force winds extend 
outward up to 25 miles (35 km) from the center and 
tropical-storm-force winds extend outward up to 205 miles (335 km).
 
The minimum central pressure based on data from the Air Force 
Hurricane Hunters is 940 mb (27.76 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin will continue to produce areas of
heavy rainfall today across the northern Leeward Islands,
the Virgin Islands, and Puerto Rico. Rainfall totals of 2 to 4
inches, with isolated totals of 8 inches, are expected. Locally
considerable flash and urban flooding, along with landslides or
mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are possible within the watch area
in the Turks and Caicos Islands beginning tonight. Squalls with
wind gusts to tropical storm force could occur over portions
of the Virgin Islands and Puerto Rico today and across the 
southeast and central Bahamas tonight through Tuesday.
 
SURF:  Swells generated by Erin will continue to affect portions of 
the northern Leeward Islands, the Virgin Islands, Puerto Rico, 
Hispaniola, and the Turks and Caicos Islands during the next couple 
of days. These swells will spread to the Bahamas, Bermuda, the 
east coast of the United States, and Atlantic Canada during the 
early and middle portions of the week.  These rough ocean conditions 
will likely cause life-threatening surf and rip currents.  Please 
consult products from your local weather forecast office for more 
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.
 
$$
Forecaster Cangialosi
  