928 
WTNT35 KNHC 171457
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  25
NWS National Hurricane Center Miami FL       AL052025
1100 AM AST Sun Aug 17 2025
 
...OUTER RAINBANDS OF ERIN STILL PRODUCING HEAVY RAINS AND
GUSTY WINDS ACROSS PUERTO RICO AND THE VIRGIN ISLANDS...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.0N 67.4W
ABOUT 200 MI...320 KM NNW OF SAN JUAN PUERTO RICO
ABOUT 240 MI...385 KM E OF GRAND TURK ISLAND
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...946 MB...27.94 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
 
A Tropical Storm Watch is in effect for...
* Southeast Bahamas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 24 hours.
 
Interests elsewhere in the central Bahamas, the North Carolina
Outer Banks, and Bermuda should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Erin was located
near latitude 21.0 North, longitude 67.4 West. Erin is moving toward
the west-northwest near 13 mph (20 km/h).  This general motion is
expected today, followed by a gradual turn to the north on Monday
and Tuesday.  On the forecast track, the core of Erin is expected to
pass to the east of the Turks and Caicos Islands and the
southeastern Bahamas tonight and Monday.
 
Maximum sustained winds are near 125 mph (205 km/h) with higher
gusts.  Erin is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Some fluctuation in intensity are likely
over the next couple of days, but Erin is expected to remain a
dangerous major hurricane through the middle of this week.
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 205 miles
(335 km).
 
The estimated minimum central pressure is 946 mb (27.94 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin will continue to produce areas of
heavy rainfall today across Puerto Rico. Additional rainfall of 2 to
4 inches, with locally higher amounts to 6 inches, are expected
across Puerto Rico through Monday, as well as the Turks and Caicos,
and the eastern Bahamas through San Salvador Island through Tuesday.
Locally considerable flash and urban flooding, along with landslides
or mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected across the warning
area in the Turks and Caicos Islands beginning tonight. Tropical
storm conditions are possible in the watch area in the Southeast
Bahamas tonight and Monday. Squalls with wind gusts to tropical
storm force could occur over portions of the Virgin Islands and
Puerto Rico today and across the central Bahamas Monday and Tuesday.
 
SURF:  Swells generated by Erin will continue to affect portions of
the Virgin Islands, Puerto Rico, Hispaniola, and the Turks and
Caicos Islands during the next couple of days. These swells will
spread to the Bahamas, Bermuda, the east coast of the United
States, and Atlantic Canada during the early and middle portions of
the week. These rough ocean conditions will likely cause
life-threatening surf and rip currents.  Please consult products
from your local weather forecast office for more information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  Minor coastal flooding is possible in areas of
onshore winds in the Turks and Caicos Islands.  Near the coast, the
surge will be accompanied by large waves.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.
 
$$
Forecaster Pasch
  