537 
WTNT35 KNHC 172349
TCPAT5
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 26A
NWS National Hurricane Center Miami FL       AL052025
800 PM AST Sun Aug 17 2025
 
...LIFE-THREATENING SURF AND RIP CURRENTS LIKELY ACROSS THE U.S.
EASTERN SEABOARD AS ERIN BECOMES A VERY LARGE HURRICANE THIS WEEK...
 
 
SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...22.1N 68.8W
ABOUT 310 MI...500 KM NW OF SAN JUAN PUERTO RICO
ABOUT 155 MI...245 KM ENE OF GRAND TURK ISLAND
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...946 MB...27.94 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
* Southeast Bahamas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.
 
Interests elsewhere in the central Bahamas, the North Carolina
Outer Banks, and Bermuda should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Hurricane Erin was located 
near latitude 22.1 North, longitude 68.8 West. Erin is moving toward 
the west-northwest near 13 mph (20 km/h). This general motion is 
expected tonight, followed by a gradual turn to the northwest and 
north on Monday and Tuesday.  On the forecast track, the core of 
Erin is expected to pass to the east and northeast of the Turks and 
Caicos Islands and the southeastern Bahamas tonight into Monday.
 
Maximum sustained winds are near 125 mph (205 km/h) with higher 
gusts.  Erin is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Some increase in size and strength is 
forecast during the next 48 hours. Erin is forecast to remain a 
large and dangerous major hurricane through the middle of this week.
 
Hurricane-force winds extend outward up to 50 miles (85 km) from
the center and tropical-storm-force winds extend outward up to 205
miles (335 km).
 
The estimated minimum central pressure is 946 mb (27.94 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: The outer bands of Erin continue to produce areas of heavy
rainfall across Puerto Rico.  Additional rainfall of 2 to 4 inches
are expected across Puerto Rico through Monday. Additional rainfall
of 2 to 4 inches, with locally higher amounts to 6 inches, are
forecast over the Turks and Caicos and the eastern Bahamas including
San Salvador Island through Tuesday. Locally considerable flash and
urban flooding, along with landslides or mudslides, are possible.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected in the Turks and
Caicos Islands beginning tonight.  Tropical storm conditions are
expected in the southeast Bahamas late tonight into Monday.
 
SURF:  Swells generated by Erin will continue to affect portions of
the Virgin Islands, Puerto Rico, Hispaniola, and the Turks and
Caicos Islands during the next couple of days.  These swells will
spread to the Bahamas, Bermuda, the east coast of the United
States, and Atlantic Canada during the early and middle portions of
the week. These rough ocean conditions will likely cause
life-threatening surf and rip currents.  Please consult products
from your local weather forecast office for more information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  Minor coastal flooding is possible in areas of
onshore winds in the Turks and Caicos Islands and the southeast
Bahamas.  Near the coast, the surge will be accompanied by large
waves.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.
 
$$
Forecaster Papin
  