000
WTNT35 KNHC 181447
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  29
NWS National Hurricane Center Miami FL       AL052025
1100 AM EDT Mon Aug 18 2025
 
...ERIN STRENGTHENS...
...EXPECTED TO GROW EVEN LARGER...
 
 
SUMMARY OF 1100 AM EDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...23.1N 70.8W
ABOUT 110 MI...180 KM N OF GRAND TURK ISLAND
ABOUT 880 MI...1420 KM SSE OF CAPE HATTERAS NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...935 MB...27.61 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
* Southeast Bahamas
 
A Tropical Storm Watch is in effect for...
* Central Bahamas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 12 to 24 hours.
 
Interests in the northwestern Bahamas, the North Carolina Outer
Banks, and Bermuda should monitor the progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM EDT (1500 UTC), the center of Hurricane Erin was located
near latitude 23.1 North, longitude 70.8 West. Erin is moving toward
the west-northwest near 10 mph (17 km/h).  A turn to the northwest 
is expected later today, followed by a turn to the north and on 
Tuesday.  On the forecast track, the core of Erin is expected to 
pass to the east of the southeastern Bahamas today and move between 
Bermuda and the east coast of the United States by the middle of the 
week.
 
Maximum sustained winds have increased to near 140 mph (220 km/h) 
with higher gusts.  Erin is a category 4 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Some additional strengthening 
is expected today.  Erin will remain a dangerous major hurricane 
through the middle of this week.
 
Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).
 
The minimum central pressure estimated from NOAA and Air 
Force Reserve Hurricane Hunter observations is 935 mb (27.61 
inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: Outer bands of Erin will produce localized areas of heavy 
rainfall across portions of Hispaniola through today and through 
Tuesday for the Turks and Caicos and the Bahamas east from San 
Salvador Island.  Additional rainfall of 2 to 4 inches, with 
locally higher amounts to 6 inches, are forecast.

For a complete depiction of forecast rainfall and flash flooding 
associated with Erin, please see the National Weather Service Storm 
Total Rainfall Graphic, available at 
hurricanes.gov/graphics_at5.shtml?rainqpf
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected today across the Turks
and Caicos Islands and the southeast Bahamas.  Tropical storm
conditions are possible in portions of the central Bahamas late
today through Tuesday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions will likely cause
life-threatening surf and rip currents.  Please consult products
from your local weather forecast office for more information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  Minor coastal flooding is possible in areas of
onshore winds in the Turks and Caicos Islands and the southeast
Bahamas.  Near the coast, the surge will be accompanied by large
waves.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM EDT.
Next complete advisory at 500 PM EDT.
 
$$
Forecaster Pasch/Roberts
  