569 
WTNT35 KNHC 190233
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  31
NWS National Hurricane Center Miami FL       AL052025
1100 PM EDT Mon Aug 18 2025
 
...ERIN MOVING NORTHWESTWARD TO THE EAST OF THE BAHAMAS...
...EXPECTED TO BRING HIGH SURF AND POSSIBLE TROPICAL STORM
CONDITIONS TO PARTS OF THE BAHAMAS AND THE U.S. ATLANTIC COAST...
 
 
SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.4N 71.7W
ABOUT 690 MI...1105 KM SW OF BERMUDA
ABOUT 780 MI...1255 KM SSE OF CAPE HATTERAS NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...949 MB...28.03 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
* Southeast Bahamas
 
A Storm Surge Watch is in effect for...
* Cape Lookout to Duck, North Carolina
 
A Tropical Storm Watch is in effect for...
* Central Bahamas
* Beaufort Inlet to Duck, North Carolina including Pamlico Sound
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Storm Surge Watch means there is a possibility of life-
threatening inundation, from rising water moving inland from the
coastline, in the indicated locations during the next 48 hours.
For a depiction of areas at risk, please see the National Weather
Service Storm Surge Watch/Warning Graphic, available at
hurricanes.gov.
 
Interests in the northwestern Bahamas, Bermuda, and other parts
of the southeastern coast of the United States should monitor the
progress of Erin.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Hurricane Erin was located
near latitude 24.4 North, longitude 71.7 West. Erin is moving toward
the northwest near 8 mph (13 km/h), and this motion is expected to 
continue tonight. A turn to the north is forecast on Tuesday or 
Tuesday night.  On the forecast track, the core of Erin is expected 
to move away from the southeastern Bahamas and the Turks and Caicos 
Islands tonight and move east of the remainder of the Bahamas on 
Tuesday.  The hurricane is then expected to move between Bermuda 
and the east coast of the United States by the middle of the week.
 
Reports from Air Force Reserve and NOAA Hurricane Hunter aircraft
indicate that maximum sustained winds are now near 125 mph (205 
km/h) with higher gusts.  Erin is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Fluctuations in strength are 
expected during the next couple of days. However, Erin is likely to 
remain a dangerous major hurricane through the middle of this week.
 
Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).
 
The minimum central pressure estimated from the Hurricane Hunter
aircraft data is 949 mb (28.03 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: Erin will produce localized areas of heavy rainfall across
portions of the southeastern Bahamas into Wednesday. Additional
rainfall of 2 to 4 inches, with storm total amounts to 8 inches, are
possible, which could lead to flash flooding and urban flood
concerns.  Portions of Hispaniola, the central Bahamas, and the
Turks and Caicos should receive an additional 1 to 2 inches of rain
as well.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected for a few more hours
across the Turks and Caicos Islands and the southeast Bahamas.
Tropical storm conditions are possible in portions of the central
Bahamas tonight through Tuesday.  Tropical storm conditions are
possible over portions of the North Carolina Outer Banks beginning
late Wednesday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions are expected to
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  Minor coastal flooding is possible in areas of onshore
winds in the Turks and Caicos Islands and the southeast Bahamas.
Near the coast, the surge will be accompanied by large waves.
 
The combination of a dangerous storm surge and the tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...
 
Cape Lookout to Duck, North Carolina...2 to 4 ft
 
The deepest water will occur along the immediate coast where the
surge will be accompanied by large and dangerous waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge
inundation, please see the National Weather Service Peak
Storm Surge Graphic, available at
hurricanes.gov/graphics_at5.shtml?peakSurge.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Beven
  