115 
WTNT35 KNHC 190856
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  32
NWS National Hurricane Center Miami FL       AL052025
500 AM EDT Tue Aug 19 2025
 
...ERIN FORECAST TO SUBSTANTIALLY GROW IN SIZE WHILE MOVING OVER
THE WESTERN ATLANTIC THROUGH THE WEEK...
...DANGEROUS RIP CURRENTS EXPECTED ALONG U.S. EAST COAST BEACHES...
 
 
SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...24.8N 72.0W
ABOUT 675 MI...1090 KM SW OF BERMUDA
ABOUT 750 MI...1205 KM SSE OF CAPE HATTERAS NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
* Southeast Bahamas
 
A Storm Surge Watch is in effect for...
* Cape Lookout to Duck, North Carolina
 
A Tropical Storm Watch is in effect for...
* Central Bahamas
* Beaufort Inlet to Duck, North Carolina including Pamlico Sound
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Storm Surge Watch means there is a possibility of life-
threatening inundation, from rising water moving inland from the
coastline, in the indicated locations during the next 48 hours.
For a depiction of areas at risk, please see the National Weather
Service Storm Surge Watch/Warning Graphic, available at
hurricanes.gov.
 
Interests in the northwestern Bahamas, Bermuda, and the U.S
Mid-Atlantic and southern New England coast should monitor the
progress of Erin.  Additional tropical storm watches and warnings
may be required later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Hurricane Erin was located
near latitude 24.8 North, longitude 72.0 West.  Erin is moving 
toward the northwest near 7 mph (11 km/h).  A turn toward the 
north-northwest with an increase in forward speed is expected 
today, followed by a northward motion on Wednesday and then a 
northeastward motion on Thursday.  On the forecast track, the 
center of Erin will pass to the east of the Bahamas today and 
tonight, and then move over the western Atlantic between the U.S. 
east coast and Bermuda on Wednesday and Thursday.
 
Maximum sustained winds are near 115 mph (185 km/h) with higher
gusts.  Erin is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Fluctuations in strength are possible over 
the next few days.
 
Erin is a large hurricane and will continue to grow in size.  
Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 205
miles (335 km).
 
The estimated minimum central pressure is 955 mb (28.20 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: Outer bands of Erin will produce localized areas of heavy
rainfall across portions of the Turks and Caicos today and through
tonight for the Bahamas. Additional rainfall of 1 to 3 inches, with
storm total amounts to 8 inches, are possible, which could lead to
flash and urban flooding. Heavy rainfall is possible on the Outer
Banks of North Carolina Wednesday night into Thursday with potential
for 1 to 2 inches and a local maximum of 4 inches.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected for a few more hours
across the Turks and Caicos Islands and the southeast Bahamas.
Tropical storm conditions are possible in portions of the central
Bahamas today.  Tropical storm conditions are possible over portions
of the North Carolina Outer Banks beginning late Wednesday or
Wednesday night.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions are expected to
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  Minor coastal flooding is possible in areas of onshore
winds in the Turks and Caicos Islands and the southeast Bahamas.
Near the coast, the surge will be accompanied by large waves.
 
The combination of a dangerous storm surge and the tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...
 
Cape Lookout to Duck, North Carolina...2 to 4 ft
 
The deepest water will occur along the immediate coast where the
surge will be accompanied by large and dangerous waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation, 
please see the National Weather Service Peak Storm Surge Graphic, 
available at hurricanes.gov/graphics_at5.shtml?peakSurge.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Berg
  