000
WTNT35 KNHC 200233
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  35
NWS National Hurricane Center Miami FL       AL052025
1100 PM EDT Tue Aug 19 2025
 
...ERIN BECOMING BETTER ORGANIZED AS IT MOVES NORTH-NORTHWESTWARD...
...LIFE-THREATENING RIP CURRENTS EXPECTED ALONG U.S. EAST COAST
BEACHES...
 
 
SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...27.7N 73.0W
ABOUT 585 MI...940 KM WSW OF BERMUDA
ABOUT 540 MI...865 KM SSE OF CAPE HATTERAS NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...959 MB...28.32 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Storm Surge Warning is in effect for...
* Cape Lookout to Duck, North Carolina
 
A Tropical Storm Warning is in effect for...
* Beaufort Inlet, North Carolina to Duck, North Carolina including
Pamlico and Albemarle sounds.
 
A Tropical Storm Watch is in effect for...
* North of Duck, North Carolina to Chincoteague, Virginia
* Bermuda
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within the next 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Storm Surge Warning means there is a danger of life-threatening
inundation, from rising water moving inland from the coastline,
during the next 36 hours in the indicated locations. For a depiction
of areas at risk, please see the National Weather Service Storm
Surge Watch/Warning Graphic, available at hurricanes.gov.  This is a
life-threatening situation.  Persons located within these areas
should take all necessary actions to protect life and property from
rising water and the potential for other dangerous conditions.
Promptly follow evacuation and other instructions from local
officials.
 
Interests along the U.S Mid-Atlantic coast, the southern New
England coast, and Atlantic Canada should monitor the progress of 
Erin.
 
For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Hurricane Erin was located
near latitude 27.7 North, longitude 73.0 West. Erin is moving toward
the north-northwest near 12 mph (19 km/h).  This motion with an
increase in forward speed is expected for the rest of tonight 
followed by a northward motion on Wednesday and then a 
northeastward motion on Thursday.  On the forecast track, the 
center of Erin will pass to the east of the Bahamas tonight, and 
then move over the western Atlantic between the U.S. east coast and 
Bermuda on Wednesday and Thursday.
 
Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts. Satellite imagery and reports from an Air Force Reserve 
Hurricane Hunter aircraft indicate that Erin is getting better 
organized, and slow strengthening is expected through Thursday 
night.
 
Erin is a large hurricane.  Hurricane-force winds extend outward up 
to 80 miles (130 km) from the center and tropical-storm-force winds 
extend outward up to 230 miles (370 km).
 
The minimum central pressure estimated from the Hurricane Hunter 
aircraft data is 959 mb (28.32 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
RAINFALL: Rainfall will be diminishing across the Bahamas tonight.
Heavy rainfall is possible on the Outer Banks of North Carolina
Wednesday night into Thursday, with the potential for 1 to 2 inches.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
WIND:  Tropical storm conditions are expected over portions of the 
North Carolina Outer Banks beginning late Wednesday or Wednesday 
night.  Tropical storm conditions are possible in the watch area 
north of Duck, North Carolina to Cape Charles Light beginning 
Thursday.  Tropical storm conditions are possible in Bermuda 
beginning Thursday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions are expected to
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Cape Lookout to Duck, North Carolina...2 to 4 ft
 
The deepest water will occur along the immediate coast where the
surge will be accompanied by large and dangerous waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at5.shtml?peakSurge.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Beven
  