677 
WTNT35 KNHC 201454
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  37
NWS National Hurricane Center Miami FL       AL052025
1100 AM EDT Wed Aug 20 2025
 
...LARGE ERIN STRENGTHENS WHILE HEADED NORTH...
...BEACHGOERS ARE CAUTIONED AGAINST SWIMMING AT MOST U.S. EAST
COAST BEACHES DUE TO LIFE-THREATENING SURF AND RIP CURRENTS...
 
 
SUMMARY OF 1100 AM EDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...30.1N 73.7W
ABOUT 545 MI...880 KM WSW OF BERMUDA
ABOUT 365 MI...590 KM SSE OF CAPE HATTERAS NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...941 MB...27.79 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
A Tropical Storm Warning has been issued from north of the North
Carolina/Virginia border to Chincoteague, Virginia.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Storm Surge Warning is in effect for...
* Cape Lookout to Duck, North Carolina
 
A Tropical Storm Warning is in effect for...
* Beaufort Inlet, North Carolina to Chincoteague, Virginia,
including Pamlico and Albemarle sounds.
 
A Tropical Storm Watch is in effect for...
* Bermuda
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Storm Surge Warning means there is a danger of life-threatening
inundation, from rising water moving inland from the coastline,
during the next 36 hours in the indicated locations. For a depiction
of areas at risk, please see the National Weather Service Storm
Surge Watch/Warning Graphic, available at hurricanes.gov.  This is a
life-threatening situation.  Persons located within these areas
should take all necessary actions to protect life and property from
rising water and the potential for other dangerous conditions.
Promptly follow evacuation and other instructions from local
officials.

Interests in Atlantic Canada should monitor the progress of
Erin.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM EDT (1500 UTC), the eye of Hurricane Erin was located
near latitude 30.1 North, longitude 73.7 West. Erin is moving toward
the north near 13 mph (20 km/h).  A turn toward the north-northeast 
is expected later today and tonight, followed by a faster motion 
toward the northeast and east-northeast by Thursday and Friday.  On 
the forecast track, the center of Erin will move over the western 
Atlantic between the U.S. east coast and Bermuda today through early 
Friday, and then pass south of Atlantic Canada Friday and Saturday.
 
Maximum sustained winds have increased to near 110 mph (175 km/h) 
with higher gusts.  Some additional strengthening is likely during 
the next day or so, and Erin could become a major hurricane again 
by tonight.  Weakening is likely to begin by Friday, but Erin is 
forecast to remain a hurricane into the weekend.
 
Erin is a large hurricane. Hurricane-force winds extend outward up 
to 90 miles (150 km) from the center and tropical-storm-force winds 
extend outward up to 265 miles (425 km).
 
The minimum central pressure estimated from Air Force Hurricane 
Hunter observations is 941 mb (27.79 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
WIND:  Tropical storm conditions are expected over portions of the
North Carolina Outer Banks and the Virginia coastline beginning 
late today.  Elsewhere along the mid-Atlantic and southern New 
England coast, wind gusts to tropical storm force are likely 
Thursday through early Friday.  Tropical storm conditions are 
possible on Bermuda Thursday and Friday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda, 
the east coast of the United States, and Atlantic Canada during the 
next several days. These rough ocean conditions are expected to 
cause life-threatening surf and rip currents.  Please consult 
products from your local weather forecast office for more 
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Cape Lookout to Duck, North Carolina...2 to 4 ft
 
The deepest water will occur along the immediate coast where the
surge will be accompanied by large and dangerous waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at5.shtml?peakSurge.
 
RAINFALL: The outer bands of Erin may bring 1 to 2 inches of 
rainfall to the Outer Banks of North Carolina this afternoon into 
Thursday.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM EDT.
Next complete advisory at 500 PM EDT.
 
$$
Forecaster Pasch
  