000
WTNT35 KNHC 202036
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  38
NWS National Hurricane Center Miami FL       AL052025
500 PM EDT Wed Aug 20 2025
 
...OUTER BANDS OF LARGE HURRICANE ERIN NEARING THE NORTH CAROLINA
OUTER BANKS...
...BEACHGOERS ARE CAUTIONED AGAINST SWIMMING AT MOST U.S. EAST
COAST BEACHES DUE TO LIFE-THREATENING SURF AND RIP CURRENTS...
 
 
SUMMARY OF 500 PM EDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...31.2N 73.6W
ABOUT 520 MI...840 KM W OF BERMUDA
ABOUT 295 MI...480 KM SSE OF CAPE HATTERAS NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...943 MB...27.85 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Storm Surge Warning is in effect for...
* Cape Lookout to Duck, North Carolina
 
A Tropical Storm Warning is in effect for...
* Beaufort Inlet, North Carolina to Chincoteague, Virginia,
including Pamlico and Albemarle sounds.
 
A Tropical Storm Watch is in effect for...
* Bermuda
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Storm Surge Warning means there is a danger of life-threatening
inundation, from rising water moving inland from the coastline,
during the next 36 hours in the indicated locations. For a depiction
of areas at risk, please see the National Weather Service Storm
Surge Watch/Warning Graphic, available at hurricanes.gov.  This is a
life-threatening situation.  Persons located within these areas
should take all necessary actions to protect life and property from
rising water and the potential for other dangerous conditions.
Promptly follow evacuation and other instructions from local
officials.
 
Interests in Atlantic Canada should monitor the progress of
Erin.
 
For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM EDT (2100 UTC), the center of Hurricane Erin was located
near latitude 31.2 North, longitude 73.6 West. Erin is moving toward
the north near 14 mph (22 km/h).  A turn toward the north-northeast
is expected later today and tonight, followed by a faster motion
toward the northeast and east-northeast by Thursday and Friday.  On
the forecast track, the center of Erin will move over the western
Atlantic between the U.S. east coast and Bermuda today through
early Friday, and then pass south of Atlantic Canada Friday and
Saturday.

Maximum sustained winds are near 110 mph (175 km/h) with higher
gusts.  Some strengthening is possible during the next day 
or so, and Erin could become a major hurricane again by tonight.  
Weakening is likely to begin by Friday, but Erin is forecast to 
remain a hurricane into the weekend.

Erin is a large hurricane.  Hurricane-force winds extend outward up 
to 105 miles (165 km) from the center and tropical-storm-force winds 
extend outward up to 265 miles (425 km). During the past few hours, 
NOAA buoy 41002, located west-northwest of the center, has reported 
sustained winds of 58 mph (94 km/h) and a wind gust of 67 mph   
(108 km/h).
 
The estimated minimum central pressure is 943 mb (27.85 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
WIND:  Tropical storm conditions are expected over portions of the
North Carolina Outer Banks and the Virginia coastline beginning
late today.  Elsewhere along the mid-Atlantic and southern New
England coast, wind gusts to tropical storm force are likely
Thursday through early Friday.  Tropical storm conditions are
possible on Bermuda Thursday and Friday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions are expected to
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Cape Lookout to Duck, North Carolina...2 to 4 ft
 
The deepest water will occur along the immediate coast where the
surge will be accompanied by large and dangerous waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at5.shtml?peakSurge.
 
RAINFALL: The outer bands of Erin may bring up to 1 inch of rainfall 
to the Outer Banks of North Carolina this afternoon into Thursday. 

For a complete depiction of forecast rainfall and flash flooding 
associated with Erin, please see the National Weather Service Storm 
Total Rainfall Graphic, available at 
hurricanes.gov/graphics_at5.shtml?rainqpf
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM EDT.
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Pasch
  