ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Hurricane Erin Intermediate Advisory Number 39A
NWS National Hurricane Center Miami FL       AL052025
200 AM EDT Thu Aug 21 2025
 
...TROPICAL STORM CONDITIONS OCCURRING ON THE NORTH CAROLINA OUTER 
BANKS AS ERIN TURNS TO THE NORTH-NORTHEAST...
...BEACHGOERS ARE CAUTIONED AGAINST SWIMMING AT MOST U.S. EAST
COAST BEACHES DUE TO LIFE-THREATENING SURF AND RIP CURRENTS...
 
 
SUMMARY OF 200 AM EDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...33.5N 72.7W
ABOUT 200 MI...320 KM SE OF CAPE HATTERAS NORTH CAROLINA
ABOUT 465 MI...750 KM WNW OF BERMUDA
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NNE OR 15 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...945 MB...27.91 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Storm Surge Warning is in effect for...
* Cape Lookout to Duck, North Carolina
 
A Tropical Storm Warning is in effect for...
* Beaufort Inlet, North Carolina to Chincoteague, Virginia, 
including Pamlico and Albemarle sounds
 
A Tropical Storm Watch is in effect for...
* Bermuda
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Storm Surge Warning means there is a danger of life-threatening
inundation, from rising water moving inland from the coastline,
during the next 36 hours in the indicated locations. For a depiction
of areas at risk, please see the National Weather Service Storm
Surge Watch/Warning Graphic, available at hurricanes.gov.  This is a
life-threatening situation.  Persons located within these areas
should take all necessary actions to protect life and property from
rising water and the potential for other dangerous conditions.
Promptly follow evacuation and other instructions from local
officials.
 
Interests in Atlantic Canada should monitor the progress of Erin and 
refer to local watches and warnings issued by Environment Canada.
 
For storm information specific to your area in the United States, 
including possible inland watches and warnings, please monitor 
products issued by your local National Weather Service forecast 
office. For storm information specific to your area outside of the 
United States, please monitor products issued by your national 
meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM EDT (0600 UTC), the center of Hurricane Erin was located
near latitude 33.5 North, longitude 72.7 West.  Erin is now moving 
toward the north-northeast near 17 mph (28 km/h).  A faster motion 
toward the northeast and east-northeast is expected later today and 
on Friday.  On the forecast track, the center of Erin will move over 
the western Atlantic between the U.S. east coast and Bermuda today 
through early Friday, and then pass south of Atlantic Canada Friday 
and Saturday.
 
Reports from an Air Force Reserve reconnaissance aircraft indicate 
that maximum sustained winds are near 105 mph (165 km/h) with higher
gusts.  Gradual weakening is expected over the next several days, 
and Erin is likely to become post-tropical by Saturday.
 
Erin is a large hurricane.  Hurricane-force winds extend outward up 
to 105 miles (165 km) from the center and tropical-storm-force winds 
extend outward up to 300 miles (480 km).  A sustained wind of 40 
mph (65 km/h) and a gust to 46 mph (74 km/h) were recently reported 
at the U.S. Coast Guard Station Hatteras.
 
The minimum central pressure based on dropsonde data is 945 mb 
(27.91 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
WIND:  Tropical storm conditions are occurring over portions of the
North Carolina Outer Banks and will spread northward along the 
Virginia coastline later this morning.  Elsewhere along the 
mid-Atlantic and southern New England coast, wind gusts to tropical 
storm force are likely today through early Friday.  Tropical storm 
conditions are possible on Bermuda later today through early 
Friday.  Gale conditions are possible along portions of the coast of 
Nova Scotia beginning early Friday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions are expected to
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Cape Lookout to Duck, North Carolina...2 to 4 ft
 
The deepest water will occur along the immediate coast where the
surge will be accompanied by large and dangerous waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at5.shtml?peakSurge.
 
RAINFALL: The outer bands of Erin may bring up to 1 inch of rainfall
to the Outer Banks of North Carolina today.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Erin, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Berg/Hagen
 
NNNN
  