000
WTNT35 KNHC 221438
TCPAT5
 
BULLETIN
Hurricane Erin Advisory Number  45
NWS National Hurricane Center Miami FL       AL052025
1100 AM AST Fri Aug 22 2025
 
...ERIN STILL A VERY LARGE HURRICANE...
...SWIMMING AT MANY U.S. EAST COAST BEACHES IS LIKELY TO REMAIN
DANGEROUS FOR A COUPLE MORE DAYS...
 
 
SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...38.8N 63.1W
ABOUT 460 MI...740 KM NNE OF BERMUDA
ABOUT 400 MI...645 KM S OF HALIFAX NOVA SCOTIA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 28 MPH...44 KM/H
MINIMUM CENTRAL PRESSURE...956 MB...28.23 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Erin was located
near latitude 38.8 North, longitude 63.1 West. Erin is moving toward 
the east-northeast near 28 mph (44 km/h).  This general motion with 
an increase in forward speed is expected later today, followed by a 
turn back to the northeast on Sunday.  On the forecast track, the 
center of Erin will pass south of Atlantic Canada today and tonight, 
and then race across the north Atlantic waters.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher 
gusts.  Erin is likely to become post-tropical by tonight but remain 
a powerful hurricane-force low pressure system through the weekend.
 
Erin is growing in size.  Hurricane-force winds extend outward up 
to 140 miles (220 km) from the center and tropical-storm-force 
winds extend outward up to 435 miles (705 km).
 
The estimated minimum central pressure is 956 mb (28.23 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Erin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC.
 
WIND:  Gale-force wind gusts are possible along portions of the 
coast of Nova Scotia today and the Avalon Peninsula of Newfoundland 
on Saturday.
 
SURF:  Swells generated by Erin will affect the Bahamas, Bermuda,
the east coast of the United States, and Atlantic Canada during the
next several days. These rough ocean conditions are expected to
cause life-threatening surf and rip currents.  Please consult
products from your local weather forecast office for more
information.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at5.shtml?ripCurrents
 
STORM SURGE:  Coastal flooding is expected at times of high tide
along portions of the U.S. Mid-Atlantic and New England coasts
through tonight, making some roads impassable.   See updates from
your local National Weather Service office for details.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.
 
$$
Forecaster Blake
  