

000
WTPZ33 KNHC 092351
TCPEP3

BULLETIN
Tropical Storm Julia Intermediate Advisory Number 14A
NWS National Hurricane Center Miami FL       EP182022
700 PM CDT Sun Oct 09 2022

...CENTER OF JULIA EMERGES OVER THE EASTERN PACIFIC...
...HEAVY RAINFALL WITH A RISK OF LIFE-THREATENING FLASH FLOODS AND 
MUDSLIDES TO CONTINUE ACROSS CENTRAL AMERICA AND SOUTHERN MEXICO 
THROUGH TUESDAY...


SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...12.5N 87.6W
ABOUT 90 MI...145 KM WNW OF MANAGUA NICARAGUA
ABOUT 135 MI...220 KM SE OF SAN SALVADOR EL SALVADOR
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Pacific coast of Nicaragua
* Pacific coast of Honduras
* Coast of El Salvador

A Tropical Storm Watch is in effect for...
* Pacific coast of Guatemala

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 12 to 24 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 24
hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Storm Julia was
located near latitude 12.5 North, longitude 87.6 West.  Julia is
moving toward the west near 16 mph (26 km/h).  A westward or
west-northwestward motion with some decrease in forward speed is
expected tonight and on Monday.  On the forecast track, the center
of Julia will move close to and parallel to the Pacific coasts of 
Honduras, El Salvador, and Guatemala tonight and on Monday.

Maximum sustained winds have decreased to near 45 mph (75 km/h)
with higher gusts.  Additional weakening is forecast, but Julia is
expected to remain a tropical storm near the Pacific coast of
Central America through early Monday.  Julia is expected to
dissipate by Monday night.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Julia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

WIND:  Tropical storm conditions are likely occuring along
the Pacific coast of Nicaragua and should spread to the Pacific
coasts of Honduras and El Salvador this evening and tonight.
Tropical storm conditions are possible along the Pacific coast of
Guatemala on Monday.

RAINFALL:  Julia is expected to produce the following rainfall
accumulations through Tuesday:

Nicaragua and El Salvador...5 to 10 inches, isolated 15 inches.
Honduras, Belize, northern Guatemala, and the Isthmus of Tehuantepec
in Mexico...3 to 6 inches, isolated 10 inches.
Southern Guatemala...4 to 8 inches, isolated 12 inches.
Costa Rica...an additional 2 to 4 inches, isolated 12 inch storm
total amounts.

This rainfall may cause life-threatening flash floods and mudslides
across Central America today and Monday.  Flash flooding is
anticipated across the Isthmus of Tehuantepec in Mexico early this
week.

SURF:  Swells generated by Julia continue to affect Providencia and
San Andres Islands and the Caribbean coast of Central America, but
should gradually subside through Monday night.  Swells not caused by
Julia are expected to affect the Pacific coast of Central America
during the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Brown

