

000
WTPZ33 KNHC 100241
TCPEP3

BULLETIN
Tropical Storm Julia Advisory Number  15
NWS National Hurricane Center Miami FL       EP182022
1000 PM CDT Sun Oct 09 2022

...HEAVY RAINFALL FROM JULIA SPREADING ACROSS CENTRAL AMERICA...
...RISK OF LIFE-THREATENING FLASH FLOODS AND MUDSLIDES TO CONTINUE
ACROSS CENTRAL AMERICA AND SOUTHERN MEXICO THROUGH TUESDAY...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...12.8N 88.1W
ABOUT 95 MI...155 KM SE OF SAN SALVADOR EL SALVADOR
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Nicaragua has discontinued the Tropical Storm
Warning for the Pacific coast of Nicaragua south of Puerto Sandino.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Pacific coast of Nicaragua from Puerto Sandino northward to the
Honduras border
* Pacific coast of Honduras
* Coast of El Salvador

A Tropical Storm Watch is in effect for...
* Pacific coast of Guatemala

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 12 to
24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Tropical Storm Julia was
located near latitude 12.8 North, longitude 88.1 West. Julia is
moving toward the west near 15 mph (24 km/h).  A westward or
west-northwestward motion with some decrease in forward speed is
expected overnight and on Monday.  On the forecast track, 
the center of Julia will move close to and parallel to the Pacific 
coasts of Honduras, El Salvador, and Guatemala overnight and on
Monday.

Maximum sustained winds have decreased to near 40 mph (65 km/h) 
with higher gusts. Additional weakening is forecast, but Julia is
expected to remain a tropical storm near the Pacific coast 
of Central America through early Monday.  Julia is expected to
dissipate by Monday night.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Julia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

WIND:  Tropical storm conditions are likely occuring along
the Pacific coast of northwestern Nicaragua and should spread to
the Pacific coasts of Honduras and El Salvador overnight. Tropical
storm conditions are possible along the Pacific coast of Guatemala
on Monday.

RAINFALL:  Julia is expected to produce the following rainfall
accumulations through Tuesday:

Nicaragua and El Salvador...5 to 10 inches, isolated 15 inches.
Honduras, Belize, northern Guatemala, and the Isthmus of Tehuantepec
in Mexico...3 to 6 inches, isolated 10 inches.
Southern Guatemala...4 to 8 inches, isolated 12 inches.

This rainfall may cause life-threatening flash floods and mudslides
across Central America into Monday.  Flash flooding is anticipated
across the Isthmus of Tehuantepec in Mexico early this week.

SURF:  Swells generated by Julia continue to affect Providencia and
San Andres Islands and the Caribbean coast of Central America, but
should gradually subside through Monday night.  Swells not caused by
Julia are expected to affect the Pacific coast of Central America
during the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Brown

