

728 
WTPZ33 KNHC 100541
TCPEP3

BULLETIN
Tropical Storm Julia Intermediate Advisory Number 15A
NWS National Hurricane Center Miami FL       EP182022
100 AM CDT Mon Oct 10 2022

...HEAVY RAINFALL FROM JULIA SPREADING ACROSS CENTRAL AMERICA...
...RISK OF LIFE-THREATENING FLASH FLOODS AND MUDSLIDES TO CONTINUE
ACROSS CENTRAL AMERICA AND SOUTHERN MEXICO THROUGH TUESDAY...


SUMMARY OF 100 AM CDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...13.1N 88.9W
ABOUT 45 MI...75 KM SSE OF SAN SALVADOR EL SALVADOR
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Pacific coast of Nicaragua from Puerto Sandino northward to the
Honduras border
* Pacific coast of Honduras
* Coast of El Salvador

A Tropical Storm Watch is in effect for...
* Pacific coast of Guatemala

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 12 to
24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 AM CDT (0600 UTC), the center of Tropical Storm Julia was 
located near latitude 13.1 North, longitude 88.9 West. Julia is 
moving toward the west-northwest near 15 mph (24 km/h). This general 
motion with some decrease in forward speed is expected today. On the 
forecast track, the center of Julia will move near or over the 
Pacific coasts of El Salvador and Guatemala today.

Maximum sustained winds are near 40 mph (65 km/h) with higher 
gusts. Weakening is forecast, and Julia is expected to become a 
tropical depression today and dissipate by tonight.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Julia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

WIND:  Tropical storm conditions are likely occurring along the 
Pacific coast of northwestern Nicaragua, Honduras, and El Salvador. 
Tropical storm conditions are possible along the Pacific coast of 
Guatemala today.

RAINFALL:  Julia is expected to produce the following rainfall
accumulations through Tuesday:

Nicaragua and El Salvador...5 to 10 inches, isolated 15 inches.
Honduras, Belize, northern Guatemala, and the Isthmus of Tehuantepec
in Mexico...3 to 6 inches, isolated 10 inches.
Southern Guatemala...4 to 8 inches, isolated 12 inches.

This rainfall may cause life-threatening flash floods and mudslides
across Central America through today. Flash flooding is anticipated
across the Isthmus of Tehuantepec in Mexico early this week.

SURF:  Swells generated by Julia continue to affect Providencia and
San Andres Islands and the Caribbean coast of Central America, but
should gradually subside through tonight. Swells not caused by
Julia are expected to affect the Pacific coast of Central America
during the next couple of days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.

$$
Forecaster Reinhart


