000
WTPZ31 KNHC 042344
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       EP162025
500 PM MST Sat Oct 04 2025
 
...LARGE PRISCILLA MOVING SLOWLY OFF THE COAST OF SOUTHWESTERN 
MEXICO...
 
 
SUMMARY OF 500 PM MST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...15.4N 106.6W
ABOUT 290 MI...470 KM SSW OF MANZANILLO MEXICO
ABOUT 560 MI...900 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Punta San Telmo to Punta Mita, Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests in southern Baja California Sur should monitor the 
progress of Priscilla.
 
For storm information specific to your area, please monitor products 
issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM MST (0000 UTC), the center of Tropical Storm Priscilla was 
located near latitude 15.4 North, longitude 106.6 West. Priscilla is 
moving toward the northwest near 6 mph (9 km/h). A slow, generally 
northward drift is expected through Sunday, followed by a faster 
northwestward motion beginning on Monday. On the forecast track, 
the center of Priscilla is expected to move offshore of and parallel 
to the coast of southwestern Mexico through early next week.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Strengthening is forecast during the next few days, and Priscilla is 
expected to become a hurricane by Sunday night.
 
Priscilla is a large tropical storm, with tropical-storm-force winds 
extending outward up to 140 miles (220 km) from the center.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area 
along the southwestern coast of Mexico on Sunday and Monday.
 
RAINFALL: Outer bands from Priscilla will bring heavy rain to 
portions of southwestern Mexico through Monday. Across coastal 
portions of Michoacán and far western Guerrero, rainfall amounts of 
4 to 6 inches are expected, with local amounts up to 8 inches. 
Across Colima, western Jalisco, and the rest of Guerrero along the 
coast, 2 to 4 inches of rain are expected. This rainfall will bring 
a risk of flash flooding, especially in areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the 
coast of southwestern Mexico and will reach portions of the coast of 
west-central Mexico and the southern Baja California peninsula by 
Monday. These swells are likely to cause life-threatening surf and 
rip current conditions. Please consult products from your local 
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Reinhart
  