000
WTPZ31 KNHC 050857
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Advisory Number   3
NWS National Hurricane Center Miami FL       EP162025
200 AM MST Sun Oct 05 2025
 
...PRISCILLA STRENGTHENING...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.1N 106.9W
ABOUT 305 MI...495 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 510 MI...820 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Punta San Telmo to Punta Mita, Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests in southern Baja California Sur should monitor the
progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Tropical Storm Priscilla was
located near latitude 16.1 North, longitude 106.9 West.  Priscilla 
is moving toward the northwest near 5 mph (7 km/h), and this general
motion at a slightly faster forward speed is expected over the next 
few days.  On the forecast track, the center of the system is 
expected to move offshore of and parallel to the coast of 
southwestern Mexico through early this week.
 
Maximum sustained winds have increased to near 65 mph (100 km/h)
with higher gusts.  Additional strengthening is forecast during the
next 48 hours, and Priscilla is likely to become a hurricane later
today or tonight.
 
Priscilla is a large tropical storm, with tropical-storm-force
winds extending outward up to 140 miles (220 km) from the center.
  
The estimated minimum central pressure is 991 mb (29.27 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area
along the southwestern coast of Mexico today and Monday.
 
RAINFALL: Outer bands from Priscilla will bring heavy rain to
portions of southwestern Mexico through Monday. Across coastal
portions of Michoacán and far western Guerrero, rainfall amounts of
4 to 6 inches are expected, with local amounts up to 8 inches.
Across Colima, western Jalisco, and the rest of Guerrero along the
coast, 2 to 4 inches of rain are expected. This rainfall will bring
a risk of flash flooding, especially in areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern Mexico and will reach portions of the coast of
west-central Mexico and the southern Baja California peninsula by
Monday.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 500 AM MST.
Next complete advisory at 800 AM MST.
 
$$
Forecaster Pasch
  