000
WTPZ31 KNHC 051740
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Intermediate Advisory Number 4A
NWS National Hurricane Center Miami FL       EP162025
1100 AM MST Sun Oct 05 2025
 
...PRISCILLA A LITTLE STRONGER WHILE MOVING SLOWLY...
...HEAVY RAINFALL AND GUSTY WINDS POSSIBLE FOR COASTAL SOUTHWESTERN
MEXICO...
 
 
SUMMARY OF 1100 AM MST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.5N 107.1W
ABOUT 285 MI...460 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 480 MI...770 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.21 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Punta San Telmo to Punta Mita, Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next day or
so.
 
Interests in southern Baja California Sur should monitor the
progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM MST (1800 UTC), the center of Tropical Storm Priscilla 
was located near latitude 16.5 North, longitude 107.1 West. 
Priscilla is moving toward the north-northwest near 2 mph (4 km/h) 
and this general motion at a slightly faster forward speed is 
expected over the next few days. On the forecast track, the center 
of the system is expected to move offshore of and parallel to the 
coast of southwestern Mexico through the early part of this week.
 
Maximum sustained winds have increased to near 70 mph (110 km/h) 
with higher gusts.  Additional strengthening is forecast during the 
next several days, and Priscilla is likely to become a hurricane 
later today or tonight. 
 
Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.
 
The estimated minimum central pressure is 989 mb (29.21 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area
along the southwestern coast of Mexico today into Monday.
 
RAINFALL: Outer bands from Priscilla will bring heavy rain to
portions of southwestern Mexico through Monday. Across coastal
portions of Michoacán and far western Guerrero, additional rainfall
amounts of 2 to 4 inches are expected, with local amounts up to 6
inches. Across Colima, western Jalisco, and the rest of Guerrero
along the coast, 1 to 3 inches of additional rainfall are expected.
This rainfall will bring a risk of flash flooding, especially in
areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern Mexico and will reach portions of the coast of
west-central Mexico and the southern Baja California peninsula by
Monday.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Papin
  