000
WTPZ31 KNHC 060234
TCPEP1
 
BULLETIN
Hurricane Priscilla Advisory Number   6
NWS National Hurricane Center Miami FL       EP162025
800 PM MST Sun Oct 05 2025
 
...PRISCILLA STILL CREEPING NORTH-NORTHWESTWARD...
...HEAVY RAIN AND GUSTY WIND THREAT CONTINUES FOR PARTS OF 
SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...16.7N 107.3W
ABOUT 275 MI...445 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 460 MI...740 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...986 MB...29.12 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Punta San Telmo to Punta Mita, Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case during the next day or
so.
 
Interests in southern Baja California Sur should monitor the
progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Hurricane Priscilla was
located near latitude 16.7 North, longitude 107.3 West. Priscilla is
moving toward the north-northwest near 3 mph (6 km/h).  This
general motion with a bend to the northwest at a slightly faster 
forward speed is expected over the next few days.  On the forecast 
track, the center of the system is expected to move offshore of and 
parallel to the coast of southwestern Mexico and Baja California 
Sur through the early-to-middle part of this week
 
Maximum sustained winds remain near 75 mph (120 km/h) with higher
gusts.  Strengthening is expected during the next few days, and
Priscilla is forecast to become a category 2 hurricane later this
week before weakening likely commences on Wednesday.
 
Hurricane-force winds extend outward up to 40 miles (65 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).
 
The estimated minimum central pressure is 986 mb (29.12 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area
along the southwestern coast of Mexico today into Monday.
 
RAINFALL: Outer bands from Priscilla will bring heavy rain to
portions of southwestern Mexico through Monday. Across coastal
portions of Michoacán and far western Guerrero, additional rainfall
amounts of 2 to 4 inches are expected, with local amounts up to 6
inches. Across Colima, western Jalisco, and the rest of Guerrero
along the coast, 1 to 3 inches of additional rainfall are expected.
This rainfall will bring a risk of flash flooding, especially in
areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern Mexico and will reach portions of the coast of
west-central Mexico and the southern Baja California peninsula by
Monday.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1100 PM MST.
Next complete advisory at 200 AM MST.
 
$$
Forecaster Blake
  