000
WTPZ31 KNHC 061146
TCPEP1
 
BULLETIN
Hurricane Priscilla Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP162025
500 AM MST Mon Oct 06 2025
 
...HEAVY RAINS AND GUSTY WINDS LIKELY OVER PARTS OF SOUTHWESTERN
MEXICO TODAY...
 
 
SUMMARY OF 500 AM MST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...17.3N 107.4W
ABOUT 240 MI...390 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 420 MI...675 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Punta San Telmo to Punta Mita, Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case during the next 12 
hours.
 
Interests in southern Baja California Sur should monitor the
progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM MST (1200 UTC), the center of Hurricane Priscilla was 
located near latitude 17.3 North, longitude 107.4 West. Priscilla is 
moving toward the north-northwest near 5 mph (7 km/h). This general 
motion with a bend to the northwest at a slightly faster forward 
speed is expected over the next few days. On the forecast track, the 
center of the system is expected to move offshore of and parallel to 
the coast of southwestern Mexico and Baja California Sur through the 
early-to-middle part of this week.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts. Additional strengthening is forecast, and Priscilla is 
expected to become a category 2 hurricane, and could approach major 
hurricane status within the next couple of days before weakening 
likely commences by midweek.
 
Hurricane-force winds extend outward up to 40 miles (65 km) from
the center and tropical-storm-force winds extend outward up to 195
miles (315 km).
 
The estimated minimum central pressure is 975 mb (28.80 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area
along the southwestern coast of Mexico today.
 
RAINFALL: Outer bands from Priscilla will continue to bring heavy
rain to portions of southwestern Mexico today. Across coastal
portions of Michoacán and far western Guerrero, additional rainfall
amounts of 2 to 4 inches are expected, with local amounts up to 6
inches. Across Colima, western Jalisco, and the rest of Guerrero
along the coast, 1 to 3 inches of additional rainfall are expected.
This rainfall will bring a risk of flash flooding, especially in
areas of higher terrain.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the 
coast of southwestern and west-central Mexico, and will reach 
portions of the coast of the southern Baja California peninsula 
today.  These swells are likely to cause life-threatening surf and 
rip current conditions.  Please consult products from your local 
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM MST.
 
$$
Forecaster Hagen
  