000
WTPZ31 KNHC 061745
TCPEP1
 
BULLETIN
Hurricane Priscilla Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       EP162025
1100 AM MST Mon Oct 06 2025
 
...HEAVY RAINS AND GUSTY WINDS LIKELY TODAY OVER PARTS OF COASTAL
SOUTHWESTERN AND WEST-CENTRAL MEXICO...
...TROPICAL STORM CONDITIONS POSSIBLE ACROSS PORTIONS OF BAJA 
CALIFORNIA SUR TUESDAY NIGHT AND WEDNESDAY...
 
 
SUMMARY OF 1100 AM MST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.0N 107.6W
ABOUT 205 MI...335 KM SW OF CABO CORRIENTES MEXICO
ABOUT 370 MI...595 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Punta San Telmo to Punta Mita, Mexico
* Baja California Sur from Cabo San Lucas to Santa Fe
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
Interests elsewhere in southern Baja California Sur should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM MST (1800 UTC), the center of Hurricane Priscilla was
located near latitude 18.0 North, longitude 107.6 West. Priscilla is
moving toward the north-northwest near 6 mph (9 km/h). This general
motion with a bend to the northwest at a slightly faster forward
speed is expected over the next few days. On the forecast track, the
center of the system is expected to move offshore of and parallel to
the coast of west-central Mexico and Baja California Sur through the
early-to-middle part of this week.
 
Maximum sustained winds remain near 85 mph (140 km/h) with higher
gusts. Strengthening is forecast, and Priscilla is expected to 
become a category 2 hurricane, and could approach major hurricane 
status within the next couple of days before weakening likely 
commences by midweek.
 
Hurricane-force winds extend outward up to 50 miles (85 km) from
the center and tropical-storm-force winds extend outward up to 205
miles (335 km).
 
The estimated minimum central pressure is 973 mb (28.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area
along the southwestern coast of Mexico today, and are possible in
Baja California Sur Tuesday night into Wednesday.
 
RAINFALL: Outer bands from Priscilla will continue to bring heavy
rain to portions of southwestern Mexico today. Across coastal
portions of Michoacán and Colima, additional rainfall amounts of 1
to 2 inches are expected.  From Tuesday into Wednesday, 2-4 inches
(with local amounts up to 6 inches) are expected in southern
portions of Baja California Sur as outer bands of Priscilla reach
that area. This rainfall will bring a risk of flash flooding,
especially in areas of higher terrain.  Moisture from Priscilla
should bring heavy rainfall potential over the Southwestern U.S.
late this week into this weekend.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern and west-central Mexico, and will reach
portions of the coast of the southern Baja California peninsula
today.  These swells are likely to cause life-threatening surf and
rip current conditions.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Hagen
  