000
WTPZ31 KNHC 062346
TCPEP1
 
BULLETIN
Hurricane Priscilla Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP162025
500 PM MST Mon Oct 06 2025
 
...HEAVY RAINS AND GUSTY WINDS POSSIBLE OVER PORTIONS OF BAJA
CALIFORNIA SUR ON TUESDAY AND WEDNESDAY...
 
 
SUMMARY OF 500 PM MST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...18.8N 108.0W
ABOUT 185 MI...300 KM SW OF CABO CORRIENTES MEXICO
ABOUT 310 MI...495 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...972 MB...28.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None 
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Manzanillo to Punta Mita, Mexico
* Baja California Sur from Cabo San Lucas to Santa Fe
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM MST (0000 UTC), the center of Hurricane Priscilla was
located near latitude 18.8 North, longitude 108.0 West. Priscilla is
moving toward the north-northwest near 8 mph (13 km/h). A turn 
toward the northwest at a slightly faster forward speed is expected 
over the next few days. On the forecast track, the center of the 
system is expected to move offshore of and parallel to the coast of 
west-central Mexico and Baja California Sur through the middle part 
of this week.

Maximum sustained winds remain near 85 mph (140 km/h) with higher 
gusts. Strengthening is expected over the next day or two, and 
Priscilla is forecast to become a category 2 hurricane before 
weakening begins by midweek.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from
the center and tropical-storm-force winds extend outward up to 205
miles (335 km).
 
The estimated minimum central pressure is 972 mb (28.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible within the watch area
along the west-central coast of Mexico through tonight, and are
possible in Baja California Sur Tuesday night into Wednesday.
 
RAINFALL: Outer bands from Priscilla will continue to bring heavy
rain to portions of west-central Mexico today. Across coastal
portions of Michoacán and Colima, additional rainfall amounts of 1
to 2 inches are expected.  From Tuesday into Wednesday, 1 to 2
inches with local storm total amounts to 4 inches are expected in
southern portions of Baja California Sur due to the outer bands of
Priscilla. This rainfall could bring a risk of flash flooding,
especially in areas of higher terrain.  Moisture from Priscilla
should bring heavy rainfall potential over the Southwest U.S. late
this week into this weekend.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern and west-central Mexico, as well as portions
of the coast of the southern Baja California peninsula.  These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Papin
  