000
WTPZ31 KNHC 070545
TCPEP1
 
BULLETIN
Hurricane Priscilla Intermediate Advisory Number 10A
NWS National Hurricane Center Miami FL       EP162025
1100 PM MST Mon Oct 06 2025
 
...HEAVY RAINS AND GUSTY WINDS POSSIBLE OVER PORTIONS OF BAJA
CALIFORNIA SUR ON TUESDAY AND WEDNESDAY AS PRISCILLA MOVES NEARBY...
 
 
SUMMARY OF 1100 PM MST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...19.1N 109.0W
ABOUT 235 MI...375 KM WSW OF CABO CORRIENTES MEXICO
ABOUT 265 MI...425 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...972 MB...28.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM MST (0600 UTC), the center of Hurricane Priscilla was 
located near latitude 19.1 North, longitude 109.0 West. Priscilla is 
moving toward the northwest near 9 mph (15 km/h). A continued 
northwestward motion at a slightly faster forward speed is expected 
over the next few days. On the forecast track, the center of 
Priscilla is expected to move parallel to, but offshore of, the 
coast of west-central Mexico and Baja California Sur during the 
next couple of days.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts. Strengthening is expected over the next day or so, and 
Priscilla is forecast to become a category 2 hurricane on Tuesday 
before weakening begins by midweek.
 
Hurricane-force winds extend outward up to 50 miles (85 km) from
the center and tropical-storm-force winds extend outward up to 185
miles (295 km).
 
The estimated minimum central pressure is 972 mb (28.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible on the Pacific coast of 
Baja California Sur within the watch area on Tuesday and Wednesday.
 
RAINFALL: From Tuesday to Wednesday, 1 to 2 inches of rain are 
expected in southern Baja California Sur, with local totals up to 4 
inches as the outer bands of Priscilla reach the area. This rainfall 
could bring a risk of flash flooding, especially in areas of higher 
terrain. Moisture from Priscilla could bring heavy rainfall 
potential over the Southwest U.S. late this week into this weekend.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern and west-central Mexico, as well as portions
of the coast of the southern Baja California peninsula. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Reinhart
  