000
WTPZ31 KNHC 070854
TCPEP1
 
BULLETIN
Hurricane Priscilla Advisory Number  11
NWS National Hurricane Center Miami FL       EP162025
200 AM MST Tue Oct 07 2025
 
...PRISCILLA IS STRENGTHENING...
...OUTER BANDS COULD BRING HEAVY RAINS AND GUSTY WINDS TO PORTIONS
OF BAJA CALIFORNIA SUR LATER TODAY AND WEDNESDAY...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...19.4N 109.5W
ABOUT 255 MI...410 KM WSW OF CABO CORRIENTES MEXICO
ABOUT 245 MI...390 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...967 MB...28.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Hurricane Priscilla was 
located near latitude 19.4 North, longitude 109.5 West. Priscilla is 
moving toward the northwest near 10 mph (17 km/h), and a continued 
northwestward motion is expected over the next few days. On the 
forecast track, the center of Priscilla is expected to move parallel 
to, but offshore of, the coast of west-central Mexico and Baja 
California Sur during the next couple of days.
 
Maximum sustained winds have increased to near 100 mph (155 km/h) 
with higher gusts. Additional strengthening is expected, and 
Priscilla could be at or near major hurricane strength later today. 
Weakening is forecast to begin on Wednesday and continue through the 
rest of the week.
 
Hurricane-force winds extend outward up to 50 miles (85 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 967 mb (28.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area later today and
Wednesday.
 
RAINFALL: From today into Wednesday, 1 to 2 inches of rain are
expected in southern Baja California Sur, with local totals up to 4
inches as the outer bands of Priscilla reach the area. This rainfall
could bring a risk of flash flooding, especially in areas of higher
terrain.  Moisture from Priscilla should bring heavy rainfall
potential over the Southwest U.S. late this week into this weekend.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern and west-central Mexico, as well as portions
of the coast of the southern Baja California peninsula. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 500 AM MST.
Next complete advisory at 800 AM MST.
 
$$
Forecaster Reinhart
  