000
WTPZ31 KNHC 071739
TCPEP1
 
BULLETIN
Hurricane Priscilla Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       EP162025
1100 AM MST Tue Oct 07 2025
 
...LARGE EYE OF PRISCILLA MOVING WEST-NORTHWESTWARD AS OUTER BANDS 
SPREAD OVER THE SOUTHERN BAJA CALIFORNIA PENINSULA...

 
SUMMARY OF 1100 AM MST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...19.8N 110.6W
ABOUT 320 MI...515 KM W OF CABO CORRIENTES MEXICO
ABOUT 210 MI...340 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...959 MB...28.32 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM MST (1800 UTC), the center of Hurricane Priscilla was 
located near latitude 19.8 North, longitude 110.6 West. Priscilla is 
moving toward the west-northwest near 10 mph (17 km/h). A 
northwestward motion is expected over the next couple of days, 
followed by a turn toward the north Thursday night or Friday. On the 
forecast track, the center of Priscilla is expected to move parallel 
to, but offshore of, the coast of west-central Mexico and Baja 
California Sur during the next couple of days.
 
Maximum sustained winds remain near 110 mph (175 km/h) with higher
gusts. Additional strengthening is expected, and Priscilla is 
forecast to become a major hurricane later today. Weakening is 
forecast to begin on Wednesday and continue through the rest of the 
week.
 
Hurricane-force winds extend outward up to 50 miles (85 km) from
the center and tropical-storm-force winds extend outward up to 185
miles (295 km). Socorro island, located about 70 miles (115 km) 
south-southwest of Priscilla's eye, recently recorded a sustained 
wind of 55 mph (89 km/h) with a gust of 76 mph (122 km/h).
 
The estimated minimum central pressure is 959 mb (28.32 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area later today and
Wednesday.
 
RAINFALL: From today into Wednesday, 1 to 2 inches of rain are
expected in southern Baja California Sur, with local storm totals up
to 4 inches as the outer bands of Priscilla reach the area. This
rainfall could bring a risk of flash flooding, especially in areas
of higher terrain.  Moisture from Priscilla should bring 1 to 2
inches of rain, with local amounts to 4 inches, to portions of
west-central Mexico, which could lead to flash flooding within the
area’s terrain.  From late this week into this weekend, moisture
from Priscilla leads to heavy rainfall and a flash flood risk over
portions of the U.S. Desert Southwest.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Swells generated by Priscilla are affecting portions of the
coast of southwestern and west-central Mexico, as well as portions
of the coast of the southern Baja California peninsula. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Hagen
  