000
WTPZ31 KNHC 072339
TCPEP1
 
BULLETIN
Hurricane Priscilla Intermediate Advisory Number 13A
NWS National Hurricane Center Miami FL       EP162025
500 PM MST Tue Oct 07 2025

...TROPICAL STORM CONDITIONS POSSIBLE FOR PARTS OF BAJA CALIFORNIA 
SUR AS LIFE-THREATENING SURF AFFECTS THIS AREA AND MUCH OF 
WEST-CENTRAL MEXICO...
 
 
SUMMARY OF 500 PM MST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...20.3N 111.2W
ABOUT 355 MI...575 KM W OF CABO CORRIENTES MEXICO
ABOUT 200 MI...320 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...958 MB...28.29 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area in this case within 24 hours.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM MST (0000 UTC), the eye of Hurricane Priscilla was 
located near latitude 20.3 North, longitude 111.2 West. Priscilla is 
moving toward the northwest near 9 mph (15 km/h) and this motion is 
expected to continue for the next couple of days, followed by a turn 
toward the north Thursday night. On the forecast track, the center 
of Priscilla is expected to move parallel to, but offshore of, the 
coast of Baja California Sur through Thursday.
 
Maximum sustained winds remain near 110 mph (175 km/h) with higher 
gusts.  Little change in strength is expected through tonight. 
Weakening is forecast to begin on Wednesday and continue through the 
rest of the week.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the 
center and tropical-storm-force winds extend outward up to 185 miles 
(295 km). A weather station on Socorro island, located about 105 
miles (170 km) south of Priscilla's eye, recently reported a 
sustained wind of 52 mph (84 km/h) with a gust of 73 mph (117 km/h). 
An elevated station near Cabo San Lucas in Baja California Sur also 
recently reported a wind gust of 57 mph (92 km/h). 
 
The estimated minimum central pressure is 958 mb (28.29 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area later today through
Wednesday.
 
RAINFALL: From today into Wednesday, 1 to 2 inches of rain are 
expected in southern Baja California Sur, with local storm totals up 
to 4 inches as the outer bands of Priscilla reach the area. This 
rainfall could bring a risk of flash flooding, especially in areas 
of higher terrain.  Moisture from Priscilla should bring 1 to 2 
inches of rain, with local amounts to 4 inches, to portions of 
west-central Mexico, which could lead to flash flooding within the 
area’s terrain.  From late this week into this weekend, moisture 
from Priscilla may lead to heavy rainfall and a flash flood risk 
over portions of the U.S. Desert Southwest.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting portions of
the coast of southwestern and west-central Mexico, as well as
portions of the coast of the southern Baja California peninsula.
These swells are likely to cause life-threatening surf and rip
current conditions, in addition to some coastal flooding. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Papin
  