007 
WTPZ31 KNHC 080235
TCPEP1
 
BULLETIN
Hurricane Priscilla Advisory Number  14
NWS National Hurricane Center Miami FL       EP162025
800 PM MST Tue Oct 07 2025
 
...HIGH SURF EXPECTED AND TROPICAL STORM CONDITIONS POSSIBLE FOR
BAJA CALIFORNIA SUR OVER THE NEXT DAY AS PRISCILLA PARALLELS THE
PACIFIC COAST...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...20.6N 111.5W
ABOUT 375 MI...605 KM W OF CABO CORRIENTES MEXICO
ABOUT 190 MI...305 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 24 hours.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Hurricane Priscilla was 
located near latitude 20.6 North, longitude 111.5 West. Priscilla is 
moving toward the northwest near 9 mph (15 km/h) and this motion is 
expected to continue for the next couple of days, followed by a turn 
toward the north Thursday night. On the forecast track, the center 
of Priscilla is expected to move parallel to, but offshore of, the 
coast of Baja California Sur through Thursday.
 
Maximum sustained winds have decreased to near 105 mph (165 km/h) 
with higher gusts. Additional weakening is expected on Wednesday, 
continuing through the rest of the week.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the 
center and tropical-storm-force winds extend outward up to 195 miles 
(315 km). A weather station on Socorro island, located about 130 
miles (205 km) south-southeast of Priscilla's eye, recently reported 
a wind gust of 54 mph (87 km/h). 
 
The estimated minimum central pressure is 962 mb (28.41 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area through Wednesday.
 
RAINFALL: 1 to 2 inches of rain are expected in southern Baja
California Sur into Wednesday, with local storm totals up to 4
inches as the outer bands of Priscilla reach the area . This
rainfall could bring a risk of flash flooding, especially in areas
of higher terrain.  Moisture from Priscilla should bring 1 to 2
inches of rain, with local amounts to 4 inches, to portions of
west-central Mexico, which could lead to flash flooding within the
area’s terrain.  From late this week into this weekend, moisture
from Priscilla leads to heavy rainfall and a flash flood risk over
portions of the U.S. Desert Southwest.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting portions of
the coast of southwestern and west-central Mexico, as well as
portions of the coast of the southern Baja California peninsula.
These swells are likely to cause life-threatening surf and rip
current conditions, in addition to some coastal flooding. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1100 PM MST.
Next complete advisory at 200 AM MST.
 
$$
Forecaster Papin
  