142 
WTPZ31 KNHC 081736
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Intermediate Advisory Number 16A
NWS National Hurricane Center Miami FL       EP162025
1100 AM MST Wed Oct 08 2025
 
...PRISCILLA BRINGING HIGH SURF AND GUSTY WINDS TO THE PACIFIC
COAST OF BAJA CALIFORNIA SUR...
...MOISTURE FROM PRISCILLA WILL INCREASE THE RISK OF FLOODING 
ACROSS THE U.S. DESERT SOUTHWEST LATE THIS WEEK THROUGH THE 
WEEKEND...
 
 
SUMMARY OF 1100 AM MST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.7N 112.7W
ABOUT 195 MI...315 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 12 hours.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM MST (1800 UTC), the center of Tropical Storm Priscilla 
was located near latitude 21.7 North, longitude 112.7 West. 
Priscilla is moving toward the northwest near 7 mph (11 km/h), and 
this general motion is expected to continue through Thursday, 
followed by a turn toward the north Thursday night. On the forecast 
track, the center of Priscilla is expected to move parallel to, but 
offshore of, the coast of Baja California Sur through Thursday.
 
Maximum sustained winds have decreased to near 70 mph (110 km/h) 
with higher gusts. Continued weakening is forecast during the next
48 hours.
 
Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center.
 
The estimated minimum central pressure is 985 mb (29.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area today.
 
RAINFALL: As Priscilla moves off the west coast of Baja California,
up to an inch of rain is expected across the Baja California
peninsula.  Farther north across the southwestern United States,
heavy rain from Priscilla’s moisture is expected to lead to 2 to 4
inches, with local storm total amounts to 6 inches, across portions
of central and northern Arizona and southern Utah from Thursday into
Saturday morning.  Scattered occurrences of flash flooding are
anticipated from central Arizona across southern Utah and the Four
Corners into southwest Colorado and far northwest New Mexico.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting portions of
the coast of southwestern and west-central Mexico, as well as
portions of the coast of the southern Baja California peninsula.
These swells are likely to cause life-threatening surf and rip
current conditions, in addition to some coastal flooding.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Hagen
  