000
WTPZ31 KNHC 082330
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Intermediate Advisory Number 17A
NWS National Hurricane Center Miami FL       EP162025
500 PM MST Wed Oct 08 2025
 
...PRISCILLA MOVING NORTHWESTWARD AND BRINGING HIGH SURF AND GUSTY 
WINDS TO THE PACIFIC COAST OF BAJA CALIFORNIA SUR...
...MOISTURE FROM PRISCILLA WILL INCREASE THE RISK OF FLOODING
ACROSS THE U.S. DESERT SOUTHWEST LATE THIS WEEK THROUGH THE
WEEKEND...
 
 
SUMMARY OF 500 PM MST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 113.3W
ABOUT 220 MI...355 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...986 MB...29.12 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 12 hours.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM MST (0000 UTC), the center of Tropical Storm Priscilla was
located near latitude 22.3 North, longitude 113.3 West. Priscilla is
moving toward the northwest near 8 mph (13 km/h) and this general 
motion is expected to continue through Thursday. A turn toward the 
north is expected Thursday night. On the forecast track, the center 
of Priscilla is expected to move parallel to, but offshore of, the 
coast of Baja California Sur through Thursday.
 
Maximum sustained winds are now near 65 mph (100 km/h) with higher
gusts.  Weakening is forecast, and Priscilla is expected to become 
a remnant low by Friday.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.
 
The estimated minimum central pressure is 986 mb (29.12 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area through this evening.
 
RAINFALL: As Priscilla moves off the west coast of Baja California,
up to an inch of rain is expected across the Baja California
peninsula.  Farther north across the southwestern United States,
heavy rain from Priscilla’s moisture is expected to lead to 2 to 4
inches, with local storm total amounts to 6 inches, across portions
of central and northern Arizona, southern Utah, and southwest
Colorado from Thursday into Saturday afternoon.  Scattered
occurrences of flash flooding are anticipated from central Arizona
across southern Utah across the Four Corners into southwest Colorado
and far northwest New Mexico.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting the Pacific
coast of Baja California Sur as well as portions of coastal
southwestern and west-central Mexico. These swells are likely to
cause life-threatening surf and rip current conditions, in addition
to some coastal flooding.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Beven
  