968 
WTPZ31 KNHC 090232
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Advisory Number  18
NWS National Hurricane Center Miami FL       EP162025
800 PM MST Wed Oct 08 2025
 
...PRISCILLA GRADUALLY WEAKENING AS IT MOVES NORTHWESTWARD TO THE
WEST OF BAJA CALIFORNIA SUR...
...MOISTURE FROM PRISCILLA WILL INCREASE THE RISK OF FLOODING
ACROSS THE U.S. DESERT SOUTHWEST LATE THIS WEEK THROUGH THE
WEEKEND...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...22.6N 113.6W
ABOUT 235 MI...380 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.21 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Cabo San Lucas to Cabo San Lazaro,
Mexico
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 12 hours.
 
Interests elsewhere in the Baja California peninsula should monitor
the progress of Priscilla.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Tropical Storm Priscilla was
located near latitude 22.6 North, longitude 113.6 West. Priscilla is
moving toward the northwest near 9 mph (15 km/h) and this general
motion is expected to continue through Thursday. A turn toward the
north is expected Thursday night. On the forecast track, the center
of Priscilla is expected to move parallel to, but offshore of, the
coast of Baja California Sur through Thursday.
 
Maximum sustained winds are now near 60 mph (95 km/h) with higher
gusts. Weakening is forecast, and Priscilla is expected to become
a remnant low by Friday.
 
Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center. Puerto Cortes, Mexico, recently reported a wind
gust of 40 mph (65 km/h).
 
The estimated minimum central pressure is 989 mb (29.21 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Tropical storm conditions are possible along the Pacific coast
of Baja California Sur within the watch area for the next several
hours.
 
RAINFALL: As Priscilla moves off the west coast of Baja California,
up to an inch of rain is expected across the Baja California
peninsula.  Farther north across the southwestern United States,
heavy rain from Priscilla’s moisture is expected to lead to 2 to 4
inches, with local storm total amounts to 6 inches, across portions
of central and northern Arizona, southern Utah, and southwest
Colorado from Thursday into Saturday afternoon.  Scattered
occurrences of flash flooding are anticipated from central Arizona
across southern Utah across the Four Corners into southwest Colorado
and far northwest New Mexico.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting the Pacific
coast of Baja California Sur as well as portions of coastal
southwestern and west-central Mexico. These swells are likely to
cause life-threatening surf and rip current conditions, in addition
to some coastal flooding.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1100 PM MST.
Next complete advisory at 200 AM MST.
 
$$
Forecaster Beven
  