000
WTPZ31 KNHC 091438
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Advisory Number  20
NWS National Hurricane Center Miami FL       EP162025
800 AM MST Thu Oct 09 2025
 
...PRISCILLA WEAKENS A LITTLE MORE...
...SIGNIFICANT RISK OF FLASH FLOODING ACROSS THE SOUTHWEST UNITED 
STATES THROUGH THE WEEKEND...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...23.8N 114.7W
ABOUT 165 MI...265 KM WSW OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has discontinued all watches.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect.

For storm information specific to your area, please monitor 
products issued by your local national meteorological service.
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Tropical Storm Priscilla was
located near latitude 23.8 North, longitude 114.7 West. Priscilla is
moving toward the north-northwest near 8 mph (13 km/h). A turn 
toward the north is anticipated later today and tonight. On the 
forecast track, the center of Priscilla is expected to move
parallel to, but offshore of, the coast of Baja California Sur.
 
Maximum sustained winds have decreased to near 45 mph (75 km/h) with 
higher gusts. Weakening is forecast, and Priscilla is expected to 
become a post-tropical cyclone by Friday.
 
Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The estimated minimum central pressure is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Priscilla can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
WIND: Gusty winds will be possible along the west coast of Baja
California Sur today.
 
RAINFALL:  As Priscilla moves off the west coast of Baja California,
up to an inch of rain is expected across the Baja California
peninsula.  For the southwestern United States, 2 to 4 inches of
rain, with local storm total maxima to 6 inches, are expected across
portions of central and northern Arizona, southern Utah, and
southwest Colorado through Saturday.  Flash flooding is likely in 
portions of central Arizona, with scattered areas of flash flooding 
expected across the remainder of Arizona, southern Utah, southwest 
Colorado, and far northwest New Mexico.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting the Pacific
coast of Baja California Sur as well as portions of coastal
southwestern and west-central Mexico.  These swells are likely to
cause life-threatening surf and rip current conditions, in addition
to some coastal flooding. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Kelly
  