000
WTPZ31 KNHC 100235
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Advisory Number  22
NWS National Hurricane Center Miami FL       EP162025
800 PM PDT Thu Oct 09 2025
 
...PRISCILLA STRENGTHENS SLIGHTLY...
...SIGNIFICANT RISK OF FLASH FLOODING ACROSS THE SOUTHWEST UNITED
STATES THROUGH THE WEEKEND...
 
 
SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...25.1N 115.0W
ABOUT 170 MI...275 KM W OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Priscilla was 
located near latitude 25.1 North, longitude 115.0 West.  Priscilla 
is moving toward the north-northwest near 8 mph (13 km/h).  A turn 
toward the north with a decrease in forward speed is expected later 
tonight through Friday.  A turn toward the northeast is expected 
Friday night.  On the forecast track, the center of Priscilla is 
expected to remain offshore of the coast of Baja California Sur, and 
dissipate by Saturday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Weakening is forecast, with Priscilla expected to become a 
post-tropical remnant low on Friday and dissipate by Saturday.
 
Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.
 
The estimated minimum central pressure is 995 mb (29.39 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL:  As Priscilla moves offshore of the west coast of Baja
California, up to an inch of rain is expected across the Baja
California peninsula.  For the southwestern United States, 2 to 4
inches of rain, with local storm total maxima to 6 inches, are
expected across portions of central and northern Arizona, southern
Utah, and southwest Colorado through Saturday.  Flash flooding is
likely in  portions of central Arizona, with scattered areas of
flash flooding expected across the remainder of Arizona, southern
Utah, southwest Colorado, and far northwest New Mexico.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting the Pacific
coast of Baja California Sur.  These swells are likely to cause
life-threatening surf and rip current conditions, in addition to
some coastal flooding. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.
 
$$
Forecaster Jelsema (CPHC)
  