000
WTPZ31 KNHC 101442
TCPEP1
 
BULLETIN
Tropical Storm Priscilla Advisory Number  24
NWS National Hurricane Center Miami FL       EP162025
800 AM PDT Fri Oct 10 2025
 
...PRISCILLA MOVING SLOWLY NORTH OFFSHORE BAJA CALIFORNIA SUR..
...SIGNIFICANT RISK OF FLASH FLOODING ACROSS THE SOUTHWEST UNITED
STATES THROUGH THE WEEKEND...
 
 
SUMMARY OF 800 AM PDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...25.9N 115.2W
ABOUT 195 MI...315 KM WNW OF CABO SAN LAZARO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM PDT (1500 UTC), the center of Tropical Storm Priscilla was
located near latitude 25.9 North, longitude 115.2 West. Priscilla is
moving toward the north near 5 mph (7 km/h) This general motion
will continue today, with a turn toward the north-northeast expected
tonight.  On the forecast track, the center of Priscilla is expected
to remain offshore of the coast of Baja California Sur, and
dissipate by Saturday.
 
Maximum sustained winds have decreased to near 45 mph (75 km/h) with 
higher gusts. Additional weakening is forecast, with Priscilla 
expected to become a post-tropical remnant low later today and 
dissipate by Saturday.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL:  As Priscilla moves off the west coast of Baja California,
up to an inch of rain is expected across the Baja California
peninsula.  For the southwestern United States, 2 to 4 inches of
rain, with local storm total maxima to 6 inches, are expected across
portions of central and northern Arizona, southern Utah, and
southwest Colorado through Saturday.  Flash flooding is likely in
portions of central Arizona and southwest Utah, with scattered areas
of flash flooding expected across the remainder of Arizona, southern
Utah, southwest Colorado, and far northwest New Mexico.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Priscilla, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf
 
SURF: Large swells generated by Priscilla are affecting the Pacific
coast of Baja California Sur.  These swells are likely to cause
life-threatening surf and rip current conditions, in addition to
some coastal flooding.  Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM PDT.
 
$$
Forecaster Kelly
  