960 
WTPZ35 KNHC 162051
TCPEP5
 
BULLETIN
Potential Tropical Cyclone Five-E Advisory Number   1
NWS National Hurricane Center Miami FL       EP052025
300 PM CST Mon Jun 16 2025
 
...DISTURBANCE EXPECTED STRENGTHEN AND BRING SIGNIFICANT WINDS AND 
RAIN TO PORTIONS OF SOUTHERN MEXICO...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...10.6N 91.7W
ABOUT 610 MI...980 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...1009 MB...29.80 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the disturbance was centered near latitude
10.6 North, longitude 91.7 West. The system is moving toward the
west-northwest near 8 mph (13 km/h).  A turn toward the northwest 
is expected later today or tonight, and this motion is forecast to 
continue for the next few days.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher gusts. 
Rapid strengthening is forecast during the next few days. The system 
is expected to become a tropical storm on Tuesday and a hurricane on 
Wednesday.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 7 days...high...90 percent.
 
The estimated minimum central pressure is 1009 mb (29.80 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Five-E can be found in
the Tropical Cyclone Discussion under AWIPS header
MIATCDEP5 and WMO header WTPZ45 KNHC.
 
RAINFALL: Potential Tropical Cyclone Five-E may produce rainfall
totals of 2 to 4 inches, with maximum totals of 6 inches, across
coastal sections of El Salvador, Guatemala and the Mexican states of
Chiapas, Tabasco and Veracruz.  Rainfall totals of 4 to 8 inches,
with maximum totals of 12 inches, are possible across the Mexican
states of Oaxaca and Guerrero. This rainfall may produce life
threatening flooding and mudslides, especially in areas of steep
terrain.
 
For a complete depiction of forecast rainfall associated with
Potential Tropical Cyclone Five-E, please see the National Weather
Service Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions could occur along portions of southern
Mexico by late Wednesday or Thursday.

SURF:  Swells generated by the system are expected to begin 
affecting the coast of southern Mexico in a day or so.  These 
swells are likely to cause life-threatening surf and rip current 
conditions.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.
 
$$
Forecaster Bucci/Mora/Cano
  