000
WTPZ35 KNHC 170241
TCPEP5
 
BULLETIN
Tropical Depression Five-E Advisory Number   2
NWS National Hurricane Center Miami FL       EP052025
900 PM CST Mon Jun 16 2025
 
...HURRICANE WATCH ISSUED FOR PORTIONS OF SOUTHERN MEXICO...
 
 
SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...11.2N 92.6W
ABOUT 535 MI...860 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has issued a Hurricane Watch from Bahia De
Huatulco to Punta Maldonado and a Tropical Storm Watch east of
Bahia De Huatulco to Salina Cruz.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Bahia De Huatulco to Punta Maldonado
 
A Tropical Storm Watch is in effect for...
* Salina Cruz to Bahia De Huatulco
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in southern Mexico should monitor the progress 
of this system.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Tropical Depression Five-E
was located near latitude 11.2 North, longitude 92.6 West. The
depression is moving toward the west-northwest near 12 mph. A
slower west-northwest to northwest motion is expected during the
next few days. On the forecast track, the system is expected to
approach the coast of southern Mexico by late Wednesday.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Strengthening is forecast, and the system is expected to become a
tropical storm by early Tuesday and a hurricane on Wednesday.
 
The estimated minimum central pressure is 1007 mb (29.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Five-E can be found in
the Tropical Cyclone Discussion under AWIPS header
MIATCDEP5 and WMO header WTPZ45 KNHC.
 
RAINFALL: Tropical Depression Five-E may produce rainfall totals of
2 to 4 inches, with maximum totals of 6 inches, across coastal
sections of El Salvador, Guatemala and the Mexican states of
Chiapas, Tabasco and Veracruz.  Rainfall totals of 4 to 8 inches,
with maximum totals of 12 inches, are possible across the Mexican
states of Oaxaca and Guerrero. This rainfall may produce life
threatening flooding and mudslides, especially in areas of steep
terrain.
 
For a complete depiction of forecast rainfall associated with
Tropical Depression Five-E, please see the National Weather
Service Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are possible in the hurricane watch area
by Wednesday night. Tropical storm conditions are possible in the
tropical storm watch area by late Wednesday.
 
STORM SURGE: Storm surge could produce coastal flooding near where
the center crosses the coast in areas of onshore winds. The surge
will be accompanied by large and destructive waves.
 
SURF:  Swells generated by the system are expected to begin
affecting the coast of southern Mexico in a day or so.  These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM CST.
Next complete advisory at 300 AM CST.
 
$$
Forecaster Cangialosi
  