000
WTPZ35 KNHC 170846
TCPEP5
 
BULLETIN
Tropical Storm Erick Advisory Number   3
NWS National Hurricane Center Miami FL       EP052025
300 AM CST Tue Jun 17 2025
 
...DEPRESSION BECOMES TROPICAL STORM ERICK...
...EXPECTED TO BECOME A HURRICANE BY TOMORROW...
 
 
SUMMARY OF 300 AM CST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...11.9N 93.6W
ABOUT 450 MI...725 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Bahia De Huatulco to Punta Maldonado
 
A Tropical Storm Watch is in effect for...
* Salina Cruz to Bahia De Huatulco
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in southern Mexico should monitor the progress
of this system.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM CST (0900 UTC), the center of Tropical Storm Erick was
located near latitude 11.9 North, longitude 93.6 West.  Erick is
moving toward the west-northwest near 12 mph (19 km/h).  A slower
west-northwest to northwest motion is expected during the next few
days.  On the forecast track, the system is expected to approach the
coast of southern Mexico Wednesday night.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Strengthening is forecast, and the system is expected to become a
hurricane on Wednesday.
  
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Erick can be found in the Tropical 
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header 
WTPZ45 KNHC.
 
RAINFALL: Tropical Storm Erick could produce rainfall totals of 5 to 
10 inches, with maximum totals of 15 inches, across the Mexican 
states of Chiapas, Oaxaca, and Guerrero and coastal sections of 
Guatemala.  This rainfall may produce life threatening flooding and 
mudslides, especially in areas of steep terrain.

Rainfall totals of 2 to 4 inches, with maximum totals of 6 inches 
are possible across interior portions of Southeast Mexico, El 
Salvador, interior Guatemala and the Mexican states of Chiapas, 
Tabasco and Veracruz.
 
For a complete depiction of forecast rainfall associated with 
Tropical Storm Erick, please see the National Weather Service Storm 
Total Rainfall Graphic available at 
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are possible in the hurricane watch area 
by Wednesday night.  Tropical storm conditions are possible in the 
tropical storm watch area by late Wednesday.
 
STORM SURGE: Storm surge could produce coastal flooding near where
the center crosses the coast in areas of onshore winds.  The surge
will be accompanied by large and destructive waves.
 
SURF:  Swells generated by Erick are expected to begin affecting the 
coast of southern Mexico in a day or so.  These swells are likely to 
cause life-threatening surf and rip current conditions.  Please 
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM CST.
Next complete advisory at 900 AM CST.
 
$$
Forecaster Pasch/Gibbs/Jelsema
  