140 
WTPZ35 KNHC 180238
TCPEP5
 
BULLETIN
Tropical Storm Erick Advisory Number   6
NWS National Hurricane Center Miami FL       EP052025
900 PM CST Tue Jun 17 2025
 
...ERICK FORECAST TO BRING HURRICANE CONDITIONS AND LIFE-THREATENING 
FLASH FLOODS TO PORTIONS OF SOUTHERN MEXICO WEDNESDAY NIGHT AND 
THURSDAY...
 
 
SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...13.1N 94.9W
ABOUT 210 MI...335 KM SSE OF PUERTO ANGEL MEXICO
ABOUT 330 MI...535 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has issued a Hurricane Warning from
Puerto Angel to Acapulco. A Hurricane Watch has been issued from 
west of Acapulco to Tecpan de Galeana.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Punta Angel
 
A Hurricane Watch is in effect for...
* West of Acapulco to Tecpan de Galeana
* East of Puerto Angel to Bahias de Huatulco
 
A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Salina Cruz
 
A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area.  A warning is typically issued  
36 hours before the anticipated first occurrence of 
tropical-storm-force winds, conditions that make outside 
preparations difficult or dangerous.  Preparations to protect life 
and property should be rushed to completion.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
Interests elsewhere in southern Mexico should monitor the
progress of Erick.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Tropical Storm Erick was 
located near latitude 13.1 North, longitude 94.9 West. Erick is 
moving toward the northwest near 7 mph (11 km/h). A northwestward 
motion with a gradual increase in forward speed is expected over the 
next couple of days.  On the forecast track, the center of Erick is 
expected to approach the coast of southern Mexico Wednesday night 
and move inland or be near the coast on Thursday. 
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts. 
Rapid strengthening is forecast during the next day or two, and 
Erick is expected to become a hurricane by by early Wednesday.  
Erick is forecast to be near or at major hurricane strength when it 
approaches the coast of southern Mexico Wednesday night and 
Thursday.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.
 
The estimated minimum central pressure is 998 mb (29.47 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Tropical Storm Erick could produce rainfall totals of 8 to 
16 inches, with maximum totals of 20 inches, across the Mexican 
states of Oaxaca and Guerrero. This rainfall may produce life 
threatening flooding and mudslides, especially in areas of steep 
terrain. Rainfall totals of 3 to 5 inches, with maximum totals of 8 
inches, are possible across the Mexican states of Chiapas, 
Michoacan, Colima and Jalisco.

For a complete depiction of forecast rainfall associated with 
Tropical Storm Erick, please see the National Weather Service Storm 
Total Rainfall Graphic available at 
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND:  Hurricane conditions are expected in the hurricane warning 
area Wednesday night and Thursday and possible in the hurricane 
watch area on Thursday.  Tropical storm conditions are expected in 
the tropical storm warning area late Wednesday and Wednesday night.
 
STORM SURGE: Dangerous storm surge is expected to produce coastal
flooding near and to the east of where the center crosses the coast
in areas of onshore winds.  The surge will be accompanied by large
and destructive waves.
 
SURF:  Swells generated by Erick are expected to begin affecting the
coast of southern Mexico in a day or so.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM CST.
Next complete advisory at 300 AM CST.
 
$$
Forecaster Gibbs/Bucci
  