958 
WTPZ35 KNHC 181151
TCPEP5
 
BULLETIN
Hurricane Erick Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP052025
600 AM CST Wed Jun 18 2025

...ERICK NOW A HURRICANE...
...EXPECTED TO BRING HURRICANE CONDITIONS AND LIFE-THREATENING
FLASH FLOODS TO PORTIONS OF SOUTHERN MEXICO LATER TONIGHT AND
THURSDAY...
 
 
SUMMARY OF 600 AM CST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...13.5N 95.7W
ABOUT 160 MI...255 KM SSE OF PUERTO ANGEL MEXICO
ABOUT 275 MI...440 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.26 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Puerto Angel
 
A Hurricane Watch is in effect for...
* West of Acapulco to Tecpan de Galeana
* East of Puerto Angel to Bahias de Huatulco
 
A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Salina Cruz
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
Interests elsewhere in southern Mexico should monitor the
progress of Erick.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 AM CST (1200 UTC), the center of Hurricane Erick was
located near latitude 13.5 North, longitude 95.7 West. Erick is
moving toward the northwest near 7 mph (11 km/h). A northwestward
motion with a gradual increase in forward speed is expected later
today or tonight. On the forecast track, the center of Erick is
expected to approach the coast of southern Mexico late tonight and
move inland or be near the coast on Thursday.
 
Maximum sustained winds are near 75 mph (120 km/h) with higher
gusts. Rapid strengthening is expected today, and Erick may reach 
major hurricane strength when it approaches the coast of southern 
Mexico Thursday.
 
Hurricane-force winds extend outward up to 15 miles (30 km) from 
the center, and tropical-storm-force winds extend outward up to 70 
miles (110 km) from the center.
 
The estimated minimum central pressure is 991 mb (29.26 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce rainfall totals of 8 to 16 inches, with
maximum totals of 20 inches, across the Mexican states of Oaxaca and
Guerrero. This rainfall will lead to life-threatening flooding and
mudslides, especially in areas of steep terrain. Rainfall totals of
3 to 5 inches, with maximum totals of 8 inches, are expected across
the Mexican states of Chiapas, Michoacan, Colima and Jalisco.
 
For a complete depiction of forecast rainfall associated with
Hurricane Erick, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are expected in the hurricane warning
area early Thursday and possible in the hurricane watch area on
Thursday. Tropical storm conditions are expected in the tropical
storm warning area later today and tonight.
 
STORM SURGE: A dangerous storm surge is expected to produce coastal
flooding near and to the east of where the center crosses the coast
in areas of onshore winds. The surge will be accompanied by large
and destructive waves.
 
SURF: Swells generated by Erick are expected to begin affecting the
coast of southern Mexico later today.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.
 
$$
Forecaster Hagen
  