548 
WTPZ35 KNHC 182033
TCPEP5
 
BULLETIN
Hurricane Erick Advisory Number   9
NWS National Hurricane Center Miami FL       EP052025
300 PM CST Wed Jun 18 2025
 
...DANGEROUS ERICK FORECAST TO BECOME A MAJOR HURRICANE BY 
TONIGHT...
...EXPECTED TO BRING POTENTIALLY DESTRUCTIVE WINDS AND
LIFE-THREATENING FLASH FLOODS TO PORTIONS OF SOUTHERN MEXICO LATE
TONIGHT AND THURSDAY...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...14.5N 96.5W
ABOUT 85 MI...135 KM S OF PUERTO ANGEL MEXICO
ABOUT 185 MI...300 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...967 MB...28.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Puerto Angel
 
A Hurricane Watch is in effect for...
* West of Acapulco to Tecpan de Galeana
 
A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Salina Cruz
* West of Acapulco to Tecpan de Galeana
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 hours.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.
 
Interests elsewhere in southern Mexico should monitor the progress
of Erick.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Hurricane Erick was located
near latitude 14.5 North, longitude 96.5 West. Erick is moving
toward the northwest near 9 mph (15 km/h). A northwestward motion
with a slight increase in forward speed is expected later today or
tonight. On the forecast track, the center of Erick is expected to
approach the coast of southern Mexico late tonight and move inland 
on Thursday morning.
 
Maximum sustained winds are near 110 mph (175 km/h) with higher
gusts.  Erick is forecast to reach major hurricane strength by this 
evening, with continued additional strengthening possible overnight.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).
 
The estimated minimum central pressure is 967 mb (28.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce rainfall totals of 8 to 12 inches, with 
maximum totals of 16 inches, across the Mexican states of Oaxaca and 
Guerrero. This rainfall will lead to life-threatening flooding and 
mudslides, especially in areas of steep terrain. Rainfall totals of 
2 to 4 inches, with maximum totals of 6 inches, are expected across 
the Mexican states of Chiapas, Michoacan, Colima and Jalisco.
 
For a complete depiction of forecast rainfall associated with
Hurricane Erick, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are expected in the hurricane warning
area late tonight into early Thursday and possible in the hurricane
watch area on Thursday. Tropical storm conditions are expected to
begin in the warning area this evening or overnight, and
preparations to protect life and property should be rushed to
completion.  Tropical storm conditions are expected in the tropical
storm warning area beginning this evening.
 
STORM SURGE: A dangerous, life-threatening storm surge is expected
to produce coastal flooding near and to the east of where the center
crosses the coast, in areas of onshore winds.  The surge will be
accompanied by large and destructive waves.
 
SURF: Swells generated by Erick will continue affecting the coast of
southern Mexico through Thursday.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM CST.
Next complete advisory at 900 PM CST.
 
$$
Forecaster Hagen
  