460 
WTPZ35 KNHC 182344
TCPEP5
 
BULLETIN
Hurricane Erick Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP052025
600 PM CST Wed Jun 18 2025
 
...HURRICANE HUNTER AIRCRAFT REPORTS ERICK IS A MAJOR HURRICANE...
...EXPECTED TO BRING POTENTIALLY DESTRUCTIVE WINDS AND
LIFE-THREATENING FLASH FLOODS TO PORTIONS OF SOUTHERN MEXICO LATE
TONIGHT AND THURSDAY...
 
 
SUMMARY OF 600 PM CST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...14.9N 96.7W
ABOUT 55 MI...90 KM SSW OF PUERTO ANGEL MEXICO
ABOUT 160 MI...260 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...953 MB...28.14 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Puerto Angel
 
A Hurricane Watch is in effect for...
* West of Acapulco to Tecpan de Galeana
 
A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Salina Cruz
* West of Acapulco to Tecpan de Galeana
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 hours.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.
 
Interests elsewhere in southern Mexico should monitor the progress
of Erick.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 PM CST (0000 UTC), the center of Hurricane Erick was located
near latitude 14.9 North, longitude 96.7 West. Erick is moving
toward the northwest near 9 mph (15 km/h). A northwestward motion
with a slight increase in forward speed is expected later today or
tonight. On the forecast track, the center of Erick is expected to
approach the coast of southern Mexico late tonight and move inland
on Thursday morning.
 
Reports from an Air Force Reserve Hurricane Hunter aircraft 
indicate that maximum sustained winds have increased to near     
120 mph (195 km/h) with higher gusts.  Additional strengthening   
is expected until the center makes landfall.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from
the center and tropical-storm-force winds extend outward up to     
90 miles (150 km).
 
The minimum central pressure estimated from the the Hurricane 
Hunter aircraft data is 953 mb (28.14 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce rainfall totals of 8 to 12 inches, with
maximum totals of 16 inches, across the Mexican states of Oaxaca and
Guerrero. This rainfall will lead to life-threatening flooding and
mudslides, especially in areas of steep terrain. Rainfall totals of
2 to 4 inches, with maximum totals of 6 inches, are expected across
the Mexican states of Chiapas, Michoacan, Colima and Jalisco.
 
For a complete depiction of forecast rainfall associated with
Hurricane Erick, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are expected in the hurricane warning 
area beginning during the next several hours, and they are possible 
in the hurricane watch area on Thursday. In the hurricane warning 
area, tropical storm conditions are expected to begin during the 
next few hours, and preparations to protect life and property 
should be rushed to completion.  Tropical storm conditions are 
expected in the tropical storm warning area beginning during the 
next several hours.
 
STORM SURGE: A dangerous, life-threatening storm surge is expected
to produce coastal flooding near and to the east of where the center
crosses the coast, in areas of onshore winds.  The surge will be
accompanied by large and destructive waves.
 
SURF: Swells generated by Erick will continue affecting the coast of
southern Mexico through Thursday.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.
 
$$
Forecaster Beven
  