260 
WTPZ35 KNHC 190544
TCPEP5
 
BULLETIN
Hurricane Erick Special Advisory Number  11
NWS National Hurricane Center Miami FL       EP052025
1200 AM CST Thu Jun 19 2025
 
...ERICK NOW AN EXTREMELY DANGEROUS CATEGORY 4 HURRICANE...
 
 
SUMMARY OF 1200 AM CST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.5N 97.5W
ABOUT 70 MI...110 KM WSW OF PUERTO ANGEL MEXICO
ABOUT 90 MI...145 KM SE OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...939 MB...27.73 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Puerto Angel
 
A Hurricane Watch is in effect for...
* West of Acapulco to Tecpan de Galeana
 
A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Salina Cruz
* West of Acapulco to Tecpan de Galeana
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 12-24 hours.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
12-24 hours.
 
Interests elsewhere in southern Mexico should monitor the progress
of Erick.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1200 AM CST (0600 UTC), the center of Hurricane Erick was located
near latitude 15.5 North, longitude 97.5 West. Erick is moving
toward the northwest near 9 mph (15 km/h), and this general motion
is expected to continue through tonight.  On the forecast track, the
center of Erick is expected to make landfall in the western portion
of the Mexican state of Oaxaca or the eastern portion of the Mexican
state of Guerrero this morning, and then continue inland over
southern Mexico later today.
 
Maximum sustained winds have increased to near 145 mph (230 km/h) 
with higher gusts.  Erick is a category 4 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.   Some additional strengthening
could occur before landfall.  After landfall, Erick should rapidly
weaken over the mountains of Mexico, and the system is likely to
dissipate Thursday night or early Friday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).
 
The estimated minimum central pressure is 939 mb (27.73 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce rainfall totals of 8 to 12 inches, with
maximum totals of 16 inches, across the Mexican states of Oaxaca and
Guerrero. This rainfall will lead to life-threatening flooding and
mudslides, especially in areas of steep terrain. Rainfall totals of
2 to 4 inches, with maximum totals of 6 inches, are expected across
the Mexican states of Chiapas, Michoacan, Colima and Jalisco.
 
For a complete depiction of forecast rainfall associated with Erick,
please see the National Weather Service Storm Total Rainfall Graphic
available at hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are expected in the hurricane warning
area beginning during the next few hours, with extremely
destructive winds near the core of Erick.  Hurricane conditions
are possible in the hurricane watch area today. Tropical Storm
conditions are currently spreading onshore in the hurricane warning
area.  Tropical storm conditions are expected in the tropical storm
warning area beginning during the next few hours. Wind speeds atop
and on the windward sides of hills and mountains are often up to 30
percent stronger than the near-surface winds indicated in this
advisory, and in some elevated locations could be even greater.
 
STORM SURGE: A dangerous, life-threatening storm surge is expected
to produce coastal flooding near and to the east of where the center
crosses the coast, in areas of onshore winds.  The surge will be
accompanied by large and destructive waves.
 
SURF: Swells generated by Erick will continue affecting the coast of
southern Mexico through today.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM CST.
Next complete advisory at 300 AM CST.
 
$$
Forecaster Pasch
  