211 
WTPZ35 KNHC 191137
TCPEP5
 
BULLETIN
Hurricane Erick Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       EP052025
600 AM CST Thu Jun 19 2025
 
...MAJOR HURRICANE ERICK MAKES LANDFALL IN EXTREME WESTERN OAXACA 
MEXICO...
 
 
SUMMARY OF 600 AM CST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...16.3N 98.3W
ABOUT 20 MI...30 KM E OF PUNTA MALDONADO MEXICO
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...950 MB...28.05 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Puerto Angel
 
A Hurricane Watch is in effect for...
* West of Acapulco to Tecpan de Galeana
 
A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Salina Cruz
* West of Acapulco to Tecpan de Galeana
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 AM CST (1200 UTC), the center of Hurricane Erick was located 
along the coast of Mexico near latitude 16.3 North, longitude 98.3 
West, just east of Punta Maldonado.  Erick is moving toward the 
northwest near 9 mph (15 km/h), and this general motion is expected 
to continue through tonight.  On the forecast track, the center of 
Erick is expected to move inland over southern Mexico throughout 
the day.
 
Maximum sustained winds are near 125 mph (205 km/h) with higher 
gusts.  Erick is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Erick is expected to rapidly weaken over the 
mountains of Mexico, and the system is likely to dissipate tonight 
or early Friday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from
the center and tropical-storm-force winds extend outward up to 90
miles (150 km).
 
The estimated minimum central pressure is 950 mb (28.05 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce rainfall totals of 8 to 12 inches, with
maximum totals of 16 inches, across the Mexican states of Oaxaca and
Guerrero. This rainfall will lead to life-threatening flooding and
mudslides, especially in areas of steep terrain. Rainfall totals of
2 to 4 inches, with maximum totals of 6 inches, are expected across
the Mexican states of Chiapas, Michoacan, Colima and Jalisco.
 
For a complete depiction of forecast rainfall associated with Erick,
please see the National Weather Service Storm Total Rainfall Graphic
available at hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions are expected in the hurricane warning 
area during the next few hours, with destructive winds near the core 
of Erick.  Hurricane conditions are possible in the hurricane watch 
area today.  Tropical storm conditions are ongoing in the tropical 
storm warning area.  Wind speeds atop and on the windward sides of 
hills and mountains are often up to 30 percent stronger than the 
near-surface winds indicated in this advisory, and in some elevated 
locations could be even greater.
 
STORM SURGE: A dangerous, life-threatening storm surge is expected
to produce coastal flooding near and to the east of where the center
crosses the coast, in areas of onshore winds.  The surge will be
accompanied by large and destructive waves.
 
SURF: Swells generated by Erick will continue affecting the coast of 
southern Mexico throughout the day.  These swells are likely to 
cause life-threatening surf and rip current conditions.  Please 
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.
 
$$
Forecaster Cangialosi
  