000
WTPZ35 KNHC 191730
TCPEP5
 
BULLETIN
Hurricane Erick Intermediate Advisory Number 13A
NWS National Hurricane Center Miami FL       EP052025
1200 PM CST Thu Jun 19 2025
 
...HURRICANE ERICK MOVING INLAND OVER SOUTHERN MEXICO...
...FLOODING RAINS CONTINUE...
 
 
SUMMARY OF 1200 PM CST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.1N 99.0W
ABOUT 60 MI...100 KM NNW OF PUNTA MALDONADO MEXICO
ABOUT 60 MI...100 KM ENE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Acapulco to Puerto Escondido
 
A Tropical Storm Warning is in effect for...
* West of Acapulco to Tecpan de Galeana
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1200 PM CST (1800 UTC), the center of Hurricane Erick was located
near latitude 17.1 North, longitude 99.0 West. Erick is moving
toward the northwest near 12 mph (19 km/h), and this general motion
is expected through tonight. On the forecast track, the center of
Erick is forecast to move over southern and southwestern Mexico
until it dissipates tonight.
 
Maximum sustained winds are near 75 mph (120 km/h) with higher
gusts. Continued rapid weakening is forecast, and Erick will likely
dissipate tonight.
 
Hurricane-force winds extend outward up to 15 miles (30 km) from
the center and tropical-storm-force winds extend outward up to 90
miles (150 km).
 
The estimated minimum central pressure is 988 mb (29.18 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce additional rainfall of 6 to 8 inches in
portions of the states of Oaxaca and Guerrero with storm totals of
16 inches possible. Life-threatening flooding and mudslides are
expected, especially in areas of steep terrain.  Rainfall totals of
2 to 4 inches, with maximum totals of 6 inches, are expected across
the states of, Michoacan, Colima and Jalisco.
 
For a complete depiction of forecast rainfall associated with Erick,
please see the National Weather Service Storm Total Rainfall Graphic
available at hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Hurricane conditions, especially in gusts, are expected to 
continue for a couple of more hours in portions of the hurricane 
warning area. Tropical storm conditions will likely continue into 
the late afternoon in the tropical storm warning area. Wind speeds 
atop and on the windward sides of hills and mountains are often up 
to 30 percent stronger than the near-surface winds indicated in this 
advisory, and in some elevated locations could be even greater.
 
STORM SURGE: Storm surge is expected to produce coastal flooding 
along portions of the coast of southern Mexico in areas of onshore 
winds. The surge will be accompanied by large and destructive waves.
 
SURF: Swells generated by Erick will continue affecting the coast of
southern Mexico throughout the day. These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 PM CST.
 
$$
Forecaster Cangialosi
  