601 
WTPZ35 KNHC 192032
TCPEP5
 
BULLETIN
Tropical Storm Erick Advisory Number  14
NWS National Hurricane Center Miami FL       EP052025
300 PM CST Thu Jun 19 2025
 
...ERICK WEAKENS TO A TROPICAL STORM...
...FLOODING RAINS CONTINUE...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 99.7W
ABOUT 35 MI...60 KM NNE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has discontinued all warnings east of
Punta Maldonado and downgraded the Hurricane Warning to a Tropical
Storm Warning from Acapulco to Punta Maldonado.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Punta Maldonado to Tecpan de Galeana
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Tropical Storm Erick was
located near latitude 17.4 North, longitude 99.7 West. Erick is
moving toward the northwest near 12 mph (19 km/h) and this general
motion is expected through tonight. On the forecast track, the
center of Erick is forecast to move over southern and southwestern
Mexico until it dissipates tonight.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Continued rapid weakening is forecast, and Erick will likely
dissipate tonight.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Erick can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP5 and WMO header
WTPZ45 KNHC.
 
RAINFALL: Erick will produce additional rainfall of 6 to 8 inches of 
rainfall mainly in the state of Guerrero with storm totals of 16 
inches possible. Life-threatening flooding and mudslides are 
expected, especially in areas of steep terrain. Rainfall totals of 2 
to 4 inches, with maximum totals of 6 inches, are expected across 
the states of Michoacan and Oaxaca.

For a complete depiction of forecast rainfall associated with Erick, 
please see the National Weather Service Storm Total Rainfall Graphic 
available at hurricanes.gov/graphics_ep5.shtml?rainqpf
 
WIND: Tropical storm conditions are expected to occur for a few more
hours in the warning area. Wind speeds atop and on the windward
sides of hills and mountains are often up to 30 percent stronger
than the near-surface winds indicated in this advisory, and in some
elevated locations could be even greater.
 
STORM SURGE: Storm surge is expected to gradually subside through
tonight.
 
SURF: Swells generated by Erick will continue affecting the coast of
southern Mexico through the evening. These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM CST.
Next complete advisory at 900 PM CST.
 
$$
Forecaster Cangialosi
  