

459 
WTNT33 KNHC 040544
TCPAT3

BULLETIN
Potential Tropical Cyclone Eighteen Intermediate Advisory Number 2A
NWS National Hurricane Center Miami FL       AL182024
100 AM EST Mon Nov 04 2024

...SYSTEM EXPECTED TO BECOME A HURRICANE IN THE NORTHWESTERN 
CARIBBEAN...


SUMMARY OF 100 AM EST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...14.0N 76.9W
ABOUT 275 MI...445 KM S OF KINGSTON JAMAICA
ABOUT 465 MI...745 KM SE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Cayman Islands

A Tropical Storm Warning is in effect for...
* Jamaica

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
24 to 36 hours.

Interests in Cuba and the Florida Keys should closely monitor this
system.  Additional watches or warnings could be required today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 AM EST (0600 UTC), the disturbance was centered near latitude
14.0 North, longitude 76.9 West.  The system is moving toward the
north near 6 mph (9 km/h), and a more northwestward motion is 
expected today and forecast to continue for the next few days. 
On the forecast track, the system is expected to move near Jamaica 
by late today and be near or over the Cayman Islands late Tuesday 
into Wednesday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts.  The disturbance is expected to become a tropical storm 
today with additional strengthening forecast thereafter.  The 
system could be near hurricane intensity as it passes near the 
Cayman Islands in the northwestern Caribbean.
* Formation chance through 48 hours...high...near 100 percent.
* Formation chance through 7 days ...high...near 100 percent.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Eighteen can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT3 and WMO
header WTNT43 KNHC and on the web at
hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Hurricane conditions are possible in the Cayman Islands by
late Tuesday. Tropical storm conditions are expected in Jamaica by
late today.

RAINFALL: Heavy rainfall will impact areas of the western Caribbean
with the heaviest rainfall occurring over Jamaica and southern Cuba
through mid-week.  Rainfall totals between 3 to 6 inches with 
locally up to 9 inches are expected.  Flooding could occur over 
portions of Jamaica and Cuba, with mudslides possible.

Heavy rainfall will spread north into Florida and adjacent areas of
the Southeast United States during mid- to late week.

STORM SURGE:  Minor coastal flooding is possible in Jamaica on
Monday and the Cayman Islands on Tuesday.

SURF:  Swells generated by the system are expected to affect much
of the western Caribbean during the next few days.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM EST.

$$
Forecaster Pasch


