
ZCZC MIATCPAT3 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Potential Tropical Cyclone Eighteen Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       AL182024
700 AM EST Mon Nov 04 2024

...SYSTEM EXPECTED TO BECOME A TROPICAL DEPRESSION SOON...
...FORECAST TO STRENGTHEN AS IT MOVES ACROSS THE WESTERN 
CARIBBEAN...


SUMMARY OF 700 AM EST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...14.8N 76.8W
ABOUT 220 MI...355 KM S OF KINGSTON JAMAICA
ABOUT 425 MI...685 KM SE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Cayman Islands

A Tropical Storm Warning is in effect for...
* Jamaica

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
24 hours.

Interests in Cuba and the Florida Keys should closely monitor this
system.  Additional watches or warnings could be required today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM EST (1200 UTC), the disturbance was centered near latitude
14.8 North, longitude 76.8 West. The system is moving toward the
north near 7 mph (11 km/h). A northwestward motion is expected 
later today and forecast to continue for the next few days. On
the forecast track, the system is expected to move near Jamaica 
this evening, be near or over the Cayman Islands on Tuesday, 
and approach Cuba on Wednesday.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts. 
The disturbance is expected to become a tropical depression or storm 
today with additional strengthening forecast thereafter.  The system 
could be near or at hurricane intensity when it passes near the 
Cayman Islands and Cuba.
* Formation chance through 48 hours ...high...near 100 percent.
* Formation chance through 7 days... high...near 100 percent.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Eighteen can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT3 and WMO
header WTNT43 KNHC and on the web at
hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Hurricane conditions are possible in the Cayman Islands by
Tuesday afternoon.  Tropical storm conditions are expected in
Jamaica by this evening.

RAINFALL: Heavy rainfall will impact areas of the Western Caribbean
with the heaviest rainfall occurring over Jamaica and portions of
Cuba through mid-week.  Rainfall totals between 3 to 6 inches with
locally up to 9 inches are expected.  Flooding could occur over
portions of Jamaica and Cuba, with mudslides possible.

Heavy rainfall will spread north into Florida and adjacent areas of
the Southeast United States during mid- to late week.

For a complete depiction of forecast rainfall associated with
Potential Tropical Cyclone Eighteen, please see the National Weather
Service Storm Total Rainfall Graphic, available at
www.nhc.noaa.gov/graphics_at3.shtml?rainqpf

STORM SURGE:  Minor coastal flooding is possible in Jamaica on
Monday and the Cayman Islands on Tuesday.

SURF:  Swells generated by the system are expected to affect much
of the western Caribbean during the next few days.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM EST.

$$
Forecaster Cangialosi

NNNN
