

000
WTNT33 KNHC 072033
TCPAT3

BULLETIN
Hurricane Rafael Advisory Number  17
NWS National Hurricane Center Miami FL       AL182024
300 PM CST Thu Nov 07 2024

...RAFAEL SLIGHTLY STRONGER AND BETTER ORGANIZED...


SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...24.7N 86.2W
ABOUT 260 MI...420 KM WNW OF HAVANA CUBA
ABOUT 325 MI...520 KM NE OF PROGRESO MEXICO
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the southern and southwestern Gulf of Mexico should
monitor the progress of Rafael.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Hurricane Rafael was located 
near latitude 24.7 North, longitude 86.2 West. Rafael is moving 
toward the west-northwest near 9 mph (15 km/h). A turn toward the 
west is expected tonight, with this general motion at a slightly 
slower forward speed continuing through the weekend. On the forecast 
track, Rafael is expected to move over the southern Gulf of Mexico 
for the next few days.

Maximum sustained winds have increased to near 105 mph (165 km/h) 
with higher gusts. Some small intensity fluctuations are possible 
tonight. Weakening is forecast to begin on Friday and continue 
through the weekend.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Rafael can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT3 and WMO header
WTNT43 KNHC and on the web at hurricanes.gov/text/MIATCDAT3.shtml

SURF: Swells generated by Rafael are expected to spread across most
of the Gulf of Mexico during the next several days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.

$$
Forecaster Reinhart

