

000
WTNT33 KNHC 080252
TCPAT3

BULLETIN
Hurricane Rafael Advisory Number  18
NWS National Hurricane Center Miami FL       AL182024
900 PM CST Thu Nov 07 2024

...RAFAEL GETS A LITTLE BETTER ORGANIZED AS IT MOVES
WESTWARD OVER THE GULF OF MEXICO...


SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...24.6N 87.1W
ABOUT 280 MI...455 KM NE OF PROGRESO MEXICO
ABOUT 635 MI...1025 KM E OF MOUTH OF THE RIO GRANDE
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...965 MB...28.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the southern and southwestern Gulf of Mexico should
monitor the progress of Rafael.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Hurricane Rafael was located
near latitude 24.6 North, longitude 87.1 West. Rafael is moving
toward the west near 9 mph (15 km/h), and a general westward to
west-northwestward motion at a slower forward speed is expected
through the weekend. On the forecast track, Rafael is expected to
move over the central Gulf of Mexico for the next few days.

Reports from an Air Force Reserve Hurricane Hunter aircraft indicate
that maximum sustained winds are near 105 mph (165 km/h) with higher
gusts.  Some small intensity fluctuations are possible tonight and
Friday. Weakening is forecast to begin on Friday night and continue
through the weekend.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The latest minimum central pressure reported by the Hurricane
Hunter aircraft is 965 mb (28.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Rafael can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT3 and WMO header
WTNT43 KNHC and on the web at hurricanes.gov/text/MIATCDAT3.shtml

SURF: Swells generated by Rafael are expected to spread across most
of the Gulf of Mexico during the next several days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.

$$
Forecaster Beven

