

000
WTNT33 KNHC 080558
TCPAT3

BULLETIN
Hurricane Rafael Special Advisory Number  19
NWS National Hurricane Center Miami FL       AL182024
1200 AM CST Fri Nov 08 2024

...RAFAEL STRENGTHENS INTO MAJOR HURRICANE...


SUMMARY OF 1200 AM CST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.7N 87.5W
ABOUT 275 MI...440 KM NNE OF PROGRESO MEXICO
ABOUT 610 MI...985 KM E OF MOUTH OF THE RIO GRANDE
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...956 MB...28.23 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the southern and southwestern Gulf of Mexico should
monitor the progress of Rafael.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM CST (0600 UTC), the center of Hurricane Rafael was 
located near latitude 24.7 North, longitude 87.5 West. Rafael is 
moving toward the west near 9 mph (15 km/h), and a general westward 
to west-northwestward motion at a slower forward speed is expected 
through the weekend. On the forecast track, Rafael is expected to 
move over the central Gulf of Mexico for the next few days.

Maximum sustained winds have increased to near 120 mph (195 km/h) 
with higher gusts.  Rafael is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Some additional strengthening 
is possible today. A weakening trend is forecast to begin late 
tonight and continue through the weekend.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 956 mb (28.23 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Rafael can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT3 and WMO header
WTNT43 KNHC and on the web at hurricanes.gov/text/MIATCDAT3.shtml

SURF: Swells generated by Rafael are expected to spread across most
of the Gulf of Mexico during the next several days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.

$$
Forecaster Kelly

