

000
WTNT33 KNHC 091443
TCPAT3

BULLETIN
Tropical Storm Rafael Advisory Number  25
NWS National Hurricane Center Miami FL       AL182024
900 AM CST Sat Nov 09 2024

...AIR FORCE HURRICANE HUNTERS FIND RAFAEL CONTINUES TO WEAKEN...


SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...25.2N 91.5W
ABOUT 290 MI...470 KM NNW OF PROGRESO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Tropical Storm Rafael was
located near latitude 25.2 North, longitude 91.5 West. Rafael is
moving toward the west-northwest near 6 mph (9 km/h). The storm is
expected to slow down and meander over the central Gulf of Mexico
Sunday into Monday, then turn toward the south or south-southwest by
Monday night.

Data from the Air Force Hurricane Hunters indicate that maximum
sustained winds have decreased to near 50 mph (85 km/h) with higher
gusts. Continued weakening is forecast through early next week.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure based on aircraft data is
999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Rafael can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC
and on the web at hurricanes.gov/text/MIATCDAT3.shtml

SURF: Swells generated by Rafael will continue impacting portions of
the northern and western Gulf Coast through the weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.

RAINFALL: Rainfall indirectly associated with the moisture from
Rafael is expected to lead to 3 to 6 inches of rain, with local
amounts to 10 inches, across portions of the Upper Texas Coast into
Southwest and Central Louisiana through Sunday morning. This rain
will lead to potentially significant flash flooding.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM CST.

$$
Forecaster Reinhart

