

000
WTNT33 KNHC 100231
TCPAT3

BULLETIN
Tropical Storm Rafael Advisory Number  27
NWS National Hurricane Center Miami FL       AL182024
900 PM CST Sat Nov 09 2024

...RAFAEL REMAINS SHEARED AND DISORGANIZED...


SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...25.7N 91.7W
ABOUT 330 MI...530 KM NNW OF PROGRESO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Tropical Storm Rafael was
located near latitude 25.7 North, longitude 91.7 West. Rafael is
moving toward the northwest near 3 mph (6 km/h). The storm is
expected to meander over the central Gulf of Mexico through Sunday 
night, then turn toward the south and south-southwest on Monday and 
Tuesday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Weakening is expected through early next week, and Rafael is 
forecast to degenerate to a post-tropical remnant low on Monday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Rafael can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC
and on the web at hurricanes.gov/text/MIATCDAT3.shtml

SURF: Swells generated by Rafael will continue impacting portions of
the northern and western Gulf Coast through the weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.

RAINFALL:  Rainfall indirectly associated with the moisture from 
Rafael is expected to lead to 3 to 6 inches of rain, with local 
amounts to 10 inches, across portions of Southwest and Central 
Louisiana through Sunday morning.  This rain will lead to 
potentially significant flash flooding.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.

$$
Forecaster Beven

