

990 
WTNT33 KNHC 211753
TCPAT3

BULLETIN
Tropical Storm Bret Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       AL032023
200 PM AST Wed Jun 21 2023

...AIR FORCE RESERVE HURRICANE HUNTER AIRCRAFT INVESTIGATING BRET...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...13.2N 53.3W
ABOUT 415 MI...670 KM E OF BARBADOS
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning in in effect for...
* St. Lucia

 A Tropical Storm Watch is in effect for...
* Barbados
* Dominica
* Martinique

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 24 to
48 hours.

Interests elsewhere in the Lesser Antilles should monitor the
progress of Bret.  Additional watches or warnings will likely be
required for these islands today.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Tropical Storm Bret was
located near latitude 13.2 North, longitude 53.3 West.  Bret is
moving toward the west near 15 mph (24 km/h), and this general
motion with an increase in forward speed is expected during the next
several days.  On the forecast track, the center of Bret is expected
to approach the Lesser Antilles on Thursday, move across the Lesser
Antilles late Thursday and Thursday night, and then move westward
across the eastern and central Caribbean Sea Friday and Saturday.

Air Force Reserve Hurricane Hunter data indicate that maximum 
sustained winds are near 60 mph (95 km/h) with higher gusts.  Some 
increase in strength is forecast before Bret reaches the Lesser 
Antilles.  Weakening is expected by Friday once Bret moves over the 
Caribbean Sea, and the system is likely to dissipate on Saturday.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

Data from the reconnaissance aircraft confirm that the minimum 
central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Bret can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC and
on the web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm conditions are expected within the warning
area and possible within the watch areas late Thursday and Thursday
night.

RAINFALL:  Through Saturday, storm total rainfall amounts of 3 to 6
inches with maximum amounts of 10 inches are possible across
portions of the Lesser Antilles from Guadeloupe south to St. Vincent
and the Grenadines, including Barbados.  The heavy rainfall could
lead to flash flooding, especially across areas of higher terrain.
Urban flooding is also possible.

SURF:  Swells generated by Bret are expected to begin affecting
portions of the Lesser Antilles on Thursday.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Berg


