

000
WTNT33 KNHC 221146
TCPAT3

BULLETIN
Tropical Storm Bret Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       AL032023
800 AM AST Thu Jun 22 2023

...BRET NEAR HURRICANE STRENGTH...
...EXPECTED TO BRING STRONG WINDS AND HEAVY RAIN TO PORTIONS OF THE 
LEEWARD ISLANDS LATER TODAY AND TONIGHT...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...13.6N 57.0W
ABOUT 170 MI...265 KM E OF BARBADOS
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* St. Lucia

A Tropical Storm Warning in in effect for...
* Dominica
* St. Lucia
* Martinique

A Tropical Storm Watch is in effect for...
* Barbados
* St. Vincent and the Grenadines

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 24
hours.

Interests elsewhere in the Lesser Antilles should monitor the
progress of Bret.  Additional watches or warnings may be required
later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Bret was
located near latitude 13.6 North, longitude 57.0 West.  Bret is
moving toward the west near 15 mph (24 km/h), and this general
motion with an increase in forward speed is expected during the next
few days.  On the forecast track, the center of Bret is expected to
approach the Lesser Antilles today, move across the Lesser Antilles
this evening and tonight, and then move westward across the eastern
and central Caribbean Sea Friday and Saturday.

Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts.  Little change in strength is forecast today while Bret
approaches the Lesser Antilles.  Weakening is anticipated to begin
tonight or Friday after Bret passes the Lesser Antilles, and the
system is likely to dissipate over the central Caribbean Sea by
Saturday night.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center, especially to the north.

The minimum central pressure partially based on data from the Air 
Force Hurricane Hunters is 996 mb (29.42 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Bret can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC and
on the web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Hurricane conditions are possible in the hurricane watch area
this evening or tonight.  Tropical storm conditions are expected
within the tropical storm warning areas and possible within the
watch areas later today and tonight.

RAINFALL:  Storm total rainfall amounts of 3 to 6 inches with
maximum amounts of 10 inches are possible across portions of the
Lesser Antilles from Guadeloupe south to St. Vincent and the
Grenadines, including Barbados.  The heavy rainfall could lead to
flash flooding, especially across areas of higher terrain.  Urban
flooding is also possible.

SURF:  Swells generated by Bret are beginning to affect portions of 
the Lesser Antilles.  These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Cangialosi

