

000
WTNT33 KNHC 222032
TCPAT3

BULLETIN
Tropical Storm Bret Advisory Number  14
NWS National Hurricane Center Miami FL       AL032023
500 PM AST Thu Jun 22 2023

...BRET VERY NEAR BARBADOS...
...HEAVY RAIN AND STRONG WINDS EXPECTED IN PORTIONS OF THE LESSER
ANTILLES THROUGH TONIGHT...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...13.4N 59.6W
ABOUT 15 MI...25 KM NNW OF BARBADOS
ABOUT 100 MI...160 KM ESE OF ST. LUCIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...W OR 265 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* St. Lucia

A Tropical Storm Warning in in effect for...
* Dominica
* St. Lucia
* Martinique
* Barbados
* St. Vincent and the Grenadines

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.

Interests elsewhere in the Lesser Antilles should monitor the
progress of Bret.  Additional watches or warnings may be required
later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Bret was
located near latitude 13.4 North, longitude 59.6 West. Bret is
moving toward the west near 16 mph (26 km/h) and this general motion
with an increase in forward speed is expected during the next few
days.  On the forecast track, the center of Bret is expected to move
across the Lesser Antilles this evening and tonight, and then move
westward across the eastern and central Caribbean Sea Friday and
Saturday.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Gradual weakening is anticipated over the next couple of
days, and the system is likely to dissipate over the central
Caribbean Sea on Sunday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Bret can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC and
on the web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Hurricane conditions are possible in the hurricane watch area
this evening or tonight.  Tropical storm conditions are expected
within the tropical storm warning areas through tonight.

RAINFALL:  Storm total rainfall amounts of 3 to 6 inches with
maximum amounts of 10 inches are possible across portions of the
Lesser Antilles from Guadeloupe south to St Vincent and the
Grenadines, including Barbados.  The heavy rainfall could lead to
flash flooding, especially across areas of higher terrain. Urban
flooding is also possible.

SURF:  Swells generated by Bret are expected to affect portions of
the Lesser Antilles through Friday.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Cangialosi

