

955 
WTNT33 KNHC 230240
TCPAT3

BULLETIN
Tropical Storm Bret Advisory Number  15
NWS National Hurricane Center Miami FL       AL032023
1100 PM AST Thu Jun 22 2023

...CENTER OF BRET NEAR ST. VINCENT...
...HEAVY RAIN AND STRONG WINDS EXPECTED IN PORTIONS OF THE LESSER
ANTILLES THROUGH TONIGHT...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.3N 61.1W
ABOUT 5 MI...10 KM E OF ST. VINCENT
ABOUT 35 MI...55 KM S OF ST. LUCIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Government of St. Lucia has discontinued the Hurricane Watch
for St. Lucia.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning in in effect for...
* Dominica
* St. Lucia
* Martinique
* Barbados
* St. Vincent and the Grenadines

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.

Interests elsewhere in the Lesser Antilles and the southeastern
Caribbean Sea should monitor the progress of Bret.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Bret was
located near latitude 13.3 North, longitude 61.1 West. Bret is
moving toward the west near 18 mph (30 km/h), and this general 
motion is expected during the next couple of days.  On the forecast 
track, the center of Bret is expected to move through and away from 
the Windward Islands during the next several hours, and then move 
westward across the eastern and central Caribbean Sea Friday
and Saturday.

Maximum sustained winds are now near 60 mph (95 km/h) with higher 
gusts.  Gradual weakening is anticipated over the next couple of
days, and the system is likely to dissipate over the central
Caribbean Sea Saturday night or Sunday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.  The Hewanorra International Airport on St. Lucia 
recently reported sustained winds of 41 mph (67 km/h) and a wind 
gust of 69 mph (111 km/h).  Tropical-storm conditions are also 
being reported from Martinique.

The minimum central pressure estimated from Air Force Reserve 
Hurricane Hunter data and earlier surface observations is 1004 mb 
(29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Bret can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC and
on the web at hurricanes.gov/text/MIATCDAT3.shtml

WIND: Tropical storm conditions are expected within the tropical
storm warning areas through tonight.

RAINFALL:  Storm total rainfall amounts of 3 to 6 inches with 
maximum amounts of 10 inches are possible across portions of the 
Lesser Antilles from Guadeloupe south through St. Vincent and the 
Grenadines, including Barbados. The heavy rainfall could lead to 
flash flooding, especially across areas of higher terrain. Urban 
flooding is also possible.

SURF:  Swells generated by Bret are expected to affect portions of
the Lesser Antilles through Friday.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Beven


