

778 
WTNT33 KNHC 230850
TCPAT3

BULLETIN
Tropical Storm Bret Advisory Number  16
NWS National Hurricane Center Miami FL       AL032023
500 AM AST Fri Jun 23 2023

...BRET'S TRAILING RAINBANDS CONTINUE TO PRODUCE GUSTY WINDS AND
HEAVY RAINS OVER PORTIONS OF THE WINDWARD ISLANDS...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...13.4N 62.9W
ABOUT 115 MI...185 KM W OF ST. VINCENT
ABOUT 420 MI...670 KM E OF CURACAO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Barbados has discontinued the Tropical Storm
Warning for Barbados.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning in in effect for...
* Dominica
* St. Lucia
* Martinique
* St. Vincent and the Grenadines

In this case, a Tropical Storm Warning means that tropical storm
conditions are occurring within the warning area.

Interests adjacent to the southeastern Caribbean Sea should monitor
the progress of Bret.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Bret was
located near latitude 13.4 North, longitude 62.9 West.  Bret is
moving toward the west near 18 mph (30 km/h), and this general
motion is expected to continue through the weekend.  On the
forecast track, the center of Bret will continue moving westward
away from the Windward Islands and across the eastern and central
Caribbean Sea during the next couple of days.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Weakening is forecast during the next couple of days, and Bret is
expected to dissipate over the central Caribbean Sea by Saturday
night or Sunday.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
mainly to the north of the center.

The estimated minimum central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Bret can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC and
on the web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm conditions are expected to diminish within
the tropical storm warning areas later this morning.

RAINFALL:  Storm total rainfall amounts of 3 to 6 inches with
maximum amounts of 10 inches are possible across portions of the
Lesser Antilles from Guadeloupe south through St. Vincent and the
Grenadines, including Barbados. The heavy rainfall could lead to
flash flooding, especially across areas of higher terrain. Urban
flooding is also possible.

SURF:  Swells generated by Bret are expected to begin subsiding
along the Lesser Antilles through the day.  Swells are likely
to increase in areas adjacent to the central Caribbean Sea
later today and on Sunday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.

$$
Forecaster Berg


