

000
WTNT33 KNHC 231435
TCPAT3

BULLETIN
Tropical Storm Bret Advisory Number  17
NWS National Hurricane Center Miami FL       AL032023
1100 AM AST Fri Jun 23 2023

...BRET MOVING WESTWARD OVER THE EASTERN CARIBBEAN SEA...
...RAIN AND GUSTY WINDS LINGER IN PORTIONS OF THE LESSER ANTILLES...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.3N 64.7W
ABOUT 235 MI...380 KM W OF ST. VINCENT
ABOUT 300 MI...480 KM ENE OF CURACAO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Barbados has discontinued the Tropical Storm
Warning for St. Vincent and the Grenadines.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.

Interests adjacent to the southeastern Caribbean Sea should monitor
the progress of Bret.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Bret was
located near latitude 13.3 North, longitude 64.7 West. Bret is
moving toward the west near 21 mph (33 km/h) and this general
motion is expected to continue through the weekend.  On the forecast
track, the center of Bret will continue moving westward away from
the Windward Islands and across the eastern and central Caribbean
Sea during the next couple of days.

Maximum sustained winds remain near 60 mph (95 km/h) with higher
gusts. Weakening is forecast during the next couple of days, and
Bret is expected to dissipate over the central Caribbean Sea
by Sunday.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure based on data from the Air 
Force Hurricane Hunters is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Bret can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC and
on the web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Gusty winds should continue to subside across the Windward 
Islands over the next few hours.

RAINFALL:  Rainfall associated with Bret is expected to diminish
across the Lesser Antilles later today as the storm continues to
move westward across the Caribbean.  Additional rainfall amounts of
1 to 2 inches are possible across portions of the Lesser Antilles
from Guadeloupe south through St Vincent and the Grenadines,
including Barbados. The heavy rainfall could lead to flash
flooding, especially across areas of higher terrain. Urban flooding
is also possible.

SURF:  Swells generated by Bret are expected to gradually subside
along the Lesser Antilles through the day.  Swells are likely
to increase in areas adjacent to the central Caribbean Sea
later today and on Saturday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi

