000
WTPZ32 KNHC 092039
TCPEP2
 
BULLETIN
Tropical Storm Raymond Advisory Number   2
NWS National Hurricane Center Miami FL       EP172025
300 PM CST Thu Oct 09 2025
 
...TROPICAL STORM WARNING ISSUED FOR SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...16.5N 101.7W
ABOUT 85 MI...135 KM S OF ZIHUATANEJO MEXICO
ABOUT 690 MI...1115 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has upgraded the Tropical Storm Watch to a
Tropical Storm Warning from Zihuatanejo to Cabo Corrientes, Mexico.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Zihuatanejo to Cabo Corrientes, Mexico
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
Interests in southern Baja California Sur should monitor the
progress of this system.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Tropical Storm Raymond was 
located near latitude 16.5 North, longitude 101.7 West. Raymond is 
moving toward the west-northwest near 15 mph (24 km/h) and this 
general motion is expected to continue through early Friday.  A turn 
toward the northwest is expected by late Friday, followed by a 
northward turn by early Sunday.  On the forecast track, the center 
of the storm is expected to move parallel to the southwestern coast 
of Mexico through Friday and then be near southern Baja California 
Sur Saturday and Sunday.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Some strengthening is forecast through Friday, but weakening is 
likely over the weekend.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected within the
warning area tonight through Friday.
 
RAINFALL: Outer bands from Raymond will bring heavy rain to portions
of southwestern Mexico through Saturday. Across coastal portions of
Guerrero and Michoacán, rainfall amounts of 2 to 4 inches are
expected, with local amounts of 6 inches or more in Michoacán. This
rainfall will bring a risk of flash flooding, especially in areas of
higher terrain. Across coastal portions of Oaxaca, Colima, and
Jalisco, rainfall amounts of 1 to 2 inches are expected. Moisture
from Raymond will also bring the potential for additional heavy
rainfall over portions of the Southwest U.S. early next week.
 
For a complete depiction of forecast rainfall and flash flooding
associated with the storm, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by the storm are expected to spread
westward along the southwestern coast of Mexico through Friday and
reach southern Baja California Sur on Saturday.  Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM CST.
Next complete advisory at 900 PM CST.
 
$$
Forecaster Kelly
  