315 
WTPZ32 KNHC 092350
TCPEP2
 
BULLETIN
Tropical Storm Raymond Intermediate Advisory Number 2A
NWS National Hurricane Center Miami FL       EP172025
600 PM CST Thu Oct 09 2025
 
...RAYMOND MOVING WEST-NORTHWESTWARD PARALLEL TO THE SOUTHWESTERN 
COAST OF MEXICO...
...RISK OF FLASH FLOODING IN AREAS OF HIGHER TERRAIN THROUGH 
SATURDAY... 
 
SUMMARY OF 600 PM CST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...16.5N 102.3W
ABOUT 95 MI...155 KM SSW OF ZIHUATANEJO MEXICO
ABOUT 665 MI...1065 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Zihuatanejo to Cabo Corrientes, Mexico
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
Interests in southern Baja California Sur should monitor the
progress of this system.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 PM CST (0000 UTC), the center of Tropical Storm Raymond was
located near latitude 16.5 North, longitude 102.3 West.  Raymond is
moving toward the west-northwest near 14 mph (22 km/h) and this 
general motion is expected to continue through early Friday.  A 
turn toward the northwest is expected by late Friday, followed by a 
northward turn by early Sunday.  On the forecast track, the center 
of the cyclone is expected to move parallel to the southwestern 
coast of Mexico through Friday and then approach the southern Baja 
California Sur over the weekend.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher
gusts. Some strengthening is forecast through Friday, followed by a 
weakening trend over the weekend.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected within the
warning area tonight through Friday.
 
RAINFALL: Outer bands from Raymond will bring heavy rain to portions
of southwestern Mexico through Saturday.  Across coastal portions of
Guerrero and Michoacán, rainfall amounts of 2 to 4 inches are
expected, with local amounts of 6 inches or more in Michoacán.  This
rainfall will bring a risk of flash flooding, especially in areas of
higher terrain.  Across coastal portions of Oaxaca, Colima, and
Jalisco, rainfall amounts of 1 to 2 inches are expected.  Moisture
from Raymond will also bring the potential for additional heavy
rainfall over portions of the Southwest U.S. early next week.
 
For a complete depiction of forecast rainfall and flash flooding
associated with the storm, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by the storm are expected to spread
westward along the southwestern coast of Mexico through Friday and
reach southern Baja California Sur on Saturday.  Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.
 
$$
Forecaster Roberts
  