000
WTPZ32 KNHC 100851
TCPEP2
 
BULLETIN
Tropical Storm Raymond Advisory Number   4
NWS National Hurricane Center Miami FL       EP172025
300 AM CST Fri Oct 10 2025
 
...RAYMOND JUST OFF THE SOUTHWESTERN COAST OF MEXICO...
...TROPICAL STORM WATCH ISSUED FOR BAJA CALIFORNIA SUR...
 
 
SUMMARY OF 300 AM CST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 103.4W
ABOUT 120 MI...195 KM W OF ZIHUATANEJO MEXICO
ABOUT 565 MI...915 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has issued a Tropical Storm Watch from
Los Barriles to Santa Fe, Mexico.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Zihuatanejo to Cabo Corrientes, Mexico
 
A Tropical Storm Watch is in effect for...
* Baja California Sur from Los Barriles to Santa Fe, Mexico
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM CST (0900 UTC), the center of Tropical Storm Raymond was
located near latitude 17.4 North, longitude 103.4 West. Raymond is
moving toward the west-northwest near 14 mph (22 km/h), and this 
general motion is expected to continue through this morning.  A turn 
toward the northwest is expected this evening, followed by a 
northward turn on early Sunday.  On the forecast track, the center 
of the cyclone is expected to move parallel to the southwestern 
coast of Mexico through today and then approach southern Baja 
California Sur over the weekend.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Little change in strength is expected through today, followed by a 
weakening trend over the weekend.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 998 mb (29.47 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Raymond can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC.
 
WIND: Tropical storm conditions are expected within the warning
area through today.  Tropical storm conditions are possible within
the watch area on Saturday.
 
RAINFALL: Outer bands from Raymond will bring heavy rain to portions 
of southwestern Mexico through Saturday. Across coastal portions of 
Guerrero and Michoacán, rainfall amounts of 2 to 4 inches are 
expected, with local amounts of 6 inches or more in Michoacán. This 
rainfall will bring a risk of flash flooding, especially in areas of 
higher terrain. Across coastal portions of Oaxaca, Colima, and 
Jalisco, rainfall amounts of 1 to 2 inches are expected. Moisture 
from Raymond will also bring the potential for additional heavy 
rainfall over portions of the Southwest U.S. early next week.

For a complete depiction of forecast rainfall and flash flooding 
associated with Raymond, please see the National Weather Service 
Storm Total Rainfall Graphic, available at 
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by the storm are expected to spread westward
along the southwestern coast of Mexico today and reach southern Baja
California Sur on Saturday. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM CST.
Next complete advisory at 900 AM CST.
 
$$
Forecaster Bucci
  