356 
WTPZ32 KNHC 110236
TCPEP2
 
BULLETIN
Tropical Storm Raymond Advisory Number   7
NWS National Hurricane Center Miami FL       EP172025
800 PM MST Fri Oct 10 2025
 
...RAYMOND APPROACHING BAJA CALIFORNIA SUR...
...HEAVY RAINS AND TROPICAL STORM CONDITIONS EXPECTED THERE ON
SATURDAY...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...20.2N 107.7W
ABOUT 235 MI...375 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Manzanillo to Cabo Corrientes, Mexico
* Las Islas Marias
* Baja California Sur from Los Barriles to Santa Fe, Mexico
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Tropical Storm Raymond was 
located near latitude 20.2 North, longitude 107.7 West. Raymond is 
moving toward the northwest near 18 mph (30 km/h) and this motion is 
expected to continue tonight, followed by a turn toward the north 
Saturday through Sunday.  On the forecast track, the center of 
Raymond is expected to be near the southern Baja California Sur on 
Saturday.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Little change in strength is expected tonight, but the storm is 
forecast to weaken as it moves near or over Baja California Sur 
over the weekend.
 
Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Raymond can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC.
 
WIND: Tropical storm conditions are expected within the warning area 
in Southwestern Mexico and Islas Marias during the next several 
hours.  These conditions are expected in the warning area in Baja 
California Sur starting Saturday morning.
 
RAINFALL: Rainfall totals of 4 to 6 inches with local amounts of 8
or more inches are expected across Sonora and northern Chihuahua.
This rainfall will bring a risk of flash flooding, especially in
areas of higher terrain. Across coastal portions of Michoacan,
Colima, Jalisco, Nayarit, Sinaloa, and the central to southern
portions of Baja California Sur, rainfall totals of 1 to 2 inches
are expected.  Moisture from Raymond will also bring the potential
for additional heavy rainfall over portions of the Southwest U.S.
Sunday into early next week.
 
For a complete depiction of forecast rainfall and flash flooding
associated with the depression, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Raymond are affecting the coast of 
southwest and west-central Mexico.  These swells are expected to 
spread to the southern Baja California Sur by early Saturday. Please 
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1100 PM MST.
Next complete advisory at 200 AM MST.
 
$$
Forecaster Cangialosi
  