367 
WTPZ32 KNHC 111437
TCPEP2
 
BULLETIN
Tropical Storm Raymond Advisory Number   9
NWS National Hurricane Center Miami FL       EP172025
800 AM MST Sat Oct 11 2025
 
...RAYMOND APPROACHING BAJA CALIFORNIA SUR...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...21.5N 109.2W
ABOUT 105 MI...170 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has discontinued the Tropical Storm Warning
for Las Islas Marias.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Baja California Sur from Los Barriles to Santa Fe
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 12
hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Tropical Storm Raymond was 
located near latitude 21.5 North, longitude 109.2 West. Raymond is 
moving toward the north-northwest near 15 mph (24 km/h). A turn 
toward the north is expected later today, with this motion then 
continuing through Sunday.  On the forecast track, the center of 
Raymond is expected to move over the southern portion of Baja 
California Sur later today.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Additional weakening is forecast during the next day or so, with 
Raymond expected to weaken into a post-tropical remnant low on 
Sunday.
 
Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Raymond can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC.
 
WIND:  Tropical storm conditions are expected to begin in Baja
California Sur in a few hours.
 
RAINFALL:  Rainfall totals of 4 to 6 inches with local amounts of 8
or more inches are expected across northwestern Sinaloa, Sonora and
northern Chihuahua. This rainfall will bring a risk of flash
flooding, especially in areas of higher terrain. Rainfall totals of
1 to 2 inches are expected across central Sinaloa, the southern
portions of Baja California Sur and across the far southeast portion
of Baja California and far northeast Baja California Sur.  Moisture
from Raymond will also bring the potential for additional heavy
rainfall over portions of the Southwest U.S. Sunday into early next
week.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Raymond, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Raymond are affecting the coasts of
southwest and west-central Mexico, and southern Baja California Sur.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1100 AM MST.
Next complete advisory at 200 PM MST.
 
$$
Forecaster Kelly
  