000
WTPZ32 KNHC 111743
TCPEP2
 
BULLETIN
Tropical Depression Raymond Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP172025
1100 AM MST Sat Oct 11 2025
 
...RAYMOND WEAKENS TO A DEPRESSION...
...ALL TROPICAL STORM WARNINGS DISCONTINUED...

 
SUMMARY OF 1100 AM MST...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.7N 109.6W
ABOUT 85 MI...135 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has discontinued all Tropical Storm 
Warnings.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM MST (1800 UTC), the center of Tropical Depression Raymond 
was located near latitude 21.7 North, longitude 109.6 West. The 
depression is moving toward the north-northwest near 13 mph (20 
km/h). A turn toward the north is expected later today, with this 
motion then continuing through Sunday.  On the forecast track, the 
center of Raymond is expected to move over the southern portion of 
Baja California Sur later today.
 
Recent satellite wind data indicate that the maximum sustained winds 
have decreased to near 35 mph (55 km/h) with higher gusts. 
Additional weakening is forecast, with Raymond expected to become a 
post-tropical remnant low tonight or Sunday.
 
The estimated minimum central pressure is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Raymond can be found in the 
Tropical Cyclone Discussion under AWIPS header MIATCDEP2 and WMO 
header WTPZ42 KNHC.
 
RAINFALL:  Rainfall totals of 4 to 6 inches with local amounts of 8
or more inches are expected across northwestern Sinaloa, Sonora and
northern Chihuahua. This rainfall will bring a risk of flash
flooding, especially in areas of higher terrain. Rainfall totals of
1 to 2 inches are expected across central Sinaloa, the southern
portions of Baja California Sur and across the far southeast portion
of Baja California and far northeast Baja California Sur.  Moisture
from Raymond will also bring the potential for additional heavy
rainfall over portions of the Southwest U.S. Sunday into early next
week.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Raymond, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Raymond are affecting the coasts of
southwest and west-central Mexico, and southern Baja California Sur.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Kelly
  