593 
WTPZ32 KNHC 112031
TCPEP2
 
BULLETIN
Tropical Depression Raymond Advisory Number  10
NWS National Hurricane Center Miami FL       EP172025
200 PM MST Sat Oct 11 2025
 
...RAYMOND FORECAST TO BECOME A REMNANT LOW TONIGHT...
...REMNANT MOISTURE TO BRING A RISK OF FLASH FLOODING TO
NORTHWESTERN MEXICO AND SOUTHWESTERN UNITED STATES...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...22.5N 109.9W
ABOUT 30 MI...45 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Tropical Depression Raymond 
was located near latitude 22.5 North, longitude 109.9 West. The 
depression is moving toward the north-northwest near 14 mph (22 
km/h). A turn toward the north is expected later today, with this 
motion then continuing through Sunday.  On the forecast track, the 
center of Raymond is expected to move over the southern portion of 
Baja California Sur later today.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Additional weakening is forecast, with Raymond expected to become a
post-tropical remnant low tonight.
 
The estimated minimum central pressure is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Rainfall totals of 4 to 6 inches with local amounts of 8
or more inches are expected across northwestern Sinaloa, Sonora and
northern Chihuahua. This rainfall will bring a risk of flash
flooding, especially in areas of higher terrain. Rainfall totals of
1 to 2 inches are expected across central Sinaloa, the southern
portions of Baja California Sur and across the far southeast portion
of Baja California and far northeast Baja California Sur.  Moisture
from Raymond will also bring the potential for additional heavy
rainfall over portions of the Southwest U.S. Sunday into early next
week.
 
For a complete depiction of forecast rainfall and flash flooding
associated with Raymond, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Raymond are affecting the coasts of
southwest and west-central Mexico, and southern Baja California Sur.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Kelly
  