

000
WTPZ31 KNHC 300231
TCPEP1

BULLETIN
Hurricane Adrian Advisory Number  10
NWS National Hurricane Center Miami FL       EP012023
900 PM MDT Thu Jun 29 2023

...ADRIAN STRENGTHS SLIGHTLY WHILE MOVING NORTHWESTWARD...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...16.7N 111.3W
ABOUT 440 MI...705 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Hurricane Adrian was located
near latitude 16.7 North, longitude 111.3 West. Adrian is moving
toward the northwest near 8 mph (13 km/h), and this general
motion is expected to continue over the next few days.

Maximum sustained winds have increased to near near 90 mph (150 
km/h) with higher gusts.  Some additional slight strengthening is 
expected tonight or early Friday. Weakening is forecast to begin 
later on Friday and continue through the weekend.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 976 mb (28.82 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Adrian are affecting portions of the 
southwestern and west-central coasts of Mexico and the southern Baja 
California peninsula. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Bucci

