

000
WTPZ31 KNHC 302045
TCPEP1

BULLETIN
Hurricane Adrian Advisory Number  13
NWS National Hurricane Center Miami FL       EP012023
300 PM MDT Fri Jun 30 2023

...ADRIAN MOVING NORTHWESTWARD OVER OPEN WATERS...
...FORECAST TO BEGIN WEAKENING TONIGHT...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...17.7N 112.9W
ABOUT 410 MI...655 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Hurricane Adrian was located 
near latitude 17.7 North, longitude 112.9 West. Adrian is moving 
toward the northwest near 7 mph (11 km/h). A west-northwestward 
motion at a similar forward speed is expected during the next couple 
of days, followed by a turn toward the west on Monday.

Maximum sustained winds are near 105 mph (165 km/h) with higher 
gusts. Weakening is expected during the next few days, and Adrian is 
forecast to become post-tropical on Sunday.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 970 mb (28.65 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Adrian are affecting portions of the
west-central coast of Mexico and the southern Baja California
peninsula. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster Reinhart

