

000
WTPZ31 KNHC 011440
TCPEP1

BULLETIN
Tropical Storm Adrian Advisory Number  16
NWS National Hurricane Center Miami FL       EP012023
900 AM MDT Sat Jul 01 2023

...ADRIAN NOW A TROPICAL STORM...
...CENTER TO PASS NEAR OR OVER CLARION ISLAND THIS MORNING...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...18.4N 114.5W
ABOUT 430 MI...690 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Adrian was 
located near latitude 18.4 North, longitude 114.5 West. Adrian is 
moving toward the west-northwest near 7 mph (11 km/h). This general 
motion is expected to continue within a gradual turn toward the west 
during the next couple of days.

Maximum sustained winds are near 65 mph (100 km/h) with higher 
gusts. Steady to rapid weakening is expected during the next couple 
of days, and Adrian is forecast to weaken to a tropical depression 
early Sunday and become a post-tropical remnant low soon thereafter.

Tropical-storm-force winds extend outward up to 70 miles (110 km) 
from the center. A Mexican navy automated weather station on Clarion 
Island recently reported a sustained wind of 34 mph (55 km/h) and a 
gust of 49 mph (79 km/h).

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Adrian are affecting portions of the
southern Baja California peninsula. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Reinhart

