

231 
WTNT35 KNHC 262051
TCPAT5

BULLETIN
Tropical Storm Isaac Advisory Number   4
NWS National Hurricane Center Miami FL       AL102024
500 PM AST Thu Sep 26 2024

...ISAAC CONTINUING EASTWARD WITH NO CHANGE IN STRENGTH...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...37.5N 50.6W
ABOUT 1285 MI...2070 KM W OF THE AZORES
ABOUT 880 MI...1415 KM ENE OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...E OR 80 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Isaac was
located near latitude 37.5 North, longitude 50.6 West. Isaac is
moving toward the east near 10 mph (17 km/h), and a turn toward the
east-northeast is expected by the weekend. 

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Strengthening is forecast, and Isaac is expected reach or be near
hurricane strength by late Friday or early Saturday.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 995 mb (29.39 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and a large wind fetch from a
deep-layer trough are affecting portions of the coast of Bermuda and
could spread into the Azores by this weekend.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster D. Zelinsky/Bookbinder


