

000
WTNT35 KNHC 270239
TCPAT5

BULLETIN
Tropical Storm Isaac Advisory Number   5
NWS National Hurricane Center Miami FL       AL102024
1100 PM AST Thu Sep 26 2024

...ISAAC STRENGTHENING AND LIKELY TO BECOME A HURRICANE SOON...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...37.1N 49.8W
ABOUT 1245 MI...2005 KM W OF THE AZORES
ABOUT 910 MI...1470 KM ENE OF BERMUDA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...E OR 90 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Isaac was
located near latitude 37.1 North, longitude 49.8 West. Isaac is
moving toward the east near 12 mph (19 km/h) and this motion with a 
turn more east-northeastward is expected over the next several days.

Satellite wind data suggests that maximum sustained winds have 
increased to near 65 mph (100 km/h) with higher gusts.  Additional 
strengthening is expected during the next day or so and Isaac is 
forecast to become a hurricane tomorrow. 

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and a large wind fetch from a
deep-layer trough are affecting portions of the coast of Bermuda and
could spread into the Azores by this weekend.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Papin

