

000
WTNT35 KNHC 280237
TCPAT5

BULLETIN
Hurricane Isaac Advisory Number   9
NWS National Hurricane Center Miami FL       AL102024
300 AM GMT Sat Sep 28 2024

...ISAAC CONTINUES TO STRENGTHEN...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...38.2N 43.4W
ABOUT 890 MI...1430 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...ENE OR 75 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Hurricane Isaac was located
near latitude 38.2 North, longitude 43.4 West. Isaac is moving
toward the east-northeast near 16 mph (26 km/h). A gradual turn to 
the northeast is expected with a slight decrease in forward speed 
over the next day or so. The northeastward motion should then 
continue through Monday.

Maximum sustained winds are near 90 mph (150 km/h) with higher
gusts. Little change in strength is expected through Saturday 
morning, followed by gradual weakening through early next week. 
Isaac is expected to be a post-tropical cyclone on Monday.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).

The estimated minimum central pressure is 973 mb (28.74 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and a large wind fetch from a
deep-layer trough could spread into the Azores this weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Hagen

