

000
WTNT35 KNHC 281431
TCPAT5

BULLETIN
Hurricane Isaac Advisory Number  11
NWS National Hurricane Center Miami FL       AL102024
300 PM GMT Sat Sep 28 2024

...ISAAC REMAINS A CATEGORY TWO HURRICANE OVER THE CENTRAL
ATLANTIC...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...40.2N 39.7W
ABOUT 695 MI...1120 KM WNW OF THE AZORES
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...ENE OR 60 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the eye of Hurricane Isaac was located
near latitude 40.2 North, longitude 39.7 West. Isaac is moving
toward the east-northeast near 20 mph (31 km/h) and a decrease in 
forward speed and a turn to the northeast is expected during the 
next couple of days.

Maximum sustained winds are near 105 mph (165 km/h) with higher
gusts.  Gradual weakening is expected, and Isaac is expected to be 
a post-tropical cyclone on Monday.

Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and a large wind fetch from a
deep-layer trough will affect the Azores over the next few days.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Konarik/Cangialosi

