

000
WTNT35 KNHC 282041
TCPAT5

BULLETIN
Hurricane Isaac Advisory Number  12
NWS National Hurricane Center Miami FL       AL102024
900 PM GMT Sat Sep 28 2024

...ISAAC STILL A CATEGORY 2 HURRICANE BUT FORECAST TO WEAKEN...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...41.3N 38.4W
ABOUT 645 MI...1040 KM WNW OF THE AZORES
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Hurricane Isaac was located 
near latitude 41.3 North, longitude 38.4 West. Isaac is moving 
toward the northeast near 18 mph (30 km/h).  A slower east-northeast 
to northeast motion is expected during the next couple of days.

Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts.  Gradual weakening is expected, and Isaac is forecast to be
a post-tropical cyclone on Monday.

Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and a large wind fetch from a
deep-layer trough will affect the Azores over the next few days.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM GMT.

$$
Forecaster Cangialosi

