

000
WTNT35 KNHC 291435
TCPAT5

BULLETIN
Hurricane Isaac Advisory Number  15
NWS National Hurricane Center Miami FL       AL102024
300 PM GMT Sun Sep 29 2024

...ISAAC CONTINUES MOVING TOWARDS THE NORTHEAST OVER THE OPEN
ATLANTIC...
...LARGE AREA OF DANGEROUS HIGH SEAS SURROUND THE HURRICANE...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...43.2N 35.6W
ABOUT 575 MI...925 KM NW OF THE AZORES
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...971 MB...28.68 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Hurricane Isaac was located 
near latitude 43.2 North, longitude 35.6 West. Isaac is moving 
toward the northeast near 12 mph (19 km/h) and this motion is 
expected to continue during the next couple of days, followed by a 
turn toward the north-northeast on Tuesday.

Maximum sustained winds have decreased to near 75 mph (120 km/h) 
with higher gusts, and continued weakening is forecast over the next 
few days. Isaac is forecast to become a post-tropical cyclone on 
Monday. 

Hurricane-force winds extend outward up to 45 miles (75 km) from the 
center and tropical-storm-force winds extend outward up to 205 miles 
(335 km).

The estimated minimum central pressure is 971 mb (28.68 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and an upstream deep-layer trough 
will affect the Azores over the next few days. These swells are 
likely to cause life-threatening surf and rip current conditions.  
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Mahoney/Papin

