
ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Isaac Advisory Number  17
NWS National Hurricane Center Miami FL       AL102024
300 AM GMT Mon Sep 30 2024

...ISAAC FORECAST TO BECOME POST-TROPICAL LATER TODAY...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...44.4N 32.8W
ABOUT 535 MI...860 KM NNW OF THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NE OR 55 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Tropical Storm Isaac was
located near latitude 44.4 North, longitude 32.8 West. Isaac is
moving toward the northeast near 14 mph (22 km/h). A turn toward 
the north-northeast at a similar forward speed is expected on 
Tuesday.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Slow weakening is expected during the next several days. 
Isaac is forecast to become a post-tropical cyclone later today.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac and an upstream deep-layer trough
will affect the Azores over the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster D. Zelinsky

NNNN
