

000
WTNT35 KNHC 300835
TCPAT5

BULLETIN
Tropical Storm Isaac Advisory Number  18
NWS National Hurricane Center Miami FL       AL102024
900 AM GMT Mon Sep 30 2024

...ISAAC EXPECTED TO BECOME POST-TROPICAL LATER TODAY...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...44.7N 31.3W
ABOUT 515 MI...825 KM NNW OF THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...ENE OR 60 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Tropical Storm Isaac was
located near latitude 44.7 North, longitude 31.3 West.  Isaac is
moving toward the east-northeast near 15 mph (24 km/h).  A turn
toward the northeast at a similar forward speed is expected on
Tuesday.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Slow weakening is expected during the next several days.
Isaac is forecast to become a post-tropical cyclone later today.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac will affect the Azores over the 
next few days. These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.

$$
Forecaster Pasch

