

000
WTNT35 KNHC 301453
TCPAT5

BULLETIN
Post-Tropical Cyclone Isaac Advisory Number  19
NWS National Hurricane Center Miami FL       AL102024
300 PM GMT Mon Sep 30 2024

...ISAAC BECOMES A POST-TROPICAL CYCLONE...
...THIS IS THE LAST ADVISORY...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...44.8N 29.1W
ABOUT 480 MI...775 KM NNW OF THE AZORES
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...983 MB...29.03 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Post-Tropical Cyclone Isaac 
was located near latitude 44.8 North, longitude 29.1 West. The 
post-tropical cyclone is moving toward the east-northeast near 17 
mph (28 km/h) and a turn to the northeast is expected with a similar 
forward motion for the next several days.

Maximum sustained winds have decreased to near 60 mph (95 km/h)
with higher gusts. Gradual weakening is forecast over the next
several days.

Tropical-storm-force winds extend outward up to 185 miles (295 km)
from the center.

The estimated minimum central pressure is 983 mb (29.03 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Isaac will affect the Azores over the
next few days. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on this system. Additional information on this system can be 
found in High Seas Forecasts issued by Meteo France under WMO header 
FQNT50 LFPW and available on the web at 
www.meteofrance.com/previsions-meteo-marine/bulletin/grandlarge/ 
metarea2. Additional information on this system can also be found in 
High Seas Forecasts issued by the UK Met Office under WMO header 
FQNT21 EGRR and on the web at 
metoffice.gov.uk/weather/specialist-forecasts/coast-and-sea/high- 
seas-forecast/.

$$
Forecaster Papin

