

000
WTPA31 PHFO 222036
TCPCP1

BULLETIN
Tropical Storm Hone Advisory Number   2
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
1100 AM HST Thu Aug 22 2024

...TROPICAL STORM HONE FORMS WELL EAST-SOUTHEAST OF THE HAWAIIAN
ISLANDS...
...INTERESTS IN THE MAIN HAWAIIAN ISLANDS SHOULD MONITOR THE
PROGRESS OF HONE...


SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.9N 142.2W
ABOUT 885 MI...1430 KM ESE OF HILO HAWAII
ABOUT 1090 MI...1760 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the main Hawaiian Islands should monitor the progress
of Hone. Tropical Storm Watches may be required for portions of the
main Hawaiian Islands tonight or Friday.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Tropical Storm Hone was
located near latitude 15.9 North, longitude 142.2 West. Hone is
moving toward the west-northwest near 14 mph (22 km/h) and this
motion is expected to continue for the next few days. On the 
forecast track, the center of Hone is expected to pass near or 
south of the Big Island this weekend.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Some strengthening is forecast during the next couple of days. 

Tropical-storm-force winds extend outward up to 15 miles (30 km)
from the center.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the
Tropical Cyclone Discussion under AWIPS header TCDCP1 and WMO
header WTPA41 PHFO, and on the web at
hurricanes.gov/text/HFOTCDCP1.shtml.

RAINFALL: From Saturday through Monday, storm total rainfall
amounts of 4 to 8 inches, with locally higher amounts, are possible 
along windward areas of the Big Island of Hawaii, with 2 to 4 
inches possible over windward sections of the smaller islands.

SURF: Swells generated by Tropical Storm Hone are expected to
begin reaching the Hawaiian Islands over the weekend. These swells
are likely to cause life-threatening surf and rip currents. Please
consult products issued by the National Weather Service in
Honolulu, Hawaii.

WIND: Strong and gusty winds are expected to develop over the
Hawaiian Islands this weekend as Tropical Storm Hone
passes near or south of the Big Island.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.

$$
Forecaster M Ballard/R Ballard

