

265 
WTPA31 PHFO 230250
TCPCP1

BULLETIN
Tropical Storm Hone Advisory Number   3
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
500 PM HST Thu Aug 22 2024

...HONE CONTINUING TO MOVE WESTWARD TO THE EAST-SOUTHEAST OF THE
HAWAIIAN ISLANDS...
...TROPICAL STORM WATCH ISSUED FOR THE BIG ISLAND...


SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...15.8N 143.4W
ABOUT 815 MI...1310 KM ESE OF HILO HAWAII
ABOUT 1020 MI...1645 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

A Tropical Storm Watch has been issued for Hawaii County.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Hawaii County

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Tropical Storm Hone was
located near latitude 15.8 North, longitude 143.4 West. Hone is
moving toward the west near 16 mph (26 km/h) and this motion is
expected to continue over the next few days.  On the forecast track, 
the center of Hone is expected to pass near or south of the Big 
Island Saturday night and Sunday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Some strengthening is forecast during the next couple of days. 

Tropical-storm-force winds extend outward up to 30 miles (45 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the
Tropical Cyclone Discussion under AWIPS header TCDCP1 and WMO
header WTPA41 PHFO, and on the web at
hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical storm conditions are possible in the watch area
later Saturday into Sunday. Winds are expected to be strongest 
where they blow downslope from higher terrain, over headlands, and 
through passes.

RAINFALL: Hone is expected to produce storm total rainfall of 4 to
8 inches over mainly windward and southeast facing slopes of the 
Big Island, with locally higher amounts. Rainfall totals of 2 to 4 
inches will be possible over portions of the smaller islands, 
mainly windward.

SURF: Swells generated by Tropical Storm Hone are expected to
begin reaching the Hawaiian Islands over the weekend. These swells
are likely to cause life-threatening surf and rip currents.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM HST.
Next complete advisory at 1100 PM HST.

$$
Forecaster M Ballard/R Ballard


