
ZCZC HFOTCPCP1 ALL
TTAA00 PHFO DDHHMM

BULLETIN
Tropical Storm Hone Intermediate Advisory Number 3A
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
800 PM HST Thu Aug 22 2024

...HONE CONTINUES WESTWARD WELL TO THE EAST-SOUTHEAST OF THE
HAWAIIAN ISLANDS...
...TROPICAL STORM WATCH REMAINS IN EFFECT FOR THE BIG ISLAND...


SUMMARY OF 800 PM HST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...16.0N 144.1W
ABOUT 770 MI...1240 KM ESE OF HILO HAWAII
ABOUT 980 MI...1575 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 14 MPH...23 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Hawaii County

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM HST (0600 UTC), the center of Tropical Storm Hone was
located near latitude 16.0 North, longitude 144.1 West. Hone is
moving toward the west near 14 mph (23 km/h) and this motion is
expected to continue over the next few days.  On the forecast track,
the center of Hone is expected to pass near or south of the Big
Island Saturday night and Sunday.

Maximum sustained winds are near 40 mph (65 km/h) with higher
gusts. Some strengthening is forecast during the next couple of
days.

Tropical-storm-force winds extend outward up to 30 miles (45 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the
Tropical Cyclone Discussion under AWIPS header TCDCP1 and WMO
header WTPA41 PHFO, and on the web at
hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical storm conditions are possible in the watch area
later Saturday into Sunday. Winds are expected to be strongest
where they blow downslope from higher terrain, over headlands, and
through passes.

RAINFALL: Hone is expected to produce storm total rainfall of 4 to
8 inches over mainly windward and southeast facing slopes of the
Big Island, with locally higher amounts. Rainfall totals of 2 to 4
inches will be possible over portions of the smaller islands,
mainly windward.

SURF: Swells generated by Tropical Storm Hone are expected to
begin reaching the Hawaiian Islands over the weekend. These swells
are likely to cause life-threatening surf and rip currents.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.

$$
Forecaster Jelsema

NNNN

