

000
WTPA31 PHFO 232038
TCPCP1

BULLETIN
Tropical Storm Hone Advisory Number   6
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
1100 AM HST Fri Aug 23 2024

...HONE CONTINUES WESTWARD TOWARD THE HAWAIIAN ISLANDS...


SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.7N 147.8W
ABOUT 520 MI...840 KM ESE OF HILO HAWAII
ABOUT 730 MI...1175 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Hawaii County

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within the next 48 hours.

Interests elsewhere in Hawaii should monitor the progress of Hone.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Tropical Storm Hone was
located by Air Force Reserve Hurricane Hunter aircraft near
latitude 16.7 North, longitude 147.8 West. Hone is moving toward the
west near 16 mph (26 km/h). This motion toward the west is expected
to continue over the next several days as the forward speed
gradually slows. On the forecast track, the center of Hone is 
expected to pass near or south of the Big Island Saturday night into 
early Sunday.

Maximum sustained winds are near 50 mph (85 km/h) with higher 
gusts. Some strengthening is forecast during the next 48 to 72 
hours. 

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the
Tropical Cyclone Discussion under AWIPS header TCDCP1 and WMO
header WTPA41 PHFO, and on the web at
hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical storm conditions are possible in the watch area
late Saturday into Sunday. Winds are expected to be strongest
where they blow downslope from higher terrain, over headlands, and
through passes.

RAINFALL: Hone is expected to produce storm total rainfall of 5 to
10 inches over mainly windward and southeast facing slopes of the
Big Island, with locally higher amounts. Rainfall totals of 2 to 4
inches will be possible over portions of the smaller islands,
mainly windward.

SURF: Swells generated by Tropical Storm Hone are expected to
begin reaching the Hawaiian Islands over the weekend. These swells
are likely to cause life-threatening surf and rip currents.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM HST.
Next complete advisory at 500 PM HST.

$$
Forecaster Wroe

