

000
WTPA31 PHFO 240557
TCPCP1

BULLETIN
Tropical Storm Hone Intermediate Advisory Number 7A
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
800 PM HST Fri Aug 23 2024

...HONE CONTINUES WESTWARD TOWARD THE HAWAIIAN ISLANDS...
...TROPICAL STORM WARNING REMAINS IN EFFECT FOR THE BIG ISLAND...


SUMMARY OF 800 PM HST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...17.2N 149.9W
ABOUT 380 MI...610 KM ESE OF HILO HAWAII
ABOUT 595 MI...960 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Hawaii County

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in Hawaii should monitor the progress of Hone.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM HST (0600 UTC), the center of Tropical Storm Hone was
located near latitude 17.2 North, longitude 149.9 West. Hone is
moving toward the west near 15 mph (24 km/h). This motion toward the
west is expected to continue over the next several days as the
forward speed gradually slows. On the forecast track, the center of
Hone is expected to pass near or south of the Big Island Saturday
night into early Sunday.

Maximum sustained winds are near 50 mph (85 km/h) with higher
gusts. Strengthening is forecast during the next 48 hours, and may
become a hurricane by Sunday, followed by weakening late Sunday and
beyond.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the
Tropical Cyclone Discussion under AWIPS header TCDCP1 and WMO
header WTPA41 PHFO, and on the web at
hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical storm conditions are expected in the warning area as
early as Saturday afternoon and continuing into Sunday. Winds are
expected to be strongest where they blow downslope from higher
terrain, over headlands, and through passes.

RAINFALL: Hone is expected to produce storm total rainfall of 5 to
10 inches over mainly windward and southeast facing slopes of the
Big Island, with locally higher amounts possible. Rainfall totals
of 2 to 4 inches will be possible over portions of the smaller
islands, mainly windward.

SURF: Swells generated by Tropical Storm Hone will move across
waters around the eastern end of the Hawaiian Islands on Saturday,
mainly near the Big Island of Hawaii. The large swells will spread
across the other portions of the island chain Saturday night and
Sunday, producing life-threatening surf and rip currents.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.

$$
Forecaster Jelsema

