
ZCZC HFOTCPCP1 ALL
TTAA00 PHFO DDHHMM

BULLETIN
Tropical Storm Hone Intermediate Advisory Number 10A
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
200 PM HST Sat Aug 24 2024

...TROPICAL STORM HONE STEADILY MOVING WESTWARD TOWARD HAWAII...
...TROPICAL STORM WARNING REMAINS IN EFFECT FOR THE BIG ISLAND...


SUMMARY OF 200 PM HST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...17.9N 153.7W
ABOUT 155 MI...350 KM SSE OF HILO HAWAII
ABOUT 355 MI...770 KM SE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning remains in effect for...
* Hawaii County

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in Hawaii should monitor the progress of Hone.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM HST (0000 UTC), the center of Tropical Storm Hone was
located near latitude 17.9 North, longitude 153.7 West. Hone is
moving toward the west near 15 mph (24 km/h) and this motion is
expected to continue for the next several days, gradually slowing
after the weekend.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts. A slight increase in strength is forecast during the next 48
hours. However, Hone is forecast to remain just below hurricane
strength at its peak Sunday through Monday.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the Tropical
Cyclone Discussion under AWIPS header TCDCP1 and WMO header WTPA41
PHFO, and on the web at hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical Storm conditions are expected on the Big Island,
beginning as early as this evening and continuing through early
Sunday. Winds are expected to be strongest downslope of higher
terrain, over headlands, and through passes.

RAINFALL: Hone is expected to produce storm total rainfall of 6 to
12 inches over mainly windward and southeast facing slopes of the
Big Island, with locally higher amounts possible. Rainfall totals
of 2 to 4 inches will be possible over portions of the smaller
islands, mainly windward.

SURF: Surf associated with large swells generated by Hone will
quickly build today through Sunday as Hone continues westward.
Expect dangerous conditions with life-threatening surf and rip
currents.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.

$$
Forecaster Powell

NNNN

