

000
WTPA31 PHFO 251434
TCPCP1

BULLETIN
Hurricane Hone Advisory Number  13
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
500 AM HST Sun Aug 25 2024

...HONE STRENGTHENS SLIGHTLY...
...TROPICAL STORM WARNING REMAINS IN EFFECT FOR THE BIG ISLAND...


SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...18.3N 156.1W
ABOUT 115 MI...190 KM SW OF HILO HAWAII
ABOUT 240 MI...385 KM SSE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning remains in effect for...
* Hawaii County

A Tropical Storm Warning means that tropical storm conditions are
imminent or occurring somewhere within the warning area.

Interests elsewhere in Hawaii should monitor the progress of Hone.

For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Hone was located 
near latitude 18.3 North, longitude 156.1 West. Hone is moving 
toward the west near 8 mph (13 km/h) and this motion is expected to 
continue through the middle of the week.

Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts. Little change in strength is expected through the morning 
hours today, before a gradual weakening trend begins this afternoon 
onward. 

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the Tropical
Cyclone Discussion under AWIPS header TCDCP1 and WMO header WTPA41
PHFO, and on the web at hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical Storm conditions will continue on the Big Island
through the morning hours. Winds are expected to be strongest
downslope of higher terrain, over headlands, and through passes.

RAINFALL: Hone is expected to produce storm total rainfall of 6 to
12 inches over mainly windward and southeast facing slopes of the
Big Island, with locally higher amounts possible. Rainfall totals
of 2 to 4 inches will be possible over portions of the smaller
islands, mainly windward.

SURF: Surf associated with large swells generated by Hone will
continue today as Hone tracks westward. Expect dangerous conditions 
with life-threatening surf and rip currents.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM HST.
Next complete advisory at 1100 AM HST.

$$
Forecaster Jelsema/Gibbs

