

058 
WTPA31 PHFO 252037
TCPCP1

BULLETIN
Hurricane Hone Advisory Number  14
NWS Central Pacific Hurricane Center Honolulu HI   CP012024
1100 AM HST Sun Aug 25 2024

...HONE GRADUALLY MOVING AWAY FROM THE BIG ISLAND BUT TROPICAL STORM
CONDITIONS CONTINUE...


SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.8N 157.3W
ABOUT 100 MI...165 KM SW OF KAILUA-KONA HAWAII
ABOUT 175 MI...285 KM SSE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Hawaii County

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.


For storm information specific to your area, please monitor
products issued by the National Weather Service office in
Honolulu Hawaii.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Hone was located
near latitude 18.8 North, longitude 157.3 West. Hone is moving
toward the west-northwest near 12 mph (19 km/h) and this motion is
expected to continue for the next few days.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts.  Some gradual weakening is forecast during the next couple 
of days.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure is 991 mb (29.27 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Hone can be found in the Tropical
Cyclone Discussion under AWIPS header TCDCP1 and WMO header WTPA41
PHFO, and on the web at hurricanes.gov/text/HFOTCDCP1.shtml.

WIND: Tropical Storm conditions will continue on the Big Island
into the early afternoon, with gradually diminishing wind and
rainfall through the evening. Winds will strongest downslope of
higher terrain, over headlands, and through passes.

RAINFALL: Hone is expected to produce an additional 3 to 5 inches
of rainfall over mainly windward and southeast facing slopes of the
Big Island. Additional rainfall of 1 to 3 inches will be possible
over the smaller islands, mainly windward.

SURF: Swells generated by Hone are affecting portions of the
Hawaiian islands, producing life-threatening surf and rip
current conditions.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM HST.
Next complete advisory at 500 PM HST.

$$
Forecaster Birchard


