

000
WTPZ34 KNHC 030848
TCPEP4

BULLETIN
Tropical Storm Bonnie Advisory Number  23
NWS National Hurricane Center Miami FL       EP042022
400 AM CDT Sun Jul 03 2022

...BONNIE EXPECTED TO STRENGTHEN...
...HEAVY RAINS ARE POSSIBLE ACROSS PARTS OF EL SALVADOR, GUATEMALA,
AND SOUTHERN MEXICO DURING THE NEXT COUPLE OF DAYS...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...11.6N 90.6W
ABOUT 160 MI...255 KM S OF PUERTO SAN JOSE GUATEMALA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests along the coasts of Guatemala and southern and 
southwestern Mexico should monitor the progress of this system.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Bonnie was 
located near latitude 11.6 North, longitude 90.6 West. Bonnie is 
moving toward the west near 16 mph (26 km/h).  A westward to 
west-northwestward motion should continue for the next several days.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Strengthening is forecast during the next couple of days, and 
Bonnie is expected to become a hurricane by Monday.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 997 mb (29.44 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Bonnie can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.

RAINFALL: Areas of heavy rainfall are possible during the next 
couple of days across portions of El Salvador, Guatemala, and 
southern and southwestern Mexico.  This rainfall could cause some 
instances of flash flooding and mudslides across the region.

SURF:  Swells generated by Bonnie will affect portions of the coasts 
of El Salvador, Guatemala, and southern and southwestern Mexico 
during the next couple of days.  These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Reinhart

