

817 
WTPZ34 KNHC 050242
TCPEP4

BULLETIN
Hurricane Bonnie Advisory Number  30
NWS National Hurricane Center Miami FL       EP042022
1000 PM CDT Mon Jul 04 2022

...BONNIE STRENGTHENS FURTHER...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.5N 101.4W
ABOUT 220 MI...355 KM S OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...974 MB...28.77 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the eye of Hurricane Bonnie was located 
near latitude 14.5 North, longitude 101.4 West. Bonnie is moving 
toward the west-northwest near 16 mph (26 km/h). A 
west-northwestward or westward motion with some decrease in forward 
speed is expected during the next few days. On the forecast track, 
the core of Bonnie is expected to move parallel to, but remain 
south of, the coasts of southern and southwestern Mexico during the 
next day or two.

Maximum sustained winds have increased to near 105 mph (165 km/h) 
with higher gusts.  Some additional strengthening is forecast
through tomorrow morning, followed by little change in intensity 
until Wednesday.  A gradual weakening trend is expected to begin 
thereafter.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure is 974 mb (28.77 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL: The outer rain bands of Bonnie could cause areas of heavy
rainfall during the next day or so across portions of southern
and southwestern Mexico.

SURF:  Swells generated by Bonnie will affect portions of the coasts
of southern and southwestern Mexico during the next couple of days.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.

$$
Forecaster Pasch/Bucci


