

015 
WTPZ34 KNHC 050841
TCPEP4

BULLETIN
Hurricane Bonnie Advisory Number  31
NWS National Hurricane Center Miami FL       EP042022
400 AM CDT Tue Jul 05 2022

...BONNIE CHANGES LITTLE IN STRENGTH OVER THE LAST SEVERAL HOURS...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.1N 103.2W
ABOUT 210 MI...335 KM SSW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...972 MB...28.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Hurricane Bonnie was located
near latitude 15.1 North, longitude 103.2 West. Bonnie is moving
toward the west-northwest near 17 mph (28 km/h).  A west- 
northwestward to westward motion with some decrease in forward speed 
is expected during the next few days.  On the forecast track, the 
core of Bonnie is expected to move parallel to, but remain south 
of, the coasts of southern and southwestern Mexico during the next 
day or two.

Maximum sustained winds are near 105 mph (165 km/h) with higher
gusts.  Some fluctuations in strength are possible through Thursday. 
A gradual weakening trend is expected to begin thereafter.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).

The estimated minimum central pressure is 972 mb (28.71 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL: The outer rain bands of Bonnie could cause areas of heavy
rainfall during the next day or so across portions of southern
and southwestern Mexico.

SURF:  Swells generated by Bonnie will affect portions of the coasts
of southern and southwestern Mexico during the next couple of days.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Beven


