

000
WTPZ34 KNHC 051433
TCPEP4

BULLETIN
Hurricane Bonnie Advisory Number  32
NWS National Hurricane Center Miami FL       EP042022
1000 AM CDT Tue Jul 05 2022

...BONNIE BECOMES A MAJOR HURRICANE...
...FIRST OF THE EASTERN NORTH PACIFIC SEASON...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.3N 104.3W
ABOUT 250 MI...400 KM SW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...964 MB...28.47 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Hurricane Bonnie was
located near latitude 15.3 North, longitude 104.3 West. Bonnie is
moving toward the west near 14 mph (22 km/h).  A westward to 
west-northwestward motion is forecast through the period with a 
slight decrease in forward speed during the next couple of days.  On 
the forecast track, the core of Bonnie is expected to move parallel 
to, but remain south of the coast of southwestern Mexico today.

Maximum sustained winds have increased to near 115 mph (185 km/h) 
with higher gusts.  Bonnie is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Some fluctuations in strength 
are possible through Thursday.  A gradual weakening trend is 
expected to begin thereafter.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 964 mb (28.47 inches).


HAZARDS AFFECTING LAND
---------------------- 
SURF:  Swells generated by Bonnie will affect portions of the coasts
of southern and southwestern Mexico during the next day or two.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Roberts

