
ZCZC MIATCPEP4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Hurricane Bonnie Advisory Number  33
NWS National Hurricane Center Miami FL       EP042022
400 PM CDT Tue Jul 05 2022

...LARGE SWELLS FROM BONNIE AFFECTING PORTIONS OF THE COAST OF
SOUTHWESTERN MEXICO...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...15.5N 105.7W
ABOUT 340 MI...545 KM S OF CABO CORRIENTES MEXICO
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...964 MB...28.47 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Hurricane Bonnie was located
near latitude 15.5 North, longitude 105.7 West.  Bonnie is moving
toward the west-northwest near 15 mph (24 km/h).  A westward to
west-northwestward motion is forecast through the period with a
slight decrease in forward speed during the next couple of days. 

Maximum sustained winds remain near 115 mph (185 km/h) with higher
gusts.  Bonnie is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Little change in strength is forecast 
tonight.  Gradual weakening is forecast to begin Wednesday or 
Wednesday night and continue through Thursday. 

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 964 mb (28.47 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Bonnie will continue to affect portions
of the coast of southwestern Mexico during the next day or so.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Brown

NNNN
