

000
WTPZ34 KNHC 060233
TCPEP4

BULLETIN
Hurricane Bonnie Advisory Number  34
NWS National Hurricane Center Miami FL       EP042022
900 PM MDT Tue Jul 05 2022

...BONNIE SENDS ROUGH SURF TO PORTIONS OF THE COAST OF SOUTHWESTERN
MEXICO...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...15.7N 107.1W
ABOUT 335 MI...545 KM SSW OF CABO CORRIENTES MEXICO
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Hurricane Bonnie was located
near latitude 15.7 North, longitude 107.1 West.  Bonnie is moving
toward the west-northwest near 15 mph (24 km/h).  A westward to
west-northwestward motion is forecast through the week with a
slight decrease in forward speed during the next couple of days.

Maximum sustained winds are near 110 mph (175 km/h) with higher
gusts.  Little change in strength is forecast tonight.  Gradual 
weakening is forecast to begin on Wednesday and continue through 
Thursday.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Bonnie will continue to affect portions
of the coast of southwestern Mexico during the next day or so.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Pasch/Bucci

