

496 
WTPZ34 KNHC 061446
TCPEP4

BULLETIN
Hurricane Bonnie Advisory Number  36
NWS National Hurricane Center Miami FL       EP042022
900 AM MDT Wed Jul 06 2022

...RESILIENT BONNIE RESTRENGTHENS...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...16.1N 109.0W
ABOUT 365 MI...585 KM SW OF CABO CORRIENTES MEXICO
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Hurricane Bonnie was located
near latitude 16.1 North, longitude 109.0 West. Bonnie is moving
a little slower toward the west near 12 mph (19 km/h).  A westward 
to west-northwestward motion is forecast through the week with an 
increase in forward speed beginning on Thursday.

Maximum sustained winds have increased to near 105 mph (165 km/h) 
with higher gusts.  Slight fluctuations in strength are possible 
today.  Gradual weakening is forecast to commence later tonight 
continue through Saturday.  Bonnie is expected to become a 
post-tropical cyclone in a few days.

Hurricane-force winds extend outward up to 10 miles (20 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 970 mb (28.65 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Bonnie will continue to affect portions
of the coast of southwestern Mexico through today. These swells 
are likely to cause life-threatening surf and rip current 
conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Roberts


