

000
WTPZ31 KNHC 020541
TCPEP1

BULLETIN
Tropical Depression Eleven-E Intermediate Advisory Number 2A
NWS National Hurricane Center Miami FL       EP112024
1200 AM CST Wed Oct 02 2024

...DEPRESSION LIKELY TO BRING HEAVY RAINFALL OVER PORTIONS 
OF WESTERN GUATEMALA AND SOUTHEASTERN MEXICO DURING THE NEXT COUPLE 
OF DAYS...


SUMMARY OF 1200 AM CST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.7N 94.7W
ABOUT 50 MI...75 KM SE OF SALINA CRUZ MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* East of Puerto Angel to Boca de Pijijiapan

A Tropical Storm Watch is in effect for...
* East of Boca de Pijijiapan to the Mexico/Guatemala Border

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 36 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM CST (0600 UTC), the center of Tropical Depression
Eleven-E was located near latitude 15.7 North, longitude 94.7 West.
The depression is moving toward the north near 6 mph (9 km/h) and
this general motion is expected to continue during the next day or 
two.  On the forecast track, the depression will likely move inland 
later today.

Maximum sustained winds remain near 35 mph (55 km/h) with higher
gusts.  Some slow strengthening is possible before the system
reaches the coast, and it could become a tropical storm this 
morning.  Weakening is expected after landfall.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Eleven-E can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1 and WMO
header WTPZ41 KNHC.

WIND:  Tropical storm conditions are expected to begin in the
warning later this morning and are possible in the watch area this 
afternoon.

RAINFALL: Tropical Depression Eleven-E is expected to produce 4 to 8
inches of rainfall, with localized amounts up to 12 inches, across
portions of western Guatemala and the Mexican states of Chiapas,
Oaxaca, Veracruz, and Tabasco. This rainfall may lead to areas of
flooding and mudslides.

For a complete depiction of forecast rainfall associated with
this system, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_ep1.shtml?rainqpf

SURF:  Swells generated by the depression are affecting portions of
the coast of southern and southeastern Mexico.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.

$$
Forecaster Pasch

