

018 
WTPZ31 KNHC 021132
TCPEP1

BULLETIN
Tropical Depression Eleven-E Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       EP112024
600 AM CST Wed Oct 02 2024

...POORLY ORGANIZED DEPRESSION MOVING SLOWLY SOUTH OF THE COAST 
OF MEXICO...


SUMMARY OF 600 AM CST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...15.3N 95.8W
ABOUT 55 MI...85 KM SE OF PUERTO ANGEL MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 5 MPH...8 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Lagunas de Chacahua to Boca de Pijijiapan

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within the next 36 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM CST (1200 UTC), the center of Tropical Depression Eleven-E
was located near latitude 15.3 North, longitude 95.8 West.  The
depression is moving toward the west-northwest near 5 mph (8 km/h),
and this general motion is expected to continue for the next day or
so.  On the forecast track, the center of the depression will be
near the coast of Mexico in the Tropical Storm Warning area late
tonight or early Thursday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Some strengthening is possible before the center reaches the
coast, and the system could become a tropical storm later today.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Eleven-E can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1 and WMO
header WTPZ41 KNHC.

WIND:  Tropical storm conditions are expected within the Tropical
Storm Warning area today and tonight.

RAINFALL: Tropical Depression Eleven-E is expected to produce 4 to 8
inches of rainfall, with localized amounts up to 12 inches, across
portions of western Guatemala and the Mexican states of Chiapas,
Oaxaca, Veracruz, and Tabasco. This rainfall may lead to areas of
flooding and mudslides.

For a complete depiction of forecast rainfall associated with
Tropical Depression Eleven-E, please see the National Weather
Service Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep1.shtml?rainqpf

SURF:  Swells generated by the depression are affecting portions of
the coast of southern and southeastern Mexico.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.

$$
Forecaster Beven


