

000
WTPZ31 KNHC 030239
TCPEP1

BULLETIN
Tropical Depression Eleven-E Advisory Number   6
NWS National Hurricane Center Miami FL       EP112024
900 PM CST Wed Oct 02 2024

...HEAVY RAINS EXPECTED TO CONTINUE IN PORTIONS OF SOUTHERN
MEXICO FOR ANOTHER DAY OR TWO...


SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 96.7W
ABOUT 105 MI...170 KM S OF PUERTO ANGEL MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...SW OR 235 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Lagunas de Chacahua to Boca de Pijijiapan

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within the next 36 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Tropical Depression Eleven-E
was located near latitude 14.2 North, longitude 96.7 West. The
depression is moving toward the southwest near 2 mph (4 km/h).  A 
turn to the north is expected on Thursday with that motion 
continuing through Friday.  On the forecast track, the system is 
expected to move toward southern Mexico and make landfall there 
Thursday night or Friday.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Gradual strengthening is possible until the system reaches the 
coast of Mexico.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Eleven-E can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1 and WMO
header WTPZ41 KNHC.

WIND:  Tropical storm conditions are expected within the Tropical
Storm Warning area late Thursday and Friday.

RAINFALL: Tropical Depression Eleven-E is expected to produce 4 to 8
inches of rainfall, with localized amounts up to 12 inches, across
portions of western Guatemala and the Mexican states of Chiapas,
Oaxaca, Veracruz, Tabasco and coastal Guerrero. This rainfall may
lead to areas of flooding and mudslides.

For a complete depiction of forecast rainfall associated with
Tropical Depression Eleven-E, please see the National Weather
Service Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep1.shtml?rainqpf

SURF:  Swells generated by the depression are affecting portions of
the coast of southern and southeastern Mexico.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM CST.
Next complete advisory at 300 AM CST.

$$
Forecaster Cangialosi

