

000
WTPZ31 KNHC 031132
TCPEP1

BULLETIN
Tropical Depression Eleven-E Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP112024
600 AM CST Thu Oct 03 2024

...CONTINUED HEAVY RAINS EXPECTED TO PRODUCE FLOODING AND MUDSLIDES
IN PORTIONS OF SOUTHERN MEXICO...
...TROPICAL STORM WARNING REMAINS IN EFFECT...


SUMMARY OF 600 AM CST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...15.0N 95.7W
ABOUT 70 MI...115 KM SSE OF PUERTO ANGEL MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 4 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Lagunas de Chacahua to Boca de Pijijiapan

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM CST (1200 UTC), the center of Tropical Depression Eleven-E
was located near latitude 15.0 North, longitude 95.7 West. The
depression is moving toward the northeast near 4 mph (6 km/h), and a
slightly faster northeastward to northward motion is forecast
through Friday. On the forecast track, the system is expected to
move toward southern Mexico and make landfall within the warning
area tonight or early Friday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Slight strengthening is possible, and the system is forecast
to be a tropical storm when it reaches the coast of Mexico.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Eleven-E can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1 and WMO
header WTPZ41 KNHC.

WIND:  Tropical storm conditions are expected within portions of
the warning area beginning later today and continuing into early
Friday.

RAINFALL: Tropical Depression Eleven-E is expected to produce 4 to 8
inches of rainfall, with localized amounts up to 12 inches, across
portions of western Guatemala and the Mexican states of Chiapas,
Oaxaca, Veracruz, Tabasco, and coastal Guerrero. This rainfall may
lead to areas of flooding and mudslides.

For a complete depiction of forecast rainfall associated with
Tropical Depression Eleven-E, please see the National Weather
Service Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep1.shtml?rainqpf

SURF:  Swells generated by the depression are affecting portions of
the coast of southern and southeastern Mexico. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.

$$
Forecaster Beven

