000
WTPZ32 KNHC 250238
TCPEP2
 
BULLETIN
Tropical Storm Genevieve Advisory Number   3
NWS National Hurricane Center Miami FL       EP072026
900 PM CST Fri Jul 24 2026
 
...GENEVIEVE FORECAST TO STRENGTHEN TO A MAJOR HURRICANE OVER THE
NEXT COUPLE OF DAYS...
 
 
SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...9.5N 102.6W
ABOUT 570 MI...920 KM S OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Tropical Storm Genevieve was
located near latitude 9.5 North, longitude 102.6 West. Genevieve is
moving toward the west-northwest near 12 mph (19 km/h). A 
west-northwestward to northwestward motion well offshore the coast 
of Mexico is expected during the next few days.
 
Maximum sustained winds have increased to near 50 mph (85 km/h) 
with higher gusts. Significant to rapid intensification is expected 
during the next few days. Genevieve is forecast to become a 
hurricane on Saturday and a major hurricane by late Sunday.
 
Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are expected to begin
affecting portions of the southwestern coast Mexico over the weekend
and will likely reach southern portions of the Baja California
peninsula on Monday. These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.
 
$$
Forecaster Berg
  