000
WTPZ32 KNHC 250833
TCPEP2
 
BULLETIN
Tropical Storm Genevieve Advisory Number   4
NWS National Hurricane Center Miami FL       EP072026
300 AM CST Sat Jul 25 2026
 
...GENEVIEVE MOVING WEST-NORTHWESTWARD WELL OFF OF THE COAST OF
MEXICO...
...FORECAST TO STRENGTHEN TO A MAJOR HURRICANE BY EARLY MONDAY...
 
 
SUMMARY OF 300 AM CST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...10.0N 103.6W
ABOUT 550 MI...880 KM SSW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM CST (0900 UTC), the center of Tropical Storm Genevieve was 
located near latitude 10.0 North, longitude 103.6 West. Genevieve is 
moving toward the west-northwest near 13 mph (20 km/h). A 
west-northwestward to northwestward motion well offshore of the 
coast of Mexico is expected during the next few days.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Significant to rapid intensification is expected during the next few 
days. Genevieve is forecast to become a hurricane tonight and a 
major hurricane by early Monday.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are expected to begin affecting 
portions of the southwestern coast Mexico over the weekend and will 
likely reach southern portions of the Baja California Peninsula on 
Monday. These swells are likely to cause life-threatening surf and 
rip current conditions.  Please consult products from your local 
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.
 
$$
Forecaster Beven
  