000
WTPZ32 KNHC 251433
TCPEP2
 
BULLETIN
Tropical Storm Genevieve Advisory Number   5
NWS National Hurricane Center Miami FL       EP072026
900 AM CST Sat Jul 25 2026
 
...GENEVIEVE FORECAST TO RAPIDLY INTENSIFY OVER THE NEXT COUPLE
OF DAYS...
 
 
SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...10.8N 104.3W
ABOUT 510 MI...820 KM SSW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Tropical Storm Genevieve was 
located near latitude 10.8 North, longitude 104.3 West. Genevieve is 
moving toward the west-northwest near 15 mph (24 km/h). A general 
west-northwestward to northwestward motion is expected during the 
next few days, keeping Genevieve well offshore of the coast of 
Mexico. 
 
Maximum sustained winds have increased to near 60 mph (95 km/h) with 
higher gusts. Rapid intensification is forecast during the next 
couple of days. Genevieve is forecast to become a hurricane by 
tonight and a major hurricane by Monday. 
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 997 mb (29.44 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are expected to begin affecting 
portions of the southwestern coast of Mexico starting this weekend 
and will likely reach southern portions of the Baja California 
Peninsula on Monday. These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 PM CST.
 
$$
Forecaster Papin
  