000
WTPZ32 KNHC 252035
TCPEP2
 
BULLETIN
Tropical Storm Genevieve Advisory Number   6
NWS National Hurricane Center Miami FL       EP072026
300 PM CST Sat Jul 25 2026
 
...GENEVIEVE NEARLY A HURRICANE AND FORECAST TO BECOME A
MAJOR HURRICANE BY EARLY NEXT WEEK...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...11.5N 105.7W
ABOUT 510 MI...820 KM SSW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Tropical Storm Genevieve was 
located near latitude 11.5 North, longitude 105.7 West. Genevieve is 
moving toward the west-northwest near 15 mph (24 km/h) and a general 
west-northwestward to northwestward motion is expected during the 
next few days, keeping Genevieve well offshore of the coast of 
Mexico.
 
Maximum sustained winds have increased to near 70 mph (110 km/h) 
with higher gusts. Rapid intensification is forecast during the next 
couple of days. Genevieve is forecast to become a hurricane tonight 
and a major hurricane by Monday. 
 
Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.
 
The estimated minimum central pressure is 993 mb (29.33 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are expected to begin affecting 
portions of the southwestern coast of Mexico starting this weekend 
and will likely reach southern portions of the Baja California 
Peninsula on Monday. These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.
 
$$
Forecaster Papin
  