000
WTPZ32 KNHC 260234
TCPEP2
 
BULLETIN
Hurricane Genevieve Advisory Number   7
NWS National Hurricane Center Miami FL       EP072026
800 PM MST Sat Jul 25 2026
 
...GENEVIEVE NOW A HURRICANE...
...FORECAST TO RAPIDLY INTENSIFY OVER THE NEXT DAY OR SO...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...12.1N 106.7W
ABOUT 500 MI...810 KM SSW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...987 MB...29.15 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Hurricane Genevieve was
located near latitude 12.1 North, longitude 106.7 West. Genevieve is
moving toward the west-northwest near 15 mph (24 km/h). A 
west-northwestward to northwestward motion with some decrease in 
forward speed is expected during the next few days.
 
Maximum sustained winds have increased to near 80 mph (130 km/h) 
with higher gusts.  Rapid intensification is expected during the 
next day or so, and Genevieve is forecast to become a major 
hurricane by late Sunday.
 
Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).
 
The estimated minimum central pressure is 987 mb (29.15 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are affecting portions of the
southwestern coast of Mexico and will likely reach southern portions
of the Baja California Peninsula Sunday night or Monday. These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Berg
  