196 
WTPZ32 KNHC 260850
TCPEP2
 
BULLETIN
Hurricane Genevieve Advisory Number   8
NWS National Hurricane Center Miami FL       EP072026
200 AM MST Sun Jul 26 2026
 
...GENEVIEVE RAPIDLY INTENSIFYING...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...12.9N 108.3W
ABOUT 500 MI...800 KM SSW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...980 MB...28.94 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Hurricane Genevieve was 
located near latitude 12.9 North, longitude 108.3 West. Genevieve is 
moving toward the west-northwest near 17 mph (28 km/h). A 
west-northwestward to northwestward motion with some decrease in 
forward speed is expected during the next few days.

Satellite images indicate that maximum sustained winds have 
increased to near 90 mph (150 km/h) with higher gusts. Continued 
rapid intensification is expected during the next day or so, and 
Genevieve is forecast to become a major hurricane by late today.
 
Recent satellite-derived wind data indicate that hurricane-force 
winds extend outward up to 40 miles (65 km) from the center and 
tropical-storm-force winds extend outward up to 195 miles (315 km).
 
The estimated minimum central pressure is 980 mb (28.94 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are affecting portions of the
southwestern coast of Mexico and will likely reach southern portions
of the Baja California Peninsula tonight or Monday. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM MST.
 
$$
Forecaster Hagen
  