000
WTPZ32 KNHC 262036
TCPEP2
 
BULLETIN
Hurricane Genevieve Advisory Number  10
NWS National Hurricane Center Miami FL       EP072026
200 PM MST Sun Jul 26 2026
 
...MAJOR HURRICANE GENEVIEVE CONTINUING TO RAPIDLY STRENGTHEN...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...13.9N 110.3W
ABOUT 530 MI...855 KM SW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...947 MB...27.97 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Hurricane Genevieve was 
located near latitude 13.9 North, longitude 110.3 West. Genevieve is 
moving toward the west-northwest near 14 mph (22 km/h). A 
west-northwestward to northwestward motion with some decrease in 
forward speed is expected during the next few days.
 
Maximum sustained winds have increased to near 140 mph (220 km/h) 
with higher gusts.  Genevieve is a category 4 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Continued strengthening is 
expected during the next day or so. Genevieve is then forecast to 
start weakening by the middle of this week.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).
 
The estimated minimum central pressure is 947 mb (27.97 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are affecting portions of the
southwestern coast of Mexico and will likely reach southern portions
of the Baja California Peninsula tonight or Monday. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Adams/Papin
  