000
WTPZ32 KNHC 270847
TCPEP2
 
BULLETIN
Hurricane Genevieve Advisory Number  12
NWS National Hurricane Center Miami FL       EP072026
200 AM MST Mon Jul 27 2026
 
...GENEVIEVE BECOMES THE FIRST CATEGORY 5 HURRICANE IN THE EAST
PACIFIC SINCE KRISTY OF 2024...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.5N 112.2W
ABOUT 530 MI...855 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...160 MPH...260 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...925 MB...27.32 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Hurricane Genevieve was 
located near latitude 15.5 North, longitude 112.2 West. Genevieve is 
moving toward the northwest near 13 mph (20 km/h). A 
west-northwestward to northwestward motion with some decrease in 
forward speed is expected during the next couple of days.
 
Maximum sustained winds have increased to near 160 mph (260 km/h) 
with higher gusts. Genevieve is a powerful category 5 hurricane on 
the Saffir-Simpson Hurricane Wind Scale. Fluctuations in intensity 
are likely today. Steady weakening is forecast Tuesday through the 
remainder of the week.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).
 
The estimated minimum central pressure is 925 mb (27.32 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Genevieve are affecting portions of the
southwestern coast of Mexico and southern portions of the Baja
California Peninsula, and will spread northward along the remainder
of the west coast of the Baja California Peninsula by tonight. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM MST.
 
$$
Forecaster Hagen
  