000
WTPZ32 KNHC 300242
TCPEP2
 
BULLETIN
Hurricane Genevieve Advisory Number  24
NWS National Hurricane Center Miami FL       EP072026
500 PM HST Wed Jul 29 2026
 
...GENEVIEVE EXPECTED TO GRADUALLY WEAKEN OVER THE NEXT FEW DAYS...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...19.6N 120.8W
ABOUT 735 MI...1185 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Hurricane Genevieve was
located near latitude 19.6 North, longitude 120.8 West.  Genevieve 
is moving toward the west-northwest near 9 mph (15 km/h).  This 
general motion with a slight increase in forward speed is expected 
during the next several days.

Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts.  Gradual weakening is forecast during the next few days, and 
Genevieve is expected to become post-tropical this weekend.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The estimated minimum central pressure is 970 mb (28.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Genevieve are affecting portions of the
Baja California Peninsula and Southern California.  These swells
will persist for the next several days, and are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Pasch
  