

000
WTPZ32 KNHC 181453
TCPEP2

BULLETIN
Tropical Storm Norma Advisory Number   4
NWS National Hurricane Center Miami FL       EP172023
900 AM MDT Wed Oct 18 2023

...NORMA FORECAST TO RAPIDLY STRENGTHEN...
...EXPECTED TO BECOME A HURRICANE SOON...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...14.8N 107.9W
ABOUT 375 MI...605 KM SW OF MANZANILLO MEXICO
ABOUT 575 MI...925 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Baja California Sur should monitor the progress of
Norma.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Norma was 
located near latitude 14.8 North, longitude 107.9 West. Norma is 
moving toward the north-northwest near 7 mph (11 km/h). A 
north-northwestward to northward motion at a similar forward speed 
is expected during the next few days.

Maximum sustained winds are near 70 mph (110 km/h) with higher 
gusts. Rapid strengthening is forecast during the next day or so, 
and Norma is expected to become a hurricane later today. Gradual 
weakening is forecast by late this week.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 991 mb (29.27 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

SURF:  Swells generated by Norma will begin to affect portions of
the coast of southwestern Mexico today. These swells will spread
northward along the coast of western Mexico and toward Baja
California Sur during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Reinhart

