
ZCZC MIATCPEP2 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Hurricane Norma Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP172023
600 AM MDT Thu Oct 19 2023

...MAJOR HURRICANE NORMA MOVING NORTHWARD...
...HEAVY RAINFALL AND FLOODING EXPECTED ACROSS SOUTHERN PORTIONS 
OF BAJA CALIFORNIA SUR THROUGH THE WEEKEND...


SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...17.0N 107.5W
ABOUT 255 MI...410 KM WSW OF MANZANILLO MEXICO
ABOUT 430 MI...690 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...950 MB...28.05 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Baja California peninsula from Todos Santos to Los Barriles

A Hurricane Watch means that hurricane conditions are possible 
within the watch area. A watch is typically issued 48 hours before 
the anticipated first occurrence of tropical-storm-force winds, 
conditions that make outside preparations difficult or dangerous.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the center of Hurricane Norma was located 
near latitude 17.0 North, longitude 107.5 West. Norma is moving 
toward the north near 6 mph (9 km/h). A northward to 
north-northwestward motion at a similar forward speed is expected 
for the next couple of days. A slower motion is forecast by the 
weekend. On the forecast track, Norma is forecast to approach the 
southern portion of Baja California on Saturday.

Maximum sustained winds have increased to near 125 mph (205 km/h) 
with higher gusts. Norma is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Additional strengthening is 
possible today, followed by gradual weakening beginning Friday and 
continuing into the weekend.

Hurricane-force winds extend outward up to 25 miles (35 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).

The estimated minimum central pressure is 950 mb (28.05 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

WIND:  Hurricane conditions are possible within the watch area as
early as Saturday morning.

RAINFALL: Norma is expected to produce rainfall totals of 5 to 10
inches with local maxima of 15 inches through Sunday across the far
southern portion of the Mexican state of Baja California Sur.
These rains will likely produce flash and urban flooding, along
with possible mudslides in areas of high terrain.

SURF:  Swells generated by Norma are affecting portions of the coast
of southwestern Mexico, and will spread northward along the coast of
western Mexico and toward Baja California Sur during the next couple
of days. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Reinhart

NNNN
