

000
WTPZ32 KNHC 191451
TCPEP2

BULLETIN
Hurricane Norma Advisory Number   8
NWS National Hurricane Center Miami FL       EP172023
900 AM MDT Thu Oct 19 2023

...AIR FORCE HURRICANE HUNTERS TO INVESTIGATE MAJOR HURRICANE
NORMA LATER TODAY...
...HEAVY RAINFALL AND FLOODING EXPECTED ACROSS SOUTHERN PORTIONS
OF BAJA CALIFORNIA SUR THROUGH THE WEEKEND...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 107.6W
ABOUT 245 MI...390 KM WSW OF MANZANILLO MEXICO
ABOUT 410 MI...655 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...946 MB...27.94 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Baja California peninsula from Todos Santos to Los Barriles

A Hurricane Watch means that hurricane conditions are possible
within the watch area. A watch is typically issued 48 hours before
the anticipated first occurrence of tropical-storm-force winds,
conditions that make outside preparations difficult or dangerous.

Interests elsewhere in Baja California Sur and along the west coast
of mainland Mexico should monitor the progress of Norma. Additional
watches or warnings could be required later today or tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Hurricane Norma was located 
near latitude 17.4 North, longitude 107.6 West. Norma is moving 
toward the north near 7 mph (11 km/h). A northward to 
north-northwestward motion at a similar forward speed is expected 
for the next couple of days. A slower northward to northeastward 
motion is forecast over the weekend. On the forecast track, Norma is 
forecast to approach the southern portion of Baja California on 
Friday night and Saturday.

Maximum sustained winds are near 130 mph (215 km/h) with higher 
gusts. Norma is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Small intensity fluctuations are possible 
today, followed by gradual weakening beginning Friday and continuing 
into the weekend.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).

The estimated minimum central pressure is 946 mb (27.94 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

WIND:  Hurricane and tropical storm conditions are possible within 
the watch area by early Saturday.

RAINFALL: Norma is expected to produce rainfall totals of 5 to 10
inches with local maxima of 15 inches through Sunday across the far
southern portion of the Mexican state of Baja California Sur. These
rains will likely produce flash and urban flooding, along with
possible mudslides in areas of higher terrain.

SURF:  Swells generated by Norma are affecting portions of the coast
of southwestern Mexico, and will spread northward along the coast of
western Mexico and toward Baja California Sur during the next couple
of days. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM MDT.
Next complete advisory at 300 PM MDT.

$$
Forecaster Reinhart

