

000
WTPZ32 KNHC 191756
TCPEP2

BULLETIN
Hurricane Norma Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       EP172023
1200 PM MDT Thu Oct 19 2023

...AIR FORCE HURRICANE HUNTERS CURRENTLY INVESTIGATING NORMA...
...TROPICAL STORM WATCH ISSUED FOR LAS ISLAS MARIAS...


SUMMARY OF 1200 PM MDT...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.3N 108.0W
ABOUT 270 MI...435 KM WSW OF MANZANILLO MEXICO
ABOUT 405 MI...650 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...N OR 355 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...941 MB...27.79 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Tropical Storm Watch for Las 
Islas Marias.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Baja California peninsula from Todos Santos to Los Barriles

A Tropical Storm Watch is in effect for...
* Las Islas Marias

A Hurricane Watch means that hurricane conditions are possible
within the watch area. A watch is typically issued 48 hours before
the anticipated first occurrence of tropical-storm-force winds,
conditions that make outside preparations difficult or dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in Baja California Sur and along the west coast
of mainland Mexico should monitor the progress of Norma. Additional
watches or warnings could be required later today or tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 PM MDT (1800 UTC), the center of Hurricane Norma was located
near latitude 17.3 North, longitude 108.0 West. Norma is moving
toward the north near 7 mph (11 km/h). A northward to
north-northwestward motion at a similar forward speed is expected
for the next couple of days. A slower northward to northeastward
motion is forecast over the weekend. On the forecast track, Norma is
forecast to approach the southern portion of Baja California on
Friday night and Saturday.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts. Norma is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Small intensity fluctuations are possible
today, followed by gradual weakening beginning Friday and continuing
into the weekend.

Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).

The estimated minimum central pressure based on Air Force Reserve 
Hurricane Hunter dropsonde data is 941 mb (27.79 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

WIND:  Hurricane and tropical storm conditions are possible within
the watch area in Baja California Sur by early Saturday. Tropical 
storm conditions are possible in Las Islas Marias Friday and Friday 
night.

RAINFALL: Norma is expected to produce rainfall totals of 5 to 10
inches with local maxima of 15 inches through Sunday across the far
southern portion of the Mexican state of Baja California Sur. These
rains will likely produce flash and urban flooding, along with
possible mudslides in areas of higher terrain.

SURF:  Swells generated by Norma are affecting portions of the coast
of southwestern Mexico and Baja California Sur, and will spread 
northward along the coast of western Mexico during the next couple
of days. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Reinhart

