

000
WTPZ32 KNHC 200554
TCPEP2

BULLETIN
Hurricane Norma Intermediate Advisory Number 10A
NWS National Hurricane Center Miami FL       EP172023
1200 AM MDT Fri Oct 20 2023

...NORMA EXPECTED TO BRING HEAVY RAINFALL AND FLOODING TO SOUTHERN
BAJA CALIFORNIA SUR DURING THE NEXT FEW DAYS...
...TROPICAL STORM CONDITIONS ARE EXPECTED LATER TONIGHT...


SUMMARY OF 1200 AM MDT...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.3N 108.3W
ABOUT 265 MI...430 KM W OF MANZANILLO MEXICO
ABOUT 335 MI...540 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...948 MB...28.00 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Baja California Sur from Todos Santos to Los Barriles

A Tropical Storm Watch is in effect for...
* North of Los Barriles to La Paz
* North of Todos Santos to Santa Fe
* Las Islas Marias

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued 36
hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in Baja California Sur and along the west coast
of mainland Mexico should monitor the progress of Norma.  Additional
watches or warnings could be required today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM MDT (0600 UTC), the center of Hurricane Norma was located
near latitude 18.3 North, longitude 108.3 West. Norma is moving
toward the north near 7 mph (11 km/h).  A turn to the
north-northwest at a similar forward speed is expected later today 
or tonight.  A slower northward to northeastward motion is forecast 
this weekend.  On the forecast track, Norma is forecast to approach 
the southern portion of Baja California Sur tonight and Saturday.

Maximum sustained winds are near 120 mph (195 km/h) with higher
gusts.  Norma is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Some weakening is expected during the next
few days, but Norma is forecast to be a hurricane when it moves near
the southern portion of Baja California Sur.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).

The estimated minimum central pressure is 948 mb (28.00 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

WIND:  Hurricane conditions are expected within the warning area in
Baja California Sur by early Saturday, with tropical storm
conditions beginning late tonight.  Tropical storm conditions
are possible in Las Islas Marias today and tonight, and in the
watch areas in Baja California Sur on Saturday.

RAINFALL:  Norma is likely to produce rainfall totals of 5 to 10
inches with local maxima of 15 inches through Sunday across the far
southern portion of Baja California Sur.  These rains will likely
produce flash and urban flooding, along with possible mudslides in
areas of higher terrain.

STORM SURGE:  A storm surge could produce coastal flooding in areas
of onshore winds within the hurricane warning area.  Near the
coast, the surge will be accompanied by large and destructive waves.

SURF:  Swells generated by Norma are affecting portions of the coast
of southwestern Mexico and Baja California Sur, and will spread
northward along the coast of western Mexico and the Baja California
peninsula during the next couple of days.  These swells are likely
to cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Roberts

