

000
WTPZ32 KNHC 201457
TCPEP2

BULLETIN
Hurricane Norma Advisory Number  12
NWS National Hurricane Center Miami FL       EP172023
900 AM MDT Fri Oct 20 2023

...HEAVY RAINS AND FLASH FLOODING EXPECTED IN SOUTHERN BAJA
CALIFORNIA SUR DURING THE NEXT FEW DAYS...
...TROPICAL STORM WATCH ISSUED FOR A PORTION OF THE WEST COAST OF
MEXICO...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...19.4N 109.2W
ABOUT 245 MI...395 KM S OF CABO SAN LUCAS MEXICO
ABOUT 320 MI...515 KM W OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has extended the Tropical Storm Warning
from La Paz northward to San Evaristo along the east coast of the
Baja California peninsula. The government of Mexico has also issued
a Tropical Storm Watch for the west coast of mainland Mexico from
Topolobampo to Bahia Tempehuaya.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Baja California Sur from Todos Santos to Los Barriles

A Tropical Storm Warning is in effect for...
* North of Los Barriles to San Evaristo
* North of Todos Santos to Santa Fe

A Tropical Storm Watch is in effect for...
* Las Islas Marias
* Topolobampo to Bahia Tempehuaya

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. A warning is typically issued 36
hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous. Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in Baja California Sur and along the west coast
of mainland Mexico should monitor the progress of Norma. Additional
watches or warnings could be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Hurricane Norma was located 
near latitude 19.4 North, longitude 109.2 West. Norma is moving 
toward the north-northwest near 8 mph (13 km/h). A 
north-northwestward to northward motion is forecast through 
Saturday, followed by a turn toward the northeast on Sunday. On the 
forecast track, Norma is expected to approach the southern portion 
of Baja California Sur tonight and move near or over the area on 
Saturday. Norma is forecast to move toward the west coast of 
mainland Mexico on Sunday and Sunday night.

Maximum sustained winds have decreased to near 110 mph (175 km/h)
with higher gusts. Gradual weakening is expected during the next
few days, but Norma is forecast to be a hurricane when it moves
near or over the southern portion of Baja California Sur.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 175 miles
(280 km).

The estimated minimum central pressure is 960 mb (28.35 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

WIND:  Hurricane conditions are expected within the hurricane
warning area in Baja California Sur on Saturday, with tropical
storm conditions beginning late tonight. Tropical storm conditions
are expected in the tropical storm warning areas in Baja California
Sur on Saturday. Tropical storm conditions are possible in Las
Islas Marias today and tonight, and in the watch area along the
west coast of Mexico by Sunday.

RAINFALL:  Norma is likely to produce rainfall totals of 5 to 10
inches with local maxima of 15 inches across the far southern
portion of Baja California Sur through Sunday and across portions of
Sinaloa through Monday. These rains will likely produce flash and
urban flooding, along with possible mudslides in areas of higher
terrain.

STORM SURGE:  A storm surge could produce coastal flooding in areas
of onshore winds within the hurricane warning area. Near the
coast, the surge will be accompanied by large and destructive waves.

SURF:  Swells generated by Norma are affecting portions of the coast
of southwestern and west-central Mexico and Baja California Sur.
These swells will spread northward along the coast of western Mexico
and the Baja California peninsula this weekend. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM MDT.
Next complete advisory at 300 PM MDT.

$$
Forecaster Reinhart

