

000
WTPZ32 KNHC 230551
TCPEP2

BULLETIN
Tropical Storm Norma Intermediate Advisory Number 22A
NWS National Hurricane Center Miami FL       EP172023
1200 AM MDT Mon Oct 23 2023

...NORMA TAKES A SOUTHEASTWARD JOG AS IT NEARS THE COAST OF 
MAINLAND MEXICO...
...RAINFALL CONTINUES OVER PORTIONS OF WESTERN MAINLAND MEXICO...


SUMMARY OF 1200 AM MDT...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.6N 108.8W
ABOUT 85 MI...135 KM W OF CULIACAN MEXICO
ABOUT 85 MI...135 KM S OF LOS MOCHIS MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...E OR 100 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.35 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Huatabampito to Mazatlan

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM MDT (0600 UTC), the center of Tropical Storm Norma was 
located near latitude 24.6 North, longitude 108.8 West. Norma has 
moved southeastward during the past several hours, but an eastward 
motion near 5 mph (7 km/h) is expected to resume later this morning. 
On the forecast track, the center of Norma is forecast to approach 
the west coast of mainland Mexico overnight and move inland within 
the tropical storm warning area later this morning.

Recently received satellite wind data indicate that the maximum 
sustained winds have decreased to near 45 mph (75 km/h) with higher 
gusts. Norma is expected to move over the west coast of mainland 
Mexico as a tropical storm later this morning. Rapid weakening is 
anticipated once Norma moves inland over mainland Mexico.

Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.

The estimated minimum central pressure is 994 mb (29.35 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Norma can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/MIATCDEP2.shtml

WIND:  Tropical storm conditions are ongoing within portions of the
tropical storm warning area.

RAINFALL:  Norma will produce additional rainfall totals of 4 to 6 
inches with storm total maxima of 18 inches in and near Sinaloa 
through today.  These rains will produce flash and urban flooding, 
along with mudslides in areas of higher terrain.

STORM SURGE:  Coastal flooding is possible along the west coast of 
mainland Mexico within the tropical storm warning area. Near the 
coast, the coastal flooding will be accompanied by large and 
dangerous waves.

SURF:  Swells generated by Norma will continue to affect the coast 
of southwestern and west-central Mexico and Baja California Sur for 
the next day or two. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Brown

