

000
WTPA31 PHFO 152032
TCPCP1

BULLETIN
Tropical Storm Darby Advisory Number  26
NWS Central Pacific Hurricane Center Honolulu HI   EP052022
1100 AM HST Fri Jul 15 2022

...WEST-MOVING DARBY CONTINUES TO WEAKEN EAST-SOUTHEAST OF
HAWAII...


SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.6N 147.7W
ABOUT 505 MI...815 KM ESE OF HILO HAWAII
ABOUT 710 MI...1145 KM ESE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Tropical Storm Darby was
located near latitude 17.6 North, longitude 147.7 West. Darby is
moving toward the west near 20 mph (31 km/h) and this motion is
expected to continue over the next couple of days. The forecast 
track brings the center of Darby, or its remnant, south of the 
Big Island on Saturday. 

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Darby is expected to continue to weaken, to a tropical depression 
Friday night, then become a post-tropical cyclone Saturday before 
dissipating by Sunday night.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Large swells generated by Darby are expected to affect
portions of the Hawaiian Islands over the weekend. These swells are
likely to produce hazardous surf and dangerous rip current
conditions. Please consult products from your local National
Weather Service office in Honolulu, Hawaii for further details.

RAINFALL: Darby is expected to produce localized storm total
rainfall of up to 2 to 4 inches along portions of mainly windward
Big Island and windward Maui. These rains may cause nuisance
flooding especially in low-lying and poor drainage areas.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.

$$
Forecaster M Ballard/R Ballard

