

000
WTPA31 PHFO 170231
TCPCP1

BULLETIN
Remnants of Darby Advisory Number  31
NWS Central Pacific Hurricane Center Honolulu HI   EP052022
500 PM HST Sat Jul 16 2022

...DARBY NO LONGER A TROPICAL CYCLONE...
...THIS IS THE LAST ADVISORY...


SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...17.7N 157.5W
ABOUT 210 MI...335 KM SW OF HILO HAWAII
ABOUT 250 MI...400 KM S OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the remnants of Darby were
located near latitude 17.7 North, longitude 157.5 West. The 
remnants are moving toward the west near 22 mph (35 km/h) and this 
motion is expected to continue for another day or so.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Weakening is forecast over the next 24 hours.

Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.

The estimated minimum central pressure is 1007 mb (29.74 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Large swells generated by Darby are expected to affect
portions of the Hawaiian Islands over the weekend. These swells are
likely to produce hazardous surf and dangerous rip currents. Please
consult products from your local National Weather Service office in
Honolulu, Hawaii for further details.

RAINFALL: Darby is expected to produce localized storm total
rainfall of 1 to 3 inches along portions of windward Big Island.
These rains may cause minor flooding especially in low-lying and
poor drainage areas.


NEXT ADVISORY
-------------
This is the last public advisory issued by the Central Pacific
Hurricane Center on Darby. Additional information on the
remnants of Darby can be found in high seas forecasts issued by the
National Weather Service under AWIPS head HFOHSFNP, WMO header
FZPN40 PHFO, and on the web at https://www.weather.gov/hfo/HSFNP

$$
Forecaster Kodama

