

000
WTNT35 KNHC 200237
TCPAT5

BULLETIN
Hurricane Nigel Advisory Number  19
NWS National Hurricane Center Miami FL       AL152023
1100 PM AST Tue Sep 19 2023

...NIGEL TURNS NORTHWARD...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...33.2N 54.7W
ABOUT 590 MI...950 KM E OF BERMUDA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...N OR 355 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...971 MB...28.68 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Nigel was located 
near latitude 33.2 North, longitude 54.7 West. Nigel is moving 
toward the north near 15 mph (24 km/h).  A turn toward the northeast 
with an increase in forward speed is expected on Wednesday.

Maximum sustained winds are near 100 mph (155 km/h) with higher 
gusts.  Some additional strengthening is possible through early 
Wednesday. Weakening is expected on Thursday and Friday. Nigel is 
forecast to become a strong post-tropical cyclone by Friday.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 175 miles
(280 km).

The estimated minimum central pressure is 971 mb (28.68 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Nigel will affect Bermuda during the next
couple of days. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Bucci

