

881 
WTNT35 KNHC 202037
TCPAT5

BULLETIN
Hurricane Nigel Advisory Number  22
NWS National Hurricane Center Miami FL       AL152023
500 PM AST Wed Sep 20 2023

...NIGEL MOVING NORTH-NORTHEASTWARD...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...37.4N 53.0W
ABOUT 755 MI...1215 KM ENE OF BERMUDA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Nigel was located
near latitude 37.4 North, longitude 53.0 West.  Nigel is moving
toward the north-northeast near 18 mph (30 km/h).  A turn toward 
the northeast with an increase in forward speed is expected 
tonight, followed by a faster northeastward motion over the next day 
or two.

Maximum sustained winds are near 90 mph (150 km/h) with higher
gusts.  Weakening is forecast during the next couple of days,
and Nigel is forecast to become a post-tropical cyclone by
Friday.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).

The estimated minimum central pressure is 973 mb (28.74 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Nigel will affect Bermuda during the next
couple of days.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Pasch


