

000
WTNT35 KNHC 210236
TCPAT5

BULLETIN
Hurricane Nigel Advisory Number  23
NWS National Hurricane Center Miami FL       AL152023
1100 PM AST Wed Sep 20 2023

...NIGEL ACCELERATES NORTHEASTWARD...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...39.0N 50.4W
ABOUT 550 MI...885 KM SSE OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 25 MPH...41 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Nigel was located
near latitude 39.0 North, longitude 50.4 West. Nigel is moving
toward the northeast near 25 mph (41 km/h) and is expected to
accelerate northeastward over the next day or two.

Maximum sustained winds are near 90 mph (150 km/h) with higher
gusts.  Weakening is forecast during the next couple of days, and
Nigel is forecast to become a post-tropical cyclone by Friday.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).

The estimated minimum central pressure is 973 mb (28.74 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Nigel currently affecting Bermuda will
gradually subside through Thursday.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Bucci

