

000
WTNT35 KNHC 210839
TCPAT5

BULLETIN
Hurricane Nigel Advisory Number  24
NWS National Hurricane Center Miami FL       AL152023
500 AM AST Thu Sep 21 2023

...NIGEL MOVING QUICKLY NORTHEASTWARD...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...40.6N 47.8W
ABOUT 495 MI...800 KM SE OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NE OR 50 DEGREES AT 30 MPH...48 KM/H
MINIMUM CENTRAL PRESSURE...977 MB...28.85 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Nigel was located
near latitude 40.6 North, longitude 47.8 West. Nigel is moving
toward the northeast near 30 mph (48 km/h) and this motion is
expected to continue the next day or two.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts. Weakening is forecast during the next couple of days, and
Nigel is forecast to become a post-tropical cyclone by Friday.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).

The estimated minimum central pressure is 977 mb (28.85 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Nigel currently affecting Bermuda will
gradually subside through tonight.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Kelly

