

000
WTNT31 KNHC 031442
TCPAT1

BULLETIN
Hurricane Martin Advisory Number   9
NWS National Hurricane Center Miami FL       AL162022
300 PM GMT Thu Nov 03 2022

...LARGE AND POWERFUL MARTIN FORECAST TO BECOME POST-TROPICAL OVER
THE CENTRAL NORTH ATLANTIC WITHIN THE NEXT FEW HOURS...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...45.6N 37.9W
ABOUT 765 MI...1235 KM NW OF THE AZORES
ABOUT 730 MI...1175 KM E OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 48 MPH...78 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Hurricane Martin was located
near latitude 45.6 North, longitude 37.9 West. Martin is moving
toward the northeast near 48 mph (78 km/h). A turn toward the north 
at a slightly slower forward speed is expected this evening. 
Martin's forward motion is forecast to slow down substantially on 
Friday. A general east to east-southeastward motion is then 
forecast by Friday night, which will likely continue through the 
weekend.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts. Martin is forecast to become a very powerful post-tropical 
cyclone within the next few hours. Martin's peak sustained winds 
will likely begin to decrease on Friday, but it will continue to 
produce strong winds over a very large area well into the weekend.

Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 520
miles (835 km).

The estimated minimum central pressure is 960 mb (28.35 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Martin when it become a post-tropical
cyclone will likely spread across a large portion of the
high-latitude North Atlantic basin, affecting portions of Atlantic
Canada, the Azores, and the Atlantic coast of Europe by the weekend.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products form your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster D. Zelinsky

