

000
WTNT31 KNHC 032032
TCPAT1

BULLETIN
Post-Tropical Cyclone Martin Advisory Number  10
NWS National Hurricane Center Miami FL       AL162022
900 PM GMT Thu Nov 03 2022

...POST-TROPICAL MARTIN CAUSING STRONG WINDS AND HAZARDOUS SEAS
ACROSS A LARGE PORTION OF THE CENTRAL NORTH ATLANTIC...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...50.5N 34.5W
ABOUT 940 MI...1510 KM NNW OF THE AZORES
ABOUT 885 MI...1425 KM ENE OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NNE OR 20 DEGREES AT 58 MPH...93 KM/H
MINIMUM CENTRAL PRESSURE...950 MB...28.06 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Post-Tropical Cyclone Martin
was located near latitude 50.5 North, longitude 34.5 West. The
post-tropical cyclone is moving toward the north-northeast near 58
mph (93 km/h). A slower northward to north-northwestward motion is 
expected tonight, followed by a much slower turn toward the east on 
Friday. An eastward to east-southeastward motion is then 
anticipated into the weekend.

Maximum sustained winds are near 80 mph (130 km/h) with higher 
gusts.  Martin's peak sustained winds will slowly decrease over the 
next few days, but it will continue to produce strong winds over a 
very large area well into the weekend.

Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 520
miles (835 km).

The estimated minimum central pressure is 950 mb (28.06 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by post-tropical Martin will likely spread 
across a large portion of the high-latitude North Atlantic basin, 
affecting portions of Atlantic Canada, the Azores, and the Atlantic 
coast of Europe by the weekend. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on this system. Additional information on this system can be 
found in High Seas Forecasts issued by the National Weather Service, 
Meteo France, and the UK Met Office. National Weather Service 
forecasts are available under AWIPS header NFDHSFAT1, WMO header 
FZNT01 KWBC, and online at ocean.weather.gov/shtml/NFDHSFAT1.php 
High Seas Forecasts issued by Meteo France can be found under WMO 
header FQNT50 LFPW and are available on the web at 
www.meteofrance.com/previsions-meteo-marine/bulletin/grandlarge/ 
metarea2. High Seas Forecasts issued by the UK Met Office can be 
found under WMO header FQNT21 EGRR and on the web at 
metoffice.gov.uk/weather/specialist-forecasts/coast-and-sea/high- 
seas-forecast/.

$$
Forecaster D. Zelinsky

