000
WTNT31 KNHC 171630
TCPAT1
 
BULLETIN
Tropical Storm Arthur Special Advisory Number   6
NWS National Hurricane Center Miami FL       AL012026
1130 AM CDT Wed Jun 17 2026
 
...TROPICAL STORM WARNING EXTENDED SOUTHWARD...
...LIFE-THREATENING FLOODING EXPECTED ACROSS PORTIONS OF THE
SOUTHEASTERN UNITED STATES...
 
 
SUMMARY OF 1130 AM CDT...1630 UTC...INFORMATION
-----------------------------------------------
LOCATION...28.8N 95.5W
ABOUT 60 MI...100 KM ENE OF PORT OCONNOR TEXAS
ABOUT 165 MI...265 KM WSW OF LAKE CHARLES LOUISIANA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Tropical Storm Warning has been extended southward to Sargent,
Texas.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Sargent, Texas to Morgan City, Louisiana
 
A Tropical Storm Warning means that tropical storm conditions are
expected within the warning area.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1130 AM CDT (1630 UTC), the center of Tropical Storm Arthur was
located near latitude 28.8 North, longitude 95.5 West. Arthur is
moving toward the northeast near 9 mph (15 km/h), and an increase in
forward speed is expected today. On the forecast track, the low
pressure area should move northeastward along the Texas coast today
and then move inland over southwestern Louisiana by tonight.
 
Surface observations indicate maximum sustained winds have increased 
to near 45 mph (75 km/h) with higher gusts. Weakening is anticipated 
once the low moves inland, and it could dissipate by tonight or 
early Thursday.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center. NOAA buoy 42035 east of Galveston recently reported
a sustained wind of 45 mph (72 km/h) and a gust of 52 mph (83 km/h).
 
The minimum central pressure based on surface observations is 999 
mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Arthur can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT1 and WMO header
WTNT41 KNHC.
 
RAINFALL: Tropical Storm Arthur is expected to produce rainfall
totals of 5 to 10 inches, with isolated higher totals near 20
inches, through early Friday from the Mid and Upper Texas coast
east-northeast into southern and central portions of Louisiana,
Mississippi, and Alabama, along with western portions of Georgia and
the Florida Panhandle. This could generate dangerous to
life-threatening flash flooding.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Arthur, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_at1.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at1.shtml?ero.
 
For a list of rainfall observations (and wind reports) associated
with Tropical Storm Arthur, see the companion storm summary at
WBCSCCNS1 with the WMO header ACUS44 KWBC or at the following link:
www.wpc.ncep.noaa.gov/discussions/nfdscc1.html.
 
WIND: Tropical storm conditions are expected within the warning area
today.
 
STORM SURGE: The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline. The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Port Bolivar, TX to Morgan City, LA...2-4 ft
 
The deepest water will occur along the immediate coast near and to
the east of the landfall location, where the surge will be
accompanied by large and dangerous waves. Surge-related flooding
depends on the relative timing of the surge and the tidal cycle,
and can vary greatly over short distances. For information
specific to your area, please see products issued by your local
National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at1.shtml?peakSurge.
 
SURF:  Swells generated by Arthur are likely to cause
life-threatening surf and rip current conditions along the
northwestern Gulf Coast for the next couple of days. Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at1.shtml?ripCurrents
 
TORNADO: A couple of tornadoes are possible through Thursday from
the Upper Texas Coast into southern Louisiana, Mississippi, Alabama,
and the western Florida Panhandle.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.
 
$$
Forecaster Reinhart
  