000
WTNT31 KNHC 172052
TCPAT1
 
BULLETIN
Tropical Storm Arthur Advisory Number   7
NWS National Hurricane Center Miami FL       AL012026
400 PM CDT Wed Jun 17 2026
 
...LIFE-THREATENING FLOODING EXPECTED ACROSS PORTIONS OF THE 
SOUTHEASTERN UNITED STATES...
...TROPICAL STORM WARNING REMAINS IN EFFECT FOR PORTIONS OF THE 
TEXAS AND LOUISIANA COAST...
 
 
SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...28.9N 96.1W
ABOUT 20 MI...35 KM NNW OF MATAGORDA TEXAS
ABOUT 195 MI...310 KM WSW OF LAKE CHARLES LOUISIANA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NNE OR 15 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Sargent, Texas to Morgan City, Louisiana
 
A Tropical Storm Warning means that tropical storm conditions are
expected within the warning area.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Arthur was 
located near latitude 28.9 North, longitude 96.1 West. Arthur is 
moving toward the north-northeast near 7 mph (11 km/h), and this 
general motion should continue through tonight. On the forecast 
track, the center of Arthur should move farther inland over 
southeastern Texas tonight.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Weakening is expected as the low moves farther inland, and it could
dissipate by tonight or early Thursday.
 
Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center. NOAA buoy 42035 east of Galveston recently reported
a sustained wind of 40 mph (65 km/h) and a gust of 52 mph (83 km/h).
 
The estimated minimum central pressure based on surface observations
and aircraft data is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Arthur can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT1 and WMO header
WTNT41 KNHC.
 
RAINFALL: Tropical Storm Arthur is expected to produce rainfall
totals of 5 to 10 inches, with isolated higher totals near 20
inches, through early Friday from the Mid and Upper Texas coast
east-northeast into southern and central portions of Louisiana,
Mississippi, and Alabama, along with western portions of Georgia and
the Florida Panhandle. This could generate dangerous to
life-threatening flash flooding.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Arthur, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_at1.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at1.shtml?ero.
 
For a list of rainfall observations (and wind reports) associated
with Tropical Storm Arthur, see the companion storm summary at
WBCSCCNS1 with the WMO header ACUS44 KWBC or at the following link:
www.wpc.ncep.noaa.gov/discussions/nfdscc1.html.
 
WIND: Tropical storm conditions are expected within the warning area
during the next few hours.
 
STORM SURGE: The combination of a dangerous storm surge and the
tide will cause normally dry areas near the coast to be flooded by
rising waters moving inland from the shoreline. The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Matagorda, TX to the Mouth of the Mississippi River, LA...1-3 ft
 
The deepest water will occur along the immediate coast near and to
the east of the landfall location, where the surge will be
accompanied by large and dangerous waves. Surge-related flooding
depends on the relative timing of the surge and the tidal cycle,
and can vary greatly over short distances. For information
specific to your area, please see products issued by your local
National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at1.shtml?peakSurge.
 
SURF:  Swells generated by Arthur are likely to cause
life-threatening surf and rip current conditions along the
northwestern Gulf Coast for the next day or two. Please consult
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at1.shtml?ripCurrents
 
TORNADO: A few tornadoes are possible late tonight across southeast
Louisiana and southern Mississippi, and tomorrow into parts of
Alabama, Georgia, and the Florida Panhandle.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.
 
$$
Forecaster Reinhart
  