

000
WTPZ34 KNHC 290833
TCPEP4

BULLETIN
Tropical Depression Nineteen-E Advisory Number   3
NWS National Hurricane Center Miami FL       EP192023
400 AM CDT Sun Oct 29 2023

...TROPICAL DEPRESSION FORECAST TO STRENGTHEN AS IT APPROACHES
CENTRAL AMERICA...
...HEAVY RAINFALL EXPECTED TO BE THE MAIN THREAT...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...11.0N 93.1W
ABOUT 320 MI...520 KM SW OF SAN SALVADOR EL SALVADOR
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in El Salvador and southern Guatemala should monitor the
progress of this system as watches will likely be required later
today.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Depression 
Nineteen-E was located near latitude 11.0 North, longitude 93.1 
West. The depression is moving toward the north-northwest near 3 mph 
(6 km/h).  The system is forecast to begin moving northeastward by 
tonight, and it could be near the coast of El Salvador or Guatemala 
on Tuesday and Tuesday night.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Gradual strengthening is forecast, and the system could be near 
hurricane strength in a couple of days.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for the depression can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml

RAINFALL:  The tropical depression is expected to produce storm
total rainfall of 5 to 10 inches, with local amounts to 15 inches,
in and near much of the Pacific coast of Central America, including
the country of El Salvador, through Wednesday.  This rainfall will
produce flash and urban flooding, along with mudslides in areas of
higher terrain.

SURF:  Swells generated by the depression are expected to reach
portions of the Pacific coast of Central America on Monday.  These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Cangialosi

