

000
WTPZ34 KNHC 301750
TCPEP4

BULLETIN
Tropical Storm Pilar Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       EP192023
100 PM CDT Mon Oct 30 2023

...PILAR EXPECTED TO BRING HEAVY RAINFALL AND FLASH FLOODING TO
PARTS OF CENTRAL AMERICA DURING THE NEXT FEW DAYS...


SUMMARY OF 100 PM CDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...11.5N 91.2W
ABOUT 205 MI...330 KM SW OF SAN SALVADOR EL SALVADOR
ABOUT 335 MI...540 KM W OF MANAGUA NICARAGUA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...ENE OR 70 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Entire coast of El Salvador
* Pacific coast of Honduras including the Gulf of Fonseca
* Honduras/Nicaragua border southward to Puerto Sandino.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 36 hours.

Interests elsewhere along the Pacific coast of Nicaragua
and in southern Guatemala should monitor the progress of this
system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 PM CDT (1800 UTC), the center of Tropical Storm Pilar was
located near latitude 11.5 North, longitude 91.2 West. Pilar has 
recently been moving more northeastward, but an east-northeastward 
motion near 6 mph (9 km/h) is expected to resume later today. On the 
forecast track, Pilar could be near the coast of El Salvador or 
Nicaragua Tuesday through early Wednesday, though the core of the 
system is expected to remain offshore.  The storm is forecast to 
move west-southwestward away from land on Thursday.

Maximum sustained winds remain near 50 mph (85 km/h) with higher 
gusts.  Further strengthening is expected during the next day or 
so, and Pilar could be near hurricane strength on Tuesday. 
Weakening is expected to begin on Wednesday and continue through 
Thursday.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Pilar can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml

RAINFALL: Pilar is expected to produce storm total rainfall of 5 to
10 inches, with local amounts to 15 inches, for portions of Central
America from El Salvador southward to Costa Rica through Wednesday.
This rainfall will produce flash and urban flooding, along with
mudslides in areas of higher terrain.

SURF:  Swells generated by Pilar are expected to continue affecting
the Pacific coast of Central America during the next few days.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.

WIND:  Tropical storm conditions could begin in the Tropical
Storm Watch area early Tuesday.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Bucci/Blake

