
ZCZC MIATCPEP4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Pilar Intermediate Advisory Number 10A
NWS National Hurricane Center Miami FL       EP192023
100 AM CDT Tue Oct 31 2023

...HEAVY RAINS FROM PILAR MOVING INLAND OVER EL SALVADOR...
...FLASH FLOODING POSSIBLE OVER PORTIONS OF CENTRAL AMERICA DURING 
THE NEXT COUPLE OF DAYS...


SUMMARY OF 100 AM CDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...11.2N 90.6W
ABOUT 195 MI...315 KM SSW OF SAN SALVADOR EL SALVADOR
ABOUT 300 MI...480 KM WSW OF MANAGUA NICARAGUA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...E OR 80 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Entire coast of El Salvador
* Pacific coast of Honduras including the Gulf of Fonseca
* Honduras/Nicaragua border southward to Puerto Sandino

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within 36 hours.

Interests elsewhere along the Pacific coast of Nicaragua and in 
southern Guatemala should monitor the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 AM CDT (0600 UTC), the center of Tropical Storm Pilar was 
located by satellite imagery near latitude 11.2 North, longitude 
90.6 West.  Pilar is moving toward the east near 5 mph (7 km/h), and 
an east-northeast motion is expected to resume later today through 
early Wednesday. On the forecast track, Pilar could be near the 
coast of El Salvador or Nicaragua late today through early 
Wednesday, though the core of the system is expected to remain 
offshore.  The storm is forecast to begin moving west-southwestward 
away from land by late Wednesday.

Maximum sustained winds are near 50 mph (85 km/h) with higher
gusts. Some strengthening is forecast, and Pilar could be near
hurricane strength by late today.  Weakening is expected to begin
by late Wednesday and continue through Thursday.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Pilar can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml

RAINFALL: Pilar is expected to produce storm total rainfall of 5 to
10 inches, with local amounts to 15 inches, over portions of
Central America from El Salvador southward to Costa Rica through
Wednesday.  This rainfall will produce flash and urban flooding,
along with mudslides in areas of higher terrain.

SURF:  Swells generated by Pilar are expected to continue affecting
the Pacific coast of Central America during the next few days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.

WIND:  Tropical storm conditions could begin in the Tropical Storm 
Watch areas this morning.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.

$$
Forecaster Blake

NNNN
