

000
WTPZ34 KNHC 010236
TCPEP4

BULLETIN
Tropical Storm Pilar Advisory Number  14
NWS National Hurricane Center Miami FL       EP192023
1000 PM CDT Tue Oct 31 2023

...PILAR DRIFTING NORTHWARD BUT FORECAST TO BEGIN MOVING WESTWARD
TOMORROW...
...HEAVY RAINFALL AND FLOODING ONGOING FOR PORTIONS OF CENTRAL
AMERICA...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...11.9N 89.4W
ABOUT 125 MI...200 KM S OF SAN SALVADOR EL SALVADOR
ABOUT 210 MI...340 KM W OF MANAGUA NICARAGUA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Entire coast of El Salvador
* Pacific coast of Honduras including the Gulf of Fonseca
* Honduras/Nicaragua border southward to Puerto Sandino

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case over the next 12 to 24
hours.

Interests elsewhere along the Pacific coast of Nicaragua and in
southern Guatemala should monitor the progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Tropical Storm Pilar was 
located near latitude 11.9 North, longitude 89.4 West. Pilar is 
drifting toward the north near 2 mph (4 km/h). Beginning tomorrow 
into Thursday, Pilar is forecast to start moving westward to 
west-southwestward. On the forecast track, the storm may remain in 
close proximity to coastal Central America into tomorrow, but 
Pilar's core is forecast to remain offshore.

Maximum sustained winds have increased to near 60 mph (95 km/h)
with higher gusts. Little change in strength is anticipated over
the next day or so, followed by gradual weakening.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.

The estimated minimum central pressure is 996 mb (29.42 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Pilar can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml

RAINFALL:  Pilar is expected to produce storm total rainfall of 5
to 10 inches, with local amounts to 15 inches, for portions of
Central America from southern El Salvador, across southern
Honduras, western Nicaragua into northern Costa Rica through
Wednesday. This rainfall will produce flash and urban flooding,
along with mudslides in areas of higher terrain.

SURF:  Swells generated by Pilar are expected to continue affecting
the Pacific coast of Central America during the next few days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.

WIND:  Tropical storm conditions are possible within the Tropical
Storm Watch area during the next day or so.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Papin

