

000
WTPZ34 KNHC 020232
TCPEP4

BULLETIN
Tropical Storm Pilar Advisory Number  18
NWS National Hurricane Center Miami FL       EP192023
1000 PM CDT Wed Nov 01 2023

...PILAR CONTINUING WESTWARD...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...12.4N 92.6W
ABOUT 315 MI...505 KM SE OF SALINA CRUZ MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Tropical Storm Pilar was
located near latitude 12.4 North, longitude 92.6 West.  Pilar is
moving toward the west near 12 mph (19 km/h), and a faster westward 
to west-southwestward motion is expected over the next few days.

Maximum sustained winds have decreased to near 45 mph (75 km/h) 
with higher gusts.  Some additional weakening is possible during the 
next couple of days.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Pilar can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml

RAINFALL:  Pilar is expected to produce additional rainfall of 1 to
2 inches, with local amounts to 4 inches, mainly in portions of El
Salvador and southern Guatemala overnight.  The additional rainfall
may produce flash and urban flooding, along with mudslides in areas
of higher terrain.

SURF:  Swells generated by Pilar and strong winds near the Gulf of
Tehuantepec are expected to continue affecting the Pacific coast of
Central America during the next day or two.  These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.

$$
Forecaster Pasch

