

830 
WTPZ31 KNHC 012034
TCPEP1

BULLETIN
Tropical Depression Eleven-E Advisory Number   1
NWS National Hurricane Center Miami FL       EP112022
300 PM MDT Thu Sep 01 2022

...TROPICAL DEPRESSION FORMS OFF THE SOUTHERN BAJA CALIFORNIA
PENINSULA COAST...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.9N 110.5W
ABOUT 280 MI...450 KM S OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Tropical Depression Eleven-E
was located near latitude 18.9 North, longitude 110.5 West. The
depression is moving toward the northwest near 10 mph (17 km/h) and
this motion with some increase in forward speed is expected during 
the next couple of days.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Slow strengthening is forecast during the next 36 to 48 hours, and 
the depression is expected to become a tropical storm tonight or on 
Friday.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by the depression are expected to affect
portions of the southern and central Baja California peninsula.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local
weather office.

RAINFALL: Tropical Depression Eleven-E is expected to produce 1 to 
2 inches of rainfall, with isolated storm totals of 3 inches across 
southern portions of Baja California Sur through Friday. 


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster Cangialosi


