

740 
WTPZ31 KNHC 021446
TCPEP1

BULLETIN
Tropical Storm Javier Advisory Number   4
NWS National Hurricane Center Miami FL       EP112022
900 AM MDT Fri Sep 02 2022

...JAVIER GRADUALLY STRENGTHENING...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...20.7N 112.2W
ABOUT 210 MI...340 KM SW OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Javier was 
located near latitude 20.7 North, longitude 112.2 West. Javier is 
moving toward the northwest near 9 mph (15 km/h), and an increase in 
forward speed is expected through early Saturday.  A turn toward the 
west-northwest is forecast on Saturday, followed by a turn toward 
the west on Sunday.

Maximum sustained winds have increased to near 45 mph (75 km/h) 
with higher gusts.  Some additional strengthening is forecast 
through Saturday before Javier begins to weaken on Sunday.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Javier can be found in the Tropical 
Cyclone Discussion under AWIPS header MIATCDEP1 and WMO header 
WTPZ41 KNHC.

SURF:  Swells generated by Javier will continue to affect portions 
of the southern and central Baja California peninsula during the 
next day or so.  These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.

RAINFALL:  Tropical Storm Javier is expected to produce 1 to 2
inches of rainfall, with isolated storm total amounts of 4 inches
across portions of Baja California Sur through this weekend.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Bucci/Reinhart


