

000
WTPZ31 KNHC 022334
TCPEP1

BULLETIN
Tropical Storm Javier Intermediate Advisory Number 5A
NWS National Hurricane Center Miami FL       EP112022
600 PM MDT Fri Sep 02 2022

...RAIN BANDS OF JAVIER BRINGING HEAVY RAIN AND GUSTY WINDS TO BAJA 
CALIFORNIA SUR...


SUMMARY OF 600 PM MDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...22.5N 112.8W
ABOUT 185 MI...300 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 13 MPH...21 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* The west coast of Baja California Sur Mexico from Cabo San Lucas
northward to Punta Eugenia
* The east coast of Baja California Sur Mexico from Cabo San Lucas
northward to Bahia San Juan Bautista

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case, within the next 12 to
24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 PM MDT (0000 UTC), the center of Tropical Storm Javier was
located near latitude 22.5 North, longitude 112.8 West. Javier is
moving toward the north-northwest near 13 mph (21 km/h). A 
slight increase in forward speed with a turn toward the 
west-northwest is anticipated on Saturday, followed by a turn 
toward the west on Sunday. On the forecast track, the center
of Javier should move generally parallel to but well offshore the 
coast of Baja California Sur through Saturday, and then turn away 
from land on Sunday.

Maximum sustained winds are near 45 mph (75 km/h) with higher
gusts. Some slight strengthening is possible tonight or Saturday 
before Javier begins to weaken on Sunday. Javier is forecast to 
become post-tropical in about 48 hours.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center. 

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Javier can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1, WMO
header WTPZ41 KNHC, and on the web at
hurricanes.gov/text/MIATCDEP1.shtml.

WIND:  Tropical storm conditions are possible in squalls across 
portions of southern Baja California Sur tonight. Gusty conditions 
will spread northward through Saturday morning.

SURF:  Swells generated by Javier will continue to affect portions
of the southern and central Baja California peninsula during the
next day or so.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.

RAINFALL:  Tropical Storm Javier is expected to produce 1 to 2
inches of additional rainfall, with isolated storm total amounts of
5 inches across portions of Baja California Sur through Saturday.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster D. Zelinsky

