

258 
WTPZ31 KNHC 030243
TCPEP1

BULLETIN
Tropical Storm Javier Advisory Number   6
NWS National Hurricane Center Miami FL       EP112022
900 PM MDT Fri Sep 02 2022

...RAIN BANDS OF JAVIER CONTINUE TO BRING HEAVY RAIN AND
GUSTY WINDS TO THE SOUTHERN BAJA CALIFORNIA PENINSULA...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...23.1N 113.2W
ABOUT 210 MI...340 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* The west coast of Baja California Sur Mexico from Cabo San Lucas
northward to Punta Eugenia
* The east coast of Baja California Sur Mexico from Cabo San Lucas
northward to Bahia San Juan Bautista

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case, within the next 12 to
24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Tropical Storm Javier was 
located near latitude 23.1 North, longitude 113.2 West. Javier is 
moving toward the north-northwest near 14 mph (22 km/h). This 
general motion is forecast to continue tonight. A slow turn toward 
the west is expected to begin by Sunday. On the forecast track, the 
center of Javier should move generally parallel to but well offshore 
the coast of Baja California Sur through Saturday, and then turn 
away from land on Sunday.

Maximum sustained winds have increased to near 50 mph (85 km/h) 
with higher gusts. Slight additional strengthening is possible 
tonight before the tropical storm begins to weaken by the end of 
the day Saturday. Javier is forecast to become post-tropical on 
Sunday.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Javier can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1, WMO
header WTPZ41 KNHC, and on the web at
hurricanes.gov/text/MIATCDEP1.shtml.

WIND:  Tropical storm conditions will be possible in squalls across
portions of southern Baja California Sur tonight. Gusty conditions
are forecast to spread northward through Saturday morning.

SURF:  Swells generated by Javier will continue to affect portions
of the southern and central Baja California peninsula during the
next day or so.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.

RAINFALL:  Tropical Storm Javier is expected to produce 1 to 2
inches of additional rainfall, with isolated storm total amounts of
5 inches across portions of Baja California Sur through Saturday.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM MDT.
Next complete advisory at 300 AM MDT.

$$
Forecaster D. Zelinsky


