

000
WTPZ31 KNHC 032332
TCPEP1

BULLETIN
Tropical Storm Javier Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP112022
500 PM PDT Sat Sep 03 2022

...JAVIER MOVING AWAY FROM THE BAJA CALIFORNIA PENINSULA...
...TROPICAL STORM WARNINGS DISCONTINUED...


SUMMARY OF 500 PM PDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...26.5N 116.7W
ABOUT 140 MI...225 KM SW OF PUNTA EUGENIA MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Government of Mexico has discontinued the Tropical Storm 
Warning for the west coast of Baja California Sur.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM PDT (0000 UTC), the center of Tropical Storm Javier was 
located near latitude 26.5 North, longitude 116.7 West. Javier is 
moving toward the northwest near 16 mph (26 km/h). The tropical 
storm is forecast to slow down and turn toward the west through the 
end of the weekend, and then move generally westward after that. On 
the forecast track, the center of Javier will continue to move away 
from the coast of Baja California Sur this evening.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Slow weakening is forecast during the next several days. Javier will 
likely become a post-tropical cyclone tonight.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Javier can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP1, WMO
header WTPZ41 KNHC, and on the web at
hurricanes.gov/text/MIATCDEP1.shtml.

SURF:  Swells generated by Javier will continue to affect portions
of the southern and central Baja California peninsula during the
next day or so. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.

RAINFALL:  Javier is expected to produce 1 to 2 inches of additional
rainfall, with isolated storm total amounts of 5 inches across
portions of Baja California Sur through tonight.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster D. Zelinsky

