

000
WTPZ31 KNHC 040837
TCPEP1

BULLETIN
Post-Tropical Cyclone Javier Advisory Number  11
NWS National Hurricane Center Miami FL       EP112022
200 AM PDT Sun Sep 04 2022

...JAVIER DEGENERATES INTO A REMNANT LOW...
...THIS IS THE LAST NHC ADVISORY...


SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...27.2N 118.5W
ABOUT 210 MI...340 KM W OF PUNTA EUGENIA MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Post-Tropical Cyclone Javier
was located near latitude 27.2 North, longitude 118.5 West. The
post-tropical cyclone is moving toward the west-northwest near 15
mph (24 km/h). A slow turn toward the west is expected today. 
The remnant low is then forecast to continue westward through early 
next week.

Maximum sustained winds have decreased to near 35 mph (55 km/h) 
with higher gusts.  Further weakening is expected during 
the next several days and the remnant low will likely dissipate 
toward the end of the week.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Javier will continue to affect portions
of the southern and central Baja California peninsula during the
next day or so. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.

RAINFALL:  Javier may produce up to an additional inch of rainfall 
across portions of the Baja California Peninsula today, bringing 
isolated storm total rainfall up to 5 inches.

NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane
Center on Javier.  For additional information on the remnant low 
please see High Seas Forecasts issued by the National Weather 
Service, under AWIPS header NFDHSFEPI, WMO header FZPN02 KWBC, and 
on the web at ocean.weather.gov/shtml/NFDHSFEPI.php

$$
Forecaster Roberts

