

000
WTPZ32 KNHC 231441
TCPEP2

BULLETIN
Hurricane Kristy Advisory Number   8
NWS National Hurricane Center Miami FL       EP122024
800 AM MST Wed Oct 23 2024

...KRISTY RAPIDLY INTENSIFIES INTO A MAJOR HURRICANE...
...ADDITIONAL STRENGTHENING IS EXPECTED...


SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...14.3N 113.9W
ABOUT 650 MI...1045 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 365 MI...590 KM SSW OF SOCORRO ISLAND
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...W OR 265 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...954 MB...28.17 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the eye of Hurricane Kristy was located 
near latitude 14.3 North, longitude 113.9 West. Kristy is moving 
toward the west near 20 mph (31 km/h), and this general motion is 
expected to continue through Thursday. A gradual turn toward the 
west-northwest and northwest is expected on Friday and into the 
weekend.

Maximum sustained winds have increased to near 125 mph (205 km/h) 
with higher gusts. Kristy is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Additional steady to rapid 
strengthening is expected during the next day or so. Gradual 
weakening is forecast to begin on Friday.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 954 mb (28.17 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy will affect portions of the west
coast of the Baja California peninsula late this week. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.

$$
Forecaster Reinhart

