

305 
WTPZ32 KNHC 232044
TCPEP2

BULLETIN
Hurricane Kristy Advisory Number   9
NWS National Hurricane Center Miami FL       EP122024
200 PM PDT Wed Oct 23 2024

...KRISTY CONTINUES TO RAPIDLY INTENSIFY...


SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...14.1N 115.5W
ABOUT 710 MI...1140 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 440 MI...710 KM SW OF SOCORRO ISLAND
MAXIMUM SUSTAINED WINDS...155 MPH...250 KM/H
PRESENT MOVEMENT...W OR 265 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...928 MB...27.41 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Hurricane Kristy was located 
near latitude 14.1 North, longitude 115.5 West. Kristy is moving 
toward the west near 20 mph (31 km/h), and this motion is expected 
to continue through Thursday. A gradual turn toward the 
west-northwest and northwest is expected on Friday and into the 
weekend.

Maximum sustained winds are near 155 mph (250 km/h) with higher 
gusts. Kristy is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Some additional strengthening is expected 
through early Thursday. Gradual weakening should begin on Friday.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure is 928 mb (27.41 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy will affect portions of the west
coast of the Baja California peninsula late this week. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Reinhart/Adams


