

000
WTPZ32 KNHC 240231
TCPEP2

BULLETIN
Hurricane Kristy Advisory Number  10
NWS National Hurricane Center Miami FL       EP122024
800 PM PDT Wed Oct 23 2024

...KRISTY REMAINS A VERY POWERFUL CATEGORY 4 HURRICANE...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 117.2W
ABOUT 765 MI...1235 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 520 MI...835 KM SW OF SOCORRO ISLAND
MAXIMUM SUSTAINED WINDS...155 MPH...250 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...928 MB...27.41 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the eye of Hurricane Kristy was located 
near latitude 14.2 North, longitude 117.2 West.  Kristy is moving 
toward the west near 20 mph (31 km/h), and a westward to 
west-northwestward motion is forecast through Thursday.  A slower 
northwest to north-northwest motion is expected by late Friday.

Maximum sustained winds are near 155 mph (250 km/h) with higher
gusts.  Kristy is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Kristy is expected to fluctuate in strength 
over the next day or so.  Steady to rapid weakening should begin by 
early Friday.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 928 mb (27.41 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy will affect portions of the west
coast of the Baja California peninsula late this week and over the
weekend.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.

$$
Forecaster Cangialosi

