

000
WTPZ32 KNHC 260232
TCPEP2

BULLETIN
Hurricane Kristy Advisory Number  18
NWS National Hurricane Center Miami FL       EP122024
800 PM PDT Fri Oct 25 2024

...KRISTY WEAKENING RAPIDLY...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 126.9W
ABOUT 1160 MI...1865 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Hurricane Kristy was located
near latitude 17.6 North, longitude 126.9 West.  Kristy is moving
toward the northwest near 15 mph (24 km/h).  A northwestward or 
north-northwestward motion at a slower forward speed is expected 
through early Sunday, followed by a turn toward the west by late 
Sunday.

Maximum sustained winds have decreased to near 105 mph (165 km/h) 
with higher gusts.  Rapid weakening is expected to continue over 
the next couple of days, and Kristy is forecast to degenerate into 
a remnant low on Sunday.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy are affecting portions of the west
coast of the Baja California peninsula and will likely continue to
impact the region through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.

$$
Forecaster Berg

