

000
WTPZ32 KNHC 260834
TCPEP2

BULLETIN
Hurricane Kristy Advisory Number  19
NWS National Hurricane Center Miami FL       EP122024
200 AM PDT Sat Oct 26 2024

...KRISTY CONTINUES TO WEAKEN...
...EXPECTED TO BECOME A REMNANT LOW ON SUNDAY...


SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...18.7N 127.6W
ABOUT 1180 MI...1895 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...972 MB...28.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Hurricane Kristy was located 
near latitude 18.7 North, longitude 127.6 West. Kristy is moving 
toward the northwest near 15 mph (24 km/h). A northwestward or 
north-northwestward motion at a slower forward speed is expected 
today, followed by a turn toward the west by Sunday.

Maximum sustained winds have decreased to near 100 mph (155 km/h)
with higher gusts. Rapid weakening is expected to continue over the
next couple of days, and Kristy is forecast to degenerate into a
remnant low on Sunday.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 972 mb (28.71 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy are affecting portions of the west
coast of the Baja California peninsula and will likely continue to
impact the region through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.

$$
Forecaster Papin

