

000
WTPZ32 KNHC 262034
TCPEP2

BULLETIN
Tropical Storm Kristy Advisory Number  21
NWS National Hurricane Center Miami FL       EP122024
200 PM PDT Sat Oct 26 2024

...KRISTY FORECAST TO BECOME A REMNANT LOW ON SUNDAY...


SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...20.7N 129.2W
ABOUT 1245 MI...2005 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Tropical Storm Kristy was
located near latitude 20.7 North, longitude 129.2 West. Kristy is
moving toward the northwest near 14 mph (22 km/h). A northwestward 
or north-northwestward motion at a slower forward speed is expected
today, followed by a turn toward the west on Sunday.

Maximum sustained winds have decreased to near 65 mph (100 km/h) 
with higher gusts.  Rapid weakening is expected to continue over
the weekend, and Kristy is forecast to degenerate into a remnant
low on Sunday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy are affecting portions of the west
coast of the Baja California peninsula and will likely continue to
impact the region through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Blake

