

000
WTPZ32 KNHC 270833
TCPEP2

BULLETIN
Tropical Storm Kristy Advisory Number  23
NWS National Hurricane Center Miami FL       EP122024
200 AM PDT Sun Oct 27 2024

...KRISTY FORECAST TO BECOME A POST-TROPICAL CYCLONE LATER TODAY...


SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...22.0N 129.8W
ABOUT 1270 MI...2045 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Tropical Storm Kristy was
located near latitude 22.0 North, longitude 129.8 West. Kristy is
moving toward the northwest near 7 mph (11 km/h). A turn toward the
west at a slower forward speed is expected later today.

Maximum sustained winds have decreased to near 50 mph (85 km/h) with
higher gusts. Additional weakening is forecast today, and Kristy is
expected to become a post-tropical cyclone later today and dissipate
on Monday.

Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kristy are affecting portions of the west
coast of the Baja California peninsula and will likely continue to
impact the region through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.

$$
Forecaster Papin

