

000
WTPZ32 KNHC 290257
TCPEP2

BULLETIN
Potential Tropical Cyclone Two-E Advisory Number   1
NWS National Hurricane Center Miami FL       EP022023
1000 PM CDT Wed Jun 28 2023

...TROPICAL STORM EXPECTED TO FORM OFF THE SOUTHERN COAST OF MEXICO
ON THURSDAY...
...TROPICAL STORM WARNINGS AND WATCHES ISSUED FOR THE SOUTHWESTERN
COAST OF MEXICO...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.5N 96.8W
ABOUT 315 MI...505 KM SE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...30 MPH...45 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Government of Mexico has issued a Tropical Storm Warning from
Punta Maldonado to Lazaro Cardenas and a Tropical Storm Watch north
of Lazaro Cardenas to Manzanillo.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Punta Maldonado to Lazaro Cardenas

A Tropical Storm Watch is in effect for...
* North of Lazaro Cardenas to Manzanillo

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the disturbance was centered near
latitude 13.5 North, longitude 96.8 West.  The system is moving
toward the northwest near 12 mph (19 km/h) and this general motion 
is expected to continue for next few days.  On the forecast track, 
the disturbance is expected to move near the southwestern coast of 
Mexico during the next several days.

Maximum sustained winds are near 30 mph (45 km/h) with higher gusts.
Gradual strengthening is forecast, and the system is expected to 
become a tropical storm by Thursday.  
* Formation chance through 48 hours...high...80 percent.
* Formation chance through 5 days...high...90 percent.

The estimated minimum central pressure is 1007 mb (29.74 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Two-E can be found in 
the Tropical Cyclone Discussion under AWIPS header MIATCDEP2 and WMO 
header WTPZ42 KNHC and on the web at 
hurricanes.gov/text/miatcdep2.shtml

WIND: Tropical storm conditions are expected in the tropical storm 
warning area beginning late Wednesday or early Thursday.

RAINFALL: Through Saturday, storm total rainfall of 3 to 5 inches, 
with maximum amounts of 7 inches, is expected across southern Mexico 
from Oaxaca west to Jalisco.  This rainfall could lead to localized 
flash flooding. 

SURF: Swells generated by this system is forecast to build and 
spread along the southwestern coast during the next couple days.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Bucci/Pasch

