

000
WTPZ32 KNHC 291137
TCPEP2

BULLETIN
Tropical Depression Two-E Intermediate Advisory Number 2A
NWS National Hurricane Center Miami FL       EP022023
700 AM CDT Thu Jun 29 2023

...TROPICAL DEPRESSION PRODUCING HEAVY RAINS ALONG THE COAST OF 
OAXACA...


SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...14.3N 98.3W
ABOUT 155 MI...250 KM SW OF PUERTO ANGEL MEXICO
ABOUT 210 MI...335 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Punta Maldonado to Punta San Telmo Mexico

A Tropical Storm Watch is in effect for...
* North of Punta San Telmo to Playa Perula Mexico

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the southwestern coast of Mexico and in
the southern portion of the Baja California peninsula should
monitor the progress of this system.  Additional warnings and
watches will likely be required for portions of these areas later
today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Tropical Depression Two-E
was located near latitude 14.3 North, longitude 98.3 West.  The
depression is moving toward the northwest near 14 mph (22 km/h), and
this general motion is expected to continue for next few days.  On
the forecast track, the depression is expected to move near the
southwestern coast of Mexico during the next few days.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts.  Strengthening is forecast, and the depression is expected to
become a tropical storm later today.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Two-E can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDEP2 and WMO
header WTPZ42 KNHC and on the web at 
hurricanes.gov/text/miatcdep2.shtml

WIND: Tropical storm conditions are expected in the tropical storm
warning area beginning later today and continuing through Friday and 
are possible within the tropical storm watch area late Friday and 
Friday night.

RAINFALL: Through Saturday, storm total rainfall of 3 to 5 inches,
with maximum amounts of 7 inches, is expected across southern Mexico
from Oaxaca west to Jalisco.  This rainfall could lead to localized
flash flooding.

SURF: Swells generated by the depression are forecast to build and
spread northward along the southwestern coast during the next 
couple of days.  These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Berg

