

000
WTPZ32 KNHC 292054
TCPEP2

BULLETIN
Tropical Storm Beatriz Advisory Number   4
NWS National Hurricane Center Miami FL       EP022023
400 PM CDT Thu Jun 29 2023

...TROPICAL STORM BEATRIZ FORMS OFF THE SOUTHERN COAST OF MEXICO...
...FORECAST TO RAPIDLY INTENSIFY, HURRICANE WARNING ISSUED FOR 
PORTIONS OF THE SOUTHWESTERN COAST OF MEXICO...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...15.0N 99.4W
ABOUT 105 MI...170 KM SSW OF PUNTA MALDONADO MEXICO
ABOUT 135 MI...220 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Hurricane Warning from
Zihuatanejo to Playa Perula.  A Tropical Storm Watch has been
issued north of Cabo Corrientes to Punta Mita.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Zihuatanejo to Playa Perula Mexico

A Hurricane Watch is in effect for...
* North of Playa Perula to Cabo Corrientes Mexico

A Tropical Storm Warning is in effect for...
* South of Zihuatanejo to Punta Maldonado Mexico

A Tropical Storm Watch is in effect for...
* North of Cabo Corrientes to Punta Mita Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests along the west-central coast of Mexico and in the southern
portion of the Baja California peninsula should monitor the progress
of this system.  Additional warnings and watches may be required
tonight or on Friday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Beatriz was
located near latitude 15.0 North, longitude 99.4 West.  Beatriz is
moving toward the west-northwest near 12 mph (19 km/h).  A 
northwestward motion is expected to begin tonight, with a decrease 
in speed occurring over the weekend.  On the forecast track, the 
center of Beatriz is expected to move very near or along the coast 
of southwestern Mexico during the next couple of days.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Rapid strengthening is forecast, and Beatriz is likely to become a 
hurricane on Friday.  Beatriz is forecast to be a hurricane while 
it moves near portions of the coast of southwestern Mexico.

Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Beatriz can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/miatcdep2.shtml

WIND:  Hurricane conditions are expected somewhere within the 
hurricane warning area Friday and Friday night.  Hurricane 
conditions are possible within the hurricane watch area on Saturday.
Tropical storm conditions are expected in the tropical storm warning 
area through early Friday, and are possible within the tropical 
storm watch area on Saturday.

RAINFALL:  Through Sunday morning, storm total rainfall of 3 to 5
inches, with maximum amounts of 7 inches, is expected across
southern Mexico from Oaxaca west to Jalisco.  This rainfall could
lead to localized flash flooding.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds.  Near the
coast, the surge will be accompanied by large and destructive waves.

SURF: Swells generated by Beatriz are forecast to build and spread 
northward along the southwestern coast of Mexico during the next 
couple of days.  These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Berg

