

690 
WTPZ32 KNHC 301146
TCPEP2

BULLETIN
Tropical Storm Beatriz Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       EP022023
700 AM CDT Fri Jun 30 2023

...BEATRIZ STRENGTHENING OFF THE COAST OF GUERRERO MEXICO...


SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...16.7N 101.9W
ABOUT 70 MI...115 KM SSW OF ZIHUATANEJO MEXICO
ABOUT 225 MI...360 KM SE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.41 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Zihuatanejo to Cabo Corrientes Mexico

A Hurricane Watch is in effect for...
* North of Cabo Corrientes to Punta Mita Mexico

A Tropical Storm Warning is in effect for...
* South of Zihuatanejo to Acapulco Mexico
* North of Cabo Corrientes to Punta Mita Mexico

A Tropical Storm Watch is in effect for...
* North of Punta Mita to San Blas Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the west-central coast of Mexico and in
the southern portion of the Baja California peninsula should
monitor the progress of this system.  Additional warnings and
watches may be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Tropical Storm Beatriz was
located near latitude 16.7 North, longitude 101.9 West.  Beatriz is
moving toward the northwest near 13 mph (20 km/h).  A continued
northwestward motion is expected for the next few days, with a
gradual decrease in forward speed occurring over the weekend.  On
the forecast track, the center of Beatriz is expected to approach
the coast of southwestern Mexico today, then move near or over 
portions of the coast of southwestern Mexico tonight and on 
Saturday.

Maximum sustained winds are now near 65 mph (100 km/h) with higher
gusts.  Rapid strengthening is forecast, and Beatriz is likely to
become a hurricane later today.  Beatriz is forecast to be a
hurricane while the center moves near or over the coast of Mexico.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
mainly to the northeast of the center.

The estimated minimum central pressure is 996 mb (29.41 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Beatriz can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/miatcdep2.shtml

WIND:  Hurricane conditions are expected somewhere within the
hurricane warning area later today and tonight.  Hurricane
conditions are possible within the hurricane watch area on Saturday.
Tropical storm conditions are likely occurring in the tropical 
storm warning area, and are possible within the tropical storm watch 
area on Saturday.

RAINFALL: Through Sunday, storm total rainfall of 3 to 5 inches,
with maximum amounts of 8 inches, is expected across southern Mexico
from Guerrero west-northwest to Nayarit from Tropical Storm Beatriz.
This rainfall could lead to localized flash flooding and mudslides.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds.  Near the
coast, the surge will be accompanied by large and destructive waves.

SURF: Swells generated by Beatriz are forecast to spread northward 
along the southwestern coast of Mexico during the next couple of 
days.  These swells are likely to cause life-threatening surf and 
rip current conditions.  Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Berg


