

000
WTPZ32 KNHC 301457
TCPEP2

BULLETIN
Hurricane Beatriz Advisory Number   7
NWS National Hurricane Center Miami FL       EP022023
1000 AM CDT Fri Jun 30 2023

...BEATRIZ BECOMES A HURRICANE...
...STRONG WINDS AND HEAVY RAINS EXPECTED ALONG PORTIONS OF THE
SOUTHWESTERN COAST OF MEXICO THROUGH SATURDAY...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.3N 102.3W
ABOUT 50 MI...80 KM S OF LAZARO CARDENAS MEXICO
ABOUT 175 MI...285 KM SE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Tropical Storm Watch for Las
Islas Marias.  The Tropical Storm Warning south of Tecpan de
Galeana has been discontinued.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Zihuatanejo to Cabo Corrientes Mexico

A Hurricane Watch is in effect for...
* North of Cabo Corrientes to Punta Mita Mexico

A Tropical Storm Warning is in effect for...
* South of Zihuatanejo to Tecpan de Galeana Mexico
* North of Cabo Corrientes to Punta Mita Mexico

A Tropical Storm Watch is in effect for...
* North of Punta Mita to San Blas Mexico
* Las Islas Marias

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 to 36 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the west-central coast of Mexico and in
the southern portion of the Baja California peninsula should
monitor the progress of this system.  Additional watches or
warnings may be required later today or on Saturday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Hurricane Beatriz was
located near latitude 17.3 North, longitude 102.3 West.  Beatriz is
moving toward the northwest near 13 mph (20 km/h), and this motion
with some decrease in forward speed is expected through early
Sunday.  A turn toward the west-northwest with an additional
decrease in forward speed is expected on Sunday.  On the forecast
track, the center of Beatriz is expected to move near or over
portions of the coast of southwestern Mexico later today through
Saturday.  Beatriz is then expected to move away from the
west-central coast of Mexico Saturday night and Sunday.

Recent satellite images indicate that Beatriz has become a
hurricane, and maximum sustained winds have increased to near 75
mph (120 km/h) with higher gusts.  Additional strengthening is
expected today and tonight if Beatriz's center remains over water.
Weakening is expected to begin on Sunday.

Hurricane-force winds extend outward up to 10 miles (20 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).

The estimated minimum central pressure is 991 mb (29.27 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Beatriz can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/miatcdep2.shtml

WIND:  Hurricane conditions are expected somewhere within the
hurricane warning area today through Saturday.  Hurricane conditions
are possible within the hurricane watch area on Saturday.  Tropical
storm conditions are likely occurring in the tropical storm warning
area, and are possible within the tropical storm watch areas
Saturday or Saturday night.

RAINFALL: Through Sunday, storm total rainfall of 3 to 5 inches, 
with maximum amounts of 8 inches, is expected across southern Mexico 
from Guerrero west-northwest to Nayarit from Beatriz. This rainfall 
could lead to localized flash flooding and mudslides.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding in areas of onshore winds.  Near the
coast, the surge will be accompanied by large and destructive waves.

SURF: Swells generated by Beatriz are forecast to spread northward
along the southwestern coast of Mexico during the next day or so.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Berg

