

000
WTPZ32 KNHC 011445
TCPEP2

BULLETIN
Tropical Storm Beatriz Advisory Number  11
NWS National Hurricane Center Miami FL       EP022023
1000 AM CDT Sat Jul 01 2023

...BEATRIZ BEGINNING TO MOVE AWAY FROM THE WEST-CENTRAL COAST OF 
MEXICO..
...HEAVY RAINS AND GUSTY WINDS CONTINUE WITHIN THE WARNING AREAS...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.4N 105.9W
ABOUT 15 MI...20 KM W OF CABO CORRIENTES MEXICO
ABOUT 85 MI...135 KM SSE OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Manzanillo to Punta Mita Mexico

A Tropical Storm Watch is in effect for...
* North of Punta Mita to San Blas Mexico
* Las Islas Marias

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case during
the next few hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 12
hours.

Interests elsewhere along the west-central coast of Mexico and in
the southern portion of the Baja California peninsula should monitor
the progress of this system.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Beatriz was
located near latitude 20.4 North, longitude 105.9 West.  Beatriz is
moving toward the northwest near 13 mph (20 km/h), and a 
northwestward motion at a slower forward speed is expected through 
Sunday morning.  On the forecast track, Beatriz will move away from 
the west-central coast of Mexico and pass just to the southwest of 
Las Islas Marias through tonight.  Beatriz is then expected to 
drift toward the west-northwest over the mouth of the Gulf of 
California Sunday and Monday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Additional weakening is forecast, and Beatriz is expected to become 
a remnant low by early Monday.  Dissipation could occur at any time.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Beatriz can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP2 and WMO header WTPZ42 KNHC
and on the web at hurricanes.gov/text/miatcdep2.shtml

WIND:  Tropical storm conditions are expected to diminish within 
the tropical storm warning this afternoon, and are possible within 
the tropical storm watch area later today or tonight.

RAINFALL:  Through Monday, storm total rainfall of 3 to 5 inches,
with maximum amounts of 8 inches, is expected across portions of
southern and western Mexico from Colima northwest to Sinaloa and
Durango in association with Beatriz.  This rainfall could lead to
localized flash flooding and mudslides.

SURF:  Swells generated by Beatriz are occurring along portions of 
the southwestern coast of Mexico.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Berg

