

000
WTPZ32 KNHC 011802
TCPEP2

BULLETIN
Remnants Of Beatriz Special Advisory Number  12
NWS National Hurricane Center Miami FL       EP022023
1200 PM MDT Sat Jul 01 2023

...BEATRIZ DISSIPATES OFF THE WEST-CENTRAL COAST OF MEXICO...
...THIS IS THE LAST ADVISORY...


SUMMARY OF 1200 PM MDT...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.7N 106.2W
ABOUT 40 MI...60 KM WNW OF CABO CORRIENTES MEXICO
ABOUT 55 MI...90 KM SSE OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...30 MPH...45 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued all watches and warnings
for the west-central coast of mainland Mexico.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
Satellite-derived wind data indicate the Beatriz no longer has a 
surface circulation and has dissipated.  At 1200 PM MDT (1800 UTC), 
the remnants of Beatriz were located near latitude 20.7 North, 
longitude 106.2 West. The remnants are moving toward the northwest 
near 12 mph (19 km/h), but are expected to slow down and meander 
over the mouth of the Gulf of California during the next few days.

Maximum sustained winds have decreased to near 30 mph (45 km/h) with 
higher gusts. 

The estimated minimum central pressure is 1008 mb (29.77 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Through Monday, storm total rainfall of 3 to 5 inches,
with maximum amounts of 8 inches, is expected across portions of
southern and western Mexico from Colima northwest to Sinaloa and
Durango in association with the remnants of Beatriz.  This rainfall 
could lead to localized flash flooding and mudslides.

SURF:  Swells generated by Beatriz are expected to diminish along 
the southwestern coast of Mexico during the next day or so.  These 
swells could cause life-threatening surf and rip current conditions. 
Please consult products from your local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane
Center on this system.  For additional information on the remnant 
low please see High Seas Forecasts issued by the National Weather 
Service, under AWIPS header NFDHSFEPI, WMO header FZPN02 KWBC, and 
on the web at ocean.weather.gov/shtml/NFDHSFEPI.php


$$
Forecaster Berg

