

000
WTPZ33 KNHC 022037
TCPEP3

BULLETIN
Hurricane Carlotta Advisory Number  10
NWS National Hurricane Center Miami FL       EP032024
200 PM PDT Fri Aug 02 2024

...HURRICANE CARLOTTA A LITTLE STRONGER...


SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.7N 116.4W
ABOUT 510 MI...820 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...981 MB...28.97 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Hurricane Carlotta was 
located near latitude 18.7 North, longitude 116.4 West. Carlotta is 
moving toward the west near 14 mph (22 km/h) and a general westward 
to west-northwestward motion with a gradual slowdown is forecasted 
over the next few days.

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts. Additional strengthening is forecast during the 
next day or so, followed by weakening beginning by early next week.

Hurricane-force winds extend outward up to 10 miles (20 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 981 mb (28.97 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Carlotta are affecting the coasts of
west-central mainland Mexico and the southern Baja California
peninsula. These swells are likely to cause life-threatening surf
and rip current conditions through Sunday. Please consult products
from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Papin

