

203 
WTNT31 KNHC 071153
TCPAT1

BULLETIN
Hurricane Earl Intermediate Advisory Number 18A
NWS National Hurricane Center Miami FL       AL062022
800 AM AST Wed Sep 07 2022

...NOAA HURRICANE HUNTERS FIND EARL A LITTLE STRONGER...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...25.4N 65.8W
ABOUT 485 MI...775 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...135 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Hurricane Earl was located 
near latitude 25.4 North, longitude 65.8 West. Earl is moving toward 
the north near 6 mph (9 km/h), and a continued northward motion is 
expected to continue through tonight.  A turn toward the 
north-northeast and then northeast with an increase in forward speed 
is expected to begin on Thursday and continue through early 
Saturday.  On the forecast track, the center of Earl is expected to 
pass to the southeast of Bermuda late Thursday and Thursday night.

Data from a NOAA Hurricane Hunter aircraft indicate that maximum 
sustained winds have increased to 85 mph (135 km/h) with higher 
gusts.  Strengthening is forecast during the next couple of days, 
and Earl is expected to become a major hurricane late Thursday or 
Thursday night.

Hurricane-force winds extend outward up to 40 miles (65 km) from
the center and tropical-storm-force winds extend outward up to 125
miles (205 km).

The minimum central pressure reported by the NOAA Hurricane Hunter
aircraft is 978 mb (28.88 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Tropical storm conditions are expected on Bermuda beginning
Thursday afternoon.

RAINFALL:  Earl is expected to produce rainfall amounts of 1 to 2
inches (25 to 50 mm) across Bermuda through Friday.

SURF:  Swells generated by Earl are expected to reach Bermuda by
tonight.  These swells are likely to cause life-threatening surf and
rip current conditions through Friday.  Please consult products from
your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin


