

248 
WTNT31 KNHC 071447
TCPAT1

BULLETIN
Hurricane Earl Advisory Number  19
NWS National Hurricane Center Miami FL       AL062022
1100 AM AST Wed Sep 07 2022

...EARL FORECAST TO BECOME A MAJOR HURRICANE LATER THIS WEEK...
...DANGEROUS SURF AND RIP CURRENT CONDITIONS EXPECTED OVER THE
EASTERN US COASTLINE FOR THE NEXT FEW DAYS...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...25.7N 65.7W
ABOUT 460 MI...740 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Earl was located 
near latitude 25.7 North, longitude 65.7 West. Earl is moving toward 
the north near 8 mph (13 km/h), and a continued northward motion is 
expected to continue through tonight.  A turn toward the 
north-northeast and then northeast with an increase in forward speed 
is expected to begin on Thursday and continue through early 
Saturday.  On the forecast track, the center of Earl is expected to 
pass to the southeast of Bermuda late Thursday and Thursday night.

Data from a NOAA Hurricane Hunter aircraft indicate that maximum 
sustained winds are near 85 mph (135 km/h) with higher gusts.  
Strengthening is forecast during the next couple of days, and Earl 
is expected to become a major hurricane on Thursday.

Hurricane-force winds extend outward up to 40 miles (65 km) from the 
center and tropical-storm-force winds extend outward up to 140 miles 
(220 km).

The minimum central pressure reported by the NOAA Hurricane Hunters 
is 978 mb (28.88 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Tropical storm conditions are expected on Bermuda beginning
Thursday afternoon.

RAINFALL:  Earl is expected to produce rainfall amounts of 1 to 2
inches (25 to 50 mm) across Bermuda through Friday.

SURF:  Swells generated by Earl are expected to reach Bermuda by 
tonight and the U.S. east coast shortly thereafter. These swells are 
likely to cause life-threatening surf and rip current conditions 
through the weekend.  Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Papin


