

379 
WTNT31 KNHC 081159
TCPAT1

BULLETIN
Hurricane Earl Intermediate Advisory Number 22A
NWS National Hurricane Center Miami FL       AL062022
800 AM AST Thu Sep 08 2022

...EARL MOVING A BIT FASTER JUST EAST OF DUE NORTH...
...TROPICAL STORM CONDITIONS EXPECTED TO BEGIN ON BERMUDA LATER 
TODAY...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...28.6N 65.3W
ABOUT 265 MI...425 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 10 MPH...16 KM/H
MINIMUM CENTRAL PRESSURE...965 MB...28.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bermuda

A Tropical Storm Warning is in effect for...
* Bermuda

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case this evening.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case later
today and tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Hurricane Earl was located 
near latitude 28.6 North, longitude 65.3 West.  Earl is moving 
toward the north near 10 mph (16 km/h).  A turn toward the 
north-northeast with a further increase in forward speed is expected 
today, followed by a turn toward the northeast on Friday.  On the 
forecast track, the center of Earl is expected to pass to the 
southeast of Bermuda this evening and tonight.

Data from the current NOAA Hurricane Hunter mission so far suggests 
that maximum sustained winds remain near 105 mph (165 km/h) with 
higher gusts.  Additional strengthening is forecast during the next 
couple of days, and Earl is expected to become a major hurricane 
later today.  The hurricane is forecast to become a powerful 
post-tropical low on Saturday.

Hurricane-force winds extend outward up to 60 miles (95 km) from
the center and tropical-storm-force winds extend outward up to 160
miles (260 km).

The minimum central pressure from the NOAA Hurricane Hunter 
reconnaissance data is 965 mb (28.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Tropical storm conditions are expected on Bermuda beginning
this afternoon or evening.  Hurricane conditions are possible on
Bermuda this evening.

RAINFALL:  Earl is expected to produce rainfall amounts of 1 to 2
inches (25 to 50 mm) across Bermuda through Friday.

SURF:  Swells generated by Earl are building near Bermuda and
are expected to reach the U.S. east coast later today and tonight.
These swells are likely to cause life-threatening surf and rip
current conditions through the weekend.  Please consult products
from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin


