

000
WTNT31 KNHC 082055
TCPAT1

BULLETIN
Hurricane Earl Advisory Number  24
NWS National Hurricane Center Miami FL       AL062022
500 PM AST Thu Sep 08 2022

...EARL GROWING LARGER BUT NOT YET STRONGER...
...TROPICAL STORM CONDITIONS EXPECTED IN BERMUDA TONIGHT...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...30.3N 64.4W
ABOUT 140 MI...225 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...961 MB...28.38 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bermuda

A Tropical Storm Warning is in effect for...
* Bermuda

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case this evening.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case later
today and tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Earl was located
near latitude 30.3 North, longitude 64.4 West. Earl is moving toward
the north-northeast near 16 mph (26 km/h) and this motion is
expected to continue with further acceleration tonight. A turn more
northeastward is expected tomorrow.

Maximum sustained winds measured by the Air Force Reserve Hurricane 
Hunters are near 100 mph (155 km/h) with higher gusts. Strengthening 
is still anticipated and Earl could become a major hurricane by 
tomorrow. Thereafter, some weakening and transition into a powerful 
extratropical cyclone is forecast on Saturday.

Earl is growing larger, with Hurricane-force winds extending outward 
up to 60 miles (95 km) from the center and tropical-storm-force 
winds extending outward up to 185 miles (295 km).

The latest minimum central pressure measured by the Air Force
Reserve Hurricane Hunters is 961 mb (28.38 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Tropical storm conditions are expected on Bermuda beginning
this evening.  Hurricane conditions are possible on Bermuda
overnight.

RAINFALL:  Earl is expected to produce rainfall amounts of 1 to 3
inches (25 to 75 mm) across Bermuda through Friday.

SURF:  Swells generated by Earl are building near Bermuda and are
expected to reach the U.S. east coast tonight. These swells are
likely to cause life-threatening surf and rip current conditions
through the weekend.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Papin

