

979 
WTNT31 KNHC 090252
TCPAT1

BULLETIN
Hurricane Earl Advisory Number  25
NWS National Hurricane Center Miami FL       AL062022
1100 PM AST Thu Sep 08 2022

...OUTER RAINBANDS OF EARL PRODUCING TROPICAL-STORM-FORCE GUSTS ON 
BERMUDA...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...31.3N 63.7W
ABOUT 95 MI...150 KM SE OF BERMUDA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...964 MB...28.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Bermuda Weather Service has discontinued the Hurricane Watch
for Bermuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case overnight.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Earl was located
near latitude 31.3 North, longitude 63.7 West. Earl is moving toward
the north-northeast near 15 mph (24 km/h), and an increase in
forward speed is expected tonight, with a turn toward the northeast
tomorrow.

Data from a NOAA Hurricane Hunter aircraft indicate that maximum 
sustained winds are near 90 mph (150 km/h) with higher gusts.  
Re-strengthening is still possible, and Earl could become a major 
hurricane by tomorrow. Thereafter, some weakening and a
transition into a powerful extratropical cyclone is forecast on
Saturday.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).  L.F. Wade International Airport on Bermuda recently 
reported a sustained wind of 37 mph (59 km/h) and a gust to 49 mph 
(80 km/h).

The minimum central pressure reported by the NOAA plane is 964 mb 
(28.47 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Tropical storm conditions are expected on Bermuda overnight.

RAINFALL:  Earl is expected to produce rainfall amounts of 1 to 3
inches (25 to 75 mm) across Bermuda through Friday.

SURF:  Swells generated by Earl are affecting Bermuda and are
expected to reach the U.S. east coast tonight. These swells are
likely to cause life-threatening surf and rip current conditions
through the weekend.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Bucci/Pasch


