

783 
WTNT31 KNHC 091434
TCPAT1

BULLETIN
Hurricane Earl Advisory Number  27
NWS National Hurricane Center Miami FL       AL062022
1100 AM AST Fri Sep 09 2022

...EARL FORECAST TO BECOME A POWERFUL POST-TROPICAL CYCLONE ON
SATURDAY...
...RIP CURRENT THREAT WILL CONTINUE ACROSS THE WESTERN ATLANTIC
THROUGH THE WEEKEND...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...34.2N 61.0W
ABOUT 255 MI...410 KM ENE OF BERMUDA
ABOUT 955 MI...1540 KM SSW OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...961 MB...28.38 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Bermuda Weather Service has discontinued the Tropical Storm
Warning for Bermuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Earl was located
near latitude 34.2 North, longitude 61.0 West. Earl is moving toward
the northeast near 22 mph (35 km/h) and is forecast to accelerate 
further toward the northeast today. Earl is then forecast to slow 
down considerably Saturday night through Monday.

Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts. Slight fluctuations in intensity are possible today. Earl is
expected to complete its transition to a powerful hurricane-force
extratropical low on Saturday and then steadily weaken through
early Monday.

Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 961 mb (28.38 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Gusty winds are expected across the Avalon Peninsula of 
Newfoundland over the weekend after Earl becomes a post-tropical 
low.

SURF:  Swells generated by Earl are affecting Bermuda and portions
of the U.S. East Coast and are expected to reach Nova Scotia and
Newfoundland tonight and on Saturday. These swells are likely to
cause life-threatening surf and rip current conditions through the
weekend.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster D. Zelinsky


