

000
WTNT31 KNHC 100840
TCPAT1

BULLETIN
Hurricane Earl Advisory Number  30
NWS National Hurricane Center Miami FL       AL062022
500 AM AST Sat Sep 10 2022

...EARL FORECAST TO BECOME AN EXTRATROPICAL LOW THIS AFTERNOON...
...EXPECTED TO PRODUCE STRONG WINDS OVER EXTREME SOUTHEASTERN
NEWFOUNDLAND THIS AFTERNOON THROUGH SUNDAY...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...41.2N 53.5W
ABOUT 380 MI...610 KM S OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 35 MPH...56 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Earl was located
near latitude 41.2 North, longitude 53.5 West.  Earl is moving
rapidly toward the northeast near 35 mph (56 km/h).  A significant
reduction in forward speed is expected today, with Earl moving
slowly northeastward to the southeast of Newfoundland tonight
through Monday.

Maximum sustained winds are near 105 mph (165 km/h) with higher
gusts.  Earl is forecast to become a powerful hurricane-force
extratropical low this afternoon.  Weakening is expected during the
next few days, and Earl's winds are likely to fall below hurricane
force tonight or early Sunday.

Earl's wind field is expanding.  Hurricane-force winds extend
outward up to 90 miles (150 km) from the center and
tropical-storm-force winds extend outward up to 415 miles (665 km).

The estimated minimum central pressure is 955 mb (28.20 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Earl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1 and WMO header WTNT41 KNHC
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

WIND:  Strong winds are expected across the Avalon Peninsula of
Newfoundland this afternoon through Sunday, after Earl becomes a
post-tropical low.

SURF:  Swells generated by Earl will affect Bermuda, portions
of the U.S. East Coast, and Nova Scotia and Newfoundland in
Canada during the next several days.  These swells are likely to
cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Berg

