

574 
WTNT34 KNHC 112347
TCPAT4

BULLETIN
Tropical Storm Karl Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       AL142022
700 PM CDT Tue Oct 11 2022

...KARL MOVING SLOWLY NORTHWESTWARD OVER THE SOUTHWESTERN GULF 
OF MEXICO...


SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...20.1N 94.8W
ABOUT 110 MI...180 KM ENE OF VERACRUZ MEXICO
ABOUT 180 MI...290 KM ESE OF TUXPAN MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Cabo Rojo to Puerto Veracruz

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Storm Karl was
located near latitude 20.1 North, longitude 94.8 West. Karl is
moving toward the northwest near 6 mph (9 km/h), and this motion is
expected to continue for the next day or so.  A gradual turn to the
west and west-southwest is expected on Wednesday evening and a turn
to the southwest is forecast on Thursday morning.  On the forecast
track, Karl will be approaching the coast of Mexico on Thursday.

Maximum sustained winds are near 40 mph (65 km/h) with higher
gusts. Gradual strengthening is expected for the next day or so,
followed by gradual weakening on Thursday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The minimum central pressure estimated from Air Force Reserve 
reconnaissance data is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC.

RAINFALL:  Karl is expected to produce the following rainfall
totals:

*Isthmus of Tehuantepec...3 to 6 inches, with local maximum up to
10 inches.
*Southern Sierra Madre Oriental and adjacent coast...2 to 4 inches
with local maximum up to 6 inches.

WIND:  Tropical storm conditions are possible along the Mexican
coastline in the watch area starting Thursday.

SURF:  Swells generated by Karl are expected to effect the Mexican
coastline for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Brown


