
ZCZC MIATCPAT4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Karl Advisory Number   2
NWS National Hurricane Center Miami FL       AL142022
1000 PM CDT Tue Oct 11 2022

...KARL FORECAST TO STRENGTHEN TONIGHT AND WEDNESDAY WHILE IT MOVES
SLOWLY OVER THE SOUTHWESTERN GULF OF MEXICO...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.5N 94.9W
ABOUT 125 MI...200 KM NE OF VERACRUZ MEXICO
ABOUT 165 MI...265 KM ESE OF TUXPAN MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has extended the Tropical Storm Watch
southward to Roca Partida.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Cabo Rojo to Roca Partida

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Tropical Storm Karl was
located near latitude 20.5 North, longitude 94.9 West. Karl is
moving toward the north-northwest near 6 mph (9 km/h), and this
motion is expected to continue through Wednesday.  A turn to the
west and west-southwest is expected on Wednesday evening and a turn
to the southwest is forecast by Thursday morning.  On the forecast
track, Karl will be approaching the coast of Mexico within the
watch area on Thursday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Gradual strengthening is expected for the next day or so, followed
by gradual weakening on Thursday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce the following rainfall
totals:

*Isthmus of Tehuantepec...3 to 6 inches, with local maximum up to
10 inches.
*Southern Sierra Madre Oriental and adjacent coast...2 to 4 inches
with local maximum up to 6 inches.

WIND:  Tropical storm conditions are possible along the Mexican
coastline in the watch area starting Thursday.

SURF:  Swells generated by Karl are expected to effect the Mexican
coastline for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Brown

NNNN
