
ZCZC MIATCPAT4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Karl Advisory Number   3a
NWS National Hurricane Center Miami FL       AL142022
700 AM CDT Wed Oct 12 2022

...KARL MOVING SLOWLY AND BEGINNING TO STRENGTHEN...


SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...21.5N 94.8W
ABOUT 170 MI...275 KM ENE OF TUXPAN MEXICO
ABOUT 185 MI...300 KM NNE OF VERACRUZ MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...70 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Cabo Rojo to Roca Partida

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system. Additional watches or warnings may be
required for portions of the coast of Mexico later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Tropical Storm Karl was 
located near latitude 21.5 North, longitude 94.8 West. Karl is 
moving toward the north-northwest near 6 mph (9 km/h), and this 
motion is expected to continue through today.  A slow drift to the 
west and west-southwest is expected to begin later this morning and 
a somewhat faster motion toward the south-southwest is forecast by 
Thursday morning.  On the forecast track, Karl will be approaching 
the coast of Mexico within the watch area by Thursday night.

Data from an Air Force Reserve Hurricane Hunter aircraft support 
maximum sustained winds of 45 mph (70 km/h) with higher gusts. 
Additional strengthening is expected for the next day or so, 
followed by gradual weakening on Thursday.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.64 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 3 to 7 inches, with local 
maxima up to 12 inches of rain across portions of Veracruz and 
Tabasco states in Mexico through Friday night.  Flash flooding with 
mudslides in higher terrain is possible.

WIND:  Tropical storm conditions are possible along the Mexican
coastline in the watch area starting Thursday night.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Bucci

NNNN
