

000
WTNT34 KNHC 121453
TCPAT4

BULLETIN
Tropical Storm Karl Advisory Number   4
NWS National Hurricane Center Miami FL       AL142022
1000 AM CDT Wed Oct 12 2022

...AIR FORCE PLANE FINDS KARL MOVING SLOWLY NORTHWARD...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.7N 94.7W
ABOUT 200 MI...320 KM NNE OF VERACRUZ MEXICO
ABOUT 240 MI...390 KM N OF COATZACOALCOS MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has extended the Tropical Storm Watch
eastward to Frontera.  The Tropical Storm Watch from Cabo Rojo to
Tuxpan has been discontinued.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Tuxpan to Frontera

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system. Additional watches or warnings may be
required for portions of the coast of Mexico later today or tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Karl was 
located near latitude 21.7 North, longitude 94.7 West. Karl is 
moving toward the north near 3 mph (6 km/h) and this motion is 
expected to continue through today.  A slow drift to the south and 
south-southeast is expected to begin this evening and a faster 
generally southward motion is forecast by Thursday morning.  On the 
forecast track, Karl will be approaching the coast of Mexico within 
the watch area by Friday.

Data from an Air Force Reserve Hurricane Hunter aircraft support
maximum sustained winds of 45 mph (70 km/h) with higher gusts. 
Little change in strength is forecast during the next 36 hours 
followed by slight weakening before landfall.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 3 to 7 inches of rain, with
local maxima up to 12 inches, across portions of Veracruz and
Tabasco states in Mexico through Friday night. Rainfall amounts of 2
to 4 inches, with local maxima up to 6 inches, is also expected
across portions of Chiapas. Flash flooding with mudslides in higher
terrain is possible.

WIND:  Tropical storm conditions are possible along the Mexican
coastline in the watch area starting Friday.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Bucci/Brown

