

000
WTNT34 KNHC 122054
TCPAT4

BULLETIN
Tropical Storm Karl Advisory Number   6
NWS National Hurricane Center Miami FL       AL142022
400 PM CDT Wed Oct 12 2022

...KARL FORECAST TO MEANDER OVERNIGHT...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...22.2N 94.4W
ABOUT 240 MI...380 KM NNE OF VERACRUZ MEXICO
ABOUT 275 MI...445 KM N OF COATZACOALCOS MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Tuxpan to Frontera

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in southeastern Mexico should monitor the
progress of this system. Additional watches or warnings may be
required for portions of the coast of Mexico later tonight or on 
Thursday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Karl was
located near latitude 22.2 North, longitude 94.4 West. Karl is
moving toward the north near 2 mph (4 km/h).  The tropical storm 
is forecast to move little overnight, but a slow motion to the 
south-southeast is expected to begin by Thursday morning.  A
faster generally southward motion is forecast by late Thursday, and 
that motion should continue through Friday night.  On the forecast 
track, Karl will be approaching the coast of Mexico within the 
watch area on Friday.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Some slight strengthening is possible tonight, followed by gradual 
weakening until landfall.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center. NOAA buoy 42055 located about 30 miles east of the 
center of Karl recently reported a sustained wind of 45 mph (72 
km/h) with a gust to 51 mph (83 km/h). 

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 3 to 7 inches of rain, with
local maxima up to 12 inches, across portions of Veracruz and
Tabasco states in Mexico through Friday night. Rainfall amounts of 2
to 4 inches, with local maxima up to 6 inches, are also expected
across portions of Chiapas. Flash flooding with mudslides in higher
terrain is possible.

WIND:  Tropical storm conditions are possible along the Mexican
coastline in the watch area starting Friday.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Brown

