

000
WTNT34 KNHC 131443
TCPAT4

BULLETIN
Tropical Storm Karl Advisory Number   9
NWS National Hurricane Center Miami FL       AL142022
1000 AM CDT Thu Oct 13 2022

...KARL MOVING SOUTH-SOUTHEASTWARD...
...TROPICAL STORM WARNING ISSUED FOR A PORTION OF THE COAST OF
THE BAY OF CAMPECHE...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.7N 93.9W
ABOUT 245 MI...390 KM N OF COATZACOALCOS MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...SSE OR 155 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Tropical Storm Warning from 
Alvarado eastward to Ciudad del Carmen. The Tropical Storm Watch 
north of Alvarado has been discontinued.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Alvarado to Ciudad del Carmen

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Karl was
located near latitude 21.7 North, longitude 93.9 West. Karl is
moving toward the south-southeast near 5 mph (7 km/h), and this 
general motion should continue through tonight.  Karl is expected 
to turn southward or south-southwestward over the Bay of Campeche 
on Friday, and this motion should continue through early Saturday.  
On the forecast track, the center of Karl should reach the coasts 
of Tabasco or Veracruz states in Mexico late Friday night or early 
Saturday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Karl is forecast to gradually lose some strength later today or 
on Friday while it approaches the Bay of Campeche coast of Mexico.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.  NOAA buoy 42055 located just north of the center 
of Karl recently reported sustained winds of 38 mph (61 km/h) and a 
gust to 45 mph (72 km/h).

The minimum central pressure estimated from Air Force Reserve 
reconnaissance aircraft and NOAA buoy data is 1002 mb (29.59 
inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 3 to 7 inches of rain, with
local maxima up to 12 inches, across portions of Veracruz, Tabasco,
and northern Chiapas and Oaxaca states in Mexico from Friday into
Sunday morning. These rains could produce flash flooding, along
with mudslides, in higher terrain.

WIND:  Tropical storm conditions are expected to begin within
portions of the tropical storm warning area by late Friday or
Friday night.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Brown

