

000
WTNT34 KNHC 132355
TCPAT4

BULLETIN
Tropical Storm Karl Intermediate Advisory Number 10A
NWS National Hurricane Center Miami FL       AL142022
700 PM CDT Thu Oct 13 2022

...HURRICANE HUNTER AIRCRAFT INVESTIGATING TROPICAL STORM KARL 
OVER THE SOUTHWESTERN GULF OF MEXICO...


SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...20.8N 93.1W
ABOUT 200 MI...320 KM NNE OF COATZACOALCOS MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...SSE OR 155 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Alvarado to Ciudad del Carmen

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Storm Karl was
located near latitude 20.8 North, longitude 93.1 West. Karl is
moving toward the south-southeast near 7 mph (11 km/h), and this
general motion should continue through tonight. Karl is expected to
turn southward or south-southwestward over the Bay of Campeche on
Friday, and this motion should continue through early Saturday. On
the forecast track, the center of Karl should reach the coasts of
Tabasco or Veracruz states in Mexico within the warning area late
Friday night or early Saturday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Little change in strength is forecast during the next day or so, 
followed by weakening as Karl moves inland over southern Mexico.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

Data from an Air Force Reserve Hurricane Hunter Aircraft indicate 
that the minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 3 to 7 inches of rain, with
local maxima up to 10 inches, across portions of Veracruz, Tabasco,
and northern Chiapas and Oaxaca states in Mexico through Sunday
morning. These rains can produce flash flooding, along with
mudslides, in higher terrain.

WIND:  Tropical storm conditions are expected to begin within
portions of the tropical storm warning area by late Friday or Friday
night.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next couple of days. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Latto/Berg

