

000
WTNT34 KNHC 141149
TCPAT4

BULLETIN
Tropical Storm Karl Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       AL142022
700 AM CDT Fri Oct 14 2022

...AIR FORCE RESERVE HURRICANE HUNTERS ARE INVESTIGATING KARL...
...EXPECTED TO BRING HEAVY RAINFALL AND TROPICAL STORM CONDITIONS TO 
PORTIONS OF SOUTHERN MEXICO...


SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...19.9N 92.3W
ABOUT 90 MI...145 KM NNW OF CIUDAD DEL CARMEN MEXICO
ABOUT 185 MI...295 KM NE OF COATZACOALCOS MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...SE OR 145 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Alvarado to Sabancuy

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
24 to 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Tropical Storm Karl was 
located near latitude 19.9 North, longitude 92.3 West. Karl is 
moving toward the southeast near 6 mph (9 km/h). Karl is expected 
to turn southward or south-southwestward over the Bay of Campeche 
later today, and this motion should continue through early Saturday. 
On the forecast track, the center of Karl should reach the coast of 
southern Mexico late tonight or early Saturday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Little change in strength is expected before the center of Karl 
reaches the coast. Steady weakening is expected after the storm 
crosses the coastline, and the system is forecast to dissipate over 
southern Mexico by Saturday night.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center. A Mexican Navy station at Cayo Arcas recently
reported sustained winds of 31 mph (50 km/h) and a wind gust of 40
mph (64 km/h).

The estimated minimum central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 2 to 5 inches of rain, with
local maxima up to 10 inches, across portions of Veracruz, Tabasco,
and northern Chiapas and Oaxaca states in Mexico through Sunday
morning. These rains can produce flash flooding, along with
mudslides, in higher terrain.

WIND:  Tropical storm conditions are expected to begin within
portions of the tropical storm warning area by late today or
tonight.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next couple of days. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Reinhart

