

128 
WTNT34 KNHC 141446
TCPAT4

BULLETIN
Tropical Storm Karl Advisory Number  13
NWS National Hurricane Center Miami FL       AL142022
1000 AM CDT Fri Oct 14 2022

...TROPICAL STORM CONDITIONS EXPECTED TO SPREAD OVER PORTIONS OF
SOUTHERN MEXICO BEGINNING LATER TODAY...
...HEAVY RAINFALL COULD RESULT IN FLASH FLOODING AND MUDSLIDES
INTO THE WEEKEND...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...19.4N 92.7W
ABOUT 80 MI...130 KM NW OF CIUDAD DEL CARMEN MEXICO
ABOUT 140 MI...225 KM NE OF COATZACOALCOS MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...SSE OR 160 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm Warning
west of Coatzacoalcos to Alvarado.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Coatzacoalcos to Sabancuy

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
12 to 24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Karl was 
located near latitude 19.4 North, longitude 92.7 West. Karl is 
moving toward the south-southeast near 7 mph (11 km/h). A southward 
to south-southwestward motion is expected later today and tonight 
over the Bay of Campeche. On the forecast track, the center of Karl 
should reach the coast of southern Mexico late tonight or early 
Saturday.

Data from an Air Force Reserve Hurricane Hunter aircraft indicate 
that maximum sustained winds are near 45 mph (75 km/h) with higher 
gusts. Little change in strength is expected before the center of 
Karl reaches the coast. Steady weakening is expected after the storm 
crosses the coastline, and the system is forecast to dissipate over 
southern Mexico by Saturday night.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches) 
based on dropsonde data from the aircraft.


HAZARDS AFFECTING LAND
----------------------
Key messages for Karl can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/MIATCDAT4.shtml

RAINFALL:  Karl is expected to produce 2 to 5 inches of rain, with 
local maxima up to 10 inches, across portions of Veracruz, Tabasco, 
and northern Chiapas and Oaxaca states in Mexico through Sunday 
morning. These rains could produce flash flooding, along with 
mudslides, in higher terrain.

WIND:  Tropical storm conditions are expected to begin within
portions of the tropical storm warning area by this afternoon or
this evening.

SURF:  Swells generated by Karl are expected to affect the Mexican
coastline for the next couple of days. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Reinhart


