

000
WTNT34 KNHC 121447
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  21
NWS National Hurricane Center Miami FL       AL142023
300 PM GMT Tue Sep 12 2023

...EYE OF MARGOT HEADING NORTHWARD...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...30.2N 39.4W
ABOUT 890 MI...1430 KM SW OF THE AZORES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Hurricane Margot was located
near latitude 30.2 North, longitude 39.4 West. Margot is moving
toward the north near 12 mph (19 km/h). A turn toward the 
north-northwest at a slower forward speed is expected beginning 
tomorrow, followed by a turn back generally toward the north at an 
even slower speed on Thursday and Friday.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts. Little change in strength is expected for the next several 
days, but short term fluctions, up or down, are possible.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 255 miles
(405 km).

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Margot will begin to affect the Azores on
Wednesday. These swells are likely to cause life-threatening surf
and rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster D. Zelinsky

