

000
WTNT34 KNHC 122040
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  22
NWS National Hurricane Center Miami FL       AL142023
900 PM GMT Tue Sep 12 2023

...MARGOT CONTINUES NORTHWARD FOR NOW...
...FORECAST BEYOND FRIDAY HIGHLY UNCERTAIN...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...31.7N 39.6W
ABOUT 835 MI...1345 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...977 MB...28.85 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Hurricane Margot was located 
near latitude 31.7 North, longitude 39.6 West. Margot is moving 
toward the north near 14 mph (22 km/h). A turn toward the 
north-northwest at a slower forward speed is expected beginning 
tomorrow. A meandering northward motion is then expected on Thursday 
and Friday. Margot's track beyond Friday is unusually uncertain, but 
a slow meandering motion is generally expected into the weekend.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts. Slight fluctuations in intensity, up or down, are possible 
during the next several days.

Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 265
miles (425 km).

The estimated minimum central pressure is 977 mb (28.85 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Margot will begin to affect the Azores on
Wednesday. These swells are likely to cause life-threatening surf
and rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM GMT.

$$
Forecaster D. Zelinsky

