

144 
WTNT34 KNHC 130234
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  23
NWS National Hurricane Center Miami FL       AL142023
300 AM GMT Wed Sep 13 2023

...MARGOT A LITTLE STRONGER...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...32.7N 39.7W
ABOUT 800 MI...1290 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Hurricane Margot was located 
near latitude 32.7 North, longitude 39.7 West. Margot is moving 
toward the north near 12 mph (19 km/h). A north-northwestward or 
northward motion with a gradual decrease in forward speed is 
expected over the next couple of days. A slow meandering motion is 
expected on Friday and into the weekend.

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts. Slight fluctuations in intensity are possible 
during the next several days.

Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 265
miles (425 km).

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Margot will begin to affect the Azores on
Wednesday. These swells are likely to cause life-threatening surf
and rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Kelly


