

000
WTNT34 KNHC 131455
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  25
NWS National Hurricane Center Miami FL       AL142023
Issued by the NWS Weather Prediction Center College Park MD
300 PM GMT Wed Sep 13 2023

...MARGOT NOT EXPECTED TO MOVE MUCH OVER THE NEXT FEW DAYS...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...34.1N 40.4W
ABOUT 795 MI...1280 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Hurricane Margot was located
near latitude 34.1 North, longitude 40.4 West. Margot is moving
toward the north-northwest near 7 mph (11 km/h) and this motion with 
a gradual decrease in forward speed is expected through early 
Thursday. Then, Margot is likely to stall or meander within weak 
steering currents into the weekend.

Maximum sustained winds are near 90 mph (150 km/h) with higher
gusts.  Some weakening is forecast during the next 72 hours.

Satellite data indicated that Margot's hurricane-force winds 
extend outward up to 70 miles (110 km) from the center and 
tropical-storm-force winds extend outward up to 230 miles (370 km).

The estimated minimum central pressure is 970 mb (28.65 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Margot will begin to affect the Azores
later today. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Orrison/Blake

