

000
WTNT34 KNHC 140243
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  27
NWS National Hurricane Center Miami FL       AL142023
300 AM GMT Thu Sep 14 2023

...MARGOT TO MEANDER OVER THE NORTH ATLANTIC...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...35.2N 40.5W
ABOUT 770 MI...1245 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...N OR 10 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...972 MB...28.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Hurricane Margot was located 
near latitude 35.2 North, longitude 40.5 West. Margot is moving 
toward the north near 7 mph (11 km/h), and this motion is expected 
to continue with a gradual decrease in forward speed through 
Thursday. Margot is then likely to meander within weak steering 
currents through this weekend.

Maximum sustained winds have decreased to near 85 mph (140 km/h) 
with higher gusts. Steady weakening is forecast over the next few 
days.

Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 972 mb (28.71 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Kelly

