

000
WTNT34 KNHC 140847
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  28
NWS National Hurricane Center Miami FL       AL142023
900 AM GMT Thu Sep 14 2023

...MARGOT WEAKENS OVER THE CENTRAL ATLANTIC...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...35.9N 40.3W
ABOUT 745 MI...1205 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NNE OR 15 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Hurricane Margot was located
near latitude 35.9 North, longitude 40.3 West. Margot is moving
toward the north-northeast near 6 mph (9 km/h), and a slower 
forward motion is expected today. Margot is forecast to meander 
within weak steering currents on Friday and make a small clockwise 
loop over the weekend.

Maximum sustained winds have decreased to near 75 mph (120 km/h) 
with higher gusts. Continued weakening is forecast over the next few 
days, and Margot is likely to become a tropical storm later today.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 205 miles
(335 km).

The estimated minimum central pressure is 979 mb (28.91 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.

$$
Forecaster Reinhart

