

000
WTNT34 KNHC 141455
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  29
NWS National Hurricane Center Miami FL       AL142023
Issued by the NWS Weather Prediction Center College Park MD
300 PM GMT Thu Sep 14 2023

...MARGOT GROWING IN SIZE OVER THE NORTH-CENTRAL ATLANTIC...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...36.5N 39.8W
ABOUT 710 MI...1145 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Hurricane Margot was located
near latitude 36.5 North, longitude 39.8 West. Margot is moving
toward the north-northeast near 6 mph (9 km/h), and a slower
forward motion is expected today. Margot is forecast to meander
within weak steering currents on Friday and make a small clockwise
loop over the weekend.

Satellite-wind data indicate that the maximum sustained winds are 
near 80 mph (130 km/h) with higher gusts.  Gradual weakening is 
forecast over the next few days.

Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 978 mb (28.88 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Fracasso/Blake

