
ZCZC MIATCPAT4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Hurricane Margot Advisory Number  30
NWS National Hurricane Center Miami FL       AL142023
Issued by the NWS Weather Prediction Center College Park MD
900 PM GMT Thu Sep 14 2023

...MARGOT EXPECTED TO SLOWLY LOOP OVER THE NORTH-CENTRAL ATLANTIC
WELL WEST OF THE AZORES...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...36.9N 39.3W
ABOUT 680 MI...1090 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NE OR 50 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Hurricane Margot was located
near latitude 36.9 North, longitude 39.3 West. Margot is moving
toward the northeast near 5 mph (7 km/h), and this motion is 
expected to slow while Margot undergoes a clockwise loop well to the 
west of the Azores.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts.  Some weakening is forecast during the next 48 hours, and 
Margot should weaken to a tropical storm by Saturday.

Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 978 mb (28.88 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM GMT.

$$
Forecaster Roth/Blake

NNNN
