

000
WTNT34 KNHC 150231
TCPAT4

BULLETIN
Hurricane Margot Advisory Number  31
NWS National Hurricane Center Miami FL       AL142023
300 AM GMT Fri Sep 15 2023

...MARGOT CONTINUES TO MEANDER IN CENTRAL ATLANTIC...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...36.9N 38.9W
ABOUT 655 MI...1055 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...ENE OR 70 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...982 MB...29.00 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Hurricane Margot was located 
near latitude 36.9 North, longitude 38.9 West. Margot is moving 
toward the east-northeast near 3 mph (6 km/h) and a continued slow 
motion is expected while Margot undergoes a clockwise loop the next 
day or two.

Maximum sustained winds have decreased to near 75 mph (120 km/h) 
with higher gusts.  Gradual to steady weakening is forecast, and 
Margot should weaken to a tropical storm by Saturday.

Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 982 mb (29.00 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Kelly

