

630 
WTNT34 KNHC 150853
TCPAT4

BULLETIN
Tropical Storm Margot Advisory Number  32
NWS National Hurricane Center Miami FL       AL142023
900 AM GMT Fri Sep 15 2023

...MARGOT NOW A TROPICAL STORM...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...36.7N 38.6W
ABOUT 645 MI...1035 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...ESE OR 115 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...984 MB...29.06 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Tropical Storm Margot was
located near latitude 36.7 North, longitude 38.6 West. Margot is
drifting toward the east-southeast near 3 mph (6 km/h), and it is 
expected to make a slow clockwise loop during the next day or two. 
Then, a faster northeastward motion is forecast by Monday.

Maximum sustained winds have decreased to near 70 mph (110 km/h) 
with higher gusts. Some additional weakening is forecast during the 
next couple of days.

Tropical-storm-force winds extend outward up to 220 miles (350 km)
from the center.

The estimated minimum central pressure is 984 mb (29.06 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.

$$
Forecaster Reinhart


