

113 
WTNT34 KNHC 151453
TCPAT4

BULLETIN
Tropical Storm Margot Advisory Number  33
NWS National Hurricane Center Miami FL       AL142023
300 PM GMT Fri Sep 15 2023

...MARGOT'S TROPICAL-STORM-FORCE WINDS EXPAND NORTHWARD...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...36.3N 38.2W
ABOUT 625 MI...1010 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...SE OR 135 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Tropical Storm Margot was
located near latitude 36.3 North, longitude 38.2 West. Margot is
moving toward the southeast near 5 mph (7 km/h), and is expected to 
make a slow clockwise loop during the next day or two.  A faster 
northeastward motion is forecast by Monday.

Maximum sustained winds have decreased to near 65 mph (100 km/h) 
with higher gusts.  Some additional weakening is forecast during 
the next couple of days. 

Tropical-storm-force winds extend outward up to 300 miles (480 km)
from the center.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM GMT.

$$
Forecaster Bucci


