

000
WTNT34 KNHC 152040
TCPAT4

BULLETIN
Tropical Storm Margot Advisory Number  34
NWS National Hurricane Center Miami FL       AL142023
900 PM GMT Fri Sep 15 2023

...MARGOT MAKING A SLOW LOOP OVER THE NORTH-CENTRAL ATLANTIC...


SUMMARY OF 900 PM GMT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...36.0N 37.9W
ABOUT 615 MI...990 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...SE OR 135 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM GMT (2100 UTC), the center of Tropical Storm Margot was
located near latitude 36.0 North, longitude 37.9 West. Margot is
moving toward the southeast near 3 mph (6 km/h), and is expected to
make a slow clockwise loop during the next day or two.  A faster
northeastward motion is forecast by Monday.

Maximum sustained winds are near 65 mph (100 km/h) with higher 
gusts.  Some additional weakening is forecast during the next couple 
of days.

Tropical-storm-force winds extend outward up to 300 miles (480 km)
from the center.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM GMT.

$$
Forecaster Bucci

