
ZCZC MIATCPAT4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Margot Advisory Number  36
NWS National Hurricane Center Miami FL       AL142023
900 AM GMT Sat Sep 16 2023

...MARGOT A LITTLE WEAKER AS IT CONTINUES A CLOCKWISE LOOP OVER THE
NORTH-CENTRAL ATLANTIC...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...35.0N 38.3W
ABOUT 660 MI...1060 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...SW OR 220 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Tropical Storm Margot was
located near latitude 35.0 North, longitude 38.3 West. Margot is
moving toward the southwest near 7 mph (11 km/h) and is expected to
continue making a slow clockwise loop during the next day or two. A
faster northeastward to eastward motion is forecast by early next
week.

Maximum sustained winds have decreased to near 60 mph (95 km/h) 
with higher gusts. Additional weakening is forecast during the next
day or so, though Margot may re-intensify some by early next week.

Tropical-storm-force winds extend outward up to 300 miles (480 km)
from the center.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.

$$
Forecaster Papin

NNNN
