

000
WTNT34 KNHC 170244
TCPAT4

BULLETIN
Tropical Storm Margot Advisory Number  39
NWS National Hurricane Center Miami FL       AL142023
300 AM GMT Sun Sep 17 2023

...MARGOT WEAKENS...
...FORECAST TO BECOME POST-TROPICAL ON SUNDAY NIGHT OR MONDAY...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...33.9N 40.5W
ABOUT 805 MI...1295 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 260 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Tropical Storm Margot was
located near latitude 33.9 North, longitude 40.5 West. Margot is
moving toward the west near 8 mph (13 km/h)  A westward to
west-northwestward motion is expected during the next 24 hours.
A faster northward to northeastward motion is forecast to begin
Sunday night, and a east-northeastward is expected Monday and
Tuesday.

Maximum sustained winds have decreased to near 45 mph (75 km/h)
with higher gusts. Additional weakening is forecast during the next
day or so, and Margot is now forecast to become a post-tropical
cyclone by Sunday night or Monday.

Tropical-storm-force winds extend outward up to 185 miles (295 km)
from the center.

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot will continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Brown

