

982 
WTNT34 KNHC 170842
TCPAT4

BULLETIN
Tropical Storm Margot Advisory Number  40
NWS National Hurricane Center Miami FL       AL142023
900 AM GMT Sun Sep 17 2023

...MARGOT MAY NOT LAST MUCH LONGER...


SUMMARY OF 900 AM GMT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...34.0N 41.4W
ABOUT 850 MI...1365 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM GMT (0900 UTC), the center of Tropical Storm Margot was
located near latitude 34.0 North, longitude 41.4 West. Margot is
moving toward the west near 9 mph (15 km/h).  Margot is expected to 
turn northward on Monday and eastward on Tuesday.

Maximum sustained winds have decreased to near 40 mph (65 km/h) 
with higher gusts. Little change in strength is forecast during the 
next 72 hours, and Margot could degenerate into a post-tropical 
cyclone later today.

Tropical-storm-force winds extend outward up to 175 miles (280 km)
from the center.

The estimated minimum central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Margot should continue to affect the
Azores for the next several days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM GMT.

$$
Forecaster Blake


