012 
WTPZ34 KNHC 131436
TCPEP4
 
BULLETIN
Tropical Depression Four-E Advisory Number   4
NWS National Hurricane Center Miami FL       EP042025
900 AM CST Fri Jun 13 2025
 
...DISTURBANCE BECOMES TROPICAL DEPRESSION FOUR-E...
...TROPICAL STORM WARNING ISSUED FOR PORTIONS OF THE COAST OF
SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...13.9N 101.6W
ABOUT 260 MI...420 KM S OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has issued a Tropical Storm Warning for the
coast of Mexico from Lazaro Cardenas to Playa Perula, and a
Tropical Storm Watch north of Playa Perula to Cabo Corrientes.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Lazaro Cardenas to Playa Perula
 
A Tropical Storm Watch is in effect for...
* East of Lazaro Cardenas to Tecpan De Galeana
* North of Playa Perula to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
  
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Tropical Depression Four-E 
was located near latitude 13.9 North, longitude 101.6 West. The 
depression is moving toward the north-northwest near 10 mph (17 
km/h).  A turn toward the northwest is expected later today, with a 
turn toward the west-northwest forecast by Sunday.  On the forecast 
track, the disturbance is forecast to move parallel to, but offshore 
of, the southwestern coast of Mexico.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Strengthening is expected during the next couple of days. The
system is forecast to become a tropical storm later today and
continue strengthening on Saturday as it moves parallel to the coast
of southwestern Mexico.
 
The estimated minimum central pressure is 1005 mb (29.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Four-E can be found in the 
Tropical Cyclone Discussion under AWIPS header MIATCDEP4 and WMO
header WTPZ44 KNHC.
 
RAINFALL: Rainfall totals of 2 to 4 inches, with localized amounts 
up to 6 inches, are possible across portions of the Mexican states 
of Guerrero, Michoacán, and Colima through this weekend. This 
rainfall may lead to areas of flooding and mudslides. 

For a complete depiction of forecast rainfall associated with 
Tropical Depression Four-E, please see the National Weather Service 
Storm Total Rainfall Graphic available at 
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within the warning
area, and tropical storm conditions are possible within the watch
area on Saturday.
 
SURF: Swells generated by Tropical Depression Four-E will affect
portions of the coast of southwestern Mexico during the next few
days. These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM CST.
Next complete advisory at 300 PM CST.
 
$$
Forecaster Kelly
  