925 
WTPZ34 KNHC 132031
TCPEP4
 
BULLETIN
Tropical Storm Dalila Advisory Number   5
NWS National Hurricane Center Miami FL       EP042025
300 PM CST Fri Jun 13 2025
 
...DALILA BRINGING AREAS OF HEAVY RAINS AND STRONG WINDS ALONG THE
COAST OF SOUTHERN AND SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...14.8N 102.4W
ABOUT 205 MI...335 KM SSW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Lazaro Cardenas to Playa Perula
 
A Tropical Storm Watch is in effect for...
* East of Lazaro Cardenas to Tecpan De Galeana
* North of Playa Perula to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Tropical Storm Dalila was 
located near latitude 14.8 North, longitude 102.4 West. Dalila is 
moving toward the north-northwest near 14 mph (22 km/h). A turn 
toward the northwest is expected later today, with a turn toward the 
west forecast by Sunday. On the forecast track, Dalila is forecast 
to move parallel to, but offshore of, the southwestern coast of 
Mexico.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Gradual strengthening is expected during the next day or so. 
Weakening should begin by Sunday.
 
Dalila is a large system. Tropical-storm-force winds extend 
outward up to 310 miles (500 km) from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Dalila can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.
 
RAINFALL: Rainfall totals of 2 to 4 inches, with localized amounts
up to 6 inches, are possible across portions of the Mexican states
of Guerrero, Michoacán, and Colima through this weekend. This
rainfall may lead to areas of flooding and mudslides.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Dalila, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within the warning
area, and tropical storm conditions are possible within the watch
area tonight and Saturday.
 
SURF: Swells generated by Tropical Storm Dalila will affect
portions of the coast of southwestern Mexico during the next few
days. These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM CST.
Next complete advisory at 900 PM CST.
 
$$
Forecaster Cangialosi
  