000
WTPZ34 KNHC 140549
TCPEP4
 
BULLETIN
Tropical Storm Dalila Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       EP042025
1200 AM CST Sat Jun 14 2025
 
...DALILA CONTINUES TO MOVE NORTHWESTWARD OFFSHORE THE SOUTHWEST 
COAST OF MEXICO...
 
 
SUMMARY OF 1200 AM CST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.6N 103.2W
ABOUT 190 MI...305 KM SW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...72 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Tecpan De Galeana to Playa Perula
 
A Tropical Storm Watch is in effect for...
* North of Playa Perula to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1200 AM CST (0600 UTC), the center of Tropical Storm Dalila was 
located near latitude 15.6 North, longitude 103.2 West. Dalila is 
moving toward the northwest near 12 mph (19 km/h), and this general 
motion is expected to continue today. A turn toward the west is 
forecast by Sunday. On the forecast track, the center of Dalila is 
forecast to move parallel to, but offshore of, the southwestern 
coast of Mexico.
 
Maximum sustained winds are now near 45 mph (72 km/h) with higher 
gusts. Gradual strengthening is expected during the next day or so. 
Weakening should begin by Sunday.
 
Dalila is a large storm. Tropical-storm-force winds extend outward
up to 310 miles (500 km) from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Dalila can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.

RAINFALL: Rainfall totals of 3 to 6 inches are expected across
portions of the Mexican states of Guerrero, Michoacán, and Colima
through Sunday morning, with localized amounts up to 9 inches near
the coast. This rainfall will lead to areas of flooding and
mudslides, especially in areas of steep terrain near the coast.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Dalila, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within the warning
area and are possible within the watch area tonight and Saturday.
 
SURF: Swells generated by Tropical Storm Dalila will affect
portions of the coast of southwestern Mexico during the next few
days. These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.
 
$$
Forecaster Jelsema/Beven
  