ZCZC MIATCPEP4 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Tropical Storm Dalila Advisory Number   7
NWS National Hurricane Center Miami FL       EP042025
300 AM CST Sat Jun 14 2025
 
...DALILA STRENGTHENS OFFSHORE THE SOUTHWEST COAST OF MEXICO...
...TROPICAL STORM WARNING NOW IN EFFECT FROM PLAYA PERULA TO CABO
CORRIENTES...
 
 
SUMMARY OF 300 AM CST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.9N 103.9W
ABOUT 195 MI...315 KM SW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The government of Mexico has issued a Tropical Storm Warning for
the coast of Mexico from Playa Perula to Cabo Corrientes.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Tecpan De Galeana to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM CST (0900 UTC), the center of Tropical Storm Dalila was 
located near latitude 15.9 North, longitude 103.9 West. Dalila is 
moving toward the northwest near 12 mph (19 km/h), and a turn toward 
the west-northwest at a similar forward speed is expected today. A 
gradual turn toward the west is expected tonight and Sunday. On the 
forecast track, the center of Dalila is forecast to move parallel 
to, but offshore of, the southwestern coast of Mexico.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Some weakening is forecast during the next 48 hours. Some additional 
strengthening is expected today. Weakening is forecast to begin 
Sunday.
 
Tropical-storm-force winds extend outward up to 255 miles (405 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Dalila can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.
 
RAINFALL: Rainfall totals of 3 to 6 inches are expected across
portions of the Mexican states of Guerrero, Michoacán, and Colima
through Monday morning, with localized amounts up to 9 inches near
the coast. This rainfall will lead to areas of flooding and
mudslides, especially in areas of steep terrain near the coast.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Dalila, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within the warning area
today.
 
SURF: Swells generated by Tropical Storm Dalila will affect portions
of the coast of southwestern Mexico during the next couple days.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM CST.
Next complete advisory at 900 AM CST.
 
$$
Forecaster Jelsema/Beven
 
NNNN
  