127 
WTPZ34 KNHC 141434
TCPEP4
 
BULLETIN
Tropical Storm Dalila Advisory Number   8
NWS National Hurricane Center Miami FL       EP042025
900 AM CST Sat Jun 14 2025
 
...DALILA'S OUTER RAINBANDS AFFECTING SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...16.5N 104.8W
ABOUT 175 MI...285 KM S OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Tecpan De Galeana to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Tropical Storm Dalila was 
located near latitude 16.5 North, longitude 104.8 West. Dalila is 
moving toward the northwest near 12 mph (19 km/h). A gradual 
west-northwest to westward turn is expected later today into Sunday. 
On the forecast track, the center of Dalila is forecast to remain 
offshore the southwestern coast of Mexico.
 
Maximum sustained winds have increased to near 60 mph (95 km/h) with 
higher gusts. Some additional strengthening is possible today, with 
a weakening trend beginning on Sunday.
 
Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.
 
The estimated minimum central pressure is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Dalila can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.
 
RAINFALL: Additional rainfall amounts of 3 to 6 inches are expected
across portions of the Mexican states of Michoacán and Guerrero
through Sunday morning, with localized storm totals up to 9 inches
near the coast. This rainfall will lead to areas of flooding and
mudslides, especially in areas of steep terrain near the coast.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Dalila, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within the warning area
today.
 
SURF: Swells generated by Tropical Storm Dalila will affect portions
of the coast of southwestern Mexico during the next couple of days.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM CST.
Next complete advisory at 300 PM CST.
 
$$
Forecaster Kelly
  