824 
WTPZ34 KNHC 142342
TCPEP4
 
BULLETIN
Tropical Storm Dalila Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP042025
600 PM CST Sat Jun 14 2025
 
...DALILA CONTINUES TO BRING STRONG WINDS AND HEAVY RAIN TO 
PORTIONS OF SOUTHWEST MEXICO...
 
 
SUMMARY OF 600 PM CST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...17.2N 105.2W
ABOUT 135 MI...220 KM SSW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Tecpan De Galeana to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 PM CST (0000 UTC), the center of Tropical Storm Dalila was 
located near latitude 17.2 North, longitude 105.2 West. Dalila is 
moving toward the west-northwest near 10 mph (17 km/h). A gradual 
westward turn is expected tonight and Sunday. On the forecast track, 
the center of Dalila is forecast to remain offshore the southwestern 
coast of Mexico.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher 
gusts. Dalila is likely near its peak intensity and will gradually 
begin to weaken by Sunday.
 
Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.
 
The estimated minimum central pressure is 993 mb (29.33 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Dalila can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.

RAINFALL: Additional rainfall amounts of 2 to 4 inches are expected
across portions of the Mexican states of Michoacán and Guerrero
through Sunday morning, with localized storm totals up to 9 inches
near the coast. This rainfall will lead to areas of flooding and
mudslides, especially in areas of steep terrain near the coast.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Dalila, please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are expected within the warning area
through tonight.
 
SURF: Swells generated by Tropical Storm Dalila will affect portions
of the coast of southwestern Mexico during the next couple of days.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.
 
$$
Forecaster Jelsema/Gibbs/Cangialosi
  