634 
WTPZ34 KNHC 150844
TCPEP4
 
BULLETIN
Tropical Storm Dalila Advisory Number  11
NWS National Hurricane Center Miami FL       EP042025
200 AM MST Sun Jun 15 2025
 
...DALILA MOVING WESTWARD AND AWAY FROM THE COAST OF SOUTHWESTERN
MEXICO...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...18.0N 107.2W
ABOUT 200 MI...325 KM WSW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Lazaro Cardenas to Cabo Corrientes
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Tropical Storm Dalila was
located near latitude 18.0 North, longitude 107.2 West. Dalila is
moving toward the west-northwest near 14 mph (22 km/h). This 
general motion is expected during the next couple days, as Dalila 
moves farther offshore of the southwestern coast of Mexico. 
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts. Dalila has reached its peak intensity and will begin to 
weaken soon. Steady weakening is then forecast during the next 
couple of days, with the system becoming a post-tropical remnant 
low tonight or Monday.
  
Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.
 
The estimated minimum central pressure is 993 mb (29.33 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Dalila can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP4 and WMO header
WTPZ44 KNHC.
 
RAINFALL: Additional rainfall amounts of 1 to 2 inches are expected 
across portions of the Mexican states of Michoacán and Guerrero 
this morning, with localized storm totals up to 9 inches near the 
coast. Any instances of flash flooding and mudslides should 
decrease later today.

For a complete depiction of forecast rainfall associated with 
Tropical Storm Dalila, please see the National Weather Service Storm 
Total Rainfall Graphic available at 
hurricanes.gov/graphics_ep4.shtml?rainqpf

 
WIND: Tropical storm conditions are expected within the warning area
during the next few hours. Winds will diminish today as Dalila 
moves westward and farther away from the southwest coast of Mexico.
 
SURF: Swells generated by Tropical Storm Dalila will affect portions
of the coast of southwestern Mexico today. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 500 AM MST.
Next complete advisory at 800 AM MST.
 
$$
Forecaster Jelsema/Pasch
  