000
WTPZ34 KNHC 151436
TCPEP4
 
BULLETIN
Tropical Storm Dalila Advisory Number  12
NWS National Hurricane Center Miami FL       EP042025
800 AM MST Sun Jun 15 2025
 
...DALILA WEAKENING WHILE MOVING OVER COOLER WATERS...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...18.2N 107.8W
ABOUT 235 MI...380 KM WSW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Tropical Storm Dalila was 
located near latitude 18.2 North, longitude 107.8 West. Dalila is 
moving toward the west-northwest near 9 mph (15 km/h). A gradual 
turn towards the west will occur later today, with a continued 
westward motion the next couple of days
 
Maximum sustained winds have decreased to near 50 mph (85 km/h) 
with higher gusts. Steady weakening is forecast the during the next 
few days, and the system is expected to become a remnant low 
tonight or Monday.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Additional rainfall amounts of 1 to 2 inches are 
possible across portions of the Mexican states of Nayarit, Jalisco, 
Colima, and Michoacán today, with localized storm totals up to 9 
inches near the coast. Any instances of flash flooding and mudslides 
should decrease today.

For a complete depiction of forecast rainfall associated with 
Tropical Storm Dalila, please see the National Weather Service Storm 
Total Rainfall Graphic available at 
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
SURF: Swells generated by Tropical Storm Dalila will affect portions 
of the coast of southwestern Mexico today. These swells are likely 
to cause life-threatening surf and rip current conditions. Please 
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Kelly
  