165 
WTPZ34 KNHC 152038
TCPEP4
 
BULLETIN
Tropical Storm Dalila Advisory Number  13
NWS National Hurricane Center Miami FL       EP042025
200 PM MST Sun Jun 15 2025
 
...DALILA EXPECTED TO BECOME A POST-TROPICAL CYCLONE LATER TODAY...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.2N 108.4W
ABOUT 275 MI...440 KM W OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Tropical Storm Dalila was
located near latitude 18.2 North, longitude 108.4 West. Dalila is
moving toward the west-northwest near 8 mph (13 km/h). A gradual
turn towards the west will occur later today, with a continued
westward motion the next couple of days.
 
Maximum sustained winds have decreased to near 45 mph (75 km/h) with
higher gusts. Steady weakening is forecast the during the next
couple of days, and the system is expected to become a remnant low
later tonight.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Tropical Storm Dalila will affect portions
of the coast of southwestern Mexico today. These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Bucci
  