872 
WTPZ34 KNHC 131134
TCPEP4
 
BULLETIN
Potential Tropical Cyclone Four-E Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       EP042025
600 AM CST Fri Jun 13 2025
 
...DISTURBANCE BECOMING BETTER ORGANIZED AND EXPECTED TO BECOME A 
TROPICAL STORM LATER TODAY...
...TROPICAL STORM WATCH REMAINS IN EFFECT FOR THE COAST OF
SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 600 AM CST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...13.4N 101.3W
ABOUT 295 MI...475 KM S OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Tecpan De Galeana to Manzanillo
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
A Tropical Storm Warning may be required for portions of the watch
area later today. The Tropical Storm Watch may need to be extended 
northward later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 600 AM CST (1200 UTC), the disturbance was centered near latitude
13.4 North, longitude 101.3 West. The system is moving toward the
north-northwest near 9 mph (15 km/h). A turn toward the northwest is
expected later today, with a turn toward the west-northwest forecast
by Sunday.  On the forecast track, the disturbance is forecast to
move parallel to, but offshore of, the southwestern coast of Mexico.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Strengthening is expected during the next couple of days. The
system is forecast to become a tropical storm later today and
continue strengthening on Saturday as it moves parallel to the coast
of southwestern Mexico.
* Formation chance through 48 hours...high ...near 100 percent.
* Formation chance through 7 days...high...near 100 percent.
 
The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Four-E can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDEP4 and WMO
header WTPZ44 KNHC.
 
RAINFALL: Rainfall totals of 2 to 4 inches, with localized amounts
up to 6 inches, are possible across portions of the Mexican states
of Guerrero, Michoacán, and Colima through this weekend. This
rainfall may lead to areas of flooding and mudslides.
 
For a complete depiction of forecast rainfall associated with
Potential Tropical Cyclone Four-E, please see the National Weather
Service Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
WIND: Tropical storm conditions are possible within the watch area
on Saturday.
 
SURF: Swells generated by Potential Tropical Cyclone Four-E will
affect portions of the coast of southwestern Mexico during the next
few days. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.
 
$$
Forecaster Kelly
  