

000
WTPZ34 KNHC 161456
TCPEP4

BULLETIN
Tropical Storm Hilary Advisory Number   1
NWS National Hurricane Center Miami FL       EP092023
1000 AM CDT Wed Aug 16 2023

...TROPICAL STORM HILARY FORMS...
...EXPECTED TO STRENGTHEN...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...12.4N 102.6W
ABOUT 470 MI...755 KM SSE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Hilary was
located near latitude 12.4 North, longitude 102.6 West. Hilary is
moving toward the west-northwest near 14 mph (22 km/h) and this
general motion is expected to continue with a gradual turn to the
northwest in a day or so.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Steady to rapid strengthening is forecast for the next few days.
Hilary is expected to become a hurricane on Thursday.

Tropical-storm-force winds extend outward up to 205 miles (335 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Large swells generated by Hilary will affect portions of the 
coast of southwestern Mexico and the Baja California peninsula over 
the next few days.  These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Bucci

