

000
WTPZ34 KNHC 170856
TCPEP4

BULLETIN
Tropical Storm Hilary Advisory Number   4
NWS National Hurricane Center Miami FL       EP092023
300 AM MDT Thu Aug 17 2023

...HILARY FORECAST TO RAPIDLY INTENSIFY AND BECOME A HURRICANE
VERY SOON...
...TROPICAL STORM WATCH ISSUED FOR THE SOUTHERN PORTION OF BAJA
CALIFORNIA SUR...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...14.6N 106.3W
ABOUT 330 MI...535 KM SSW OF MANZANILLO MEXICO
ABOUT 620 MI...995 KM SSE OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Tropical Storm Watch for the
southern portion of Baja California Sur from Cabo San Lazaro
southward on the west coast and San Evaristo southward on the east
coast.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Baja California Sur Mexico from Cabo San Lazaro southward
* Baja California Sur Mexico from San Evaristo southward

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere on the Baja California peninsula and along the
coast of northwestern mainland Mexico should closely monitor the
progress of Hilary.  Additional watches or warnings will likely be
required for a portion of this area later today.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Tropical Storm Hilary was
located near latitude 14.6 North, longitude 106.3 West.  Hilary is
moving toward the west-northwest near 13 mph (20 km/h), and this
general motion is expected to continue through tonight.  A turn 
toward the northwest is expected Friday morning, followed by a turn 
toward the north-northwest and north on Saturday.  On the forecast 
track, the center of Hilary will approach the Baja California 
peninsula over the weekend.

Maximum sustained winds have increased to near 70 mph (110 km/h) 
with higher gusts.  Rapid strengthening is forecast, and Hilary 
will become a hurricane very soon.  It could become a major 
hurricane by tonight or early Friday.

Tropical-storm-force winds extend outward up to 275 miles (445 km)
from the center.

The estimated minimum central pressure is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Tropical storm conditions are possible within the watch
area by Friday night or early Saturday.

RAINFALL:  Hilary is expected to produce rainfall amounts of 3 to 6
inches, with isolated maximum amounts of 8 inches, across portions
of the Baja California Peninsula through Monday morning.  Flash
flooding, locally significant, will be possible.

Heavy rainfall in association with Hilary is expected to impact the
Southwestern United States from Friday through early next week,
peaking on Sunday and Monday.

SURF:  Large swells generated by Hilary will affect portions of the
coast of southwestern Mexico and the Baja California peninsula over
the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 AM MDT.
Next complete advisory at 900 AM MDT.

$$
Forecaster Berg

