

000
WTPZ34 KNHC 172055
TCPEP4

BULLETIN
Hurricane Hilary Advisory Number   6
NWS National Hurricane Center Miami FL       EP092023
300 PM MDT Thu Aug 17 2023

...HILARY APPROACHING MAJOR HURRICANE STATUS...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...16.1N 108.9W
ABOUT 475 MI...765 KM S OF CABO SAN LUCAS MEXICO
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has extended the Tropical Storm Watch
northward on the west coast of the Baja California peninsula
to Punta Abreojos, and northward on the east coast of the Baja
California peninsula to Loreto.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Baja California Sur Mexico from Cabo San Lazaro southward
* Baja California Sur Mexico from Los Barriles southward

A Tropical Storm Watch is in effect for...
* North of Cabo San Lazaro to Punta Abreojos
* North of Los Barriles to Loreto

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere on the Baja California peninsula, along the 
coast of northwestern mainland Mexico, and the southwestern United 
States coastline should closely monitor the progress of Hilary.  
Additional watches or warnings will likely be required for portions 
of these areas later tonight and Friday. 

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Hurricane Hilary was located
near latitude 16.1 North, longitude 108.9 West. Hilary is moving
toward the west-northwest near 14 mph (22 km/h), and this general
motion is expected to continue through tonight.  A turn toward the
northwest is expected Friday morning, followed by a turn toward the
north-northwest and north on Saturday.  On the forecast track, the
center of Hilary will approach the Baja California peninsula over
the weekend.

Maximum sustained winds have increased to near 110 mph (175 km/h)
with higher gusts.  Additional rapid strengthening is forecast
during the next day or so, and Hilary is likely to become a major
hurricane later today.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 275 miles
(445 km).

The estimated minimum central pressure is 960 mb (28.35 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Hilary is expected to produce rainfall amounts of 3 to 6
inches, with isolated maximum amounts up to 10 inches, across
portions of the Baja California Peninsula through Sunday night.
Flash flooding, locally significant, will be possible.

Heavy rainfall in association with Hilary is expected to impact the
Southwestern United States from Friday through early next week,
peaking on Sunday and Monday. Rainfall amounts of 2 to 4 inches,
with isolated amounts in excess of 8 inches, will be possible across
portions of southern California and southern Nevada.

WIND:  Tropical storm conditions are expected within the warning
area by late Friday, and are possible within the watch area by
early Saturday.

SURF:  Large swells generated by Hilary will affect portions of the
coast of southwestern Mexico and the Baja California peninsula over
the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM MDT.
Next complete advisory at 900 PM MDT.

$$
Forecaster Pasch

