

000
WTPZ34 KNHC 202359
TCPEP4

BULLETIN
Tropical Storm Hilary Intermediate Advisory Number 18A
NWS National Hurricane Center Miami FL       EP092023
500 PM PDT Sun Aug 20 2023

...CENTER OF HILARY MOVES INTO SOUTHERN CALIFORNIA...
...CATASTROPHIC AND LIFE-THREATENING FLOODING LIKELY OVER NORTHERN 
BAJA CALIFORNIA AND PORTIONS OF THE SOUTHWESTERN U.S. THROUGH 
MONDAY...


SUMMARY OF 500 PM PDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...33.5N 116.7W
ABOUT 25 MI...40 KM SSW OF PALM SPRINGS CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm
Warning south of San Jose de Las Palmas on the west coast and south 
of Isla San Luis on the east coast of the Baja California Peninsula.
The warning has also been discontinue south of Puerto Libertad on 
northwest coast of mainland Mexico. 


SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Baja California peninsula west coast from San Jose de Las Palms 
northward
* Baja California peninsula east coast from Isla San Luis northward
* Mainland Mexico north of Puerto Libertad
* California/Mexico border to Point Mugu
* Catalina Island

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning.

Interests elsewhere in the southwestern U.S. should monitor the
progress of Hilary.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM PDT (0000 UTC), the center of Tropical Storm Hilary was
located inland near latitude 33.5 North, longitude 116.7 West.
Hilary is moving toward the north near 23 mph (37 km/h) and the
storm is expected to accelerate even more as it moves
north-northwestward to northward during the next day or so.  On the
forecast track, the center of Hilary will move across southern
California this evening.

Maximum sustained winds are near 50 mph (85 km/h) with higher
gusts. Weakening is expected to continue, and Hilary is forecast to 
become a post-tropical cyclone overnight.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.  A sustained wind of 45 mph (72 km/h) with a gust 
to 69 mph (111 km/h) was reported in Yuma, Arizona within the past 
couple of hours. A sustained wind of 40 mph (65 km/h) with a gust 
to 63 mph (102 km/h) was recently reported at Imperial County 
Airport in Imperial, California. 

The estimated minimum central pressure is 997 mb (29.44 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hilary can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml.

RAINFALL:  Hilary is expected to produce storm total rainfall
amounts of 3 to 6 inches, with maximum amounts up to 10 inches,
across portions of the northern Baja California Peninsula through
tonight. Flash and urban flooding, locally catastrophic, is
expected.

Intense heavy rainfall associated with Hilary is expected across the
Southwestern United States through early Monday morning. Rainfall
amounts of 3 to 6 inches, with isolated maximum amounts of 10
inches, are expected across portions of southern California and
southern Nevada leading to dangerous to catastrophic flooding.
Across portions of Oregon and Idaho, rainfall totals of 1 to 3
inches with local maxima to 5 inches are expected through Tuesday
morning, resulting in localized significant flash flooding.

A list of rainfall observations compiled by the NOAA Weather
Prediction Center for this storm can be found at:
www.wpc.ncep.noaa.gov/discussions/nfdscc4.html

WIND:  Tropical storm conditions will continue through the evening
in the Tropical Storm Warning area in the northern portions of 
the Baja California Peninsula.  Tropical storm conditions will 
continue into tonight in the warning area in southern California.

Winds could be particularly strong and gusty in and near areas of
elevated terrain.  Higher gusts are expected well inland and will
persist even after the system becomes post-tropical.

STORM SURGE:  Coastal flooding is possible along the northern coast 
of the Gulf of California through early Monday.

TORNADOES: A couple tornadoes are possible through this evening over
southeast California, western Arizona, southern Nevada, and far
southwest Utah.

SURF:  Large swells generated by Hilary will affect portions of the
Baja California Peninsula and southern California over the next
day or so.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Brown

