

150 
WTPZ34 KNHC 210251
TCPEP4

BULLETIN
Tropical Storm Hilary Advisory Number  19
NWS National Hurricane Center Miami FL       EP092023
800 PM PDT Sun Aug 20 2023

...CENTER OF HILARY MOVING NEAR THE COAST OF SOUTHERN CALIFORNIA...
...CATASTROPHIC AND LIFE-THREATENING FLOODING LIKELY OVER NORTHERN
BAJA CALIFORNIA AND PORTIONS OF THE SOUTHWESTERN U.S. THROUGH
MONDAY...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...33.9N 118.2W
ABOUT 105 MI...170 KM NW OF SAN DIEGO CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 28 MPH...44 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm
Warning for the west coast of the Baja California peninsula and
for the east coast of the Baja California peninsula south of San
Felipe. The warning has also been discontinued south of Puerto
Penasco along the coast of mainland Mexico.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* San Felipe to Puerto Penasco, Mexico
* California/Mexico border to Point Mugu
* Catalina Island

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning.

Interests elsewhere in the southwestern U.S. should monitor the
progress of Hilary.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Hilary was
located near latitude 33.9 North, longitude 118.2 West. Hilary is
moving toward the north-northwest near 28 mph (44 km/h), and this 
general motion is expected to continue into Monday. On the forecast 
track, the center of Hilary will move across portions of southern 
California through early Monday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Weakening is expected to continue, and Hilary is forecast to become 
a post-tropical cyclone by early Monday.

Tropical-storm-force winds extend outward up to 230 miles (370 km), 
primarily to the east of the center. A sustained wind of 41 mph (66 
km/h) and a gust of 54 mph (87 km/h) was recently reported at the 
Salton Sea in southern California.

The estimated minimum central pressure based on surface observations 
is 998 mb (29.47 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hilary can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC
and on the web at hurricanes.gov/text/MIATCDEP4.shtml.

RAINFALL:  Hilary is expected to produce storm total rainfall
amounts of 3 to 6 inches, with maximum amounts up to 10 inches,
across portions of the northern Baja California Peninsula through
Sunday night. Flash and urban flooding, locally catastrophic, is
expected.

Intense heavy rainfall associated with Hilary is expected across the
Southwestern United States through early Monday morning. Rainfall
amounts of 3 to 6 inches, with isolated maximum amounts of 10
inches, are expected across portions of southern California and
southern Nevada leading to dangerous to catastrophic flooding.
Across portions of Oregon and Idaho, rainfall totals of 1 to 3
inches with local maxima to 5 inches are expected through Tuesday
morning, resulting in localized, some significant, flash flooding.

A list of rainfall observations compiled by the NOAA Weather
Prediction Center for this storm can be found at:
www.wpc.ncep.noaa.gov/discussions/nfdscc4.html

WIND:  Tropical storm conditions will continue for the next few
hours within the Tropical Storm Warning area along the northern Gulf
of California. Tropical storm conditions will continue into tonight
in the warning area in southern California.

Winds could be particularly strong and gusty in and near areas of
elevated terrain.  Higher gusts are expected well inland and will
persist even after the system becomes post-tropical.

STORM SURGE:  Coastal flooding is possible along the northern coast
of the Gulf of California through early Monday.

TORNADOES: A brief tornado or two will be possible this evening
across southeast California, northwest Arizona, southern Nevada and
far southwest Utah.

SURF:  Large swells generated by Hilary will affect portions of the
Baja California Peninsula and southern California through early
Monday. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1100 PM PDT.
Next complete advisory at 200 AM PDT.

$$
Forecaster Reinhart


