

103 
WTNT33 KNHC 070832
TCPAT3

BULLETIN
Hurricane Lee Advisory Number   8
NWS National Hurricane Center Miami FL       AL132023
500 AM AST Thu Sep 07 2023

...LEE FORECAST TO RAPIDLY STRENGTHEN...
...LARGE SWELLS LIKELY TO REACH THE LESSER ANTILLES, THE
VIRGIN ISLANDS, AND PUERTO RICO THROUGH THE WEEKEND...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.1N 48.6W
ABOUT 965 MI...1555 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.21 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the northern Leeward Islands should monitor the
progress of Lee.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Lee was located 
near latitude 16.1 North, longitude 48.6 West. Lee is moving toward 
the west-northwest near 14 mph (22 km/h) and this motion is expected 
to continue through Friday.  A slower motion toward the 
west-northwest is forecast over the weekend.

Maximum sustained winds remain near 80 mph (130 km/h) with higher
gusts.  Rapid intensification is expected to begin later today, 
and Lee is forecast to become a major hurricane by early Friday.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure is 989 mb (29.21 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

SURF:  Swells generated by Lee are expected to reach portions of
the Lesser Antilles on Friday, and reach the British and U.S.
Virgin Islands, Puerto Rico, Hispaniola, the Bahamas, and Bermuda
this weekend.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Cangialosi


