

000
WTNT33 KNHC 081453
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  13
NWS National Hurricane Center Miami FL       AL132023
1100 AM AST Fri Sep 08 2023

...LEE EXPECTED TO REMAIN A POWERFUL HURRICANE THROUGH EARLY NEXT 
WEEK...
...DANGEROUS BEACH CONDITIONS EXPECTED TO DEVELOP AROUND THE
WESTERN ATLANTIC THROUGH EARLY NEXT WEEK...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.2N 54.5W
ABOUT 565 MI...910 KM E OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...155 MPH...250 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...942 MB...27.82 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Lee was located
near latitude 18.2 North, longitude 54.5 West. Lee is moving toward
the west-northwest near 13 mph (20 km/h)  and this motion is
expected to continue through early next week with a significant
decrease in forward speed.  On the forecast track, Lee is expected
to pass well to the north of the northern Leeward Islands, the
Virgin Islands, and Puerto Rico over the weekend and into early
next week.

Maximum sustained winds are near 155 mph (250 km/h) with higher
gusts.  Lee is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Some fluctuations in intensity are likely 
over the next few days, however Lee is expected to remain a 
powerful hurricane through early next week.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).

The estimated minimum central pressure is 942 mb (27.82 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

SURF:  Swells generated by Lee are expected to reach portions of the
Lesser Antilles later today, and reach the British and U.S. Virgin
Islands, Puerto Rico, Hispaniola, the Turks and Caicos Islands, the
Bahamas, and Bermuda this weekend. These swells are likely to cause
life-threatening surf and rip current conditions. Dangerous surf and
rip currents are expected to begin along most of the U.S. East Coast
beginning Sunday.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Brown

