

000
WTNT33 KNHC 092035
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  18
NWS National Hurricane Center Miami FL       AL132023
500 PM AST Sat Sep 09 2023

...LEE TO PASS WELL NORTH OF THE LEEWARD ISLANDS DURING THE NEXT
DAY OR SO...
...HAZARDOUS BEACH CONDITIONS EXPECTED TO DEVELOP AROUND THE WESTERN
ATLANTIC THROUGH NEXT WEEK...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...20.7N 59.1W
ABOUT 310 MI...505 KM NE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...958 MB...28.29 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Lee was located
near latitude 20.7 North, longitude 59.1 West. Lee is moving toward
the west-northwest near 10 mph (17 km/h).  A slower west- 
northwestward motion is expected during the next few days.  On the
forecast track, Lee is expected to pass well to the north of the
northern Leeward Islands, the Virgin Islands, and Puerto Rico into
early next week.

Maximum sustained winds are near 115 mph (185 km/h) with higher
gusts.  Lee is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Gradual restrengthening is possible during 
the next couple of days. 

Hurricane-force winds extend outward up to 40 miles (65 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km). NOAA buoy 40144 located about 85 miles north-northeast of 
the center of Lee has reported a peak sustained wind of 54 mph (86 
km/h) with a gust to 67 mph (107 km/h) within the past couple of 
hours. 

The estimated minimum central pressure is 958 mb (28.29 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

SURF:  Swells generated by Lee are affecting portions of the Lesser 
Antilles, and are spreading westward to the British and U.S. Virgin 
Islands, Puerto Rico, Hispaniola, the Turks and Caicos Islands, the 
Bahamas, and Bermuda through this weekend. These swells are likely 
to cause life-threatening surf and rip current conditions. Dangerous 
surf and rip currents are expected to begin along most of the U.S. 
East Coast on Sunday and Monday and worsen through the week. Please 
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Brown

