

000
WTNT33 KNHC 100241
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  19
NWS National Hurricane Center Miami FL       AL132023
1100 PM AST Sat Sep 09 2023

...LEE EXPECTED TO GROW IN SIZE OVER THE NEXT FEW DAYS...
...HAZARDOUS BEACH CONDITIONS EXPECTED TO DEVELOP AROUND THE WESTERN
ATLANTIC OVER THE UPCOMING WEEK...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.0N 59.9W
ABOUT 285 MI...455 KM NE OF THE NORTHERN LEEWARD ISLANDS
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Lee was located 
near latitude 21.0 North, longitude 59.9 West. Lee is moving toward 
the west-northwest near 9 mph (15 km/h). A slower west-northwestward 
motion is expected during the next few days. On the forecast track, 
Lee is expected to pass well north of the northern Leeward Islands, 
the Virgin Islands, and Puerto Rico into early next week.

Maximum sustained winds are near 105 mph (165 km/h) with higher 
gusts. Restrengthening is anticipated over the next day or two.

Hurricane-force winds extend outward up to 35 miles (55 km) from the 
center and tropical-storm-force winds extend outward up to 185 miles 
(295 km). NOAA buoy 40144 located about 90 miles east-northeast of 
the center of Lee reported a peak sustained wind of 52 mph (83 
km/h) with a gust to 60 mph (98 km/h) within the past couple of 
hours.

The minimum central pressure measured by the NOAA hurricane hunter 
aircraft is 962 mb (28.41 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

SURF:  Swells generated by Lee are affecting portions of the Lesser
Antilles, and are spreading westward to the British and U.S. Virgin
Islands, Puerto Rico, Hispaniola, the Turks and Caicos Islands, the
Bahamas, and Bermuda over the remainder of this weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Dangerous surf and rip currents are expected to begin
along most of the U.S. East Coast tomorrow and worsen through next
week. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Papin

