

000
WTNT33 KNHC 110247
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  23
NWS National Hurricane Center Miami FL       AL132023
1100 PM AST Sun Sep 10 2023

...LEE GROWING LARGER BUT MAXIMUM SUSTAINED WINDS HAVE NOT YET
INCREASED...
...HAZARDOUS BEACH CONDITIONS EXPECTED TO SPREAD THROUGH THE WESTERN
ATLANTIC DURING THE WEEK...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...22.6N 62.2W
ABOUT 310 MI...500 KM N OF THE NORTHERN LEEWARD ISLANDS
ABOUT 690 MI...1110 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...950 MB...28.06 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Lee was located 
near latitude 22.6 North, longitude 62.2 West. Lee is moving toward 
the northwest near 8 mph (13 km/h). A slower west-northwestward 
motion is expected during the next few days. On the forecast track, 
Lee is expected to pass well north of the northern Leeward Islands, 
the Virgin Islands, and Puerto Rico during the next day or two.

NOAA aircraft data indicate that maximum sustained winds remain 
near 120 mph (195 km/h) with higher gusts. Lee is a category 3 
hurricane on the Saffir-Simpson Hurricane Wind Scale. Additional 
strengthening is forecast over the next day or so, followed by 
gradual weakening.

Lee has been growing in size, with hurricane-force winds now 
extending outward up to 75 miles (120 km) from the center and 
tropical-storm-force winds extending outward up to 175 miles (280 
km).

The minimum central pressure measured by NOAA reconnaissance
aircraft is 950 mb (28.06 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

SURF:  Swells generated by Lee are affecting portions of the Lesser 
Antilles, the British and U.S. Virgin Islands, Puerto Rico, 
Hispaniola, the Turks and Caicos Islands, the Bahamas, and Bermuda. 
These swells are likely to cause life-threatening surf and rip 
current conditions. Dangerous surf and rip currents have begun to 
reach portions of the southeast U.S. coast and are forecast to 
worsen and spread northward along much of the U.S. East Coast during 
the next couple of days. Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Papin

