

000
WTNT33 KNHC 110851
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  24
NWS National Hurricane Center Miami FL       AL132023
500 AM AST Mon Sep 11 2023

...LARGE LEE REMAINS A MAJOR HURRICANE...
...HAZARDOUS SURF AND RIP CURRENT CONDITIONS EXPECTED AT BEACHES
ACROSS THE WESTERN ATLANTIC DURING THE WEEK...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...23.1N 62.6W
ABOUT 340 MI...545 KM N OF THE NORTHERN LEEWARD ISLANDS
ABOUT 650 MI...1045 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...950 MB...28.06 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Lee was located
near latitude 23.1 North, longitude 62.6 West. Lee is moving toward
the northwest near 7 mph (11 km/h). A slow west-northwestward
motion is expected during the next couple of days, followed by a
gradual turn toward the north by midweek. On the forecast track,
Lee is expected to pass well north of the northern Leeward Islands,
the Virgin Islands, and Puerto Rico during the next day or two.

Maximum sustained winds are near 120 mph (195 km/h) with higher 
gusts. Lee is a category 3 hurricane on the Saffir-Simpson Hurricane 
Wind Scale. Some additional strengthening is forecast over the next 
day or so, followed by gradual weakening.

Hurricane-force winds extend outward up to 75 miles (120 km) from
the center and tropical-storm-force winds extend outward up to 185
miles (295 km).

The estimated minimum central pressure is 950 mb (28.06 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

SURF:  Swells generated by Lee are affecting portions of the Lesser
Antilles, the British and U.S. Virgin Islands, Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, and Bermuda.
These swells are likely to cause life-threatening surf and rip
current conditions. Dangerous surf and rip currents have begun to
affect portions of the southeastern U.S. coast, and these conditions
are forecast to spread northward along much of the U.S. East Coast
during the next couple of days. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Reinhart

