

000
WTNT33 KNHC 121758
TCPAT3

BULLETIN
Hurricane Lee Intermediate Advisory Number 29A
NWS National Hurricane Center Miami FL       AL132023
Issued by the NWS Weather Prediction Center College Park MD
200 PM AST Tue Sep 12 2023

...AIR FORCE HURRICANE HUNTER CURRENTLY INVESTIGATING LEE...
...HAZARDOUS SURF AND RIP CURRENT CONDITIONS EXPECTED AT BEACHES
ACROSS THE WESTERN ATLANTIC ALL WEEK...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...24.5N 66.2W
ABOUT 545 MI...875 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...951 MB...28.09 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in the northeastern United States and Atlantic Canada
should monitor the progress of Lee.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Hurricane Lee was located
near latitude 24.5 North, longitude 66.2 West. Lee is moving toward
the west-northwest near 6 mph (9 km/h).  A slow west-northwest to
northwest motion is expected during the next day or two, followed by
a turn toward the north by midweek. On the forecast track, Lee is
expected to pass near but to the west of Bermuda in a few days.

Air Force Reserve Hurricane Hunter data indicate that the maximum 
sustained winds remain near 115 mph (185 km/h) with higher gusts.  
Lee is a category 3 hurricane on the Saffir-Simpson Hurricane Wind 
Scale.  Some slow weakening is forecast during the next 48 hours, 
but Lee is expected to remain a large and powerful hurricane.

Hurricane-force winds extend outward up to 90 miles (150 km) from
the center and tropical-storm-force winds extend outward up to 205
miles (335 km).

The estimated minimum central pressure is 951 mb (28.09 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm force winds are possible on Bermuda starting
Thursday morning.

SURF:  Swells generated by Lee are affecting portions of the Lesser
Antilles, the British and U.S. Virgin Islands, Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, and Bermuda.
These swells are likely to cause life-threatening surf and rip
current conditions. Dangerous surf and rip currents are affecting
portions of the southeastern U.S. coast, and these conditions are
forecast to spread northward along much of the U.S. East Coast
during the next couple of days. Please consult products from your
local weather office.

RAIN: Outer rain bands from Lee may produce rainfall amounts of 1 to
2 inches, 25 to 50 millimeters, across Bermuda Thursday into
early Friday.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Gallina/Blake/Bann

