

407 
WTNT33 KNHC 122056
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  30
NWS National Hurricane Center Miami FL       AL132023
Issued by the NWS Weather Prediction Center College Park MD
500 PM AST Tue Sep 12 2023

...AIR FORCE HURRICANE HUNTER FINDS LEE GROWING IN SIZE...
...HAZARDOUS SURF AND RIP CURRENT CONDITIONS EXPECTED AT BEACHES
ACROSS THE WESTERN ATLANTIC ALL WEEK...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...24.7N 66.4W
ABOUT 535 MI...860 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...946 MB...27.94 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in the northeastern United States and Atlantic Canada
should monitor the progress of Lee.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Lee was located
near latitude 24.7 North, longitude 66.4 West. Lee is moving toward
the northwest near 7 mph (11 km/h).  Lee is forecast to turn toward 
the north on Thursday and increase in forward speed. 

Air Force Hurricane Hunter data indicate that the maximum sustained 
winds remain near 115 mph (185 km/h) with higher gusts.  Lee is a 
category 3 hurricane on the Saffir-Simpson Hurricane Wind Scale.  
Some slow weakening is forecast during the next 48 hours though the 
wind field is to remain large.

Lee is very large hurricane.  Hurricane-force winds extend outward 
up to 125 miles (205 km) from the center and tropical-storm-force 
winds extend outward up to 240 miles (390 km).

The estimated minimum central pressure is 946 mb (27.94 inches) 
based on dropsonde data.


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm force winds are possible on Bermuda starting
early Thursday.

SURF:  Swells generated by Lee are affecting portions of the Lesser
Antilles, the British and U.S. Virgin Islands, Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, and Bermuda.
These swells are likely to cause life-threatening surf and rip
current conditions. Dangerous surf and rip currents are affecting
portions of the southeastern U.S. coast, and these conditions are
forecast to spread northward along much of the U.S. East Coast and 
Atlantic Canada during the next couple of days. Please consult 
products from your local weather office.

RAIN: Outer rain bands from Lee may produce rainfall amounts of 1 to
2 inches, 25 to 50 millimeters, across Bermuda Thursday into
early Friday.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Gallina/Blake/Bann


