

274 
WTNT33 KNHC 131745
TCPAT3

BULLETIN
Hurricane Lee Intermediate Advisory Number 33A
NWS National Hurricane Center Miami FL       AL132023
200 PM AST Wed Sep 13 2023

...AIR FORCE HURRICANE HUNTERS INVESTIGATING LEE...
...RISK OF WIND, COASTAL FLOODING, AND RAIN IMPACTS INCREASING FOR
PORTIONS OF NEW ENGLAND AND ATLANTIC CANADA...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...26.8N 67.5W
ABOUT 420 MI...675 KM SSW OF BERMUDA
ABOUT 1015 MI...1635 KM S OF NANTUCKET MASSACHUSETTS
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...952 MB...28.11 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

Interests in the northeastern United States and Atlantic Canada
should monitor the progress of Lee.  Watches will likely be
required for a portion of these areas later today or tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Hurricane Lee was located
near latitude 26.8 North, longitude 67.5 West. Lee is moving toward
the north-northwest near 9 mph (15 km/h). A turn toward the north is
expected by tonight, followed by an increase in speed on Thursday
and Friday.  On the forecast track, the center of Lee will pass west
of Bermuda Thursday and Thursday night and then approach the coast
of New England or Atlantic Canada Friday and Saturday.

Maximum sustained winds are near 110 mph (175 km/h) with higher
gusts.  Slow weakening is forecast during the next few
days, however, Lee is likely to remain a large and dangerous
hurricane into the weekend.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 240
miles (390 km).

The estimated minimum central pressure based on dropsonde data 
from the Air Force reconnaissance aircraft is 952 mb (28.11 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm conditions are expected in Bermuda
starting early Thursday.

SURF:  Swells generated by Lee are affecting portions of the Lesser
Antilles, the British and U.S. Virgin Islands, Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, and Bermuda.
These swells are likely to cause life-threatening surf and rip
current conditions. Dangerous surf and rip currents are affecting
portions of the southeastern and mid-Atlantic U.S. coast, and these
conditions are forecast to spread northward across New England and
Atlantic Canada later today. Please consult products from your local
weather office.

RAINFALL: Outer rain bands from Lee may produce rainfall amounts of
1 to 2 inches, 25 to 50 millimeters, across Bermuda Thursday into
early Friday.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi


