

000
WTNT33 KNHC 151144
TCPAT3

BULLETIN
Hurricane Lee Intermediate Advisory Number 40A
NWS National Hurricane Center Miami FL       AL132023
800 AM AST Fri Sep 15 2023

...LEE REMAINS A LARGE HURRICANE OVER THE WESTERN ATLANTIC...
...TROPICAL STORM CONDITIONS EXPECTED TO BEGIN ACROSS PARTS OF
COASTAL NEW ENGLAND LATER THIS AFTERNOON...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...35.1N 67.0W
ABOUT 460 MI...740 KM SSE OF NANTUCKET MASSACHUSETTS
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...N OR 10 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...962 MB...28.41 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Petit Manan Point, Maine to the U.S./Canada border
* New Brunswick from the U.S./Canada border to Point Lepreau,
including Grand Manan Island
* Nova Scotia from Digby to Medway Harbour

A Tropical Storm Warning is in effect for...
* Bermuda
* Westport Massachusetts northward to the U.S./Canada border
* Martha's Vineyard
* Nantucket
* New Brunswick from the U.S./Canada border to Fort Lawrence,
including Grand Manan Island
* Nova Scotia from Fort Lawrence to Point Tupper

A Hurricane Watch means that hurricane conditions are possible 
within the watch area.  A watch is typically issued 48 hours before 
the anticipated first occurrence of tropical-storm-force winds, 
conditions that make outside preparations difficult or dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in the northeastern United States and Atlantic
Canada should monitor the progress of Lee.

For storm information specific to your area in the United States, 
including possible inland watches and warnings, please monitor 
products issued by your local National Weather Service forecast 
office. For storm information specific to your area outside of the 
United States, please monitor products issued by your national 
meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Hurricane Lee was located 
near latitude 35.1 North, longitude 67.0 West.  Lee is moving toward 
the north near 16 mph (26 km/h), and a northward motion at a faster 
forward speed is expected through Saturday.  On the forecast track, 
the center of Lee will continue to move farther away from Bermuda 
this morning and approach the coast of New England and Atlantic 
Canada today and Saturday.  Lee is then expected to turn toward the 
north-northeast and northeast and move across Atlantic Canada 
Saturday night and Sunday.

Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts.  Little change in strength is expected through tonight. Lee 
is forecast to become post-tropical and begin weakening by Saturday, 
but it is still expected to be a large and dangerous storm when it 
reaches eastern New England and Atlantic Canada.

Hurricane-force winds extend outward up to 105 miles (165 km) from
the center and tropical-storm-force winds extend outward up to 320
miles (520 km).

The minimum central pressure based on data from the NOAA Hurricane 
Hunter aircraft is 962 mb (28.41 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm conditions will continue on Bermuda through
the morning.

Hurricane conditions are possible in the Hurricane Watch areas in
Down East Maine and in Atlantic Canada on Saturday.  Tropical storm
conditions are expected to begin in southern New England late this
afternoon and spread northward within the Tropical Storm Warning
area through Saturday.  Tropical storm conditions are expected to
spread across the Tropical Storm Warning area in Atlantic Canada
tonight and Saturday.  These conditions are likely to lead to
downed trees and potential power outages.

SURF:  Swells generated by Lee are affecting portions of the Lesser
Antilles, the British and U.S. Virgin Islands, Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the
east coast of the United States, and Atlantic Canada.  These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.

RAINFALL:  From tonight through Saturday night, Lee is expected to
produce rainfall amounts of 1 to 4 inches, or 25 to 100 millimeters,
across portions of eastern New England into portions of New
Brunswick and Nova Scotia.  This may produce localized urban and
small stream flooding.

STORM SURGE:  The combination of storm surge and tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...

Flushing, NY to U.S./Canada border...1-3 ft
Long Island Sound...1-3 ft
Cape Cod...1-3 ft
Martha's Vineyard and Nantucket...1-3 ft
Boston Harbor...1-3 ft
Rockaway Inlet, NY to Montauk Point, NY...1-2 ft

The deepest water will occur along the immediate coast where the
surge will be accompanied by large and destructive waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.

A dangerous storm surge will produce coastal flooding within the
wind warning areas in Atlantic Canada in areas of onshore winds.
Near the coast, the surge will be accompanied by large and
destructive waves.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Cangialosi

