

601 
WTNT33 KNHC 152048
TCPAT3

BULLETIN
Hurricane Lee Advisory Number  42
NWS National Hurricane Center Miami FL       AL132023
500 PM AST Fri Sep 15 2023

...TROPICAL STORM CONDITIONS EXPECTED TO OCCUR THIS EVENING IN
SOUTHEASTERN NEW ENGLAND...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...37.9N 66.7W
ABOUT 490 MI...790 KM SSW OF HALIFAX NOVA SCOTIA
ABOUT 290 MI...465 KM SE OF NANTUCKET MASSACHUSETTS
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...N OR 10 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...965 MB...28.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

Environment Canada has issued a Tropical Storm Warning for
southeastern New Brunswick. Environment Canada has also issued a
Tropical Storm Watch for much of the coast of New Brunswick, all of
Prince Edward Island, and the northern coast of Nova Scotia.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* New Brunswick from the U.S./Canada border to Point Lepreau,
including Grand Manan Island
* Nova Scotia from Digby to Ecum Secum

A Tropical Storm Warning is in effect for...
* Westport Massachusetts northward to the U.S./Canada border
* Martha's Vineyard
* Nantucket
* New Brunswick from the U.S./Canada border to Fort Lawrence,
including Grand Manan Island
* New Brunswick from Shediac to Tidnish
* Nova Scotia from Fort Lawrence to Point Tupper

A Tropical Storm Watch is in effect for...
* Prince Edward Island
* Magdalen Islands
* New Brunswick from Belledune to Shediac
* Nova Scotia from Tidnish to Aulds Cove
* Nova Scotia from Aulds Cove to Meat Cove to Point Tupper

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours before
the anticipated first occurrence of tropical-storm-force winds,
conditions that make outside preparations difficult or dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Lee was located
near latitude 37.9 North, longitude 66.7 West. Lee is moving toward
the north near 20 mph (31 km/h) and this motion at a faster forward 
speed is expected through Saturday.  On the forecast track, the 
center of Lee will continue to move farther away from Bermuda and 
approach the coast of New England and Atlantic Canada through 
Saturday.  Lee is then expected to turn toward the north-northeast 
and northeast and move across Atlantic Canada Saturday night and 
Sunday.

Maximum sustained winds are near 80 mph (130 km/h) with higher 
gusts.  Lee is expected to be a very large and dangerous storm when 
it reaches eastern New England and Atlantic Canada.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 345
miles (555 km).

The estimated minimum central pressure is 965 mb (28.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND: Hurricane conditions are possible in the Hurricane Watch areas
in Atlantic Canada on Saturday.  Tropical storm conditions are
expected to begin in southern New England late this afternoon and
spread northward across the rest of New England within the Tropical
Storm Warning area through Saturday.  Tropical storm conditions are
expected to spread across the Tropical Storm Warning area in
Atlantic Canada tonight and Saturday.  These conditions are likely
to lead to downed trees and potential power outages.

SURF:  Swells generated by Lee are affecting the northern Leeward 
Islands, the British and U.S. Virgin Islands, Puerto Rico, 
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the 
east coast of the United States, and Atlantic Canada.  These swells 
are likely to cause life-threatening surf and rip current 
conditions.  Please consult products from your local weather office.

RAINFALL:  Late tonight into Saturday night, Lee is expected to
produce rainfall amounts of 2 to 5 inches, or 50 to 125 millimeters
over portions of eastern Maine, western Nova Scotia, and New
Brunswick. This may produce localized urban and small stream
flooding.

STORM SURGE:  The combination of storm surge and tide will cause
normally dry areas near the coast to be flooded by rising waters
moving inland from the shoreline.  The water could reach the
following heights above ground somewhere in the indicated areas if
the peak surge occurs at the time of high tide...

East of Montauk Point, NY to U.S./Canada border...1-3 ft
Cape Cod...1-3 ft
Martha's Vineyard and Nantucket...1-3 ft
Boston Harbor...1-3 ft
Rockaway Inlet, NY to Montauk Point, NY...1-2 ft
Long Island Sound...1-2 ft

The deepest water will occur along the immediate coast where the
surge will be accompanied by large and destructive waves.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.

A dangerous storm surge will produce coastal flooding within the
wind warning areas in Atlantic Canada in areas of onshore winds.
Near the coast, the surge will be accompanied by large and
destructive waves.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster A Reinhart/Cangialosi


