

806 
WTNT33 KNHC 162036
TCPAT3

BULLETIN
Post-Tropical Cyclone Lee Advisory Number  46
NWS National Hurricane Center Miami FL       AL132023
500 PM AST Sat Sep 16 2023

...CORE OF LEE BRUSHING WESTERN NOVA SCOTIA...
...STRONG WINDS, COASTAL FLOODING, AND HEAVY RAINS ARE OCCURRING IN
PORTIONS OF MAINE AND ATLANTIC CANADA...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...44.5N 66.1W
ABOUT 50 MI...85 KM ESE OF EASTPORT MAINE
ABOUT 125 MI...200 KM W OF HALIFAX NOVA SCOTIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

Environment Canada has discontinued the Hurricane Watch for New
Brunswick and Nova Scotia.

The Tropical Storm Warning has been discontinued south of Cape
Elizabeth, Maine.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Cape Elizabeth northward to the U.S./Canada border
* New Brunswick from the U.S./Canada border to Belledune,
including Grand Manan Island
* All of Nova Scotia
* Prince Edward Island
* Magdalen Islands

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning, in this case today through
Sunday.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Post-Tropical Cyclone Lee
was located near latitude 44.5 North, longitude 66.1 West. The
post-tropical cyclone is moving toward the north near 16 mph (26
km/h). A faster northeastward motion is expected during the next
day or so, taking the system across the Canadian Maritimes.

Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts.  Steady weakening is forecast during the next couple of days.

Tropical-storm-force winds extend outward up to 320 miles (520 km)
from the center.  An observing site in Halifax, Canada, reported a
sustained wind of 52 mph (83 km/h) and a gust to 60 mph (96 km/h).
An observation in Vinal Haven, Maine, reported a sustained wind of
44 mph (71 km/h).

Tropical-storm-force winds extend outward up to 320 miles (520 km)
from the center.

The estimated minimum central pressure is 970 mb (28.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND:  Tropical storm conditions are occurring along the coasts of
Maine and Nova Scotia and will spread northward within the Tropical
Storm Warning areas through tonight.  The strong winds are leading
to downed trees and power outages.

SURF:  Swells generated by Lee are affecting Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the
east coast of the United States, and Atlantic Canada.  These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.

RAINFALL:  Lee may produce an additional 1 to 2 inches of rain, or
25 to 50 millimeters, over portions of eastern Maine and New
Brunswick. This may produce localized urban and small stream
flooding.

STORM SURGE: A dangerous storm surge will produce coastal flooding
within the wind warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Cangialosi


