

000
WTNT33 KNHC 162346
TCPAT3

BULLETIN
Post-Tropical Cyclone Lee Intermediate Advisory Number 46A
NWS National Hurricane Center Miami FL       AL132023
800 PM AST Sat Sep 16 2023

...STRONG WINDS, COASTAL FLOODING, AND HEAVY RAINS ARE OCCURRING IN
PORTIONS OF MAINE AND ATLANTIC CANADA...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...44.7N 66.3W
ABOUT 40 MI...60 KM ESE OF EASTPORT MAINE
ABOUT 130 MI...215 KM W OF HALIFAX NOVA SCOTIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Tropical Storm Warning has been discontinued south of 
Stonington, Maine.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Stonington, Maine northward to the U.S./Canada border
* New Brunswick from the U.S./Canada border to Belledune,
including Grand Manan Island
* All of Nova Scotia
* Prince Edward Island
* Magdalen Islands

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning, in this case today through
Sunday.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Post-Tropical Cyclone Lee
was located near latitude 44.7 North, longitude 66.3 West. The
post-tropical cyclone is moving toward the north near 14 mph (22
km/h). A faster northeastward motion is expected during the next day
or so, taking the system across the Canadian Maritimes.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts. Steady weakening is forecast during the next couple of days.

Tropical-storm-force winds extend outward up to 320 miles (520 km)
from the center. An observing site on Beaver Island, Canada, 
reported a sustained wind of 48 mph (78 km/h) and a gust to 63 mph 
(102 km/h).

The estimated minimum central pressure is 979 mb (28.91 inches).

HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND: Tropical storm conditions are occurring along the coasts of 
Maine and Nova Scotia and will spread northward within the Tropical 
Storm Warning areas through tonight.  The strong winds are leading 
to downed trees and power outages.

SURF:  Swells generated by Lee are affecting Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the
east coast of the United States, and Atlantic Canada.  These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.

RAINFALL:  Lee may produce an additional 1 to 2 inches of rain, or
25 to 50 millimeters, over portions of eastern Maine and New
Brunswick. This may produce localized urban and small stream
flooding.

STORM SURGE: A dangerous storm surge will produce coastal flooding
within the wind warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Kelly/Brown

