

000
WTNT33 KNHC 170241
TCPAT3

BULLETIN
Post-Tropical Cyclone Lee Advisory Number  47
NWS National Hurricane Center Miami FL       AL132023
1100 PM AST Sat Sep 16 2023

...LEE NEAR THE COAST OF NEW BRUNSWICK...
...STRONG WINDS, COASTAL FLOODING, AND HEAVY RAINS ARE OCCURRING IN
PORTIONS OF ATLANTIC CANADA...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...45.3N 65.5W
ABOUT 105 MI...170 KM WNW OF HALIFAX NOVA SCOTIA
ABOUT 80 MI...125 KM ENE OF EASTPORT MAINE
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NNE OR 20 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Tropical Storm Warning has been discontinued for the coast of 
Maine.

Environment Canada has discontinued the Tropical Storm Warning in 
New Brunswick from the U.S./Canada international border to south of 
Fundy National Park, from Belledune to north of Shediac, and north 
of Lower East Pubnico to west of Avonport along the Fundy Coast of 
Nova Scotia. 

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* New Brunswick from the Fundy National Park to Fort Lawrence and 
  from Tidnish to Shediac including Grand Manan Island
* Nova Scotia from Fort Lawrence to Avonport and then east from 
  Lower East Pubnico to Tidnish
* Prince Edward Island
* Magdalen Islands


A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning, in this case today through
Sunday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Post-Tropical Cyclone Lee 
was located near latitude 45.3 North, longitude 65.5 West. The 
post-tropical cyclone is moving toward the north-northeast near 14 
mph (22 km/h). A faster northeastward motion is expected during the 
next day or so, taking the system across the Canadian Maritimes.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Steady weakening is forecast the next couple of days.

Tropical-storm-force winds extend outward up to 290 miles (465 km)
from the center.

The estimated minimum central pressure is 979 mb (28.91 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND: Tropical storm conditions are occurring along portions of the
coasts of New Brunswick and Nova Scotia and will spread northward
within the Tropical Storm Warning areas overnight.  The strong
winds are leading to downed trees and power outages.

SURF:  Swells generated by Lee are affecting Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the
east coast of the United States, and Atlantic Canada.  These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.

RAINFALL:  Lee is expected to produce an additional 1 inch or less,
or 25 millimeters or less, from portions of eastern Maine into parts
of New Brunswick and far western Nova Scotia. This may produce
localized urban and small stream flooding.

STORM SURGE: A dangerous storm surge will produce coastal flooding
within the wind warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Kelly/Brown

