

205 
WTNT33 KNHC 170553
TCPAT3

BULLETIN
Post-Tropical Cyclone Lee Intermediate Advisory Number 47A
NWS National Hurricane Center Miami FL       AL132023
200 AM AST Sun Sep 17 2023

...LEE OVER SOUTHEASTERN NEW BRUNSWICK...
...STRONG WINDS, COASTAL FLOODING, AND HEAVY RAINS ARE OCCURRING IN
PORTIONS OF ATLANTIC CANADA...


SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...45.9N 64.8W
ABOUT 10 MI...15 KM SW OF MONCTON NEW BRUNSWICK
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...983 MB...29.03 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Canadian Hurricane Centre has discontinued all Tropical Storm 
Warnings for New Brunswick, including Grand Manan Island.

The Canadian Hurricane Centre has discontinued the Tropical Storm 
Warning for Prince Edward Island from west of Victoria westward 
to Lower Darnley.

The Canadian Hurricane Centre has discontinued the Tropical Storm 
Warning for Nova Scotia from Tidnish eastward to west of Brule,
the Fundy Coast from Ft. Lawrence east of Margaretsville and from 
Lower East Pubnico to west of Hubbards.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Nova Scotia from Brule eastward to Point Aconi then southwestward 
to Hubbards 
* Prince Edward Island from east of Lower Darnley eastward to 
Victoria
* Magdalen Islands

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning, in this case today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Post-Tropical Cyclone Lee
was located near latitude 45.9 North, longitude 64.8 West. The
post-tropical cyclone is moving toward the north-northeast near 14
mph (22 km/h). A faster northeastward motion is expected during the
next day or so, taking the system across the Canadian Maritimes.

Maximum sustained winds remain near 60 mph (95 km/h) with higher
gusts. Steady weakening is forecast the next couple of days.

Tropical-storm-force winds extend outward up to 290 miles (465 km)
from the center. Beaver Island Nova Scotia recently reported a 
sustained wind of 52 mph (83 km/h) with a gust to 61 mph (98 km/h). 

The estimated minimum central pressure is 983 mb (29.03 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND: Tropical storm conditions will continues in portions of the 
warning areas today.  The strong winds are leading to some downed 
trees and power outages.

SURF:  Swells generated by Lee are affecting Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the
east coast of the United States, and Atlantic Canada.  These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.

RAINFALL:  Lee is expected to produce an additional 1 inch (25 mm) 
or less, across eastern portions of New Brunswick.

STORM SURGE: A dangerous storm surge will produce coastal flooding
within the wind warning areas in Atlantic Canada in areas of
onshore winds. Near the coast, the surge will be accompanied by
large and destructive waves.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Blake


