

000
WTNT33 KNHC 171441
TCPAT3

BULLETIN
Post-Tropical Cyclone Lee Advisory Number  49
NWS National Hurricane Center Miami FL       AL132023
1100 AM AST Sun Sep 17 2023

...ALL TROPICAL STORM WARNINGS FOR CANADA ARE DISCONTINUED...
...THIS IS THE LAST ADVISORY ON LEE...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...48.0N 62.0W
ABOUT 135 MI...215 KM WNW OF PORT AUX BASQUES NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NE OR 50 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.21 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

Environment Canada has discontinued all Tropical Storm Warnings for
Canada.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warning in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Post-Tropical Cyclone Lee
was located near latitude 48.0 North, longitude 62.0 West. The
post-tropical cyclone is moving toward the northeast near 22 mph (35
km/h), and a faster northeastward to east-northeastward motion is
expected over the next couple of days, taking Lee over Newfoundland
later today and over the Atlantic waters by early Monday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Continued gradual weakening is forecast during the next couple of
days, and Lee could dissipate on Tuesday.

Tropical-storm-force winds extend outward up to 290 miles (465 km)
from the center.

The estimated minimum central pressure is 989 mb (29.21 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lee can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC and on the
web at hurricanes.gov/text/MIATCDAT3.shtml

WIND: Wind gusts to near gale force are still possible over
portions of Atlantic Canada today.

SURF: Swells generated by Lee continue to affect Puerto Rico,
Hispaniola, the Turks and Caicos Islands, the Bahamas, Bermuda, the
east coast of the United States, and Atlantic Canada. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on this system. Additional information on this system can be 
found in High Seas Forecasts issued by the National Weather Service, 
under AWIPS header NFDHSFAT1, WMO header FZNT01 KWBC, and online at 
ocean.weather.gov/shtml/NFDHSFAT1.php

$$
Forecaster Pasch

