

000
WTPZ31 KNHC 082035
TCPEP1

BULLETIN
Hurricane Jova Advisory Number  17
NWS National Hurricane Center Miami FL       EP112023
200 PM PDT Fri Sep 08 2023

...JOVA CONTINUES TO WEAKEN...
...DANGEROUS BEACH CONDITIONS EXPECTED ALONG THE COAST OF
CALIFORNIA THIS WEEKEND...


SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...20.4N 122.4W
ABOUT 820 MI...1320 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...980 MB...28.94 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Hurricane Jova was located
near latitude 20.4 North, longitude 122.4 West. Jova is moving
toward the west-northwest near 15 mph (24 km/h), and this general
motion with a gradual decrease in forward speed is expected over the
next few days.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts. Continued weakening is forecast during the next several
days.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).

The estimated minimum central pressure is 980 mb (28.94 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Jova are expected to reach portions of
the coast of California later today. These swells are likely to
cause life-threatening surf and rip current conditions through the
weekend.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Kelly

