

000
WTPZ31 KNHC 090245
TCPEP1

BULLETIN
Hurricane Jova Advisory Number  18
NWS National Hurricane Center Miami FL       EP112023
800 PM PDT Fri Sep 08 2023

...JOVA WEAKENS BUT STILL A HURRICANE...
...PRODUCING DANGEROUS BEACH CONDITIONS ALONG THE COASTS OF
CALIFORNIA AND MEXICO...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...21.1N 123.7W
ABOUT 890 MI...1435 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...987 MB...29.15 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Hurricane Jova was located 
near latitude 21.1 North, longitude 123.7 West. Jova is moving 
toward the west-northwest near 16 mph (26 km/h). A 
west-northwestward to northwestward motion at a slightly slower 
speed is expected for the next couple of days. Jova is forecast to 
slow down further and turn westward by late Sunday.

Maximum sustained winds have decreased to near 75 mph (120 km/h) 
with higher gusts. Additional weakening is likely. Jova is forecast 
to become a remnant low early next week. 

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 987 mb (29.15 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Jova are affecting the western coast of 
Mexico and are expected to reach portions of the coast of California 
tonight. These swells are likely to cause life-threatening surf and 
rip current conditions through the weekend.  Please consult products 
from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.

$$
Forecaster D. Zelinsky

