000
WTNT32 KNHC 192044
TCPAT2
 
BULLETIN
Tropical Depression Two Advisory Number   2
NWS National Hurricane Center Miami FL       AL022026
400 PM CDT Sun Jul 19 2026
 
...TROPICAL DEPRESSION MEANDERING OFF THE WEST COAST OF FLORIDA...
...TROPICAL STORM CONDITIONS ARE POSSIBLE IN THE FLORIDA PANHANDLE
BY LATE MONDAY...
 
 
SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...27.5N 85.0W
ABOUT 190 MI...310 KM SSE OF PANAMA CITY FLORIDA
MAXIMUM SUSTAINED WINDS...30 MPH...45 KM/H
PRESENT MOVEMENT...STATIONARY
MINIMUM CENTRAL PRESSURE...1010 MB...29.83 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Ochlockonee River to the FL/AL border
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case in the next 36 to 48
hours.
 
Additional tropical storm watches or warnings will likely be
required over the next day or two.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Depression Two was 
located near latitude 27.5 North, longitude 85.0 West. The 
depression is stationary.  A very slow northwestward or 
north-northwestward motion is expected during the next day or two, 
followed by a turn toward the west.  On the forecast track, the 
depression will move near or along the northern Gulf coast during 
the next several days.
 
Maximum sustained winds remain near 30 mph (45 km/h) with higher 
gusts. Gradual strengthening is forecast, and the depression is
expected to become a tropical storm on Monday.
 
The minimum central pressure based on data from an Air Force 
Reserve reconnaissance aircraft is 1010 mb (29.83 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Two can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT2 and WMO
header WTNT42 KNHC.
 
WIND:  Tropical storm conditions are possible within the watch
area by late Monday.
 
STORM SURGE:  The combination of storm surge and the tide will
cause normally dry areas near the immediate coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Indian Pass to Chassahowitzka, FL...1 to 3 ft
 
The deepest water will occur along the immediate coast.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge
inundation, please see the National Weather Service Peak
Storm Surge Graphic, available at
hurricanes.gov/graphics_at2.shtml?peakSurge.
 
RAINFALL: The tropical depression is expected to produce rainfall 
amounts of 2 to 4 inches with locally higher totals around 8 inches 
through Friday along the Gulf Coast and adjacent inland locations 
from western Florida to the Middle Texas Coast, including southern 
portions of Alabama, Mississippi, and Louisiana. This rainfall may 
produce areas of flash flooding, especially in urban areas.

For a complete depiction of forecast rainfall associated with 
Tropical Depression Two, please see the National Weather Service 
Storm Total Rainfall Graphic available at 
hurricanes.gov/graphics_at2.shtml?rainqpf and the Flash Flood Risk 
graphic at hurricanes.gov/graphics_at2.shtml?ero.

SURF:  Swells generated by the depression are affecting portions of
the Gulf coast of Florida and are likely to spread westward during 
the week.  These swells are likely to cause life-threatening surf 
and rip current conditions.  Please consult products from your 
local weather office.

A depiction of rip current risk for the United States can be found 
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.
 
$$
Forecaster Cangialosi
  