000
WTNT32 KNHC 201146
TCPAT2
 
BULLETIN
Tropical Depression Two Intermediate Advisory Number 4A
NWS National Hurricane Center Miami FL       AL022026
700 AM CDT Mon Jul 20 2026
 
...DEPRESSION EXPECTED TO BECOME A TROPICAL STORM LATER TODAY...
...AIR FORCE HURRICANE HUNTER AIRCRAFT CURRENTLY INVESTIGATING 
THE SYSTEM...
 
 
SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...28.6N 85.6W
ABOUT 110 MI...180 KM S OF PANAMA CITY FLORIDA
ABOUT 210 MI...335 KM SE OF MOBILE ALABAMA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Watch is in effect for...
* Ochlockonee River to the MS/AL border
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case in the next 24 to 48
hours.
 
Additional tropical storm watches or warnings will likely be
required over the next day or two.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Tropical Depression Two was
located near latitude 28.6 North, longitude 85.6 West. The
depression is moving toward the northwest near 3 mph (6 km/h). A 
slow northwestward motion is expected during the next day or so, 
followed by a turn toward the west-northwest or west. On the 
forecast track, the depression will move near or along the northern 
Gulf coast during the next several days.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Gradual strengthening is forecast, and the depression is 
expected to become a tropical storm later today.
 
The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Two can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT2 and WMO
header WTNT42 KNHC.
 
WIND:  Tropical storm conditions are possible within the watch
area by tonight into Tuesday.
 
STORM SURGE:  The combination of storm surge and the tide will
cause normally dry areas near the immediate coast to be flooded by
rising waters moving inland from the shoreline.  The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Indian Pass to Chassahowitzka, FL...1 to 3 ft
MS/AL Border to AL/FL Border...1 to 3 ft
Mobile Bay...1 to 3 ft
 
The deepest water will occur along the immediate coast.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances.  For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge
inundation, please see the National Weather Service Peak
Storm Surge Graphic, available at
hurricanes.gov/graphics_at2.shtml?peakSurge.
 
RAINFALL: The tropical depression is expected to produce rainfall
amounts of 2 to 4 inches with locally higher totals around 6 inches
through Friday along the Gulf Coast and adjacent inland locations
from western Florida to the Middle Texas Coast, including southern
portions of Alabama, Mississippi, and Louisiana. This rainfall may
produce areas of flash flooding, especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Tropical Depression Two, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_at2.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at2.shtml?ero.
 
SURF:  Swells generated by the depression are affecting portions of
the Gulf coast of Florida and are likely to spread westward during
the week.  These swells are likely to cause life-threatening surf
and rip current conditions.  Please consult products from your
local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.
 
$$
Forecaster Beven
  