114 
WTNT32 KNHC 220535
TCPAT2
 
BULLETIN
Tropical Storm Bertha Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       AL022026
100 AM CDT Wed Jul 22 2026
 
...BERTHA MOVING WESTWARD WITH TROPICAL STORM CONDITIONS EXPECTED TO 
CONTINUE ALONG THE NORTHERN GULF COAST...
 
 
SUMMARY OF 100 AM CDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...29.3N 87.9W
ABOUT 145 MI...235 KM WSW OF PANAMA CITY FLORIDA
ABOUT 75 MI...120 KM E OF THE MOUTH OF THE MISSISSIPPI RIVER
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Bay/Gulf County Line in Florida to Morgan City, Louisiana
* Metropolitan New Orleans and Lake Pontchartrain
 
A Tropical Storm Watch is in effect for...
* West of Morgan City, Louisiana, to Cameron, Louisiana
* Lake Maurepas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 24 to
48 hours.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 100 AM CDT (0600 UTC), the center of Tropical Storm Bertha was 
located by Air Force Reserve aircraft near latitude 29.3 North, 
longitude 87.9 West. Bertha is moving toward the west near 6 mph  
(9 km/h) and this general motion is expected to continue through 
Friday. On the forecast track, Bertha will move near or along the 
northern Gulf Coast during the next couple of days. 

Maximum sustained winds have decreased to near 50 mph (85 km/h) with 
higher gusts. Gradual weakening is forecast to continue over the 
next several days. 
 
Tropical-storm-force winds extend outward up to 115 miles (185 km) 
from the center. In the past hour, a wind gust of 40 mph (64 km/h) 
was reported at Panama City Beach, Florida. 
 
The minimum central pressure estimated by Air Force Reserve 
reconnaissance aircraft is 998 mb (29.47 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Bertha can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC.
 
WIND:  Tropical storm conditions will continue spreading across
portions of the northern Gulf Coast within the warning area 
through the day. Tropical storm conditions are possible within
the watch area in Louisiana by tonight.
 
STORM SURGE:  The combination of storm surge and the tide will
cause normally dry areas near the immediate coast to be flooded by
rising waters moving inland from the shoreline. The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Mouth of the Mississippi River, LA to MS/AL Border...2-4 ft
Cameron, LA to Mouth of the Mississippi River, LA...1-3 ft
MS/AL Border to Aucilla River, FL...1-3 ft
Lake Pontchartrain...1-3 ft
 
The deepest water will occur along the immediate coast.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances. For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at2.shtml?peakSurge.
 
RAINFALL: Bertha is expected to produce total rainfall amounts of 1
to 4 inches with isolated higher totals to 6 inches through Thursday
along the central Gulf Coast from western Florida through southern
Louisiana. This rainfall may produce isolated flash flooding,
especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Bertha, please see the National Weather Service Storm Total Rainfall
Graphic available at hurricanes.gov/graphics_at2.shtml?rainqpf and
the Flash Flood Risk graphic at
hurricanes.gov/graphics_at2.shtml?ero.
 
SURF: Swells generated by Bertha will continue spreading westward
along the northern Gulf Coast during the next few days. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.
 
$$
Forecaster Papin
  