064 
WTNT32 KNHC 221736
TCPAT2
 
BULLETIN
Tropical Storm Bertha Intermediate Advisory Number 13A
NWS National Hurricane Center Miami FL       AL022026
100 PM CDT Wed Jul 22 2026
 
...CENTER OF BERTHA APPROACHING THE COAST OF SOUTHEASTERN 
LOUISIANA...
...TROPICAL STORM CONDITIONS CONTINUE TO SPREAD WESTWARD WITHIN THE 
WARNING AREA...
 
 
SUMMARY OF 100 PM CDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...29.9N 89.1W
ABOUT 35 MI...60 KM SSW OF BILOXI MISSISSIPPI
ABOUT 60 MI...95 KM E OF NEW ORLEANS LOUISIANA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Tropical Storm Warning has been discontinued east of the 
Alabama/Florida border.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Alabama/Florida border to Morgan City, Louisiana
* Metropolitan New Orleans and Lake Pontchartrain
 
A Tropical Storm Watch is in effect for...
* West of Morgan City, Louisiana, to Sargent, Texas
* Lake Maurepas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
to 36 hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 12 to
36 hours.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 100 PM CDT (1800 UTC), the center of Tropical Storm Bertha was
located near latitude 29.9 North, longitude 89.1 West. Bertha is
moving toward the west-northwest near 7 mph (11 km/h). A westward 
motion with an increase in forward speed is expected to resume 
later today and continue through Friday. On the forecast track, the 
center of Bertha will move near or along the Louisiana and upper 
Texas coasts through Thursday, and then move farther inland into 
Texas on Friday.
 
Data from an Air Force Reserve Hurricane Hunter aircraft indicate 
that maximum sustained winds have decreased to near 45 mph (75 km/h) 
with higher gusts. Additional weakening is forecast during the next 
couple of days, but Bertha could maintain tropical storm intensity 
through late Thursday.
 
Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center. Dauphin Island, Alabama, recently reported a 
sustained wind of 36 mph (58 km/h) and a gust to 41 mph (66 km/h).
 
Data from the reconnaissance aircraft indicate that the minimum 
central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Bertha can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC.
 
WIND:  Tropical storm conditions will continue spreading across
portions of the northern Gulf Coast within the warning area today.
Tropical storm conditions are possible within the watch area in
Louisiana by tonight and along the upper Texas coast by Thursday or
Thursday night.
 
STORM SURGE:  The combination of storm surge and the tide will
cause normally dry areas near the immediate coast to be flooded by
rising waters moving inland from the shoreline. The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Alabama/Florida border to Port Bolivar, TX...1-3 ft
Lake Pontchartrain...1-3 ft
 
The deepest water will occur along the immediate coast.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances. For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at2.shtml?peakSurge.
 
RAINFALL: Bertha is expected to produce total rainfall amounts of 1
to 4 inches with isolated higher totals of 6 inches through Friday
along the central to western Gulf Coast from Northwest Florida to
southern Texas. This rainfall may produce isolated flash flooding,
especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Bertha, please see the National Weather Service Storm Total Rainfall
Graphic available at hurricanes.gov/graphics_at2.shtml?rainqpf and
the Flash Flood Risk graphic at
hurricanes.gov/graphics_at2.shtml?ero.
 
SURF: Swells generated by Bertha will continue spreading westward
along the northern Gulf Coast during the next few days. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.
 
$$
Forecaster Berg
  