000
WTNT32 KNHC 222338
TCPAT2
 
BULLETIN
Tropical Storm Bertha Intermediate Advisory Number 14A
NWS National Hurricane Center Miami FL       AL022026
700 PM CDT Wed Jul 22 2026
 
...BERTHA MOVING A LITTLE SOUTH OF WEST OVER SOUTHEASTERN 
LOUISIANA...
 
 
SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...29.5N 90.5W
ABOUT 40 MI...70 KM SW OF NEW ORLEANS LOUISIANA
ABOUT 165 MI...270 KM ESE OF LAKE CHARLES LOUISIANA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 260 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Alabama/Florida border to Cameron, Louisiana
* Metropolitan New Orleans and Lake Pontchartrain
 
A Tropical Storm Watch is in effect for...
* West of Cameron, Louisiana, to Sargent, Texas
* Lake Maurepas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, in this case within the next 24 to
36 hours.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Storm Bertha was
located near latitude 29.5 North, longitude 90.5 West.  Bertha is
moving a little south of west near 7 mph (11 km/h).  A faster 
westward or west-southwestward motion is expected during the 
next day or so. On the forecast track, the center of Bertha will 
move near or along the Louisiana and upper Texas coasts through 
Thursday, and then move farther inland into Texas Thursday night.

Maximum sustained winds are near 45 mph (75 km/h) with higher
gusts.  Little change in strength is expected during the next day 
or so, and Bertha is forecast to maintain tropical storm intensity 
up until it reaches the upper Texas coast on Thursday.  Bertha is
expected to dissipate inland over Texas by Thursday night or Friday.
 
Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center.  A sustained wind of 36 mph (58 km/h) was recently 
reported near Point a la Hache Louisiana.
 
The minimum central pressure estimated from surface observations is 
1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Bertha can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC.
 
WIND:  Tropical storm conditions will continue spreading across
portions of the northern Gulf Coast within the warning area through
Thursday. Tropical storm conditions are possible within the watch
area by Thursday or Thursday night.
 
STORM SURGE:  The combination of storm surge and the tide will
cause normally dry areas near the immediate coast to be flooded by
rising waters moving inland from the shoreline. The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Alabama/Florida border to Port Bolivar, TX...1-3 ft
Lake Pontchartrain...1-3 ft
 
The deepest water will occur along the immediate coast.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances. For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at2.shtml?peakSurge.
 
RAINFALL: Bertha is expected to produce total rainfall amounts of 1
to 4 inches with isolated higher totals of 6 inches through Friday
along the central to western Gulf Coast from Northwest Florida to
southern Texas. This rainfall may produce isolated flash flooding,
especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Bertha, please see the National Weather Service Storm Total Rainfall
Graphic available at hurricanes.gov/graphics_at2.shtml?rainqpf and
the Flash Flood Risk graphic at
hurricanes.gov/graphics_at2.shtml?ero.
 
SURF: Swells generated by Bertha will continue spreading westward
along the northern Gulf Coast during the next few days. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.
 
$$
Forecaster Pasch
  