000
WTNT32 KNHC 230535
TCPAT2
 
BULLETIN
Tropical Storm Bertha Intermediate Advisory Number 15A
NWS National Hurricane Center Miami FL       AL022026
100 AM CDT Thu Jul 23 2026
 
...BERTHA NOW SOUTH OF THE COAST OF SOUTHERN LOUISIANA...
...WARNINGS DISCONTINUED FOR PORTIONS OF THE LOUISIANA AND 
MISSISSIPPI COASTS...
 
 
SUMMARY OF 100 AM CDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...29.1N 91.6W
ABOUT 110 MI...175 KM SW OF NEW ORLEANS LOUISIANA
ABOUT 120 MI...190 KM SE OF LAKE CHARLES LOUISIANA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 260 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Tropical Storm Warning has been discontinued for the Louisiana 
and Mississippi coasts north and east of the Plaquemines/St. 
Bernard Parish line, including Metropolitan New Orleans and Lake 
Pontchartrain.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* The Gulf Coast from the Plaquemines/St. Bernard Parish line, 
Louisiana to Sargent, Texas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24
hours.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 100 AM CDT (0600 UTC), the center of Tropical Storm Bertha was
located near latitude 29.1 North, longitude 91.6 West. Bertha is
moving toward the west near 12 mph (19 km/h).  A generally westward 
motion is expected through Friday.  On the forecast track, the 
center of Bertha will move near or along the Louisiana and upper 
Texas coasts through this afternoon, and then move farther inland 
into Texas this evening and tonight.
 
Recent satellite wind data indicate that maximum sustained winds 
remain near 45 mph (75 km/h) with higher gusts. Little change in 
strength is expected today, and Bertha is forecast to maintain 
tropical storm intensity up until it reaches the upper Texas coast 
later today.  Bertha is expected to dissipate inland over Texas by 
tonight or Friday.
 
Tropical-storm-force winds extend outward up to 160 miles (260 km)
mainly to the south of the center. An oil platform south of the 
Louisiana coast recently reported sustained winds of 52 mph (84 
km/h) and a wind gust of 61 mph (98 km/h) at an elevation of 82 ft 
(25 m). Another oil platform located southwest of the center of 
Bertha was recently hit by a severe thunderstorm and reported a wind 
gust of 82 mph (132 km/h) at an elevation of 98 ft (30 m).
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Bertha can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC.
 
WIND:  Tropical storm conditions will continue spreading across
portions of the northern and northwestern Gulf Coast within the
warning area through today.
 
STORM SURGE:  The combination of storm surge and the tide will
cause normally dry areas near the immediate coast to be flooded by
rising waters moving inland from the shoreline. The water could
reach the following heights above ground somewhere in the indicated
areas if the peak surge occurs at the time of high tide...
 
Alabama/Mississippi border to Port Bolivar, TX...1-3 ft
Lake Pontchartrain...1-3 ft
 
The deepest water will occur along the immediate coast.
Surge-related flooding depends on the relative timing of the surge
and the tidal cycle, and can vary greatly over short distances. For
information specific to your area, please see products issued by
your local National Weather Service forecast office.
 
For a complete depiction of areas at risk of storm surge inundation,
please see the National Weather Service Peak Storm Surge Graphic,
available at hurricanes.gov/graphics_at2.shtml?peakSurge.
 
RAINFALL: Bertha is expected to produce total rainfall amounts of 2
to 4 inches with isolated totals to 6 inches through tonight along 
Texas Gulf Coast and South Texas.  This rainfall may produce 
isolated flash flooding, especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Bertha, please see the National Weather Service Storm Total Rainfall
Graphic available at hurricanes.gov/graphics_at2.shtml?rainqpf and
the Flash Flood Risk graphic at
hurricanes.gov/graphics_at2.shtml?ero.
 
SURF: Swells generated by Bertha will continue spreading westward
along the northern Gulf Coast during the next few days. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.
 
$$
Forecaster Beven
  