156 
WTNT32 KNHC 232035
TCPAT2
 
BULLETIN
Tropical Storm Bertha Advisory Number  18
NWS National Hurricane Center Miami FL       AL022026
400 PM CDT Thu Jul 23 2026
 
...BERTHA MOVING INLAND OVER EASTERN TEXAS...
...HEAVY RAINS SPREADING ACROSS PORTIONS OF COASTAL TEXAS...
 
 
SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...29.8N 94.7W
ABOUT 35 MI...55 KM N OF GALVESTON TEXAS
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Tropical Storm Warning east of the Vermilion/Cameron Parish
Line has been discontinued.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Tropical Storm Warning is in effect for...
* Vermilion/Cameron Parish Line, Louisiana, to Sargent, Texas
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Bertha was 
located near latitude 29.8 North, longitude 94.7 West. Bertha is 
moving toward the west-northwest near 13 mph (20 km/h) and this 
motion with some increase in forward speed is expected during the 
next day or so. On the forecast track, the center of Bertha will 
move across portions of eastern Texas during the next several hours.
 
Maximum sustained winds have decreased to near 40 mph (65 km/h)
with higher gusts. Bertha is expected to gradually weaken, and it is
forecast to dissipate tonight or on Friday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
south the center.
 
The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Bertha can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDAT2 and WMO header
WTNT42 KNHC.
 
WIND:  Tropical storm conditions will continue across portions of
the Louisiana and Texas coasts within the warning area into the
evening.
 
STORM SURGE:  Water levels may remain elevated through the next
high tide cycle along the Louisiana and Texas coastline but should
subside thereafter.
 
RAINFALL: Bertha is expected to produce total rainfall amounts of 1
to 3 inches with isolated totals to 4 inches into tonight along the
Texas Gulf Coast and South Texas. This rainfall may produce isolated
flash flooding, especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Bertha, please see the National Weather Service Storm Total Rainfall
Graphic available at hurricanes.gov/graphics_at2.shtml?rainqpf and
the Flash Flood Risk graphic at
hurricanes.gov/graphics_at2.shtml?ero.
 
SURF: Swells generated by Bertha will continue to affect the
Louisiana and Texas coast through tonight.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.
 
$$
Forecaster Cangialosi/R. Zelinsky
  