000
WTNT32 KNHC 232339
TCPAT2
 
BULLETIN
Tropical Depression Bertha Intermediate Advisory Number 18A
NWS National Hurricane Center Miami FL       AL022026
700 PM CDT Thu Jul 23 2026
 
...BERTHA WEAKENS TO A DEPRESSION...
...TROPICAL STORM WARNINGS DISCONTINUED...
 
 
SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...29.9N 95.3W
ABOUT 10 MI...20 KM NNE OF HOUSTON TEXAS
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Tropical Storm Warning from the Vermilion/Cameron Parish Line, 
Louisiana, to Sargent, Texas has been discontinued.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
There are no coastal watches or warnings in effect. 

 
DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Depression Bertha 
was located near latitude 29.9 North, longitude 95.3 West.  Bertha 
is moving toward the west near 13 mph (20 km/h), and this general 
motion is expected to continue tonight.
 
Maximum sustained winds have decreased to near 35 mph (55 km/h) 
with higher gusts.  Additional weakening is expected, and Bertha is 
likely to dissipate tonight.
 
The estimated minimum central pressure is 1007 mb (29.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
WIND:  Wind gusts to tropical storm force are still possible along 
the upper Texas coast during the next couple of hours.
 
STORM SURGE:  Water levels may remain elevated through the next
high tide cycle along the Louisiana and Texas coastline but should
subside thereafter.
 
RAINFALL: Bertha is expected to produce total rainfall amounts of 1
to 3 inches with isolated totals to 4 inches into tonight along the
Texas Gulf Coast and South Texas. This rainfall may produce isolated
flash flooding, especially in urban areas.
 
For a complete depiction of forecast rainfall associated with
Bertha, please see the National Weather Service Storm Total Rainfall
Graphic available at hurricanes.gov/graphics_at2.shtml?rainqpf and
the Flash Flood Risk graphic at
hurricanes.gov/graphics_at2.shtml?ero.
 
SURF: Swells generated by Bertha will continue to affect the
Louisiana and Texas coast through tonight.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at2.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.
 
$$
Forecaster Pasch/Mahoney
  