000
WTNT33 KNHC 220549
TCPAT3
 
BULLETIN
Tropical Storm Melissa Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       AL132025
200 AM EDT Wed Oct 22 2025
 
...AIR FORCE RESERVE HURRICANE HUNTER AIRCRAFT CURRENTLY 
INVESTIGATING MELISSA...
 
 
SUMMARY OF 200 AM EDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 74.0W
ABOUT 325 MI...520 KM SSW OF PORT AU PRINCE HAITI
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Tropical Storm Watch is in effect for...
* Jamaica
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, and Cuba
should monitor the progress of Melissa.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM EDT (0600 UTC), the center of Tropical Storm Melissa was
estimated near latitude 14.2 North, longitude 74.0 West.  While the 
storm has recently been nearly stationary, Melissa is expected to 
move toward the west near 12 mph (19 km/h) overnight.  A decrease 
in forward speed and a gradual turn to the northwest and north is 
expected during the next few days.  On the forecast track, Melissa 
is expected to approach Jamaica and the southwestern portion of 
Haiti later this week.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher
gusts. Gradual strengthening is expected during the next few days.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area in
Haiti beginning late on Thursday.  Tropical storm conditions could
begin in Jamaica on Thursday or Friday.
 
RAINFALL: Melissa is forecast to bring 5 to 10 inches of rain to
southern Haiti and the southern Dominican Republic through Friday,
with locally higher amounts possible.  Across eastern Jamaica, 4 to
8 inches of rain are expected, also with locally higher amounts
possible.  Additional heavy rainfall is possible beyond Friday;
however, uncertainty in Melissa’s track and forward speed reduces
confidence in exact totals. Significant flash flooding and
landslides are possible.
 
Across the northern Dominican Republic and northern Haiti, 2 to 4
inches of rain are expected through Friday. For Aruba, western
Jamaica, and Puerto Rico, 1 to 3 inches are expected through the 
same period. Flash and urban flooding will be possible through at 
least Friday.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
SURF:  Swells generated by Melissa are expected to spread to
Hispaniola, Jamaica, and eastern Cuba during the next couple of
days.  Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at3.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Blake
  