494 
WTNT33 KNHC 221450
TCPAT3
 
BULLETIN
Tropical Storm Melissa Advisory Number   5
NWS National Hurricane Center Miami FL       AL132025
1100 AM EDT Wed Oct 22 2025
 
...MELISSA DRIFTING WEST-NORTHWESTWARD IN THE CENTRAL CARIBBEAN...
...HEAVY RAINFALL AND FLOODING EXPECTED OVER PORTIONS OF HISPANIOLA
AND JAMAICA OVER THE REMAINDER OF THIS WEEK...
 
 
SUMMARY OF 1100 AM EDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.4N 73.6W
ABOUT 300 MI...485 KM SSW OF PORT AU PRINCE HAITI
ABOUT 325 MI...525 KM SE OF KINGSTON JAMAICA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Tropical Storm Watch is in effect for...
* Jamaica
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, and Cuba
should monitor the progress of Melissa.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM EDT (1500 UTC), the center of Tropical Storm Melissa was 
located by Air Force Reserve reconnaissance aircraft near latitude 
14.4 North, longitude 73.6 West. Melissa is moving slowly toward the 
west-northwest near 2 mph (4 km/h). A continued slow forward speed 
and a gradual turn to the northwest and north-northwest is expected 
during the next couple of days, followed by a turn back westward by 
the end of the week.  On the forecast track, Melissa is expected to 
approach Jamaica and the southwestern portion of Haiti later this 
week.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts. 
Some gradual strengthening is anticipated during the next few days, 
and Melissa could become a hurricane by Friday. 
 
Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The minimum central pressure estimated by aircraft dropsonde data is 
1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area in
Haiti beginning late on Thursday.  Tropical storm conditions could
begin in Jamaica late on Thursday or Friday.
 
RAINFALL:  Melissa is expected to bring 5 to 10 inches of rain to
the southern Dominican Republic, southern Haiti, and eastern Jamaica
through Saturday, with locally higher amounts possible. Additional
heavy rainfall is possible beyond Saturday; however, uncertainty in
Melissa’s track and forward speed reduces confidence in exact
totals. Significant flash flooding and landslides are possible.
 
Across Puerto Rico, northern Dominican Republic, northern Haiti, and 
western Jamaica, 2 to 4 inches of rain is expected through Saturday. 
Flash and urban flooding will be possible through at least Saturday.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
SURF:  Swells generated by Melissa are expected to spread to
Hispaniola, Jamaica, and eastern Cuba during the next couple of
days.  Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at3.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM EDT.
Next complete advisory at 500 PM EDT.
 
$$
Forecaster Papin
  