ZCZC MIATCPAT3 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Tropical Storm Melissa Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       AL132025
800 PM EDT Wed Oct 22 2025
 
...MELISSA MOVING VERY SLOWLY IN THE CENTRAL CARIBBEAN...
...HEAVY RAINFALL AND FLOODING EXPECTED OVER PORTIONS OF HISPANIOLA
AND JAMAICA INTO THE WEEKEND...
 
 
SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...14.3N 74.5W
ABOUT 330 MI...530 KM SSW OF PORT AU PRINCE HAITI
ABOUT 300 MI...480 KM SSE OF KINGSTON JAMAICA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 1 MPH...2 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Tropical Storm Watch is in effect for...
* Jamaica
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, and Cuba
should monitor the progress of Melissa.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Tropical Storm Melissa was
located by an Air Force reconnaissance aircraft near latitude 14.3 
North, longitude 74.5 West.  Melissa is drifting toward the west 
near 1 mph (2 km/h).  A slow forward speed and a gradual turn to 
the northwest or north-northwest is forecast during the next couple 
of days, followed by a westward turn by this weekend.  On the 
forecast track,  Melissa is expected to be nearer to Jamaica and 
the southwestern portion of Haiti later this week.

Maximum sustained winds are near 50 mph (85 km/h) with higher
gusts.  Some slow strengthening is forecast during the next few 
days, and Melissa could become a hurricane by Friday, with more 
substantial intensification forecast by this weekend. 

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area in
Haiti beginning on Friday.  Tropical storm conditions could begin in
Jamaica late on Thursday or on Friday.
 
RAINFALL: Melissa is expected to bring 5 to 10 inches of rain to the
southern Dominican Republic, southern Haiti, and eastern Jamaica
through Saturday, with locally higher amounts possible.  Additional
heavy rainfall is possible beyond Saturday.  However, uncertainty
in Melissa’s track and forward speed reduces confidence in exact
totals.  Significant, life-threatening flash flooding and numerous
landslides are possible.
 
Across Puerto Rico, northern Dominican Republic, northern Haiti, and
western Jamaica, 2 to 4 inches of rain is expected through Saturday.
Flash and urban flooding will be possible through at least Saturday.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
SURF:  Swells generated by Melissa are expected to spread to
Hispaniola, Jamaica, and eastern Cuba during the next couple of
days.  Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at3.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Pasch
 
NNNN
  