000
WTNT33 KNHC 230535
TCPAT3
 
BULLETIN
Tropical Storm Melissa Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       AL132025
200 AM EDT Thu Oct 23 2025
 
...MELISSA CRAWLING OVER THE CENTRAL CARIBBEAN SEA...
...EXPECTED TO BRING HEAVY RAINS AND LIFE-THREATENING FLOODING TO 
PORTIONS OF HISPANIOLA AND JAMAICA INTO THE WEEKEND...
 
 
SUMMARY OF 200 AM EDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...14.5N 74.7W
ABOUT 280 MI...450 KM SSE OF KINGSTON JAMAICA
ABOUT 325 MI...520 KM SSW OF PORT AU PRINCE HAITI
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Tropical Storm Watch is in effect for...
* Jamaica
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, and Cuba
should monitor the progress of Melissa.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM EDT (0600 UTC), the center of Tropical Storm Melissa was
located near latitude 14.5 North, longitude 74.7 West. Melissa is
moving toward the west near 2 mph (4 km/h). A slow forward speed 
and a gradual turn to the northwest or north-northwest is forecast 
during the next day or two, followed by a westward turn by the 
weekend.  On the forecast track,  Melissa is expected to be nearer 
to Jamaica and the southwestern portion of Haiti during the next 
couple of days.
 
Maximum sustained winds remain near 50 mph (85 km/h) with higher
gusts. Some slow strengthening is forecast during the next day or 
two, with more substantial intensification expected by the 
weekend.  Melissa is forecast to become a hurricane in a couple of 
days.
 
Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area in
Haiti beginning on Friday.  Tropical storm conditions could begin in
Jamaica tonight or on Friday.
 
RAINFALL: Melissa is expected to bring 5 to 10 inches of rain to the
southern Dominican Republic, southern Haiti, and eastern Jamaica
through Saturday, with locally higher amounts possible.  Additional
heavy rainfall is possible beyond Saturday.  However, uncertainty
in Melissa’s track and forward speed reduces confidence in exact
totals.  Significant, life-threatening flash flooding and numerous
landslides are possible.
 
Across Puerto Rico, northern Dominican Republic, northern Haiti, and
western Jamaica, 2 to 4 inches of rain is expected through Saturday.
Flash and urban flooding will be possible through at least Saturday.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
SURF:  Swells generated by Melissa are expected to affect portions 
of Hispaniola, Jamaica, and eastern Cuba during the next several
days.  Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at3.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Cangialosi
  