000
WTNT33 KNHC 230838
TCPAT3
 
BULLETIN
Tropical Storm Melissa Advisory Number   8
NWS National Hurricane Center Miami FL       AL132025
500 AM EDT Thu Oct 23 2025
 
...MELISSA CRAWLING OVER THE CENTRAL CARIBBEAN SEA...
...EXPECTED TO BRING HEAVY RAINS AND LIFE-THREATENING FLOODING TO
PORTIONS OF HISPANIOLA AND JAMAICA INTO THE WEEKEND...
 
 
SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.0N 74.9W
ABOUT 240 MI...390 KM SSE OF KINGSTON JAMAICA
ABOUT 300 MI...485 KM SW OF PORT AU PRINCE HAITI
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Tropical Storm Watch is in effect for...
* Jamaica
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.
 
A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, and Cuba
should monitor the progress of Melissa.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Tropical Storm Melissa was
located near latitude 15.0 North, longitude 74.9 West. Melissa is
moving toward the west-northwest near 3 mph (6 km/h). A slow
northwest or north motion is forecast during the next couple of
days, followed by a westward turn over the weekend.  On the forecast
track,  Melissa is expected to be nearer to Jamaica and the
southwestern portion of Haiti during the next couple of days.
 
Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Little change in strength is expected during the next day or so,
but significant strengthening is expected by late Friday and over
the weekend.  Melissa is forecast to become a hurricane in a couple
of days.
 
Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The estimated minimum central pressure is 1002 mb (29.59 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND:  Hurricane conditions are possible within the watch area in
Haiti beginning on Friday.  Tropical storm conditions could begin in
Jamaica on Friday.
 
RAINFALL: Melissa is expected to bring 5 to 10 inches of rain to the
southern Dominican Republic, southern Haiti, and eastern Jamaica
through Sunday, with locally higher amounts possible. Additional
heavy rainfall is possible beyond Sunday; however, uncertainty in
Melissa’s track and forward speed reduces confidence in exact
totals. Significant, life-threatening flash flooding and numerous
landslides are possible.
 
Across Puerto Rico, northern Dominican Republic, northern Haiti, and
western Jamaica, 2 to 4 inches of rain is expected through Sunday.
Flash and urban flooding will be possible through at least Sunday.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
SURF:  Swells generated by Melissa are expected to affect portions
of Hispaniola, Jamaica, and eastern Cuba during the next several
days.  Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_at3.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Cangialosi
  