ZCZC MIATCPAT3 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Tropical Storm Melissa Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       AL132025
800 AM EDT Fri Oct 24 2025
 
...MELISSA DRIFTING EAST-SOUTHEASTWARD AS RECONNAISSANCE 
INVESTIGATES THIS MORNING...
...LIFE-THREATENING AND CATASTROPHIC FLASH FLOODING AND LANDSLIDES
EXPECTED IN PORTIONS OF SOUTHERN HISPANIOLA AND JAMAICA THROUGH THE
WEEKEND...
 
 
SUMMARY OF 800 AM EDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...15.9N 75.0W
ABOUT 185 MI...300 KM SE OF KINGSTON JAMAICA
ABOUT 260 MI...415 KM SW OF PORT AU PRINCE HAITI
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...ESE OR 105 DEGREES AT 1 MPH...2 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
* Jamaica
 
A Tropical Storm Warning in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
* Jamaica
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours before
the anticipated first occurrence of tropical-storm-force winds,
conditions that make outside preparations difficult or dangerous.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, and eastern
Cuba should monitor the progress of Melissa.  A hurricane warning
may be required for Jamaica later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM EDT (1200 UTC), the center of Tropical Storm Melissa was 
located by Air Force reconnaissance aircraft near latitude 15.9 
North, longitude 75.0 West. Melissa is drifting toward the 
east-southeast near 1 mph (2 km/h). A slow drift toward the 
northeast and north is expected to begin later today and tonight.  A 
westward drift is then forecast to begin on Saturday and continue 
through Monday.  On the forecast track, the center of Melissa is 
expected to move near or just south of Jamaica early next week.
 
Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Gradual strengthening is forecast over the next day or so, followed 
by rapid intensification this weekend.  Melissa is forecast to 
become a hurricane by Saturday and a major hurricane by Sunday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The minimum central pressure estimated by aircraft dropsonde data is 
1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND: Hurricane conditions are possible within the watch area in
Haiti on Saturday and Jamaica beginning late Saturday or Sunday.
Tropical storm conditions are expected to begin in Haiti later today
and in Jamaica on Saturday.
 
RAINFALL: Melissa is expected to bring 8 to 14 inches of rain to
southern Dominican Republic, southern Haiti, and eastern Jamaica
through Sunday night, with locally higher amounts possible.
Additional heavy rainfall is likely beyond Sunday night; however,
uncertainty in Melissa’s track and forward speed reduces confidence
in exact totals. Significant, life-threatening flash flooding and
numerous landslides are expected in the southern Dominican Republic
and eastern Jamaica, with catastrophic flash flooding and landslides
anticipated in southern Haiti.
 
Across northern Dominican Republic, northern Haiti, and western
Jamaica, 3 to 5 inches of rain are expected through Sunday night.
Flash and urban flooding will be possible through Sunday night.
Flooding impacts may increase across western Jamaica next week.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
STORM SURGE: Minor coastal flooding is likely along the coast of
Jamaica by Saturday in areas of onshore winds as tropical storm
conditions begin to reach the area.  However, there is a potential
risk of a more significant storm surge, especially along the south
coast of Jamaica, early next week.  Due to Melissa's slow motion and
large forecast uncertainty, it is still too soon to know exactly how
high the storm surge could reach.
 
SURF: Swells generated by Melissa are expected to affect portions
of Hispaniola, Jamaica, and eastern Cuba during the next several
days.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Papin
 
NNNN
  