000
WTNT33 KNHC 251152
TCPAT3
 
BULLETIN
Tropical Storm Melissa Intermediate Advisory Number 16A
NWS National Hurricane Center Miami FL       AL132025
800 AM EDT Sat Oct 25 2025
 
...MELISSA NEAR HURRICANE STRENGTH AND FORECAST TO RAPIDLY INTENSIFY 
THIS WEEKEND...
...LIFE-THREATENING AND CATASTROPHIC FLASH FLOODING AND LANDSLIDES 
EXPECTED IN PORTIONS OF SOUTHERN HISPANIOLA AND JAMAICA THROUGH THE 
WEEKEND...
 
 
SUMMARY OF 800 AM EDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...16.4N 75.0W
ABOUT 160 MI...260 KM SE OF KINGSTON JAMAICA
ABOUT 235 MI...375 KM SW OF PORT AU PRINCE HAITI
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 1 MPH...2 KM/H
MINIMUM CENTRAL PRESSURE...982 MB...29.00 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Jamaica
 
A Hurricane Watch is in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Tropical Storm Warning in effect for...
* Southwestern peninsula of Haiti from the border with the
Dominican Republic to Port-Au-Prince
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.
 
A Hurricane Watch means that hurricane conditions are possible
within the watch area.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.
 
Interests elsewhere in Haiti, the Dominican Republic, eastern Cuba,
the Bahamas, and the Turks and Caicos Islands should monitor the
progress of Melissa. Watches could be required for portions of
eastern Cuba later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM EDT (1200 UTC), the center of Tropical Storm Melissa was
located by both NOAA and Air Force Reserve Hurricane Hunter 
aircraft near latitude 16.4 North, longitude 75.0 West. Melissa is
moving slowly toward the west-northwest near 1 mph (2 km/h). 
 
Maximum sustained winds remain near 70 mph (110 km/h) with higher 
gusts. Rapid intensification is forecast to begin over the next 24 
hours. Melissa is forecast to become a hurricane shortly and a major 
hurricane by Sunday.
 
Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The minimum central pressure measured by Air Force and NOAA aircraft 
dropsonde data is 982 mb (29.00 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND: Tropical storm conditions are expected to begin in Jamaica by
tonight, with hurricane conditions expected by Sunday or Monday.
Tropical storm conditions are expected and hurricane conditions are
possible within the watch and warning area in Haiti later today.
 
RAINFALL: Melissa is expected to bring total rainfall of 15 to 25
inches to portions of southern Hispaniola and Jamaica through
Tuesday, with local maxima of 35 inches possible across the Tiburon
Peninsula of Haiti.  Additional heavy rainfall is likely beyond
Tuesday; uncertainty at that time range precludes exact storm
totals.  Potential catastrophic flash flooding and landslides are
possible across portions of Jamaica and the southern Dominican
Republic, while catastrophic flash flooding is anticipated in
southern Haiti.
 
For eastern Cuba, total rainfall of 4 to 8 inches, with local
amounts to 12 inches, is possible into Tuesday.  Additional heavy
rainfall is likely beyond Tuesday; uncertainty at that time range
precludes exact storm totals.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
STORM SURGE: Minor coastal flooding is likely along the coast of
Jamaica starting by tonight in areas of onshore winds as tropical
storm conditions begin to reach the area.
 
However, there is a risk of a more life-threatening storm surge,
especially along the south coast of Jamaica, later in the
weekend or early next week.  Peak storm surge heights could reach 5
to 10 feet above ground level, near and to the east of where the
center of Melissa makes landfall. This storm surge will be
accompanied by large and destructive waves.
 
SURF: Swells generated by Melissa are expected to affect portions
of Hispaniola, Jamaica, and eastern Cuba during the next several
days.  Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Papin
  