676 
WTNT33 KNHC 292358
TCPAT3
 
BULLETIN
Hurricane Melissa Intermediate Advisory Number 34A
NWS National Hurricane Center Miami FL       AL132025
800 PM EDT Wed Oct 29 2025
 
...MELISSA PRODUCING DAMAGING WINDS, FLOODING RAINS, AND A
DANGEROUS STORM SURGE IN THE BAHAMAS...
 
 
SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...23.5N 74.8W
ABOUT 65 MI...100 KM E OF THE CENTRAL BAHAMAS
ABOUT 860 MI...1385 KM SW OF BERMUDA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NNE OR 25 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Southeastern and Central Bahamas
* Bermuda
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. Residents in the Bahamas should
remain sheltered. In Bermuda, preparations should be underway and be
completed before anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Hurricane Melissa was
located by an Air Force Reserve Hurricane Hunter aircraft 
near latitude 23.5 North, longitude 74.8 West.  Melissa is
moving toward the north-northeast near 16 mph (26 km/h).  An 
accelerating northeastward motion is expected during the next few 
days.  On the forecast track, the core of Melissa is expected to 
continue to move across the southeastern or central Bahamas this 
evening, and is forecast to pass near or to the west of Bermuda 
late Thursday and Thursday night.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher 
gusts. Some restrengthening is forecast tonight into tomorrow with 
weakening beginning thereafter. 
 
Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).  A private weather station at Pitts Town on Crooked Island 
recently reported sustained winds of 76 mph (122 km/h) and a wind 
gust of 85 mph (137 km/h).
 
The estimated minimum central pressure is 970 mb (28.65 inches) 
based on dropsonde data.
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND: Hurricane conditions are occurring within the warning area in
the southeastern and central Bahamas and should continue through
tonight. Tropical storm conditions are ongoing in the Turks and
Caicos Islands and should continue through tonight.
 
Hurricane conditions are now expected on Bermuda late Thursday and
Thursday night with Tropical storm conditions expected earlier on
Thursday.
 
RAINFALL: Over the Southeast Bahamas, storm total rainfall of 5 to
10 inches are expected through Thursday morning, which will result
in areas of flash flooding. For the Turks and Caicos rainfall totals
of 1 to 3 inches are expected. Heavy rain may begin to affect
Bermuda on Thursday or Thursday night.
 
Over southern Hispaniola, additional rainfall of 1 to 2 inches are
through this evening, with storm total local maxima of 40 inches
possible.
 
For eastern Cuba, the rainfall has subsided. However, additional
scattered showers are expected through this evening, with additional
rainfall amounts of 1 to 2 inches. With storm total rainfall of 10
to 20 inches, possibly up to 25 inches over mountainous terrain, the
ongoing life-threatening and potentially catastrophic flash flooding
and landslides will likely persist into the evening.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
STORM SURGE: Storm surge of 4 to 7 ft above normally dry ground is
possible in the southeastern Bahamas tonight, and minor coastal
flooding is possible in the Turks and Caicos Islands tonight.
 
SURF: Swells generated by Melissa will continue to affect portions
of Hispaniola, Jamaica, eastern Cuba, the Cayman Islands for the
remainder of the day, will affect the Bahamas and the Turks and
Caicos Islands for the next few days, and will spread toward Bermuda
later this week, causing life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.
 
$$
Forecaster Blake
  