000
WTNT33 KNHC 300254
TCPAT3
 
BULLETIN
Hurricane Melissa Advisory Number  35
NWS National Hurricane Center Miami FL       AL132025
1100 PM EDT Wed Oct 29 2025
 
...DAMAGING WINDS, FLOODING RAINS, AND DANGEROUS STORM SURGE 
ONGOING IN THE BAHAMAS DUE TO MELISSA...
 
 
SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.3N 74.3W
ABOUT 105 MI...170 KM ENE OF THE CENTRAL BAHAMAS
ABOUT 800 MI...1285 KM SW OF BERMUDA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...970 MB...28.65 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Southeastern and Central Bahamas
* Bermuda
 
A Tropical Storm Warning is in effect for...
* Turks and Caicos Islands
 
A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area. Residents in the Bahamas should 
remain sheltered. In Bermuda, preparations should be underway and be 
completed before the anticipated first occurrence of 
tropical-storm-force winds, conditions that make outside 
preparations difficult or dangerous.
 
A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Hurricane Melissa was 
located near latitude 24.3 North, longitude 74.3 West.  Melissa is 
moving toward the north-northeast near 21 mph (33 km/h).  An 
accelerating northeastward motion is expected during the next few 
days.  On the forecast track, the core of Melissa is expected to 
continue moving near the southeastern or central Bahamas overnight, 
and is forecast to pass near or to the west of Bermuda late Thursday 
and Thursday night.
 
Data from an Air Force Reserve Hurricane Hunter aircraft indicate 
that the maximum sustained winds have increased to near 100 mph 
(155 km/h) with higher gusts.  Further strengthening is possible 
tomorrow before weakening likely begins on Friday.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 970 mb (28.65 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND: Hurricane conditions are occurring within the warning area in
the southeastern and central Bahamas and should continue overnight. 
Tropical storm conditions are ongoing in the Turks and Caicos 
Islands and should continue overnight.
 
Hurricane conditions are expected on Bermuda late Thursday and
Thursday night with tropical storm conditions expected earlier on
Thursday.
 
RAINFALL: Over the Southeastern Bahamas, storm total rainfall of 5 
to 10 inches is expected through Thursday morning, which will result 
in areas of flash flooding. For the Turks and Caicos, rainfall 
totals of 1 to 2 inches are expected.

Over southern Hispaniola, additional rainfall of 1 to 2 inches is 
expected through tonight, with storm total local maxima of 40 inches 
possible.

Across Bermuda, outer bands east of Melissa’s track may bring up to 
an inch or 25 mm of rain Thursday and Thursday night.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
STORM SURGE: Storm surge of 4 to 7 ft above normally dry ground is
possible in the southeastern Bahamas overnight, and minor coastal
flooding is possible in the Turks and Caicos Islands overnight.
 
SURF:  Swells generated by Melissa will continue to affect portions
of Hispaniola, Cuba, the Bahamas and the Turks and Caicos Islands 
for the next few days, and will spread toward Bermuda later this 
week, causing life-threatening surf and rip current conditions. 
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.
 
$$
Forecaster Blake
  