000
WTNT33 KNHC 301157
TCPAT3
 
BULLETIN
Hurricane Melissa Intermediate Advisory Number 36A
NWS National Hurricane Center Miami FL       AL132025
800 AM EDT Thu Oct 30 2025
 
...MELISSA WILL BE APPROACHING BERMUDA LATER TODAY AND TONIGHT...
...HURRICANE WARNING IN EFFECT FOR BERMUDA...
 
 
SUMMARY OF 800 AM EDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...26.8N 72.7W
ABOUT 605 MI...980 KM SW OF BERMUDA
ABOUT 295 MI...475 KM NE OF THE CENTRAL BAHAMAS
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...965 MB...28.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
None.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
A Hurricane Warning is in effect for...
* Bermuda
 
A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area. Preparations should be rushed to
completion in Bermuda before tropical-storm-force winds reach the
island later today.
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM EDT (1200 UTC), the center of Hurricane Melissa was
located by an Air Force Hurricane Hunter aircraft near latitude 
26.8 North, longitude 72.7 West.  Melissa is moving toward the 
north-northeast near 21 mph (33 km/h), and the hurricane is expected 
to continue accelerating northeastward during the next couple of 
days.  On the forecast track, the center of Melissa is expected to 
pass to the northwest of Bermuda later today and tonight.
 
Maximum sustained winds are near 105 mph (165 km/h) with higher
gusts.  Little change in strength is expected today, and a 
weakening trend is likely to begin on Friday.
 
Hurricane-force winds extend outward up to 60 miles (95 km) from
the center and tropical-storm-force winds extend outward up to 195
miles (315 km).
 
The minimum central pressure reported by the Hurricane Hunters is 
965 mb (28.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND: Tropical storm conditions will begin on Bermuda later today,
with hurricane conditions expected there tonight.
 
RAINFALL: Over the Southeastern Bahamas and the Turks and Caicos,
an additional inch of rain is possible, with storm total maxima up
to 10 inches in the southeast Bahamas and storm total maxima up to
4 inches across the Turks and Caicos. Any residual flooding should
be waning.
 
Over portions of Hispaniola, additional rainfall of 1 to 3 inches
is possible this morning, with storm total accumulations up to 40
inches possible in southern Hispaniola.
 
Across Bermuda, outer bands east of Melissa’s track may bring up t
an inch (25 mm) of rain today and tonight.
 
For a complete depiction of forecast rainfall associated with
Melissa, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at3.shtml?rainqpf
 
STORM SURGE: Water levels should continue to subside through the
morning for the southeastern Bahamas.
 
Coastal flooding from storm surge is possible in areas of onshore
winds for Bermuda.
 
SURF: Swells generated by Melissa will continue to affect portions
of Hispaniola, Cuba, the Bahamas, and the Turks and Caicos Islands
during the next couple of days, and will spread toward Bermuda later
today, causing life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM EDT.
 
$$
Forecaster Pasch
  