000
WTNT33 KNHC 310846
TCPAT3
 
BULLETIN
Hurricane Melissa Advisory Number  40
NWS National Hurricane Center Miami FL       AL132025
500 AM AST Fri Oct 31 2025
 
...MELISSA MOVING QUICKLY AWAY FROM BERMUDA...
...EXPECTED TO BECOME AN EXTRATROPICAL CYCLONE LATER TODAY...
 
 
SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...35.9N 64.0W
ABOUT 255 MI...405 KM N OF BERMUDA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NE OR 40 DEGREES AT 41 MPH...67 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:
 
The Meteorological Service of Bermuda has discontinued the Hurricane 
Warning for Bermuda.
 
SUMMARY OF WATCHES AND WARNINGS IN EFFECT:
 
None.
 
After Melissa becomes post-tropical, a brief period of heavy rain
and gusty winds is possible over the southern Avalon Peninsula of
Newfoundland tonight. For more information on impacts in Canada, see
the Canadian Hurricane Center website at
https://weather.gc.ca/hurricane/index_e.html
 
For storm information specific to your area, please monitor
products issued by your national meteorological service.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Melissa was 
located near latitude 35.9 North, longitude 64.0 West. Melissa is 
moving toward the northeast near 41 mph (67 km/h). This general 
motion is expected to continue into Saturday, followed by a gradual 
slowdown and turn toward the east-northeast later this weekend. On 
the forecast track, the center of Melissa is expected to pass to the 
south of the Avalon Peninsula of Newfoundland as a post-tropical 
cyclone tonight.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher 
gusts. Melissa is expected to become a strong post-tropical cyclone 
later today, with gradual weakening forecast over the weekend.
 
Hurricane-force winds extend outward up to 80 miles (130 km) from
the center and tropical-storm-force winds extend outward up to 265
miles (425 km).
 
The estimated minimum central pressure is 973 mb (28.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Melissa can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.
 
WIND: Gusty winds over Bermuda will gradually subside this morning.
Gusty winds are possible over the southern Avalon Peninsula of
Newfoundland tonight.
 
RAINFALL: A brief period of heavy rain is possible over the southern
Avalon Peninsula of Newfoundland tonight.
 
STORM SURGE: Water levels should continue to subside this morning
for Bermuda.
 
SURF: Swells generated by Melissa will continue to affect portions
of Hispaniola, Cuba, the Bahamas, the Turks and Caicos Islands, and
Bermuda during the next couple of days. These swells are expected to
reach the coast of the Northeastern United States and Atlantic
Canada today and persist into the weekend. These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.
 
$$
Forecaster Reinhart
  