663 
WTPZ31 KNHC 300233
TCPEP1
 
BULLETIN
Tropical Storm Alvin Advisory Number   6
NWS National Hurricane Center Miami FL       EP012025
800 PM MST Thu May 29 2025
 
...ALVIN REMAINS WELL OFFSHORE OF SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...16.0N 107.9W
ABOUT 495 MI...795 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Tropical Storm Alvin was 
located near latitude 16.0 North, longitude 107.9 West. Alvin is 
moving toward the northwest near 13 mph (20 km/h). A turn toward the 
north-northwest and north is expected to begin on Friday and 
continue through the weekend.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Gradual weakening is forecast during the next couple of days, and
Alvin is expected to degenerate to a post-tropical low on Saturday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Alvin will affect portions of the coasts
of west-central Mexico and the southern Baja California Peninsula
during the next couple of days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Reinhart
  