564 
WTPZ31 KNHC 302043
TCPEP1
 
BULLETIN
Tropical Storm Alvin Advisory Number   9
NWS National Hurricane Center Miami FL       EP012025
200 PM MST Fri May 30 2025
 
...TROPICAL STORM ALVIN MOVING NORTH-NORTHWESTWARD...
 
...LARGE SWELL AND RIP CURRENTS POSSIBLE ACROSS PORTIONS OF WESTERN
MAINLAND MEXICO AND SOUTHERN BAJA CALIFORNIA PENINSULA THROUGH THE
WEEKEND...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.1N 109.0W
ABOUT 335 MI...540 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Tropical Storm Alvin was
located near latitude 18.1 North, longitude 109.0 West. Alvin is
moving toward the north-northwest near 10 mph (17 km/h). A turn 
toward the north is expected tonight, and this motion should 
continue through the weekend.

Maximum sustained winds remain near 50 mph (85 km/h) with higher 
gusts. Weakening is forecast, and Alvin is expected to degenerate to 
a remnant low on Saturday.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Alvin will affect portions of the coasts
of west-central and southwestern Mexico and the southern Baja
California Peninsula through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Hagen
  