225 
WTPZ31 KNHC 310248
TCPEP1
 
BULLETIN
Tropical Storm Alvin Advisory Number  10
NWS National Hurricane Center Miami FL       EP012025
800 PM MST Fri May 30 2025
 
...ALVIN WEAKENING...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...19.1N 109.1W
ABOUT 265 MI...430 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Tropical Storm Alvin was
located near latitude 19.1 North, longitude 109.1 West. Alvin is
moving toward the north near 10 mph (17 km/h). A slightly slower 
north-northwestward or northward motion is expected during the next 
day or two.
 
Maximum sustained winds have decreased to near 45 mph (75 km/h) 
with higher gusts. Continued weakening is forecast, and Alvin is 
expected to become a remnant low on Saturday and dissipate entirely 
on Sunday.
 
Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.
 
The estimated minimum central pressure is 1003 mb (29.62 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Alvin will affect portions of the coasts
of west-central and southwestern Mexico and the southern Baja
California Peninsula through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Cangialosi
  