000
WTPZ31 KNHC 311436
TCPEP1
 
BULLETIN
Post-Tropical Cyclone Alvin Advisory Number  12
NWS National Hurricane Center Miami FL       EP012025
800 AM MST Sat May 31 2025
 
...ALVIN DEGENERATES TO A REMNANT LOW...
...SWELLS AND RIP CURRENTS POSSIBLE ALONG PORTIONS OF THE COASTS OF
WEST-CENTRAL MAINLAND MEXICO AND SOUTHERN BAJA CALIFORNIA THIS
WEEKEND...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...20.7N 109.5W
ABOUT 155 MI...250 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Post-Tropical Cyclone Alvin
was located near latitude 20.7 North, longitude 109.5 West. The
post-tropical cyclone is moving toward the north near 9 mph (15
km/h).  A slightly slower northward motion is expected through 
tonight. 

Maximum sustained winds have decreased to near 35 mph (55 km/h) 
with higher gusts. Additional weakening is expected today and the 
low is forecast to dissipate by Sunday. 

The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by this system will affect portions of the
coasts of west-central Mexico and the southern Baja California
Peninsula through the weekend. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane
Center on Alvin.  Additional information on this system can be 
found in High Seas Forecasts issued by the National Weather 
Service, under AWIPS header NFDHSFAT1, WMO header FZNT01 KWBC, and 
online at ocean.weather.gov/shtml/NFDHSFAT1.php
 
$$
Forecaster Brown
  