486 
WTPZ32 KNHC 080838
TCPEP2
 
BULLETIN
Tropical Storm Barbara Advisory Number   1
NWS National Hurricane Center Miami FL       EP022025
300 AM CST Sun Jun 08 2025
 
...TROPICAL STORM BARBARA FORMS OFFSHORE OF SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 300 AM CST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.2N 102.4W
ABOUT 180 MI...290 KM SSW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 AM CST (0900 UTC), the center of Tropical Storm Barbara was 
located near latitude 15.2 North, longitude 102.4 West. Barbara is 
moving toward the west-northwest near 12 mph (19 km/h), and this 
motion is expected to continue for the next couple of days. A turn 
toward the west at a slower forward speed is anticipated on Tuesday.
 
Satellite-derived wind data indicate that maximum sustained winds 
are near 45 mph (75 km/h) with higher gusts. Strengthening is 
forecast during the next day or so, and Barbara is forecast to 
become a hurricane on Monday.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Rainfall totals of 2 to 4 inches, with localized amounts
up to 6 inches, are possible across portions of the Mexican states
of Guerrero, Michoacan, Colima, and Jalisco through Monday. This
rainfall may lead to areas of flooding and mudslides.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Barbara, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Barbara will affect portions of the coast
of southwestern Mexico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 AM CST.
 
$$
Forecaster Reinhart
  