000
WTPZ32 KNHC 081436
TCPEP2
 
BULLETIN
Tropical Storm Barbara Advisory Number   2
NWS National Hurricane Center Miami FL       EP022025
900 AM CST Sun Jun 08 2025
 
...BARBARA STRENGTHENING...
 
 
SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...15.7N 103.1W
ABOUT 170 MI...275 KM SW OF ZIHUATANEJO MEXICO
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Tropical Storm Barbara was 
located near latitude 15.7 North, longitude 103.1 West. Barbara is 
moving toward the west-northwest near 12 mph (19 km/h) and this 
motion is expected to continue for the next couple of days. A turn 
toward the west at a slower forward speed is anticipated on Tuesday.
 
Maximum sustained winds have increased to near 60 mph (95 km/h) with 
higher gusts. Additional strengthening is expected during the next 
day or so, and Barbara is forecast to become a hurricane later 
tonight.
 
Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.
 
The estimated minimum central pressure is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Rainfall totals of 2 to 4 inches, with localized amounts
up to 6 inches, are possible across portions of the Mexican states
of Guerrero, Michoacan, Colima, and Jalisco through Monday. This
rainfall may lead to areas of flooding and mudslides.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Barbara, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep2.shtml?rainqpf
 
SURF:  Swells generated by Barbara will affect portions of the coast
of southwestern Mexico during the next few days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
WIND: Gusty winds are likely along coastal areas of southwestern
Mexico.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 PM CST.
 
$$
Forecaster Kelly
  