
ZCZC MIATCPAT2 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Hurricane Kirk Advisory Number  12
NWS National Hurricane Center Miami FL       AL122024
1100 AM AST Wed Oct 02 2024

...KIRK CONTINUES TO STRENGTHEN...
...FORECAST TO BECOME A MAJOR HURRICANE TOMORROW...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.0N 43.0W
ABOUT 1260 MI...2030 KM W OF THE CABO VERDE ISLANDS
ABOUT 1225 MI...1970 KM E OF THE LESSER ANTILLES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...980 MB...28.94 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Kirk was located
near latitude 18.0 North, longitude 43.0 West. Kirk is moving toward
the northwest near 12 mph (19 km/h) and this motion is expected 
over the next several days with a gradual turn more to the 
north-northwest by the end of the week. 

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts.  Additional strengthening is forecast, and Kirk 
is forecast to become a major hurricane tomorrow. 

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 205 miles
(335 km).

The estimated minimum central pressure is 980 mb (28.94 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are beginning to spread outward and
could affect affect portions of Leeward Islands and Bermuda by this
weekend. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Papin

NNNN
