

000
WTNT32 KNHC 022042
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  13
NWS National Hurricane Center Miami FL       AL122024
500 PM AST Wed Oct 02 2024

...KIRK EXPECTED TO BECOME A LARGE AND FORMIDABLE MAJOR HURRICANE...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.9N 44.0W
ABOUT 1330 MI...2145 KM WNW OF THE CABO VERDE ISLANDS
ABOUT 1165 MI...1875 KM ENE OF THE LESSER ANTILLES
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Kirk was located 
near latitude 18.9 North, longitude 44.0 West. Kirk is moving toward 
the northwest near 12 mph (19 km/h) and this general motion is 
expected over the day or so with a gradual turn more to the 
north-northwest and northward by this weekend. 

Maximum sustained winds have increased to near 90 mph (150 km/h) 
with higher gusts.  Strengthening is forecast over the next several 
days and Kirk is expected to become a major hurricane tomorrow. 

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 220 miles
(350 km).

The estimated minimum central pressure is 975 mb (28.80 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are beginning to spread outward and
could affect portions of Leeward Islands and Bermuda by this 
weekend. These swells are likely to cause life-threatening surf and 
rip current conditions. Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Papin

