

941 
WTNT32 KNHC 030035
TCPAT2

BULLETIN
Hurricane Kirk Special Advisory Number  14
NWS National Hurricane Center Miami FL       AL122024
800 PM AST Wed Oct 02 2024

...KIRK RAPIDLY INTENSIFYING INTO A MAJOR HURRICANE...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...19.3N 44.3W
ABOUT 1355 MI...2180 KM WNW OF THE CABO VERDE ISLANDS
ABOUT 1150 MI...1855 KM ENE OF THE LESSER ANTILLES
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...955 MB...28.20 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Hurricane Kirk was located
near latitude 19.3 North, longitude 44.3 West. Kirk is moving toward
the northwest near 12 mph (19 km/h) and this general motion is
expected over the day or so with a gradual turn more to the
north-northwest and northward by this weekend.

Maximum sustained winds are near 120 mph (195 km/h) with higher
gusts.  Kirk is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Strengthening is forecast over the next 
couple of days.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 220 miles
(350 km).

The estimated minimum central pressure is 955 mb (28.20 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are beginning to spread outward and
could affect portions of Leeward Islands and Bermuda by this
weekend. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Bucci/Cangialosi


