

838 
WTNT32 KNHC 031439
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  17
NWS National Hurricane Center Miami FL       AL122024
1100 AM AST Thu Oct 03 2024

...KIRK STRENGTHENING OVER THE CENTRAL ATLANTIC...
...LARGE SWELLS COULD REACH THE U.S. EAST COAST BY SUNDAY...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.4N 45.9W
ABOUT 1130 MI...1820 KM E OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1660 MI...2670 KM SW OF THE AZORES
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...948 MB...28.00 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Kirk was located 
near latitude 20.4 North, longitude 45.9 West. Kirk is moving toward 
the northwest near 10 mph (17 km/h), and this general motion is 
expected to continue through early Friday. A turn toward the north 
and north-northeast at a faster forward speed is forecast over the 
weekend.

Maximum sustained winds have increased to near 125 mph (205 km/h) 
with higher gusts.  Kirk is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Some strengthening is forecast 
the next day or so.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).

The estimated minimum central pressure is 948 mb (28.00 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are spreading westward and are
expected to reach portions of the Leeward Islands on Friday,
Bermuda and the Greater Antilles on Saturday, and the east coast
of the United States and the Bahamas on Sunday.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Kelly/E.Adams


