

000
WTNT32 KNHC 040231
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  19
NWS National Hurricane Center Miami FL       AL122024
1100 PM AST Thu Oct 03 2024

...KIRK IS A POWERFUL CATEGORY 4 HURRICANE...
...LARGE SWELLS COULD REACH THE U.S. EAST COAST BY SUNDAY...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.5N 47.5W
ABOUT 1040 MI...1670 KM ENE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1670 MI...2685 KM SW OF THE AZORES
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...935 MB...27.61 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the eye of Hurricane Kirk was located
near latitude 21.5 North, longitude 47.5 West. Kirk is moving toward
the northwest near 10 mph (17 km/h) and this general motion is
expected to continue through Friday. A turn toward the north and
north-northeast at a faster forward speed is forecast over the
weekend.

Maximum sustained winds have increased to near 145 mph (230 km/h)
with higher gusts.  Kirk is a category 4 hurricane on the
Saffir-Simpson Hurricane Wind Scale.  Some additional strengthening
is possible through early Friday, but steady weakening is expected
after that.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).

The estimated minimum central pressure is 935 mb (27.61 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are spreading westward and are
expected to reach portions of the Leeward Islands on Friday,
Bermuda and the Greater Antilles on Saturday, and the east
coast of the United States, Atlantic Canada, and the Bahamas on
Sunday.  These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Cangialosi

