

000
WTNT32 KNHC 040844
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  20
NWS National Hurricane Center Miami FL       AL122024
500 AM AST Fri Oct 04 2024

...KIRK REMAINS A LARGE AND POWERFUL MAJOR HURRICANE...
...LARGE SWELLS FROM KIRK COULD REACH THE U.S. EAST COAST BY
SUNDAY...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 48.1W
ABOUT 1010 MI...1630 KM ENE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1655 MI...2665 KM SW OF THE AZORES
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...934 MB...27.58 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the eye of Hurricane Kirk was located near 
latitude 22.3 North, longitude 48.1 West. Kirk is moving toward the 
northwest near 10 mph (17 km/h), and this general motion is expected 
to continue today. A turn toward the north and north-northeast at a 
faster forward speed is anticipated over the weekend.

Maximum sustained winds are near 145 mph (230 km/h) with higher 
gusts. Kirk is a category 4 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Small intensity fluctuations are possible 
today. Weakening is forecast to begin on Saturday and continue 
through early next week.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 195 miles
(315 km).

The estimated minimum central pressure is 934 mb (27.58 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are spreading westward and are
expected to reach the Leeward Islands later today, Bermuda and the
Greater Antilles on Saturday, the east coast of the United States,
Atlantic Canada, and the Bahamas on Sunday, and the Azores on
Monday. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Reinhart

