

000
WTNT32 KNHC 050232
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  23
NWS National Hurricane Center Miami FL       AL122024
1100 PM AST Fri Oct 04 2024

...KIRK REMAINS A POWERFUL CATEGORY 4 HURRICANE OVER THE OPEN
ATLANTIC...
...LARGE SWELLS FROM KIRK EXPECTED TO REACH THE U.S. EAST COAST BY
SUNDAY...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...25.0N 49.8W
ABOUT 975 MI...1565 KM ENE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1610 MI...2585 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...943 MB...27.85 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the eye of Hurricane Kirk was located
near latitude 25.0 North, longitude 49.8 West. Kirk is moving toward
the north-northwest near 13 mph (20 km/h).  A turn to the north is 
expected on Saturday, followed by a faster northeastward motion 
Sunday and Monday.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Kirk is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Small intensity fluctuations are possible 
overnight, but steady weakening should begin on Saturday.

Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 220 miles
(350 km).

The estimated minimum central pressure is 943 mb (27.85 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, and the Greater Antilles.  These swells are expected to
spread westward to the east coast of the United States, Atlantic
Canada, and the Bahamas Saturday night and Sunday, and the Azores on
Monday. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Cangialosi

