

000
WTNT32 KNHC 050839
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  24
NWS National Hurricane Center Miami FL       AL122024
500 AM AST Sat Oct 05 2024

...KIRK REMAINS A POWERFUL MAJOR HURRICANE OVER THE OPEN ATLANTIC...
...LARGE SWELLS FROM KIRK EXPECTED TO REACH THE U.S. EAST COAST BY
SUNDAY...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...26.2N 50.2W
ABOUT 990 MI...1595 KM NE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1575 MI...2535 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...945 MB...27.91 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Kirk was located 
near latitude 26.2 North, longitude 50.2 West. Kirk is moving toward 
the north-northwest near 13 mph (20 km/h). A turn to the north is 
expected today, followed by a faster northeastward motion on Sunday 
and Monday.

Maximum sustained winds are near 125 mph (205 km/h) with higher 
gusts. Kirk is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Weakening is forecast through early next week, 
but Kirk will remain a large hurricane for the next couple of days.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 220 miles
(350 km).

The estimated minimum central pressure is 945 mb (27.91 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, and the Greater Antilles. These swells are expected to
spread westward to the east coast of the United States, Atlantic
Canada, and the Bahamas Saturday night and Sunday, and to the Azores
on Monday. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Reinhart

