

000
WTNT32 KNHC 051451
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  25
NWS National Hurricane Center Miami FL       AL122024
1100 AM AST Sat Oct 05 2024

...MAJOR HURRICANE KIRK TURNING MORE NORTHWARD...
...LARGE SWELLS FROM KIRK EXPECTED TO REACH THE U.S. EAST COAST BY
SUNDAY...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...27.6N 50.3W
ABOUT 1040 MI...1675 KM NE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1525 MI...2455 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...N OR 355 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...949 MB...28.03 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Kirk was located 
near latitude 27.6 North, longitude 50.3 West. Kirk is moving toward 
the north near 16 mph (26 km/h) and this motion is expected to 
continue through tonight. A faster northeastward motion is expected 
on Sunday and Monday.

Maximum sustained winds are near 120 mph (195 km/h) with higher 
gusts.  Kirk is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale. Weakening is forecast through early next week, 
but Kirk will remain a large hurricane for the next couple of days.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 230 miles
(370 km).

The estimated minimum central pressure is 949 mb (28.03 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, and the Greater Antilles. These swells are expected to
spread westward to the east coast of the United States, Atlantic
Canada, and the Bahamas Saturday night and Sunday, and to the Azores
on Monday. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Kelly

