

000
WTNT32 KNHC 052047
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  26
NWS National Hurricane Center Miami FL       AL122024
500 PM AST Sat Oct 05 2024

...KIRK MOVING NORTHWARD OVER THE CENTRAL ATLANTIC...
...LARGE SWELLS FROM KIRK EXPECTED TO REACH THE U.S. EAST COAST BY
SUNDAY...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...29.6N 50.0W
ABOUT 1140 MI...1835 KM NE OF THE NORTHERN LEEWARD ISLANDS
ABOUT 1435 MI...2310 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...949 MB...28.03 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Kirk was located 
near latitude 29.6 North, longitude 50.0 West. Kirk is moving toward 
the north near 20 mph (31 km/h) and this motion is expected to 
continue through tonight. A faster northeastward motion is expected 
on Sunday and Monday.

Maximum sustained winds are near 120 mph (195 km/h) with higher
gusts.  Kirk is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Weakening is forecast through early next week,
but Kirk will remain a large hurricane for the next couple of days.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 230 miles
(370 km).

The estimated minimum central pressure is 949 mb (28.03 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, and the Greater Antilles. These swells are expected to
spread westward to the east coast of the United States, Atlantic
Canada, and the Bahamas tonight and Sunday, and to the Azores
on Monday. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Kelly

