

000
WTNT32 KNHC 060243
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  27
NWS National Hurricane Center Miami FL       AL122024
1100 PM AST Sat Oct 05 2024

...KIRK SENDING LARGE SWELL TOWARDS THE U.S. EAST COAST...
...INCREASED RISK OF LIFE-THREATENING RIP CURRENTS...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...31.3N 49.3W
ABOUT 1345 MI...2165 KM WSW OF THE AZORES
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 20 MPH...31 KM/H
MINIMUM CENTRAL PRESSURE...951 MB...28.09 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Kirk was located 
near latitude 31.3 North, longitude 49.3 West. Kirk is moving toward 
the north near 20 mph (31 km/h).  On Sunday, Kirk should accelerate 
and turn toward the north-northeast and northeast, followed by an 
east-northeastward to eastward motion on Monday and Tuesday.

Maximum sustained winds have decreased to near 115 mph (185 km/h) 
with higher gusts.  Kirk is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Weakening is forecast through 
early next week, but Kirk will remain a large hurricane for the next 
couple of days.

Hurricane-force winds extend outward up to 60 miles (95 km) from the
center and tropical-storm-force winds extend outward up to 230 miles
(370 km).

The estimated minimum central pressure is 951 mb (28.09 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, the Greater Antilles, the Bahamas, and portions of the east
coast of the United States. These swells are expected to spread
northward along the east coast of the United States, Atlantic Canada
on Sunday, and to the Azores on Monday. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Bucci

