

000
WTNT32 KNHC 060849
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  28
NWS National Hurricane Center Miami FL       AL122024
500 AM AST Sun Oct 06 2024

...KIRK ACCELERATING NORTH-NORTHEASTWARD OVER OPEN WATERS...
...LARGE SWELLS ARE PRODUCING AN INCREASED RISK OF LIFE-THREATENING
RIP CURRENTS ALONG THE U.S. EAST COAST...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...33.5N 49.0W
ABOUT 1270 MI...2040 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...105 MPH...165 KM/H
PRESENT MOVEMENT...NNE OR 15 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...957 MB...28.26 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Kirk was located 
near latitude 33.5 North, longitude 49.0 West. Kirk is moving toward 
the north-northeast near 23 mph (37 km/h). An acceleration toward 
the northeast and east-northeast is expected over the next few days 
while Kirk moves across the northeastern Atlantic.

Maximum sustained winds are near 105 mph (165 km/h) with higher 
gusts. Although weakening is expected through midweek, Kirk will 
remain a large hurricane for the next next day or so before 
transitioning to an extratropical cyclone by early Tuesday.

Hurricane-force winds extend outward up to 70 miles (110 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 957 mb (28.26 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, the Greater Antilles, the Bahamas, and the east coast of
the United States. These swells will continue spreading northward
along the east coast of the United States and Atlantic Canada today,
and to the Azores on Monday. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Reinhart

