
ZCZC MIATCPAT2 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Hurricane Kirk Advisory Number  29
NWS National Hurricane Center Miami FL       AL122024
1100 AM AST Sun Oct 06 2024

...KIRK ACCELERATING NORTH-NORTHEASTWARD OVER OPEN WATERS...
...LARGE SWELLS ARE PRODUCING AN INCREASED RISK OF LIFE-THREATENING
RIP CURRENTS ALONG THE U.S. EAST COAST...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...35.6N 47.7W
ABOUT 1155 MI...1855 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 25 MPH...41 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Kirk was located
near latitude 35.6 North, longitude 47.7 West. Kirk is moving toward
the northeast near 25 mph (41 km/h). An acceleration toward the 
northeast and east-northeast is expected over the next few days
while Kirk moves across the northeastern Atlantic.

Maximum sustained winds are near 100 mph (155 km/h) with higher
gusts.  Although weakening is expected through midweek, Kirk will
remain a large hurricane for the next next day or so before
transitioning to an extratropical cyclone by Monday night.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 290
miles (465 km).

The estimated minimum central pressure is 960 mb (28.35 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, the Greater Antilles, the Bahamas, and the east coast of
the United States. These swells will continue spreading northward
along the east coast of the United States and Atlantic Canada today,
and to the Azores on Monday. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Hagen

NNNN
