

000
WTNT32 KNHC 062035
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  30
NWS National Hurricane Center Miami FL       AL122024
500 PM AST Sun Oct 06 2024

...KIRK SPREADING LARGE SWELLS ACROSS THE NORTH ATLANTIC...
...INCREASED RISK OF LIFE-THREATENING RIP CURRENTS CONTINUE ALONG
THE U.S. EAST COAST...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...37.0N 46.2W
ABOUT 1050 MI...1695 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...961 MB...28.38 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Kirk was located
near latitude 37.0 North, longitude 46.2 West. Kirk is moving toward
the north-northeast near 23 mph (37 km/h). A turn toward the 
northeast is expected tonight. An acceleration toward the 
east-northeast or east is expected by Monday night.

Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts.  Although gradual weakening is expected over the next few 
days and Kirk is expected to become post-tropical on Monday, it will 
remain a large cyclone with a large wind field through the early 
part of this week.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 300
miles (480 km).

The estimated minimum central pressure is 961 mb (28.38 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, the Greater Antilles, the Bahamas, the east coast of the
United States and portions of Atlantic Canada. These swells will
spread to the Azores on Monday. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Hagen

