

325 
WTNT32 KNHC 070232
TCPAT2

BULLETIN
Hurricane Kirk Advisory Number  31
NWS National Hurricane Center Miami FL       AL122024
300 AM GMT Mon Oct 07 2024

...KIRK EXPECTED TO BECOME EXTRATROPICAL ON MONDAY...
...STILL CAUSING LARGE SWELLS AND RIP CURRENT RISK ALONG U.S. EAST
COAST...


SUMMARY OF 300 AM GMT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...38.6N 43.6W
ABOUT 900 MI...1445 KM W OF THE AZORES
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 25 MPH...41 KM/H
MINIMUM CENTRAL PRESSURE...964 MB...28.47 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Azores should monitor the progress of Kirk.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM GMT (0300 UTC), the center of Hurricane Kirk was located
near latitude 38.6 North, longitude 43.6 West. Kirk is moving toward
the northeast near 25 mph (41 km/h).  An even faster 
east-northeastward motion is expected during the next few days.

Maximum sustained winds are near 80 mph (130 km/h) with higher 
gusts. Although gradual weakening is expected, Kirk is forecast to 
become a large and strong extratropical low during the next couple 
of days.

Hurricane-force winds extend outward up to 115 miles (185 km) from
the center and tropical-storm-force winds extend outward up to 310
miles (500 km).

The estimated minimum central pressure is 964 mb (28.47 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Kirk are affecting the Leeward Islands,
Bermuda, the Greater Antilles, the Bahamas, the east coast of the
United States, portions of Atlantic Canada, and the Azores. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM GMT.

$$
Forecaster Cangialosi


