
ZCZC MIATCPEP3 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Otis Advisory Number   4
NWS National Hurricane Center Miami FL       EP182023
400 AM CDT Mon Oct 23 2023

...OTIS EXPECTED TO APPROACH THE SOUTHERN COAST OF MEXICO BY
MIDWEEK...
...TROPICAL STORM WATCH ISSUED FOR A PORTION OF THE COAST OF
SOUTHERN MEXICO...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...11.4N 97.1W
ABOUT 425 MI...680 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Tropical Storm Watch along
the coast of southern Mexico from Lagunas de Chacahua westward to
Tecpan de Galeana.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Lagunas de Chacahua to Tecpan de Galeana

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in elsewhere in southern and southwestern Mexico should
monitor the progress of the Otis.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Otis was
located near latitude 11.4 North, longitude 97.1 West. Otis is
moving toward the north near 5 mph (7 km/h). A north-northwestward
to northward motion is expected during the next few days.  On the
forecast track, the center of Otis will be approaching the southern
coast of Mexico late Tuesday into Wednesday.

Maximum sustained winds have increased to near 45 mph (75 km/h) with 
higher gusts. Some gradual strengthening is forecast during the next 
couple of days.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Otis can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml

RAINFALL:  Otis is expected to produce rainfall totals of 5 to 10
inches with maximum amounts of 15 inches across Guerrero and the
western coastal sections of Oaxaca.  This rainfall is likely to
produce flash and urban flooding, along with mudslides in areas of
higher terrain.

WIND:  Tropical storm conditions are possible within the watch
area by Tuesday night.

SURF: Swells generated by Otis will begin to affect portions of the
southern coast of Mexico by late Tuesday. These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Brown

NNNN
