
ZCZC MIATCPEP3 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Otis Advisory Number   5
NWS National Hurricane Center Miami FL       EP182023
1000 AM CDT Mon Oct 23 2023

...OTIS FORECAST TO STRENGTHEN AS IT APPROACHES SOUTHERN MEXICO...
...HEAVY RAINFALL EXPECTED TO BE THE MAIN THREAT....


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...12.0N 97.5W
ABOUT 375 MI...605 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Lagunas de Chacahua to Tecpan de Galeana

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in elsewhere in southern and southwestern Mexico should
monitor the progress of the Otis.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Otis was
located near latitude 12.0 North, longitude 97.5 West. Otis is
moving toward the north-northwest near 5 mph (7 km/h). A
north-northwestward motion is expected during the next few days.  On
the forecast track, the center of Otis will reach the southern coast
of Mexico early Wednesday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts.
Gradual strengthening is forecast during the next couple of
days.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Otis can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml

RAINFALL:  Otis is expected to produce rainfall totals of 5 to 10
inches with maximum amounts of 15 inches through Friday across
Guerrero and the western coastal sections of Oaxaca.  This rainfall
will produce flash and urban flooding, along with mudslides in areas
of higher terrain.

WIND:  Tropical storm conditions are possible within the watch
area by Tuesday night.

SURF: Swells generated by Otis will begin to affect portions of the 
southern coast of Mexico on Tuesday. These swells are likely to 
cause life-threatening surf and rip current conditions. Please 
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Cangialosi/Delgado

NNNN
