

445 
WTPZ33 KNHC 240847
TCPEP3

BULLETIN
Tropical Storm Otis Advisory Number   8
NWS National Hurricane Center Miami FL       EP182023
400 AM CDT Tue Oct 24 2023

...OTIS STRENGTHENING AND IS EXPECTED TO BECOME A HURRICANE BEFORE 
REACHING THE COAST OF SOUTHERN MEXICO...
...HURRICANE WARNING ISSUED FOR PORTIONS OF SOUTHERN MEXICO...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 98.5W
ABOUT 210 MI...335 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...997 MB...29.44 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Hurricane Warning along the
southern coast of Mexico from Punta Maldonado westward to
Zihuatanejo.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Punta Maldonado westward to Zihuatanejo

A Hurricane Watch is in effect for...
* Lagunas de Chacahua to Punta Maldonado

A Tropical Storm Warning is in effect for...
* Lagunas de Chacahua to Punta Maldonado

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case within the next 24
to 36 hours.  Preparations to protect life and property should be
rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 to 36 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in elsewhere in southern and southwestern Mexico should
monitor the progress of Otis.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Otis was
located near latitude 14.2 North, longitude 98.5 West. Otis is
moving toward the north-northwest near 8 mph (13 km/h), and this
general motion is expected during the next couple of days.  On the
forecast track, Otis is expected to reach the coast of southern
Mexico late tonight or Wednesday. 

Maximum sustained winds have increased to near 65 mph (100 km/h) 
with higher gusts. Additional strengthening is forecast, Otis 
is expected to become a hurricane before it reaches southern Mexico.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 997 mb (29.44 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Otis can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml

RAINFALL:  Otis is expected to produce rainfall totals of 5 to 10
inches with maximum amounts of 15 inches through Friday across
Guerrero and the western coastal sections of Oaxaca.  This rainfall
will produce flash and urban flooding, along with mudslides in areas
of higher terrain.

WIND:  Hurricane conditions are expected withing portions of the 
hurricane warning area by late tonight and Wednesday.  Tropical 
storm conditions are expected to first reach the coast within the 
warning areas later today or this evening, and then spread 
northwestward within the warning areas through Wednesday.

STORM SURGE:  A dangerous storm surge is expected to produce 
significant coastal flooding near and to the east of where the 
center makes landfall.  Near the coast, the surge will be 
accompanied by large and destructive waves.

SURF: Swells generated by Otis will affect portions of the southern
coast of Mexico during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Brown


