

000
WTPZ33 KNHC 241757
TCPEP3

BULLETIN
Hurricane Otis Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       EP182023
100 PM CDT Tue Oct 24 2023

...OTIS BECOMES A HURRICANE...
...FURTHER STRENGTHENING LIKELY UNTIL LANDFALL...


SUMMARY OF 100 PM CDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...14.9N 99.3W
ABOUT 145 MI...235 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Punta Maldonado westward to Zihuatanejo

A Hurricane Watch is in effect for...
* Lagunas de Chacahua to Punta Maldonado

A Tropical Storm Warning is in effect for...
* Lagunas de Chacahua to Punta Maldonado

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case within the next 24
hours.  Preparations to protect life and property should be rushed 
to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in southern and southwestern Mexico should 
monitor the progress of Otis.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 PM CDT (1800 UTC), the center of Hurricane Otis was
located near latitude 14.9 North, longitude 99.3 West.  Otis is
moving toward the north-northwest near 7 mph (11 km/h), and this
general motion is expected during the next couple of days.  On the
forecast track, Otis is expected to reach the coast of southern
Mexico by early Wednesday.

Maximum sustained winds have increased to near 80 mph (130 km/h) 
with higher gusts.  Continued strengthening is forecast until 
the center reaches the coastline.  Rapid weakening is likely after 
landfall.

Hurricane-force winds extend outward up to 15 miles (30 km) from 
the center and tropical-storm-force winds extend outward up to 60 
miles (95 km) from the center.

The estimated minimum central pressure is 985 mb (29.09 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Otis can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml

RAINFALL:  Otis is expected to produce rainfall totals of 5 to 10
inches with maximum amounts of 15 inches through Friday across
Guerrero and the western coastal sections of Oaxaca.  This rainfall
will produce flash and urban flooding, along with mudslides in areas
of higher terrain.

WIND:  Hurricane conditions are expected within portions of the
hurricane warning area by late tonight and Wednesday.  Tropical
storm conditions are expected to first reach the coast within the
warning areas later today or this evening, and then spread
northwestward within the warning areas through Wednesday.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the east of where the
center makes landfall.  Near the coast, the surge will be
accompanied by large and destructive waves.

SURF: Swells generated by Otis will affect portions of the southern
coast of Mexico during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Pasch

