

000
WTPZ33 KNHC 242055
TCPEP3

BULLETIN
Hurricane Otis Advisory Number  10
NWS National Hurricane Center Miami FL       EP182023
400 PM CDT Tue Oct 24 2023

...OTIS RAPIDLY STRENGTHENS INTO A MAJOR HURRICANE...
...NOW EXPECTED TO BE AT CATEGORY 4 INTENSITY AT LANDFALL...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...15.3N 99.5W
ABOUT 115 MI...185 KM SSE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...125 MPH...205 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Punta Maldonado westward to Zihuatanejo

A Hurricane Watch is in effect for...
* Lagunas de Chacahua to Punta Maldonado

A Tropical Storm Warning is in effect for...
* Lagunas de Chacahua to Punta Maldonado

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case within the next 24
hours.  Preparations to protect life and property should be rushed
to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in southern and southwestern Mexico should
monitor the progress of Otis.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Hurricane Otis was located
near latitude 15.3 North, longitude 99.5 West. Otis is moving 
toward the north- northwest near 8 mph (13 km/h), and a north- 
northwestward to northwestward motion is expected during the
next couple of days.  On the forecast track, Otis is expected to
reach the coast of southern Mexico by early Wednesday.

Maximum sustained winds have increased to near 125 mph (205 km/h) 
with higher gusts.  Otis is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Additional strengthening is 
forecast, and Otis is expected to be an extremely dangerous 
category 4 hurricane when the center reaches the coast.  Rapid 
weakening will occur after landfall.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).

The minimum central pressure estimated from Air Force Hurricane 
Hunter observations is 960 mb (28.35 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Otis can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP3 and WMO header WTPZ43 KNHC
and on the web at hurricanes.gov/text/MIATCDEP3.shtml

RAINFALL:  Otis is expected to produce rainfall totals of 5 to 10
inches with maximum amounts of 15 inches through Friday across
Guerrero and the western coastal sections of Oaxaca.  This rainfall
will produce flash and urban flooding, along with mudslides in areas
of higher terrain.

WIND:  Hurricane conditions are expected within portions of the
hurricane warning area by late tonight and Wednesday, with
extremely destructive winds near the core.  Tropical storm
conditions are expected to first reach the coast within the
warning areas later today or this evening, and then spread
northwestward within the warning areas through Wednesday.

STORM SURGE:  A dangerous, life-threatening storm surge is expected
to produce significant coastal flooding near and to the east of
where the center makes landfall.  Near the coast, the surge will be
accompanied by large and destructive waves.

SURF: Swells generated by Otis will affect portions of the southern
coast of Mexico during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Pasch

