

317 
WTPZ33 KNHC 030247
TCPEP3

BULLETIN
Hurricane Carlotta Advisory Number  11
NWS National Hurricane Center Miami FL       EP032024
800 PM PDT Fri Aug 02 2024

...HURRICANE CARLOTTA HEADING WESTWARD...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...18.8N 117.9W
ABOUT 590 MI...945 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...981 MB...28.97 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Hurricane Carlotta was
located near latitude 18.8 North, longitude 117.9 West. Carlotta is
moving toward the west near 14 mph (22 km/h) and this motion is
expected to continue for the next day or so. By Saturday night, 
a turn to the west-northwest is forecast.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Additional strengthening is forecast within the next day, 
followed by steady weakening through early next week.

Hurricane-force winds extend outward up to 10 miles (20 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 981 mb (28.97 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Carlotta along the coasts of west-central
mainland Mexico and the southern Baja California peninsula are
beginning to subside and should diminish by Sunday. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.

$$
Forecaster Bucci


