

000
WTPZ33 KNHC 032042
TCPEP3

BULLETIN
Hurricane Carlotta Advisory Number  14
NWS National Hurricane Center Miami FL       EP032024
200 PM PDT Sat Aug 03 2024

...CARLOTTA MOVING TOWARD A LESS FAVORABLE ENVIRONMENT...


SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...19.0N 120.9W
ABOUT 760 MI...1220 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...982 MB...29.00 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Hurricane Carlotta was
located near latitude 19.0 North, longitude 120.9 West. Carlotta is
moving toward the west near 10 mph (17 km/h). A westward to 
west-northwestward motion is expected during the next few days.

Maximum sustained winds have decreased to near 85 mph (140 km/h) 
with higher gusts.  Gradual weakening is expected through tonight, 
with a more steady rate of weakening forecast by Sunday.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 90 miles
(150 km).

The estimated minimum central pressure is 982 mb (29.00 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Carlotta along the coasts of west-central
mainland Mexico and the southern Baja California peninsula are
gradually subsiding, and should diminish by Sunday. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Hagen/Papin

