

000
WTPZ33 KNHC 040841
TCPEP3

BULLETIN
Tropical Storm Carlotta Advisory Number  16
NWS National Hurricane Center Miami FL       EP032024
200 AM PDT Sun Aug 04 2024

...CARLOTTA NOW A TROPICAL STORM...


SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...19.9N 123.0W
ABOUT 865 MI...1395 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Tropical Storm Carlotta was 
located near latitude 19.9 North, longitude 123.0 West. Carlotta is 
moving toward the west-northwest near 12 mph (19 km/h). This general 
motion is expected to continue through Monday, with a gradual turn 
toward the west on Monday night and Tuesday.

Maximum sustained winds have decreased to near 70 mph (110 km/h) 
with higher gusts. Continued weakening is expected over the next few 
days, and Carlotta is forecast to become a post-tropical remnant low 
on Tuesday.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Carlotta along the coast of the southern
Baja California peninsula are expected to diminish today. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.

$$
Forecaster Reinhart

