

000
WTPZ34 KNHC 150539
TCPEP4

BULLETIN
Tropical Storm Ileana Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       EP092024
1100 PM MST Sat Sep 14 2024

...ILEANA WEAKENING WHILE MEANDERING JUST OFFSHORE NORTHERN 
SINALOA...


SUMMARY OF 1100 PM MST...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...25.4N 109.2W
ABOUT 30 MI...50 KM SSW OF LOS MOCHIS MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Altata to Huatabampito Mexico

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case during the 
next few hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM MST (0600 UTC), the center of Tropical Storm Ileana was
located near latitude 25.4 North, longitude 109.2 West.  Ileana is
meandering off the coast of northern Sinaloa but has a longer-term 
motion toward the west-northwest near 2 mph (4 km/h).  A turn 
toward the northwest is expected soon with an increase in forward 
speed.  On the forecast track, the center of Ileana will move near 
the coastal region of northern Sinaloa overnight, and then move over 
the Gulf of California roughly parallel to the coast on Sunday.

Maximum sustained winds have begun decreasing and are now near 40 
mph (65 km/h) with higher gusts.  Additional weakening is forecast, 
and Ileana is expected to degenerate into a remnant low on Sunday.  
The remnant low is expected to dissipate by Monday.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ileana can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP4 and WMO header WTPZ44 KNHC.

RAINFALL: Tropical Storm Ileana is expected to bring additional
rainfall amounts of 3 to 6 inches, with localized higher amounts up
to 10 inches, across northwest coastal Sinaloa through this weekend.

For a complete depiction of forecast rainfall associated with
Tropical Storm Ileana, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_ep4.shtml?rainqpf

WIND: Tropical storm conditions, especially in gusts, are expected 
across portions of the warning area in northern Sinaloa and 
southern Sonora during the next few hours.

SURF: Swells generated by Ileana will affect portions of the
Gulf of California coasts of Sinaloa, southern Sonora, and southern
Baja California Sur during the next day or so.  These swells could
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.

$$
Forecaster Berg

