000
WTPZ34 KNHC 242031
TCPEP4
 
BULLETIN
Hurricane Narda Advisory Number  13
NWS National Hurricane Center Miami FL       EP142025
200 PM MST Wed Sep 24 2025
 
...NARDA A LITTLE WEAKER BUT FORECAST TO RESTRENGTHEN ON FRIDAY...
 
 
SUMMARY OF 200 PM MST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...15.1N 112.3W
ABOUT 560 MI...905 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...W OR 265 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM MST (2100 UTC), the center of Hurricane Narda was located
near latitude 15.1 North, longitude 112.3 West. Narda is moving
toward the west near 10 mph (17 km/h). This general motion is
expected to continue during the next day or two, followed by a
gradual turn toward the west-northwest Thursday night and Friday.
 
Maximum sustained winds have decreased to near 100 mph (155 km/h) 
with higher gusts. Additional weakening is forecast during the next
24 hours, followed by some restrengthening Thursday night and
Friday.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The estimated minimum central pressure is 976 mb (28.82 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Surf: Swells generated by Narda are affecting portions of the coast
of southwestern and west-central Mexico, and are expected to spread
to portions of Baja California Sur late this week through the
weekend. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local or
national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM MST.
 
$$
Forecaster Hagen
  