ZCZC MIATCPEP4 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Hurricane Narda Advisory Number  14
NWS National Hurricane Center Miami FL       EP142025
800 PM MST Wed Sep 24 2025
 
...NARDA WEAKENS SLIGHTLY DUE TO SHEAR BUT FORECAST TO RESTRENGTHEN
ON FRIDAY...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...15.1N 113.2W
ABOUT 580 MI...935 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Hurricane Narda was located 
near latitude 15.1 North, longitude 113.2 West. Narda is moving 
toward the west near 10 mph (17 km/h). A westward motion is expected 
to continue during the next day or so, followed by a gradual turn 
toward the west-northwest on Friday. A northwestward and then 
north-northeastward motion is forecast this weekend and into early 
next week.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher 
gusts. Only slight weakening is forecast during the next day or so, 
followed by some re-strengthening by Friday.
 
Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).
 
The estimated minimum central pressure is 978 mb (28.88 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Surf: Swells generated by Narda are affecting portions of the coast
of southwestern and west-central Mexico, and are expected to spread
to portions of Baja California Sur late this week through the
weekend. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local or
national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Gibbs (CPHC)
 
NNNN
  