145 
WTPZ34 KNHC 270233
TCPEP4
 
BULLETIN
Hurricane Narda Advisory Number  22
NWS National Hurricane Center Miami FL       EP142025
800 PM PDT Fri Sep 26 2025
 
...NARDA HOLDING STEADY WHILE CONTINUING WEST-NORTHWESTWARD...
 
 
SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...17.3N 123.6W
ABOUT 970 MI...1560 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Hurricane Narda was located 
near latitude 17.3 North, longitude 123.6 West. Narda is moving 
toward the west-northwest near 13 mph (20 km/h), and this general 
motion is expected to continue into early Saturday. A gradual turn 
toward the north with a decrease in forward speed is forecast over 
the weekend.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher 
gusts. Narda is expected to maintain its strength into early 
Saturday, followed by steady weakening over the weekend.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 979 mb (28.91 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Narda are affecting portions of the coast 
of west-central Mexico and portions of the Baja California 
peninsula. The swells should reach southern California over the 
weekend. These swells are likely to cause life-threatening surf and 
rip current conditions. Please consult products from your local or 
national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.
 
$$
Forecaster Gibbs (CPHC)
  