946 
WTPZ34 KNHC 270843
TCPEP4
 
BULLETIN
Hurricane Narda Advisory Number  23
NWS National Hurricane Center Miami FL       EP142025
200 AM PDT Sat Sep 27 2025
 
...NARDA HOLDING STEADY BUT GRADUAL WEAKENING EXPECTED TO BEGIN
LATER TODAY...
 
 
SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 124.7W
ABOUT 1025 MI...1650 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Hurricane Narda was located 
near latitude 17.6 North, longitude 124.7 West. Narda is moving 
toward the west-northwest near 12 mph (19 km/h). A gradual turn
toward the north with a decrease in forward speed is forecast later 
today through the rest of the weekend.
 
Maximum sustained winds are near 90 mph (150 km/h) with higher 
gusts. Gradual weakening is expected to begin later today, and Narda 
is forecast to weaken below hurricane strength by late Sunday.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 979 mb (28.91 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Narda are affecting portions of the coast
of west-central Mexico and portions of the Baja California
peninsula. The swells should reach southern California over the
weekend. These swells are likely to cause life-threatening surf and
rip current conditions. Please consult products from your local or
national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.
 
$$
Forecaster Gibbs (CPHC)
  