070 
WTPZ34 KNHC 271434
TCPEP4
 
BULLETIN
Hurricane Narda Advisory Number  24
NWS National Hurricane Center Miami FL       EP142025
800 AM PDT Sat Sep 27 2025
 
...NARDA EXPECTED TO BEGIN WEAKENING SOON...
 
 
SUMMARY OF 800 AM PDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...18.0N 124.9W
ABOUT 1025 MI...1655 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM PDT (1500 UTC), the center of Hurricane Narda was located
near latitude 18.0 North, longitude 124.9 West. Narda is moving
toward the west-northwest near 9 mph (15 km/h). A gradual turn
toward the north with a decrease in forward speed is forecast 
during the next day or so.
 
Maximum sustained winds remain near 90 mph (150 km/h) with higher
gusts. Gradual weakening is expected to begin later today, and Narda
is forecast to weaken below hurricane strength tonight or early 
Sunday.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 175 miles
(280 km).
 
The estimated minimum central pressure is 979 mb (28.91 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Narda are affecting portions of the coast
of west-central Mexico and portions of the Baja California
peninsula. The swells should reach southern California later today 
or tonight. These swells are likely to cause life-threatening surf 
and rip current conditions. Please consult products from your local 
or national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM PDT.
 
$$
Forecaster Cangialosi
  