000
WTPZ34 KNHC 272031
TCPEP4
 
BULLETIN
Hurricane Narda Advisory Number  25
NWS National Hurricane Center Miami FL       EP142025
200 PM PDT Sat Sep 27 2025
 
...NARDA BEGINS TO WEAKEN...
 
 
SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.2N 125.5W
ABOUT 1060 MI...1705 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Hurricane Narda was located
near latitude 18.2 North, longitude 125.5 West. Narda is moving
toward the west-northwest near 7 mph (11 km/h). A gradual turn
toward the north with a decrease in forward speed is forecast
during the next day or so.
 
Maximum sustained winds have decreased to near 80 mph (130 km/h)
with higher gusts.  Continued weakening is expected, and Narda is
forecast to become a tropical storm tonight and a post-tropical low
in a day or two.
 
Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).
 
The estimated minimum central pressure is 985 mb (29.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Narda are affecting portions of the coast
of west-central Mexico and the Baja California peninsula. The swells
should reach southern California tonight. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local or national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.
 
$$
Forecaster Cangialosi
  