000
WTPZ34 KNHC 280232
TCPEP4
 
BULLETIN
Tropical Storm Narda Advisory Number  26
NWS National Hurricane Center Miami FL       EP142025
800 PM PDT Sat Sep 27 2025
 
...NARDA STEADILY WEAKENING AS IT BEGINS TO TURN NORTHWARD...
 
 
SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...18.7N 125.9W
ABOUT 1070 MI...1725 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Narda was
located near latitude 18.7 North, longitude 125.9 West. Narda is
moving toward the north-northwest near 5 mph (7 km/h). A gradual 
turn toward the north is forecast by Sunday. 
 
Maximum sustained winds have decreased to near 70 mph (110 km/h) 
with higher gusts. Additional weakening is expected, and Narda is 
forecast to become a post-tropical low on Monday.
 
Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.
 
The estimated minimum central pressure is 991 mb (29.27 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Narda are affecting portions of the coast
of west-central Mexico and the Baja California peninsula. The swells
should reach southern California tonight. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local or national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.
 
$$
Forecaster Gibbs (CPHC)
  