000
WTPZ34 KNHC 281436
TCPEP4
 
BULLETIN
Tropical Storm Narda Advisory Number  28
NWS National Hurricane Center Miami FL       EP142025
800 AM PDT Sun Sep 28 2025
 
...NARDA CONTINUES WEAKENING OVER OPEN WATERS...
...LIKELY TO BECOME POST-TROPICAL LATER TODAY OR EARLY MONDAY...
 
 
SUMMARY OF 800 AM PDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...19.7N 125.5W
ABOUT 1025 MI...1655 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...N OR 5 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM PDT (1500 UTC), the center of Tropical Storm Narda was 
located near latitude 19.7 North, longitude 125.5 West. Narda is 
moving toward the north near 6 mph (9 km/h), and this general motion 
is expected to continue for the next couple of days.
 
Maximum sustained winds have decreased to near 50 mph (85 km/h)
with higher gusts. Continued weakening is expected, and Narda is
forecast to become a post-tropical low later today or early Monday.
 
Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Narda are affecting portions of the coast
of west-central Mexico, the Baja California peninsula, and southern
California. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
or national meteorological office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM PDT.
 
$$
Forecaster Reinhart
  