
ZCZC MIATCPEP1 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Estelle Advisory Number   5
NWS National Hurricane Center Miami FL       EP062022
1000 AM CDT Sat Jul 16 2022

...ESTELLE CONTINUES STRENGTHENING...
...EXPECTED TO BECOME A HURRICANE LATER TODAY...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.0N 103.7W
ABOUT 350 MI...560 KM S OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Estelle was
located near latitude 14.0 North, longitude 103.7 West. Estelle is
moving toward the west-northwest near 10 mph (17 km/h), and this
general motion is expected to continue for the next few days.

Maximum sustained winds have increased to near 70 mph (110 km/h) 
with higher gusts, and continued strengthening is expected during 
the next day or two. Estelle is likely to become a hurricane later 
today, and it is forecast to become a major hurricane by early 
Monday.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle are beginning to affect portions
of the southwestern coast of Mexico and will spread northward to the
coast of west-central Mexico and the southern Baja California
peninsula on Sunday and Monday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Reinhart

NNNN
