

000
WTPZ31 KNHC 162034
TCPEP1

BULLETIN
Tropical Storm Estelle Advisory Number   6
NWS National Hurricane Center Miami FL       EP062022
400 PM CDT Sat Jul 16 2022

...ESTELLE EXPECTED TO BECOME A HURRICANE SOON AND STRENGTHEN MORE 
INTO EARLY NEXT WEEK...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 104.4W
ABOUT 330 MI...535 KM S OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Estelle was 
located near latitude 14.2 North, longitude 104.4 West. Estelle is 
moving toward the west-northwest near 9 mph (15 km/h), and this 
general motion is expected to continue for the next few days.

Maximum sustained winds are near 70 mph (110 km/h) with higher 
gusts. Strengthening is forecast during the next day or two, and 
Estelle is expected to become a hurricane by this evening and could 
become a major hurricane by early Monday.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle are affecting portions of the
southwestern coast of Mexico and will spread northward to the coast
of west-central Mexico and the southern Baja California peninsula on
Sunday and Monday. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Reinhart

