

854 
WTPZ31 KNHC 170236
TCPEP1

BULLETIN
Hurricane Estelle Advisory Number   7
NWS National Hurricane Center Miami FL       EP062022
1000 PM CDT Sat Jul 16 2022

...ESTELLE INTENSIFIES RAPIDLY TO A HURRICANE...
...RAPID INTENSIFICATION FORECAST TO CONTINUE THROUGH SUNDAY...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.7N 105.0W
ABOUT 300 MI...485 KM S OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Hurricane Estelle was
located near latitude 14.7 North, longitude 105.0 West.  Estelle is
moving toward the west-northwest near 9 mph (15 km/h).  A
west-northwestward motion with some increase in forward speed is
expected through Tuesday.

Estelle is rapidly intensifying, and maximum sustained winds have
increased to near 80 mph (130 km/h) with higher gusts.  Continued
rapid intensification is likely through Sunday, and Estelle is
forecast to become a major hurricane by Sunday night.  Some 
weakening is expected to begin on Tuesday.

Hurricane-force winds extend outward up to 10 miles (20 km) from the
center, and tropical-storm-force winds extend outward up to 70 miles
(110 km).

The estimated minimum central pressure is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle are affecting portions of the
southwestern coast of Mexico and will spread northward to the coast
of west-central Mexico and the southern Baja California peninsula on
Sunday and Monday. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.

$$
Forecaster Berg


