

000
WTPZ31 KNHC 170831
TCPEP1

BULLETIN
Hurricane Estelle Advisory Number   8
NWS National Hurricane Center Miami FL       EP062022
400 AM CDT Sun Jul 17 2022

...ESTELLE EXPECTED TO STRENGTHEN DURING THE NEXT DAY OR SO...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.1N 105.9W
ABOUT 290 MI...465 KM SSW OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Hurricane Estelle was
located near latitude 15.1 North, longitude 105.9 West. Estelle is
moving toward the west-northwest near 9 mph (15 km/h) and this
motion with some increase in forward speed is expected during the 
next few days.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts. Steady to rapid strengthening is expected, and Estelle 
could become a major hurricane on Monday.

Hurricane-force winds extend outward up to 10 miles (20 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).

The estimated minimum central pressure is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle are affecting portions of the
southwestern coast of Mexico and will spread northward to the coast
of west-central Mexico and the southern Baja California peninsula
later today and Monday. These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Cangialosi

