

911 
WTPZ31 KNHC 181444
TCPEP1

BULLETIN
Hurricane Estelle Advisory Number  13
NWS National Hurricane Center Miami FL       EP062022
900 AM MDT Mon Jul 18 2022

...ESTELLE PASSING JUST SOUTH OF SOCORRO ISLAND...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...18.0N 111.1W
ABOUT 55 MI...90 KM S OF SOCORRO ISLAND
ABOUT 345 MI...560 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...986 MB...29.12 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Hurricane Estelle was
located near latitude 18.0 North, longitude 111.1 West. Estelle is
moving toward the west-northwest near 14 mph (22 km/h) and this
general motion is expected to continue for the next few days.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts.  Some slight strengthening is possible during the next day or
so, but weakening is expected to begin around the middle of the
week.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).  An automated Mexican Navy weather station on Socorro 
Island recently reported sustained winds of 46 mph (74 km/h) and 
gusts to 61 mph (98 km/h).

The estimated minimum central pressure is 986 mb (29.12 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle are affecting portions of the
coast of southwestern Mexico, west-central Mexico, and the southern
Baja California peninsula. These swells are likely to continue for
another day or so and could cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Pasch/Bucci


