

000
WTPZ31 KNHC 190233
TCPEP1

BULLETIN
Hurricane Estelle Advisory Number  15
NWS National Hurricane Center Miami FL       EP062022
900 PM MDT Mon Jul 18 2022

...ESTELLE BARELY A HURRICANE...
...NOW EXPECTED TO WEAKEN FURTHER...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...18.3N 113.6W
ABOUT 175 MI...280 KM W OF SOCORRO ISLAND
ABOUT 400 MI...640 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Hurricane Estelle was
located near latitude 18.3 North, longitude 113.6 West. Estelle is
moving toward the west-northwest near 14 mph (22 km/h) and this
motion is expected to continue for the next several days. 

Maximum sustained winds have decreased to near 75 mph (120 km/h) 
with higher gusts. Gradual weakening is forecast over the next day 
or two followed by more pronounced weakening, and Estelle is 
expected to become a post-tropical cyclone towards the end of 
the week.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle are affecting portions of the
coast of southwestern Mexico, west-central Mexico, and the southern
Baja California peninsula. These swells are likely to continue for
the next day or so and could cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Papin

