

000
WTPZ31 KNHC 191438
TCPEP1

BULLETIN
Tropical Storm Estelle Advisory Number  17
NWS National Hurricane Center Miami FL       EP062022
800 AM PDT Tue Jul 19 2022

...ESTELLE EXPECTED TO WEAKEN...


SUMMARY OF 800 AM PDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...19.0N 115.5W
ABOUT 450 MI...725 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM PDT (1500 UTC), the center of Tropical Storm Estelle was
located near latitude 19.0 North, longitude 115.5 West. Estelle is
moving toward the west-northwest near 12 mph (19 km/h) and this
general motion is expected to continue for the next couple of days.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Weakening is forecast and Estelle is likely to become a 
post-tropical cyclone by Thursday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Estelle will diminish along the coasts
of southwestern Mexico and the southern Baja California peninsula
today.


NEXT ADVISORY
-------------
Next complete advisory at 200 PM PDT.

$$
Forecaster Pasch/Bucci

