

000
WTPA32 PHFO 081431
TCPCP2

BULLETIN
Hurricane Dora Advisory Number  33
NWS Central Pacific Hurricane Center Honolulu HI   EP052023
500 AM HST Tue Aug 08 2023

...MAJOR HURRICANE DORA CONTINUES TO TRACK RAPIDLY WESTWARD FAR TO
THE SOUTH OF HAWAII...


SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...11.5N 156.1W
ABOUT 685 MI...1105 KM S OF HONOLULU HAWAII
ABOUT 965 MI...1555 KM ESE OF JOHNSTON ISLAND
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...953 MB...28.15 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests on Johnston Island should monitor the progress of Dora.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Dora was located
near latitude 11.5 North, longitude 156.1 West. Dora is moving
toward the west near 22 mph (35 km/h) and this motion is expected to
continue during the next couple days.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Dora is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Slight weakening is forecast during the next 
48 hours.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 105 miles
(165 km).

The estimated minimum central pressure is 953 mb (28.15 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Dora are expected to begin impacting
Johnston island late Wednesday, likely producing large and dangerous
waves through Thursday.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.

$$
Forecaster Jelsema

