

012 
WTPA32 PHFO 091432
TCPCP2

BULLETIN
Hurricane Dora Advisory Number  37
NWS Central Pacific Hurricane Center Honolulu HI   EP052023
500 AM HST Wed Aug 09 2023

...DORA TO PASS FAR SOUTH OF JOHNSTON ISLAND LATER TODAY...


SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...11.4N 164.0W
ABOUT 795 MI...1275 KM SSW OF HONOLULU HAWAII
ABOUT 520 MI...835 KM SE OF JOHNSTON ISLAND
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...953 MB...28.15 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests on Johnston Island should monitor the progress of Dora.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Dora was located
near latitude 11.4 North, longitude 164.0 West. Dora is moving
toward the west near 22 mph (35 km/h) and this motion is expected to
continue, with a gradual turn to the west-northwest over the
next day.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts. Dora is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Some gradual weakening is forecast during the 
next several days. 

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 953 mb (28.15 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Dora are expected to begin impacting
Johnston Island late today, likely producing large and
life-threatening surf through Thursday.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.

$$
Forecaster M Ballard/Jelsema


