

000
WTPA32 PHFO 100836
TCPCP2

BULLETIN
Hurricane Dora Advisory Number  40
NWS Central Pacific Hurricane Center Honolulu HI   EP052023
1100 PM HST Wed Aug 09 2023

...DORA MOVING WESTWARD AND WEAKENS SLIGHTLY...


SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...12.1N 169.8W
ABOUT 1010 MI...1625 KM SW OF HONOLULU HAWAII
ABOUT 320 MI...510 KM S OF JOHNSTON ISLAND
MAXIMUM SUSTAINED WINDS...140 MPH...220 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...950 MB...28.06 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests on Wake Island should monitor the progress of Dora.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Dora was located
near latitude 12.1 North, longitude 169.8 West. Dora is moving
toward the west near 22 mph (35 km/h) and this motion is expected to
gradually slow down and turn towards the west-northwest over the 
next several days.

Maximum sustained winds are near 140 mph (220 km/h) with higher
gusts. Dora is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Some weakening is forecast over the next few 
days.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 950 mb (28.06 inches).


HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Dora will produce large and
life-threatening surf on Johnston Island through Thursday.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.

$$
Forecaster Foster/Birchard

