
ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Post-Tropical Cyclone Idalia Advisory Number  21
NWS National Hurricane Center Miami FL       AL102023
500 PM EDT Thu Aug 31 2023

...IDALIA BECOMES POST-TROPICAL BUT NHC ADVISORIES WILL CONTINUE...
...TROPICAL STORM WATCH ISSUED FOR BERMUDA...


SUMMARY OF 500 PM EDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...33.5N 73.5W
ABOUT 165 MI...265 KM SE OF CAPE HATTERAS NORTH CAROLINA
ABOUT 510 MI...820 KM WNW OF BERMUDA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...E OR 90 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

All Tropical Storm Warnings and Storm Surge Watches have been
discontinued along the coast of North Carolina.

The Bermuda Weather Service has issued a Tropical Storm Watch for
Bermuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM EDT (2100 UTC), the center of Post-Tropical Cyclone Idalia 
was located near latitude 33.5 North, longitude 73.5 West.  Idalia 
is moving toward the east near 21 mph (33 km/h), and this motion is 
expected to continue through tonight.  A turn toward the 
east-southeast and east is expected on Friday and Saturday, 
accompanied by a considerable decrease in forward speed.  On the 
forecast track, the center of Idalia will continue moving away from 
the coast of North Carolina and approach Bermuda over the weekend.

Maximum sustained winds are near 65 mph (100 km/h) with higher 
gusts.  Gradual weakening is forecast through Friday night.  
Restrengthening is possible over the weekend, and Idalia is expected 
to transition back to a tropical storm by Saturday.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.  NOAA buoy 41002 well to the south of Cape 
Hatteras recently reported a sustained wind of 47 mph (76 km/h) and 
a gust to 61 mph (98 km/h).

The estimated minimum central pressure is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Idalia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

STORM SURGE:  Water levels remain elevated at the following 
heights above ground somewhere in the indicated areas but should 
subside overnight...

Beaufort Inlet, NC to Ocracoke Inlet, NC...1-3 ft
Neuse and Bay Rivers...1-3 ft
Pamlico and Pungo Rivers...1-3 ft
Ocracoke Inlet, NC to Duck, NC...1-3 ft

For information specific to your area, please see products issued by
your local National Weather Service forecast office.

WIND:  Gusts to tropical storm force are still possible along the
coast of North Carolina through tonight.

Tropical storm conditions are possible on Bermuda by Saturday.

RAINFALL:  Idalia is expected to produce rainfall amounts of 5 to 7 
inches (125 to 175 millimeters) across Bermuda through Sunday night. 
The heavy rainfall will likely lead to areas of flash and urban 
flooding on the island. 

SURF:  Swells generated by Idalia will affect the southeastern U.S.
coast during the next few days and will reach Bermuda on Friday.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM EDT.
Next complete advisory at 1100 PM EDT.

$$
Forecaster Berg

NNNN
