

000
WTNT35 KNHC 010243
TCPAT5

BULLETIN
Post-Tropical Cyclone Idalia Advisory Number  22
NWS National Hurricane Center Miami FL       AL102023
1100 PM EDT Thu Aug 31 2023

...IDALIA PULLING AWAY FROM NORTH CAROLINA...
...EXPECTED TO AFFECT BERMUDA THIS WEEKEND...


SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...33.1N 71.5W
ABOUT 270 MI...435 KM ESE OF CAPE HATTERAS NORTH CAROLINA
ABOUT 395 MI...635 KM W OF BERMUDA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...E OR 95 DEGREES AT 23 MPH...37 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Post-Tropical Cyclone 
Idalia was located near latitude 33.1 North, longitude 71.5 West. 
The post-tropical cyclone is moving toward the east near 23 mph (37 
km/h).  A turn toward the east-southeast and east is expected on 
Friday and Saturday, accompanied by a considerable decrease in 
forward speed.  On the forecast track, the center of Idalia will 
continue moving away from the coast of North Carolina and approach 
Bermuda over the weekend.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Gradual weakening is forecast through early Saturday.
Restrengthening is possible over the weekend, and Idalia is expected
to transition back to a tropical storm on Saturday.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 996 mb (29.42 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Idalia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

STORM SURGE:  Water levels are expected to recede overnight and 
into early Friday.  For information specific to your area, please 
see products issued by your local National Weather Service forecast 
office.

WIND:  Gusts to tropical storm force are expected to continue along
the coast of North Carolina through early Friday.

Tropical storm conditions are possible on Bermuda by Saturday.

RAINFALL:  Idalia is expected to produce rainfall amounts of 4 to 6 
inches, or 100 to 150 millimeters, across Bermuda through Sunday 
night. The heavy rainfall may cause areas of flash and urban 
flooding on the island.

SURF:  Swells generated by Idalia will affect the southeastern U.S.
coast during the next couple of days and will reach Bermuda on
Friday. These swells are likely to cause life-threatening surf and
rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.

$$
Forecaster Cangialosi

