

000
WTNT35 KNHC 010844
TCPAT5

BULLETIN
Post-Tropical Cyclone Idalia Advisory Number  23
NWS National Hurricane Center Miami FL       AL102023
500 AM AST Fri Sep 01 2023

...IDALIA TURNS EAST-SOUTHEASTWARD...
...EXPECTED TO AFFECT BERMUDA THIS WEEKEND...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...32.6N 69.8W
ABOUT 290 MI...470 KM W OF BERMUDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...ESE OR 110 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Post-Tropical Cyclone Idalia
was located near latitude 32.6 North, longitude 69.8 West. The
post-tropical cyclone is moving toward the east-southeast near 16
mph (26 km/h). An east-southeastward to eastward motion at a 
much slower forward speed is expected during the 24 hours.  An 
east-northeastward motion is expected to begin over the weekend.  On
the forecast track, Idalia will approach Bermuda over the weekend.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Gradual weakening is forecast through early Saturday. 
Restrengthening is possible over the weekend, and Idalia is expected
to transition back to a tropical storm on Saturday.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 998 mb (29.47 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Idalia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are possible on Bermuda by 
Saturday.

RAINFALL:  Idalia is expected to produce rainfall amounts of 3 to 5 
inches, or 75 to 125 millimeters, across Bermuda through Sunday 
night. The heavy rainfall will likely cause areas of flash and urban 
flooding on the island.

SURF:  Swells generated by Idalia will affect the southeastern U.S.
coast during the next couple of days and will reach Bermuda today.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.

$$
Forecaster Brown

