

000
WTNT35 KNHC 011437
TCPAT5

BULLETIN
Post-Tropical Cyclone Idalia Advisory Number  24
NWS National Hurricane Center Miami FL       AL102023
1100 AM AST Fri Sep 01 2023

...IDALIA MOVING TOWARD THE EAST-SOUTHEAST OVER THE WESTERN
ATLANTIC...
...TROPICAL STORM WARNING ISSUED FOR BERMUDA...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...31.9N 67.9W
ABOUT 185 MI...295 KM W OF BERMUDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...ESE OR 110 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Bermuda Weather Service has upgraded to the Tropical Storm
Watch for Bermuda to a Tropical Storm Warning.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Post-Tropical Cyclone
Idalia was located near latitude 31.9 North, longitude 67.9 West.
Idalia is moving toward the east-southeast near 17 mph (28 km/h), 
and this general trajectory at a slower forward speed is expected 
through Saturday.  A turn toward the east and then northeast is 
forecast late Saturday and Sunday.  On the forecast track, the 
center of Idalia will move near or to the south of Bermuda on 
Saturday.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Gradual weakening is forecast through early Saturday.
Restrengthening is possible over the weekend, and Idalia is expected
to transition back to a tropical storm on Saturday.

Tropical-storm-force winds extend outward up to 240 miles (390 km)
from the center.

The estimated minimum central pressure is 998 mb (29.47 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Idalia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected on Bermuda by
Saturday.

RAINFALL:  Idalia is expected to produce rainfall amounts of 3 to 5
inches, or 75 to 125 millimeters, across Bermuda through Sunday
night. The heavy rainfall will likely cause areas of flash and urban
flooding on the island.

SURF:  Swells generated by Idalia will affect the southeastern U.S.
coast and Bermuda during the next couple of days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Berg

