

000
WTNT35 KNHC 012035
TCPAT5

BULLETIN
Post-Tropical Cyclone Idalia Advisory Number  25
NWS National Hurricane Center Miami FL       AL102023
500 PM AST Fri Sep 01 2023

...HEAVY RAINS AND STRONG WINDS EXPECTED ON BERMUDA THIS WEEKEND...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...32.0N 66.5W
ABOUT 100 MI...165 KM W OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...ESE OR 105 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Post-Tropical Cyclone Idalia
was located near latitude 32.0 North, longitude 66.5 West.  Idalia 
is moving toward the east-southeast near 15 mph (24 km/h), and this
general trajectory at a slower forward speed is expected through 
early Saturday.  A turn toward the east and then northeast is 
forecast over the weekend.  On the forecast track, the center of
Idalia will move near or to the south of Bermuda on Saturday.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Additional weakening is forecast through early Saturday.
Little change in strength is expected during the next few days. 
Idalia could transition to a tropical or subtropical storm on 
Saturday.

Tropical-storm-force winds extend outward up to 240 miles (390 km)
from the center.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Idalia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected on Bermuda by
Saturday.

RAINFALL:  Idalia is expected to produce rainfall amounts of 3 to 5 
inches, or 75 to 125 millimeters, across Bermuda through the 
weekend.  The heavy rainfall will likely cause areas of flash and 
urban flooding on the island.

SURF:  Swells generated by Idalia will affect the southeastern U.S.
coast and Bermuda during the next couple of days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Berg

