

000
WTNT35 KNHC 020847
TCPAT5

BULLETIN
Post-Tropical Cyclone Idalia Advisory Number  27
NWS National Hurricane Center Miami FL       AL102023
500 AM AST Sat Sep 02 2023

...TROPICAL STORM FORCE WINDS OCCURRING ON BERMUDA...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...31.7N 64.6W
ABOUT 45 MI...70 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...E OR 90 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Post-Tropical Cyclone Idalia
was located near latitude 31.7 North, longitude 64.6 West. The
post-tropical cyclone is moving toward the east near 6 mph (9 km/h), 
and this general motion is expected today.  A faster northeastward 
motion is forecast to begin on Sunday, and this motion should 
continue into Monday.  On the forecast track, Idalia will remain 
near Bermuda today, and then begin to move away from the island  
tonight and Sunday.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Little change in strength is forecast during the next few days. 
Idalia could transition to a subtropical storm later today.

Tropical-storm-force winds extend outward up to 220 miles (350 km)
from the center.  A wind gust to 49 mph (80 km/h) was recently 
reported at the LF Wade International Airport on Bermuda. An 
elevated observing site at the National Museum of Bermuda recently 
reported sustained winds of 55 mph (89 km/h) with a gust to 69 
mph (111 km/h). 

The estimated minimum central pressure is 999 mb (29.50 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Idalia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected on Bermuda through
early Sunday.

RAINFALL:  Idalia is expected to produce rainfall amounts of 1 to 3 
inches, or 25 to 75 millimeters, across Bermuda through the weekend. 
The heavy rainfall may cause areas of flash and urban flooding on 
the island.

SURF:  Swells generated by Idalia will affect the southeastern U.S.
coast and Bermuda during the next couple of days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.

$$
Forecaster Brown

