998 
WTPZ34 KNHC 070239
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number   2
NWS National Hurricane Center Miami FL       EP092025
900 PM CST Wed Aug 06 2025
 
...IVO BRINGING LOCALLY HEAVY RAINS TO PORTIONS OF THE COAST OF
SOUTHWESTERN MEXICO...
 
 
SUMMARY OF 900 PM CST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...15.0N 100.9W
ABOUT 145 MI...235 KM SSW OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
Interests along the coast of southwestern Mexico should monitor the
progress of Ivo.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 PM CST (0300 UTC), the center of Tropical Storm Ivo was
located near latitude 15.0 North, longitude 100.9 West. Ivo is
moving toward the west-northwest near 22 mph (35 km/h).  The system 
is forecast to move generally parallel to, but offshore of, the 
coast of Mexico during the next day or two and move away from 
Mexico thereafter.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Strengthening is forecast, and Ivo is expected to be near hurricane 
strength by the end of the week.
 
Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.
 
The estimated minimum central pressure is 1008 mb (29.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Tropical Storm Ivo is expected to produce storm total
rainfall of 2 to 4 inches, with isolated maximum totals of 6 inches,
across portions of the Mexican states of Guerrero, Michoacan and
southwestern Oaxaca through Saturday. This rainfall could lead to
flash flooding.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Ivo, please see the National Weather Service
Storm Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
SURF:  Swells generated by Ivo will be affecting the southwestern
coast of Mexico during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at:
hurricanes.gov/graphics_at[X].shtml?ripCurrnets
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 AM CST.
 
$$
Forecaster Pasch
  