000
WTPZ34 KNHC 071455
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number   4
NWS National Hurricane Center Miami FL       EP092025
900 AM CST Thu Aug 07 2025
 
...TINY IVO CONTINUES MOVING QUICKLY WEST-NORTHWESTWARD...
 
 
SUMMARY OF 900 AM CST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...17.8N 104.4W
ABOUT 305 MI...490 KM WNW OF ACAPULCO MEXICO
ABOUT 500 MI...805 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 24 MPH...39 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES
 
 
WATCHES AND WARNINGS
--------------------
Interests along the coast of southwestern Mexico should continue to
monitor the progress of Ivo.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 900 AM CST (1500 UTC), the center of Tropical Storm Ivo was 
located near latitude 17.8 North, longitude 104.4 West. Ivo is 
moving quickly toward the west-northwest near 24 mph (39 km/h). The 
system is forecast to move generally parallel to, but offshore of, 
the coast of Mexico during the next day or so and turn westward away 
from Mexico thereafter.
 
Maximum sustained winds have increased to near 45 mph (75 km/h) with
higher gusts. Strengthening is forecast, and Ivo is expected to be
near hurricane strength by the end of the week.
 
Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.
 
The estimated minimum central pressure is 1006 mb (29.71 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Tropical Storm Ivo is expected to produce storm total
rainfall of 2 to 4 inches, with isolated maximum totals of 6 inches,
across portions of the Mexican states of Guerrero, Michoacan de
Ocampo and Colima through Friday. This would result in an elevated
risk for flash flooding.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Ivo please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
SURF:  Swells generated by Ivo will be affecting the southwestern
coast of Mexico during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep4.shtml?ripCurrnets
 
 
NEXT ADVISORY
-------------
Next complete advisory at 300 PM CST.
 
$$
Forecaster Papin
  