000
WTPZ34 KNHC 072053
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number   5
NWS National Hurricane Center Miami FL       EP092025
300 PM CST Thu Aug 07 2025
 
...IVO INTENSIFYING AS IT MAKES ITS CLOSEST APPROACH TO MEXICO...
 
 
SUMMARY OF 300 PM CST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.8N 105.8W
ABOUT 410 MI...660 KM WNW OF ACAPULCO MEXICO
ABOUT 385 MI...625 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
Interests along the coast of southwestern Mexico should continue to
monitor the progress of Ivo.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 300 PM CST (2100 UTC), the center of Tropical Storm Ivo was 
located near latitude 18.8 North, longitude 105.8 West. Ivo is 
moving toward the northwest near 21 mph (33 km/h). On the forecast 
track, Ivo is expected to start moving away from the coast of Mexico 
over the next day or so. The storm is forecast to turn more westward 
by the weekend. 
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts. 
Strengthening is forecast for the next day or so, and Ivo could 
become a hurricane on Friday. 
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Tropical Storm Ivo is expected to produce storm total
rainfall of 2 to 4 inches, with isolated maximum totals of 6 inches,
across portions of the Mexican states of Guerrero, Michoacan de
Ocampo and Colima through Friday. This would result in an elevated
risk for flash flooding.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Ivo please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
SURF:  Swells generated by Ivo will be affecting the southwestern
coast of Mexico during the next couple of days. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep4.shtml?ripCurrnets
 
 
NEXT ADVISORY
-------------
Next complete advisory at 900 PM CST.
 
$$
Forecaster Papin
  