048 
WTPZ34 KNHC 080250
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number   6
NWS National Hurricane Center Miami FL       EP092025
800 PM MST Thu Aug 07 2025
 
...IVO FORECAST TO STRENGTHEN AS IT PULLS AWAY FROM MEXICO...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...19.7N 107.3W
ABOUT 275 MI...445 KM SE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 22 MPH...35 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
Interests along the coast of southwestern Mexico and the southern 
portion of the Baja California peninsula should continue to monitor 
the progress of Ivo.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Tropical Storm Ivo was
located near latitude 19.7 North, longitude 107.3 West. Ivo is
moving toward the northwest near 22 mph (35 km/h). A decrease in 
forward speed and a turn to the west-northwest are expected during 
the next few days. On the forecast track, Ivo is expected to pull 
away from mainland Mexico and pass well south of the Baja 
California peninsula.
 
Maximum sustained winds remain near 60 mph (95 km/h) with higher 
gusts. Strengthening is forecast for the next day or so, and Ivo 
could become a hurricane on Friday. Weakening should begin over the 
weekend.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
RAINFALL: Tropical Storm Ivo is expected to produce additional 
rainfall of 1 to 2 inches across coastal portions of the Mexican 
states of Michoacán de Ocampo, Colima, and Jalisco through tonight. 
The additional rainfall may result in localized flash flooding.
 
For a complete depiction of forecast rainfall associated with
Tropical Storm Ivo please see the National Weather Service Storm
Total Rainfall Graphic available at
hurricanes.gov/graphics_ep4.shtml?rainqpf
 
SURF:  Swells generated by Ivo will continue to affect the 
southwestern coast of Mexico during the next day or so, and are 
forecast to reach the southern portion of the Baja California 
peninsula on Friday. These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep4.shtml?ripCurrnets
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Cangialosi
  