000
WTPZ34 KNHC 081435
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number   8
NWS National Hurricane Center Miami FL       EP092025
800 AM MST Fri Aug 08 2025
 
...IVO PASSING SOUTH OF THE BAJA CALIFORNIA PENINSULA...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...20.7N 110.1W
ABOUT 150 MI...245 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
Interests in the southern portion of the Baja California peninsula 
should continue to monitor the progress of Ivo.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Tropical Storm Ivo was
located near latitude 20.7 North, longitude 110.1 West.  Ivo is
moving toward the west-northwest near 16 mph (26 km/h).  A westward 
to west-northwestward motion at a slower speed is forecast during 
the next several days.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Some strengthening is possible through tonight, but weakening is 
likely to begin on Saturday and continue into early next week.  Ivo 
could become post-tropical by late Sunday.
 
Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Ivo will continue to affect the
southwestern coast of Mexico during the next day or so, and are
beginning to reach the southern portion of the Baja California
peninsula. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep4.shtml?ripCurrnets
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Berg
  