118 
WTPZ34 KNHC 090232
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number  10
NWS National Hurricane Center Miami FL       EP092025
800 PM MST Fri Aug 08 2025
 
...IVO MOVING WESTWARD WELL OFFSHORE OF BAJA CALIFORNIA...
 
 
SUMMARY OF 800 PM MST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...20.5N 112.1W
ABOUT 220 MI...350 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...999 MB...29.50 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM MST (0300 UTC), the center of Tropical Storm Ivo was
located near latitude 20.5 North, longitude 112.1 West. Ivo is
moving toward the west near 12 mph (19 km/h). A westward to
west-northwestward motion is expected during the next few days.
 
Maximum sustained winds remain near 65 mph (100 km/h) with higher
gusts.  Little change in strength is expected through early 
Saturday, followed by a gradual weakening trend. Ivo is
forecast to become post-tropical by Sunday night.
 
Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.
 
The estimated minimum central pressure is 999 mb (29.50 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Ivo will continue to affect the southern
portion of the Baja California peninsula during the next day or so.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM MST.
 
$$
Forecaster Cangialosi
  