219 
WTPZ34 KNHC 090839
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number  11
NWS National Hurricane Center Miami FL       EP092025
200 AM MST Sat Aug 09 2025
 
...IVO HEADING WESTWARD...
 
 
SUMMARY OF 200 AM MST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...20.6N 112.4W
ABOUT 225 MI...365 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM MST (0900 UTC), the center of Tropical Storm Ivo was
located near latitude 20.6 North, longitude 112.4 West. Ivo is
moving toward the west near 9 mph (15 km/h).  A westward to
west-northwestward motion is expected during the next few days.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Gradual weakening is forecast for the next few days and Ivo is 
expected to become post-tropical by Sunday night.
 
Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Ivo will continue to affect the southern
portion of the Baja California peninsula during the next day or so.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM MST.
 
$$
Forecaster Bucci
  