000
WTPZ34 KNHC 091439
TCPEP4
 
BULLETIN
Tropical Storm Ivo Advisory Number  12
NWS National Hurricane Center Miami FL       EP092025
800 AM MST Sat Aug 09 2025
 
...IVO FORECAST TO WEAKEN OVER COLDER WATERS...
 
 
SUMMARY OF 800 AM MST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...21.0N 112.7W
ABOUT 220 MI...360 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM MST (1500 UTC), the center of Tropical Storm Ivo was
located near latitude 21.0 North, longitude 112.7 West.  Ivo is
moving toward the west-northwest near 6 mph (9 km/h).  A faster
motion toward the west-northwest and then west is expected during
the next few days.
 
Maximum sustained winds are near 60 mph (95 km/h) with higher gusts.
Weakening is forecast during the next few days, and Ivo is likely
to become post-tropical by late Sunday.
 
Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.
 
The estimated minimum central pressure is 1001 mb (29.56 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Ivo will continue to affect the southern
portion of the Baja California peninsula during the next day or so.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM MST.
 
$$
Forecaster Berg
  