

000
WTNT34 KWNH 280856
TCPAT4

BULLETIN
Post-Tropical Cyclone Helene Advisory Number  20
NWS Weather Prediction Center College Park MD   AL092024
400 AM CDT Sat Sep 28 2024

...CATASTROPHIC, HISTORIC FLOODING CONTINUES OVER PORTIONS OF THE
SOUTHERN APPALACHIANS, THOUGH THE RISK FOR ADDITIONAL HEAVY
RAINFALL CONTINUES TO WANE...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...37.3N 87.9W
ABOUT 135 MI...220 KM WSW OF LOUISVILLE KENTUCKY
MAXIMUM SUSTAINED WINDS...25 MPH...35 KM/H
PRESENT MOVEMENT...SE OR 140 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Several flood warning and advisories, along with flash flood
warnings, remain in effect across portions of the southern and 
central Appalachians, the Southeast, and the Ohio Valley through 
Saturday morning.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Post-Tropical Cyclone Helene
was located near latitude 37.3 North, longitude 87.9 West. The
post-tropical cyclone is moving toward the southeast near 3 mph (6
km/h), and will drift slowly southeast and eventually eastward 
along the Kentucky-Tennessee border through the weekend. 

Maximum sustained winds are near 25 mph (35 km/h) with higher gusts.
Continued weakening is expected during the next couple of days.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key Messages for Helene can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC
and on the web at hurricanes.gov/text/MIATCDAT4.shtml

RAINFALL: The remnant low of post tropical cyclone Helene is
expected to produce an additional 1-2 inches of rainfall across
portions of the Ohio Valley through early Sunday, with some isolated
3 inch totals possible.  Most of the rainfall across the central and
southern Appalachians has come to an end, although a few lingering
showers are possible through Saturday.

For a complete depiction of forecast rainfall associated with
Tropical Storm Helene, please see the National Weather Service Storm
Total Rainfall Graphic, available at
hurricanes.gov/graphics_at4.shtml?rainqpf and the Flash Flood Risk
graphic at hurricanes.gov/graphics_at4.shtml?ero.

For a list of rainfall observations (and wind reports) associated
this storm, see the companion storm summary at WBCSCCNS4 with the
WMO header ACUS44 KWBC or at the following link:
www.wpc.ncep.noaa.gov/discussions/nfdscc4.html.

SURF: Swells generated by Helene will affect much the Atlantic
Seaboard from Florida to Long Island NY through Saturday. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Hurley

