

000
WTPZ32 KNHC 051732
TCPEP2

BULLETIN
Tropical Storm Kay Intermediate Advisory Number 5A
NWS National Hurricane Center Miami FL       EP122022
1200 PM MDT Mon Sep 05 2022

...KAY STRENGTHENING JUST OFF THE COAST OF SOUTHWESTERN MEXICO...
...AIR FORCE HURRICANE HUNTERS ENROUTE...


SUMMARY OF 1200 PM MDT...1800 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.5N 106.8W
ABOUT 295 MI...470 KM SW OF MANZANILLO MEXICO
ABOUT 535 MI...865 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.32 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Loreto southward to Cabo San Lucas
* Cabo San Lucas northward to Puerto San Andresito

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests north of the watch area in Baja California should closely
monitor the progress of Kay as Hurricane or Tropical Storm Watches
could be required tonight or on Tuesday.

For storm information specific to your area, please monitor
products issued by your local weather office.


DISCUSSION AND OUTLOOK
----------------------
At 1200 PM MDT (1800 UTC), the center of Tropical Storm Kay was
located near latitude 15.5 North, longitude 106.8 West. Kay is
moving toward the west near 15 mph (24 km/h). A turn to the
west-northwest is expected tonight, followed by a northwest to
north-northwest motion by late Tuesday. On the forecast track, the
center of Kay is expected to remain south and southwest of
southwestern Mexico through tonight, then move toward the southern
Baja California peninsula on Wednesday.

Maximum sustained winds have increased to near 65 mph (100 km/h) 
with higher gusts.  Additional strengthening is expected, and Kay 
is forecast to become a hurricane tonight or on Tuesday. Continued 
strengthening is forecast through midweek.

Tropical-storm-force winds extend outward up to 205 miles (335 km)
from the center.

The estimated minimum central pressure is 993 mb (29.32 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Tropical-storm-force wind gusts in outer rainbands are
likely near the coast of southwestern Mexico during the next day or
so.  Tropical storm conditions are possible in the watch area in
the southern Baja California peninsula by early Wednesday.

SURF:  Swells generated by Kay will affect portions of the coast of
southwestern Mexico during the next few days. Large swells are
likely to reach the southern portion of the Baja California
peninsula on Tuesday and are expected to spread up the peninsula
and the Gulf of California later this week. These swells will
likely cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.

RAINFALL:  Kay is expected to produce 3 to 6 inches of rainfall,
with isolated storm total amounts of 10 inches, across portions of
the Mexican Riviera and western Mexico through Wednesday night.
These rainfall amounts could lead to flash flooding, including
landslides.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Cangialosi

