

956 
WTPZ32 KNHC 052058
TCPEP2

BULLETIN
Hurricane Kay Advisory Number   6
NWS National Hurricane Center Miami FL       EP122022
300 PM MDT Mon Sep 05 2022

...KAY STRENGTHENS INTO A HURRICANE...
...OUTER RAIN BANDS CONTINUE TO AFFECT SOUTHWESTERN MEXICO...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...15.6N 107.3W
ABOUT 305 MI...495 KM SW OF MANZANILLO MEXICO
ABOUT 530 MI...855 KM SSE OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...981 MB...28.97 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Loreto southward to Cabo San Lucas
* Cabo San Lucas northward to Puerto San Andresito

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests north of the watch area in Baja California should closely
monitor the progress of Kay as hurricane or tropical storm watches
could be required tonight or on Tuesday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Hurricane Kay was
located near latitude 15.6 North, longitude 107.3 West. Kay is
moving toward the west near 12 mph (19 km/h).  A turn to the
west-northwest is expected tonight, followed by a northwest to
north-northwest motion by late Tuesday. On the forecast track, the
center of Kay is expected to remain south and southwest of
southwestern Mexico through tonight, then move to the west of the
southern Baja California peninsula on Wednesday.

Maximum sustained winds have increased to near 80 mph (130 km/h)
with higher gusts.  Continued strengthening is forecast through 
midweek.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 175 miles
(280 km).

The minimum central pressure very recently reported by the Air 
Force Hurricane Hunters is 981 mb (28.97 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Tropical-storm-force wind gusts in outer rainbands are
likely near the coast of southwestern Mexico during the next day or
so.  Tropical storm conditions are possible in the watch area in
the southern Baja California peninsula by early Wednesday.

SURF:  Swells generated by Kay will affect portions of the coast of
southwestern Mexico during the next few days. Large swells are
likely to reach the southern portion of the Baja California
peninsula on Tuesday and are expected to spread up the peninsula
and the Gulf of California later this week. These swells will
likely cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.

RAINFALL:  Kay is expected to produce 3 to 6 inches of rainfall,
with isolated storm total amounts of 10 inches, across portions of
the Mexican Riviera and western Mexico through Wednesday night.
These rainfall amounts could lead to flash flooding, including
landslides.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM MDT.
Next complete advisory at 900 PM MDT.

$$
Forecaster Cangialosi


