

000
WTPZ32 KNHC 060538
TCPEP2

BULLETIN
Hurricane Kay Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP122022
1200 AM MDT Tue Sep 06 2022

...KAY EXPECTED TO STRENGTHEN...
...OUTER RAIN BANDS, GUSTY WINDS, AND ROUGH SURF CONTINUE TO AFFECT
SOUTHWESTERN MEXICO...


SUMMARY OF 1200 AM MDT...0600 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.6N 108.7W
ABOUT 335 MI...535 KM WSW OF MANZANILLO MEXICO
ABOUT 440 MI...710 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 295 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...980 MB...28.94 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Loreto southward to Cabo San Lucas
* Cabo San Lucas northward to Punta Abreojos

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests north of the watch area on the Baja California peninsula 
should closely monitor the progress of Kay as hurricane or tropical 
storm watches could be required later today.  Tropical storm 
warnings could also be required for portions of the watch area 
later today.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1200 AM MDT (0600 UTC), the center of Hurricane Kay was located
near latitude 16.6 North, longitude 108.7 West. Kay is moving toward
the west-northwest near 10 mph (17 km/h). A turn toward the
northwest is expected later this morning, followed by a 
north-northwestward motion tonight through Thursday. On the 
forecast track, the center of Kay is expected to remain southwest 
and west of southwestern Mexico today, then move to the west of the
southern Baja California peninsula on Wednesday and Thursday.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts. Strengthening is forecast during the next couple of days, and
Kay is expected to be a strong hurricane when it passes near the
Baja California peninsula during the middle of the week.

Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 175
miles (280 km).

The estimated minimum central pressure is 980 mb (28.94 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Tropical-storm-force wind gusts in outer rainbands are likely
near the coast of southwestern Mexico today. Tropical storm 
conditions are possible in the watch area in the southern Baja
California peninsula by Wednesday morning.

SURF:  Swells generated by Kay will affect portions of the coast of 
southwestern Mexico during the next few days. Large swells are 
likely to reach the southern portion of the Baja California
peninsula later this morning and are expected to spread northward 
and into the Gulf of California through midweek. These swells will 
likely cause life-threatening surf and rip current conditions. 
Please consult products from your local weather office.

RAINFALL:  Kay is expected to produce 3 to 6 inches of rainfall,
with isolated storm total amounts of 10 inches, across portions of
the Mexican Riviera and western Mexico through Wednesday night.
These rainfall amounts could lead to flash flooding, including
landslides.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Brown

