

000
WTPZ32 KNHC 061131
TCPEP2

BULLETIN
Hurricane Kay Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       EP122022
600 AM MDT Tue Sep 06 2022

...TROPICAL STORM CONDITIONS AND AREAS OF HEAVY RAIN EXPECTED TO 
BEGIN ACROSS SOUTHERN BAJA CALIFORNIA PENINSULA BY WEDNESDAY 
MORNING...


SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...17.6N 109.6W
ABOUT 360 MI...580 KM WSW OF MANZANILLO MEXICO
ABOUT 365 MI...590 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...977 MB...28.85 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* San Evaristo southward to Cabo San Lucas
* Cabo San Lucas northward to Cabo San Lazaro

A Tropical Storm Watch is in effect for...
* North of San Evaristo northward to Loreto
* North of Cabo San Lazaro northward to Punta Abreojos

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests north of the watch area on the Baja California peninsula
should closely monitor the progress of Kay as hurricane or tropical
storm watches could be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the center of Hurricane Kay was located
near latitude 17.6 North, longitude 109.6 West. Kay is moving toward
the northwest near 13 mph (20 km/h), and this general motion should
continue through tonight.  A turn toward the north-northwest is
expected on Wednesday, and this motion should continue into
Thursday.  On the forecast track, the center of Kay is expected 
move to the west of the southern Baja California peninsula on 
Wednesday, and approach the west-central coast of the Baja 
California peninsula Wednesday night and Thursday.

Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts. Strengthening is forecast during the next 36 hours, and Kay 
could become a major hurricane during that time. Weakening is 
forecast to begin by Thursday, but Kay is forecast to remain a 
strong hurricane when it passes near the Baja California peninsula.

Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 175
miles (280 km).

The estimated minimum central pressure is 977 mb (28.85 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Tropical-storm-force wind gusts in outer rainbands are likely 
to continue along the coast of southwestern Mexico today. Tropical 
storm conditions are expected within the warning area in the 
southern Baja California peninsula beginning Wednesday morning. 
Tropical storm conditions are possible in the watch area in the 
southern Baja California peninsula by late Wednesday.

SURF:  Swells generated by Kay will continue to affect portions of 
the coast of southwestern Mexico during the next couple of days. 
Large swells are beginning to reach the southern portion of the 
Baja California peninsula and are expected to spread northward and 
into the Gulf of California during the next few days. These swells 
will likely cause life-threatening surf and rip current conditions. 
Please consult products from your local weather office.

RAINFALL:  Kay is expected to produce 4 to 8 inches of rainfall,
with isolated storm total amounts of 12 inches, across portions of
western Mexico, including the Baja California peninsula, through
Thursday night.  These rainfall amounts could lead to flash
flooding, including landslides.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Cangialosi

