

372 
WTPZ32 KNHC 071143
TCPEP2

BULLETIN
Hurricane Kay Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       EP122022
600 AM MDT Wed Sep 07 2022

...OUTER RAIN BANDS OF KAY BEGINNING TO REACH THE SOUTHERN BAJA 
CALIFORNIA PENINSULA...
...HURRICANE CONDITIONS EXPECTED ACROSS WEST-CENTRAL BAJA ON 
THURSDAY...


SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...20.6N 112.3W
ABOUT 220 MI...355 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...975 MB...28.80 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* North of Punta Abreojos to San Jose De Las Palomas

A Hurricane Watch is in effect for...
* Puerto Cortes to Punta Abreojos

A Tropical Storm Warning is in effect for...
* Punta Abreojos southward to Cabo San Lucas
* Cabo San Lucas northward to Bahia De Los Angeles

A Tropical Storm Watch is in effect for...
* North of Bahia De Los Angeles to San Felipe
* North of San Jose De Las Palomas to Cabo San Quintin

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 36 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests north of the watch area on the Baja California peninsula
and along the northwestern coast of mainland Mexico should closely
monitor the progress of Kay as additional tropical storm watches
could be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the eye of Hurricane Kay was located
near latitude 20.6 North, longitude 112.3 West. Kay is moving toward
the north-northwest near 12 mph (19 km/h), and this motion should
continue into Friday.  On the forecast track, the center of Kay is
expected to pass to the west of the southern Baja California
peninsula today, and be near the west-central coast of the Baja
California peninsula Thursday and Friday.

Maximum sustained winds are near 100 mph (155 km/h) with higher 
gusts. Some strengthening is forecast today. Although weakening is 
forecast to begin by Thursday, Kay is expected to remain a large
hurricane when it passes near the west-central coast of the Baja 
California peninsula.

Hurricane-force winds extend outward up to 30 miles (45 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure is 975 mb (28.80 inches).

HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Hurricane conditions are expected within the Hurricane Warning
area beginning on Thursday, and are possible within the Hurricane
Watch area Thursday.  Tropical storm conditions are expected in the
Tropical Storm Warning area beginning later this morning and are 
forecast to spread northward through Thursday.  Tropical storm 
conditions are possible in the Tropical Storm Watch areas Thursday 
night.

STORM SURGE: A storm surge could produce coastal flooding near
where the center passes the coast in areas of onshore winds, or
east of the center if Kay makes landfall. The surge will be
accompanied by large and destructive waves.

RAINFALL:  Kay is expected to produce rainfall totals of...

Baja California Peninsula: 6 to 10 inches, isolated maxima of 15
inches
Northwest Mainland Mexico: 2 to 4 inches, isolated maxima of 6
inches
Southernmost California: 2 to 4 inches with maxima of 6 inches
through Saturday morning

These rainfall amounts could lead to flash flooding, including
landslides across mountainous areas of Mexico.

SURF:  Swells generated by Kay will continue to affect portions of
the coast of southwestern Mexico during the next day or so. Large
swells are expected to spread northward along the Baja California
peninsula coast and into the Gulf of California during the next few
days. These swells will likely cause life-threatening surf and rip
current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Cangialosi


