

000
WTPZ32 KNHC 081154
TCPEP2

BULLETIN
Hurricane Kay Intermediate Advisory Number 16A
NWS National Hurricane Center Miami FL       EP122022
600 AM MDT Thu Sep 08 2022

...KAY CONTINUING ITS APPROACH TO BAJA CALIFORNIA...
...EXPECTED TO BRING HURRICANE CONDITIONS TO PORTIONS OF THE
WEST COAST OF THE BAJA CALIFORNIA PENINSULA LATER TODAY...


SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...25.1N 113.5W
ABOUT 85 MI...135 KM W OF CABO SAN LAZARO MEXICO
ABOUT 210 MI...340 KM SSE OF PUNTA EUGENIA MEXICO
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...974 MB...28.77 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* North of Punta Abreojos to San Jose De Las Palomas

A Hurricane Watch is in effect for...
* Puerto Cortes to Punta Abreojos

A Tropical Storm Warning is in effect for...
* Punta Abreojos southward to Cabo San Lucas
* San Jose De Las Palomas to the U.S./Mexico border
* Cabo San Lucas northward along the entire east coast of the Baja
California peninsula and then southward to Guaymas in mainland
Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 12 to 18 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in southern California should monitor the progress of Kay
and consult products from your local weather office.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the center of Hurricane Kay was located
near latitude 25.1 North, longitude 113.5 West. Kay is moving toward
the north-northwest near 14 mph (22 km/h), and this general motion
should continue into midday Friday.  A slower northwestward to
west-northwestward motion is forecast to begin by late Friday and
continue into Saturday.  On the forecast track, the center of Kay is
expected move near or over the west-central coast of the Baja
California peninsula later today and tonight, and near the northwest
coast of the Baja California peninsula on Friday.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Weakening is expected during the next couple of days.
However, Kay is expected to remain a large hurricane when it passes
near the west-central coast of the Baja California peninsula today.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).  A Mexican automated station at Puerto Cortes 
recently reported sustained winds of 50 mph (81 km/h) and a wind 
gust of 68 mph (109 km/h).

The estimated minimum central pressure is 974 mb (28.77 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Hurricane Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Hurricane conditions are expected within the Hurricane Warning
area beginning by late this morning, and are possible within the
Hurricane Watch area today.  Tropical storm conditions are occurring
over the Tropical Storm Warning area and are forecast to spread
northward through Friday.

STORM SURGE: A dangerous storm surge is likely to produce coastal
flooding near where the center passes the coast in areas of onshore
winds, or east of the center if Kay makes landfall along the
western Baja peninsula of Mexico. The surge will be accompanied by
large and destructive waves.

RAINFALL: Kay is expected to produce the following rainfall totals
through Saturday...

Baja California Peninsula: 6 to 10 inches, isolated maxima of 15
inches

Northwest Mainland Mexico:  2 to 4 inches, isolated maxima of 6
inches

Southernmost California:  2 to 4 inches with maxima of 6 inches

Southwest Arizona: 1 to 2 inches with isolated maxima of 4 inches

These rainfall amounts could lead to flash flooding, with landslides
possible across mountainous areas of Mexico.

SURF:  Swells generated by Kay will continue to affect portions of
the coast of southwestern Mexico during the next day or so. Large
swells are expected to spread northward along the Baja California
peninsula coast, into the Gulf of California, and to southern
California during the next couple of days. These swells will
likely cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Beven

