

000
WTPZ32 KNHC 090251
TCPEP2

BULLETIN
Tropical Storm Kay Advisory Number  19
NWS National Hurricane Center Miami FL       EP122022
800 PM PDT Thu Sep 08 2022

...HEAVY RAINS AND FLOODING CONTINUING OVER PORTIONS OF THE BAJA
CALIFORNIA PENINSULA...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...28.4N 115.0W
ABOUT 40 MI...65 KM N OF PUNTA EUGENIA MEXICO
ABOUT 320 MI...520 KM SSE OF SAN DIEGO CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Government of Mexico has discontinued the Tropical Storm
Warnings south of Puerto San Andresito on the west coast of the
Baja California peninsula and south of Loreto on the east
coast of the Baja California peninsula.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Puerto San Andresito northward along the west coast of the Baja
California peninsula to the U.S./Mexico border
* North of Loreto northward along the east coast of the Baja
California peninsula and then southward to Guaymas in mainland
Mexico

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in southern California should monitor the progress of Kay
and consult products from your local weather office.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Kay was
located near latitude 28.4 North, longitude 115.0 West.  Kay is
moving toward the north-northwest near 14 mph (22 km/h).  A slower 
northwestward to west-northwestward motion is forecast to begin 
on Friday and continue into Saturday.  A turn to the west is 
expected by late Saturday.  On the forecast track, the center of Kay 
will pass near or west of the northwest coast of the Baja peninsula 
Friday and Friday night.

Maximum sustained winds have decreased to near 65 mph (100 km/h) 
with higher gusts.  Additional weakening is forecast during the 
next couple of days, and Kay is expected to degenerate into a 
remnant low by late Saturday.

Tropical-storm-force winds extend outward up to 205 miles (335 km)
from the center.

The estimated minimum central pressure is 985 mb (29.09 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Tropical storm conditions are occurring over portions of the
Tropical Storm Warning area and are forecast to spread northward
through Friday.

Strong winds not directly associated with Kay's core wind field are
expected across portions of southern California and extreme
southwestern Arizona beginning on Friday. For information on this
wind hazard, users should see High Wind Warnings and other products
from their local NWS Weather Forecast Office.

STORM SURGE: A dangerous storm surge is likely to produce coastal
flooding in areas of onshore winds along the west coast of the
central Baja California peninsula of Mexico. The surge will be
accompanied by large and destructive waves.

RAINFALL: Kay is expected to produce the following rainfall totals
through Saturday:

Baja California Peninsula: 6 to 10 inches, isolated maxima of 15
inches

Northwest Mainland Mexico:  2 to 4 inches, isolated maxima of 6
inches

Southernmost California:  3 to 5 inches with isolated maxima of 8
inches

Southwest Arizona: 1 to 2 inches with isolated maxima of 3 inches

These rainfall amounts could lead to flash flooding, with landslides
possible across mountainous areas of Mexico.

SURF:  Swells generated by Kay will continue to affect portions of
the coast of southwestern Mexico during the next day or so. Large
swells are expected to spread northward along the Baja California
peninsula coast, into the Gulf of California, and to southern
California during the next couple of days. These swells will
likely cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1100 PM PDT.
Next complete advisory at 200 AM PDT.

$$
Forecaster Pasch

