

000
WTPZ32 KNHC 092052
TCPEP2

BULLETIN
Tropical Storm Kay Advisory Number  22
NWS National Hurricane Center Miami FL       EP122022
200 PM PDT Fri Sep 09 2022

...KAY BECOMING LESS ORGANIZED AND COULD DECAY TO A REMNANT LOW
TONIGHT...
...HEAVY RAINS CONTINUE IN PARTS OF NORTHWESTERN MEXICO AND
SOUTHERN CALIFORNIA...


SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...31.0N 118.0W
ABOUT 130 MI...205 KM SSW OF SAN DIEGO CALIFORNIA
ABOUT 150 MI...240 KM WNW OF PUNTA BAJA MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm
Warning for mainland Mexico and for the east coast of the Baja
California peninsula.  The Government of Mexico has also
discontinued the Tropical Storm Warning on the west coast of the
Baja California peninsula south of Cabo San Quintin.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Cabo San Quintin northward along the west coast of the Baja
California peninsula to the U.S./Mexico border

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in southern California should monitor the progress of Kay
and consult products from your local weather office.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Tropical Storm Kay was
located near latitude 31.0 North, longitude 118.0 West. Kay is
moving toward the northwest near 12 mph (19 km/h). A turn toward the
west-northwest and a decrease in forward speed are expected later
today, and a turn to the west is expected by late Saturday. On the
forecast track, the center of Kay will move parallel to the coast of
the northwestern Baja California peninsula through today, and then
begin to move further offshore tonight and Saturday.

Reports from an Air Force Reserve Hurricane Hunter aircraft and 
recent satellite wind data indicate that maximum sustained winds are 
now near 40 mph (65 km/h) with higher gusts.  Continued weakening 
is forecast during the next couple of days, and Kay is expected to 
degenerate into a remnant low sometime tonight.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
mainly to the east of the center.  There are continued report of 
50-70 mph (80-110 km/h) wind gusts in the mountains east and 
northeast of San Diego, with occasional gusts to hurricane force.

The minimum central pressure estimated from the Hurricane Hunter 
data is 994 mb (29.36 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Tropical storm conditions are occurring over portions of the
Tropical Storm Warning area.

Strong winds not directly associated with Kay's core wind field are
occurring across portions of southern California and extreme
southwestern Arizona. For information on this wind hazard, users
should see High Wind Warnings and other products from their local
NWS Weather Forecast Office.

RAINFALL: Kay is expected to produce the following rainfall totals:

Baja California: Additional rainfall of 2 to 4 inches with isolated
maxima of 6 inches. Event total rainfall 6 to 10 inches, isolated
maxima of 15 inches

Western Sonora: Additional rainfall of 1 to 2 inches with isolated
maxima of 4 inches. Event total rainfall 2 to 4 inches, isolated
maxima of 8 inches

Southernmost California:  2 to 4 inches with isolated maxima of 6 to
8 inches

Sierra Nevada, Arizona, and Southern Nevada: 1 to 2 inches with
isolated maxima of 3 inches

These rainfall amounts could lead to flash flooding, with landslides
possible across mountainous areas of Mexico.

SURF:  Swells generated by Kay will continue to affect portions of
the coast of southwestern Mexico during the next day or so. Large
swells are expected to spread northward along the Baja California
peninsula coast, into the Gulf of California, and to southern
California during the next day or two. These swells will likely
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 500 PM PDT.
Next complete advisory at 800 PM PDT.

$$
Forecaster Beven

