

000
WTPZ32 KNHC 092341
TCPEP2

BULLETIN
Tropical Storm Kay Intermediate Advisory Number 22A
NWS National Hurricane Center Miami FL       EP122022
500 PM PDT Fri Sep 09 2022

...KAY PULLING AWAY FROM THE NORTHERN BAJA CALIFORNIA PENINSULA...
...EXPECTED TO BECOME A POST-TROPICAL CYCLONE SOON...


SUMMARY OF 500 PM PDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...31.2N 118.4W
ABOUT 130 MI...205 KM SSW OF SAN DIEGO CALIFORNIA
ABOUT 160 MI...260 KM WNW OF PUNTA BAJA MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Cabo San Quintin northward along the west coast of the Baja
California peninsula to the U.S./Mexico border

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in southern California should monitor the progress of Kay
and consult products from your local weather office.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM PDT (0000 UTC), the center of Tropical Storm Kay was
located near latitude 31.2 North, longitude 118.4 West. Kay is
moving toward the west-northwest near 12 mph (19 km/h). A turn 
to the west is expected on Saturday, and this motion should 
continue to take Kay away from the northern Baja California 
peninsula.

Maximum sustained winds are estimated to be near 40 mph (65 km/h) 
with higher gusts. Weakening is forecast, and Kay is expected to 
degenerate into a remnant low tonight.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
mainly to the east of the center.  There are continued report of
50-70 mph (80-110 km/h) wind gusts in the mountains east and
northeast of San Diego, with occasional gusts to hurricane force.

The minimum central pressure is estimated to be 994 mb (29.36 
inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Kay can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP2 and WMO header
WTPZ42 KNHC and on the web at hurricanes.gov/text/MIATCDEP2.shtml.

WIND: Winds are expected to drop below tropical storm force in the 
Tropical Storm Warning area in the northwestern portion of the 
Baja California peninsula during the next couple of hours.

Strong winds not directly associated with Kay's core wind field are
occurring across portions of southern California and extreme
southwestern Arizona. For information on this wind hazard, users
should see High Wind Warnings and other products from their local
NWS Weather Forecast Office.

RAINFALL: Kay is expected to produce the following rainfall totals:

Baja California: Additional rainfall of 2 to 4 inches with isolated
maxima of 6 inches. Event total rainfall 6 to 10 inches, isolated
maxima of 15 inches

Western Sonora: Additional rainfall of 1 to 2 inches with isolated
maxima of 4 inches. Event total rainfall 2 to 4 inches, isolated
maxima of 8 inches

Southernmost California:  2 to 4 inches with isolated maxima of 6 to
8 inches

Sierra Nevada, Arizona, and Southern Nevada: 1 to 2 inches with
isolated maxima of 3 inches

These rainfall amounts could lead to flash flooding, with landslides
possible across mountainous areas of Mexico.

SURF:  Swells generated by Kay will continue to affect the Baja 
California peninsula coast, the Gulf of California, and southern 
California during the next day or so. These swells will likely 
cause life-threatening surf and rip current conditions. Please 
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.

$$
Forecaster Cangialosi

