

000
WTPZ32 KNHC 100239
TCPEP2

BULLETIN
Post-Tropical Cyclone Kay Advisory Number  23
NWS National Hurricane Center Miami FL       EP122022
800 PM PDT Fri Sep 09 2022

...KAY IS NOW A POST-TROPICAL CYCLONE...
...THIS IS THE LAST NHC ADVISORY...


SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...31.3N 118.9W
ABOUT 145 MI...230 KM SW OF SAN DIEGO CALIFORNIA
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm
Warning from Cabo San Quintin to the U.S./Mexico border.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.

Interests in southern California should consult products from your 
local weather office.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Post-Tropical Cyclone Kay
was located near latitude 31.3 North, longitude 118.9 West. The
post-tropical cyclone is moving toward the west-northwest near 8 mph
(13 km/h).  A turn to the southwest and then the south is expected 
this weekend and early next week.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Gradual weakening is expected during the next couple of days.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 996 mb (29.42 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Strong winds not directly associated with Kay's core wind
field are occurring across portions of southern California and
extreme southwestern Arizona. For information on this wind hazard,
users should see High Wind Warnings and other products from their
local NWS Weather Forecast Office.

RAINFALL: Kay is expected to produce the following rainfall totals:

Baja California: Additional rainfall of 2 to 4 inches with isolated
maxima of 6 inches. Event total rainfall 6 to 10 inches, isolated
maxima of 15 inches

Western Sonora: Additional rainfall of 1 to 2 inches with isolated
maxima of 4 inches. Event total rainfall 2 to 4 inches, isolated
maxima of 8 inches

Southernmost California:  2 to 4 inches with isolated maxima of 6 to
8 inches

Sierra Nevada, Arizona, and Southern Nevada: 1 to 2 inches with
isolated maxima of 3 inches

These rainfall amounts could lead to flash flooding, with landslides
possible across mountainous areas of Mexico.

SURF:  Swells generated by Kay are still affecting the coast of
southern California and the northern Baja California peninsula.
These swells should subside on Saturday.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane
Center on Kay.  For additional information on the post-tropical 
cyclone please see High Seas Forecasts issued by the National 
Weather Service, under AWIPS header NFDHSFEPI, WMO header FZPN02 
KWBC, and on the web at ocean.weather.gov/shtml/NFDHSFEPI.php


$$
Forecaster Cangialosi

