000
WTPZ31 KNHC 202046
TCPEP1
 
BULLETIN
Tropical Storm Fausto Advisory Number   8
NWS National Hurricane Center Miami FL       EP062026
200 PM PDT Mon Jul 20 2026
 
...FAUSTO EXPECTED TO BECOME A HURRICANE BY TUESDAY...
 
 
SUMMARY OF 200 PM PDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...14.2N 116.7W
ABOUT 745 MI...1205 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 PM PDT (2100 UTC), the center of Tropical Storm Fausto was 
located near latitude 14.2 North, longitude 116.7 West. Fausto is 
moving toward the northwest near 10 mph (17 km/h). A decrease in 
forward speed and a motion toward the northwest is expected to 
continue for the next day or two.  A turn back to the west-northwest 
is expected on Wednesday.
 
Maximum sustained winds are near 70 mph (110 km/h) with higher 
gusts.  Steady to rapid strengthening is expected during the next 
couple of days, and Fausto is forecast to become a hurricane later 
today or tonight.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 994 mb (29.36 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Fausto are expected to reach the west
coast of the Baja California Peninsula on Wednesday, and persist for
a couple of days.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 PM PDT.
 
$$
Forecaster Katz/Hagen
  