037 
WTPZ31 KNHC 210844
TCPEP1
 
BULLETIN
Hurricane Fausto Advisory Number  10
NWS National Hurricane Center Miami FL       EP062026
200 AM PDT Tue Jul 21 2026
 
...FAUSTO STEADILY STRENGTHENING...
 
 
SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.4N 118.0W
ABOUT 740 MI...1190 KM SW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Hurricane Fausto was located
near latitude 15.4 North, longitude 118.0 West. Fausto is moving
toward the northwest near 12 mph (19 km/h), and that general motion
is expected through tonight. A turn toward the west-northwest,
accompanied by an increase in forward speed, is expected on
Wednesday.
 
Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts. Steady to rapid strengthening is expected during the next
couple of days, with Fausto forecast to near major hurricane
intensity by Wednesday.
 
Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).
 
The estimated minimum central pressure is 985 mb (29.09 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Fausto are expected to reach the west
coast of the Baja California Peninsula on Wednesday, and persist for
a couple of days.  These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.
 
$$
Forecaster Gibbs (CPHC)
  