347 
WTPZ31 KNHC 230834
TCPEP1
 
BULLETIN
Hurricane Fausto Advisory Number  18
NWS National Hurricane Center Miami FL       EP062026
1100 PM HST Wed Jul 22 2026
 
...FAUSTO HOLDING STEADY...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.8N 124.0W
ABOUT 980 MI...1575 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 2035 MI...3275 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...982 MB...29.00 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Fausto was
located near latitude 17.8 North, longitude 124.0 West. Fausto is
moving toward the west-northwest near 12 mph (19 km/h). A continued
west-northwestward to westward motion, along with an increase in
forward speed, is expected over the next several days.
 
Maximum sustained winds are near 80 mph (130 km/h) with higher 
gusts. Some fluctuations in intensity could occur over the next day 
or so but Fausto is forecast to gradually weaken thereafter.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 982 mb (29.00 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF: Swells generated by Fausto are affecting portions of the west
coast of the Baja California Peninsula and are spreading northward
toward the coast of southern California. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep1.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.
 
$$
Forecaster Kelly
  