000
WTPZ31 KNHC 240251
TCPEP1
 
BULLETIN
Hurricane Fausto Advisory Number  21
NWS National Hurricane Center Miami FL       EP062026
500 PM HST Thu Jul 23 2026
 
...FAUSTO STRENGTHENS A BIT MORE...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...18.3N 128.4W
ABOUT 1235 MI...1990 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 1745 MI...2805 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Hurricane Fausto was located
near latitude 18.3 North, longitude 128.4 West. Fausto is moving
toward the west near 15 mph (24 km/h), and this motion is expected 
to continue over the next few days.
 
Maximum sustained winds have increased to near 90 mph (150 km/h) 
with higher gusts. Little change in intensity is forecast through 
tonight, followed by steady weakening through the weekend.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 976 mb (28.82 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC. 

SURF: Swells generated by Fausto are affecting the west coast of the
Baja California Peninsula and the coast of southern California.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep1.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Mahoney/Berg
  