000
WTPZ31 KNHC 240838
TCPEP1
 
BULLETIN
Hurricane Fausto Advisory Number  22
NWS National Hurricane Center Miami FL       EP062026
1100 PM HST Thu Jul 23 2026
 
...FAUSTO CONTINUES WESTWARD...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...18.5N 129.9W
ABOUT 1325 MI...2135 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 1645 MI...2645 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...973 MB...28.74 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Fausto was
located near latitude 18.5 North, longitude 129.9 West. Fausto is
moving toward the west near 15 mph (24 km/h), and this motion is
expected to continue over the next few days.
 
Maximum sustained winds have increased to near 100 mph (155 km/h) 
with higher gusts. Little change in intensity is forecast through 
tonight, followed by steady weakening through the weekend.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 973 mb (28.74 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Swells generated by Fausto are affecting the west coast of the
Baja California Peninsula and the coast of southern California.
These swells are likely to cause life-threatening surf and rip
current conditions. Please consult products from your local weather
office.
 
A depiction of rip current risk for the United States can be found
at: hurricanes.gov/graphics_ep1.shtml?ripCurrents
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.
 
$$
Forecaster Kelly
  