226 
WTPZ31 KNHC 252034
TCPEP1
 
BULLETIN
Hurricane Fausto Advisory Number  28
NWS National Hurricane Center Miami FL       EP062026
1100 AM HST Sat Jul 25 2026
 
...FAUSTO CONTINUES WESTWARD...
...EXPECTED TO MOVE INTO THE CENTRAL PACIFIC EARLY SUNDAY...
 
 
SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...19.3N 137.6W
ABOUT 1140 MI...1835 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...100 MPH...155 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...971 MB...28.68 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Fausto was 
located near latitude 19.3 North, longitude 137.6 West. Fausto is 
moving toward the west near 14 mph (22 km/h), and this general 
motion is expected to continue for the next several days.
 
Maximum sustained winds are near 100 mph (155 km/h) with higher 
gusts. Gradual weakening is forecast during the next several days.
 
Hurricane-force winds extend outward up to 40 miles (65 km) from the
center and tropical-storm-force winds extend outward up to 185 miles
(295 km).
 
The estimated minimum central pressure is 971 mb (28.68 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP1 and WMO header WTPZ41 KNHC.
 
SURF: Surf generated by Fausto is expected to begin building across
east-facing shores of the eastern end of Hawaii on Sunday, spreading 
westward Sunday night into Monday, and continue building through 
Tuesday as Fausto approaches and moves into the area. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.
 
$$
Forecaster Reinhart
  