000
WTPA31 PHFO 261445
TCPCP1
 
BULLETIN
Hurricane Fausto Advisory Number  31
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
500 AM HST Sun Jul 26 2026
 
...FAUSTO CONTINUES TO GRADUALLY WEAKEN...
...SIGNIFICANT SURF EXPECTED FOR PORTIONS OF THE HAWAIIAN ISLANDS 
THIS WEEK...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...19.9N 141.1W
ABOUT 910 MI...1465 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...977 MB...28.85 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Fausto was located 
near latitude 19.9 North, longitude 141.1 West. Fausto is moving 
toward the west near 14 mph (22 km/h), and this general motion is 
expected to continue for the next several days.
 
Maximum sustained winds have decreased to near 85 mph (140 km/h) 
with higher gusts. Gradual weakening is forecast during the next 
several days.
 
Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 175 miles
(280 km).
 
The estimated minimum central pressure is 977 mb (28.85 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto is expected to begin building across
east-facing shores of the eastern end of Hawaii later today,
spreading westward tonight into Monday, and continue building
through Tuesday as Fausto approaches and moves into the area. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Future information on Fausto can be found under Central Pacific 
basin headers starting with this advisory at 500 AM HST, under AWIPS 
header HFOTCPCP1, WMO header WTPA31 PHFO. Products will continue to 
be available on the web at hurricanes.gov. 

Next complete advisory at 1100 AM HST. 
 
$$
Forecaster Papin
  