000
WTPA31 PHFO 270235
TCPCP1
 
BULLETIN
Hurricane Fausto Advisory Number  33
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
500 PM HST Sun Jul 26 2026
 
...FAUSTO HOLDING STEADY AS IT CONTINUES WESTWARD ACROSS THE 
CENTRAL PACIFIC...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...20.1N 143.7W
ABOUT 740 MI...1190 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...984 MB...29.06 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Hurricane Fausto was located 
near latitude 20.1 North, longitude 143.7 West. Fausto is moving 
toward the west near 15 mph (24 km/h), and a general westward to 
west-northwestward motion is expected to continue for the next 
several days.
 
Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts. Gradual weakening is forecast during the next several days.
 
Hurricane-force winds extend outward up to 35 miles (55 km) from the 
center and tropical-storm-force winds extend outward up to 150 miles 
(240 km).
 
The estimated minimum central pressure is 984 mb (29.06 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto will continue to build westward 
across the state along exposed east-facing shores through Tuesday as 
Fausto approaches and begins to pass north of the islands. Large 
surf and strong currents will lead to dangerous conditions along 
exposed shores. Please consult products from your local weather 
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Gibbs/Pierce
  