000
WTPA31 PHFO 270844
TCPCP1
 
BULLETIN
Hurricane Fausto Advisory Number  34
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
1100 PM HST Sun Jul 26 2026
 
...FAUSTO WEAKENS SLIGHTLY AS IT CONTINUES WEST-NORTHWESTWARD ACROSS 
THE CENTRAL PACIFIC...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.4N 144.8W
ABOUT 670 MI...1080 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Hurricane Fausto was 
located near latitude 20.4 North, longitude 144.8 West. Fausto is 
moving toward the west-northwest near 14 mph (22 km/h), and a 
general westward to west-northwestward motion is expected to 
continue for the next several days.
 
Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts. Gradual weakening is forecast during the next several days.
 
Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).
 
The estimated minimum central pressure is 988 mb (29.18 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto will continue to build westward
across the state along exposed east-facing shores through Tuesday as
Fausto approaches and begins to pass north of the islands. Large
surf and strong currents will lead to dangerous conditions along
exposed shores. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.
 
$$
Forecaster Gibbs/Pierce
  