000
WTPA31 PHFO 271446
TCPCP1
 
BULLETIN
Hurricane Fausto Advisory Number  35
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
500 AM HST Mon Jul 27 2026
 
...FAUSTO STILL A CATEGORY ONE HURRICANE...
...SIGNIFICANT SURF EXPECTED FOR THE HAWAIIAN ISLANDS OVER THE NEXT 
FEW DAYS...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...20.7N 146.2W
ABOUT 580 MI...935 KM E OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...986 MB...29.12 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Hurricane Fausto was located 
near latitude 20.7 North, longitude 146.2 West. Fausto is moving 
toward the west-northwest near 14 mph (22 km/h), and a general 
westward to west-northwestward motion is expected to continue for 
the next several days.
 
Maximum sustained winds remain near 80 mph (130 km/h) with higher
gusts. Gradual weakening is forecast during the next several days.
 
Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The estimated minimum central pressure is 986 mb (29.12 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto will continue to build westward
across Hawaii along exposed east-facing shores through Tuesday as
Fausto approaches and begins to pass north of the islands. Large
surf and strong currents will lead to dangerous conditions along
exposed shores. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 AM HST.
 
$$
Forecaster Papin
  