000
WTPA31 PHFO 272046
TCPCP1
 
BULLETIN
Hurricane Fausto Advisory Number  36
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
1100 AM HST Mon Jul 27 2026
 
...AIRCRAFT DATA FINDS FAUSTO WEAKENING...
...SIGNIFICANT SURF EXPECTED FOR THE HAWAIIAN ISLANDS OVER THE NEXT
FEW DAYS...
 
 
SUMMARY OF 1100 AM HST...2100 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.3N 147.5W
ABOUT 505 MI...810 KM ENE OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 AM HST (2100 UTC), the center of Hurricane Fausto was 
located by Air Force Reconnaissance aircraft near latitude 21.3 
North, longitude 147.5 West. Fausto is moving toward the 
west-northwest near 16 mph (26 km/h), and a general 
west-northwestward motion is expected to continue for the next 
several days.
 
Maximum sustained winds have decreased to near 75 mph (120 km/h) 
with higher gusts. Additional weakening is forecast during the next 
several days.
 
Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).
 
The minimum central pressure estimated by aircraft dropsonde data is 
994 mb (29.36 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto will continue to build westward
across Hawaii along exposed east-facing shores through Tuesday as
Fausto approaches and begins to pass north of the islands. Large
surf and strong currents will lead to dangerous conditions along
exposed shores. Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 PM HST.
 
$$
Forecaster Papin
  