964 
WTPA31 PHFO 280235
TCPCP1
 
BULLETIN
Tropical Storm Fausto Advisory Number  37
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
500 PM HST Mon Jul 27 2026
 
...FAUSTO NOW A TROPICAL STORM...
...SIGNIFICANT SURF EXPECTED FOR THE HAWAIIAN ISLANDS OVER THE NEXT
FEW DAYS...
 
 
SUMMARY OF 500 PM HST...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...21.7N 149.0W
ABOUT 415 MI...670 KM ENE OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 PM HST (0300 UTC), the center of Tropical Storm Fausto was
located near latitude 21.7 North, longitude 149.0 West.  Fausto is
moving toward the west-northwest near 16 mph (26 km/h), and a 
generally west-northwestward motion is expected to continue for the 
next several days.  On the forecast track, Fausto should pass north 
of the Hawaiian Islands during the next few days.
 
Maximum sustained winds have decreased to near 70 mph (110 km/h) 
with higher gusts.  Additional weakening is forecast during the 
next several days.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto will continue to build westward
across Hawaii along exposed east-facing shores through Tuesday as
Fausto approaches and begins to pass north of the islands.  Large
surf and strong currents will lead to dangerous conditions along
exposed shores.  Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 1100 PM HST.
 
$$
Forecaster Pasch
  