000
WTPA31 PHFO 280849
TCPCP1
 
BULLETIN
Tropical Storm Fausto Advisory Number  38
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
1100 PM HST Mon Jul 27 2026
 
...FAUSTO FORECAST TO PASS NORTH OF THE HAWAIIAN ISLANDS TUESDAY
NIGHT THROUGH LATE WEDNESDAY...
...SIGNIFICANT SURF EXPECTED FOR THE HAWAIIAN ISLANDS OVER THE NEXT
FEW DAYS...
 
 
SUMMARY OF 1100 PM HST...0900 UTC...INFORMATION
-----------------------------------------------
LOCATION...21.7N 150.3W
ABOUT 340 MI...545 KM ENE OF HILO HAWAII
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 1100 PM HST (0900 UTC), the center of Tropical Storm Fausto was
located near latitude 21.7 North, longitude 150.3 West. Fausto is
moving toward the west-northwest near 15 mph (24 km/h), and a
generally west-northwestward motion is expected to continue for the
next several days. On the forecast track, Fausto should pass north
of the Hawaiian Islands Tuesday night through late Wednesday.
 
Maximum sustained winds have decreased to near 65 mph (100 km/h)
with higher gusts. Additional weakening is forecast during the
next few days.
 
Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by Fausto will continue to build westward
across Hawaii along exposed east-facing shores through Tuesday as
Fausto approaches and begins to pass north of the islands.  Large
surf and strong currents will lead to dangerous conditions along
exposed shores.  Please consult products from your local weather
office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 500 AM HST.
 
$$
Forecaster Hagen
  