966 
WTPA31 PHFO 291433
TCPCP1
 
BULLETIN
Post-Tropical Cyclone Fausto Advisory Number  43
NWS Central Pacific Hurricane Center Honolulu HI   EP062026
Issued by NWS National Hurricane Center Miami FL
500 AM HST Wed Jul 29 2026
 
...FAUSTO DEGENERATES TO A REMNANT LOW PRESSURE AREA...
...SIGNIFICANT SURF STILL EXPECTED FOR THE HAWAIIAN ISLANDS THROUGH
TODAY...
 
 
SUMMARY OF 500 AM HST...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...23.8N 155.6W
ABOUT 285 MI...460 KM N OF HILO HAWAII
ABOUT 225 MI...365 KM NE OF HONOLULU HAWAII
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
Interests in the Hawaiian Islands should monitor the progress of
the remnants of Fausto.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 500 AM HST (1500 UTC), the center of Post-Tropical Cyclone Fausto
was located near latitude 23.8 North, longitude 155.6 West. The
post-tropical cyclone is moving toward the west-northwest near     
13 mph (20 km/h) and this general motion is expected to continue 
for the next couple of days. On the forecast track, Fausto will 
pass north of the Hawaiian Islands through this evening.
 
Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Weakening is expected, and the post-tropical cyclone is forecast to 
weaken to a trough by Friday.

The estimated minimum central pressure is 1008 mb (29.77 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
Key messages for Fausto can be found in the Tropical Cyclone
Discussion under AWIPS header HFOTCDCP1 and WMO header WTPA41 PHFO.
 
SURF: Surf generated by the remnants of Fausto is building westward
across the Hawaiian Islands along exposed east-facing shores and
will remain dangerous today as the system passes north of the
islands.  Large surf and strong currents will lead to dangerous
conditions along exposed shores.  Please consult products from your
local weather office.
 
 
NEXT ADVISORY
-------------
This is the last public advisory issued by the Central Pacific
Hurricane Center on this system. For additional information on the 
remnant low please see High Seas Forecasts issued by the National 
Weather Service, under AWIPS header NFDHSFEPI, WMO header FZPN02 
KWBC, and on the web at ocean.weather.gov/shtml/NFDHSFEPI.php
 
$$
Forecaster Beven
  