

000
WTPZ33 KNHC 152334
TCPEP3

BULLETIN
Tropical Depression Thirteen-E Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       EP132022
700 PM CDT Thu Sep 15 2022

...TROPICAL DEPRESSION MOVING SLOWLY NORTHWESTWARD...
...HEAVY RAINS EXPECTED OVER PORTIONS OF SOUTHERN MEXICO...


SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...12.8N 95.6W
ABOUT 215 MI...345 KM SSE OF PUERTO ANGEL MEXICO
ABOUT 235 MI...380 KM SSE OF PUERTO ESCONDIDO MEXICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 3 MPH...6 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Laguna de Chacahua westward to Zihuatanejo

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Depression
Thirteen-E was located near latitude 12.8 North, longitude 95.6
West. The depression is moving toward the northwest near 3 mph (6
km/h).  A northwestward motion with an increase in forward speed is
expected over the next couple of days.  On the forecast track, the
center of the cyclone is expected to approach the southern coast of
Mexico within the watch area on Saturday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Gradual strengthening is forecast during the next couple of
days, and the depression is forecast to become a tropical storm
tonight or Friday.

The estimated minimum central pressure is 1007 mb (29.74 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  The system is expected to produce rainfall totals of
3-6 inches with isolated maximum totals of 10 inches across coastal
portions of the Mexican States of Oaxaca, Guerrero, and Michoacán
through Sunday morning. These rains may produce flash and urban
flooding, along with isolated mudslides in areas of higher terrain
near the coast.

WIND:  Tropical storm conditions are possible within the watch
area beginning early Saturday.

SURF:  Swells generated by the depression are expected to begin
affecting portions of the coast of southern Mexico by late Friday
and continue into the weekend.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Beven

