

000
WTPZ33 KNHC 160857
TCPEP3

BULLETIN
Tropical Storm Lester Advisory Number   3
NWS National Hurricane Center Miami FL       EP132022
400 AM CDT Fri Sep 16 2022

...DEPRESSION BECOMES TROPICAL STORM LESTER...
...TROPICAL STORM WARNING ISSUED FOR PORTIONS OF THE SOUTHERN COAST 
OF MEXICO...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...13.2N 95.9W
ABOUT 175 MI...285 KM SSE OF PUERTO ANGEL MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has upgraded the Tropical Storm Watch to a 
Tropical Storm Warning from Punta Maldonado to Zihuatanejo, and 
issued a Tropical Storm Watch from Zihuatanejo to Lazaro Cardenas.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Punta Maldonado westward to Zihuatanejo

A Tropical Storm Watch is in effect for...
* Laguna de Chacahua westward to Punta Maldonado
* Zihuatanejo westward to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Lester was 
located near latitude 13.2 North, longitude 95.9 West. Lester is 
moving toward the north-northwest near 5 mph (7 km/h). A 
northwestward motion with an increase in forward speed is expected 
over the next couple of days.  On the forecast track, the center of 
the cyclone is expected to move near or over the coast of 
southwestern Mexico Saturday or Saturday night.

Satellite-derived wind data indicate that maximum sustained winds 
have increased to near 40 mph (65 km/h) with higher gusts.  Gradual 
strengthening is forecast during the next couple of days.

Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Lester can be found in the Tropical 
Cyclone Discussion under AWIPS header MIATCDEP3 and WMO header 
WTPZ43 KNHC and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

RAINFALL:  The system is expected to produce rainfall totals of 3-6
inches with local totals of 10 inches across coastal portions of the
Mexican States of Oaxaca, Guerrero, Michoacán, Colima, and into
Jalisco through Monday. These rains may produce flash and urban
flooding, along with isolated mudslides in areas of higher coastal
terrain.

WIND:  Tropical storm conditions are expected in the tropical storm
warning areas and possible within the watch area beginning early
Saturday.

SURF:  Swells generated by the depression are expected to begin
affecting portions of the coast of southern Mexico later today and
continue into the weekend.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Bucci

