

708 
WTPZ33 KNHC 161435
TCPEP3

BULLETIN
Tropical Storm Lester Advisory Number   4
NWS National Hurricane Center Miami FL       EP132022
1000 AM CDT Fri Sep 16 2022

...LESTER MOVING NORTHWESTWARD TOWARD THE COAST OF SOUTHWESTERN
MEXICO...
...HEAVY RAINFALL EXPECTED TO SPREAD OVER PORTIONS OF SOUTHERN
MEXICO LATER TODAY...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.7N 96.5W
ABOUT 315 MI...510 KM SE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Punta Maldonado to Zihuatanejo

A Tropical Storm Watch is in effect for...
* East of Punta Maldonado to Laguna de Chacahua
* West of Zihuatanejo to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Lester was 
located near latitude 13.7 North, longitude 96.5 West. Lester is 
moving toward the northwest near 8 mph (13 km/h). A slightly faster 
northwestward motion is expected to begin later today. On the 
forecast track, the center of the cyclone is expected to move near 
or over the coast of southwestern Mexico Saturday or Saturday 
night, and dissipate over southwestern Mexico on Sunday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Gradual strengthening is forecast during the next day or so. Rapid 
weakening is expected after the center crosses the coast of Mexico.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Lester can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP3 and WMO header
WTPZ43 KNHC and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

RAINFALL:  Lester is expected to produce rainfall totals of 3 to 6 
inches with local maximum totals of 10 inches across coastal 
portions of the Mexican States of western Oaxaca, Guerrero, 
Michoacan, Colima, and Jalisco through Monday. These rains may 
produce flash and urban flooding, along with possible mudslides in 
areas of higher coastal terrain. 

WIND:  Tropical storm conditions are expected in the tropical storm
warning areas and possible within the watch area beginning early
Saturday.

SURF:  Swells generated by Lester are affecting portions of the
coast of southern Mexico and this will continue into the weekend.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster Latto


