

000
WTPZ33 KNHC 162034
TCPEP3

BULLETIN
Tropical Storm Lester Advisory Number   5
NWS National Hurricane Center Miami FL       EP132022
400 PM CDT Fri Sep 16 2022

...TROPICAL STORM WARNING EXTENDED EASTWARD ALONG THE COAST OF 
MEXICO TO PUERTO ESCONDIDO...
...HEAVY RAINS EXPECTED TO BEGIN TONIGHT...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...14.3N 97.3W
ABOUT 250 MI...400 KM SE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has extended the Tropical Storm Warning
eastward to Puerto Escondido.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Puerto Escondido to Zihuatanejo

A Tropical Storm Watch is in effect for...
* West of Zihuatanejo to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Tropical Storm Lester was
located near latitude 14.3 North, longitude 97.3 West. Lester is
moving toward the northwest near 12 mph (19 km/h) and this motion is
expected to continue through Saturday night. On the forecast track,
the center of the cyclone is expected to move near or over the coast
of southwestern Mexico Saturday or Saturday night, and dissipate
over southwestern Mexico on Sunday morning.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Gradual strengthening is forecast through Saturday morning. Rapid 
weakening is expected after the center crosses the coast of Mexico.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Lester can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP3 and WMO header
WTPZ43 KNHC and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

RAINFALL:  Lester is forecast to produce rainfall totals across the
following Mexican states:

Coastal Oaxaca, lower coast of Guerrero, coastal Colima and coastal
Jalisco:  3 to 6 inches with local maximum totals of 10 inches.

Upper coast of Guerrero and coastal Michoacan: 8 to 12 inches with
maximum totals of 16 inches.

These rains may produce flash and urban flooding, along with
possible mudslides in areas of higher coastal terrain.

WIND:  Tropical storm conditions are expected in the tropical storm
warning area beginning tonight, and are possible within the tropical
storm watch area by Saturday afternoon.

SURF:  Swells generated by Lester are affecting portions of the
coast of southern Mexico and this will continue into the weekend.
These swells are likely to cause life-threatening surf and rip
current conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Latto

