

420 
WTPZ33 KNHC 170549
TCPEP3

BULLETIN
Tropical Storm Lester Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       EP132022
100 AM CDT Sat Sep 17 2022

...TROPICAL STORM CONDITIONS EXPECTED TO BEGIN THIS MORNING IN 
SOUTHWESTERN MEXICO...
...HEAVY RAINS WILL CONTINUE THROUGH THE DAY...


SUMMARY OF 100 AM CDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...15.2N 98.3W
ABOUT 150 MI...240 KM SE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Puerto Escondido to Zihuatanejo

A Tropical Storm Watch is in effect for...
* West of Zihuatanejo to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 100 AM CDT (0600 UTC), the center of Tropical Storm Lester was 
located near latitude 15.2 North, longitude 98.3 West. Lester is 
moving toward the northwest near 12 mph (19 km/h) and this motion is 
expected to continue through today. On the forecast track, the 
center of the cyclone is expected to move near or over the coast of 
southwestern Mexico later today, and dissipate over southwestern 
Mexico Sunday morning.

Maximum sustained winds are near 40 mph (65 km/h) with higher
gusts. Gradual strengthening is forecast until the center crosses
the coast of Mexico.  Rapid weakening is expected after landfall.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Lester can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP3 and WMO header
WTPZ43 KNHC and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

RAINFALL: Lester is forecast to produce rainfall totals across the
following Mexican states:

Coastal Oaxaca, lower coast of Guerrero, coastal Colima and coastal
Jalisco: 3-6 inches with local maximum totals of 10 inches.

Upper coast of Guerrero and coastal Michoacan: 8 to 12 inches with
maximum totals of 16 inches.

These rains may produce flash and urban flooding, along with
possible mudslides in areas of higher coastal terrain.

WIND:  Tropical storm conditions are expected to reach portions of 
the coast within the tropical storm warning area early this morning, 
and are possible within the tropical storm watch area by this 
afternoon.

SURF:  Swells generated by Lester are affecting portions of the 
coast of southern and southwestern Mexico and this will continue 
into the weekend. These swells are likely to cause life-threatening 
surf and rip current conditions.  Please consult products from your 
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 AM CDT.

$$
Forecaster Bucci


