

000
WTPZ33 KNHC 171149
TCPEP3

BULLETIN
Tropical Storm Lester Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       EP132022
700 AM CDT Sat Sep 17 2022

...HEAVY RAIN WITH THE POTENTIAL FOR FLASH FLOODING AND MUDSLIDES 
EXPECTED FOR PORTIONS OF SOUTHWESTERN MEXICO TODAY...


SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...15.8N 98.6W
ABOUT 110 MI...180 KM SE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...NW OR 310 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Puerto Escondido to Zihuatanejo

A Tropical Storm Watch is in effect for...
* West of Zihuatanejo to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Tropical Storm Lester was 
located near latitude 15.8 North, longitude 98.6 West. Lester is 
moving toward the northwest near 10 mph (17 km/h), and this motion 
is expected to continue through today. On the forecast track, the 
center of the Lester is expected to move near or over the coast of 
southwestern Mexico today.

Maximum sustained winds are near 45 mph (75 km/h) with higher
gusts. Rapid weakening leading to dissipation is expected once the 
center of Lester reaches the coast of Mexico.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Lester can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP3 and WMO header
WTPZ43 KNHC and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

RAINFALL: Lester is forecast to produce the following additional
rainfall across coastal portions of the following Mexican states
through Sunday:

Western Oaxaca, Guerrero, Michoacan, Colima, into Jalisco: 3 to 6
inches with local maximum totals of 12 inches.

These rains may produce flash and urban flooding, along with
possible mudslides in areas of higher coastal terrain.

WIND:  Tropical storm conditions are expected along portions of the 
coast within the tropical storm warning area and are possible within 
the tropical storm watch area by this morning.

SURF:  Swells generated by Lester are affecting portions of the
coast of southern and southwestern Mexico, and this will continue
into the weekend. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster D. Zelinsky

