

000
WTPZ33 KNHC 171437
TCPEP3

BULLETIN
Tropical Storm Lester Advisory Number   8
NWS National Hurricane Center Miami FL       EP132022
1000 AM CDT Sat Sep 17 2022

...CENTER OF LESTER VERY NEAR THE COAST OF MEXICO...
...RISK OF FLASH FLOODING AND MUDSLIDES ACROSS PORTIONS OF
SOUTHWESTERN MEXICO WILL PERSIST TODAY...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...16.0N 99.0W
ABOUT 85 MI...140 KM SE OF ACAPULCO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Puerto Escondido to Zihuatanejo

A Tropical Storm Watch is in effect for...
* West of Zihuatanejo to Lazaro Cardenas

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Lester was 
estimated to be near latitude 16.0 North, longitude 99.0 West. 
Lester is moving toward the northwest near 10 mph (17 km/h). The 
tropical storm is forecast to continue moving toward the coast 
during the next few hours and should move inland over southwestern 
Mexico today.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Rapid weakening leading to dissipation is expected once the center 
of Lester reaches the coast of Mexico. 

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Storm Lester can be found in the Tropical
Cyclone Discussion under AWIPS header MIATCDEP3 and WMO header
WTPZ43 KNHC and on the web at hurricanes.gov/text/MIATCDEP3.shtml.

RAINFALL: Lester is forecast to produce rainfall totals across the 
following Mexican states through Sunday:

Coastal Michoacan and coastal Guerrero: 8 to 12 inches with maximum 
totals of 16 inches

Central to Western coastal  Oaxaca, coastal  Colima and coastal 
Jalisco: 3 to 6 inches with local maximum totals of 12 inches.

These rains may produce flash and urban flooding, along with 
possible mudslides in areas of higher coastal terrain. 

WIND:  Tropical storm conditions are expected along portions of the
coast within the tropical storm warning area and are possible within
the tropical storm watch area during the next few hours.

SURF:  Swells generated by Lester are affecting portions of the
coast of southern and southwestern Mexico, and this will continue
into the weekend. These swells are likely to cause life-threatening
surf and rip current conditions.  Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 PM CDT.
Next complete advisory at 400 PM CDT.

$$
Forecaster D. Zelinsky

