

346 
WTNT31 KNHC 232343
TCPAT1

BULLETIN
Tropical Depression Ophelia Intermediate Advisory Number 10A
NWS National Hurricane Center Miami FL       AL162023
800 PM EDT Sat Sep 23 2023

...OPHELIA NOW A TROPICAL DEPRESSION...
...ALL STORM SURGE AND TROPICAL STORM WARNINGS DISCONTINUED...


SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...37.0N 77.6W
ABOUT 40 MI...60 KM SSW OF RICHMOND VIRGINIA
ABOUT 165 MI...265 KM WSW OF OCEAN CITY MARYLAND
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...N OR 355 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

All Storm Surge and Tropical Storm Warnings have been discontinued.


SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

Coastal flooding warnings and wind advisories remain in effect for 
portions of the U.S. Mid-Atlantic.  For storm information specific 
to your area, please monitor products issued by your local National 
Weather Service forecast office.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Tropical Storm Ophelia was
located near latitude 37.0 North, longitude 77.6 West. Ophelia is
moving toward the north near 9 mph (15 km/h). A gradual turn toward
the northeast is expected by tomorrow. On the forecast track, the
center of Ophelia is expected to continue moving over southeastern
Virginia through tonight, and then over the Delmarva Peninsula by
tomorrow.

Maximum sustained winds have decreased to near 35 mph (55 km/h) 
with higher gusts.  Additional weakening is expected, and Ophelia 
is likely to become a post-tropical cyclone tomorrow.

The estimated minimum central pressure is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ophelia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1, WMO header WTNT41 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

STORM SURGE:  The combination of storm surge and the tide will cause 
normally dry areas near the coast to be flooded by rising waters 
moving inland from the shoreline.  The water could reach the 
following heights above ground somewhere in the indicated areas if 
the peak surge occurs at the time of high tide...

Hatteras Inlet, NC to Manasquan Inlet, NJ...1-3 ft
Chesapeake Bay and Tidal Rivers...1-3 ft
Delaware Bay...1-3 ft
Beaufort Inlet, NC to Hatteras Inlet, NC...1-2 ft
Neuse, Bay, Pamlico, and Pungo Rivers...1-2 ft
Albemarle and Pamlico Sound...1-2 ft

The deepest water will occur along the immediate coast in areas of
onshore winds, where the surge will be accompanied by dangerous
waves.  Surge-related flooding depends on the relative timing of the
surge and the tidal cycle, and can vary greatly over short
distances.  For information specific to your area, please see
products issued by your local National Weather Service forecast
office.

WIND:  Gusty winds to tropical storm force are still possible near 
the coasts of North Carolina and Virginia during the next few hours.

RAINFALL:  Ophelia is expected to produce the following additional
rainfall through Sunday night:

Portions of the Mid-Atlantic from north central North Carolina
through New Jersey...1 to 3 inches with isolated higher totals up
to 5 inches.

Across southeastern New York through southern New England...1 to 3
inches.

This rainfall may produce locally considerable flash, urban, and
small stream flooding impacts, particularly across the Mid Atlantic
region from North Carolina to New Jersey. Isolated river flooding is
possible in areas of heavier rainfall.

SURF:  Swells generated by Ophelia will continue to affect much of
the east coast of the United States through the weekend.  These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.

TORNADOES:  A tornado or two may occur through tonight across parts
of the Mid-Atlantic Coast.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.

$$
Forecaster Berg


