

000
WTNT31 KWNH 240856
TCPAT1

BULLETIN
Post-Tropical Cyclone Ophelia Advisory Number  12
NWS Weather Prediction Center College Park MD   AL162023
500 AM EDT Sun Sep 24 2023

...POST-TROPICAL OPHELIA CONTINUES TO POSE A RISK OF COASTAL
FLOODING AND LOCALLY HEAVY RAIN FROM WASHINGTON D.C. TO NEW YORK
CITY TODAY...


SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...37.7N 77.3W
ABOUT 85 MI...135 KM S OF WASHINGTON D.C.
MAXIMUM SUSTAINED WINDS...25 MPH...35 KM/H
PRESENT MOVEMENT...NNE OR 20 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1007 MB...29.74 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

Flash flood watches have expired.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

Coastal flood warnings and advisories remain in effect for portions
of the U.S. Mid-Atlantic.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Post-Tropical Cyclone
Ophelia was located near latitude 37.7 North, longitude 77.3 West.
The post-tropical cyclone is moving toward the north-northeast near
12 mph (19 km/h) and this motion is expected to continue today 
before a turn to the east tonight.

Maximum sustained winds are near 25 mph (35 km/h) with higher gusts.
A gradual weakening is forecast during the next 48 hours as the low 
center moves slowly offshore.

The estimated minimum central pressure is 1007 mb (29.74 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ophelia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT1, WMO header WTNT41 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT1.shtml

STORM SURGE:  Water levels remain elevated within portions of
Chesapeake Bay and its tidal rivers but should gradually recede
through today.  For information specific to your area,
please see products issued by your local National Weather Service
forecast office.


RAINFALL:  Ophelia is expected to produce the following additional
rainfall through late this coming night:

Portions of the Mid-Atlantic to southern New England…1 to 3 inches

This rainfall may produce localized flash, urban, and small stream
flooding impacts across portions of the Mid-Atlantic region into
southern New England.  Isolated river flooding is possible in areas
of heavier rainfall.


SURF:  Swells generated by Ophelia will continue to affect much of
the east coast of the United States through today.  These swells are 
likely to cause life-threatening surf and rip current conditions.  
Please consult products from your local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the Weather Prediction
Center on this system.

$$
Forecaster Carbin

