

000
WTNT34 KNHC 230855
TCPAT4

BULLETIN
Tropical Depression Nine Advisory Number   1
NWS National Hurricane Center Miami FL       AL092022
500 AM AST Fri Sep 23 2022

...TROPICAL DEPRESSION FORMS OVER THE CENTRAL CARIBBEAN SEA...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...13.9N 68.6W
ABOUT 615 MI...985 KM ESE OF KINGSTON JAMAICA
ABOUT 1105 MI...1780 KM ESE OF HAVANA CUBA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Depression Nine was
located near latitude 13.9 North, longitude 68.6 West. The
depression is moving toward the west-northwest near 13 mph (20 
km/h). A turn more westward is forecast over the next next day 
or so followed by a turn back to the west-northwest and
northwest by this weekend.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts. 
Only slow intensification is forecast over the next day or so, 
followed by more significant intensification over the weekend and 
early next week.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for TD Nine can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT4 and WMO header
WTNT44 KNHC and on the web at hurricanes.gov/text/MIATCDAT4.shtml.

RAINFALL: Tropical Depression Nine is expected to produce the
following rainfall:

Aruba, Bonaire, and Curacao: Additional 1 to 2 inches

Northern Venezuela: 2 to 5 inches

Northern Columbia: 3 to 6 inches

Jamaica: 4 to 8 inches with local maximum up to 12 inches

Cayman Islands: 4 to 8 inches

Southern Haiti and Southern Dominican Republic: 2 to 4 inches with
local maximum up to 6 inches

These rains may produce flash flooding and mudslides in areas of
higher terrain, particularly over Jamaica.

SURF: Swells generated by this system will begin affecting Jamaica, 
the Cayman Islands and Cuba over the next several days. These swells 
are likely to cause life-threatening surf and rip current 
conditions. Please consult products form your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin

