

000
WTNT34 KNHC 231453
TCPAT4

BULLETIN
Tropical Depression Nine Advisory Number   2
NWS National Hurricane Center Miami FL       AL092022
1100 AM EDT Fri Sep 23 2022

...DEPRESSION EXPECTED TO STRENGTHEN OVER THE CARIBBEAN SEA...


SUMMARY OF 1100 AM EDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.2N 70.1W
ABOUT 515 MI...830 KM ESE OF KINGSTON JAMAICA
ABOUT 1015 MI...1635 KM SE OF HAVANA CUBA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Jamaica and the Cayman Islands should closely monitor
the progress of this system.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM EDT (1500 UTC), the center of Tropical Depression Nine 
was located near latitude 14.2 North, longitude 70.1 West. The 
depression is moving toward the west-northwest near 14 mph (22 
km/h). A westward motion is expected to begin later today and 
continue through Saturday, followed by a turn toward the 
west-northwest and northwest on Sunday and Monday. On the forecast 
track, the center of the cyclone is forecast to move across the 
central Caribbean Sea through Saturday, pass south of Jamaica on 
Saturday night and Sunday, and approach the Cayman Islands on Sunday 
night and early Monday.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Some slow strengthening is forecast during the next day or so, and 
the depression is expected to become a tropical storm by tonight. 
More significant intensification is forecast on Sunday and Monday.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Nine can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC and on the web at
hurricanes.gov/text/MIATCDAT4.shtml.

RAINFALL: Tropical Depression Nine is expected to produce the
following rainfall:

Aruba, Bonaire, Curacao, Northern Venezuela and Northern Colombia:
Additional 1 to 2 inches

Southern Haiti and Southern Dominican Republic: 2 to 4 inches, with
local maximum up to 6 inches

Jamaica and the Cayman Islands: 4 to 8 inches, with local maximum up
to 12 inches

Western to central Cuba: 6 to 10 inches, with local maximum up to 14
inches.

These rains may produce flash flooding and mudslides in areas of
higher terrain, particularly over Jamaica and Cuba.

SURF: Swells generated by this system will begin affecting Jamaica,
the Cayman Islands, and Cuba over the next several days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM EDT.

$$
Forecaster Reinhart

