

000
WTNT34 KNHC 232345
TCPAT4

BULLETIN
Tropical Depression Nine Intermediate Advisory Number 3A
NWS National Hurricane Center Miami FL       AL092022
800 PM EDT Fri Sep 23 2022

...DEPRESSION EXPECTED TO BECOME A TROPICAL STORM TONIGHT OR ON 
SATURDAY...


SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...14.8N 71.5W
ABOUT 410 MI...660 KM ESE OF KINGSTON JAMAICA
ABOUT 720 MI...1160 KM ESE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Cayman Islands

A Tropical Storm Watch is in effect for...
* Jamaica

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Tropical Depression Nine was
located near latitude 14.8 North, longitude 71.5 West.  The
depression is moving toward the west-northwest near 15 mph (24
km/h).  A westward motion is expected to begin tonight and continue
through Saturday night, followed by a turn toward the northwest and
north-northwest on Sunday and Monday.  On the forecast track, the
center of the cyclone is forecast to move across the central
Caribbean Sea through Saturday, pass south of Jamaica on Saturday
night and Sunday, and approach the Cayman Islands on Sunday night
and early Monday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts.  Some slow strengthening is forecast during the next day or
so, and the depression is expected to become a tropical storm 
tonight or on Saturday.  More significant intensification is 
forecast on Sunday and Monday, and the system is forecast to become 
a hurricane by early Monday.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tropical Depression Nine can be found in the
Tropical Cyclone Discussion under AWIPS header MIATCDAT4 and WMO
header WTNT44 KNHC and on the web at
hurricanes.gov/text/MIATCDAT4.shtml.

WIND: Hurricane conditions are possible in the Cayman Islands by
early Monday, with tropical storm conditions possible by late
Sunday.  Tropical storm conditions are possible on Jamaica by
Sunday.

RAINFALL: Tropical Depression Nine is expected to produce the
following rainfall:

Southern Haiti and Southern Dominican Republic: 2 to 4 inches, with
local maximum up to 6 inches

Jamaica and the Cayman Islands: 4 to 8 inches, with local maximum up
to 12 inches

Western to central Cuba: 6 to 10 inches, with local maximum up to 14
inches.

Heavy rains may begin to affect South Florida on Monday. Limited
flash and urban flood impacts may be possible with this rainfall.

These rains may produce flash flooding and mudslides in areas of
higher terrain, particularly over Jamaica and Cuba.

STORM SURGE: Storm surge could raise water levels by as much as 1 to
3 feet above normal tide levels along the immediate coast in areas
of onshore winds in the Cayman Islands Sunday night into Monday.

Localized coastal flooding is possible along the coast of Jamaica in
areas of onshore winds on Sunday.

SURF: Swells generated by this system will begin affecting Jamaica,
the Cayman Islands, and Cuba over the next several days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.

$$
Forecaster Berg

