
ZCZC MIATCPAT4 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Ian Advisory Number   4
NWS National Hurricane Center Miami FL       AL092022
1100 PM EDT Fri Sep 23 2022

...TROPICAL STORM IAN FORMS OVER THE CENTRAL CARIBBEAN SEA...
...HURRICANE CONDITIONS POSSIBLE IN THE CAYMAN ISLANDS EARLY 
MONDAY...


SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.8N 72.0W
ABOUT 385 MI...625 KM SE OF KINGSTON JAMAICA
ABOUT 680 MI...1095 KM ESE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Cayman Islands

A Tropical Storm Watch is in effect for...
* Jamaica

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in western and central Cuba should monitor the progress
of Ian.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Tropical Storm Ian was
located near latitude 14.8 North, longitude 72.0 West.  Ian is 
moving toward the west-northwest near 12 mph (19 km/h).  A westward 
or west-northwestward motion is expected through early Sunday.  A 
turn toward the northwest is forecast late Sunday, followed by a 
north-northwestward turn by late Monday.  On the forecast track, the
center of Ian is forecast to move across the central Caribbean Sea 
through Saturday, pass southwest of Jamaica on Sunday, and pass 
near or over the Cayman Islands Sunday night and early Monday.  Ian 
will then approach western Cuba on Monday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Strengthening is forecast during the next few days, and Ian is 
expected to become a hurricane Sunday night.

Tropical-storm-force winds extend outward up to 35 miles (55 km)
from the center.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ian can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC and on the
web at hurricanes.gov/text/MIATCDAT4.shtml.

WIND: Hurricane conditions are possible in the Cayman Islands by
early Monday, with tropical storm conditions possible by Sunday
night.  Tropical storm conditions are possible on Jamaica on Sunday.

RAINFALL: Ian is expected to produce the following rainfall:

Southern Haiti and Southern Dominican Republic: 2 to 4 inches, with
local maximum up to 6 inches

Jamaica and the Cayman Islands: 4 to 8 inches, with local maximum up
to 12 inches

Western to central Cuba: 6 to 10 inches, with local maximum up to 14
inches

These rains may produce flash flooding and mudslides in areas of
higher terrain, particularly over Jamaica and Cuba.

Florida Keys and South Florida: Heavy rains begin as early as
Monday. Limited flash and urban flooding is possible with this
rainfall.

STORM SURGE: Storm surge could raise water levels by as much as 1 to
3 feet above normal tide levels along the immediate coast in areas
of onshore winds in the Cayman Islands Sunday night into Monday.

Localized coastal flooding is possible along the coast of Jamaica in
areas of onshore winds on Sunday.

SURF: Swells generated by Ian will begin affecting Jamaica, the
Cayman Islands, and Cuba over the next several days. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.

$$
Forecaster Berg

NNNN
