

000
WTNT34 KNHC 240852
TCPAT4

BULLETIN
Tropical Storm Ian Advisory Number   5
NWS National Hurricane Center Miami FL       AL092022
500 AM EDT Sat Sep 24 2022

...IAN STRENGTHENS WHILE MOVING WESTWARD OVER THE CENTRAL
CARIBBEAN...
...HURRICANE CONDITIONS POSSIBLE IN THE CAYMAN ISLANDS EARLY
MONDAY...


SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...14.7N 73.5W
ABOUT 315 MI...510 KM SE OF KINGSTON JAMAICA
ABOUT 600 MI...965 KM ESE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Cayman Islands

A Tropical Storm Watch is in effect for...
* Jamaica

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests in western and central Cuba should monitor the progress
of Ian.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Tropical Storm Ian was
located near latitude 14.7 North, longitude 73.5 West. Ian is moving
toward the west near 14 mph (22 km/h).  A westward to 
west-northwestward motion is expected through early Sunday.  A
turn toward the northwest is forecast late Sunday, followed by a
north-northwestward turn by late Monday.  On the forecast track,
the center of Ian is forecast to move across the central Caribbean
Sea today, pass southwest of Jamaica on Sunday, and pass near or
over the Cayman Islands Sunday night and early Monday.  Ian will
then approach western Cuba on Monday.

Maximum sustained winds have increased to near 45 mph (75 km/h) 
with higher gusts. Additional strengthening is forecast during the 
next few days, and Ian is expected to become a hurricane late 
Sunday or Sunday night.

Tropical-storm-force winds extend outward up to 45 miles (75 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ian can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC and on the
web at hurricanes.gov/text/MIATCDAT4.shtml.

WIND: Hurricane conditions are possible in the Cayman Islands by
early Monday, with tropical storm conditions possible by Sunday
night.  Tropical storm conditions are possible on Jamaica on Sunday.

RAINFALL: Ian is expected to produce the following rainfall:

Southern Haiti and Southern Dominican Republic: 2 to 4 inches, with
local maximum up to 6 inches

Jamaica and the Cayman Islands: 4 to 8 inches, with local maximum up
to 12 inches

Western to central Cuba: 6 to 10 inches, with local maximum up to 14
inches

These rains may produce flash flooding and mudslides in areas of
higher terrain, particularly over Jamaica and Cuba.

Florida Keys and South Florida: Heavy rains could begin as early as
Monday. Limited flash and urban flooding is possible with this
rainfall.

STORM SURGE: Storm surge could raise water levels by as much as 1 to
3 feet above normal tide levels along the immediate coast in areas
of onshore winds in the Cayman Islands Sunday night into Monday.

Localized coastal flooding is possible along the coast of Jamaica in
areas of onshore winds on Sunday.

SURF: Swells generated by Ian will begin affecting Jamaica, the
Cayman Islands, and Cuba over the next several days. These swells
are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.

$$
Forecaster Brown

