

238 
WTNT34 KNHC 010251
TCPAT4

BULLETIN
Post-Tropical Cyclone Ian Advisory Number  34
NWS National Hurricane Center Miami FL       AL092022
1100 PM EDT Fri Sep 30 2022

...HEAVY RAIN, FLASH FLOODING, AND GUSTY WINDS CONTINUE AS IAN MOVES
INLAND OVER NORTH CAROLINA...


SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...35.3N 79.5W
ABOUT 60 MI...95 KM SSE OF GREENSBORO NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...N OR 350 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

All Tropical Storm and Storm Surge Watches and Warnings have been
discontinued.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.

For storm information specific to your area, including possible
inland watches and warnings, please monitor products issued by your
local National Weather Service forecast office.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the center of Post-Tropical Cyclone Ian 
was located near latitude 35.3 North, longitude 79.5 West. The 
post-tropical cyclone is moving toward the north near 15 mph (24 
km/h). This general motion with a decrease in forward speed is 
expected through Saturday as Ian moves farther inland across central 
North Carolina and Virginia.

Maximum sustained winds have decreased to near 50 mph (85 km/h) with 
higher gusts. These winds are occurring over water off the Carolina 
coast.  Ian is forecast to weaken through Saturday and dissipate by 
early Sunday.

Tropical-storm-force winds extend outward up to 195 miles (315 km)
from the center.

The estimated minimum central pressure is 994 mb (29.36 inches) 
based on surface observations.


HAZARDS AFFECTING LAND
----------------------
Key messages for Ian can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC and on the
web at hurricanes.gov/text/MIATCDAT4.shtml.

STORM SURGE: Surge related flooding will continue to recede along
portions of the North Carolina coast, including the Pamlico Sound
and Neuse River as well as the Albemarle Sound. For information
specific to your area, please see products issued by your local
National Weather forecast office.

WIND:  Wind gusts to tropical storm force are expected to continue
over portions of North Carolina and South Carolina overnight as Ian
moves farther inland.

RAINFALL: Ian is expected to produce 3 to 6 inches, with local
maxima of 8 inches across portions of North Carolina, West Virginia,
and the southern Mid-Atlantic states.

Major to record river flooding will continue across central Florida
through next week.  Considerable flash, urban and small stream
flooding is possible across portions of North Carolina and southern
Virginia tonight into early Saturday, with minor river flooding
possible over Coastal Carolinas. Limited flooding is possible across
portions of the southern Mid-Atlantic this weekend.

TORNADOES:  A brief tornado remains possible through early Saturday
morning across far southeast Virginia and the southern Delmarva
Peninsula.

SURF:  Swells generated by Ian and a nearby frontal system are
affecting the east coast of Florida, Georgia, the Carolinas, and the
northwestern Bahamas. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.

$$
Forecaster Reinhart


