

000
WTNT34 KNHC 010840
TCPAT4

BULLETIN
Post-Tropical Cyclone Ian Advisory Number  35
NWS National Hurricane Center Miami FL       AL092022
500 AM EDT Sat Oct 01 2022

...IAN'S HEAVY RAINS CONTINUE ACROSS THE CENTRAL APPALACHIANS AND
MID-ATLANTIC...


SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...35.7N 79.8W
ABOUT 30 MI...45 KM S OF GREENSBORO NORTH CAROLINA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Post-Tropical Cyclone Ian
was located near latitude 35.7 North, longitude 79.8 West.  The
post-tropical cyclone is moving toward the north-northwest near 12
mph (19 km/h).  A turn toward the north with a decrease in forward 
speed is expected later today.  On the forecast track, the center 
of Ian is expected to move northward across central North Carolina 
this morning and reach south-central Virginia by this afternoon.

Maximum sustained winds have decreased to near 35 mph (55 km/h) 
with higher gusts.  These winds are occurring over the waters east 
of North Carolina and Virginia.  Additional weakening is expected, 
and Ian is forecast to dissipate over south-central Virginia by 
tonight.

The estimated minimum central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ian can be found in the Tropical Cyclone Discussion
under AWIPS header MIATCDAT4 and WMO header WTNT44 KNHC and on the
web at hurricanes.gov/text/MIATCDAT4.shtml.

WIND:  Gusty winds are expected to continue across portions of the
central and southern Appalachians through this morning.

RAINFALL:  Ian is expected to produce 2 to 4 inches with local
maxima of 6 inches across portions of the Central Appalachians and
coastal Mid-Atlantic.

Major to record river flooding will continue across central Florida
through next week.  Limited flash, urban and small stream flooding
is possible across the central Appalachians and the southern
Mid-Atlantic this weekend, with minor river flooding expected over
the coastal Carolinas.

SURF:  Swells generated by Ian are affecting the coast of the
southeastern United States and the northwestern Bahamas but should
gradually subside over the weekend.  These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane
Center on this system.  Future information on Ian can be found in 
Public Advisories issued by the Weather Prediction Center beginning 
at 11 AM EDT, under AWIPS header TCPAT4, WMO header WTNT34 KWNH, 
and on the web at http://www.wpc.ncep.noaa.gov. 

$$
Forecaster Berg

