

461 
WTNT35 KNHC 302332
TCPAT5

BULLETIN
Potential Tropical Cyclone Fifteen Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       AL152022
800 PM EDT Sun Oct 30 2022

...DISTURBANCE MOVING WEST-NORTHWESTWARD ACROSS THE CENTRAL 
CARIBBEAN SEA...
...NOAA HURRICANE HUNTER AIRCRAFT ENROUTE TO INVESTIGATE...


SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...15.8N 74.1W
ABOUT 230 MI...370 KM SE OF KINGSTON JAMAICA
ABOUT 535 MI...860 KM ESE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Jamaica
* Grand Cayman Island

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of Central America, especially
Belize, should monitor the progress of this system. Additional
watches or warnings will likely be required early this week.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the disturbance was centered near latitude
15.8 North, longitude 74.1 West. The system is moving toward the
west-northwest near 10 mph (17 km/h) and this motion is expected to
continue over the next several days with a gradual turn to the west
by Tuesday night.

Maximum sustained winds are near 40 mph (65 km/h) with higher
gusts. Strengthening is forecast during the next 48 hours, and the
system is expected to become a tropical storm tonight. It could
be near hurricane intensity by Tuesday night.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 5 days...high...90 percent.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Tropical storm conditions are possible within the watch
area in Jamaica beginning late Monday and are possible on Grand
Cayman Island on Tuesday.

RAINFALL:  Through Wednesday afternoon, the system is expected to 
produce rainfall amounts of 1 inch, with local amounts to 2 inches 
across portions of the U.S. Virgin Islands, Puerto Rico, Hispaniola, 
the Cayman Islands, northern Honduras, eastern Nicaragua, and 
Belize.  For Jamaica, rainfall amounts of 2 inches with local 
amounts of 4 inches are expected. This degree of rainfall could lead 
to flash flooding.

SURF:  Swells generated by the system are expected to affect
Jamaica and the Cayman Islands during the next couple of days.
These swells could cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.

$$
Forecaster Beven


