

829 
WTNT35 KNHC 310234
TCPAT5

BULLETIN
Potential Tropical Cyclone Fifteen Advisory Number   2
NWS National Hurricane Center Miami FL       AL152022
1100 PM EDT Sun Oct 30 2022

...NOAA HURRICANE HUNTER AIRCRAFT REPORTS LITTLE CHANGE IN THE
DISTURBANCE...


SUMMARY OF 1100 PM EDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.8N 74.9W
ABOUT 195 MI...315 KM SE OF KINGSTON JAMAICA
ABOUT 480 MI...770 KM ESE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Jamaica
* Grand Cayman Island

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of Central America, especially
Belize and the Yucatan Peninsula of Mexico, should monitor the
progress of this system. Additional watches or warnings will likely
be required early this week.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM EDT (0300 UTC), the disturbance was centered near
latitude 15.8 North, longitude 74.9 West. The system is moving
toward the west near 12 mph (19 km/h) and a westward to 
west-northwestward motion is expected during the next several days.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
Slow strengthening is expected through Monday, and the system could 
become a tropical storm later tonight or on Monday.  A faster rate 
of strengthening is expected starting Monday night, and the system 
could be near hurricane strength Tuesday night or Wednesday.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 5 days...high...90 percent.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
mainly to the northeast of the center.

The minimum central pressure estimated from NOAA Hurricane Hunter 
aircraft data is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Tropical storm conditions are possible within the watch
area in Jamaica beginning Monday afternoon and are possible on Grand
Cayman Island on Tuesday.

RAINFALL:  Through Wednesday evening, the system is expected to
produce rainfall amounts of 1 inch, with local amounts to 2 inches
across portions of the U.S. Virgin Islands, Puerto Rico, Hispaniola,
the Cayman Islands, northern Honduras, eastern Nicaragua, and
Belize.  For Jamaica, rainfall amounts of 2 inches with local
amounts of 4 inches are expected.  This degree of rainfall could
lead to flash flooding.

SURF:  Swells generated by the system are expected to affect
Jamaica and the Cayman Islands during the next couple of days.
These swells could cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM EDT.
Next complete advisory at 500 AM EDT.

$$
Forecaster Beven


