

483 
WTNT35 KNHC 310842
TCPAT5

BULLETIN
Potential Tropical Cyclone Fifteen Advisory Number   3
NWS National Hurricane Center Miami FL       AL152022
500 AM EDT Mon Oct 31 2022

...DISTURBANCE LIKELY TO BEGIN STRENGTHENING LATER TODAY...


SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...15.8N 76.1W
ABOUT 160 MI...255 KM SSE OF KINGSTON JAMAICA
ABOUT 415 MI...665 KM SE OF GRAND CAYMAN
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Jamaica
* Grand Cayman Island

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of Central America, especially
Belize and the Yucatan Peninsula of Mexico, should monitor the
progress of this system. Additional watches or warnings will likely
be required early this week.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the disturbance was centered near latitude
15.8 North, longitude 76.1 West.  The system is moving toward the
west near 12 mph (19 km/h), and a westward to west-northwestward
motion is expected over the next few days.  On the forecast track, 
the center will pass south of Jamaica and the Cayman Islands today 
and Tuesday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
The system is expected to become a tropical storm later today.  
Strengthening is forecast during the next couple of days and 
the system could be near hurricane strength by Wednesday.
* Formation chance through 48 hours...high...90 percent.
* Formation chance through 5 days...high...90 percent.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Tropical storm conditions are possible within the watch
area in Jamaica beginning today and are possible on Grand
Cayman Island on Tuesday.

RAINFALL: Through Thursday morning, the system is expected to
produce rainfall amounts of 1 inch, with local amounts to 2 inches
across portions of Hispaniola, the Cayman Islands, northern
Honduras, and eastern Nicaragua.  For Jamaica and Belize, rainfall
amounts of 2 to 4 inches are expected, with localized totals of 6
inches in Belize.  This rainfall could lead to flash flooding.

SURF:  Swells generated by the system are expected to affect
Jamaica and the Cayman Islands during the next couple of days.
These swells could cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM EDT.
Next complete advisory at 1100 AM EDT.

$$
Forecaster Pasch


