
ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Lisa Intermediate Advisory Number 5A
NWS National Hurricane Center Miami FL       AL152022
800 PM EDT Mon Oct 31 2022

...LISA FORECAST TO STRENGTHEN AS IT APPROACHES CENTRAL AMERICA...


SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...15.5N 78.9W
ABOUT 305 MI...490 KM SSE OF GRAND CAYMAN
ABOUT 630 MI...1015 KM ESE OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 14 MPH...22 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bay Islands
* Belize coast from north of Puerto Barrios to south of Chetumal

A Tropical Storm Warning is in effect for...
* Bay Islands

A Tropical Storm Watch is in effect for...
* Jamaica
* Entire north coast of Honduras
* Guatemala from border with Honduras to Puerto Barrios
* Mexico from Chetumal to Punta Herrero.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Tropical Storm Lisa was
located near latitude 15.5 North, longitude 78.9 West. Lisa is
moving toward the west near 14 mph (22 km/h), and a westward to
west-northwestward motion is expected over the next few days. On
the forecast track, the center will pass south of Jamaica tonight,
south of the Cayman Islands on Tuesday, then move near or over the 
Bay Islands of Honduras early on Wednesday and approach Belize 
later on Wednesday.

Maximum sustained winds remain near 45 mph (75 km/h) with higher
gusts. Slow strengthening is expected, and Lisa is forecast to 
become a hurricane on Wednesday over the northwestern Caribbean Sea.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
east of the center.

The estimated minimum central pressure is 1002 mb (29.59 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are possible in the Bay Islands of
Honduras beginning early Wednesday and are possible along the coast
of Belize Wednesday afternoon. Tropical storm conditions are
possible on Jamaica tonight. Tropical storm conditions are possible
on the coast of Honduras Tuesday night through Wednesday. Tropical 
storm conditions are possible in the Tropical Storm Watch area in 
Mexico, Honduras, and Guatemala Wednesday afternoon.

RAINFALL: Through Thursday evening, Lisa is expected to produce
rainfall amounts of:

* 3 to 5 inches with local amounts to 8 inches across portions
of Belize and the Bay Islands of Honduras.
* 2 to 4 inches with local amounts to 6 inches across portions
of Northern Honduras, Jamaica, Guatemala and the eastern Yucatan
peninsula.
* 1 inch with local amounts to 2 inches across portions of the
Cayman Islands, eastern Nicaragua.

This rainfall could produce flash floods from northern Honduras
northward to the eastern Yucatan Peninsula.

STORM SURGE:  A storm surge could raise water levels by as much as 3
to 5 feet above normal tide levels along the immediate coast of
Belize in areas of onshore winds and 1 to 3 feet for the Bay Islands
of Honduras. Near the coast, the surge will be accompanied by large
and damaging waves.

SURF:  Swells generated by Lisa are expected to affect Jamaica and
the Cayman Islands during the next day or so, and will begin to
affect Central America on Tuesday. These swells could cause life-
threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.

$$
Forecaster Cangialosi

NNNN
