

000
WTNT35 KNHC 010545
TCPAT5

BULLETIN
Tropical Storm Lisa Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       AL152022
200 AM EDT Tue Nov 01 2022

...LISA EXPECTED TO STRENGTHEN AS IT APPROACHES CENTRAL AMERICA...


SUMMARY OF 200 AM EDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...15.8N 79.8W
ABOUT 260 MI...415 KM SSE OF GRAND CAYMAN
ABOUT 570 MI...915 KM E OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bay Islands
* Belize coast from north of Puerto Barrios to south of Chetumal

A Tropical Storm Warning is in effect for...
* Bay Islands
* Honduras from the border with Nicaragua to Punta Castilla

A Tropical Storm Watch is in effect for...
* Coast of Honduras from west of Punta Castilla westward to the 
Guatemala border
* Guatemala from border with Honduras to Puerto Barrios
* Mexico from Chetumal to Punta Herrero.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM EDT (0600 UTC), the center of Tropical Storm Lisa was
located near latitude 15.8 North, longitude 79.8 West. Lisa is
moving toward the west near 12 mph (19 km/h) and this motion is
expected to continue during the next few days. On the forecast
track, the center will pass south of the Cayman Islands today,
move near or over the Bay Islands of Honduras early on Wednesday,
and approach Belize later on Wednesday.

Data from an Air Force Reserve reconnaissance aircraft indicate that 
the maximum sustained winds are near 45 mph (75 km/h) with higher
gusts. Gradual strengthening is expected, and Lisa is forecast to
become a hurricane by early Wednesday over the northwestern
Caribbean Sea.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are possible in the Bay Islands of
Honduras beginning early Wednesday and are possible along the coast
of Belize Wednesday afternoon. Tropical storm conditions are 
expected along the northeastern coast of Honduras within the 
Tropical Storm Warning area tonight and Wednesday.  Tropical storm 
conditions are possible in the Tropical Storm Watch area in Mexico, 
Honduras, and Guatemala Wednesday afternoon.

RAINFALL: Through Thursday evening, Lisa is expected to produce
rainfall amounts of:

* 3 to 5 inches with local amounts to 8 inches across portions
of Belize and the Bay Islands of Honduras.
* 2 to 4 inches with local amounts to 6 inches across portions
of Northern Honduras, Jamaica, Guatemala and the eastern Yucatan
peninsula.
* 1 inch with local amounts to 2 inches across portions of the
Cayman Islands, eastern Nicaragua.

This rainfall could produce flash floods from northern Honduras
northward to the eastern Yucatan Peninsula.

STORM SURGE:  A storm surge could raise water levels by as much as 3
to 5 feet above normal tide levels along the immediate coast of
Belize in areas of onshore winds and 1 to 3 feet for the Bay Islands
of Honduras. Near the coast, the surge will be accompanied by large
and damaging waves.

SURF:  Swells generated by Lisa are expected to affect Jamaica and
the Cayman Islands during the next day or so, and will begin to
affect Central America later today. These swells could 
cause life-threatening surf and rip current conditions. Please 
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM EDT.

$$
Forecaster Brown

