

000
WTNT35 KNHC 012350
TCPAT5

BULLETIN
Tropical Storm Lisa Intermediate Advisory Number 9A
NWS National Hurricane Center Miami FL       AL152022
800 PM EDT Tue Nov 01 2022

...AIR FORCE AND NOAA AIRCRAFT INVESTIGATING LISA THIS EVENING...


SUMMARY OF 800 PM EDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...16.7N 84.0W
ABOUT 175 MI...280 KM E OF ISLA ROATAN HONDURAS
ABOUT 285 MI...460 KM E OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.41 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Bay Islands
* North of Puerto Barrios to south of Chetumal

A Hurricane Watch is in effect for...
* Chetumal to Puerto Costa Maya, Mexico

A Tropical Storm Warning is in effect for...
* Entire north coast of Honduras
* North coast of Guatemala
* Chetumal to Punta Herrero, Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM EDT (0000 UTC), the center of Tropical Storm Lisa was
located near latitude 16.7 North, longitude 84.0 West. Lisa is
moving toward the west near 15 mph (24 km/h). This general motion
with some decrease in forward speed is forecast during the next
couple of days. On the forecast track, the center of Lisa will move
near or over the Bay Islands of Honduras early Wednesday, move near
Belize late on Wednesday and over southeastern Mexico on Thursday.

Maximum sustained winds remain near 65 mph (100 km/h) with higher 
gusts.  Further strengthening is expected, and Lisa is forecast to 
become a hurricane overnight over the northwestern Caribbean Sea and 
continue to intensify on Wednesday as it approaches Belize.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The minimum central pressure of 996 mb (29.41 inches) is based on 
data from an Air Force Reserve reconnaissance aircraft.


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected in the Bay Islands of
Honduras beginning early Wednesday and along the coast of Belize
Wednesday afternoon. Tropical storm conditions are expected to
begin along the northern coast of Honduras within the Tropical
Storm Warning area tonight and in Guatemala and Yucatan on
Wednesday. Hurricane conditions are possible in eastern Yucatan on
Wednesday afternoon.

RAINFALL: Through Thursday evening, Lisa is expected to produce
rainfall amounts of:

* 4 to 6 inches with local amounts to 10 inches across Belize, the
Bay Islands of Honduras, northern Guatemala and the southeast
portion of the Mexican state of Chiapas.
* 2 to 4 inches with local amounts to 6 inches across the far
southeastern portion of the Yucatan Peninsula, Northern Honduras,
and central Guatemala
* 1 inch with local amounts to 2 inches across portions of the
Cayman Islands and eastern Nicaragua.

This rainfall could lead to flash flooding conditions primarily
across Belize into northern Guatemala, the southeast portion of the
Mexican state of Chiapas and the far southeast portion of the
Yucatan peninsula.

STORM SURGE:  A storm surge will likely raise water levels by as
much as 4 to 7 feet above normal tide levels along the immediate
coast of Belize in areas of onshore winds, with 2 to 4 feet
possible within the Hurricane Watch area in eastern Yucatan and 1
to 3 feet for the Bay Islands of Honduras. Near the coast, the
surge will be accompanied by large and damaging waves.

SURF:  Swells generated by Lisa are expected to affect Jamaica,
the Cayman Islands, and portions of Central America during the next 
couple of days. These swells could cause life-threatening surf and 
rip current conditions. Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM EDT.

$$
Forecaster Bucci/Cangialosi

