

000
WTNT35 KNHC 020838
TCPAT5

BULLETIN
Tropical Storm Lisa Advisory Number  11
NWS National Hurricane Center Miami FL       AL152022
400 AM CDT Wed Nov 02 2022

...LISA MOVING WESTWARD TOWARD THE COAST OF BELIZE...
...EXPECTED TO BECOME A HURRICANE IN THE NEXT SEVERAL HOURS...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...17.1N 86.0W
ABOUT 70 MI...110 KM NE OF ISLA ROATAN HONDURAS
ABOUT 150 MI...240 KM E OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Bay Islands, Honduras
* The coast of Belize
* Chetumal to Puerto Costa Maya, Mexico

A Tropical Storm Warning is in effect for...
* Entire north coast of Honduras
* North coast of Guatemala
* Puerto Costa Maya to Punta Allen, Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 24 hours.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Lisa was
located near latitude 17.1 North, longitude 86.0 West. Lisa is
moving toward the west near 15 mph (24 km/h).  This general motion
with some decrease in forward speed is forecast during the next
couple of days.  On the forecast track, the center of Lisa will move
near or north of the Bay Islands of Honduras this morning, make 
landfall in Belize later today, and then cross northern Guatemala 
into southeastern Mexico by Thursday.

Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts.  Strengthening is expected, and Lisa is forecast to become a 
hurricane during the next several hours over the northwestern 
Caribbean Sea and continue to intensify today as it approaches 
Belize.  Weakening is expected after the center makes landfall.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected in the Bay Islands of
Honduras in the next several hours and along the coast of Belize and
the southeastern Yucatan this afternoon. Tropical storm conditions
are expected to begin along the northern coast of Honduras within 
portions of the Tropical Storm Warning this morning and in 
Guatemala and Yucatan later today.

RAINFALL: Lisa is expected to produce rainfall amounts of:

4 to 6 inches with local amounts to 10 inches across Belize, the
Bay Islands of Honduras, northern Guatemala, the eastern portion of
the Mexican state of Chiapas, and the Mexican state of Tabasco.

2 to 4 inches with local amounts to 6 inches across the far
southeastern portion of the Yucatan Peninsula, northern Honduras,
and central Guatemala.

1 inch with local amounts to 2 inches across portions of the
Cayman Islands and eastern Nicaragua.

This rainfall could lead to flash flooding conditions, primarily
across Belize into northern Guatemala, the far southeast portion of
the Yucatan peninsula, the eastern portion of the Mexican state of
Chiapas, and the Mexican state of Tabasco.

STORM SURGE:  A storm surge will likely raise water levels by as
much as 4 to 7 feet above normal tide levels near and to the north
of where the center of Lisa crosses the coast of Belize and
extreme southeastern portions of the Yucatan Peninsula.  Elsewhere,
a storm surge of 2 to 4 feet is possible within the Tropical Storm
Warning area in eastern Yucatan and 1 to 3 feet for the Bay Islands
of Honduras. Near the coast, the surge will be accompanied by large
and damaging waves.

SURF:  Swells generated by Lisa are expected to affect Jamaica,
the Cayman Islands, and portions of Central America during the next
couple of days. These swells could cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Beven

