

000
WTNT35 KNHC 021145
TCPAT5

BULLETIN
Hurricane Lisa Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       AL152022
700 AM CDT Wed Nov 02 2022

...LISA BECOMES A HURRICANE WHILE HEADED FOR BELIZE...


SUMMARY OF 700 AM CDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...17.2N 86.7W
ABOUT 60 MI...100 KM N OF ISLA ROATAN HONDURAS
ABOUT 100 MI...165 KM ESE OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Bay Islands, Honduras
* The coast of Belize
* Chetumal to Puerto Costa Maya, Mexico

A Tropical Storm Warning is in effect for...
* Entire north coast of Honduras
* North coast of Guatemala
* Puerto Costa Maya to Punta Allen, Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 24 hours.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 AM CDT (1200 UTC), the center of Hurricane Lisa was located 
near latitude 17.2 North, longitude 86.7 West.  Lisa is moving 
toward the west near 15 mph (24 km/h).  This general motion with 
some decrease in forward speed is forecast during the next couple 
of days.  On the forecast track, the center of Lisa will move just 
north of the Bay Islands of Honduras this morning, make landfall in 
Belize later today, and then cross northern Guatemala and move into 
southeastern Mexico by Thursday.

Reports from an Air Force Hurricane Hunter aircraft indicate that 
the maximum sustained winds have increased to near 75 mph (120 
km/h) with higher gusts.  Additional strengthening is forecast as 
Lisa approaches Belize.  Weakening is expected after the center 
makes landfall.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The minimum central pressure estimated from Air Force Hurricane 
Hunter aircraft observations is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected in the Bay Islands of
Honduras in the next several hours and along the coast of Belize and
the southeastern Yucatan peninsula this afternoon.  Tropical storm 
conditions are expected along the northern coast of Honduras within 
portions of the Tropical Storm Warning area this morning and in 
Guatemala and Yucatan later today.

RAINFALL: Lisa is expected to produce rainfall amounts of:

4 to 6 inches with local amounts to 10 inches across Belize, the
Bay Islands of Honduras, northern Guatemala, the eastern portion of
the Mexican state of Chiapas, and the Mexican state of Tabasco.

2 to 4 inches with local amounts to 6 inches across the far
southeastern portion of the Yucatan Peninsula, northern Honduras,
and central Guatemala.

1 inch with local amounts to 2 inches across portions of the
Cayman Islands and eastern Nicaragua.

This rainfall could lead to flash flooding conditions, primarily
across Belize into northern Guatemala, the far southeast portion of
the Yucatan peninsula, the eastern portion of the Mexican state of
Chiapas, and the Mexican state of Tabasco.

STORM SURGE:  A storm surge will likely raise water levels by as
much as 4 to 7 feet above normal tide levels near and to the north
of where the center of Lisa crosses the coast of Belize and
extreme southeastern portions of the Yucatan Peninsula.  Elsewhere,
a storm surge of 2 to 4 feet is possible within the Tropical Storm
Warning area in eastern Yucatan and 1 to 3 feet for the Bay Islands
of Honduras. Near the coast, the surge will be accompanied by large
and damaging waves.

SURF:  Swells generated by Lisa are expected to affect Jamaica,
the Cayman Islands, and portions of Central America during the next
couple of days. These swells could cause life-threatening surf and
rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 AM CDT.

$$
Forecaster Pasch

