

000
WTNT35 KNHC 022044
TCPAT5

BULLETIN
Hurricane Lisa Advisory Number  13
NWS National Hurricane Center Miami FL       AL152022
400 PM CDT Wed Nov 02 2022

...LISA ABOUT TO MAKE LANDFALL NEAR BELIZE CITY...


SUMMARY OF 400 PM CDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 88.2W
ABOUT 5 MI...10 KM S OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Honduras has discontinued the Tropical Storm
Warning for the Bay Islands and the north coast of Honduras.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* The coast of Belize
* Chetumal to Puerto Costa Maya, Mexico

A Tropical Storm Warning is in effect for...
* North coast of Guatemala
* Puerto Costa Maya to Punta Allen, Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 PM CDT (2100 UTC), the center of Hurricane Lisa was located
near latitude 17.4 North, longitude 88.2 West. Lisa is moving toward
the west near 12 mph (19 km/h).  This general motion is expected to 
continue for the next day or so, bringing the center of Lisa across 
Belize, northern Guatemala, and southeastern Mexico.  After that 
time, a turn to the northwest and a decrease in forward speed are 
expected as Lisa moves over the Bay of Campeche.

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts.  Rapid weakening will occur after the center of 
Lisa moves inland.

Hurricane-force winds extend outward up to 15 miles (30 km) from the
center and tropical-storm-force winds extend outward up to 70 miles
(110 km).  An observation in Belize City recently reported a wind 
gust of 70 mph (115 km/h).

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected along the coast of Belize
and the southeastern Yucatan peninsula during the next few hours.
Tropical storm conditions are expected through tonight in portions
of Guatemala and Yucatan in the Tropical Storm Warning areas.

RAINFALL: Lisa is expected to produce rainfall amounts of:

4 to 6 inches with local amounts to 10 inches across Belize,
northern Guatemala, the southern portion of the Mexican state of
Quintana Roo. southern Campeche, Tabasco, northern Chiapas, and far
eastern Veracruz.

2 to 4 inches with local amounts to 6 inches across the far
southeastern portion of the Yucatan Peninsula, the Bay Islands of
Honduras, central Guatemala and south-central Campeche.

This rainfall could lead to flash flooding conditions, primarily
across Belize into northern Guatemala, the far southeast portion of
the Yucatan peninsula, the southern portion of the Mexican state of
Campeche, Tabasco, northern Chiapas and far eastern Veracruz.

STORM SURGE:  A storm surge will likely raise water levels by as
much as 4 to 7 feet above normal tide levels near and to the north
of where the center of Lisa crosses the coast of Belize and
extreme southeastern portions of the Yucatan Peninsula.  Elsewhere,
a storm surge of 1 to 3 feet is possible within the Tropical Storm
Warning area in eastern Yucatan and up to 1 foot for the Bay
Islands of Honduras. Near the coast, the surge will be accompanied
by large and damaging waves.

SURF:  Swells generated by Lisa are expected to affect portions of
Central America during the next day or two. These swells could
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 PM CDT.
Next complete advisory at 1000 PM CDT.

$$
Forecaster Cangialosi

