

000
WTNT35 KNHC 022345
TCPAT5

BULLETIN
Hurricane Lisa Intermediate Advisory Number 13A
NWS National Hurricane Center Miami FL       AL152022
700 PM CDT Wed Nov 02 2022

...LISA BRINGING WIND, RAIN, AND STORM SURGE TO BELIZE...


SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...17.5N 88.5W
ABOUT 20 MI...30 KM W OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Guatemala has discontinued the Tropical Storm 
Warning for the north coast of Guatemala.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* The coast of Belize
* Chetumal to Puerto Costa Maya, Mexico

A Tropical Storm Warning is in effect for...
* Puerto Costa Maya to Punta Allen, Mexico

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Hurricane Lisa was located
inland near latitude 17.5 North, longitude 88.5 West. Lisa is 
moving toward the west near 12 mph (19 km/h).  This general motion 
is expected to continue for the next day or so, bringing the center 
of Lisa across Belize, northern Guatemala, and southeastern Mexico. 
After that time, a turn to the northwest and a decrease in forward 
speed are expected as Lisa moves over the Bay of Campeche.

Maximum sustained winds are estimated to be near 75 mph (120 km/h) 
with higher gusts.  Rapid weakening will continue while the center 
of Lisa moves farther inland.

Hurricane-force winds extend outward up to 15 miles (30 km) from
the center and tropical-storm-force winds extend outward up to 70
miles (110 km).  An observation station at the port of Belize City 
reported a sustained wind of 68 mph (109 km/h) with a wind gust of 
86 mph (138 km/h) within the past couple of hours.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are expected along the coast of Belize
and the southeastern Yucatan peninsula during the next hour or two.
Tropical storm conditions are expected through tonight in portions
of the southern Yucatan Peninsula in the Tropical Storm Warning 
area.

RAINFALL: Lisa is expected to produce rainfall amounts of:

4 to 6 inches with local amounts to 10 inches across Belize,
northern Guatemala, the southern portion of the Mexican state of
Quintana Roo. southern Campeche, Tabasco, northern Chiapas, and far
eastern Veracruz.

2 to 4 inches with local amounts to 6 inches across the far
southeastern portion of the Yucatan Peninsula, the Bay Islands of
Honduras, central Guatemala and south-central Campeche.

This rainfall could lead to flash flooding conditions, primarily
across Belize into northern Guatemala, the far southeast portion of
the Yucatan peninsula, the southern portion of the Mexican state of
Campeche, Tabasco, northern Chiapas and far eastern Veracruz.

STORM SURGE:  A storm surge will likely raise water levels by as
much as 4 to 7 feet above normal tide levels in areas of onshore 
flow near and to the north of the center of Lisa along the coast of 
Belize and extreme southeastern portions of the Yucatan Peninsula.  
Elsewhere, a storm surge of 1 to 3 feet is possible within the 
Tropical Storm Warning area in eastern Yucatan and up to 1 foot for 
the Bay Islands of Honduras. Near the coast, the surge will be 
accompanied by large and damaging waves.

SURF:  Swells generated by Lisa are expected to affect portions of
Central America during the next day or two. These swells could
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Bucci/Brown

