

000
WTNT35 KNHC 030249
TCPAT5

BULLETIN
Tropical Storm Lisa Advisory Number  14
NWS National Hurricane Center Miami FL       AL152022
1000 PM CDT Wed Nov 02 2022

...LISA BRINGING HEAVY RAIN AND GUSTY WINDS TO BELIZE,
NORTHERN GUATEMALA, AND SOUTHEASTERN MEXICO...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...17.6N 89.1W
ABOUT 60 MI...95 KM W OF BELIZE CITY
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.38 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has changed the Hurricane Warning to a
Tropical Storm Warning from Chetumal to Puerto Costa Maya, and
discontinued the Tropical Storm Warning north of Puerto Costa 
Maya.  

The government of Belize has changed the Hurricane Warning to a 
Tropical Storm Warning for the coast of Belize.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* The coast of Belize
* Chetumal to Puerto Costa Maya, Mexico

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests elsewhere in Central America and the Yucatan Peninsula of
Mexico should monitor the progress of Lisa.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Tropical Storm Lisa was
located inland near latitude 17.6 North, longitude 89.1 West. Lisa 
is moving toward the west near 12 mph (19 km/h). This general motion
is expected to continue for the next day or so, bringing the center
of Lisa across Belize, northern Guatemala, and southeastern Mexico.
After that time, a turn to the northwest and a decrease in forward
speed are expected as Lisa moves over the Bay of Campeche.

Maximum sustained winds have decreased to near 60 mph (95 km/h) 
with higher gusts. Rapid weakening will continue while the center
of Lisa moves farther inland.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.

The estimated minimum central pressure is 995 mb (29.38 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are expected to spread inland 
through tonight over portions of Belize, northern Guatemala, and 
the southern Yucatan Peninsula of Mexico. 

RAINFALL: Lisa is expected to produce rainfall amounts of:

4 to 6 inches with local amounts to 10 inches across Belize,
northern Guatemala, the southern portion of the Mexican state of
Quintana Roo, southern Campeche, Tabasco, northern Chiapas, and far
eastern Veracruz.

2 to 4 inches with local amounts to 6 inches across the far
southeastern portion of the Yucatan Peninsula, the Bay Islands of
Honduras, central Guatemala and south-central Campeche.

This rainfall could lead to flash flooding conditions, primarily
across Belize into northern Guatemala, the far southeast portion of
the Yucatan peninsula, the southern portion of the Mexican state of
Campeche, Tabasco, northern Chiapas and far eastern Veracruz.

STORM SURGE:  Water levels along the coast of Belize may remain 
elevated by as much as 1 to 3 feet above normal tide levels 
through the night in areas of onshore winds within the Tropical 
Storm Warning area.

SURF:  Swells generated by Lisa are expected to affect portions of
Central America during the next day or so. These swells could
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Bucci/Brown

