

000
WTNT33 KNHC 280853
TCPAT3

BULLETIN
Hurricane Franklin Advisory Number  31
NWS National Hurricane Center Miami FL       AL082023
500 AM EDT Mon Aug 28 2023

...FRANKLIN BECOMES THE FIRST MAJOR HURRICANE OF THE 2023
ATLANTIC HURRICANE SEASON...


SUMMARY OF 500 AM EDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...27.2N 70.8W
ABOUT 395 MI...635 KM N OF GRAND TURK ISLAND
ABOUT 505 MI...810 KM SW OF BERMUDA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...956 MB...28.23 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in Bermuda should monitor the progress of this system.
Watches will likely be required for Bermuda later today.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM EDT (0900 UTC), the center of Hurricane Franklin was
located near latitude 27.2 North, longitude 70.8 West. Franklin is
moving toward the north-northwest near 8 mph (13 km/h). A gradual
turn toward the north and north-northeast with a slightly faster
forward speed is expected during the next couple of days.

Maximum sustained winds have increased to near 115 mph (185 km/h) 
with higher gusts. This makes Franklin a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale. Some additional strengthening 
is forecast today, but gradual weakening is expected to begin by 
Tuesday afternoon. 

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).

The estimated minimum central pressure is 956 mb (28.23 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Franklin are beginning to affect Bermuda.
These swells are expected to spread toward the east coast of the
United States during the next couple of days, likely resulting in
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM EDT.

$$
Forecaster Papin

