

000
WTNT33 KNHC 282034
TCPAT3

BULLETIN
Hurricane Franklin Advisory Number  33
NWS National Hurricane Center Miami FL       AL082023
500 PM EDT Mon Aug 28 2023

...FRANKLIN REMAINS A POWERFUL MAJOR HURRICANE...
...LIFE-THREATENING SURF AND RIP CURRENTS ARE OCCURING ALONG THE
COAST OF THE SOUTHEAST UNITED STATES...


SUMMARY OF 500 PM EDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...28.5N 71.0W
ABOUT 485 MI...780 KM N OF GRAND TURK ISLAND
ABOUT 455 MI...730 KM SW OF BERMUDA
MAXIMUM SUSTAINED WINDS...145 MPH...230 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...937 MB...27.67 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM EDT (2100 UTC), the center of Hurricane Franklin was
located near latitude 28.5 North, longitude 71.0 West. Franklin is
moving toward the north near 9 mph (15 km/h). This northward to
north-northeastward motion with a slightly faster forward speed is
expected during the next few days.  On the forecast track, the
center of Franklin is expected to pass well to the west of Bermuda
on Wednesday.

Maximum sustained winds are near 145 mph (230 km/h) with higher
gusts.  Franklin is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Additional strengthening is possible,
but gradual weakening is expected to begin late Tuesday.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).

The estimated minimum central pressure is 937 mb (27.67 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells, life-threatening surf and rip currents generated by
Franklin are already affecting Bermuda and the coast of the
southeast United States. These conditions are expected to spread
northward along the east coast of the United States and Atlantic
Canada during the next couple of days.

WIND:  Tropical storm conditions are possible within the watch
area by Wednesday morning.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM EDT.
Next complete advisory at 1100 PM EDT.

$$
Forecaster Kelly/Brown

