

000
WTNT33 KNHC 290538
TCPAT3

BULLETIN
Hurricane Franklin Intermediate Advisory Number 34A
NWS National Hurricane Center Miami FL       AL082023
200 AM EDT Tue Aug 29 2023

...FRANKLIN REMAINS A POWERFUL CATEGORY 4 HURRICANE...
...LIFE-THREATENING SURF AND RIP CURRENTS ARE OCCURING ALONG THE
COAST OF THE SOUTHEAST UNITED STATES AND EXPECTED TO SPREAD 
NORTHWARD...


SUMMARY OF 200 AM EDT...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...29.8N 71.0W
ABOUT 405 MI...655 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...145 MPH...235 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...930 MB...27.46 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Bermuda

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM EDT (0600 UTC), the center of Hurricane Franklin was
located near latitude 29.8 North, longitude 71.0 West. Franklin is
moving toward the north near 9 mph (15 km/h). A north-northeastward
to northeastward motion with a faster forward speed is expected
during the next few days.  On the forecast track, the center of
Franklin is expected to pass well to the west of Bermuda on
Wednesday.

Maximum sustained winds are near 145 mph (235 km/h) with higher
gusts.  Franklin is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale. Steady weakening should begin later today.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).

The estimated minimum central pressure is 930 mb (27.46 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Life-threatening surf and rip currents generated by
Franklin are already affecting Bermuda and the coast of the
southeast United States. These conditions are expected to spread
northward along the east coast of the United States and Atlantic
Canada during the next couple of days.

WIND:  Tropical storm conditions are possible in Bermuda by
Wednesday morning.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM EDT.

$$
Forecaster Papin

