

000
WTNT33 KNHC 291746
TCPAT3

BULLETIN
Hurricane Franklin Intermediate Advisory Number 36A
NWS National Hurricane Center Miami FL       AL082023
200 PM EDT Tue Aug 29 2023

...LIFE-THREATENING SURF AND RIP CURRENTS ONGOING ALONG THE
EAST COAST OF THE UNITED STATES...


SUMMARY OF 200 PM EDT...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...31.0N 70.2W
ABOUT 330 MI...530 KM WSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...125 MPH...200 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...947 MB...27.97 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM EDT (1800 UTC), the center of Hurricane Franklin was
located near latitude 31.0 North, longitude 70.2 West. Franklin is
moving toward the north-northeast near 12 mph (19 km/h). A
north-northeastward to northeastward motion with a faster forward
speed is expected during the next few days. On the forecast track,
the center of Franklin is expected to pass to the northwest of
Bermuda on Wednesday.

Maximum sustained winds are near 125 mph (200 km/h) with higher
gusts.  Franklin is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Steady weakening is forecast during the next
several days, but Franklin will remain a hurricane through late this
week.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km). NOAA Buoy 41048 west of Bermuda recently reported a 
sustained wind of 43 mph (69 km/h) and a gust of 59 mph (95 km/h). 

The estimated minimum central pressure is 947 mb (27.97 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Life-threatening surf and rip currents generated by Franklin
are already affecting Bermuda and the east coast of the United
States. These conditions are expected to continue during the next
several days.

WIND:  Tropical storm conditions are expected to reach Bermuda by
Wednesday morning, making outside preparations difficult or
dangerous.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM EDT.

$$
Forecaster Kelly

