

000
WTNT33 KNHC 300255
TCPAT3

BULLETIN
Hurricane Franklin Advisory Number  38
NWS National Hurricane Center Miami FL       AL082023
1100 PM AST Tue Aug 29 2023

...TROPICAL STORM CONDITIONS EXPECTED IN BERMUDA
BEGINNING TOMORROW MORNING...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...32.3N 69.0W
ABOUT 245 MI...395 KM W OF BERMUDA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...NE OR 40 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...953 MB...28.15 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 12
hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Franklin was 
located near latitude 32.3 North, longitude 69.0 West. Franklin is 
moving toward the northeast near 12 mph (19 km/h), and this motion 
with a faster forward speed is expected through Wednesday. On 
Thursday, Franklin is expected to turn to the east-northeast and 
continue to increase in forward speed.  On the forecast track, the 
center of Franklin is expected to pass to the northwest of Bermuda 
on Wednesday.

Maximum sustained winds have decreased to near 115 mph (185 km/h) 
with higher gusts.  Franklin is a category 3 hurricane on the 
Saffir-Simpson Hurricane Wind Scale.  Steady weakening is forecast 
during the next several days.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 150 miles
(240 km).

The estimated minimum central pressure is 953 mb (28.15 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Franklin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC. 

SURF:  Life-threatening surf and rip currents generated by Franklin
are already affecting Bermuda and the east coast of the United
States. These conditions are expected to continue during the next
several days.

WIND:  Tropical storm conditions are expected to reach Bermuda by
Wednesday morning, making outside preparations difficult or
dangerous.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Bucci

