

992 
WTNT33 KNHC 300546
TCPAT3

BULLETIN
Hurricane Franklin Intermediate Advisory Number 38A
NWS National Hurricane Center Miami FL       AL082023
200 AM AST Wed Aug 30 2023

...TROPICAL STORM CONDITIONS EXPECTED IN BERMUDA
BEGINNING LATER TODAY...
...LIFE-THREATENING SURF AND RIP CURRENTS ONGOING ALONG THE EAST 
COAST OF THE UNITED STATES...


SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...32.6N 68.7W
ABOUT 230 MI...370 KM W OF BERMUDA
MAXIMUM SUSTAINED WINDS...115 MPH...185 KM/H
PRESENT MOVEMENT...NE OR 40 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...953 MB...28.15 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case beginning 
later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Hurricane Franklin was 
located near latitude 32.6 North, longitude 68.7 West. Franklin is 
moving toward the northeast near 12 mph (19 km/h), and this motion 
with a faster forward speed is expected through today. On Thursday, 
Franklin is forecast to turn toward the east-northeast at a faster 
forward speed.  On the forecast track, the center of Franklin is 
expected to pass to the northwest of Bermuda later today. 

Maximum sustained winds are near 115 mph (185 km/h) with higher 
gusts.  Franklin is a category 3 hurricane on the Saffir-Simpson 
Hurricane Wind Scale.  Steady weakening is forecast over the next 
several days.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 150
miles (240 km).

The estimated minimum central pressure is 953 mb (28.15 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Franklin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3 and WMO header WTNT43 KNHC.

SURF:  Life-threatening surf and rip currents generated by Franklin
are already affecting Bermuda and the east coast of the United
States. These conditions are expected to continue during the next
several days.

WIND:  Tropical storm conditions are expected to reach Bermuda this 
morning, making outside preparations difficult or dangerous.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Papin


