

565 
WTNT33 KNHC 300845
TCPAT3

BULLETIN
Hurricane Franklin Advisory Number  39
NWS National Hurricane Center Miami FL       AL082023
500 AM AST Wed Aug 30 2023

...FRANKLIN IS A LARGE HURRICANE AND IS PRODUCING SIGNIFICANT SURF
AND RIP CURRENTS ALONG THE EASTERN SEABOARD...
...TROPICAL STORM CONDITIONS ARE EXPECTED IN BERMUDA LATER TODAY...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...33.0N 68.2W
ABOUT 205 MI...325 KM WNW OF BERMUDA
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...956 MB...28.23 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case beginning
later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Franklin was 
located near latitude 33.0 North, longitude 68.2 West. Franklin is 
moving toward the northeast near 13 mph (20 km/h) and this motion is 
expected to continue today. On Thursday, Franklin is forecast to 
turn toward the east-northeast.  On the forecast track, the center 
of Franklin is expected to pass to the northwest of Bermuda later 
today.

Maximum sustained winds have decreased to near 110 mph (175 km/h)
with higher gusts. Additional weakening is forecast over the next
several days.

Hurricane-force winds extend outward up to 45 miles (75 km) from the
center and tropical-storm-force winds extend outward up to 160 miles
(260 km).

The estimated minimum central pressure is 956 mb (28.23 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Franklin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT3.shtml.

SURF:  Life-threatening surf and rip currents generated by Franklin
are already affecting Bermuda and the east coast of the United
States. These conditions are expected to continue during the next
several days.

WIND:  Tropical storm conditions are expected to reach Bermuda this
morning, making outside preparations difficult or dangerous.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin


