

000
WTNT33 KNHC 301153
TCPAT3

BULLETIN
Hurricane Franklin Intermediate Advisory Number 39A
NWS National Hurricane Center Miami FL       AL082023
800 AM AST Wed Aug 30 2023

...LARGE FRANKLIN EXPECTED TO BRING TROPICAL STORM CONDITIONS TO 
BERMUDA LATER TODAY...
...DANGEROUS SURF AND RIP CURRENT CONDITIONS CONTINUE ALONG THE 
EASTERN SEABOARD...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...33.3N 67.6W
ABOUT 180 MI...290 KM WNW OF BERMUDA
MAXIMUM SUSTAINED WINDS...110 MPH...175 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...956 MB...28.23 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case beginning
later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the eye of Hurricane Franklin was located 
near latitude 33.3 North, longitude 67.6 West. Franklin is moving 
toward the northeast near 13 mph (20 km/h), and this motion is 
expected to continue today. On Thursday, Franklin is forecast to 
turn toward the east-northeast. On the forecast track, the center of 
Franklin is expected to pass to the northwest of Bermuda today.

Maximum sustained winds are near 110 mph (175 km/h) with higher 
gusts. Gradual weakening is forecast over the next several days.

Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 160
miles (260 km).

The estimated minimum central pressure is 956 mb (28.23 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Franklin can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT3, WMO header WTNT43 KNHC,
and on the web at hurricanes.gov/text/MIATCDAT3.shtml.

SURF:  Life-threatening surf and rip currents generated by Franklin 
are affecting Bermuda and the east coast of the United States. These 
conditions are expected to continue during the next couple of days.

WIND:  Tropical storm conditions are expected to reach Bermuda this 
morning, making outside preparations difficult or dangerous.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Reinhart

