

612 
WTPZ34 KNHC 201448
TCPEP4

BULLETIN
Tropical Storm Roslyn Advisory Number   3
NWS National Hurricane Center Miami FL       EP192022
1000 AM CDT Thu Oct 20 2022

...DEPRESSION BECOMES TROPICAL STORM ROSLYN...
...EXPECTED TO STRENGTHEN MORE AND PRODUCE HEAVY RAINS AND FLOODING
ALONG PORTIONS OF THE SOUTHWESTERN AND WEST-CENTRAL COAST OF
MEXICO...


SUMMARY OF 1000 AM CDT...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.2N 102.0W
ABOUT 175 MI...280 KM S OF ZIHUATANEJO MEXICO
ABOUT 305 MI...490 KM SSE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests along the coast of southwestern and west-central Mexico
should monitor the progress of this system.  Watches will likely be
required for portions of the coast later today.


DISCUSSION AND OUTLOOK
----------------------
At 1000 AM CDT (1500 UTC), the center of Tropical Storm Roslyn was
located near latitude 15.2 North, longitude 102.0 West. Roslyn is
moving toward the west near 6 mph (9 km/h), and this general motion 
is expected to continue today.  A turn toward the west-northwest 
and northwest is expected tonight and Friday, followed by a 
northward motion by Saturday night.  On the forecast track, the 
system is expected to move parallel to the southwestern coast of 
Mexico through Saturday and then pass near or over the west-central 
coast of Mexico Saturday night.

Maximum sustained winds have increased to near 40 mph (65 km/h) 
with higher gusts. Additional strengthening is forecast during the 
next few days, and Roslyn is expected to become a hurricane by late 
Friday or Friday night.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
RAINFALL:  Tropical Storm Roslyn outer rainbands may produce
rainfall totals of 1 to 3 inches along coastal areas of Guerrero
and Michoacán and 2 to 4 inches with maximum amounts of 6 inches
along coastal areas of Colima and Jalisco. This rainfall could
lead to flash flooding as well as possible landslides in areas of
rugged terrain.

Roslyn is then forecast to turn north and northeast this weekend
and may bring locally heavy rainfall to coastal areas of Nayarit
including Islas Marias, and southeastern Sinaloa. This rainfall
could lead to flash flooding and landslides in areas of rugged
terrain.

SURF:  Swells generated by Roslyn are affecting portions of the 
coast of southwestern Mexico and will spread northward to the coast 
of west-central Mexico by Friday.  These swells are likely to cause 
life-threatening surf and rip current conditions.  Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 400 PM CDT.

$$
Forecaster Beven


