

000
WTPZ34 KNHC 202342
TCPEP4

BULLETIN
Tropical Storm Roslyn Intermediate Advisory Number 4A
NWS National Hurricane Center Miami FL       EP192022
700 PM CDT Thu Oct 20 2022

...ROSLYN EXPECTED TO STRENGTHEN...
...TROPICAL STORM WATCH IN EFFECT FOR PORTIONS OF THE COAST OF 
SOUTHWESTERN MEXICO...


SUMMARY OF 700 PM CDT...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...15.6N 103.4W
ABOUT 245 MI...390 KM SSE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* The Pacific coast of Mexico from Manzanillo to Cabo Corrientes

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of southwestern and west-central 
Mexico and the Islas Marias should monitor the progress of this 
system. Additional watches or warnings will likely be required for 
portions of these areas later tonight or on Friday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 700 PM CDT (0000 UTC), the center of Tropical Storm Roslyn was 
located near latitude 15.6 North, longitude 103.4 West. Roslyn is 
moving toward the west near 7 mph (11 km/h). A turn toward the 
west-northwest and northwest is expected later tonight and Friday, 
followed by a north-northwestward and northward motion on Saturday 
and Saturday night. On the forecast track, Roslyn is expected to 
move parallel to the southwestern coast of Mexico through Saturday, 
then approach the west-central coast of Mexico on Saturday night and 
Sunday.

Maximum sustained winds are near 45 mph (75 km/h) with higher gusts. 
Strengthening is forecast during the next few days, and Roslyn is 
expected to become a hurricane by Friday night.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
mainly to the northeast of the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are possible in the watch area on
Saturday.

RAINFALL:  The outer rainbands of Roslyn may produce rainfall totals 
of 1 to 3 inches along coastal areas of Guerrero and Michoacán and 2 
to 4 inches with maximum amounts of 6 inches along coastal areas of 
Colima and Jalisco. Roslyn is also forecast to bring locally heavy 
rainfall to coastal areas of Nayarit including Islas Marias, and 
southeastern Sinaloa. This rainfall could lead to flash flooding and 
landslides in areas of rugged terrain.

SURF:  Swells generated by Roslyn are affecting portions of the
coast of southwestern Mexico and will spread northward to the coast
of west-central Mexico on Friday. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1000 PM CDT.

$$
Forecaster Reinhart

