

000
WTPZ34 KNHC 210242
TCPEP4

BULLETIN
Tropical Storm Roslyn Advisory Number   5
NWS National Hurricane Center Miami FL       EP192022
1000 PM CDT Thu Oct 20 2022

...ROSLYN STRENGTHENS...
...HURRICANE WATCHES ISSUED FOR PORTIONS OF THE COAST OF MEXICO...


SUMMARY OF 1000 PM CDT...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...15.7N 103.6W
ABOUT 230 MI...375 KM SSE OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Hurricane Watch for the
Pacific coast of Mexico from Playa Perula northward to San Blas.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* The Pacific coast of Mexico from Playa Perula to San Blas

A Tropical Storm Watch is in effect for...
* The Pacific coast of Mexico south of Playa Perula to Manzanillo

A Hurricane Watch means that hurricane conditions are possible
within the watch area. A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere along the coast of southwestern and west-central
Mexico and the Islas Marias should monitor the progress of this
system. Additional watches or warnings will likely be required for
portions of these areas on Friday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1000 PM CDT (0300 UTC), the center of Tropical Storm Roslyn was 
located near latitude 15.7 North, longitude 103.6 West. Roslyn is 
moving toward the west-northwest near 8 mph (13 km/h). A turn toward 
the northwest is expected on Friday, followed by a 
north-northwestward motion on Saturday and a northward motion 
Saturday night into Sunday. On the forecast track, Roslyn is 
expected to move parallel to the southwestern coast of Mexico 
through Saturday, then approach the west-central coast of Mexico on 
Saturday night and Sunday.

Maximum sustained winds have increased to near 50 mph (85 km/h) with 
higher gusts. Strengthening is forecast during the next couple of 
days or so, and Roslyn is expected to become a hurricane by late 
Friday.

Tropical-storm-force winds extend outward up to 60 miles (95 km)
from the center.

The estimated minimum central pressure is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
WIND: Hurricane conditions are possible within the hurricane watch
area along the coast of mainland Mexico by Saturday evening, with
tropical storm conditions possible on Saturday. Tropical storm
conditions are possible in the tropical storm watch area on
Saturday.

RAINFALL:  The outer rainbands of Roslyn may produce rainfall totals
of 1 to 3 inches along coastal areas of Guerrero and Michoacán and
2 to 4 inches with maximum amounts of 6 inches along coastal areas 
of Colima and Jalisco. Roslyn is also forecast to bring locally 
heavy rainfall to coastal areas of Nayarit including Islas Marias, 
and southeastern Sinaloa. This rainfall could lead to flash flooding 
and landslides in areas of rugged terrain.

SURF:  Swells generated by Roslyn are affecting portions of the
coast of southwestern Mexico and will spread northward to the coast
of west-central Mexico and the southern portion of the Baja
California peninsula through the weekend. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 100 AM CDT.
Next complete advisory at 400 AM CDT.

$$
Forecaster Reinhart

