

000
WTPZ34 KNHC 210838
TCPEP4

BULLETIN
Tropical Storm Roslyn Advisory Number   6
NWS National Hurricane Center Miami FL       EP192022
400 AM CDT Fri Oct 21 2022

...ROSLYN STILL STRENGTHENING AND EXPECTED TO BECOME A HURRICANE
TODAY...
...HURRICANE WARNING ISSUED FOR A PORTION OF THE COAST OF
WEST-CENTRAL MEXICO...


SUMMARY OF 400 AM CDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.2N 103.8W
ABOUT 195 MI...315 KM S OF MANZANILLO MEXICO
ABOUT 315 MI...510 KM SSE OF CABO CORRIENTES MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...998 MB...29.47 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Hurricane Warning from Playa
Perula to Cabo Corrientes and a Tropical Storm Warning south of
Playa Perula to Manzanillo.  A Hurricane Watch has also been issued
for Las Islas Marias and from San Blas to El Roblito.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Playa Perula to Cabo Corrientes

A Hurricane Watch is in effect for...
* North of Cabo Corrientes to El Roblito
* Las Islas Marias

A Tropical Storm Warnings is in effect for...
* South of Playa Perula to Manzanillo

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere along the coast of southwestern and west-central
Mexico should monitor the progress of Roslyn.  Additional watches
or warnings will likely be required for portions of these areas
later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 400 AM CDT (0900 UTC), the center of Tropical Storm Roslyn was
located near latitude 16.2 North, longitude 103.8 West.  Roslyn is
moving toward the west-northwest near 7 mph (11 km/h), and this 
general motion is expected to continue today.  A turn toward the 
northwest and north-northwest is forecast tonight and Saturday, 
followed by a northward and then north-northeastward motion 
Saturday night and Sunday.  On the forecast track, the center of 
Roslyn will move parallel to the southwestern coast of Mexico 
today and tonight, and pass near and make landfall along the coast 
of west-central Mexico Saturday night and Sunday.

Maximum sustained winds have increased to near 65 mph (100 km/h) 
with higher gusts.  Rapid strengthening is expected during the next 
day or so, and Roslyn is forecast to become a hurricane later 
today.  Roslyn is expected to still be a hurricane when it reaches 
the coast of west-central Mexico on Sunday.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.

The estimated minimum central pressure is 998 mb (29.47 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane conditions are expected to reach the coast
within the hurricane warning area by late Saturday.  Winds are
expected to first reach tropical storm strength by midday Saturday,
making outside preparations difficult or dangerous.  Preparations to
protect life and property should be rushed to completion.

Hurricane conditions are possible within the hurricane watch area
beginning Saturday night or early Sunday, with tropical storm
conditions possible by Saturday evening.

Tropical storm conditions are expected within the tropical storm
warning area on Saturday.

RAINFALL:  Roslyn is expected to produce the following rainfall
totals across coastal areas of southwestern and west-central
Mexico:

Guerrero and Michoacan: 1 to 3 inches
Colima and Jalisco: 2 to 4 inches with maximum amounts of 6 inches
Nayarit including Islas Marias and southeastern Sinaloa: 4 to 6
inches with maximum amounts of 8 inches

This rainfall could lead to flash flooding and landslides in areas
of rugged terrain.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the east of where the
center makes landfall.  Near the coast, the surge will be
accompanied by large and destructive waves.

SURF:  Swells generated by Roslyn are affecting portions of the
coast of southwestern Mexico and will spread northward to the coast
of west-central Mexico and the southern portion of the Baja
California peninsula through the weekend.  These swells are likely
to cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 700 AM CDT.
Next complete advisory at 1000 AM CDT.

$$
Forecaster Berg

