

000
WTPZ34 KNHC 222053
TCPEP4

BULLETIN
Hurricane Roslyn Advisory Number  12
NWS National Hurricane Center Miami FL       EP192022
300 PM MDT Sat Oct 22 2022

...AIR FORCE RESERVE HURRICANE HUNTER AIRCRAFT CONFIRMS THAT ROSLYN
IS A CATEGORY 4 HURRICANE...
...FORECAST TO REACH THE COAST OF WEST-CENTRAL MEXICO ON SUNDAY...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...19.0N 106.6W
ABOUT 115 MI...180 KM SSW OF CABO CORRIENTES MEXICO
ABOUT 150 MI...240 KM W OF MANZANILLO MEXICO
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...NNW OR 340 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...954 MB...28.17 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Government of Mexico has issued a Hurricane Warning for the
coast of Mexico from El Roblito to Escuinapa.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Playa Perula to Escuinapa
* Las Islas Marias

A Hurricane Watch is in effect for...
* North of Escuinapa to Mazatlan

A Tropical Storm Warning is in effect for...
* South of Playa Perula to Manzanillo
* North of Escuinapa to Mazatlan

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within the
next 24 hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Hurricane Roslyn was located
near latitude 19.0 North, longitude 106.6 West. Roslyn is moving
toward the north-northwest near 9 mph (15 km/h).  A turn toward the
north is expected during the next few hours, followed by a faster
motion toward the north-northeast on Sunday. On the forecast
track, the center of Roslyn will approach the coast of west-central
Mexico, likely making landfall along the coast of the Mexican state
of Nayarit Sunday morning.

Reports from an Air Force Reserve Hurricane Hunter aircraft
indicate that maximum sustained winds are near 130 mph (215 km/h)
with higher gusts.  Roslyn is a category 4 hurricane on the
Saffir-Simpson Hurricane Wind Scale.  Although some weakening
could occur tonight, Roslyn is expected to at or near major
hurricane strength when it makes landfall on Sunday.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The minimum central pressure reported by the Hurricane Hunter
aircraft is 954 mb (28.17 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane conditions are expected to reach the coast within
the hurricane warning area by tonight and early Sunday.  Winds
are expected to first reach tropical storm strength during the
next several hours, making outside preparations difficult or
dangerous. Preparations to protect life and property should be
rushed to completion.

Hurricane conditions are possible within the hurricane watch area
on Sunday.

Tropical storm conditions are expected within the tropical storm
warning area south of Playa Perula this afternoon or tonight, and
within the warning area north of El Roblito on Sunday.

RAINFALL: Roslyn is expected to produce the following rainfall
totals across coastal areas of southwestern and west-central
Mexico:

Michoacán and the lower coast of Colima: 1 to 3 inches

Jalisco:  4 to 8 inches with maximum amounts of 10 inches along the
northern coast.

Upper coast of Colima, western Nayarit including Islas Marias and
southeastern Sinaloa: 4 to 6 inches with maximum amounts of 8 
inches.

Southern Durango into western Zacatecas:  1 to 3 inches with maximum
amounts of 5 inches.

This rainfall could lead to flash flooding and landslides in areas
of rugged terrain.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the east of where the
center makes landfall.  Near the coast, the surge will be
accompanied by large and destructive waves.

SURF:  Swells generated by Roslyn are affecting portions of the
coast of southwestern Mexico and will spread northward to the coast
of west-central Mexico and the southern portion of the Baja
California peninsula through the weekend.  These swells are likely
to cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM MDT.
Next complete advisory at 900 PM MDT.

$$
Forecaster Beven

