

000
WTPZ34 KNHC 230243
TCPEP4

BULLETIN
Hurricane Roslyn Advisory Number  13
NWS National Hurricane Center Miami FL       EP192022
900 PM MDT Sat Oct 22 2022

...ROSLYN EXPECTED TO BRING STRONG WINDS, A DANGEROUS STORM SURGE,
AND FLOODING RAINS TO PORTIONS OF WEST-CENTRAL MEXICO TONIGHT AND
SUNDAY...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...20.0N 106.6W
ABOUT 65 MI...105 KM WSW OF CABO CORRIENTES MEXICO
MAXIMUM SUSTAINED WINDS...130 MPH...215 KM/H
PRESENT MOVEMENT...N OR 360 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...954 MB...28.17 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Playa Perula to Escuinapa
* Las Islas Marias

A Hurricane Watch is in effect for...
* North of Escuinapa to Mazatlan

A Tropical Storm Warning is in effect for...
* South of Playa Perula to Manzanillo
* North of Escuinapa to Mazatlan

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Hurricane Roslyn was located
near latitude 20.0 North, longitude 106.6 West.  Roslyn is moving
toward the north near 12 mph (19 km/h), and a faster motion toward 
the north-northeast is expected on Sunday.  On the forecast track, 
the center of Roslyn will approach the coast of west-central Mexico, 
likely making landfall along the coast of the Mexican state of 
Nayarit Sunday morning.

Maximum sustained winds are near 130 mph (215 km/h) with higher
gusts.  Roslyn is a category 4 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Although some weakening is possible
tonight and early Sunday, Roslyn is expected to be at or near
major hurricane intensity when it makes landfall on Sunday.

Hurricane-force winds extend outward up to 30 miles (45 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 954 mb (28.17 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane conditions are expected to reach the coast within
the hurricane warning area tonight and early Sunday.  Winds are
likely near tropical storm strength over portions of the area.
Preparations to protect life and property should be rushed to
completion.

Hurricane conditions are possible within the hurricane watch area
on Sunday.

Tropical storm conditions are expected within the tropical storm
warning area south of Playa Perula tonight, and within the warning
area north of Escuinapa on Sunday.

RAINFALL: Roslyn is expected to produce the following rainfall
totals across coastal areas of southwestern and west-central
Mexico:

Michoacán and the lower coast of Colima: 1 to 3 inches.

Jalisco: 4 to 8 inches with maximum amounts of 10 inches along the
northern coast.

Upper coast of Colima, western Nayarit including Islas Marias, and
southeastern Sinaloa: 4 to 6 inches with maximum amounts of 8
inches.

Southern Durango into western Zacatecas: 1 to 3 inches with maximum
amounts of 5 inches.

This rainfall could lead to flash flooding and landslides in areas
of rugged terrain.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the east of where the
center makes landfall.  Near the coast, the surge will be
accompanied by large and destructive waves.

SURF:  Swells generated by Roslyn are affecting portions of the
coast of southwestern Mexico and will spread northward to the coast
of west-central Mexico and the southern portion of the Baja
California peninsula through the weekend.  These swells are likely
to cause life-threatening surf and rip current conditions.  Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM MDT.
Next complete advisory at 300 AM MDT.

$$
Forecaster Pasch

