

110 
WTPZ34 KNHC 231155
TCPEP4

BULLETIN
Hurricane Roslyn Intermediate Advisory Number 14A
NWS National Hurricane Center Miami FL       EP192022
600 AM MDT Sun Oct 23 2022


...CENTER OF ROSLYN MOVING INLAND OVER NORTHERN NAYARIT...
...BRINGING DAMAGING WINDS, A LIFE-THREATENING STORM SURGE AND 
FLOODING RAINS TO PORTIONS OF WEST-CENTRAL MEXICO...


SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...22.1N 105.5W
ABOUT 55 MI...90 KM NW OF TEPIC MEXICO
MAXIMUM SUSTAINED WINDS...120 MPH...195 KM/H
PRESENT MOVEMENT...NNE OR 25 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...960 MB...28.35 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Playa Perula to Escuinapa
* Las Islas Marias

A Hurricane Watch is in effect for...
* North of Escuinapa to Mazatlan

A Tropical Storm Warning is in effect for...
* South of Playa Perula to Manzanillo
* North of Escuinapa to Mazatlan

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.

A Hurricane Watch means that hurricane conditions are possible
within the watch area.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the eye of Hurricane Roslyn was located
near latitude 22.1 North, longitude 105.5 West. Roslyn is moving
toward the north-northeast near 16 mph (26 km/h).  This general
motion with some increase in forward speed is expected today. On the
forecast track, Roslyn will move farther inland over west-central 
Mexico today.

Maximum sustained winds are near 120 mph (195 km/h) with higher
gusts.  Roslyn is a category 3 hurricane on the Saffir-Simpson
Hurricane Wind Scale.  Now that Roslyn has made landfall, rapid 
weakening is expected as the hurricane moves farther inland.

Hurricane-force winds extend outward up to 25 miles (35 km) from
the center and tropical-storm-force winds extend outward up to 80
miles (130 km).

The estimated minimum central pressure is 960 mb (28.35 inches). 


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane and tropical storm conditions will continue to 
spread inland within the warning area today.  Wind speeds atop hills 
and mountains are often up to 30 percent stronger than the 
near-surface winds indicated in this advisory, and in some elevated 
locations could be even greater.  

Hurricane conditions are possible within the hurricane watch area 
this morning.

RAINFALL: Roslyn is expected to produce the following rainfall
totals across coastal areas of southwestern and west-central
Mexico:

Jalisco: 4 to 8 inches with maximum amounts of 10 inches along the
northern coast.

Upper coast of Colima, western Nayarit including Islas Marias, and
southeastern Sinaloa: 4 to 6 inches with maximum amounts of 8
inches.

Southern Durango into western Zacatecas: 1 to 3 inches with maximum
amounts of 5 inches.

This rainfall could lead to flash flooding and landslides in areas
of rugged terrain.

STORM SURGE:  Roslyn is expected to produce a life-threatening storm 
surge with significant coastal flooding in areas of onshore winds 
through today.  Near the coast, the surge will be accompanied by 
large and destructive waves.

SURF:  Swells generated by Roslyn are affecting portions of the 
coast of southwestern Mexico, west-central Mexico, and the southern 
portion of the Baja California peninsula through tonight.  These 
swells are likely to cause life-threatening surf and rip current 
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Bucci/Brown


