

000
WTPZ35 KNHC 062037
TCPEP5

BULLETIN
Tropical Storm Lidia Advisory Number  15
NWS National Hurricane Center Miami FL       EP152023
300 PM MDT Fri Oct 06 2023

...SHEARED LIDIA REMAINS NEAR HURRICANE INTENSITY...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...16.4N 111.2W
ABOUT 490 MI...785 KM WSW OF MANZANILLO MEXICO
ABOUT 455 MI...735 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Tropical Storm Lidia was
located near latitude 16.4 North, longitude 111.2 West. Lidia is
moving toward the west near 6 mph (9 km/h). This general motion 
is expected to continue over the next day, followed by a gradual
turn toward the northwest, and then north, through the weekend.

Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts. Slight strengthening is possible during the next day or 
two, and Lidia could become a hurricane tonight or over the weekend.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 991 mb (29.27 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Lidia will begin to affect the west coast
of Mexico and the Baja California peninsula on Saturday.  These
swells are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 PM MDT.

$$
Forecaster Delgado/D. Zelinsky

