

000
WTPZ35 KNHC 070253
TCPEP5

BULLETIN
Tropical Storm Lidia Advisory Number  16
NWS National Hurricane Center Miami FL       EP152023
900 PM MDT Fri Oct 06 2023

...LIDIA REMAINS A SHEARED TROPICAL STORM...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...16.4N 111.6W
ABOUT 515 MI...825 KM WSW OF MANZANILLO MEXICO
ABOUT 460 MI...745 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...W OR 275 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Tropical Storm Lidia was 
located near latitude 16.4 North, longitude 111.6 West. Lidia is 
moving toward the west near 6 mph (9 km/h). A gradual turn toward 
the northwest and north is expected this weekend, followed by a 
slightly faster northeastward motion on Monday.

Maximum sustained winds remain near 70 mph (110 km/h) with higher
gusts. Small intensity fluctuations are possible during the next
couple of days, and Lidia could become a hurricane over the weekend.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The estimated minimum central pressure is 991 mb (29.27 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Lidia will begin to affect the west coast
of Mexico and the Baja California peninsula on Saturday. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 AM MDT.

$$
Forecaster Reinhart

