

000
WTPZ35 KNHC 070831
TCPEP5

BULLETIN
Tropical Storm Lidia Advisory Number  17
NWS National Hurricane Center Miami FL       EP152023
300 AM MDT Sat Oct 07 2023

...LIDIA FORECAST TO MOVE SLOWLY WELL OFFSHORE OF SOUTHWESTERN
MEXICO THIS WEEKEND...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.0N 111.9W
ABOUT 540 MI...870 KM WSW OF MANZANILLO MEXICO
ABOUT 495 MI...795 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Tropical Storm Lidia was
located near latitude 16.0 North, longitude 111.9 West. Lidia is
moving toward the west near 5 mph (7 km/h).  A gradual turn toward
the northwest and north is expected this weekend, followed by a
slightly faster northeastward motion on Monday.

Satellite data show that maximum sustained winds are near 65 mph 
(100 km/h) with higher gusts.  Little change in strength is 
anticipated this weekend, but Lidia could become a hurricane early 
next week. 

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 995 mb (29.39 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Lidia will begin to affect the west coast
of Mexico and the Baja California peninsula today. These swells are 
likely to cause life-threatening surf and rip current conditions. 
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Blake

