

000
WTPZ35 KNHC 071443
TCPEP5

BULLETIN
Tropical Storm Lidia Advisory Number  18
NWS National Hurricane Center Miami FL       EP152023
900 AM MDT Sat Oct 07 2023

...LIDIA FORECAST TO SLOWLY TURN NORTHWARD THIS WEEKEND...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...16.2N 112.2W
ABOUT 555 MI...895 KM WSW OF MANZANILLO MEXICO
ABOUT 485 MI...780 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Lidia was
located near latitude 16.2 North, longitude 112.2 West. Lidia is
moving toward the west-northwest near 5 mph (7 km/h), and a gradual 
turn toward the north is expected this weekend, followed by a 
faster northeastward motion on Monday.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Little change in strength is forecast this weekend, but 
Lidia could become a hurricane early next week.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 995 mb (29.39 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Lidia will begin to affect the west coast
of Mexico and the Baja California peninsula today. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 300 PM MDT.

$$
Forecaster Hogsett/Berg

