
ZCZC MIATCPEP5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Lidia Advisory Number  21
NWS National Hurricane Center Miami FL       EP152023
300 AM MDT Sun Oct 08 2023

...LIDIA MOVING LITTLE WITH NO CHANGE IN STRENGTH...
...FORECAST TO APPROACH THE WEST COAST OF MEXICO AS A HURRICANE
ON TUESDAY...


SUMMARY OF 300 AM MDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...16.4N 112.5W
ABOUT 570 MI...915 KM WSW OF MANZANILLO MEXICO
ABOUT 480 MI...770 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 2 MPH...4 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.

Interests in the Islas Marias and along the west-central coast of
Mexico should monitor the progress of this system. Watches could be
required for portions of these areas later today.


DISCUSSION AND OUTLOOK
----------------------
At 300 AM MDT (0900 UTC), the center of Tropical Storm Lidia was
located near latitude 16.4 North, longitude 112.5 West. Lidia is
drifting north-northwestward near 2 mph (4 km/h), and a slow 
generally northward motion is expected to continue through today, 
followed by an accelerated northeastward motion on Monday and 
Tuesday. On the forecast track, the center of Lidia should approach 
the Islas Marias and the coast of west-central Mexico on Tuesday.

Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts. Some gradual strengthening is expected through early next 
week, and Lidia is forecast to become a hurricane by early Monday.

Tropical-storm-force winds extend outward up to 115 miles (185 km)
from the center.

The estimated minimum central pressure is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lidia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP5 and WMO header WTPZ45 KNHC
and on the web at hurricanes.gov/text/MIATCDEP5.shtml

SURF: Swells generated by Lidia will affect the west coast of Mexico
and the Baja California peninsula for the next several days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Roberts

NNNN
