
ZCZC MIATCPEP5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Lidia Intermediate Advisory Number 25A
NWS National Hurricane Center Miami FL       EP152023
600 AM MDT Mon Oct 09 2023

...LIDIA TURNING NORTHEASTWARD TOWARD WEST-CENTRAL MEXICO...
...HURRICANE CONDITIONS FORECAST TO BEGIN ON TUESDAY...


SUMMARY OF 600 AM MDT...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...18.4N 112.1W
ABOUT 340 MI...550 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 425 MI...690 KM WSW OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias

A Hurricane Watch is in effect for...
* Playa Perula to Mazatlan

A Tropical Storm Watch is in effect for...
* Mazatlan to Bahia Tempehuaya
* Manzanillo to Playa Perula

A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area.  A warning is typically issued  
36 hours before the anticipated first occurrence of 
tropical-storm-force winds, conditions that make outside 
preparations difficult or dangerous.  Preparations to protect life 
and property should be rushed to completion.

A Hurricane Watch means that hurricane conditions are possible
within the watch area, generally within 48 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in west-central Mexico and the southern portion
of the Baja California peninsula should monitor the progress of
Lidia.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 600 AM MDT (1200 UTC), the center of Tropical Storm Lidia was
located near latitude 18.4 North, longitude 112.1 West. Lidia is
moving toward the northeast near 5 mph (7 km/h). A faster
northeastward to east-northeastward motion is expected later today
and Tuesday. On the forecast track, the center of Lidia should
approach Las Islas Marias and the coast of west-central Mexico on
Tuesday, and move inland over west-central Mexico Tuesday night.

Maximum sustained winds are near 65 mph (100 km/h) with higher 
gusts. Strengthening is forecast later today and Tuesday, and Lidia 
is expected to be a hurricane when it approaches Las Islas Marias 
and the coast of west-central Mexico.

Tropical-storm-force winds extend outward up to 105 miles (165 km)
from the center.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lidia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP5 and WMO header WTPZ45 KNHC
and on the web at hurricanes.gov/text/MIATCDEP5.shtml

RAINFALL:  Lidia is expected to produce rainfall totals of 4 to 8
inches with local maxima of 12 inches through Wednesday across the
state of Nayarit, southern portions of the state of Sinaloa, and
coastal portions of the state of Jalisco in western Mexico. These
rains will likely produce flash and urban flooding, along with
possible mudslides in areas of higher terrain near the coast.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the south of where
the center makes landfall.  Near the coast, the surge will be
accompanied by large and dangerous waves.

WIND:  Hurricane conditions are expected to reach the warning area
on Tuesday.  Winds are expected to first reach tropical storm
strength for the warning area by early Tuesday, making outside
preparations difficult or dangerous. Preparations to protect life
and property should be rushed to completion. Hurricane conditions
are possible within the watch area by late Tuesday, with tropical
storm conditions possible on Tuesday. Tropical storm conditions are
possible in the Tropical Storm Watch areas beginning Tuesday.

SURF: Swells generated by Lidia will affect the west coast of Mexico
and the Baja California peninsula for the next few days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 900 AM MDT.

$$
Forecaster Cangialosi 

NNNN
