

204 
WTPZ35 KNHC 091432
TCPEP5

BULLETIN
Tropical Storm Lidia Advisory Number  26
NWS National Hurricane Center Miami FL       EP152023
900 AM MDT Mon Oct 09 2023

...HURRICANE AND TROPICAL STORM WARNINGS ISSUED FOR WEST-CENTRAL
MEXICO...


SUMMARY OF 900 AM MDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...18.5N 111.8W
ABOUT 330 MI...525 KM SSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 405 MI...655 KM WSW OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NE OR 45 DEGREES AT 6 MPH...9 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has issued a Hurricane Warning from Playa
Perula to Escuinapa.  The government of Mexico has also issued a
Tropical Storm Warning from Manzanillo to Playa Perula and from
Escuinapa to Bahia Tempehuaya.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* Playa Perula to Escuinapa

A Tropical Storm Warning is in effect for...
* Escuinapa to Bahia Tempehuaya
* Manzanillo to Playa Perula

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in west-central Mexico and the southern portion
of the Baja California peninsula should monitor the progress of
Lidia.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 AM MDT (1500 UTC), the center of Tropical Storm Lidia was
located near latitude 18.5 North, longitude 111.8 West. Lidia is
moving toward the northeast near 6 mph (9 km/h). A faster
northeastward to east-northeastward motion is expected later today
and Tuesday. On the forecast track, the center of Lidia should
approach Las Islas Marias on Tuesday, and move inland over 
west-central Mexico Tuesday night.

Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Strengthening is forecast later today and Tuesday, and Lidia
is expected to be a hurricane when it approaches Las Islas Marias
and the coast of west-central Mexico.

Tropical-storm-force winds extend outward up to 90 miles (150 km)
from the center.

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lidia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP5 and WMO header WTPZ45 KNHC
and on the web at hurricanes.gov/text/MIATCDEP5.shtml

RAINFALL:  Lidia is expected to produce rainfall totals of 4 to 8
inches with local maxima of 12 inches through Wednesday across the
state Nayarit, southern portions of the state of Sinaloa, and
coastal portions of the state of Jalisco in western Mexico. These
rains will likely produce flash and urban flooding, along with
possible mudslides in areas of higher terrain near the coast.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the south of where
the center makes landfall.  Near the coast, the surge will be
accompanied by large and dangerous waves.

WIND:  Hurricane conditions are expected to reach the warning area
on Tuesday, with winds expected to first reach tropical
storm strength by early Tuesday, making outside preparations
difficult or dangerous. Preparations to protect life and property
should be rushed to completion. Tropical storm conditions are
expected in the Tropical Storm Warning areas beginning Tuesday.

SURF: Swells generated by Lidia will affect the west coast of Mexico
and the Baja California peninsula for the next few days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 PM MDT.
Next complete advisory at 300 PM MDT.

$$
Forecaster Cangialosi


