

000
WTPZ35 KNHC 092036
TCPEP5

BULLETIN
Tropical Storm Lidia Advisory Number  27
NWS National Hurricane Center Miami FL       EP152023
300 PM MDT Mon Oct 09 2023

...LIDIA ALMOST A HURRICANE...
...HURRICANE-FORCE WINDS AND FLOODING RAINS EXPECTED TO BEGIN IN
WEST-CENTRAL MEXICO ON TUESDAY...


SUMMARY OF 300 PM MDT...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...18.1N 110.9W
ABOUT 340 MI...545 KM S OF THE SOUTHERN TIP OF BAJA CALIFORNIA
ABOUT 375 MI...605 KM SW OF LAS ISLAS MARIAS MEXICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...985 MB...29.09 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* Playa Perula to Escuinapa

A Tropical Storm Warning is in effect for...
* Escuinapa to Bahia Tempehuaya
* Manzanillo to Playa Perula

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.  A warning is typically issued
36 hours before the anticipated first occurrence of
tropical-storm-force winds, conditions that make outside
preparations difficult or dangerous.  Preparations to protect life
and property should be rushed to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within 24 
hours.

Interests elsewhere in west-central Mexico should monitor the 
progress of Lidia.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM MDT (2100 UTC), the center of Tropical Storm Lidia was
located near latitude 18.1 North, longitude 110.9 West. Lidia is
moving toward the east-northeast near 8 mph (13 km/h).  A faster
east-northeastward motion is expected this evening and Tuesday. On
the forecast track, the center of Lidia should approach Las Islas
Marias on Tuesday, and move inland over west-central Mexico late 
Tuesday or Tuesday night.

Maximum sustained winds are near 70 mph (110 km/h) with higher
gusts.  Strengthening is forecast later today and Tuesday, and 
Lidia is expected to be a hurricane when it approaches Las Islas 
Marias and the coast of west-central Mexico.

Tropical-storm-force winds extend outward up to 80 miles (130 km)
from the center.

The minimum central pressure of 985 mb (29.09 inches) is based on 
data collected by the Air Force Hurricane Hunters.


HAZARDS AFFECTING LAND
----------------------
Key messages for Lidia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP5 and WMO header WTPZ45 KNHC
and on the web at hurricanes.gov/text/MIATCDEP5.shtml

RAINFALL:  Lidia is expected to produce rainfall totals of 4 to 8
inches with local maxima of 12 inches through Wednesday across the
state Nayarit, southern portions of the state of Sinaloa, and
coastal portions of the state of Jalisco in western Mexico. These
rains will likely produce flash and urban flooding, along with
possible mudslides in areas of higher terrain near the coast.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the south of where
the center makes landfall.  Near the coast, the surge will be
accompanied by large and dangerous waves.

WIND:  Hurricane conditions are expected to reach the warning area
on Tuesday, with winds expected to first reach tropical
storm strength by Tuesday morning, making outside preparations
difficult or dangerous. Preparations to protect life and property
should be rushed to completion. Tropical storm conditions are
expected in the Tropical Storm Warning areas beginning Tuesday.

SURF: Swells generated by Lidia will affect the west coast of Mexico
and the Baja California peninsula for the next couple of days. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 600 PM MDT.
Next complete advisory at 900 PM MDT.

$$
Forecaster Cangialosi

