

000
WTPZ35 KNHC 100243
TCPEP5

BULLETIN
Hurricane Lidia Advisory Number  28
NWS National Hurricane Center Miami FL       EP152023
900 PM MDT Mon Oct 09 2023

...LIDIA STRENGTHENS INTO A HURRICANE...
...HURRICANE-FORCE WINDS AND FLOODING RAINS EXPECTED TO BEGIN IN
WEST-CENTRAL MEXICO ON TUESDAY...


SUMMARY OF 900 PM MDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...18.2N 110.2W
ABOUT 335 MI...540 KM SW OF LAS ISLAS MARIAS MEXICO
ABOUT 365 MI...590 KM WSW OF PUERTO VALLARTA MEXICO
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...ENE OR 65 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...983 MB...29.03 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Mexico has discontinued the Tropical Storm
Warning north of Mazatlan.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Las Islas Marias
* Playa Perula to Escuinapa

A Tropical Storm Warning is in effect for...
* Escuinapa to Mazatlan
* Manzanillo to Playa Perula

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case within the next 24
hours. Preparations to protect life and property should be rushed
to completion.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
the next 12 to 24 hours.

Interests elsewhere in west-central Mexico should monitor the
progress of Lidia.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 900 PM MDT (0300 UTC), the center of Hurricane Lidia was located
near latitude 18.2 North, longitude 110.2 West. Lidia is moving
toward the east-northeast near 10 mph (17 km/h). A faster
east-northeastward motion is expected through Tuesday. On the
forecast track, the center of Lidia should approach the west-central
coast of Mexico within the hurricane warning area on Tuesday and
move inland over west-central Mexico late Tuesday or Tuesday night.

Maximum sustained winds have increased to near 75 mph (120 km/h)
with higher gusts. Additional strengthening is forecast tonight
and Tuesday as Lidia approaches the coast of west-central Mexico.
Rapid weakening is expected after Lidia moves inland.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 80 miles
(130 km).

The estimated minimum central pressure is 983 mb (29.03 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Lidia can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDEP5 and WMO header WTPZ45 KNHC
and on the web at hurricanes.gov/text/MIATCDEP5.shtml

RAINFALL:  Lidia is expected to produce rainfall totals of 4 to 8
inches with local maxima of 12 inches through Wednesday across the
state of Nayarit, southern portions of the state of Sinaloa, and
coastal portions of the state of Jalisco in western Mexico. These
rains will likely produce flash and urban flooding, along with
possible mudslides in areas of higher terrain near the coast.

STORM SURGE:  A dangerous storm surge is expected to produce
significant coastal flooding near and to the south of where
the center makes landfall.  Near the coast, the surge will be
accompanied by large and dangerous waves.

WIND:  Hurricane conditions are expected to reach the warning area
on Tuesday, with winds expected to first reach tropical
storm strength by Tuesday morning, making outside preparations
difficult or dangerous. Preparations to protect life and property
should be rushed to completion. Tropical storm conditions are
expected in the Tropical Storm Warning areas beginning Tuesday.

SURF: Swells generated by Lidia will affect the west coast of Mexico
and the Baja California peninsula for the next day or two. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 1200 AM MDT.
Next complete advisory at 300 AM MDT.

$$
Forecaster Brown

