

000
WTNT33 KNHC 061745
TCPAT3

BULLETIN
Potential Tropical Cyclone Thirteen Intermediate Advisory Number 1A
NWS National Hurricane Center Miami FL       AL132022
200 PM AST Thu Oct 06 2022

...HURRICANE WATCH ISSUED FOR SAN ANDRES, PROVIDENCIA, AND SANTA 
CATALINA ISLANDS...
...HEAVY RAINS EXPECTED ACROSS THE ABC ISLANDS AND PORTIONS OF
NORTHERN SOUTH AMERICA THROUGH FRIDAY...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...11.5N 67.7W
ABOUT 100 MI...160 KM ESE OF CURACAO
ABOUT 265 MI...425 KM ESE OF NTHRN TIP OF GUAJIRA PNSULA COLOMBIA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Colombia has issued a Hurricane Watch for San 
Andres, Providencia, and Santa Catalina Islands.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* San Andres, Providencia, and Santa Catalina Islands Colombia

A Tropical Storm Warning is in effect for...
* Coast of Colombia from Riohacha eastward to the Colombia/Venezuela 
border

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
the next 24 hours.

Interests along the coasts of Nicaragua and Honduras should monitor 
the progress of the disturbance.  Additional watches or warnings 
could be required tonight or on Friday.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the disturbance was centered near latitude
11.5 North, longitude 67.7 West.  The system is moving toward the
west near 15 mph (24 km/h), and this general motion is expected to
continue through Sunday.  On the forecast track, the system is
expected to move near the ABC Islands, the coast of northwestern
Venezuela, and the Guajira Peninsula of Colombia through Friday
morning.  The system is then forecast to move across the
southwestern Caribbean Sea, moving near San Andres and Providencia 
Islands Saturday night, and approaching the coast of Nicaragua on
Sunday.

Maximum sustained winds are near 35 mph (55 km/h) with higher
gusts. Strengthening is forecast during the next few days.  The
system could become a tropical depression by tonight, and is
forecast to become a tropical storm on Friday.  The system is then
expected to become a hurricane by Sunday as it approaches the coast
of Nicaragua.
* Formation chance through 48 hours...high...near 100 percent.
* Formation chance through 5 days...high...near 100 percent.  

The estimated minimum central pressure is 1005 mb (29.68 inches) 
based on observations from Bonaire.


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane conditions are possible on the Colombian islands of 
San Andres, Providencia, and Santa Catalina Saturday night, with 
tropical storm conditions possible by late Saturday.

Tropical storm conditions are expected along the coast of
Colombia within the warning area by early Friday.  Gusts to tropical
storm force are also possible across the ABC Islands and the
northwestern coast of Venezuela today and tonight.

RAINFALL:  Potential Tropical Cyclone Thirteen is expected to
produce the following rain accumulations through early Monday:

Northern Coastal Venezuela...3 to 6 inches, isolated 10 inches.
Aruba, Bonaire, and Curacao...3 to 6 inches
Guajira Peninsula of Colombia...3 to 6 inches, isolated 10 inches.
San Andres and Providencia...6 to 12 inches
Eastern Nicaragua...6 to 10 inches, isolated 16 inches.
Central Nicaragua...3 to 6 inches, isolated 10 inches.

This rainfall may cause life-threatening flash floods.

STORM SURGE:  A storm surge could raise water levels by as much as 
1 to 3 feet above normal tide levels along the immediate coast in 
areas of onshore winds on San Andres, Providencia, and Santa 
Catalina Islands.  Near the coast, the surge will be accompanied by 
large and damaging waves.

SURF:  Swells generated by disturbance will affect the ABC Islands
and portions of the coasts of northwestern Venezuela and the Guajira
Peninsula of Colombia through Friday.  Swells could reach Jamaica,
Providencia, and San Andres on Saturday, and portions of the coast
of Central America on Sunday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Berg

