

403 
WTNT33 KNHC 070235
TCPAT3

BULLETIN
Tropical Depression Thirteen Advisory Number   3
NWS National Hurricane Center Miami FL       AL132022
1100 PM AST Thu Oct 06 2022

...DISTURBANCE BECOMES A TROPICAL DEPRESSION NEAR THE ABC ISLANDS
AND THE COAST OF NORTHWESTERN VENEZUELA...
...HEAVY RAINS EXPECTED ACROSS THE ABC ISLANDS AND PORTIONS OF
NORTHERN SOUTH AMERICA THROUGH FRIDAY...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...11.9N 69.8W
ABOUT 60 MI...100 KM WSW OF CURACAO
ABOUT 120 MI...195 KM ESE OF NTHRN TIP OF GUAJIRA PNSULA COLOMBIA
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* San Andres, Providencia, and Santa Catalina Islands Colombia

A Tropical Storm Warning is in effect for...
* Coast of Colombia from Riohacha eastward to the Colombia/Venezuela
border

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area, in this case within
the next 12 to 24 hours.

Interests along the coasts of Nicaragua and Honduras should monitor
the progress of the disturbance.  Additional watches or warnings
will likely be required on Friday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Depression
Thirteen was located near latitude 11.9 North, longitude 69.8 West.
The depression is moving toward the west near 15 mph (24 km/h), and 
a generally westward motion is expected to continue through Sunday. 
On the forecast track, the cyclone is expected to move near the 
ABC Islands, the coast of northwestern Venezuela, and the Guajira 
Peninsula of Colombia tonight through Friday morning.  The system 
is then forecast to move across the southwestern Caribbean Sea, 
moving near San Andres and Providencia Islands Saturday night, and 
approaching the coast of Nicaragua on Sunday morning.

Maximum sustained winds are near 35 mph (55 km/h) with higher gusts.
Gradual strengthening is expected for the next 12-24 hours, and the 
depression is expected to become a tropical storm by Friday morning. 
After that, a faster rate of strengthening is likely, with the 
system expected to become a hurricane by Saturday night as it 
approaches San Andres and Providencia Islands.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
WIND:  Hurricane conditions are possible on the Colombian islands of
San Andres, Providencia, and Santa Catalina Saturday night, with
tropical storm conditions possible by Saturday afternoon.

Tropical storm conditions are expected along the coast of Colombia
within the warning area by early Friday.  Gusts to tropical
storm force are also possible across the ABC Islands and the
northwestern coast of Venezuela tonight.

RAINFALL:  The tropical depression is expected to produce the
following rain accumulations through early Monday:

Northern Coastal Venezuela...3 to 6 inches, isolated 10 inches.
Aruba, Bonaire, and Curacao...3 to 6 inches
Guajira Peninsula...3 to 6 inches, isolated 10 inches.
San Andres and Providencia...6 to 12 inches
Eastern Nicaragua...6 to 10 inches, isolated 16 inches.
Central Nicaragua...3 to 6 inches, isolated 10 inches.
Southwest Costa Rica and Southwestern Panama...4 to 8 inches,
isolated 12 inches

This rainfall may cause life-threatening flash floods.  There is
also the potential for life-threatening mudslides across portions of
Central America this weekend.

STORM SURGE:  A storm surge could raise water levels by as much as
1 to 3 feet above normal tide levels along the immediate coast in
areas of onshore winds on San Andres, Providencia, and Santa
Catalina Islands.  Near the coast, the surge will be accompanied by
large and damaging waves.

SURF:  Swells generated by the cyclone will affect the ABC Islands
and portions of the coasts of northwestern Venezuela and the Guajira
Peninsula of Colombia through Friday.  Swells could reach Jamaica,
Providencia, and San Andres on Saturday, and portions of the coast
of Central America on Sunday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Beven


