625 
WTPZ35 KNHC 171437
TCPEP5
 
BULLETIN
Tropical Storm Elida Advisory Number  12
NWS National Hurricane Center Miami FL       EP052026
800 AM PDT Fri Jul 17 2026
 
...ELIDA STILL HAS NOT SHOWN MUCH CHANGE IN INTENSITY...
 
 
SUMMARY OF 800 AM PDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...16.8N 120.8W
ABOUT 825 MI...1325 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 300 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...994 MB...29.36 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM PDT (1500 UTC), the center of Tropical Storm Elida was 
located near latitude 16.8 North, longitude 120.8 West. Elida is 
moving toward the west-northwest near 10 mph (17 km/h). A turn 
toward the northwest is expected later today, followed by a 
north-northwestward motion at a slightly faster forward speed by 
Sunday.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts.  Some strengthening is possible, and Elida could still 
become a hurricane within the next day. Weakening is expected 
to start over the weekend and continue into early next week. 
 
Tropical-storm-force winds extend outward up to 160 miles (260 km)
from the center.
 
The estimated minimum central pressure is 994 mb (29.36 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Elida will affect portions of the west
coast of the Baja California peninsula through this weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 PM PDT.
 
$$
Forecaster Katz/Cangialosi
  