000
WTPZ35 KNHC 180232
TCPEP5
 
BULLETIN
Tropical Storm Elida Advisory Number  14
NWS National Hurricane Center Miami FL       EP052026
800 PM PDT Fri Jul 17 2026
 
...ELIDA TURNS NORTHWESTWARD OVER OPEN WATERS...
 
 
SUMMARY OF 800 PM PDT...0300 UTC...INFORMATION
----------------------------------------------
LOCATION...17.4N 122.5W
ABOUT 900 MI...1450 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 PM PDT (0300 UTC), the center of Tropical Storm Elida was
located near latitude 17.4 North, longitude 122.5 West. Elida is
moving toward the northwest near 10 mph (17 km/h), and this motion
is expected to continue through Saturday. A north-northwestward
motion is forecast later this weekend and into early next week.
 
Maximum sustained winds are near 65 mph (100 km/h) with higher
gusts. Little change in strength is expected overnight. Weakening
is forecast to begin later on Saturday and continue through early
next week.
 
Tropical-storm-force winds extend outward up to 195 miles (315 km)
from the center.
 
The estimated minimum central pressure is 992 mb (29.30 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Elida will affect portions of the west
coast of the Baja California peninsula through this weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 200 AM PDT.
 
$$
Forecaster Reinhart
  