000
WTPZ35 KNHC 180834
TCPEP5
 
BULLETIN
Tropical Storm Elida Advisory Number  15
NWS National Hurricane Center Miami FL       EP052026
200 AM PDT Sat Jul 18 2026
 
...ELIDA A LITTLE STRONGER BUT HEADING TOWARD COOLER WATERS...
 
 
SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...18.0N 122.8W
ABOUT 900 MI...1450 KM WSW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NW OR 315 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Tropical Storm Elida was
located near latitude 18.0 North, longitude 122.8 West. Elida is
moving toward the northwest near 9 mph (15 km/h), and this 
general motion is expected to continue today. A faster motion 
toward the north-northwest is forecast by early Sunday, followed by 
a northward turn on Monday.
 
Maximum sustained winds have increased to near 70 mph (110 km/h) 
with higher gusts.  Little change in strength is forecast today, 
but weakening is expected to begin by tonight and continue for the 
next few days. Elida is likely to become post-tropical on Monday.
 
Tropical-storm-force winds extend outward up to 195 miles (315 km)
from the center.
 
The estimated minimum central pressure is 990 mb (29.24 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Elida will affect portions of the west
coast of the Baja California peninsula through this weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.
 
$$
Forecaster Berg
  