000
WTPZ35 KNHC 190831
TCPEP5
 
BULLETIN
Tropical Storm Elida Advisory Number  19
NWS National Hurricane Center Miami FL       EP052026
200 AM PDT Sun Jul 19 2026
 
...ELIDA WEAKENS A LITTLE MORE...
 
 
SUMMARY OF 200 AM PDT...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...21.4N 125.2W
ABOUT 985 MI...1585 KM W OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.42 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 200 AM PDT (0900 UTC), the center of Tropical Storm Elida was
located near latitude 21.4 North, longitude 125.2 West. Elida is
moving toward the north-northwest near 13 mph (20 km/h). A gradual
increase in forward speed is expected over the next couple of days
as the system turns northward.
 
Maximum sustained winds have decreased to near 60 mph (95 km/h) with 
higher gusts. Steady weakening is expected during the next couple of 
days as Elida moves over progressively cooler waters. Elida is 
forecast to become a remnant low by Monday night and dissipate by 
late Wednesday.
 
Tropical-storm-force winds extend outward up to 185 miles (295 km)
from the center.
 
The estimated minimum central pressure is 996 mb (29.42 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Elida will affect portions of the west
coast of the Baja California Peninsula and southern California
through early next week. These swells will likely result in
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
Next complete advisory at 800 AM PDT.
 
$$
Forecaster Gibbs (CPHC)
  