ZCZC MIATCPEP5 ALL
TTAA00 KNHC DDHHMM
 
BULLETIN
Post-Tropical Cyclone Elida Advisory Number  24
NWS National Hurricane Center Miami FL       EP052026
800 AM PDT Mon Jul 20 2026
 
...ELIDA BECOMES POST-TROPICAL...
...DANGEROUS SURF AND HIGH RISK OF RIP CURRENTS IN SOUTHERN
CALIFORNIA CONTINUES...
 
 
SUMMARY OF 800 AM PDT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...26.4N 127.2W
ABOUT 1110 MI...1790 KM WNW OF THE SOUTHERN TIP OF BAJA CALIFORNIA
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...NNW OR 345 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES
 
 
WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.
 
 
DISCUSSION AND OUTLOOK
----------------------
At 800 AM PDT (1500 UTC), the center of Post-Tropical Cyclone Elida 
was located near latitude 26.4 North, longitude 127.2 West. The 
post-tropical cyclone is moving toward the north-northwest near 13 
mph (20 km/h). A turn to the north with an increase in forward speed 
is forecast the during the next couple days.
 
Maximum sustained winds are near 40 mph (65 km/h) with higher gusts.
The post-tropical cyclone is expected to continue to weaken and 
should dissipate within the next couple of days.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.
 
The estimated minimum central pressure is 1000 mb (29.53 inches).
 
 
HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Elida will affect portions of the west
coast of the Baja California Peninsula and southern California
during the next several days. These swells will likely result in
life-threatening surf and rip current conditions. Please consult
products from your local weather office.
 
 
NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on this system. For additional information please see High 
Seas Forecasts issued by the National Weather Service, under AWIPS 
header NFDHSFEPI, WMO header FZPN02 KWBC, and on the web at 
ocean.weather.gov/shtml/NFDHSFEPI.php

$$
Forecaster Katz/Cangialosi
 
NNNN
  