

000
WTNT35 KNHC 112049
TCPAT5

BULLETIN
Potential Tropical Cyclone Five Advisory Number   1
NWS National Hurricane Center Miami FL       AL052024
500 PM AST Sun Aug 11 2024

...TROPICAL STORM WATCHES ISSUED FOR PORTIONS OF THE LEEWARD
ISLANDS...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...13.6N 48.0W
ABOUT 950 MI...1530 KM ESE OF ANTIGUA
MAXIMUM SUSTAINED WINDS...30 MPH...45 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 21 MPH...33 KM/H
MINIMUM CENTRAL PRESSURE...1010 MB...29.83 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of France has issued a Tropical Storm Watch for
Guadeloupe and St. Martin.

The government of Antigua has issued a Tropical Storm Watch for St.
Kitts, Nevis, Montserrat, Antigua, Barbuda, and Anguilla.

The government of the Netherlands has issued a Tropical Storm Watch
for Saba and St. Eustatius.

The government of Sint Maarten has issued a Tropical Storm Watch
for Sint Maarten.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Guadeloupe
* St. Kitts, Nevis, Montserrat, Antigua, Barbuda, and Anguilla
* Saba and St. Eustatius
* St. Martin
* Sint Maarten

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Interests elsewhere in the Leeward Islands, British and U.S. Virgin
Islands, and Puerto Rico should monitor the progress of Potential
Tropical Cyclone Five.  Additional watches could be required 
tonight or early Monday. 

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the disturbance was centered near latitude
13.6 North, longitude 48.0 West. The system is moving toward the
west-northwest near 21 mph (33 km/h) and this motion is expected to
continue during the next couple of days.  On the forecast track, 
the disturbance is expected to move across portions of the Leeward 
Islands on Tuesday and approach the U.S. and British Virgin Islands 
Tuesday night.

Maximum sustained winds are near 30 mph (45 km/h) with higher gusts.
Some strengthening is forecast, and the system is expected to 
become a tropical storm by late Monday. 
* Formation chance through 48 hours...high...80 percent.
* Formation chance through 7 days...high...90 percent.

The estimated minimum central pressure is 1010 mb (29.83 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Five can be found in 
the Tropical Cyclone Discussion under AWIPS header MIATCDAT5 and WMO 
header WTNT45 KNHC and on the web at 
hurricanes.gov/text/MIATCDAT5.shtml.

RAINFALL: Potential Tropical Cyclone Five is expected to produce
total rain accumulations of 4 to 6 inches over the northern Leeward
Islands. For Puerto Rico, 3 to 6 inches of rainfall, with maximum
amounts of 10 inches, is expected.

For a complete depiction of forecast rainfall associated with 
Potential Tropical Cyclone Five, please see the National Weather 
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf

Elsewhere in the Caribbean, Potential Tropical Cyclone Five is
expected to produce the following rain accumulations through Friday
morning:
Windward Islands… 1 to 2 inches
Southern Leeward Islands… 2 to 4 inches
Eastern Hispaniola… 2 to 4 inches.

WIND:  Tropical storm conditions are possible within the watch
area beginning Tuesday.

SURF:  Swells generated by the system will likely begin to affect
portions of the Leeward Islands beginning Monday night. These swells
are likely to cause life-threatening surf and rip current
conditions.  Please consult products from your local weather
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Hagen/Cangialosi

