

000
WTNT35 KNHC 121746
TCPAT5

BULLETIN
Potential Tropical Cyclone Five Intermediate Advisory Number 4A
NWS National Hurricane Center Miami FL       AL052024
200 PM AST Mon Aug 12 2024

...AIR FORCE HURRICANE HUNTERS INVESTIGATING THE SYSTEM...
...TROPICAL STORM CONDITIONS AND HEAVY RAIN EXPECTED IN PORTIONS OF 
THE LEEWARD ISLANDS LATE TONIGHT OR EARLY TUESDAY...

SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...15.5N 56.4W
ABOUT 375 MI...600 KM ESE OF ANTIGUA
ABOUT 670 MI...1080 KM ESE OF SAN JUAN PUERTO RICO
MAXIMUM SUSTAINED WINDS...35 MPH...55 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 26 MPH...43 KM/H
MINIMUM CENTRAL PRESSURE...1010 MB...29.83 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* St. Kitts, Nevis, Montserrat, Antigua, Barbuda, and Anguilla
* Guadeloupe
* St. Martin and St. Barthelemy
* Sint Maarten
* British Virgin Islands
* U.S. Virgin Islands
* Puerto Rico
* Vieques
* Culebra

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in the northeastern Caribbean should monitor the
progress of Potential Tropical Cyclone Five.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the disturbance was centered near latitude
15.5 North, longitude 56.4 West. The system is moving toward the
west near 26 mph (43 km/h). A westward to west-northwestward motion
with some decrease in forward speed is expected during the next
couple of days. On the forecast track, the disturbance is expected
to move across portions of the Leeward Islands late tonight or
Tuesday and approach the U.S. and British Virgin Islands and Puerto
Rico Tuesday evening. Then, the disturbance is forecast to move away
from Puerto Rico over the western Atlantic through midweek.

Maximum sustained winds are near 35 mph (55 km/h) with higher 
gusts. Gradual strengthening is forecast during the next couple of 
days, and the disturbance is expected to become a tropical 
depression later today or tonight and become a tropical storm as it
nears the Leeward Islands.
* Formation chance through 48 hours... high...near 100 percent.
* Formation chance through 7 days...high...near 100 percent.

The estimated minimum central pressure is 1010 mb (29.83 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Potential Tropical Cyclone Five can be found in
the Tropical Cyclone Discussion under AWIPS header MIATCDAT5 and WMO
header WTNT45 KNHC and on the web at
hurricanes.gov/text/MIATCDAT5.shtml.

RAINFALL: Potential Tropical Cyclone Five is expected to produce
total rain accumulations of 4 to 6 inches over portions of the
Leeward and Virgin Islands. For Puerto Rico, 3 to 6 inches of
rainfall, with maximum amounts of 10 inches, is expected.

Elsewhere in the Caribbean, Potential Tropical Cyclone Five is
expected to produce the following rain accumulations through Friday
morning:
Windward Islands...1 to 4 inches
Eastern Hispaniola...2 to 4 inches

For a complete depiction of forecast rainfall associated with
Potential Tropical Cyclone Five, please see the National Weather
Service Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf

WIND:  Tropical storm conditions are expected in the warning area
for the Leeward Islands beginning late tonight or early Tuesday. 
Tropical storm conditions are expected to begin spreading over the 
Virgin Islands and Puerto Rico on Tuesday night or early Wednesday.

STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level for the eastern coast of Puerto Rico
from San Juan to Guayama, including the islands of Culebra and
Vieques and in the U.S. Virgin Islands, including St. Thomas, St.
John, and St. Croix.

A storm surge will raise water levels by as much as 1 to 3 feet
above normal tide levels in the British Virgin Islands. Near the
coast, the surge will be accompanied by large and destructive waves.

SURF:  Swells generated by the system will likely begin to affect
portions of the Leeward Islands beginning tonight. These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi/Hagen

