

000
WTNT35 KNHC 131154
TCPAT5

BULLETIN
Tropical Storm Ernesto Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       AL052024
800 AM AST Tue Aug 13 2024

...ERNESTO STRENGTHENS A LITTLE WHILE PASSING ACROSS THE LESSER 
ANTILLES...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...16.6N 61.9W
ABOUT 35 MI...55 KM NW OF GUADELOUPE
ABOUT 300 MI...480 KM ESE OF SAN JUAN PUERTO RICO
MAXIMUM SUSTAINED WINDS...45 MPH...75 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 18 MPH...30 KM/H
MINIMUM CENTRAL PRESSURE...1005 MB...29.68 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* St. Kitts, Nevis, Montserrat, Antigua, Barbuda, and Anguilla
* Guadeloupe
* St. Martin and St. Barthelemy
* Sint Maarten
* British Virgin Islands
* U.S. Virgin Islands
* Puerto Rico
* Vieques
* Culebra

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests elsewhere in the northeastern Caribbean should
monitor the progress of Ernesto.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Ernesto was
located near latitude 16.6 North, longitude 61.9 West. Ernesto is
moving toward the west near 18 mph (30 km/h).  A west-northwestward
motion with some decrease in forward speed is expected during the
next day or so.  On the forecast track, Ernesto is expected to move
across portions of the Leeward Islands this morning and near or over
the U.S. and British Virgin Islands and Puerto Rico by this evening.
After passing Puerto Rico and the Virgin Islands, Ernesto is
forecast to turn northward over the western Atlantic.

Data from a NOAA Hurricane Hunter aircraft indicate that maximum 
sustained winds have increased to near 45 mph (75 km/h) with 
higher gusts. Additional strengthening is expected during the next 
few days, and Ernesto could reach hurricane strength by Thursday 
over the waters north of the Greater Antilles.

Tropical-storm-force winds extend outward up to 70 miles (110 km)
from the center.  St. Barthelemy reported a wind gust of 56 mph (90 
km/h), and St. Martin reported a gust of 50 mph (80 km/h) during 
the past few hours.

The estimated minimum central pressure based on dropsonde 
observations is 1005 mb (29.68 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

RAINFALL: Tropical Storm Ernesto is expected to produce total rain
accumulations of 4 to 6 inches over portions of the Leeward and
Virgin Islands. For Puerto Rico, 3 to 6 inches of rainfall, with
maximum amounts of 10 inches, are expected.

For a complete depiction of forecast rainfall associated with
Tropical Storm Ernesto, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf

Elsewhere in the Caribbean, Tropical Storm Ernesto is expected to
produce the following rain accumulations through Friday morning:
Windward Islands...1 to 4 inches
Eastern Hispaniola...2 to 4 inches

WIND:  Tropical storm conditions are occurring over portions of the
warning area for the Leeward Islands.  Tropical storm conditions are 
expected to begin spreading over the Virgin Islands and Puerto Rico 
by this evening.

STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level for the eastern coast of Puerto Rico
from San Juan to Guayama, including the islands of Culebra and
Vieques and in the U.S. Virgin Islands, including St. Thomas, St.
John, and St. Croix.

A storm surge will raise water levels by as much as 1 to 3 feet
above normal tide levels in the British Virgin Islands. Near the
coast, the surge will be accompanied by large and destructive waves.

SURF:  Swells generated by Ernesto are affecting portions of the 
Leeward Islands and Virgin Islands and will spread westward to 
Puerto Rico later today.  These swells will then reach the 
Dominican Republic tonight, the Turks and Caicos Islands and 
southeastern Bahamas on Wednesday, and Bermuda on Thursday.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Berg

