

016 
WTNT35 KNHC 140549
TCPAT5

BULLETIN
Tropical Storm Ernesto Intermediate Advisory Number 10A
NWS National Hurricane Center Miami FL       AL052024
200 AM AST Wed Aug 14 2024

...HEAVY RAIN AND STRONG WINDS FROM ERNESTO BEGINNING TO MOVE OVER 
PUERTO RICO...


SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...19.0N 66.0W
ABOUT 80 MI...130 KM NW OF ST. THOMAS
ABOUT 40 MI...65 KM N OF SAN JUAN PUERTO RICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 16 MPH...25 KM/H
MINIMUM CENTRAL PRESSURE...996 MB...29.41 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* U.S. Virgin Islands
* British Virgin Islands
* Vieques and Culebra

A Tropical Storm Warning is in effect for...
* British Virgin Islands
* U.S. Virgin Islands
* Puerto Rico
* Vieques and Culebra

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case through the early morning.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

Interests in Bermuda should monitor the progress of Ernesto.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Tropical Storm Ernesto was
located by San Juan radar near latitude 19.0 North, longitude 66.0 
West. Ernesto is moving toward the northwest near 16 mph (25 km/h). 
A turn toward the north-northwest and north with a gradual decrease 
in forward speed is expected tonight and Thursday. On the 
forecast track, the center of Ernesto will pass to the north of 
Puerto Rico through today. Ernesto should then move over the
western Atlantic later in the week and approach Bermuda on Friday
and Friday night.

Surface observations indicate that the maximum sustained winds have 
increased to near 70 mph (110 km/h) with higher gusts. Strengthening 
is forecast during the next several days, and Ernesto is expected 
to become a hurricane later this morning and could become a major 
hurricane in a couple of days. 

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center. A WeatherFlow station (XCUL) on Culebra recently
reported a sustained wind of 68 mph (109 km/h) and a gust of 86 mph
(139 km/h).  A NOAA Saildrone located about 70 miles north- 
northeast of San Juan, Puerto Rico, recently reported a sustained 
wind of 52 mph (84 km/h) with a gust to 63 mph (101 km/h).

The estimated minimum central pressure is 996 mb (29.41 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

RAINFALL: Ernesto is expected to produce total rain accumulations of
4 to 6 inches over the U.S and British Virgin Islands. Rainfall
totals of 6 to 8 inches, with maximum amounts of 10 inches, are
expected across southeastern Puerto Rico, with totals of 2 to 4
inches across northwestern Puerto Rico.

For a complete depiction of forecast rainfall associated with
Ernesto, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf

WIND: Tropical storm conditions will continue spreading across the
Virgin Islands, Puerto Rico, Vieques, and Culebra through the
overnight hours. Hurricane conditions are possible in portions of
the watch area during the next few hours.

STORM SURGE: A storm surge will raise water levels by as much as 1
to 3 feet above ground level for the eastern coast of Puerto Rico
from San Juan to Guayama, including the islands of Culebra and
Vieques and in the U.S. Virgin Islands, including St. Thomas, St.
John, and St. Croix.

A storm surge will raise water levels by as much as 1 to 3 feet
above normal tide levels in the British Virgin Islands. Near the
coast, the surge will be accompanied by large and destructive waves.

SURF: Swells generated by Ernesto are affecting portions of the
Leeward Islands, the Virgin Islands, Puerto Rico and the Dominican 
Republic. These swells will reach the Turks and Caicos Islands and 
southeastern Bahamas today, and Bermuda and the rest of the Bahamas 
on Thursday. Swells are expected to reach the east coast of the 
United States Thursday night and continue into the weekend. These 
swells are likely to cause life-threatening surf and rip current 
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Blake


