

000
WTNT35 KNHC 141152
TCPAT5

BULLETIN
Tropical Storm Ernesto Intermediate Advisory Number 11A
NWS National Hurricane Center Miami FL       AL052024
800 AM AST Wed Aug 14 2024

...FLOODING RAINS FROM ERNESTO CONTINUE ACROSS PUERTO RICO AND THE 
VIRGIN ISLANDS...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...19.8N 67.2W
ABOUT 125 MI...200 KM NW OF SAN JUAN PUERTO RICO
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NW OR 305 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.26 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Hurricane Watch has been discontinued for the British Virgin 
Islands.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* British Virgin Islands
* U.S. Virgin Islands
* Puerto Rico
* Vieques and Culebra

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in Bermuda should monitor the progress of Ernesto.

For storm information specific to your area in the United
States, including possible inland watches and warnings, please
monitor products issued by your local National Weather Service
forecast office. For storm information specific to your area
outside of the United States, please monitor products issued by
your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Ernesto was
located near latitude 19.8 North, longitude 67.2 West. Ernesto is
moving toward the northwest near 16 mph (26 km/h).  A turn toward
the north-northwest and north with a gradual decrease in forward
speed is expected tonight and Thursday. On the forecast track, the
center of Ernesto will move northward away from Puerto Rico through
today. Ernesto should then move over the western Atlantic later in
the week and be nearing Bermuda on Saturday.

Maximum sustained winds remain near 70 mph (110 km/h) with higher
gusts.  Ernesto is expected to become a hurricane later today and 
could become a major hurricane in a couple of days.

Tropical-storm-force winds extend outward up to 150 miles (240 km)
from the center.

The estimated minimum central pressure based on dropsonde data is 
991 mb (29.26 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

RAINFALL: Ernesto is expected to produce total rain accumulations of
4 to 6 inches over the U.S and British Virgin Islands. Rainfall
totals of 6 to 8 inches, with maximum amounts of 10 inches, are
expected across southeastern Puerto Rico, with totals of 2 to 4
inches across northwestern Puerto Rico.

For a complete depiction of forecast rainfall associated with
Ernesto, please see the National Weather Service Storm Total
Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf

WIND: Tropical storm conditions will continue across the Virgin
Islands, Puerto Rico, Vieques, and Culebra through the overnight
hours. Hurricane conditions are possible in portions of the watch
area during the next few hours.

STORM SURGE:  Minor coastal flooding remains possible in areas of
onshore winds along the eastern coast of Puerto Rico, including the
islands of Culebra and Vieques, and in the U.S. Virgin Islands,
including St. Thomas, St. John, and St. Croix.  For information
specific to your area, please see products issued by your local
National Weather Service forecast office.

SURF: Swells generated by Ernesto are affecting portions of the
Leeward Islands, the Virgin Islands, Puerto Rico and the Dominican
Republic. These swells will reach the Turks and Caicos Islands and
southeastern Bahamas today, and Bermuda and the rest of the Bahamas
on Thursday. Swells are expected to reach the east coast of the
United States Thursday night and continue into the weekend. These
swells are likely to cause life-threatening surf and rip current
conditions. Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Berg

