

000
WTNT35 KNHC 141749
TCPAT5

BULLETIN
Hurricane Ernesto Intermediate Advisory Number 12A
NWS National Hurricane Center Miami FL       AL052024
200 PM AST Wed Aug 14 2024

...FLASH FLOOD RISK CONTINUES OVER PORTIONS OF PUERTO RICO DUE TO 
ONGOING HEAVY RAINS...


SUMMARY OF 200 PM AST...1800 UTC...INFORMATION
----------------------------------------------
LOCATION...21.1N 68.0W
ABOUT 225 MI...365 KM NW OF SAN JUAN PUERTO RICO
ABOUT 805 MI...1295 KM SSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...989 MB...29.20 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Tropical Storm Warnings for Puerto Rico and the U.S. Virgin 
Islands have been discontinued.

The government of Antigua and Barbuda has discontinued the Tropical 
Storm Warning for the British Virgin Islands.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.

Interests in Bermuda should monitor the progress of Ernesto.  A
hurricane watch may be required for the island later today.


DISCUSSION AND OUTLOOK
----------------------
At 200 PM AST (1800 UTC), the center of Hurricane Ernesto was
located near latitude 21.1 North, longitude 68.0 West. Ernesto is
moving toward the northwest near 16 mph (26 km/h).  A turn toward
the north-northwest and north is expected later today and tonight,
with a generally northward motion at a slower forward speed
continuing through Saturday.  On the forecast track, the center of
Ernesto will continue to move away from Puerto Rico today, move
across the western Atlantic during the next few days, and approach
Bermuda Friday and Saturday.

Maximum sustained winds are near 75 mph (120 km/h) with higher 
gusts.  Strengthening is forecast during the next couple of days.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 230
miles (370 km).

The estimated minimum central pressure based on recent dropsonde 
data is 989 mb (29.20 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

RAINFALL: Tropical Storm Ernesto is expected to produce total rain
accumulations of 4 to 6 inches over the U.S and British Virgin
Islands. Rainfall totals of 6 to 8 inches, with maximum amounts of
10 inches, are expected across southeastern Puerto Rico, with totals
of 2 to 4 inches across northwestern Puerto Rico.

Rainfall associated with Ernesto may begin to affect Bermuda on
Thursday.

For a complete depiction of forecast rainfall associated with
Tropical Storm Ernesto, please see the National Weather Service
Storm Total Rainfall Graphic, available at
hurricanes.gov/graphics_at5.shtml?rainqpf

WIND: Gusty winds will continue across Puerto Rico and the Virgin 
Islands through rest of today.

SURF: Swells generated by Ernesto are affecting portions of the
Leeward Islands, the Virgin Islands, Puerto Rico, the Dominican
Republic, and the Turks and Caicos Islands.  These swells will
reach the southeastern Bahamas today, and Bermuda and the rest of
the Bahamas on Thursday.  Swells are expected to reach the east
coast of the United States Thursday night and continue into the
weekend. These swells are likely to cause life-threatening surf and
rip current conditions.  Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Berg

