

000
WTNT35 KNHC 142350
TCPAT5

BULLETIN
Hurricane Ernesto Intermediate Advisory Number 13A
NWS National Hurricane Center Miami FL       AL052024
800 PM AST Wed Aug 14 2024

...AIR FORCE HURRICANE HUNTERS FIND ERNESTO IS STRENGTHENING...
...HURRICANE WATCH IN EFFECT FOR BERMUDA...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...22.4N 68.7W
ABOUT 180 MI...290 KM ENE OF GRAND TURK ISLAND
ABOUT 720 MI...1160 KM SSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...981 MB...28.97 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bermuda

A Hurricane Watch means that hurricane conditions are possible 
within the watch area. A watch is typically issued 48 hours before 
the anticipated first occurrence of tropical-storm-force winds, 
conditions that make outside preparations difficult or dangerous.

For storm information specific to your area, please monitor products 
issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Hurricane Ernesto was
located near latitude 22.4 North, longitude 68.7 West. Ernesto is
moving toward the northwest near 16 mph (26 km/h). A turn toward
the north-northwest and north is expected tonight and on Thursday. A
northward to northeastward motion at a slower forward speed is
expected Friday and Saturday. On the forecast track, the center of
Ernesto is expected to pass near Bermuda on Saturday.

Data from Air Force Reserve Hurricane Hunter aircraft indicate that 
maximum sustained winds have increased to near 80 mph (130 km/h) 
with higher gusts. Strengthening is forecast during the next couple 
of days, and Ernesto could become a major hurricane by Friday.

Hurricane-force winds extend outward up to 35 miles (55 km) from
the center and tropical-storm-force winds extend outward up to 175
miles (280 km).

The estimated minimum central pressure is 981 mb (28.97 inches) 
based on Hurricane Hunter aircraft data.


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

WIND: Hurricane conditions are possible on Bermuda Saturday, with
tropical storm conditions possible by Friday afternoon.

RAINFALL: Ernesto is expected to produce total rain accumulations
of 3 to 6 inches on Bermuda with isolated maximum amounts of 9
inches. This rainfall may result in considerable life-threatening
flash flooding.

Rainfall is expected to diminish this evening across Puerto Rico and 
the U.S. and British Virgin Islands. Total rainfall amounts from 
Ernesto are expected to be in the 6 to 10 inch range, with maximum 
amounts of 12 inches across southern to eastern Puerto Rico, 3 to 6 
inches across northwestern Puerto Rico, and 4 to 6 inches across the 
U.S and British Virgin Islands.

For a complete depiction of forecast rainfall associated with 
Ernesto, please see the National Weather Service Storm Total 
Rainfall Graphic, available at 
hurricanes.gov/graphics_at5.shtml?rainqpf

SURF: Swells generated by Ernesto are affecting portions of the 
northern Leeward Islands, the Virgin Islands, Puerto Rico, the 
Dominican Republic, the Turks and Caicos Islands, and the 
southeastern Bahamas. These swells will spread toward Bermuda and 
the rest of the Bahamas on Thursday. Swells are expected to reach 
the east coast of the United States Thursday night and continue into 
the weekend. These swells are likely to cause life-threatening surf 
and rip current conditions. Please consult products from your local 
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Reinhart

