

000
WTNT35 KNHC 150548
TCPAT5

BULLETIN
Hurricane Ernesto Intermediate Advisory Number 14A
NWS National Hurricane Center Miami FL       AL052024
200 AM AST Thu Aug 15 2024

...SATELLITE IMAGERY INDICATES THAT ERNESTO IS GRADUALLY 
STRENGTHENING...


SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...23.3N 69.1W
ABOUT 180 MI...290 KM NE OF GRAND TURK ISLAND
ABOUT 675 MI...1085 KM SSW OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...979 MB...28.91 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Bermuda

A Hurricane Watch means that hurricane conditions are possible
within the watch area. A watch is typically issued 48 hours before
the anticipated first occurrence of tropical-storm-force winds,
conditions that make outside preparations difficult or dangerous.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Hurricane Ernesto was
located near latitude 23.3 North, longitude 69.1 West. Ernesto is
moving toward the north-northwest near 16 mph (26 km/h). A turn
toward the north is expected later today, followed by a slower
northward to northeastward motion on Friday and Saturday. On the
forecast track, the center of Ernesto is expected to pass near
Bermuda on Saturday.

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts. Strengthening is forecast during the next couple 
of days, and Ernesto could become a major hurricane by Friday.

Hurricane-force winds extend outward up to 45 miles (75 km) from
the center and tropical-storm-force winds extend outward up to 175
miles (280 km). NOAA buoy 41046, located about 40 miles north of 
Ernesto, recently reported a wind gust to 57 mph (91 km/h) and a 
minimum central pressure of 997.9 mb (29.47 inches).

The estimated minimum central pressure is 979 mb (28.91 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

WIND: Hurricane conditions are possible on Bermuda Saturday, with
tropical storm conditions possible by Friday afternoon.

RAINFALL: Ernesto is expected to produce total rain accumulations of
3 to 6 inches on Bermuda with isolated maximum amounts of 9 inches.
This rainfall may result in considerable life-threatening flash
flooding.

SURF: Swells generated by Ernesto are affecting portions of the
northern Leeward Islands, the Virgin Islands, Puerto Rico, the
Dominican Republic, the Turks and Caicos Islands, and the
southeastern Bahamas. These swells will spread toward Bermuda and
the rest of the Bahamas later today. Swells are expected to reach
the east coast of the United States tonight and continue into
the weekend. These swells are likely to cause life-threatening surf
and rip current conditions. Please consult products from your local
weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Blake

