

000
WTNT35 KNHC 171155
TCPAT5

BULLETIN
Hurricane Ernesto Intermediate Advisory Number 23A
NWS National Hurricane Center Miami FL       AL052024
800 AM AST Sat Aug 17 2024

...ERNESTO'S CENTER BEGINNING TO MOVE AWAY FROM BERMUDA AND WINDS 
HAVE PICKED BACK UP ON THE ISLAND...
...HAZARDOUS CONDITIONS WILL CONTINUE ON BERMUDA THROUGH THIS 
EVENING...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...32.6N 64.6W
ABOUT 15 MI...25 KM NNE OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNE OR 20 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...974 MB...28.76 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Bermuda

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area.

Interests in Atlantic Canada should monitor the progress of Ernesto.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Hurricane Ernesto was 
located near latitude 32.6 North, longitude 64.6 West. Ernesto is 
moving toward the north-northeast near 9 mph (15 km/h), and this 
general motion is expected today.  A faster northeastward motion is 
then expected late this weekend into early next week.  On the 
forecast track, the center of Ernesto is expected to slowly depart 
Bermuda today and move near or east of Newfoundland Monday night.

Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts.  Little change in strength is forecast today.  Some 
re-intensification is possible late in the weekend before weakening 
begins on Monday.

Ernesto is a large tropical cyclone. Hurricane-force winds extend
outward up to 70 miles (110 km) from the center and tropical-storm-
force winds extend outward up to 240 miles (390 km).

The estimated minimum central pressure based on dropsonde data is 
974 mb (28.76 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

WIND:  Hurricane conditions are expected on Bermuda through the
next several hours.  Due to Ernesto's large size and slow motion,
strong winds will continue on the island through most of today into 
this evening.

STORM SURGE: A dangerous storm surge is expected to produce
significant coastal flooding on Bermuda in areas of onshore winds.
Near the coast, the surge will be accompanied by large and
destructive waves.

RAINFALL: Ernesto is expected to produce total rain accumulations of
6 to 9 inches or 150 to 225 mm on Bermuda. This rainfall will likely
result in considerable life-threatening flash flooding, especially
in low-lying areas on the island.

SURF: Swells generated by Ernesto are affecting portions of the the
Bahamas, Bermuda, and the east coast of the United States. These
swells will likely reach portions of Atlantic Canada today.
Life-threatening surf and rip current conditions are likely in these
areas during the next couple of days.  Please consult products from
your local weather office, and stay out of the water if advised by
lifeguards.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Berg

