

000
WTNT35 KNHC 180237
TCPAT5

BULLETIN
Tropical Storm Ernesto Advisory Number  26
NWS National Hurricane Center Miami FL       AL052024
1100 PM AST Sat Aug 17 2024

...ERNESTO MOVING AWAY FROM BERMUDA BUT TROPICAL STORM CONDITIONS
EXPECTED FOR A FEW MORE HOURS...
...DANGEROUS BEACH CONDITIONS EXPECTED ALONG THE U.S. EAST COAST
THROUGH EARLY NEXT WEEK...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...33.9N 63.3W
ABOUT 140 MI...225 KM NE OF BERMUDA
ABOUT 1030 MI...1660 KM SW OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NNE OR 30 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Warning is in effect for...
* Bermuda

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area.

Interests in southeastern Newfoundland should monitor the progress
of Ernesto.  A watch may be required for a portion of this area on
Sunday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Ernesto was
located near latitude 33.9 North, longitude 63.3 West. Ernesto is
moving toward the north-northeast near 8 mph (13 km/h), and this 
general motion is expected to continue through tonight.  An 
acceleration toward the north-northeast is forecast to begin on 
Sunday, with a turn toward the northeast and east-northeast 
occurring on Monday and Tuesday.  On the forecast track, the center 
of Ernesto will move away from Bermuda tonight and pass near 
southeastern Newfoundland late Monday and Monday night.

Maximum sustained winds have decreased to near 70 mph (110 km/h) 
with higher gusts.  Little change in strength is expected tonight. 
Some intensification is possible Sunday and Sunday night, and 
Ernesto could regain hurricane status. The cyclone will likely 
become post-tropical near southeastern Newfoundland by Monday night 
or Tuesday morning.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 978 mb (28.88 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

WIND:  Tropical storm conditions are likely to continue on Bermuda
for the next few hours.

STORM SURGE:  Coastal flooding is still possible on Bermuda in areas
of onshore winds.  Near the coast, the surge will be accompanied by
large and destructive waves.

RAINFALL: Ernesto is expected to produce an additional 1 to 2 inches 
or 25 to 50 mm of rainfall through Saturday night across Bermuda, 
with storm total amounts of 7 to 9 inches (175 to 225 mm). This 
rainfall will likely result in considerable life-threatening flash 
flooding to the island.

SURF:  Swells generated by Ernesto are affecting portions of the
Bahamas, Bermuda, the east coast of the United States, and Atlantic
Canada today.  Life-threatening surf and rip current conditions are
likely in these areas during the next couple of days.  Please
consult products from your local weather office, and stay out of the
water if advised by lifeguards.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Beven

