

000
WTNT35 KNHC 180843
TCPAT5

BULLETIN
Tropical Storm Ernesto Advisory Number  27
NWS National Hurricane Center Miami FL       AL052024
500 AM AST Sun Aug 18 2024

...ERNESTO COULD RESTRENGTHEN SOME TODAY...
...DANGEROUS BEACH CONDITIONS EXPECTED ALONG THE U.S. EAST COAST
THROUGH DURING THE NEXT FEW DAYS...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...34.6N 63.0W
ABOUT 690 MI...1110 KM S OF HALIFAX NOVA SCOTIA
ABOUT 980 MI...1580 KM SW OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NNE OR 25 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...978 MB...28.88 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The Bermuda Weather Service has discontinued the Tropical Storm
Warning for Bermuda.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.

Interests in southeastern Newfoundland should monitor the progress
of Ernesto.  A watch may be required for a portion of this area
later today.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Tropical Storm Ernesto was 
located near latitude 34.6 North, longitude 63.0 West. Ernesto is 
moving toward the north-northeast near 9 mph (15 km/h),  and some 
increase in forward speed is forecast later today, followed by a 
turn toward the northeast and east-northeast on Monday and Tuesday. 
On the forecast track, the center of Ernesto will pass near 
southeastern Newfoundland late Monday and Monday night.

Maximum sustained winds are near 70 mph (110 km/h) with higher 
gusts.  Some re-intensification is possible later today, and Ernesto 
could regain hurricane status.  The cyclone will likely become 
post-tropical near southeastern Newfoundland by Monday night or 
Tuesday morning.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 978 mb (28.88 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

SURF:  Swells generated by Ernesto are affecting portions of the 
Bahamas, Bermuda, the east coast of the United States, and Atlantic 
Canada.  Life-threatening surf and rip current conditions are likely 
in these areas during the next couple of days.  Please consult 
products from your local weather office, and stay out of the water 
if advised by lifeguards.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Pasch

