

394 
WTNT35 KNHC 191447
TCPAT5

BULLETIN
Hurricane Ernesto Advisory Number  32
NWS National Hurricane Center Miami FL       AL052024
1100 AM AST Mon Aug 19 2024

...ERNESTO STRENGTHENS A LITTLE MORE...
...DANGEROUS BEACH CONDITIONS CONTINUING ALONG THE NORTHEAST
U.S. COAST AND ATLANTIC CANADA...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...41.8N 58.5W
ABOUT 320 MI...515 KM SE OF HALIFAX NOVA SCOTIA
ABOUT 430 MI...695 KM SW OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...90 MPH...150 KM/H
PRESENT MOVEMENT...NE OR 40 DEGREES AT 28 MPH...44 KM/H
MINIMUM CENTRAL PRESSURE...968 MB...28.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

There are no coastal watches or warnings in effect.

Interests in southeastern Newfoundland should monitor the progress
of Ernesto.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Ernesto was
located near latitude 41.8 North, longitude 58.5 West. Ernesto is
moving toward the northeast near 28 mph (44 km/h). A turn
toward the northeast and east-northeast with an increase in forward
speed is expected during the next couple of days.  On the forecast
track, the center of Ernesto will pass near southeastern
Newfoundland tonight and early Tuesday.

Maximum sustained winds are near 90 mph (150 km/h) with higher
gusts.  Weakening is forecast, and Ernesto is expected
to become a post-tropical cyclone by early Tuesday.

Hurricane-force winds extend outward up to 35 miles (55 km) from the
center and tropical-storm-force winds extend outward up to 220 miles
(350 km).

The estimated minimum central pressure is 968 mb (28.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Ernesto can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml.

SURF:  Swells generated by Ernesto are affecting Bermuda, the
northeast coast of the United States, and Atlantic Canada.
Life-threatening surf and rip current conditions are likely to
continue in these areas during the next day or so.  In southeastern
Newfoundland large breaking waves could bring the possibility of
coastal flooding, particularly along southwest-facing shorelines
from Burin east to Avalon regions.  Please consult products from
your local weather office, and stay out of the water if advised by
lifeguards.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi/Nepaul


