

000
WTNT35 KNHC 201436
TCPAT5

BULLETIN
Post-Tropical Cyclone Ernesto Advisory Number  36
NWS National Hurricane Center Miami FL       AL052024
300 PM GMT Tue Aug 20 2024

...ERNESTO BECOMES A POWERFUL POST-TROPICAL CYCLONE OVER THE NORTH
ATLANTIC...
...THIS IS THE LAST NHC ADVISORY...


SUMMARY OF 300 PM GMT...1500 UTC...INFORMATION
----------------------------------------------
LOCATION...49.0N 44.7W
ABOUT 420 MI...675 KM ENE OF CAPE RACE NEWFOUNDLAND
MAXIMUM SUSTAINED WINDS...70 MPH...110 KM/H
PRESENT MOVEMENT...NE OR 55 DEGREES AT 37 MPH...59 KM/H
MINIMUM CENTRAL PRESSURE...987 MB...29.15 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 300 PM GMT (1500 UTC), the center of Post-Tropical Cyclone 
Ernesto was located near latitude 49.0 North, longitude 44.7 West. 
The post-tropical cyclone is moving toward the northeast near 37 mph 
(59 km/h), and an even faster east-northeastward motion is expected 
during the next day or two.

Maximum sustained winds are near 70 mph (110 km/h) with higher 
gusts. Some weakening is expected tonight and on Wednesday, and 
post-tropical Ernesto is forecast to merge with a frontal system and 
dissipate by late Wednesday.

Tropical-storm-force winds extend outward up to 230 miles (370 km)
from the center.

The estimated minimum central pressure is 987 mb (29.15 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by post-tropical Ernesto are affecting the
northeast coast of the United States and Atlantic Canada. The swells
and associated life-threatening surf and rip current conditions
should gradually subside during the next day or so. Please consult
products from your local weather office, and stay out of the water
if advised by lifeguards.


NEXT ADVISORY
-------------
This is the last public advisory issued by the National Hurricane 
Center on Ernesto. Additional information on this system can be 
found in High Seas Forecasts issued by the National Weather Service, 
under AWIPS header NFDHSFAT1, WMO header FZNT01 KWBC, and online at 
ocean.weather.gov/shtml/NFDHSFAT1.php

$$
Forecaster Reinhart

