

312 
WTNT35 KNHC 190249
TCPAT5

BULLETIN
Tropical Storm Tammy Advisory Number   2
NWS National Hurricane Center Miami FL       AL202023
1100 PM AST Wed Oct 18 2023

...TAMMY STARTING TO SLOW DOWN...
...HEAVY RAINFALL EXPECTED FOR THE LESSER ANTILLES ON FRIDAY AND
SATURDAY...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.0N 53.1W
ABOUT 530 MI...855 KM E OF THE WINDWARD ISLANDS
MAXIMUM SUSTAINED WINDS...40 MPH...65 KM/H
PRESENT MOVEMENT...W OR 270 DEGREES AT 17 MPH...28 KM/H
MINIMUM CENTRAL PRESSURE...1006 MB...29.71 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Barbados
* Dominica
* Martinique and Guadeloupe

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings will likely be required later
tonight or on Thursday.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Tammy was 
located near latitude 13.0 North, longitude 53.1 West. Tammy is 
moving toward the west near 17 mph (28 km/h).  A westward motion 
with an additional slow down is expected on Thursday.  A turn toward 
the west-northwest is forecast by Thursday night, followed by a turn 
toward the northwest Friday night or Saturday.  On the forecast 
track, the center of Tammy will move near or over the Leeward 
Islands Friday and Saturday.

Maximum sustained winds are near 40 mph (65 km/h) with higher gusts. 
Additional strengthening is forecast during the next couple of days 
and Tammy could be near hurricane intensity by the end of the 
weekend. 

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 1006 mb (29.71 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are possible within the watch
area beginning on Friday.

RAINFALL:  Through Saturday night, Tammy is expected to produce
storm total rainfall of 3 to 6 inches, with maximum amounts of 10
inches, across portions of the northern Windward into the Leeward
Islands.  Rainfall totals of 1 to 2 inches with maximum amounts of
4 inches are expected for the British and U.S. Virgin Islands into
eastern Puerto Rico.  These rains may produce isolated flash and
urban flooding, along with isolated mudslides in areas of higher
terrain.

SURF:  Swells generated by Tammy will begin affecting portions of
the Lesser Antilles on Thursday.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 AM AST.
Next complete advisory at 500 AM AST.

$$
Forecaster Papin


