

000
WTNT35 KNHC 191201
TCPAT5

BULLETIN
Tropical Storm Tammy Special Advisory Number   4
NWS National Hurricane Center Miami FL       AL202023
800 AM AST Thu Oct 19 2023

...NOAA HURRICANE HUNTER AIRCRAFT FIND TAMMY STRONGER...
...TROPICAL STORM CONDITIONS AND HEAVY RAIN ARE POSSIBLE BEGINNING
FRIDAY...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...13.5N 55.1W
ABOUT 465 MI...745 KM ESE OF GUADELOUPE
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...W OR 280 DEGREES AT 16 MPH...26 KM/H
MINIMUM CENTRAL PRESSURE...1004 MB...29.65 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Netherlands has issued a Tropical Storm Watch for
Saba and St. Eustatius.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Tropical Storm Watch is in effect for...
* Barbados
* Dominica
* Martinique and Guadeloupe
* Antigua, Barbuda, Montserrat, St. Kitts, and Nevis
* Saba and St. Eustatius

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings will likely be required later
today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Tammy was
located near latitude 13.5 North, longitude 55.1 West. Tammy is
moving toward the west near 16 mph (26 km/h). A turn toward the
west-northwest is forecast by tonight, followed by a turn toward the
northwest Friday night or Saturday.  On the forecast track, the
center of Tammy will move near or over the Leeward Islands Friday
and Saturday.

Data from an a NOAA Hurricane Hunter aircraft indicate that 
the maximum sustained winds are near 60 mph (95 km/h) with higher 
gusts. Gradual strengthening is forecast during the next few days 
and Tammy could be near hurricane intensity by early Saturday.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 1004 mb (29.65 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are possible within the watch
area beginning on Friday.

RAINFALL:  Through Saturday night, Tammy is expected to produce
storm total rainfall of 3 to 6 inches, with maximum amounts of 10
inches, across portions of the northern Windward into the Leeward
Islands.  Rainfall totals of 1 to 2 inches with maximum amounts of
4 inches are expected for the British and U.S. Virgin Islands into
eastern Puerto Rico.  These rains may produce isolated flash and
urban flooding, along with isolated mudslides in areas of higher
terrain.

SURF:  Swells generated by Tammy will begin affecting portions of
the Lesser Antilles later today.  These swells are likely to cause
life-threatening surf and rip current conditions.  Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Brown

