

436 
WTNT35 KNHC 191451
TCPAT5

BULLETIN
Tropical Storm Tammy Advisory Number   5
NWS National Hurricane Center Miami FL       AL202023
1100 AM AST Thu Oct 19 2023

...NEW WATCHES AND WARNINGS ISSUED FOR PORTIONS OF THE LEEWARD 
ISLANDS...
...TROPICAL STORM CONDITIONS AND HEAVY RAIN ARE POSSIBLE BEGINNING
FRIDAY...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...13.6N 55.7W
ABOUT 425 MI...680 KM ESE OF GUADELOUPE
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 15 MPH...24 KM/H
MINIMUM CENTRAL PRESSURE...1003 MB...29.62 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua has issued a Tropical Storm Watch for
Anguilla and St. Barthelemy.

The government of St. Maarten has issued a Tropical Storm Watch
for St. Maarten.

The government of France has issued a Tropical Storm Warning and
Hurricane Watch for Guadeloupe, and a Tropical Storm Watch for St.
Martin.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Guadeloupe

A Tropical Storm Warning is in effect for...
* Guadeloupe

A Tropical Storm Watch is in effect for...
* Barbados
* Dominica
* Martinique
* Antigua, Barbuda, Montserrat, St. Kitts, Nevis, Anguilla, and St.
Barthelemy
* Saba and St. Eustatius
* St. Maarten
* St. Martin

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings will likely be required later
today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Tammy was
located near latitude 13.6 North, longitude 55.7 West. Tammy is
moving toward the west-northwest near 15 mph (24 km/h).  A slower 
west-northwest motion is expected through tonight.  A turn toward 
the northwest is forecast on Friday, and this motion should 
continue into the weekend.  On the forecast track, the center of 
Tammy will move near or over the Leeward Islands Friday and 
Saturday.

Maximum sustained winds are near 60 mph (95 km/h) with higher gusts. 
Gradual strengthening is expected during the next few days, and 
Tammy is forecast to be at or near hurricane intensity when it moves 
near the Leeward Islands. 

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The estimated minimum central pressure is 1003 mb (29.62 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected within the tropical 
storm warning area by late Friday.  Hurricane conditions are 
possible in portions of Leeward Islands Friday night and Saturday. 
Tropical storm conditions are possible within the tropical storm 
watch area beginning on Friday.

RAINFALL:  Through Sunday, Tammy is expected to produce storm total 
rainfall of 3 to 6 inches, with maximum amounts of 10 inches, across 
portions of the northern Windward and Leeward Islands.  Rainfall 
totals of 1 to 2 inches with maximum amounts of 4 inches are 
expected for the British and U.S. Virgin Islands into eastern Puerto 
Rico. These rains may produce isolated flash and urban flooding, 
along with isolated mudslides in areas of higher terrain. 

STORM SURGE:  Storm surge could raise water levels by as much as 1 
to 3 feet above normal tide levels near where the center of Tammy 
moves across the Leeward Islands.

SURF:  Swells generated by Tammy will begin affecting portions of 
the Lesser Antilles today, and will continue into the weekend.  
These swells are likely to cause life-threatening surf and rip 
current conditions.  Please consult products from your local weather 
office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Brown


