

000
WTNT35 KNHC 192054
TCPAT5

BULLETIN
Tropical Storm Tammy Advisory Number   6
NWS National Hurricane Center Miami FL       AL202023
500 PM AST Thu Oct 19 2023

...CENTER OF TAMMY EXPECTED TO APPROACH THE LEEWARD ISLANDS ON 
FRIDAY...
...TROPICAL STORM CONDITIONS AND HEAVY RAIN ARE EXPECTED IN
PORTIONS OF THE LEEWARD ISLANDS BEGINNING FRIDAY...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...13.7N 56.6W
ABOUT 200 MI...320 KM E OF BARBADOS
ABOUT 300 MI...485 KM ESE OF MARTINIQUE
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 13 MPH...20 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Dominica has issued a Tropical Storm Warning for
Dominica.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Guadeloupe
* Antigua, Barbuda, Montserrat, St. Kitts, and Nevis

A Tropical Storm Warning is in effect for...
* Dominica
* Guadeloupe
* Antigua, Barbuda, Montserrat, St. Kitts, and Nevis

A Tropical Storm Watch is in effect for...
* Barbados
* Martinique
* Anguilla
* St. Barthelemy
* Saba and St. Eustatius
* St. Maarten
* St. Martin

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings will likely be required tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Tropical Storm Tammy was
located near latitude 13.7 North, longitude 56.6 West. Tammy is
moving toward the west-northwest near 13 mph (20 km/h).  A slower 
west-northwestward motion is expected tonight.  A turn toward the 
northwest is forecast on Friday, and this motion should continue 
through Saturday.  A northward motion is forecast to begin Saturday 
night or Sunday.  On the forecast track, the center of Tammy will 
move near or over the Leeward Islands Friday and Saturday, and then 
move north of the Leeward Islands Saturday night and Sunday.

Data from an Air Force Reserve reconnaissance aircraft indicate that 
the maximum sustained winds are near 60 mph (95 km/h) with higher 
gusts. Little change in strength is expected tonight, but gradual 
strengthening is expected to begin on Friday and continue into this 
weekend. Tammy is forecast to be at or near hurricane intensity when 
it moves near the Leeward Islands Friday night and Saturday.

Tropical-storm-force winds extend outward up to 125 miles (205 km) 
primarily to the east of the center.

The latest minimum central pressure is estimated from reconnaissance 
aircraft data is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected within the tropical
storm warning area beginning Friday.  Hurricane conditions
are possible in portions of the Leeward Islands Friday night and
Saturday. Tropical storm conditions are possible within the tropical
storm watch area beginning on Friday.

RAINFALL:  Tammy is expected to produce storm total rainfall of 3 to
6 inches, with maximum amounts of 10 inches, across the Leeward and
northern Windward Islands. Rainfall totals of 1 to 2 inches with
maximum amounts of 4 inches are expected for the British and U.S.
Virgin Islands into eastern Puerto Rico. These rains may produce
isolated flash and urban flooding, along with isolated mudslides in
areas of higher terrain.

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 PM AST.
Next complete advisory at 1100 PM AST.

$$
Forecaster Brown

