
ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Tropical Storm Tammy Intermediate Advisory Number 6A
NWS National Hurricane Center Miami FL       AL202023
800 PM AST Thu Oct 19 2023

...TAMMY SLOWING DOWN AS IT APPROACHES THE LEEWARD ISLANDS...
...TROPICAL STORM CONDITIONS AND HEAVY RAIN ARE EXPECTED TO BEGIN ON 
FRIDAY FOR PORTIONS OF THE LEEWARD ISLANDS...


SUMMARY OF 800 PM AST...0000 UTC...INFORMATION
----------------------------------------------
LOCATION...13.7N 56.8W
ABOUT 190 MI...305 KM ENE OF BARBADOS
ABOUT 290 MI...470 KM ESE OF MARTINIQUE
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 10 MPH...16 KM/H
MINIMUM CENTRAL PRESSURE...1001 MB...29.56 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of Antigua has issued a Tropical Storm Warning and 
Hurricane Watch for Anguilla and St. Barthelemy.

The government of St. Maarten has issued a Tropical Storm Warning 
for St. Maarten.

The government of France has issued a Tropical Storm Warning for St. 
Martin.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Guadeloupe
* Antigua, Barbuda, Montserrat, St. Kitts, and Nevis
* Anguilla and St. Barthelemy

A Tropical Storm Warning is in effect for...
* Dominica
* Guadeloupe
* Antigua, Barbuda, Montserrat, St. Kitts, and Nevis
* Anguilla and St. Barthelemy
* St. Maarten
* St. Martin

A Tropical Storm Watch is in effect for...
* Barbados
* Martinique
* Saba and St. Eustatius

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings will likely be required tonight.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 PM AST (0000 UTC), the center of Tropical Storm Tammy was 
located near latitude 13.7 North, longitude 56.8 West. Tammy is 
moving toward the west-northwest near 10 mph (16 km/h).  A gradual 
turn to the northwest with some additional slowdown is forecast 
tonight into Friday, and this motion should continue through 
Saturday.  A more northward motion is forecast to begin Saturday 
night or Sunday.  On the forecast track, the center of Tammy will 
move near or over the Leeward Islands Friday and Saturday, and then 
move north of the Leeward Islands Saturday night and Sunday.

Data from both Air Force Reserve and NOAA reconnaissance aircraft 
indicate that the maximum sustained winds remain near 60 mph (95 
km/h) with higher gusts. Little change in strength is expected 
tonight, but gradual strengthening is expected to begin on Friday 
and continue into this weekend. Tammy is forecast to be at or near 
hurricane intensity when it moves near the Leeward Islands Friday 
night and Saturday.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
primarily to the east of the center.

The latest minimum central pressure is estimated from
reconnaissance aircraft data is 1001 mb (29.56 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected within the tropical
storm warning area beginning Friday.  Hurricane conditions
are possible in portions of the Leeward Islands Friday night and
Saturday. Tropical storm conditions are possible within the tropical
storm watch area beginning on Friday.

RAINFALL:  Tammy is expected to produce storm total rainfall of 3 to
6 inches, with maximum amounts of 10 inches, across the Leeward and
northern Windward Islands. Rainfall totals of 1 to 2 inches with
maximum amounts of 4 inches are expected for the British and U.S.
Virgin Islands into eastern Puerto Rico. These rains may produce
isolated flash and urban flooding, along with isolated mudslides in
areas of higher terrain.

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Papin

NNNN
