

000
WTNT35 KNHC 200555
TCPAT5

BULLETIN
Tropical Storm Tammy Intermediate Advisory Number 7A
NWS National Hurricane Center Miami FL       AL202023
200 AM AST Fri Oct 20 2023

...AIR FORCE RESERVE HURRICANE HUNTERS INVESTIGATING TAMMY...
...TROPICAL STORM CONDITIONS AND HEAVY RAIN EXPECTED TO BEGIN
LATER TODAY ACROSS PORTIONS OF THE LESSER ANTILLES...


SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...13.8N 58.0W
ABOUT 110 MI...175 KM ENE OF BARBADOS
ABOUT 210 MI...340 KM ESE OF MARTINIQUE
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...WNW OR 285 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...1002 MB...29.59 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Guadeloupe
* Antigua and Barbuda, Montserrat, St. Kitts and Nevis, and Anguilla
* St. Maarten
* St. Martin and St. Barthelemy

A Tropical Storm Warning is in effect for...
* Dominica
* Guadeloupe
* Antigua and Barbuda, Montserrat, St. Kitts and Nevis, and Anguilla
* St. Maarten
* St. Martin and St. Barthelemy

A Tropical Storm Watch is in effect for...
* Barbados
* Martinique
* Saba and St. Eustatius

A Hurricane Watch means that hurricane conditions are possible
within the watch area.  A watch is typically issued 48 hours
before the anticipated first occurrence of tropical-storm-force
winds, conditions that make outside preparations difficult or
dangerous.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings could be required tomorrow.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Tropical Storm Tammy was
located near latitude 13.8 North, longitude 58.0 West. Tammy is
moving toward the west-northwest near 10 mph (17 km/h). A gradual
turn to the northwest with a decrease in forward speed is forecast 
later today, and this motion should continue through Saturday.  A 
more northward motion is forecast to begin Saturday night or Sunday. 
On the forecast track, the center of Tammy will move near or over 
the Leeward Islands later today through Saturday, and then move 
north of the Leeward Islands Saturday night and Sunday.

Data collected so far by a Air Force Reserve Hurricane Hunter 
aircraft indicate that maximum sustained winds remain near 60 mph 
(95 km/h) with higher gusts.  Gradual strengthening is expected to 
begin later today and continue into this weekend.  Tammy is forecast 
to be at or near hurricane intensity when it moves near the Leeward 
Islands tonight and Saturday.

Tropical-storm-force winds extend outward up to 125 miles (205 km)
from the center.

The minimum central pressure based on dropsonde data is 1002 mb 
(29.59 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected within the tropical
storm warning area beginning later today.  Hurricane conditions
are possible in portions of the Leeward Islands tonight and
Saturday. Tropical storm conditions are possible within the tropical
storm watch area beginning later today.

RAINFALL: Tammy is expected to produce the following storm total
rainfall:

Leeward Islands: 4 to 8 inches with maximum amounts of 12 inches

Northern Windward Islands: 2 to 4 inches with maximum amounts of 6
inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2
inches with maximum amounts of 4 inches

These rains may produce isolated flash and urban flooding, along
with isolated mudslides in areas of higher terrain.

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Berg

