

000
WTNT35 KNHC 201157
TCPAT5

BULLETIN
Tropical Storm Tammy Intermediate Advisory Number 8A
NWS National Hurricane Center Miami FL       AL202023
800 AM AST Fri Oct 20 2023

...NOAA AND AIR FORCE RESERVE HURRICANE HUNTER AIRCRAFT FIND 
TAMMY SLIGHTLY STRONGER...


SUMMARY OF 800 AM AST...1200 UTC...INFORMATION
----------------------------------------------
LOCATION...14.0N 58.4W
ABOUT 90 MI...150 KM NE OF BARBADOS
ABOUT 180 MI...290 KM ESE OF MARTINIQUE
MAXIMUM SUSTAINED WINDS...65 MPH...100 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...1000 MB...29.53 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Watch is in effect for...
* Guadeloupe
* Antigua and Barbuda, Montserrat, St. Kitts and Nevis, and Anguilla
* St. Maarten
* St. Martin and St. Barthelemy

A Tropical Storm Warning is in effect for...
* Dominica
* Guadeloupe
* Antigua and Barbuda, Montserrat, St. Kitts and Nevis, and Anguilla
* St. Maarten
* St. Martin and St. Barthelemy
* Saba and St. Eustatius

A Tropical Storm Watch is in effect for...
* Barbados
* Martinique

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 to 48 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings could be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 800 AM AST (1200 UTC), the center of Tropical Storm Tammy was
located near latitude 14.0 North, longitude 58.4 West.  Tammy is
moving toward the west-northwest near 7 mph (11 km/h), and this
general motion is expected to continue through this afternoon.  A
turn toward the northwest is anticipated by this evening, followed
by a north-northwestward and northward turn Saturday night through
Sunday night.  On the forecast track, the center of Tammy will move
near or over portions of the Leeward Islands tonight and on
Saturday, and then move north of the northern Leeward Islands on
Sunday.

Data from both NOAA and Air Force Reserve Hurricane Hunter aircraft
indicate that maximum sustained winds have increased to near 65 mph 
(100 km/h) with higher gusts.  Gradual strengthening is forecast 
during the next few days, and Tammy is expected to be at or near 
hurricane intensity while it moves near or over portions of the 
Leeward Islands.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The minimum central pressure based on reconnaissance aircraft data 
is 1000 mb (29.53 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected within the tropical
storm warning area beginning later today and tonight.  Hurricane
conditions are possible in portions of the Leeward Islands on
Saturday.  Tropical storm conditions are possible within the
tropical storm watch area beginning later today.

RAINFALL: Tammy is expected to produce the following storm total
rainfall:

Leeward Islands: 4 to 8 inches with maximum amounts of 12 inches

Northern Windward Islands: 2 to 4 inches with maximum amounts of 6
inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2
inches with maximum amounts of 4 inches

These rains may produce isolated flash and urban flooding, along
with isolated mudslides in areas of higher terrain.

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Brown

