

481 
WTNT35 KNHC 201458
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number   9
NWS National Hurricane Center Miami FL       AL202023
1100 AM AST Fri Oct 20 2023

...TAMMY EXPECTED TO BRING HURRICANE CONDITIONS TO PORTIONS OF THE
LEEWARD ISLANDS LATE TONIGHT AND SATURDAY...
...HEAVY RAINFALL AND FLOODING LIKELY OVER MUCH OF THE LESSER
ANTILLES...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...14.1N 58.6W
ABOUT 165 MI...265 KM ESE OF MARTINIQUE
ABOUT 240 MI...385 KM SE OF GUADELOUPE
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...WNW OR 290 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of France has issued a Hurricane Warning for
Guadeloupe.

The government of Antigua has issued a Hurricane Warning for
Antigua, Barbuda, Montserrat, and St. Kitts and Nevis. 

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Guadeloupe
* Antigua, Barbuda, Montserrat, St. Kitts and Nevis 

A Hurricane Watch is in effect for...
* Anguilla
* St. Maarten
* St. Martin and St. Barthelemy

A Tropical Storm Warning is in effect for...
* Dominica
* Anguilla
* St. Maarten
* St. Martin and St. Barthelemy
* Saba and St. Eustatius

A Tropical Storm Watch is in effect for...
* Barbados
* Martinique

A Hurricane Watch means that hurricane conditions are possible
within the watch area, in this case within the next 24 to 36 hours.

A Tropical Storm Warning means that tropical storm conditions are
expected somewhere within the warning area within 36 hours.

A Tropical Storm Watch means that tropical storm conditions are
possible within the watch area, generally within 48 hours.

Additional watches and warnings could be required later today.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Tammy was located
near latitude 14.1 North, longitude 58.6 West. Tammy is moving
toward the west-northwest near 7 mph (11 km/h), and this general 
motion is expected to continue through this afternoon.  A turn 
toward the northwest is anticipated by this evening, followed
by a north-northwestward and northward turn Saturday night through
Sunday night.  On the forecast track, the center of Tammy will move
near or over portions of the Leeward Islands tonight and on
Saturday, and then move north of the northern Leeward Islands on
Sunday.

Data from NOAA and Air Force Reserve reconnaissance aircraft 
indicate that the maximum sustained winds are near 75 mph (120 
km/h) with higher gusts.  Gradual strengthening is forecast during 
the next couple of days, and Tammy is expected to be a hurricane 
while it moves near or over portions of the Leeward Islands.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).

The minimum central pressure estimated from reconnaissance aircraft 
data is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Tropical storm conditions are expected within the tropical
storm warning area beginning later today or tonight.  Hurricane 
conditions are expected in the hurricane warning area by late 
tonight or early Saturday.  Hurricane conditions are possible in 
the hurricane watch area in the Leeward Islands on Saturday.  
Tropical storm conditions are possible within the tropical storm 
watch area beginning later today.

RAINFALL: Tammy is expected to produce the following storm total 
rainfall:

Leeward Islands: 4 to 8 inches with maximum amounts of 12 inches

Northern Windward Islands: 2 to 4 inches with maximum amounts of 6 
inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2 
inches with maximum amounts of 4 inches

These rains may produce isolated flash and urban flooding, along 
with isolated mudslides in areas of higher terrain. 

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.  Near the coast, the surge will 
be accompanied by large and dangerous waves.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 200 PM AST.
Next complete advisory at 500 PM AST.

$$
Forecaster Brown


