

000
WTNT35 KNHC 220556
TCPAT5

BULLETIN
Hurricane Tammy Intermediate Advisory Number 15A
NWS National Hurricane Center Miami FL       AL202023
200 AM AST Sun Oct 22 2023

...TAMMY NOW NORTHWEST OF BARBUDA... 
...STRONG WINDS AND HEAVY RAINS OVER PORTIONS OF THE LEEWARD ISLANDS 
CONTINUE...


SUMMARY OF 200 AM AST...0600 UTC...INFORMATION
----------------------------------------------
LOCATION...17.9N 62.1W
ABOUT 30 MI...45 KM NW OF BARBUDA
ABOUT 60 MI...100 KM E OF ST. MARTIN
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 330 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

None.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Barbuda and Anguilla
* St. Maarten
* St. Martin and St. Barthelemy

A Tropical Storm Warning is in effect for...
* Saba and St. Eustatius

A Hurricane Warning means that hurricane conditions are expected 
somewhere within the warning area, in this case over the next few 
hours.

A Tropical Storm Warning means that tropical storm conditions are 
expected somewhere within the warning area, in this case over the 
next few hours. 

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 200 AM AST (0600 UTC), the center of Hurricane Tammy was located
near latitude 17.9 North, longitude 62.1 West. Tammy is moving
toward the north-northwest near 10 mph (17 km/h) and this general
motion is expected through today, followed by a turn toward the
north on Monday.  On the forecast track, the center of Tammy will
move north of the northern Leeward Islands by this afternoon.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts. Some slight strengthening is possible during the next couple
of days.

Hurricane-force winds extend outward up to 25 miles (35 km) from
the center and tropical-storm-force winds extend outward up to 125
miles (205 km).

The minimum central pressure estimated from Air Force Reserve 
reconnaissance aircraft observations is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Hurricane conditions are expected over portions of the 
northern Leeward Islands through this morning.  Tropical storm 
conditions are expected within the tropical storm warning areas 
through this morning.

RAINFALL: Tammy is expected to produce the following storm total
rainfall:

Leeward Islands: 4 to 8 inches with storm total maximum amounts of
12 inches

Martinique and Dominica: Additional 2 to 4 inches, storm total
maximum 6 inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2
inches with maximum storm total amounts of 4 inches

These rains may produce isolated flash and urban flooding, along
with isolated mudslides in areas of higher terrain.

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.  Near the coast, the surge will
be accompanied by large and dangerous waves.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Papin

