

000
WTNT35 KNHC 220851
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  16
NWS National Hurricane Center Miami FL       AL202023
500 AM AST Sun Oct 22 2023

...TINY CORE OF TAMMY TREKKING NORTH-NORTHWESTWARD...
...STRONG WINDS EXPECTED TO CONTINUE FOR A FEW MORE HOURS FOR THE
NORTHERNMOST LEEWARD ISLANDS...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...18.5N 62.3W
ABOUT 70 MI...115 KM NNW OF BARBUDA
ABOUT 55 MI...90 KM ENE OF ANGUILLA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
CHANGES WITH THIS ADVISORY:

The government of the Netherlands has discontinued the Tropical
Storm Warning for Saba and St. Eustatius.

SUMMARY OF WATCHES AND WARNINGS IN EFFECT:

A Hurricane Warning is in effect for...
* Barbuda and Anguilla
* St. Maarten
* St. Martin and St. Barthelemy

A Hurricane Warning means that hurricane conditions are expected
somewhere within the warning area, in this case over the next few
hours.

For storm information specific to your area, please monitor
products issued by your national meteorological service.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Tammy was located 
near latitude 18.5 North, longitude 62.3 West. Tammy is moving 
toward the north-northwest near 10 mph (17 km/h) and this general 
motion is expected through today, followed by a turn toward the 
north or north-northeast on Monday.  On the forecast track, the 
center of Tammy will move further away from the northernmost Leeward 
Islands later today.

Maximum sustained winds are near 85 mph (140 km/h) with higher 
gusts. Some strengthening is possible today followed by fluctuations 
in strength thereafter.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

WIND:  Hurricane conditions are expected over portions of the
northernmost Leeward Islands for the next few hours.

RAINFALL: Tammy is expected to produce the following storm total
rainfall:

Leeward Islands: 4 to 8 inches with storm total maximum amounts of
12 inches

Martinique and Dominica: An additional 2 to 4 inches, with storm
total maximum of 6 inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2
inches with maximum storm total amounts of 4 inches

These rains may produce isolated flash and urban flooding, along
with isolated mudslides in areas of higher terrain.

STORM SURGE:  Storm surge could raise water levels by as much as 1
to 3 feet above normal tide levels near where the center of Tammy
moves across the Leeward Islands.  Near the coast, the surge will
be accompanied by large and dangerous waves.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next intermediate advisory at 800 AM AST.
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin

