

000
WTNT35 KNHC 221434
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  17
NWS National Hurricane Center Miami FL       AL202023
1100 AM AST Sun Oct 22 2023

...TAMMY PULLING AWAY FROM THE NORTHERN LEEWARD ISLANDS...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...19.1N 63.0W
ABOUT 60 MI...100 KM N OF ANGUILLA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...NW OR 320 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...992 MB...29.30 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Tammy was located
near latitude 19.1 North, longitude 63.0 West. Tammy is moving
toward the northwest near 9 mph (15 km/h) and this general
motion is expected today.  A turn toward the north is expected
tonight, followed by a north-northeast or northeast motion on
Tuesday.

Maximum sustained winds are near 80 mph (130 km/h) with higher
gusts.  Little change in strength is forecast during the next few
days.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).

The estimated minimum central pressure is 992 mb (29.30 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

RAINFALL: Tammy is expected to produce the following storm total
rainfall:

Leeward Islands: 4 to 8 inches with storm total maximum amounts of
12 inches

Martinique and Dominica: Additional 2 to 4 inches, storm total
maximum 6 inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2
inches with maximum storm total amounts of 4 inches

These rains may produce isolated flash and urban flooding, along
with isolated mudslides in areas of higher terrain.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Cangialosi

