

000
WTNT35 KNHC 222034
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  18
NWS National Hurricane Center Miami FL       AL202023
500 PM AST Sun Oct 22 2023

...HEAVY RAINS LINGER ACROSS THE LEEWARD ISLANDS...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...19.9N 63.4W
ABOUT 120 MI...190 KM N OF ANGUILLA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...988 MB...29.18 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Tammy was located
near latitude 19.9 North, longitude 63.4 West.  Tammy is moving
toward the northwest near 9 mph (15 km/h).  A turn toward the north
is expected late tonight, followed by a north-northeast or
northeast motion on Monday and Tuesday.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Some slight strengthening is possible during the next few 
days.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The estimated minimum central pressure is 988 mb (29.18 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

RAINFALL: Tammy is expected to produce the following storm total
rainfall:

Leeward Islands: 4 to 8 inches with storm total maximum amounts of
12 inches

Martinique and Dominica: Additional 2 to 4 inches, storm total
maximum 6 inches

British and U.S. Virgin Islands into eastern Puerto Rico: 1 to 2
inches with maximum storm total amounts of 4 inches

These rains may produce isolated flash and urban flooding, along
with isolated mudslides in areas of higher terrain.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Cangialosi

