

000
WTNT35 KNHC 230236
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  19
NWS National Hurricane Center Miami FL       AL202023
1100 PM AST Sun Oct 22 2023

...HEAVY RAINS STILL LINGERING ACROSS THE LEEWARD ISLANDS...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...20.8N 64.0W
ABOUT 190 MI...305 KM NNW OF ANGUILLA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NW OR 325 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Tammy was located
near latitude 20.8 North, longitude 64.0 West.  Tammy is moving
toward the northwest near 9 mph (15 km/h).  A turn toward the
north is expected late tonight, followed by a north-northeast or
northeast motion on Monday and Tuesday.

Maximum sustained winds are near 85 mph (140 km/h) with higher
gusts.  Some slight strengthening is possible during the next 
couple of days.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 115 miles
(185 km).

The minimum central pressure estimated from NOAA Hurricane Hunter 
aircraft observations is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

RAINFALL: Tammy is expected to produce an additional 1 to 3 inches
of rainfall across portions of the British Virgin Islands, the
Leeward Islands, and the northern Windward Islands into Monday
morning, bringing storm total maximum amounts to 12 inches in the
Leeward Islands.  These rains may produce isolated flash and urban
flooding, along with isolated mudslides in areas of higher terrain.

SURF:  Swells generated by Tammy will continue to affect portions of
the Lesser Antilles during the next few days.  These swells are
likely to cause life-threatening surf and rip current conditions.
Please consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Pasch

