
ZCZC MIATCPAT5 ALL
TTAA00 KNHC DDHHMM

BULLETIN
Hurricane Tammy Advisory Number  20
NWS National Hurricane Center Miami FL       AL202023
500 AM AST Mon Oct 23 2023

...TAMMY TURNING NORTHWARD...
...HEAVY RAINS STILL OCCURING OVER PARTS OF THE LEEWARD ISLANDS...


SUMMARY OF 500 AM AST...0900 UTC...INFORMATION
----------------------------------------------
LOCATION...21.4N 64.0W
ABOUT 230 MI...370 KM NNW OF ANGUILLA
MAXIMUM SUSTAINED WINDS...80 MPH...130 KM/H
PRESENT MOVEMENT...N OR 355 DEGREES AT 10 MPH...17 KM/H
MINIMUM CENTRAL PRESSURE...993 MB...29.33 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 AM AST (0900 UTC), the center of Hurricane Tammy was located 
near latitude 21.4 North, longitude 64.0 West. Tammy is now moving 
toward the north near 10 mph (17 km/h). A turn toward the 
north-northeast or northeast is expected to begin later today 
and continue into Tuesday.

Maximum sustained winds are near 80 mph (130 km/h) with higher 
gusts. Some slight strengthening is possible during the next couple 
of days followed by weakening. 

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).

The estimated minimum central pressure is 993 mb (29.33 inches).


HAZARDS AFFECTING LAND
----------------------
Key messages for Tammy can be found in the Tropical Cyclone
Discussion under AWIPS header MIATCDAT5 and WMO header WTNT45 KNHC
and on the web at hurricanes.gov/text/MIATCDAT5.shtml

RAINFALL: Tammy is expected to produce an additional 1 to 3 inches 
of rainfall across portions of the British Virgin Islands, the 
Leeward Islands, and the northern Windward Islands through this 
morning, bringing storm total maximum amounts to 12 inches in the 
Leeward Islands.  These rains may produce isolated flash and urban 
flooding, along with isolated mudslides in areas of higher terrain.

SURF:  Swells generated by Tammy will continue to affect portions of 
the Leeward Islands, the British and U.S. Virgin Islands, and Puerto 
Rico during the next few days.  These swells are likely to cause 
life-threatening surf and rip current conditions. Please consult 
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 AM AST.

$$
Forecaster Papin

NNNN
