

117 
WTNT35 KNHC 232039
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  22
NWS National Hurricane Center Miami FL       AL202023
500 PM AST Mon Oct 23 2023

...TAMMY TURNING NORTH-NORTHEASTWARD...


SUMMARY OF 500 PM AST...2100 UTC...INFORMATION
----------------------------------------------
LOCATION...22.3N 63.6W
ABOUT 695 MI...1115 KM S OF BERMUDA
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NNE OR 15 DEGREES AT 7 MPH...11 KM/H
MINIMUM CENTRAL PRESSURE...990 MB...29.24 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 500 PM AST (2100 UTC), the center of Hurricane Tammy was located
near latitude 22.3 North, longitude 63.6 West. Tammy is moving
toward the north-northeast near 7 mph (11 km/h).  A turn toward the
northeast is expected to by Tuesday and this general motion should
continue through Wednesday.  On Thursday a turn back toward the
north and north-northwest is forecast.

Maximum sustained winds are near 75 mph (120 km/h) with higher
gusts.  Some slight strengthening is possible during the next day or
so followed by steady weakening.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 125 miles
(205 km).

The estimated minimum central pressure based on recent NOAA 
Saildrone data is 990 mb (29.24 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Tammy will continue to affect portions of
the Leeward Islands, the British and U.S. Virgin Islands, and Puerto
Rico during the next few days.  These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 1100 PM AST.

$$
Forecaster Bucci


