

000
WTNT35 KNHC 241441
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  25
NWS National Hurricane Center Miami FL       AL202023
1100 AM AST Tue Oct 24 2023

...HURRICANE TAMMY HOLDS STEADY WHILE MOVING NORTHEASTWARD OVER
SOUTHWESTERN ATLANTIC...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.2N 62.3W
ABOUT 580 MI...935 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...75 MPH...120 KM/H
PRESENT MOVEMENT...NE OR 35 DEGREES AT 8 MPH...13 KM/H
MINIMUM CENTRAL PRESSURE...987 MB...29.15 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Hurricane Tammy was located
near latitude 24.2 North, longitude 62.3 West. Tammy is moving
toward the northeast near 8 mph (13 km/h), and this general motion
is expected to continue through Wednesday. A turn toward the north
at a slower forward speed is forecast to begin on Thursday, 
followed by a bend to the northwest on Friday.

Maximum sustained winds are near 75 mph (120 km/h) with higher
gusts.  Slight strengthening is possible during the next day or so 
followed by steady weakening. Tammy is forecast to become a
post-tropical cyclone on Thursday.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 140 miles
(220 km).

The estimated minimum central pressure is 987 mb (29.15 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Tammy will continue to affect portions of
the Leeward Islands, the British and U.S. Virgin Islands, and Puerto
Rico during the next few days. These swells are likely to cause
life-threatening surf and rip current conditions. Please consult
products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Bucci

