

141 
WTNT35 KNHC 250237
TCPAT5

BULLETIN
Hurricane Tammy Advisory Number  27
NWS National Hurricane Center Miami FL       AL202023
1100 PM AST Tue Oct 24 2023

...TAMMY STRENGTHENS OVER OPEN WATERS...
...FORECAST TO BECOME A POWERFUL EXTRATROPICAL CYCLONE BY
THURSDAY...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...24.9N 60.7W
ABOUT 570 MI...915 KM SSE OF BERMUDA
MAXIMUM SUSTAINED WINDS...85 MPH...140 KM/H
PRESENT MOVEMENT...NE OR 50 DEGREES AT 9 MPH...15 KM/H
MINIMUM CENTRAL PRESSURE...976 MB...28.82 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Hurricane Tammy was located 
near latitude 24.9 North, longitude 60.7 West. Tammy is moving 
toward the northeast near 9 mph (15 km/h). A northward turn is 
expected on Wednesday, followed by a slower northwestward motion on 
Thursday and Friday.

Maximum sustained winds have increased to near 85 mph (140 km/h) 
with higher gusts. Some additional strengthening is possible through 
early Wednesday, followed by weakening through late this week. Tammy 
is forecast to become a powerful post-tropical cyclone by Thursday.

Hurricane-force winds extend outward up to 25 miles (35 km) from the
center and tropical-storm-force winds extend outward up to 175 miles
(280 km).

The estimated minimum central pressure is 976 mb (28.82 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Tammy will continue to affect portions of
the Leeward Islands, the British and U.S. Virgin Islands, and Puerto
Rico during the next couple of days. These swells are likely to
cause life-threatening surf and rip current conditions. Please
consult products from your local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Reinhart


