

388 
WTNT35 KNHC 280235
TCPAT5

BULLETIN
Tropical Storm Tammy Advisory Number  35
NWS National Hurricane Center Miami FL       AL202023
1100 PM AST Fri Oct 27 2023

...SHEARED TAMMY WILL MOVE AWAY FROM BERMUDA TONIGHT...


SUMMARY OF 1100 PM AST...0300 UTC...INFORMATION
-----------------------------------------------
LOCATION...32.7N 61.3W
ABOUT 205 MI...330 KM E OF BERMUDA
MAXIMUM SUSTAINED WINDS...60 MPH...95 KM/H
PRESENT MOVEMENT...NNW OR 335 DEGREES AT 5 MPH...7 KM/H
MINIMUM CENTRAL PRESSURE...991 MB...29.27 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 PM AST (0300 UTC), the center of Tropical Storm Tammy was 
located near latitude 32.7 North, longitude 61.3 West. Tammy is 
moving toward the north-northwest near 5 mph (7 km/h). A turn toward 
the north and northeast is expected through early Saturday, followed 
by a faster eastward to east-southeastward motion on Sunday and 
Monday. On the forecast track, Tammy will move away from Bermuda on 
Saturday.

Maximum sustained winds have decreased to near 60 mph (95 km/h) with 
higher gusts. Weakening is expected during the next few days, and 
Tammy is forecast to become a post-tropical remnant low early next 
week.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 991 mb (29.27 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Tammy will continue to affect Bermuda
through Saturday. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 AM AST.

$$
Forecaster Reinhart


