

576 
WTNT35 KNHC 281448
TCPAT5

BULLETIN
Tropical Storm Tammy Advisory Number  37
NWS National Hurricane Center Miami FL       AL202023
1100 AM AST Sat Oct 28 2023

...TAMMY TURNING EASTWARD AND EXPECTED TO WEAKEN...


SUMMARY OF 1100 AM AST...1500 UTC...INFORMATION
-----------------------------------------------
LOCATION...33.3N 58.7W
ABOUT 360 MI...580 KM ENE OF BERMUDA
MAXIMUM SUSTAINED WINDS...50 MPH...85 KM/H
PRESENT MOVEMENT...E OR 80 DEGREES AT 12 MPH...19 KM/H
MINIMUM CENTRAL PRESSURE...995 MB...29.39 INCHES


WATCHES AND WARNINGS
--------------------
There are no coastal watches or warnings in effect.


DISCUSSION AND OUTLOOK
----------------------
At 1100 AM AST (1500 UTC), the center of Tropical Storm Tammy was
located near latitude 33.3 North, longitude 58.7 West. Tammy is
moving toward the east near 12 mph (19 km/h), and this motion is
expected to continue today, followed by a turn to the southeast
tonight. Early next week, Tammy is forecast to turn southward and
eventually southwestward as a remnant low.

Maximum sustained winds are near 50 mph (85 km/h) with higher gusts.
Some weakening is forecast during the next 48 hours, and Tammy is
forecast to become a post-tropical remnant low early next week.

Tropical-storm-force winds extend outward up to 140 miles (220 km)
from the center.

The estimated minimum central pressure is 995 mb (29.39 inches).


HAZARDS AFFECTING LAND
----------------------
SURF:  Swells generated by Tammy will continue to affect Bermuda
through today. These swells are likely to cause life-threatening
surf and rip current conditions. Please consult products from your
local weather office.


NEXT ADVISORY
-------------
Next complete advisory at 500 PM AST.

$$
Forecaster Hogsett/Blake


